import Link from 'next/link';
import {requireSession} from '@/core/auth/session';
import {can} from '@/core/permissions/check';
import {HR_CAPABILITIES as HR} from '@/core/permissions/capabilities';
import {db} from '@/core/db/client';
import {hrPageRestriction,hrAccess,employeeOptions,pageNumber,personSelect} from '@/modules/people/services/platform-queries';
import {assuranceState} from '@/modules/people/domain/platform';
import {RegisterForm} from '@/modules/people/components/register-form';
import {HRRestricted,HRHeading,panelClass,inputClass,Pager} from '@/modules/people/components/platform-ui';
import {Button} from '@/components/ui/button';
export default async function Training({searchParams}:{searchParams:Promise<{q?:string;view?:string;page?:string;employeeId?:string}>}){const session=await requireSession();const restriction=await hrPageRestriction(session,false);if(restriction)return <HRRestricted disabled={restriction==='disabled'}/>;await hrAccess(session);const filters=await searchParams,query=(filters.q??'').trim().slice(0,100),page=pageNumber(filters.page),manage=can(session,HR.employeeManage),today=new Date(new Date().toISOString().slice(0,10)+'T00:00:00Z'),soon=new Date(today.getTime()+30*86400000);
 const where={organisationId:session.organisationId,...(filters.employeeId?{employeeId:filters.employeeId}:{}),...(query?{OR:[{title:{contains:query,mode:'insensitive' as const}},{employee:{OR:[{firstName:{contains:query,mode:'insensitive' as const}},{lastName:{contains:query,mode:'insensitive' as const}}]}}]}:{}),...(filters.view==='renewal'?{status:'COMPLETED',expiresOn:{lte:soon},employee:{organisationId:session.organisationId,status:{not:'LEFT' as const}}}:filters.view==='overdue'?{status:{in:['PLANNED','IN_PROGRESS']},dueOn:{lt:today},employee:{organisationId:session.organisationId,status:{not:'LEFT' as const}}}:filters.view==='required'?{required:true}:filters.view==='completed'?{status:'COMPLETED'}:{})};
 const [records,employees,total]=await Promise.all([db.employeeTraining.findMany({where,include:{employee:{select:personSelect}},orderBy:[{dueOn:'asc'},{createdAt:'desc'}],skip:(page-1)*25,take:26}),manage?employeeOptions(session):[],db.employeeTraining.count({where})]);
 return <div className="min-w-0 space-y-6 break-words"><HRHeading title="Training & qualifications" description="Assign development, record actual completion and track renewals against the employee record."/><form className={`${panelClass} flex flex-wrap items-end gap-3`}><label className="min-w-0 flex-1 text-sm">Search training or employee<input className={inputClass} name="q" defaultValue={query}/></label>{filters.employeeId&&<input type="hidden" name="employeeId" value={filters.employeeId}/>}<label className="text-sm">Show<select name="view" className={inputClass} defaultValue={filters.view??''}><option value="">All training</option><option value="overdue">Overdue</option><option value="renewal">Expired / expires in 30 days</option><option value="required">Required training</option><option value="completed">Completed</option></select></label><Button type="submit">Filter</Button><Link href="/people/training">Clear</Link></form>
 {manage&&<details className={panelClass}><summary className="cursor-pointer font-medium">Assign training or qualification</summary><RegisterForm kind="training" employees={employees} employeeId={filters.employeeId}/></details>}
 <p className="text-sm text-slate-500">{total} records · 25 per page. Recorded completion is evidence held by HR, not automatic certification.</p>
 {records.slice(0,25).map(r=><article key={r.id} className={panelClass}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{r.title}</h3><Link className="text-sm text-[var(--color-atlas-blue)]" href={`/people/${r.employeeId}`}>{r.employee.firstName} {r.employee.lastName}</Link><p className="mt-1 text-xs text-slate-500">{r.category}{r.provider?` · ${r.provider}`:''}{r.required?' · Required':''}</p></div><span className="text-sm font-medium">{assuranceState(r)}</span></div><p className="mt-3 text-sm">Due: {r.dueOn?.toLocaleDateString('en-GB')??'Not set'} · Completed: {r.completedOn?.toLocaleDateString('en-GB')??'Not yet'} · Renewal: {r.expiresOn?.toLocaleDateString('en-GB')??'Not set'}</p>{r.notes&&<p className="mt-2 whitespace-pre-wrap break-words text-sm text-slate-600">{r.notes}</p>}{r.evidenceUrl&&<a className="mt-2 inline-block text-sm text-[var(--color-atlas-blue)]" href={r.evidenceUrl} target="_blank" rel="noreferrer">Open evidence ↗</a>}{manage&&<details className="mt-3"><summary className="cursor-pointer text-sm">Update training record</summary><RegisterForm kind="training" employees={[r.employee]} record={r}/></details>}</article>)}
 {!records.length&&<p className={panelClass}>No training matches these filters. Assign a course or qualification to start tracking.</p>}<Pager page={page} more={records.length>25} href={`/people/training?q=${encodeURIComponent(query)}&view=${encodeURIComponent(filters.view??'')}${filters.employeeId?`&employeeId=${encodeURIComponent(filters.employeeId)}`:''}`}/></div>;
}
