import { requireSession } from "@/core/auth/session";
import { assertCapability } from "@/core/permissions/check";
import { getFinanceConfiguration, saveFinanceAccount, saveFinanceDimension, saveFinanceEntityDetails, createFinancePeriod, setFinancePeriodExceptions, requestFinancePeriodReopen, decideFinancePeriodReopen } from "@/modules/finance/services/configuration";
import { setFinancePeriodState } from "@/modules/finance/services/commands";
import { ACCOUNT_TYPES, POSTING_PROFILES, DIMENSIONS } from "@/modules/finance/domain/accounting";
import type { FinanceAccount } from "@/generated/prisma/client";
import { ActionForm } from "@/modules/finance/components/action-form";
import { FinanceWorkspace, FinanceEntities, financeField as field, financeSection as section } from "@/modules/finance/components/workspace";
import Link from "next/link";

function AccountFields({ account, accounts, entityId }: { account?: FinanceAccount; accounts: FinanceAccount[]; entityId: string }) {
  const rules = account?.dimensionRules as Record<string, string> | undefined;
  return <><input type="hidden" name="entityId" value={entityId}/><input type="hidden" name="id" value={account?.id ?? ""}/>
    <div className="grid gap-3 sm:grid-cols-3">
      <label className="text-xs">Account code<input name="code" className={field} required defaultValue={account?.code}/></label>
      <label className="text-xs">Name<input name="name" className={field} required defaultValue={account?.name}/></label>
      <label className="text-xs">Account type<select name="type" className={field} defaultValue={account?.type}>{ACCOUNT_TYPES.map(type => <option key={type}>{type}</option>)}</select></label>
      <label className="text-xs">Statement category / subtype<input name="subType" className={field} defaultValue={account?.subType ?? ""} placeholder="e.g. Cost of sales"/></label>
      <label className="text-xs">Posting profile<select name="control" className={field} defaultValue={account?.control ?? ""}><option value="">Ordinary account</option>{Object.keys(POSTING_PROFILES).map(profile => <option key={profile}>{profile}</option>)}</select></label>
      <label className="text-xs">Restricted currency<input name="currencyRestriction" className={field} defaultValue={account?.currencyRestriction ?? ""} placeholder="Optional, e.g. EUR"/></label>
      <label className="text-xs">Parent group<select name="parentId" className={field} defaultValue={account?.parentId ?? ""}><option value="">No parent</option>{accounts.filter(row => !row.postingAllowed && row.id !== account?.id).map(row => <option key={row.id} value={row.id}>{row.code} · {row.name}</option>)}</select></label>
      <label className="text-xs sm:col-span-2">Description<input name="description" className={field} defaultValue={account?.description ?? ""}/></label>
    </div><div className="grid gap-3 sm:grid-cols-4">{DIMENSIONS.map(dimension => <label className="text-xs" key={dimension}>{dimension === "projectId" ? "Project" : dimension}<select name={dimension} className={field} defaultValue={rules?.[dimension] ?? "OPTIONAL"}><option>OPTIONAL</option><option>REQUIRED</option><option>PROHIBITED</option></select></label>)}</div>
    <div className="flex flex-wrap gap-5 text-sm"><label><input name="active" type="checkbox" defaultChecked={account?.active ?? true}/> Active</label><label><input name="postingAllowed" type="checkbox" defaultChecked={account?.postingAllowed ?? true}/> Allow posting</label></div></>;
}

export default async function FinanceSettings({ searchParams }: { searchParams: Promise<{ entity?: string }> }) {
  const session = await requireSession();
  assertCapability(session, "finance.configure");
  const filter = await searchParams, data = await getFinanceConfiguration(filter.entity), entity = data.entity;
  return <FinanceWorkspace title="Finance settings" description="Legal entities, chart of accounts, posting profiles, dimensions and financial periods. Changes apply to future accounting; posted history is retained.">
    <FinanceEntities entities={data.entities} selected={entity?.id} path="/finance/settings"/>
    {!entity ? <p className="text-sm">Set up the first books from <Link className="text-blue-700" href="/finance">Finance overview</Link>.</p> : <>
      <section className={section}><h2 className="text-lg font-semibold">Legal entity</h2><ActionForm action={saveFinanceEntityDetails} label="Save legal entity"><input type="hidden" name="entityId" value={entity.id}/><div className="grid gap-3 sm:grid-cols-3">{[{ key: "name", label: "Legal name", value: entity.name }, { key: "registrationNumber", label: "Registration number", value: entity.registrationNumber }, { key: "vatNumber", label: "Tax / VAT number", value: entity.vatNumber }, { key: "country", label: "Country code", value: entity.country }].map(item => <label className="text-xs" key={item.key}>{item.label}<input name={item.key} className={field} defaultValue={item.value ?? ""} required={item.key === "name"}/></label>)}<label className="text-xs">Fiscal year starts in month<input name="fiscalStartMonth" type="number" min="1" max="12" className={field} defaultValue={entity.fiscalStartMonth}/></label><label className="text-xs">PO invoice price tolerance (basis points)<input name="matchToleranceBps" type="number" min="0" max="10000" className={field} defaultValue={entity.matchToleranceBps}/></label><p className="self-center text-sm">Base currency: <strong>{entity.currency}</strong></p><label className="text-xs sm:col-span-3">Registered address<textarea name="registeredAddress" className={field} defaultValue={entity.registeredAddress ?? ""}/></label></div><p className="text-xs text-slate-500">Fiscal start month is a planning default. It does not change existing period dates. Sites remain operational locations within a legal entity.</p></ActionForm></section>
      <section className={section}><h2 className="text-lg font-semibold">Chart of accounts and posting profiles</h2><p className="text-sm text-slate-500">Profiles choose the account used by the posting engine. Configure FX_GAIN, FX_LOSS and ROUNDING before foreign-currency settlement. Account type, profile and currency cannot be changed after transactions exist.</p>
        <div className="divide-y divide-slate-100">{data.accounts.map(account => <details key={account.id} className="py-3"><summary className="cursor-pointer text-sm"><span className="inline-block w-24 font-mono">{account.code}</span><span className="font-medium">{account.name}</span><span className="ml-3 text-xs text-slate-500">{account.type} · {account.control ?? (account.postingAllowed ? "Posting account" : "Group")}{!account.active ? " · Inactive" : ""}</span></summary><ActionForm action={saveFinanceAccount} className="mt-4" label="Save account"><AccountFields account={account} accounts={data.accounts} entityId={entity.id}/></ActionForm></details>)}</div>
        <details className="border-t border-slate-200 pt-4"><summary className="cursor-pointer text-sm font-medium text-blue-700">Create account or group</summary><ActionForm action={saveFinanceAccount} className="mt-4" label="Create account"><AccountFields accounts={data.accounts} entityId={entity.id}/></ActionForm></details>
      </section>
      <section className={section}><h2 className="text-lg font-semibold">Financial dimension values</h2><p className="text-sm text-slate-500">Department and cost centre codes belong to these books. Once configured, postings must use an active configured code. Site and project dimensions refer to Atlas’s existing sites and authorised projects.</p><div className="divide-y divide-slate-100">{data.dimensions.map(value => <p key={value.id} className="py-2 text-sm">{value.dimension} · <strong>{value.code}</strong> · {value.name}{!value.active ? " · Inactive" : ""}</p>)}</div><ActionForm action={saveFinanceDimension} label="Save dimension value"><input type="hidden" name="entityId" value={entity.id}/><div className="grid gap-3 sm:grid-cols-3"><label className="text-xs">Dimension<select name="dimension" className={field}><option value="department">Department</option><option value="costCentre">Cost centre</option></select></label><label className="text-xs">Stable code<input name="code" className={field} required/></label><label className="text-xs">Name<input name="name" className={field} required/></label></div><label className="text-sm"><input name="active" type="checkbox" defaultChecked/> Active (use the same code to rename or deactivate)</label></ActionForm></section>
      {session.capabilities.has("finance.period.manage") && <section className={section}><h2 className="text-lg font-semibold">Periods and controlled reopening</h2><p className="text-sm text-slate-500">Periods cannot overlap. On hold allows only explicitly configured source types. Closed periods require independent approval to reopen; locked periods remain final. Create a PERIOD_REOPEN route in the <Link className="text-blue-700" href="/finance/control">Control centre</Link> before requesting reopening.</p>
        {data.periods.map(period => <details key={period.id} className="border-b border-slate-100 py-3"><summary className="cursor-pointer text-sm font-medium">{period.name} · {period.state} <span className="ml-3 font-normal text-slate-500">{period.startAt.toISOString().slice(0, 10)} to {period.endAt.toISOString().slice(0, 10)}</span></summary><p className="mt-2 text-xs text-slate-500">On-hold exceptions: {period.allowedSources.join(", ") || "None"}</p>{["OPEN", "SOFT_CLOSED"].includes(period.state) && <details className="mt-4"><summary className="cursor-pointer text-xs text-blue-700">Configure on-hold source exceptions</summary><ActionForm className="mt-3" action={setFinancePeriodExceptions} label="Save period exceptions"><input type="hidden" name="periodId" value={period.id}/><div className="grid gap-2 text-xs sm:grid-cols-3">{["AP_INVOICE", "AR_INVOICE", "AP_CREDIT", "AR_CREDIT", "AP_DEBIT", "AR_DEBIT", "RECEIPT", "BANK", "DEPRECIATION", "REVERSAL", "EXPENSE"].map(source => <label key={source}><input type="checkbox" name="allowedSources" value={source} defaultChecked={period.allowedSources.includes(source)}/> {source}</label>)}</div><input name="reason" className={field} required minLength={5} placeholder="Reason for these source exceptions"/></ActionForm></details>}{period.state !== "LOCKED" && <ActionForm className="mt-4" action={setFinancePeriodState.bind(null, period.id)} label="Apply period control"><select name="state" className={field}><option value="SOFT_CLOSED">On hold</option><option value="CLOSED">Closed</option><option value="LOCKED">Locked permanently</option></select><input name="reason" className={field} minLength={5} required placeholder="Reason for closing / holding"/></ActionForm>}{["SOFT_CLOSED", "CLOSED"].includes(period.state) && <ActionForm className="mt-4" action={requestFinancePeriodReopen} label="Request independent reopening"><input type="hidden" name="periodId" value={period.id}/><input name="reason" className={field} minLength={5} required placeholder="Why does this period need to reopen?"/></ActionForm>}</details>)}
        <details><summary className="cursor-pointer text-sm font-medium text-blue-700">Add the next financial period</summary><ActionForm className="mt-4" action={createFinancePeriod} label="Create period and close checklist"><input type="hidden" name="entityId" value={entity.id}/><input name="name" className={field} required placeholder="Period name"/><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs">Start<input name="startAt" type="date" className={field} required/></label><label className="text-xs">End<input name="endAt" type="date" className={field} required/></label></div></ActionForm></details>
        {session.capabilities.has("finance.approval.decide") && data.reopenings.map(approval => <ActionForm key={approval.id} action={decideFinancePeriodReopen} label="Record reopening decision"><input type="hidden" name="approvalId" value={approval.id}/><p className="text-sm">Reopening: {data.periods.find(period => period.id === approval.subjectId)?.name} · Stage {approval.currentStage + 1}</p><select name="decision" className={field}><option>APPROVED</option><option>REJECTED</option></select><input name="reason" className={field} required minLength={5} placeholder="Independent review reason"/></ActionForm>)}
      </section>}
    </>}
  </FinanceWorkspace>;
}
