'use client';
import { useRef,useState } from 'react';
import { ActionForm } from '@/components/ui/action-form';
import { Button } from '@/components/ui/button';
import { createProductionPlan,addProductionPlanLine,getPlanOptions } from '../services/plans';
const input='mt-1.5 block w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm';
function presetEnd(start:string,preset:string){const d=new Date(`${start}T00:00:00Z`);if(!Number.isFinite(d.getTime()))return start;if(preset==='YEAR')d.setUTCFullYear(d.getUTCFullYear()+1);else if(preset==='MONTH')d.setUTCMonth(d.getUTCMonth()+1);else d.setUTCDate(d.getUTCDate()+7);d.setUTCDate(d.getUTCDate()-1);return d.toISOString().slice(0,10);}
export function NewPlanForm({today}:{today:string}) {
 const [preset,setPreset]=useState('YEAR'),[start,setStart]=useState(today),[end,setEnd]=useState(presetEnd(today,'YEAR'));
 const key=useRef<string|null>(null);
 async function submit(form:FormData){key.current??=crypto.randomUUID();form.set('requestKey',key.current);await createProductionPlan(form);key.current=null;}
 return <ActionForm action={submit} className="space-y-4"><label className="block text-xs font-medium">Plan name<input name="name" required maxLength={150} placeholder="2027 production plan" className={input}/></label><label className="block text-xs font-medium">Horizon<select value={preset} onChange={e=>{setPreset(e.target.value);if(e.target.value!=='CUSTOM')setEnd(presetEnd(start,e.target.value));}} className={input}><option value="YEAR">One year</option><option value="MONTH">One month</option><option value="WEEK">One week</option><option value="CUSTOM">Custom dates</option></select></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-xs font-medium">Starts<input name="startsOn" type="date" required value={start} onChange={e=>{setStart(e.target.value);if(preset!=='CUSTOM')setEnd(presetEnd(e.target.value,preset));}} className={input}/></label><label className="block text-xs font-medium">Ends<input name="endsOn" type="date" required value={end} min={start} onChange={e=>{setPreset('CUSTOM');setEnd(e.target.value);}} className={input}/></label></div><label className="block text-xs font-medium">Planning interval<select name="bucket" defaultValue="MONTH" className={input}><option value="DAY">Daily</option><option value="WEEK">Weekly</option><option value="MONTH">Monthly</option><option value="QUARTER">Quarterly</option><option value="YEAR">Yearly</option></select></label><p className="text-xs leading-5 text-slate-500">Save product targets for any period. Plan lines remain intentions until validated production orders can be created.</p><Button type="submit" variant="primary">Create plan</Button></ActionForm>;
}
export function PlanLineForm({plan,options}:{plan:{id:string;version:number;startsOn:string;endsOn:string;bucket:string};options:Awaited<ReturnType<typeof getPlanOptions>>}) {
 const key=useRef<string|null>(null),[teamId,setTeamId]=useState(''),[member,setMember]=useState('');
 const team=options.teams.find(t=>t.id===teamId);
 const members=options.memberships.filter(m=>!team||team.members.some(tm=>tm.membershipId===m.id));
 async function submit(form:FormData){key.current??=crypto.randomUUID();form.set('requestKey',key.current);await addProductionPlanLine(form);key.current=null;}
 return <ActionForm action={submit} className="space-y-4"><input type="hidden" name="planId" value={plan.id}/><input type="hidden" name="version" value={plan.version}/><input type="hidden" name="bucket" value={plan.bucket}/><label className="block text-xs font-medium">Product<select name="productId" required className={input}><option value="">Choose a product</option>{options.products.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name} ({p.unitOfMeasure})</option>)}</select></label><label className="block text-xs font-medium">Planned quantity<input name="quantity" type="number" min="0.000001" step="0.000001" required className={input}/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-xs font-medium">Work starts<input name="startsOn" type="date" min={plan.startsOn} max={plan.endsOn} defaultValue={plan.startsOn} required className={input}/></label><label className="block text-xs font-medium">Work ends<input name="endsOn" type="date" min={plan.startsOn} max={plan.endsOn} defaultValue={plan.endsOn} required className={input}/></label></div><div className="grid gap-4 sm:grid-cols-2"><label className="block text-xs font-medium">Team<select name="teamId" value={teamId} onChange={e=>{setTeamId(e.target.value);setMember('');}} className={input}><option value="">Unassigned</option>{options.teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="block text-xs font-medium">Responsible person<select name="assignedMembershipId" value={member} onChange={e=>setMember(e.target.value)} className={input}><option value="">Unassigned</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label></div><label className="block text-xs font-medium">Work notes<textarea name="notes" maxLength={2000} rows={3} className={input}/></label><Button type="submit" variant="primary">Add planned work</Button></ActionForm>;
}
