import { ExportMenu } from '@/components/ui/export-menu';
import Link from 'next/link';
import { requireSession } from '@/core/auth/session';
import { assertCapability } from '@/core/permissions/check';
import { assertModuleEnabled } from '@/core/modules/access';
import { db } from '@/core/db/client';
import { DataTable } from '@/components/ui/table';
import { can } from '@/core/permissions/check';
import { ActionForm } from '@/components/ui/action-form';
import { Button } from '@/components/ui/button';
import { placeLabel } from '@/modules/stock/domain/places';
import { receiveMoveAction } from '../actions';
export default async function MovementsPage({searchParams}:{searchParams:Promise<{q?:string;warehouse?:string;direction?:string;page?:string}>}) {
 const session=await requireSession();assertCapability(session,'stock.read');await assertModuleEnabled(session,'stock');
 const filters=await searchParams;
 const q=typeof filters.q==='string'?filters.q.trim():'';
 const warehouse=typeof filters.warehouse==='string'?filters.warehouse:'';
 const direction=filters.direction==='in'?'in':filters.direction==='out'?'out':'';
 const page=Math.max(1,Math.min(10000,Number.parseInt(String(filters.page??'1'),10)||1));
 const where={organisationId:session.organisationId,...(warehouse?{warehouseId:warehouse}:{}),...(direction?{delta:direction==='in'?{gt:0}:{lt:0}}:{}),...(q?{OR:[{reference:{contains:q,mode:'insensitive' as const}},{reason:{contains:q,mode:'insensitive' as const}},{product:{name:{contains:q,mode:'insensitive' as const}}},{product:{code:{contains:q,mode:'insensitive' as const}}}]}:{})};
 const [rows,count,warehouses,transit]=await Promise.all([db.inventoryMovement.findMany({where,include:{product:{select:{id:true,code:true,name:true,unitOfMeasure:true}},warehouse:{select:{name:true}}},orderBy:[{createdAt:'desc'},{id:'desc'}],take:50,skip:(page-1)*50}),db.inventoryMovement.count({where}),db.warehouse.findMany({where:{organisationId:session.organisationId},orderBy:{name:'asc'}}),db.internalMove.findMany({where:{organisationId:session.organisationId,status:'IN_TRANSIT'},include:{product:{select:{code:true,name:true,unitOfMeasure:true}},fromWarehouse:{include:{site:true}},toWarehouse:{include:{site:true}}},orderBy:{createdAt:'desc'},take:30})]);
 function href(next:number){const params=new URLSearchParams({q,warehouse,direction,page:String(next)});return `/stock/movements?${params}`;}
 return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-semibold tracking-tight">Movement ledger</h2><p className="mt-1 text-sm text-slate-500">Every receipt, issue, adjustment and transfer, with its reason and reference. A move between sites stays here until the destination receives it.</p></div><ExportMenu href={`/api/stock/export?${new URLSearchParams({type:'movements',q,warehouse,direction})}`}/></div>{!!transit.length&&<div className="space-y-3 rounded-2xl border border-amber-200 bg-amber-50 p-4">{transit.map(move=><div key={move.id} className="flex flex-wrap items-center justify-between gap-3 text-sm"><p><span className="font-medium">{move.product.name}</span> · {move.quantity.toLocaleString('en-GB')} {move.product.unitOfMeasure} · {move.reference}<span className="mt-1 block text-xs text-amber-900">In transit from {placeLabel({code:move.fromWarehouse.code,name:move.fromWarehouse.name,kind:move.fromWarehouse.kind,siteName:move.fromWarehouse.site?.name})} to {placeLabel({code:move.toWarehouse.code,name:move.toWarehouse.name,kind:move.toWarehouse.kind,siteName:move.toWarehouse.site?.name})}</span></p>{can(session,'stock.manage')&&<ActionForm action={receiveMoveAction}><input type="hidden" name="moveId" value={move.id}/><Button type="submit" variant="primary">Receive</Button></ActionForm>}</div>)}</div>}<form className="flex flex-wrap items-end gap-3 rounded-2xl border border-slate-200 bg-white p-4"><label className="min-w-48 flex-1 text-xs text-slate-500">Search<input name="q" defaultValue={q} placeholder="SKU, reason or reference" className="mt-1.5 block w-full rounded-xl border border-slate-200 px-3 py-2 text-sm"/></label><label className="text-xs text-slate-500">Warehouse<select name="warehouse" defaultValue={warehouse} className="mt-1.5 block rounded-xl border border-slate-200 px-3 py-2 text-sm"><option value="">All warehouses</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label className="text-xs text-slate-500">Direction<select name="direction" defaultValue={direction} className="mt-1.5 block rounded-xl border border-slate-200 px-3 py-2 text-sm"><option value="">All movements</option><option value="in">Stock in</option><option value="out">Stock out</option></select></label><button className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-medium text-white">Apply</button><Link href="/stock/movements" className="px-2 py-2 text-sm text-slate-500">Reset</Link></form><DataTable rows={rows} getHref={m=>`/stock/items/${m.productId}`} emptyLabel="No movements match this view." columns={[
 {header:'Product',render:m=><div><p className="font-medium">{m.product.name}</p><p className="mt-1 text-xs text-slate-400">{m.product.code}</p></div>},
 {header:'Recorded',render:m=>m.createdAt.toLocaleString('en-GB',{timeZone:'Europe/London',dateStyle:'short',timeStyle:'short'})},
 {header:'Warehouse',render:m=>m.warehouse.name},
 {header:'Change',align:'right',render:m=><span className={m.delta>0?'text-emerald-700':'text-slate-700'}>{m.delta>0?'+':''}{m.delta} {m.product.unitOfMeasure}</span>},
 {header:'Reason',render:m=>m.reason},{header:'Reference',render:m=>m.reference||'—'},
 ]}/><div className="flex items-center justify-between text-xs text-slate-500"><p>{count.toLocaleString('en-GB')} movements · Page {page} of {Math.max(1,Math.ceil(count/50))}</p><div className="flex gap-4">{page>1&&<Link href={href(page-1)}>← Previous</Link>}{page*50<count&&<Link href={href(page+1)}>Next →</Link>}</div></div></div>;
}
