import { db } from "@/core/db/client";
import type { AnalyticsProvider } from "@/core/analytics/types";
import { assertCapability } from "@/core/permissions/check";
export const peopleAnalytics: AnalyticsProvider = [{
 id:"people.headcount", name:"Active employees", subject:"HR", definition:"Current active employee headcount by department. No salary, health or personal fields are returned.", grain:"One employee", capability:"people.employee.read", href:"/people", snapshot:true,
 query:async(session)=>{assertCapability(session,"people.employee.read");const rows=await db.employee.groupBy({by:["department"],where:{organisationId:session.organisationId,status:"ACTIVE"},_count:{_all:true}});return rows.map(r=>({label:r.department??"Unassigned",value:r._count._all}));}
},
{id:"people.employment",name:"Employee lifecycle",subject:"HR",definition:"Current employee count by employment status. No salary or personal information.",grain:"One employee",capability:"people.employee.read",href:"/people",snapshot:true,query:async(session)=>{assertCapability(session,"people.employee.read");const rows=await db.employee.groupBy({by:["status"],where:{organisationId:session.organisationId},_count:{_all:true}});return rows.map(r=>({label:r.status.replaceAll("_"," "),value:r._count._all}));}},
{id:"people.appraisals",name:"Appraisal reviews",subject:"HR",definition:"Appraisals scheduled in the selected period by completion status. Review content and ratings are excluded.",grain:"One appraisal",capability:"people.appraisal.read",href:"/people/appraisals",snapshot:false,query:async(session,since)=>{assertCapability(session,"people.appraisal.read");const rows=await db.appraisal.groupBy({by:["status"],where:{organisationId:session.organisationId,scheduledAt:since?{gte:since,lte:new Date()}:undefined},_count:{_all:true}});return rows.map(r=>({label:r.status,value:r._count._all}));}},
{id:"people.oneToOnes",name:"One-to-one meetings",subject:"HR",definition:"One-to-ones scheduled in the selected period by status. Meeting content is excluded.",grain:"One meeting",capability:"people.one_to_one.read",href:"/people/one-to-ones",snapshot:false,query:async(session,since)=>{assertCapability(session,"people.one_to_one.read");const rows=await db.oneToOne.groupBy({by:["status"],where:{organisationId:session.organisationId,scheduledAt:since?{gte:since,lte:new Date()}:undefined},_count:{_all:true}});return rows.map(r=>({label:r.status,value:r._count._all}));}},
{id:"people.absence.status",name:"Time off requests",subject:"HR",definition:"Current absence requests by decision status. Counts requests. Reasons, notes and medical detail are excluded.",grain:"One absence request",capability:"people.absence.read",href:"/people/absence",snapshot:true,query:async(session)=>{assertCapability(session,"people.absence.read");const rows=await db.absenceRecord.groupBy({by:["status"],where:{organisationId:session.organisationId},_count:{_all:true}});return rows.map(r=>({label:String(r.status).replaceAll("_"," "),value:r._count._all}));}},
];
