"use client";
import Link from "next/link";
import { startTransition, useActionState, useState } from "react";
import { useRouter } from "next/navigation";
import { Cable, Download, FileCheck2, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { ConnectionTemplate } from "@/modules/connections/domain/catalogue";
import { attachConnection } from "./actions";
type Company = { id: string; name: string; status: string };
type History = { id: string; section: string; date: string; details: { rows: string; fileName: string } };
export function ConnectionsWorkspace({ companies, selectedCompany, templates, history }: { companies: Company[]; selectedCompany: string; templates: ConnectionTemplate[]; history: History[] }) {
  const [entity, setEntity] = useState(templates[0].id);
  const [search, setSearch] = useState("");
  const router = useRouter();
  const selected = templates.find(template => template.id === entity)!;
  const company = companies.find(company => company.id === selectedCompany);
  return <div className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-5 rounded-2xl bg-slate-900 p-6 text-white sm:p-8">
      <div className="max-w-2xl"><Cable className="mb-4 text-blue-300" size={26} /><p className="text-xs font-medium uppercase tracking-widest text-blue-200">Atlas staff · Company onboarding</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Connections</h2><p className="mt-3 text-sm leading-6 text-slate-300">Bring a company into Atlas. Download a template, upload the completed file, select its company and attach the validated records.</p></div>
      <div className="rounded-xl border border-white/15 p-4 text-sm"><p className="font-medium">{templates.length} ready-to-use templates</p><p className="mt-2 text-slate-300">Customers · Sales · Products · Stock</p><p className="mt-1 text-slate-300">People · Machines & work centres</p></div>
    </header>
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Find a company<input type="search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search company names…" className="mt-2 block w-full rounded-lg border border-slate-200 px-3 py-2 font-normal" /></label><label className="text-sm font-medium">Attach records to<select aria-label="Attach records to company" value={selectedCompany} onChange={event => router.push(event.target.value ? `/atlas/connections?company=${encodeURIComponent(event.target.value)}` : "/atlas/connections")} className="mt-2 block w-full rounded-lg border border-slate-200 px-3 py-2 font-normal"><option value="">Select a company…</option>{companies.filter(item => item.id === selectedCompany || item.name.toLowerCase().includes(search.toLowerCase())).map(item => <option key={item.id} value={item.id}>{item.name}{item.status === "SUSPENDED" ? " (suspended)" : ""}</option>)}</select></label></div>{company && <div className="mt-4 flex flex-wrap items-center justify-between gap-2 text-sm"><p>Destination: <strong>{company.name}</strong>. Imports affect this company only.</p><Link className="text-blue-600" href={`/atlas/${company.id}/setup`}>Company setup →</Link></div>}{!companies.length && <p className="mt-3 text-sm text-slate-500">Create a company in Atlas Admin to get started.</p>}</section>
    <nav aria-label="Connection sections" className="flex flex-wrap gap-2">{templates.map(template => <button type="button" key={template.id} aria-pressed={entity === template.id} onClick={() => setEntity(template.id)} className={`rounded-lg border px-3 py-2 text-sm ${entity === template.id ? "border-blue-600 bg-blue-600 text-white" : "border-slate-200 bg-white text-slate-600 hover:border-blue-300"}`}>{template.title}</button>)}</nav>
    <ConnectionUpload key={`${selectedCompany}:${entity}`} template={selected} company={company} templates={templates} />
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">Company import history</h3><Button type="button" onClick={() => router.refresh()}>Refresh history</Button></div><p className="mt-2 text-xs text-slate-500">Latest 30 successful imports for the selected company. Files with validation errors make no changes.</p>{!history.length ? <p className="py-6 text-sm text-slate-500">{company ? "No imports recorded for this company yet." : "Select a company to see its imports."}</p> : <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="text-xs text-slate-500">{["Section", "File", "Rows", "Imported at"].map(title => <th className="p-2 font-medium" key={title}>{title}</th>)}</tr></thead><tbody>{history.map(item => <tr key={item.id} className="border-t border-slate-100"><td className="p-2 font-medium">{item.section}</td><td className="p-2">{item.details.fileName}</td><td className="p-2">{item.details.rows}</td><td className="p-2">{new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/London" }).format(new Date(item.date))}</td></tr>)}</tbody></table></div>}</section>
  </div>;
}
function ConnectionUpload({ template, company, templates }: { template: ConnectionTemplate; company?: Company; templates: ConnectionTemplate[] }) {
  const [state, action, pending] = useActionState(attachConnection, { error: "", message: "", token: "", preview: [] });
  const [dirty, setDirty] = useState(true);
  const [acknowledge, setAcknowledge] = useState(false);
  return <section className="grid gap-6 rounded-2xl border border-slate-200 bg-white p-5 lg:grid-cols-[minmax(0,1fr)_minmax(20rem,1fr)] sm:p-7">
    <div><p className="text-xs font-medium uppercase tracking-widest text-blue-600">{template.group}</p><h3 className="mt-2 text-2xl font-semibold tracking-tight">{template.title}</h3><p className="mt-2 text-sm text-slate-500">{template.summary}</p><a href={`/api/atlas/connections/template?entity=${template.id}`} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-blue-50 px-4 py-2.5 text-sm font-medium text-blue-700"><Download size={16} />Download CSV template</a><p className="mt-3 text-xs text-slate-500">The template includes one example row. Replace it with your own records.</p>{template.dependsOn.length > 0 && <p className="mt-5 text-sm"><strong>Import first: </strong>{template.dependsOn.map(id => templates.find(item => item.id === id)?.title ?? id).join(", ")}</p>}<p className="mt-5 text-sm font-medium">{template.behaviour}</p><ul className="mt-3 list-disc space-y-2 pl-4 text-xs leading-5 text-slate-500">{template.notes.map(note => <li key={note}>{note}</li>)}</ul><details className="mt-5 rounded-xl bg-slate-50 p-4"><summary className="cursor-pointer text-sm font-medium">Template columns & required fields</summary><div className="mt-3 flex flex-wrap gap-2">{template.columns.map(column => <span key={column} className="rounded bg-white px-2 py-1 font-mono text-xs">{column}{template.required.includes(column) ? " *" : ""}</span>)}</div><p className="mt-3 text-xs text-slate-500">* Required in every row.</p></details></div>
    <form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); const button = (event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement | null; data.set("mode", button?.value ?? "preview"); setDirty(false); startTransition(() => action(data)); }} className="min-w-0 space-y-4">
      <input type="hidden" name="organisationId" value={company?.id ?? ""} /><input type="hidden" name="entity" value={template.id} /><input type="hidden" name="token" value={state.token} />
      <fieldset disabled={pending} className="space-y-4"><label className="block rounded-xl border border-dashed border-slate-300 bg-slate-50 p-5 text-sm font-medium"><Upload size={20} className="mb-3 text-blue-600" />Upload {template.title.toLowerCase()}<input required name="file" type="file" accept=".csv,text/csv" onChange={() => { setDirty(true); setAcknowledge(false); }} className="mt-3 block w-full text-sm font-normal" /><span className="mt-3 block text-xs font-normal text-slate-500">Up to 500 rows · 2 MB · CSV</span></label>
      <p className="text-sm">{company ? <>Selected company: <strong>{company.name}</strong></> : "Select a company above to validate and attach your file."}</p>
      <Button type="submit" name="mode" value="preview" disabled={!company || pending}><FileCheck2 size={16} />Validate & preview</Button>
      {!dirty && state.preview.length > 0 && <><label className="flex items-start gap-2 rounded-lg bg-amber-50 p-3 text-xs leading-5 text-amber-900"><input type="checkbox" name="acknowledge" value="yes" checked={acknowledge} onChange={event => setAcknowledge(event.target.checked)} className="mt-1" /><span>I reviewed the preview and import rules. Attach these records to <strong>{company?.name}</strong>.</span></label><Button type="submit" variant="primary" name="mode" value="apply" disabled={!acknowledge || !state.token || pending}>Attach to {company?.name}</Button></>}
      </fieldset>
      {pending && <p role="status" className="text-sm text-blue-700">Processing your file…</p>}{!dirty && state.error && <p role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{state.error}</p>}{!dirty && state.message && <p role="status" className="rounded-lg bg-blue-50 p-3 text-sm text-blue-800">{state.message}</p>}
      {!dirty && state.preview.length > 0 && <div className="overflow-x-auto rounded-xl border border-slate-200"><p className="bg-slate-50 p-3 text-xs text-slate-500">Preview · First {state.preview.length} records · All rows validated</p><table className="w-full text-left text-xs"><thead><tr>{Object.keys(state.preview[0]).map(key => <th key={key} className="whitespace-nowrap p-2 font-medium">{key}</th>)}</tr></thead><tbody>{state.preview.map((row, index) => <tr key={index}>{Object.entries(row).map(([key, value]) => <td key={key} className="max-w-60 truncate border-t border-slate-100 p-2" title={value}>{value}</td>)}</tr>)}</tbody></table></div>}
    </form>
  </section>;
}
