import Link from "next/link";
import { requireSession } from "@/core/auth/session";
import { assertCapability } from "@/core/permissions/check";
import { getFinanceReconciliation, importFinanceStatementForm, financeReconciliationForm } from "@/modules/finance/services/banking";
import { money, digits } from "@/modules/finance/domain/money";
import { ActionForm } from "@/modules/finance/components/action-form";
import { ReconciliationEditor } from "@/modules/finance/components/reconciliation-editor";
import { FinanceWorkspace, FinanceEntities, FinancePagination, financeField as field, financeSection as section } from "@/modules/finance/components/workspace";

export default async function Reconcile({ searchParams }: { searchParams: Promise<{ entity?: string; bank?: string; status?: string; page?: string; transaction?: string; q?: string }> }) {
  const session = await requireSession();
  assertCapability(session, "finance.bank.read");
  const filter = await searchParams, page = Number(filter.page || 0), data = await getFinanceReconciliation({ entityId: filter.entity, bankId: filter.bank, page, status: filter.status || "UNRECONCILED", query: filter.q, transactionId: filter.transaction }), entity = data.entity;
  const query = new URLSearchParams({ entity: entity?.id ?? "", bank: filter.bank ?? "", status: filter.status || "UNRECONCILED", q: filter.q ?? "" });
  const decimal = (amount: bigint, currency: string) => { const places = digits(currency), base = 10n ** BigInt(places); return `${amount / base}${places ? "." + (amount % base).toString().padStart(places, "0") : ""}`; };
  return <FinanceWorkspace title="Bank reconciliation" description="Import statement evidence, review suggested matches and settle posted invoices. Matching is explicit; an import alone never creates accounting.">
    <FinanceEntities entities={data.entities} selected={entity?.id} path="/finance/reconcile"/>
    {!entity ? <p className="text-sm">Set up books and a bank account first.</p> : <>
      <div className="flex flex-wrap gap-6">{data.banks.map(bank => { const balance = data.bankBalances.find(row => row.accountId === bank.accountId); return <div key={bank.id}><p className="text-xs text-slate-500">{bank.name} · {bank.currency}</p><p className="mt-1 text-xl font-semibold">{money((balance?._sum.debit ?? 0n) - (balance?._sum.credit ?? 0n), entity.currency)}</p><p className="text-xs text-slate-500">Posted GL cash</p></div>; })}</div>
      <form className="grid items-end gap-3 sm:grid-cols-4"><input type="hidden" name="entity" value={entity.id}/><label className="text-xs">Bank account<select name="bank" className={field} defaultValue={filter.bank}><option value="">All bank accounts</option>{data.banks.map(bank => <option key={bank.id} value={bank.id}>{bank.name}</option>)}</select></label><label className="text-xs">Statement state<select name="status" className={field} defaultValue={filter.status || "UNRECONCILED"}><option value="UNRECONCILED">Unmatched</option><option value="RECONCILED">Reconciled</option><option value="ALL">All activity</option></select></label><label className="text-xs">Find invoice / customer / supplier<input name="q" className={field} defaultValue={filter.q}/></label><button className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-medium text-white">Apply</button></form>
      <section className={section}><h2 className="text-lg font-semibold">Statement activity</h2>{!data.rows.length && <p className="text-sm text-slate-500">No bank transactions match these filters.</p>}
        {data.rows.map(transaction => { const bank = data.banks.find(bank => bank.id === transaction.bankId)!, incoming = transaction.amount > 0n, eligible = data.invoices.filter(invoice => invoice.kind.startsWith(incoming ? "AR_" : "AP_") && session.capabilities.has(incoming ? "finance.receivables.manage" : "finance.payables.manage")); const selected = filter.transaction === transaction.id;
          return <article key={transaction.id} className="grid gap-6 border-b border-slate-200 py-5 lg:grid-cols-[minmax(220px,1fr)_2fr]"><div><p className="text-xs text-slate-500">{transaction.date.toISOString().slice(0, 10)} · {bank.name}</p><h3 className="mt-2 text-base font-medium">{transaction.reference}</h3><p className="mt-2 text-2xl font-semibold">{money(transaction.amount, bank.currency)}</p><p className="mt-2 text-xs text-slate-500">{transaction.status === "RECONCILED" ? "Reconciled" : "Needs a match"} · {transaction.externalId}</p></div>
            <div>{transaction.status === "RECONCILED" ? <div className="space-y-2 text-sm">{transaction.settlements.map(settlement => <p key={settlement.documentId}><Link className="text-blue-700" href={`/finance/documents/${settlement.documentId}`}>Settled invoice →</Link> · Bank {money(settlement.bankAmount ?? settlement.amount, bank.currency)}{settlement.realisedFx ? ` · FX ${money(settlement.realisedFx, entity.currency)}` : ""}</p>)}</div> : session.capabilities.has("finance.bank.manage") ? <>
              {data.suggestions.find(row => row.transactionId === transaction.id)?.matches.filter(match => match.ids.every(id => eligible.some(invoice => invoice.id === id))).slice(0, 3).map((match, index) => <ActionForm action={financeReconciliationForm} label="Accept match and reconcile" key={index} className="mb-4 border-l-2 border-blue-200 pl-4"><input type="hidden" name="transactionId" value={transaction.id}/><p className="text-sm font-medium">Suggested match · {match.confidence}% confidence</p><p className="text-xs text-slate-500">{match.reason}</p>{match.ids.map(id => { const invoice = eligible.find(invoice => invoice.id === id); return invoice ? <p className="text-sm" key={id}><input type="hidden" name={`amount:${id}`} value={decimal(invoice.gross - invoice.settled, invoice.currency)}/><Link className="text-blue-700" href={`/finance/documents/${id}`}>{invoice.reference}</Link> · {invoice.party?.name} · {money(invoice.gross - invoice.settled, invoice.currency)}</p> : null; })}</ActionForm>)}
              {selected ? <ReconciliationEditor transactionId={transaction.id} amount={transaction.amount} currency={bank.currency} invoices={eligible}/> : <Link className="text-sm text-blue-700" href={`/finance/reconcile?${query}&transaction=${transaction.id}`}>Choose invoices or enter a partial / foreign-currency allocation →</Link>}
            </> : <p className="text-sm text-slate-500">A permitted bank reconciler must review this transaction.</p>}</div>
          </article>;
        })}
        {filter.transaction ? <Link className="text-sm text-blue-700" href={`/finance/reconcile?${query}`}>Back to statement activity</Link> : <FinancePagination page={page} count={data.count} href={`/finance/reconcile?${query}`}/>}
        <p className="text-xs text-slate-500">Invoice choices show up to 200 authorised open records. Use invoice search to narrow the set. A confidence score is a matching hint, and every posting still checks the amount, period, currency and permissions.</p>
      </section>
      {session.capabilities.has("finance.bank.manage") && <details className={section}><summary className="cursor-pointer text-base font-semibold">Import statement transactions</summary><ActionForm className="mt-4" action={importFinanceStatementForm} label="Validate and import"><label className="text-xs">Bank account<select name="bankId" className={field} required>{data.banks.map(bank => <option key={bank.id} value={bank.id}>{bank.name} · {bank.currency}</option>)}</select></label><label className="block text-xs">Statement rows<textarea className={field} rows={6} name="transactions" required placeholder={"external-id\t2026-10-07\tInvoice reference\t12000.00"}/></label><p className="text-xs text-slate-500">Tab-separated external ID, date, reference and signed amount. Positive amounts are receipts. Exact retries are unchanged; a reused ID with different values is rejected.</p></ActionForm></details>}
      <Link className="inline-block text-sm text-blue-700" href={`/finance/banking?entity=${entity.id}`}>Bank account setup &amp; approved supplier payment runs →</Link>
    </>}
  </FinanceWorkspace>;
}
