import {requireSession} from '@/core/auth/session';
import {assertCapability} from '@/core/permissions/check';
import {assertModuleEnabled} from '@/core/modules/access';
import {db} from '@/core/db/client';
import {tokenRequest,callbackUrl} from '@/modules/meetings/services/microsoft';
import {encryptSecret} from '@/core/security/secrets';
import {audit} from '@/core/shared/operational-forms';
import {createHash} from 'node:crypto';
import {NextResponse} from 'next/server';
export async function GET(request:Request){const s=await requireSession();assertCapability(s,'meetings.calendar.connect');await assertModuleEnabled(s,'meetings');const url=new URL(request.url),raw=url.searchParams.get('state')??'',code=url.searchParams.get('code');if(!raw||raw.length>200)return new Response('Invalid calendar connection state.',{status:400});const stateHash=createHash('sha256').update(raw).digest('hex'),state=await db.meetingOAuthState.findFirst({where:{stateHash,organisationId:s.organisationId,userId:s.userId,expiresAt:{gt:new Date()}}});if(!state)return new Response('Calendar authorisation expired. Connect again.',{status:400});if((await db.meetingOAuthState.deleteMany({where:{stateHash,organisationId:s.organisationId,userId:s.userId}})).count!==1)return new Response('Calendar authorisation already used.',{status:400});if(!code||url.searchParams.has('error'))return NextResponse.redirect('https://atlassystem.online/meetings?view=connections&notice=declined');try{const t=await tokenRequest(new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:callbackUrl,code_verifier:state.verifier}));const data={accessToken:encryptSecret(t.access_token),refreshToken:encryptSecret(t.refresh_token),expiresAt:new Date(Date.now()+t.expires_in*1000)};await db.$transaction(async tx=>{await tx.microsoftCalendarConnection.upsert({where:{organisationId_userId:{organisationId:s.organisationId,userId:s.userId}},create:{...data,organisationId:s.organisationId,userId:s.userId},update:data});await audit(tx,s,'meetings.calendar.connected','User',s.userId);});return NextResponse.redirect('https://atlassystem.online/meetings?view=connections&notice=connected');}catch{return NextResponse.redirect('https://atlassystem.online/meetings?view=connections&notice=failed');}}
