import Link from 'next/link';
import { requireSession } from '@/core/auth/session';
import { assertCapability } from '@/core/permissions/check';
import { updateDepartmentTicket, getDepartmentWork } from '@/modules/service/services/commands';
import { ActionForm } from '@/modules/service/components/action-form';
import { RecordVersion, Select, TextArea } from '@/modules/service/components/fields';
import { label, TICKET_STATUSES } from '@/modules/service/domain/workflow';
import { Card } from '@/components/ui/card';
export default async function Tickets(){const session=await requireSession();assertCapability(session,'service.ticket.read');const tickets=await getDepartmentWork();return <div className="space-y-5"><div><h2 className="text-2xl font-semibold">Department tickets</h2><p className="mt-1 text-sm text-slate-500">Your departmental investigations. Customer Service retains ownership of the originating customer case.</p></div>{tickets.length===0&&<Card className="p-6 text-sm text-slate-500">No tickets in your permitted queues.</Card>}<div className="grid gap-4 lg:grid-cols-2">{tickets.map(t=><Card key={t.id} className="p-5"><div className="flex justify-between gap-3"><strong>{t.number} · {t.queue.name}</strong><span className="text-xs">{label(t.status)}</span></div><p className="mt-2 text-xs text-slate-500">Originating case: {t.caseNumber}</p><h3 className="mt-2 font-semibold">{t.subject}</h3><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{t.description}</p><p className={`mt-3 text-xs ${t.dueAt<new Date()&&!['COMPLETE','CANCELLED'].includes(t.status)?'text-red-700':'text-slate-500'}`}>Response due {t.dueAt.toLocaleString('en-GB',{timeZone:'Europe/London'})}</p>{session.capabilities.has('service.case.read')&&<Link className="mt-2 block text-xs text-blue-700" href={`/service/cases/${t.caseId}`}>Open originating customer case →</Link>}{t.outcome&&<p className="mt-3 whitespace-pre-wrap text-sm">Outcome: {t.outcome}</p>}{t.customerSafeSummary&&<p className="mt-2 whitespace-pre-wrap text-sm text-teal-800">Customer-safe: {t.customerSafeSummary}</p>}{session.capabilities.has('service.ticket.update')&&!['COMPLETE','CANCELLED'].includes(t.status)&&<details className="mt-4"><summary className="cursor-pointer text-sm font-medium">Respond / progress ticket</summary><ActionForm action={updateDepartmentTicket} className="mt-3" label="Save department response"><RecordVersion ticket id={t.id} version={t.version}/><Select title="Status" name="status" options={TICKET_STATUSES} defaultValue={t.status}/><label className="flex gap-2 text-sm"><input type="checkbox" name="takeOwnership" value="yes"/>Take ownership of this internal ticket</label><TextArea title="Internal outcome / reason" name="outcome" required maxLength={10000}/><TextArea title="Customer-safe summary for the case owner" name="customerSafeSummary" maxLength={10000}/></ActionForm></details>}</Card>)}</div><p className="text-xs text-slate-500">Up to 100 tickets ordered by due date. Queue membership and case security limit departmental access.</p></div>;}
