import {DOMAIN_EVENTS} from '@/core/events/bus';
import {db} from '@/core/db/client';
import type {Session} from '@/core/auth/session';
import type {Prisma} from '@/generated/prisma/client';
export function text(f:FormData,key:string,max=4000){const v=String(f.get(key)??'').trim();if(v.length>max)throw Error(`${key} is too long.`);return v;}
export function required(f:FormData,key:string,max=200){const v=text(f,key,max);if(!v)throw Error(`Enter ${key}.`);return v;}
export function choice(v:string,values:readonly string[],label='value'){if(!values.includes(v))throw Error(`Choose a valid ${label}.`);return v;}
export function number(f:FormData,key:string,min=0,max=10000000){const raw=required(f,key,30),v=Number(raw);if(!Number.isFinite(v)||v<min||v>max)throw Error(`Enter a valid ${key}.`);return v;}
export function integer(f:FormData,key:string,min=0,max=10000000){const v=number(f,key,min,max);if(!Number.isInteger(v))throw Error(`Enter a whole-number ${key}.`);return v;}
export function day(f:FormData,key:string){const v=text(f,key,10);if(!v)return null;const d=new Date(v+'T00:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(+d)||d.toISOString().slice(0,10)!==v)throw Error(`Enter a valid ${key}.`);return d;}
/** Resolve wall-clock input explicitly. Reject DST gaps and ambiguous times instead of guessing. */
export function localTime(value:string,zone='Europe/London'){if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(value))throw Error('Enter a valid date and time.');let fmt:Intl.DateTimeFormat;try{fmt=new Intl.DateTimeFormat('sv-SE',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});}catch{throw Error('Choose a valid timezone.');}const target=value.replace('T',' '),seed=Date.parse(value+'Z'),matches:Date[]=[];for(let offset=-840;offset<=840;offset+=15){const d=new Date(seed+offset*60000);if(fmt.format(d)===target)matches.push(d);}if(matches.length!==1)throw Error('This local time is invalid or ambiguous because of daylight saving. Choose another time.');return matches[0];}
export function range(f:FormData,start='startsAt',end='endsAt'){const timezone=text(f,'timezone',80)||'Europe/London',a=localTime(required(f,start,20),timezone),b=localTime(required(f,end,20),timezone);if(+b<=+a||+b-+a>7*86400000)throw Error('End must follow start and be within seven days.');return {start:a,end:b,timezone};}
export function safeJoinUrl(v:string){if(!v)return null;let u:URL;try{u=new URL(v);}catch{throw Error('Enter a valid Teams meeting URL.');}if(u.protocol!=='https:'||!['teams.microsoft.com','teams.live.com'].includes(u.hostname)||u.username||u.password)throw Error('Use a secure Microsoft Teams meeting link.');return u.toString();}
export async function member(s:Session,id:string,tx:Prisma.TransactionClient=db){if(id&&!await tx.membership.findFirst({where:{organisationId:s.organisationId,userId:id,active:true},select:{id:true}}))throw Error('Choose an active company member.');return id||null;}
export async function members(s:Session){return db.membership.findMany({where:{organisationId:s.organisationId,active:true},select:{userId:true,user:{select:{name:true}}},orderBy:{user:{name:'asc'}},take:501});}
export async function audit(tx:Prisma.TransactionClient,s:Session,action:string,entityType:string,entityId:string,after:Prisma.InputJsonValue={}){await tx.auditEntry.create({data:{organisationId:s.organisationId,actorUserId:s.userId,action,entityType,entityId,after}});await tx.domainOutbox.create({data:{organisationId:s.organisationId,eventKey:crypto.randomUUID(),eventName:DOMAIN_EVENTS.operationalRecordChanged,payload:{action,entityType,entityId,actorUserId:s.userId}}});}
export function changed(count:number){if(count!==1)throw Error('This record changed or is unavailable. Refresh before saving.');}
