'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { ArrowDownToLine, ArrowLeft, ArrowRight, Check, ChevronDown, Columns3, FileSpreadsheet, Filter, Plus, Search, X } from 'lucide-react';
import type { ReportFilter, ReportInput, ReportResult, ReportSpec } from '@/core/reports/types';
const CONTROL='min-h-11 w-full rounded-xl border border-[#dfe8f5] bg-white px-3 text-sm text-slate-800 outline-none transition focus:border-blue-400 focus:ring-2 focus:ring-blue-100 disabled:bg-slate-50 disabled:text-slate-400';
const PANEL='rounded-[24px] border border-white bg-white/95 shadow-[0_10px_40px_-28px_rgba(44,81,136,0.35)]';
function initial(spec?:ReportSpec):ReportInput{return {dataset:spec?.id||'',search:'',from:'',to:'',period:'all',filters:[],columns:spec?.columns.map(c=>c.key)||[],page:1};}
function paramsFor(input:ReportInput){const params=new URLSearchParams({dataset:input.dataset,search:input.search,from:input.from,to:input.to,period:input.period,filters:JSON.stringify(input.filters),columns:input.columns.join(','),page:String(input.page)});return params;}
function display(value:unknown,type?:string){if(value===null||value===undefined)return '—';if(type==='date')return (value instanceof Date?value.toISOString():String(value)).slice(0,10);if(typeof value==='number')return value.toLocaleString('en-GB',{maximumFractionDigits:type==='money'?2:6,minimumFractionDigits:type==='money'?2:0});if(typeof value==='boolean')return value?'Yes':'No';return String(value);}
export function ReportsWorkspace({datasets,company,initialResult,initialError}:{datasets:ReportSpec[];company:string;initialResult:ReportResult|null;initialError:string}){
 const [draft,setDraft]=useState(()=>initial(datasets[0]));const [applied,setApplied]=useState<ReportInput|null>(()=>initialResult?initial(datasets[0]):null);const [result,setResult]=useState<ReportResult|null>(initialResult);const [error,setError]=useState(initialError);const [busy,setBusy]=useState(false);const [downloading,setDownloading]=useState(false);const request=useRef<AbortController|null>(null);
 const spec=datasets.find(d=>d.id===draft.dataset);const sources=[...new Set(datasets.map(d=>d.source))];const dirty=JSON.stringify(draft)!==JSON.stringify(applied);const filterable=spec?.columns.filter(c=>c.path)||[];
 async function load(input:ReportInput){request.current?.abort();const controller=new AbortController();request.current=controller;setBusy(true);setError('');setDraft(input);try{const response=await fetch(`/api/reports?${paramsFor(input)}`,{signal:controller.signal,cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to load report.');setResult(data);setApplied(input);}catch(e){if(!controller.signal.aborted){setError(e instanceof Error?e.message:'Unable to load report.');setResult(null);}}finally{if(!controller.signal.aborted)setBusy(false);}}
 useEffect(()=>()=>request.current?.abort(),[]);
 function choose(id:string){request.current?.abort();setBusy(false);setDraft(initial(datasets.find(d=>d.id===id)));setResult(null);setApplied(null);setError('');}
 function updateFilter(index:number,patch:Partial<ReportFilter>){setDraft(d=>({...d,filters:d.filters.map((f,i)=>i===index?{...f,...patch}:f),page:1}));}
 async function download(){if(!applied||dirty||!result)return;setDownloading(true);setError('');try{const params=paramsFor(applied);params.set('download','xlsx');const response=await fetch(`/api/reports?${params}`,{cache:'no-store'});if(!response.ok){const data=await response.json();throw new Error(data.error||'Download failed.');}const url=URL.createObjectURL(await response.blob());const link=document.createElement('a');link.href=url;link.download=`atlas-${result.spec.id}-${new Date().toISOString().slice(0,10)}.xlsx`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30_000);}catch(e){setError(e instanceof Error?e.message:'Download failed.');}finally{setDownloading(false);}}
 if(!datasets.length)return <section className={`${PANEL} p-8`}><h1 className="text-3xl font-semibold">Reports</h1><p className="mt-3 text-slate-500">No report datasets are available for your account. Your company administrator can review your app access and permissions.</p><Link className="mt-5 inline-block text-blue-600" href="/home">Back to Home</Link></section>;
 return <div className="mx-auto max-w-[1440px] space-y-5 rounded-[28px] bg-[linear-gradient(125deg,#f1f7ff,#eef5ff_45%,#f8fbff)] p-3 sm:p-6">
  <header className="relative isolate flex items-center justify-between gap-4 overflow-hidden px-2 py-4 sm:py-6">
   <div aria-hidden="true" className="pointer-events-none absolute -right-12 -top-16 -z-10 hidden w-80 opacity-20 mix-blend-multiply md:block"><img src="/brand/atlas-mark.png" alt="" width={515} height={400}/></div>
   <div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#526587]">{company} · data workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[#090f22] sm:text-[38px]">Reports</h1><p className="mt-2 max-w-xl text-sm text-[#71809a]">Your data, the way you need it. Filter, preview and download to Excel.</p></div>
   <span className="hidden size-16 shrink-0 items-center justify-center rounded-[20px] bg-blue-100/70 text-[#075bff] sm:flex"><FileSpreadsheet size={30} strokeWidth={1.7}/></span>
  </header>
  <form aria-label="Report filters" className={`${PANEL} space-y-5 p-4 sm:p-6`} onSubmit={e=>{e.preventDefault();void load({...draft,page:1});}}>
   <div className="flex flex-wrap items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Filter size={18}/></span><h2 className="text-sm font-semibold text-slate-900">Build your report</h2><span className="ml-auto rounded-full bg-blue-50 px-3 py-1.5 text-[11px] font-medium text-[#526587]">{datasets.length} available datasets</span></div>
   <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-[1fr_1.4fr_1.6fr]">
    <label className="space-y-2 text-xs font-medium text-[#526587]">Source<select aria-label="Source" className={CONTROL} value={spec?.source||''} onChange={e=>choose(datasets.find(d=>d.source===e.target.value)!.id)}>{sources.map(s=><option key={s}>{s}</option>)}</select></label>
    <label className="space-y-2 text-xs font-medium text-[#526587]">Dataset<select aria-label="Dataset" className={CONTROL} value={draft.dataset} onChange={e=>choose(e.target.value)}>{datasets.filter(d=>d.source===spec?.source).map(d=><option key={d.id} value={d.id}>{d.name}{d.summary?' · summary':''}</option>)}</select></label>
    <label className="space-y-2 text-xs font-medium text-[#526587]">Search<div className="relative"><Search aria-hidden="true" size={17} className="absolute left-3 top-3.5 text-slate-400"/><input aria-label="Search records" className={`${CONTROL} pl-10`} value={draft.search} maxLength={200} placeholder={spec?.summary?'Search groups…':'Search codes, names and references…'} onChange={e=>setDraft(d=>({...d,search:e.target.value,page:1}))}/></div></label>
   </div>
   <div className="flex flex-wrap items-end gap-3">
    {spec?.dateField&&<><label className="min-w-0 flex-1 space-y-2 text-xs font-medium text-[#526587] sm:max-w-52">From<input aria-label="From date" type="date" className={CONTROL} value={draft.from} onChange={e=>setDraft(d=>({...d,from:e.target.value,page:1}))}/></label><label className="min-w-0 flex-1 space-y-2 text-xs font-medium text-[#526587] sm:max-w-52">Through<input aria-label="Through date" type="date" className={CONTROL} value={draft.to} onChange={e=>setDraft(d=>({...d,to:e.target.value,page:1}))}/></label></>}
    {spec?.summary&&!spec.snapshot&&<label className="space-y-2 text-xs font-medium text-[#526587]">Period<select aria-label="Summary period" className={CONTROL} value={draft.period} onChange={e=>setDraft(d=>({...d,period:e.target.value,page:1}))}><option value="all">All recorded time</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="365">Last 365 days</option></select></label>}
    {(!spec?.dateField&&!spec?.summary||spec?.snapshot)&&<p className="mr-auto self-center text-xs text-slate-500">Current snapshot · no historical date filter</p>}
    {!spec?.summary&&<button type="button" disabled={!filterable.length||draft.filters.length>=12} onClick={()=>setDraft(d=>({...d,filters:[...d.filters,{field:filterable[0].key,operator:'equals',value:''}],page:1}))} className="flex min-h-11 items-center gap-2 rounded-xl border border-[#dfe8f5] px-4 text-xs font-medium text-[#526587] hover:bg-blue-50 disabled:opacity-50"><Plus size={15}/> Add filter</button>}
    <details className="relative"><summary className="flex min-h-11 cursor-pointer list-none items-center gap-2 rounded-xl border border-[#dfe8f5] px-4 text-xs font-medium text-[#526587]"><Columns3 size={15}/>Columns ({draft.columns.length})<ChevronDown size={13}/></summary><div className="absolute right-0 z-20 mt-2 max-h-80 w-64 overflow-y-auto rounded-2xl border border-blue-100 bg-white p-3 shadow-xl">{spec?.columns.map(c=><label key={c.key} className="flex items-center gap-2 rounded-lg p-2 text-xs hover:bg-blue-50"><input type="checkbox" checked={draft.columns.includes(c.key)} disabled={draft.columns.includes(c.key)&&draft.columns.length===1} onChange={e=>setDraft(d=>({...d,columns:e.target.checked?[...d.columns,c.key]:d.columns.filter(k=>k!==c.key),page:1}))}/>{c.label}</label>)}</div></details>
    <button type="button" className="min-h-11 px-3 text-xs font-medium text-slate-500 hover:text-blue-700" onClick={()=>{if(spec){const next=initial(spec);setDraft(next);void load(next);}}}>Reset</button>
    <button disabled={busy} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#075bff] px-5 text-sm font-medium text-white shadow-sm transition hover:bg-blue-700 disabled:opacity-50"><Check size={16}/>{busy?'Loading…':'Apply filters'}</button>
   </div>
   {draft.filters.length>0&&<div className="space-y-2 rounded-2xl bg-[#f4f8ff] p-3">{draft.filters.map((f,i)=>{const c=filterable.find(c=>c.key===f.field);const type=c?.type||'text';return <div key={i} className="grid grid-cols-[1fr_32px] items-center gap-2 sm:grid-cols-[1fr_1fr_1.5fr_32px]"><select aria-label={`Filter ${i+1} field`} className={CONTROL} value={f.field} onChange={e=>updateFilter(i,{field:e.target.value,operator:'equals',value:''})}>{filterable.map(c=><option key={c.key} value={c.key}>{c.label}</option>)}</select><select aria-label={`Filter ${i+1} operator`} className={`${CONTROL} col-start-1 sm:col-auto`} value={f.operator} onChange={e=>updateFilter(i,{operator:e.target.value as ReportFilter['operator']})}><option value="equals">Equals</option>{type==='text'&&c?.searchable&&<option value="contains">Contains</option>}{['date','number','money'].includes(type)&&<><option value="gte">At least / from</option><option value="lte">At most / through</option></>}</select>{c?.values?<select aria-label={`Filter ${i+1} value`} className={CONTROL} value={f.value} onChange={e=>updateFilter(i,{value:e.target.value})}><option value="">Choose…</option>{c.values.map(value=><option key={value}>{value}</option>)}</select>:type==='boolean'?<select aria-label={`Filter ${i+1} value`} className={CONTROL} value={f.value} onChange={e=>updateFilter(i,{value:e.target.value})}><option value="">Choose…</option><option value="true">Yes</option><option value="false">No</option></select>:<input aria-label={`Filter ${i+1} value`} className={`${CONTROL} col-start-1 sm:col-auto`} type={type==='date'?'date':type==='number'||type==='money'?'number':'text'} step="any" value={f.value} maxLength={200} placeholder="Filter value" onChange={e=>updateFilter(i,{value:e.target.value})}/>}<button type="button" aria-label={`Remove filter ${i+1}`} className="col-start-2 row-start-1 rounded-lg p-2 text-slate-400 hover:text-red-600 sm:col-auto sm:row-auto" onClick={()=>setDraft(d=>({...d,filters:d.filters.filter((_,n)=>n!==i),page:1}))}><X size={16}/></button></div>;})}</div>}
   <p className="border-t border-[#edf2fa] pt-4 text-xs leading-5 text-[#71809a]">{spec?.description} {spec?.dateField&&'Date filters include the through date and use UTC.'}</p>
  </form>
  {error&&<div role="alert" className="rounded-2xl border border-red-100 bg-red-50 px-5 py-4 text-sm text-red-800">{error}</div>}
  <section aria-label="Report preview" aria-busy={busy} className={`${PANEL} min-w-0 overflow-hidden`}>
   <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#edf2fa] p-4 sm:px-6 sm:py-5"><div><h2 className="text-sm font-semibold text-slate-900">{result?.spec.name||'Report preview'}</h2><p role="status" className="mt-1 text-xs text-[#71809a]">{busy?'Loading your report…':result?`${result.total.toLocaleString()} matching ${result.total===1?'row':'rows'} · ${result.columns.length} columns`:'Apply your filters to preview this dataset.'}{dirty&&result?' · Apply your changes to refresh':''}</p></div><button onClick={()=>void download()} disabled={!result||dirty||busy||downloading||result.total>10_000} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#075bff] px-4 text-xs font-semibold text-white hover:bg-blue-700 disabled:bg-[#eef3fb] disabled:text-slate-400"><ArrowDownToLine size={17}/>{downloading?'Preparing Excel…':'Download Excel'}</button></div>
   {result&&result.rows.length>0?<div className="max-w-full overflow-x-auto"><table className="w-full border-collapse text-left text-xs"><thead className="bg-[#f4f8ff]"><tr>{result.columns.map(c=><th key={c.key} scope="col" className="whitespace-nowrap px-5 py-3.5 font-medium text-[#526587]">{c.label}</th>)}</tr></thead><tbody>{result.rows.map((r,i)=><tr key={i} className="border-t border-[#edf2fa] even:bg-blue-50/20 hover:bg-blue-50/60">{result.columns.map(c=><td key={c.key} className={`max-w-80 px-5 py-3.5 text-slate-700 ${['number','money'].includes(c.type||'')?'text-right tabular-nums':'break-words'}`}>{display(r[c.key],c.type)}</td>)}</tr>)}</tbody></table></div>:<div className="flex min-h-52 flex-col items-center justify-center gap-3 p-6 text-center"><span className="rounded-2xl bg-blue-50 p-4 text-blue-400"><FileSpreadsheet size={26}/></span><p className="text-sm text-slate-500">{busy?'Loading records…':result?'No records match these filters. Try widening your search or date range.':'Choose a dataset and apply filters to get started.'}</p></div>}
   {result&&<footer className="flex flex-wrap items-center justify-between gap-3 border-t border-[#edf2fa] px-5 py-4 text-xs text-[#71809a]"><span>{result.total>10_000?'Narrow your filters to download up to 10,000 rows.':'Excel includes all matching rows, up to 10,000.'}</span><div className="flex items-center gap-3"><button aria-label="Previous page" disabled={busy||dirty||result.page<=1} onClick={()=>void load({...applied!,page:result.page-1})} className="rounded-lg border border-[#dfe8f5] p-2 disabled:opacity-30"><ArrowLeft size={15}/></button><span>Page {result.page} of {Math.max(1,Math.ceil(result.total/100))}</span><button aria-label="Next page" disabled={busy||dirty||result.page*100>=result.total} onClick={()=>void load({...applied!,page:result.page+1})} className="rounded-lg border border-[#dfe8f5] p-2 disabled:opacity-30"><ArrowRight size={15}/></button></div></footer>}
  </section>
  <p className="px-2 text-center text-[11px] text-[#71809a]">Only records available to your account are included. <Link href="/home" className="font-medium text-blue-600 hover:underline">Back to your apps</Link></p>
 </div>;
}
