"use client";
import {useEffect,useRef,useState} from 'react';
export function AutoSaveDraft({initialId,revision}:{initialId?:string;revision:string}){
 const input=useRef<HTMLInputElement>(null),[id]=useState(initialId??''),[status,setStatus]=useState('Working quotation · autosave ready'),latest=useRef(''),sequence=useRef(0);
 useEffect(()=>{const form=input.current?.form;if(!form||!id)return;let timer:ReturnType<typeof setTimeout>,cancelled=false;
 const capture=()=>{const entries=Object.fromEntries([...new FormData(form).entries()].filter(([key])=>key!=='workingDraftId'));const payload=Object.fromEntries(Object.entries(entries).filter(([key])=>['mode','documentId','version','partyId','priceListId','invoiceAddressId','deliveryAddressId','paymentTermId','opportunityId','projectId','documentDate','customerPoReference','externalReference','tags','notes','pricingPartyId','deliveryInstructions','financeInstructions','lines'].includes(key)));const meaningful=JSON.parse(String(payload.lines??'[]')).some((l:{productId?:string;description?:string})=>l.productId||l.description);if(!payload.partyId&&!meaningful&&!payload.customerPoReference&&!payload.externalReference&&!payload.notes)return;sequence.current=Math.max(Date.now(),sequence.current+1);latest.current=JSON.stringify({id,payload,version:sequence.current});clearTimeout(timer);timer=setTimeout(async()=>{setStatus('Saving working quotation…');try{const response=await fetch('/api/sales/draft',{method:'POST',headers:{'Content-Type':'application/json'},body:latest.current,keepalive:true});const data=await response.json();if(!cancelled)setStatus(response.ok?`Working quotation saved · ${new Date(data.savedAt).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}`:`Autosave needs attention · ${data.error??'Retry'}`);}catch{if(!cancelled)setStatus('Autosave interrupted · keep this screen open');}},800);};
 const flush=()=>{if(latest.current)navigator.sendBeacon('/api/sales/draft',new Blob([latest.current],{type:'application/json'}));};
 form.addEventListener('change',capture);form.addEventListener('input',capture);window.addEventListener('pagehide',flush);capture();
 return()=>{cancelled=true;clearTimeout(timer);flush();form.removeEventListener('change',capture);form.removeEventListener('input',capture);window.removeEventListener('pagehide',flush);};
 },[id,revision]);
 return <><input ref={input} type="hidden" name="workingDraftId" value={id}/><p role="status" aria-live="polite" className="text-[10px] text-slate-500">{status}</p></>;
}
