"use client";
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {CreateDialog} from '@/components/ui/create-dialog';
import {Button} from '@/components/ui/button';
import {createSalesCatalogueProduct} from '../services/catalogue-actions';
export function CreateCatalogueProduct({mode,currency,onCreated}:{mode:'order'|'quote';currency:string;onCreated:(id:string)=>void}){
 const router=useRouter(),[message,setMessage]=useState(''),[pending,setPending]=useState(false);
 return <CreateDialog title="Create inventory product" label="Create product & add"><form className="space-y-4" action={async form=>{setPending(true);setMessage('');try{const product=await createSalesCatalogueProduct(mode,form);onCreated(product.id);router.refresh();setMessage(`${product.name} is saved in Inventory and added to this document.`);}catch(e){setMessage(e instanceof Error?e.message:'Could not save product.');}finally{setPending(false);}}}><p className="text-xs text-slate-500">Creates a shared business product. Stock starts at zero; receipts and adjustments belong in Inventory.</p><div className="grid gap-3 sm:grid-cols-2">{[['code','SKU',''],['name','Product name',''],['categoryCode','Category code',''],['unit','Unit','each'],['price','Standard price','0'],['currency','Currency',currency]].map(([name,label,value])=><label key={name} className="text-xs">{label}<input name={name} defaultValue={value} required={name!=='categoryCode'} type={name==='price'?'number':'text'} min={name==='price'?0:undefined} step={name==='price'?'0.01':undefined} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm"/></label>)}<label className="text-xs">Product type<select name="kind" className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm"><option value="PRODUCT">Stock product</option><option value="SERVICE">Service</option><option value="CHARGE">Charge</option></select></label><label className="text-xs">Tax<select name="taxCategory" className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm"><option>STANDARD</option><option>ZERO_RATED</option><option>EXEMPT</option></select></label></div><Button type="submit" variant="primary" disabled={pending}>{pending?'Creating…':'Create and add to document'}</Button><p role="status" className="text-xs text-slate-500">{message}</p></form></CreateDialog>;
}
