"use client";
import {useState,useRef} from 'react';
import {CreateDialog} from '@/components/ui/create-dialog';
import {createSalesAddress} from '../services/address-actions';
import type {DocumentData} from './document-types';
export function CreateSalesAddress({mode,type,accounts,initialAccount,onCreated,trigger}:{mode:'quote'|'order';type:'BILLING'|'DELIVERY';accounts:DocumentData['customers'];initialAccount:string;onCreated:(address:DocumentData['addresses'][number])=>void;trigger?:(open:()=>void)=>React.ReactNode}){
 const formRef=useRef<HTMLFormElement>(null);
 const [pending,setPending]=useState(false),[message,setMessage]=useState(''),[saved,setSaved]=useState(false),input='mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm';
 return <CreateDialog title={type==='DELIVERY'?'Add delivery address':'Add invoice address'} label={type==='DELIVERY'?'Add delivery address':'Add invoice address'} variant="secondary" trigger={trigger} onOpen={()=>{setSaved(false);setMessage('');formRef.current?.reset();}}><form ref={formRef} className="space-y-4" action={async form=>{setPending(true);setMessage('');try{const a=await createSalesAddress(mode,form);onCreated(a);setSaved(true);setMessage('Address saved and selected.');formRef.current?.closest('dialog')?.close();}catch(e){setMessage(e instanceof Error?e.message:'Could not save address.');}finally{setPending(false);}}}><fieldset disabled={pending||saved} className="space-y-4"><input type="hidden" name="type" value={type}/><p className="text-xs text-slate-500">Creates a customer address and selects it immediately. The rest of your order stays in place.</p><label className="block text-xs">Attach address to account<select name="partyId" required defaultValue={initialAccount} className={input}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.code}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2">{[['label','Site / address name'],['line1','Address line 1'],['line2','Address line 2'],['city','Town / city'],['region','Region'],['postcode','Postcode']].map(([name,label])=><label key={name} className="text-xs">{label}<input name={name} required={name==='line1'} maxLength={name==='postcode'?30:100} className={input}/></label>)}<label className="text-xs">Country code<input name="country" required defaultValue="GB" pattern="[A-Z]{2}" maxLength={2} placeholder="GB" className={input}/></label></div><button type="submit" className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">{pending?'Saving…':saved?'Address added':'Save and select address'}</button></fieldset><p role="status" className="text-xs text-slate-600">{message}</p></form></CreateDialog>;
}
