"use client";
import {hierarchyAccountIds} from "@/core/customers/hierarchy";
import {CreateCatalogueProduct} from "./create-catalogue-product";
import {useRouter} from "next/navigation";
import {AutoSaveDraft} from "./auto-save-draft";
import {ProductPicker} from "./product-picker";
import {TagEditor} from "./hashtags";
import { useActionState,useState } from "react";
import {selectPriceRule,calculateRulePrice,ruleExplanation} from "@/core/pricing/rules";
import type {DocumentLineInput} from "../services/document-lines";
import Link from "next/link";
import { Plus,Trash2,ChevronRight,GripVertical,BarChart3 } from "lucide-react";
import {stockPromiseLabel} from "@/core/availability/stock-promise";
import { formatMoney } from "@/core/shared/money";
import { saveDocument } from "@/modules/sales/services/documents";
import type { DocumentData,DocumentDraft } from "./document-types";
const input='w-full rounded-xl border border-[var(--color-border)] bg-white px-3 py-2.5 text-sm outline-none focus:border-[var(--color-atlas-blue)]';
export function DocumentComposer({data,mode,initialCustomer='',initialOpportunity='',initialProject='',initialSalesProject='',initialKind='STANDARD',initialOrderType='STANDARD',initialAgreement='',draft,workingDraftId}:{data:DocumentData;mode:'quote'|'order';initialCustomer?:string;initialOpportunity?:string;initialProject?:string;initialSalesProject?:string;initialKind?:'STANDARD'|'BLANKET';initialOrderType?:'STANDARD'|'PROJECT'|'CALL_OFF';initialAgreement?:string;draft?:DocumentDraft;workingDraftId?:string}) {
 const router=useRouter();
 const [customerId,setCustomer]=useState(draft?.partyId??initialCustomer),[listId,setList]=useState(draft?.priceListId??data.customers.find(c=>c.id===initialCustomer)?.defaultListId??''),[invoice,setInvoice]=useState(draft?.invoiceAddressId??''),[delivery,setDelivery]=useState(draft?.deliveryAddressId??'');
 const [lines,setLines]=useState<(DocumentLineInput&{key:string})[]>(draft?.lines.map((l,i)=>({...l,key:l.id??String(i)}))??[{key:'first',productId:'',type:'PRODUCT',description:'',quantity:1,discount:0,optional:false}]);
 const [pricingAccountId,setPricingAccount]=useState(draft?.pricingPartyId??''),[deliveryInstructions,setDeliveryInstructions]=useState(draft?.deliveryInstructions??''),[financeInstructions,setFinanceInstructions]=useState(draft?.financeInstructions??'');
 const [notes,setNotes]=useState(draft?.notes??''),[documentDate,setDocumentDate]=useState(draft?.documentDate??''),[activeTab,setActiveTab]=useState('lines'),[termId,setTerm]=useState(draft?.paymentTermId??data.customers.find(c=>c.id===initialCustomer)?.defaultTermId??'');
 const [state,action,pending]=useActionState(saveDocument,{error:''});
 const pricingCustomerId=pricingAccountId||customerId;
 const customer=data.customers.find(c=>c.id===customerId),list=data.lists.find(l=>l.id===listId),currency=list?.currency??data.customers.find(c=>c.id===pricingCustomerId)?.currency??customer?.currency??'GBP';
 const family=data.customers.map(c=>({id:c.id,parentPartyId:c.parentId})),related=[...hierarchyAccountIds(family,customerId),...(pricingAccountId?hierarchyAccountIds(family,pricingAccountId):[])];
 const addresses=data.addresses.filter(a=>related.includes(a.partyId));
 const invoiceId=invoice||addresses.find(a=>a.partyId===customerId&&a.defaultBilling)?.id||'',deliveryId=delivery||addresses.find(a=>a.partyId===customerId&&a.defaultDelivery)?.id||'';
 const deliveryCountry=addresses.find(a=>a.id===deliveryId)?.country?.toUpperCase(),uk=['GB','UK','UNITED KINGDOM'].includes(deliveryCountry??'');
 function priced(line:typeof lines[number]) {
  const product=data.products.find(p=>p.id===line.productId)??(line.type==='TEXT'?{id:'',name:line.description,code:'Custom',categoryCode:null,unit:'each',price:line.unitAmount??0,currency,taxCategory:'STANDARD',stock:null}:undefined);if(!['PRODUCT','TEXT'].includes(line.type)||!product)return {price:0,source:'Choose a product',net:0,tax:0,product:undefined};
  const contract=data.contracts.find(c=>c.partyId===pricingCustomerId&&c.productId===product.id),today=new Date().toISOString();
  const rule=list?selectPriceRule(list.entries,product,line.quantity,new Date(today)):undefined;
  let price=product.price,source='Standard price';
  try {if(contract){if(contract.currency!==currency)throw new Error(`Contract uses ${contract.currency}`);price=contract.price;source='Customer contract';}else if(rule&&list){price=calculateRulePrice(rule,list,{basePriceAmount:product.price,baseCurrency:product.currency});source=`${list.name} · ${ruleExplanation(rule,list.currency)}`;}else if(product.currency!==currency){throw new Error(`Add a ${currency} price rule`);}}catch(error){price=0;source=error instanceof Error?error.message:'Check price rule';}
  if(line.unitAmount!=null){price=line.unitAmount;source='Saved / entered price';}
  const net=Math.round(price*line.quantity*(1-line.discount/100)),tax=uk&&!['ZERO_RATED','EXEMPT'].includes(product.taxCategory??'')?Math.round(net*.2):0;
  return {price,source,net,tax,product};
 }
 const totals=lines.filter(l=>!l.optional).reduce((sum,line)=>{const p=priced(line);return {net:sum.net+p.net,tax:sum.tax+p.tax};},{net:0,tax:0});
 function patch(key:string,values:Partial<typeof lines[number]>){setLines(previous=>previous.map(l=>l.key===key?{...l,...values}:l));}
 const blank=(type:'PRODUCT'|'SECTION'|'NOTE',optional=false)=>({key:crypto.randomUUID(),type,description:'',optional,productId:'',quantity:1,discount:0});
 const add=(type:'PRODUCT'|'SECTION'|'NOTE')=>setLines(previous=>[...previous,blank(type,type!=='NOTE'&&activeTab==='optional')]);
 const canPrice=mode==='quote'?data.canOverrideQuotePrice:data.canOverrideOrderPrice;
 const [dragKey,setDragKey]=useState<string|null>(null);
 const reorder=(from:string,to:string)=>setLines(previous=>{const next=[...previous],a=next.findIndex(l=>l.key===from),b=next.findIndex(l=>l.key===to);if(a<0||b<0)return previous;const [moved]=next.splice(a,1);next.splice(b,0,moved);return next;});
 const shown=lines.filter(l=>activeTab==='optional'?l.optional:!l.optional);
 const tabs:[string,string][]=[['lines','Order lines'],...(mode==='quote'?[['optional','Optional products'] as [string,string]]:[]),['info','Other info']];
 const steps=mode==='quote'?['Quotation','Sent','Accepted']:['Draft','Confirmed','Fulfilled'];
 return <form action={action} className="mx-auto w-full min-w-0 max-w-6xl space-y-4"><input type="hidden" name="mode" value={mode}/><input type="hidden" name="documentId" value={draft?.id??''}/><input type="hidden" name="version" value={draft?.version??''}/><input type="hidden" name="invoiceAddressId" value={invoiceId}/><input type="hidden" name="deliveryAddressId" value={deliveryId}/><input type="hidden" name="lines" value={JSON.stringify(lines.filter(l=>l.type!=='PRODUCT'||l.productId).map(({key,...l})=>{void key;return l;}))}/><AutoSaveDraft initialId={workingDraftId} revision={JSON.stringify({lines,customerId,pricingAccountId,listId,invoice,delivery,notes,deliveryInstructions,financeInstructions,documentDate,termId})}/><fieldset disabled={pending} className="contents">
 <div className="flex flex-wrap items-center justify-between gap-3">
  <div className="flex flex-wrap items-center gap-2"><button type="submit" className="rounded-xl bg-[var(--color-atlas-blue)] px-5 py-2.5 text-sm font-medium text-white hover:bg-[var(--color-atlas-blue-hover)]">{pending?'Saving…':draft?'Save changes':'Save draft'}</button><Link href={`/sales/${mode==='quote'?'quotes':'orders'}`} className="rounded-xl border border-[var(--color-border)] bg-white px-4 py-2.5 text-sm text-[var(--color-ink-muted)] hover:text-[var(--color-ink)]">Discard</Link></div>
  <ol className="flex items-center overflow-hidden rounded-xl border border-[var(--color-border)] bg-white text-xs font-medium">{steps.map((step,index)=><li key={step} className={`flex items-center gap-2 px-4 py-2.5 ${index===0?'bg-[var(--color-atlas-blue-soft)] text-[var(--color-atlas-blue)]':'text-[var(--color-ink-faint)]'}`}>{index>0&&<ChevronRight size={12} className="-ml-2 text-[var(--color-ink-faint)]"/>}{step}</li>)}</ol>
 </div>
 {state.error&&<p role="alert" className="rounded-xl bg-[var(--color-status-danger-soft)] p-4 text-sm text-[var(--color-status-danger)]">{state.error}</p>}
 <section className="overflow-hidden rounded-2xl border border-[var(--color-border)] bg-white">
  <div className="px-6 pt-6 sm:px-8"><p className="text-xs text-[var(--color-ink-muted)]">{mode==='quote'?'Quotations':'Sales orders'} / {draft?.reference??'New'}</p><h2 className="mt-1 text-3xl font-semibold tracking-tight">{draft?.reference??(mode==='quote'?'New quotation':'New sales order')}</h2></div>
  <div className="grid gap-x-12 gap-y-1 px-6 py-5 sm:px-8 lg:grid-cols-2">
   <div>
    <Field label="Customer"><div className="flex items-center gap-2"><select name="partyId" required value={customerId} onChange={e=>{setLines(previous=>previous.map(l=>({...l,unitAmount:null})));setCustomer(e.target.value);setPricingAccount('');setTerm(data.customers.find(c=>c.id===e.target.value)?.defaultTermId??'');setInvoice('');setDelivery('');setList(data.customers.find(c=>c.id===e.target.value)?.defaultListId??'');}} className={cell}><option value="">Choose a customer…</option>{data.customers.map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select>{data.allowCustomerCreation&&<Link href="/customers/new" target="_blank" rel="noopener" aria-label="Create customer" className="rounded-lg p-1.5 text-[var(--color-ink-muted)] hover:bg-slate-100"><Plus size={16}/></Link>}</div></Field>
    <Field label="Invoice address"><select value={invoiceId} onChange={e=>setInvoice(e.target.value)} className={cell}><option value="">Select billing address</option>{addresses.filter(a=>hierarchyAccountIds(family,customerId).includes(a.partyId)&&(a.type==='BILLING'||a.defaultBilling)).map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></Field>
    <Field label="Delivery address"><select value={deliveryId} onChange={e=>setDelivery(e.target.value)} className={cell}><option value="">Select delivery site</option>{addresses.filter(a=>a.type==='DELIVERY'||a.defaultDelivery).map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></Field>
    <Field label="Pricing account"><select name="pricingPartyId" value={pricingAccountId} onChange={e=>{setPricingAccount(e.target.value);setList(data.customers.find(c=>c.id===(e.target.value||customerId))?.defaultListId??'');setDelivery('');setLines(previous=>previous.map(l=>({...l,unitAmount:null})));}} className={cell}><option value="">Same as customer</option>{data.customers.filter(c=>data.tradingLinks?.some(l=>l.accountId===c.id&&l.tradingAccountId===customerId)).map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></Field>
    <Field label={`Customer PO${customer?.poRequired?' *':''}`}><input name="customerPoReference" defaultValue={draft?.customerPoReference} maxLength={150} placeholder="Purchase order number" className={cell}/></Field>
    <Field label={`Order reference${customer?.referenceRequired?' *':''}`}><input name="externalReference" defaultValue={draft?.externalReference} placeholder="Customer order or job reference" className={cell}/></Field>
   </div>
   <div>
    <Field label={mode==='quote'?'Valid until':'Delivery requested'}><input name="documentDate" type="date" value={documentDate} onChange={e=>setDocumentDate(e.target.value)} className={cell}/></Field>
    <Field label="Pricelist"><select name="priceListId" value={listId} onChange={e=>{setList(e.target.value);setLines(previous=>previous.map(l=>({...l,unitAmount:null})));}} className={cell}><option value="">Standard prices · {currency}</option>{data.lists.map(l=><option key={l.id} value={l.id}>{l.name} · {l.currency}</option>)}</select></Field>
    <Field label="Payment terms"><select name="paymentTermId" value={termId} onChange={e=>setTerm(e.target.value)} className={cell}><option value="">Choose terms</option>{data.terms.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field>
    {data.salesProjects&&<Field label="Sales project"><select name="salesProjectId" defaultValue={draft?.salesProjectId??initialSalesProject} className={cell}><option value="">No sales project</option>{[...data.salesProjects].sort((a,b)=>Number(b.partyIds.includes(customerId))-Number(a.partyIds.includes(customerId))).map(p=><option key={p.id} value={p.id}>{p.name}{p.partyIds.includes(customerId)?' · this customer':''}</option>)}</select></Field>}
    <Field label="Delivery project"><select name="projectId" defaultValue={draft?.projectId??initialProject} className={cell}><option value="">No project</option>{data.projects.filter(p=>p.partyId===customerId).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>
    <Field label="CRM opportunity"><select name="opportunityId" defaultValue={draft?.opportunityId??initialOpportunity} className={cell}><option value="">No linked opportunity</option>{data.opportunities.filter(o=>o.partyId===customerId).map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></Field>
    <Field label="Tags"><TagEditor initial={draft?.tags??[]} name="tags"/></Field>
   </div>
  </div>
  {customer&&<div className={`mx-6 mb-5 flex flex-wrap gap-4 rounded-xl border px-4 py-2.5 text-xs sm:mx-8 ${customer.creditHold?'border-rose-200 bg-rose-50 text-rose-700':'border-blue-100 bg-blue-50/60 text-slate-600'}`}><span className="font-semibold">{customer.code}</span><span>{customer.creditHold?'● Customer credit hold':'Account selected'}</span>{customer.poRequired&&<span>PO number required</span>}{customer.referenceRequired&&<span>Order reference required</span>}<span>{list?.name??'Standard catalogue'} · {currency}</span><span>{data.terms.find(t=>t.id===termId)?.name??'Payment terms not selected'}</span></div>}
  <div className="flex items-end gap-1 border-b border-[var(--color-border)] px-6 sm:px-8">{tabs.map(([id,label])=><button key={id} type="button" onClick={()=>setActiveTab(id)} className={`-mb-px rounded-t-lg border border-b-0 px-4 py-2.5 text-sm font-medium ${activeTab===id?'border-[var(--color-border)] bg-white text-[var(--color-ink)]':'border-transparent text-[var(--color-ink-muted)] hover:text-[var(--color-ink)]'}`}>{label}{id==='lines'&&<span className="ml-2 text-xs font-normal text-[var(--color-ink-faint)]">{lines.filter(l=>l.productId&&!l.optional).length}</span>}</button>)}</div>
  <div className={activeTab==='info'?'hidden':''}>
   <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead className="text-left text-xs font-semibold text-[var(--color-ink-muted)]"><tr className="border-b border-[var(--color-border)]"><th className="w-8 py-2.5 pl-4"/><th className="py-2.5 pr-3">Product</th><th className="w-28 px-3 py-2.5">Cat. code</th><th className="w-32 px-3 py-2.5 text-right">Quantity</th><th className="w-16 px-3 py-2.5">Unit</th><th className="w-28 px-3 py-2.5 text-right">Unit price</th><th className="w-20 px-3 py-2.5 text-right">Disc %</th><th className="w-20 px-3 py-2.5">Taxes</th><th className="w-32 px-3 py-2.5 text-right">Amount</th><th className="w-10 py-2.5 pr-4"/></tr></thead><tbody>
    {shown.map(line=>{const p=priced(line);const remove=<button type="button" aria-label="Remove line" onClick={()=>setLines(previous=>previous.filter(l=>l.key!==line.key))} className="rounded p-1 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={15}/></button>;
     const handle=<td className="py-2 pl-4 align-middle"><span draggable onDragStart={e=>{setDragKey(line.key);e.dataTransfer.effectAllowed='move';}} onDragEnd={()=>setDragKey(null)} title="Drag to reorder" className="flex cursor-grab justify-center text-slate-300 hover:text-slate-500 active:cursor-grabbing"><GripVertical size={15}/></span></td>;
     const drop={onDragOver:(e:React.DragEvent)=>{if(dragKey&&dragKey!==line.key){e.preventDefault();reorder(dragKey,line.key);}},className:`border-b border-slate-100 ${dragKey===line.key?'opacity-40':''}`};
     if(!['PRODUCT','TEXT'].includes(line.type))return <tr key={line.key} onDragOver={drop.onDragOver} className={`${drop.className} bg-slate-50/70`}>{handle}<td colSpan={8} className="py-1 pr-3"><input aria-label={line.type==='SECTION'?'Section heading':'Note'} value={line.description} maxLength={2000} autoFocus={!line.description} onChange={e=>patch(line.key,{description:e.target.value})} onKeyDown={e=>{if(e.key==='Enter')e.preventDefault();}} placeholder={line.type==='SECTION'?'Section heading':'Note for the customer'} className={`atlas-cell w-full ${line.type==='SECTION'?'font-semibold':'italic text-slate-600'}`}/></td><td className="py-1 pr-4 text-right align-middle">{remove}</td></tr>;
     const stock=p.product?.stock??null,short=stock!=null&&line.productId?Math.max(0,line.quantity-Math.max(0,stock)):0,level=stock==null||!line.productId?'none':short===0?'ok':stock>0?'part':'out';
     const promise=short>0&&stock!=null?stockPromiseLabel(stock,line.quantity,p.product?.arrivals??[]).replace(/^Out of stock\. No dated supply covers this quantity\.$/,'no supply due yet'):'';
     return <tr key={line.key} onDragOver={drop.onDragOver} className={`${drop.className} group align-middle hover:bg-[#f7f9ff]`}>{handle}
      <td className="py-1 pr-3">{line.type==='TEXT'?<span className="block px-2 py-1.5 text-slate-500">{line.description||'Custom line'}</span>:<><ProductPicker bare products={data.products} value={line.productId} currency={currency} price={id=>priced({...line,productId:id,unitAmount:null}).price} onChange={id=>{patch(line.key,{productId:id,unitAmount:null,description:''});if(id&&shown[shown.length-1]?.key===line.key)add('PRODUCT');}}/>{short>0&&<p className={`px-2 pb-1 text-[11px] ${level==='out'?'text-red-600':'text-amber-700'}`}>{level==='out'?'None in stock':`Only ${stock?.toLocaleString('en-GB')} in stock, ${short.toLocaleString('en-GB')} short`} · {promise}</p>}{(line.unitAmount!=null&&line.unitAmount!==priced({...line,unitAmount:null}).price||(line.description&&line.description!==p.product?.name))&&<p className="px-2 pb-1 text-[11px] text-slate-400">{[line.unitAmount!=null&&line.unitAmount!==priced({...line,unitAmount:null}).price?'Price changed from the list':'',line.description&&line.description!==p.product?.name?line.description:''].filter(Boolean).join(' · ')}</p>}</>}</td>
      <td className="px-3 py-1 text-xs text-slate-500">{p.product?.categoryCode||(line.productId?'—':'')}</td>
      <td className="px-3 py-1"><div className="flex items-center justify-end gap-1.5"><input aria-label="Quantity" type="number" min={1} max={1000000} step={1} value={line.quantity} onChange={e=>patch(line.key,{quantity:Number(e.target.value)})} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();add('PRODUCT');}}} className="atlas-cell w-20 text-right tabular-nums"/>{level!=='none'&&<span className="relative flex" tabIndex={0} aria-label={`Stock: ${stock} free now`}><BarChart3 size={16} className={`peer cursor-help ${level==='ok'?'text-emerald-600':level==='part'?'text-amber-500':'text-red-500'}`}/><span role="tooltip" className="pointer-events-none absolute right-full top-1/2 z-10 mr-2 hidden w-56 -translate-y-1/2 rounded-xl border border-slate-200 bg-white p-3 text-left text-xs font-normal text-slate-600 shadow-lg peer-hover:block"><span className="block font-semibold text-slate-900">{p.product?.name}</span><span className="mt-1 flex justify-between"><span>Free in stock now</span><span className="font-semibold tabular-nums text-slate-900">{stock?.toLocaleString('en-GB')} {p.product?.unit}</span></span><span className="flex justify-between"><span>This line</span><span className="tabular-nums">{line.quantity.toLocaleString('en-GB')}</span></span><span className={`flex justify-between ${short?'text-red-600':'text-emerald-700'}`}><span>{short?'Short by':'Left after'}</span><span className="font-semibold tabular-nums">{(short||Math.max(0,(stock??0)-line.quantity)).toLocaleString('en-GB')}</span></span>{promise&&<span className="mt-1 block text-slate-500">{promise}</span>}{(p.product?.arrivals??[]).slice(0,3).map(arrival=><span key={`${arrival.on}-${arrival.source}`} className="flex justify-between text-slate-500"><span>Due {new Date(`${arrival.on}T00:00:00Z`).toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'UTC'})}</span><span className="tabular-nums">+{arrival.quantity.toLocaleString('en-GB')}</span></span>)}</span></span>}</div></td>
      <td className="px-3 py-1 text-xs text-slate-500">{p.product?.unit||''}</td>
      <td className="px-3 py-1"><input aria-label="Unit price" type="number" min={0} step="0.01" disabled={!canPrice} value={p.price/100} onChange={e=>patch(line.key,{unitAmount:Math.round(Number(e.target.value)*100)})} className="atlas-cell w-full text-right tabular-nums"/></td>
      <td className="px-3 py-1"><input aria-label="Discount percent" type="number" min={0} max={100} step="0.1" value={line.discount} onChange={e=>patch(line.key,{discount:Number(e.target.value)})} className="atlas-cell w-full text-right tabular-nums"/></td>
      <td className="px-3 py-1">{p.product&&line.productId?<span className={`rounded-full px-2 py-0.5 text-[11px] font-medium ${!uk?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-600'}`}>{!uk?'Review':['ZERO_RATED','EXEMPT'].includes(p.product.taxCategory??'')?'0%':'20%'}</span>:null}</td>
      <td className="px-3 py-1 text-right font-semibold tabular-nums">{line.productId||line.type==='TEXT'?formatMoney(p.net,currency):''}</td>
      <td className="py-1 pr-4 text-right">{remove}</td></tr>;})}
    <tr><td/><td colSpan={9} className="py-3 pr-6"><div className="flex flex-wrap items-center gap-5 px-2 text-sm font-medium text-[var(--color-atlas-blue)]"><button type="button" onClick={()=>add('PRODUCT')} className="hover:underline">Add a product</button><button type="button" onClick={()=>add('SECTION')} className="hover:underline">Add a section</button>{activeTab==='lines'&&<button type="button" onClick={()=>add('NOTE')} className="hover:underline">Add a note</button>}{mode==='quote'&&<button type="button" onClick={()=>setLines(previous=>previous.map(l=>({...l,unitAmount:null})))} className="font-normal text-slate-500 hover:underline">Recalculate prices</button>}<span className="ml-auto flex items-center gap-1 text-xs font-normal text-slate-400"><BarChart3 size={12}/>Green: in stock · amber: part · red: none. Hover for detail</span></div></td></tr>
   </tbody></table></div>
   <div className="grid gap-6 border-t border-[var(--color-border)] px-6 py-5 sm:grid-cols-[1fr_auto] sm:px-8"><label className="block text-xs text-[var(--color-ink-muted)]">Terms and notes for the customer<textarea name="notes" value={notes} onChange={e=>setNotes(e.target.value)} maxLength={5000} placeholder="Shown on the quotation or order acknowledgement…" className={`${input} mt-2 min-h-24`}/></label><dl className="w-full space-y-2 text-sm sm:w-72"><div className="flex justify-between"><dt className="text-[var(--color-ink-muted)]">Untaxed amount</dt><dd className="tabular-nums">{formatMoney(totals.net,currency)}</dd></div><div className="flex justify-between"><dt className="text-[var(--color-ink-muted)]">Estimated tax</dt><dd className="tabular-nums">{formatMoney(totals.tax,currency)}</dd></div><div className="flex justify-between border-t border-[var(--color-border)] pt-3 text-xl font-semibold"><dt>Total</dt><dd className="tabular-nums">{formatMoney(totals.net+totals.tax,currency)}</dd></div>{!uk&&<p className="text-xs text-[var(--color-status-warning)]">Tax needs review until a supported delivery country is selected.</p>}</dl></div>
  </div>
  <div className={`grid gap-5 px-6 py-6 sm:px-8 lg:grid-cols-2 ${activeTab==='info'?'':'hidden'}`}><label className="block text-xs text-[var(--color-ink-muted)]">Delivery instructions<textarea name="deliveryInstructions" value={deliveryInstructions} onChange={e=>setDeliveryInstructions(e.target.value)} maxLength={5000} placeholder="Access, unloading, site contact or delivery constraints…" className={`${input} mt-2 min-h-32`}/></label><label className="block text-xs text-[var(--color-ink-muted)]">Finance instructions · internal<textarea name="financeInstructions" value={financeInstructions} onChange={e=>setFinanceInstructions(e.target.value)} maxLength={5000} placeholder="Invoice references, billing instructions or finance follow-up…" className={`${input} mt-2 min-h-32`}/></label></div>
 </section>
 </fieldset></form>;
}
const cell='w-full rounded-lg border border-transparent bg-transparent px-2 py-1.5 text-sm outline-none transition hover:border-[var(--color-border)] focus:border-[var(--color-atlas-blue)] focus:bg-white';
function Field({label,children}:{label:string;children:React.ReactNode}) {return <label className="grid items-center gap-2 border-b border-slate-100 py-1 sm:grid-cols-[140px_1fr]"><span className="text-sm font-medium text-[var(--color-ink)]">{label}</span>{children}</label>;}
