"use client";
import {useState,useRef,useId,useEffect} from 'react';
import {createPortal} from 'react-dom';
import {Search} from 'lucide-react';
import {formatMoney} from '@/core/shared/money';
import type {DocumentData} from './document-types';
export function ProductPicker({products,value,onChange,price,currency}:{products:DocumentData['products'];value:string;onChange:(id:string)=>void;price:(id:string)=>number;currency:string}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[active,setActive]=useState(0),[position,setPosition]=useState({left:0,top:0,width:320}),wrapper=useRef<HTMLDivElement>(null),menu=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null),id=useId();const selected=products.find(p=>p.id===value),matches=products.filter(p=>`${p.code} ${p.name} ${p.categoryCode??''}`.toLowerCase().includes(query.toLowerCase())).slice(0,30);
 function show(){const rect=wrapper.current?.getBoundingClientRect();if(rect)setPosition({left:Math.max(8,Math.min(rect.left,window.innerWidth-360)),top:Math.min(rect.bottom+5,window.innerHeight-265),width:Math.max(320,rect.width)});setOpen(true);setQuery('');setActive(0);}
 function choose(productId:string){onChange(productId);setOpen(false);input.current?.focus();}
 useEffect(()=>{if(!open)return;const outside=(event:PointerEvent)=>{if(!wrapper.current?.contains(event.target as Node)&&!menu.current?.contains(event.target as Node))setOpen(false);};const close=()=>setOpen(false);document.addEventListener('pointerdown',outside);window.addEventListener('resize',close);return()=>{document.removeEventListener('pointerdown',outside);window.removeEventListener('resize',close);};},[open]);
 return <div ref={wrapper} className="relative"><Search size={14} className="pointer-events-none absolute left-3 top-3 text-slate-400"/><input ref={input} role="combobox" aria-label="Search products" aria-expanded={open} aria-controls={id} aria-autocomplete="list" aria-activedescendant={open&&matches[active]?`${id}-${active}`:undefined} value={open?query:selected?`[${selected.code}] ${selected.name}`:''} onFocus={show} onChange={e=>{setQuery(e.target.value);setActive(0);setOpen(true);}} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);e.preventDefault();}if(open&&['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();setActive(i=>(i+(e.key==='ArrowDown'?1:-1)+Math.max(matches.length,1))%Math.max(matches.length,1));}if(open&&e.key==='Enter'){e.preventDefault();if(matches[active])choose(matches[active].id);}}} placeholder="Search SKU, product or category…" className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-9 pr-3 text-sm"/>{open&&createPortal(<div ref={menu} id={id} role="listbox" aria-label="Product results" style={{position:'fixed',...position}} className="z-[80] max-h-60 overflow-y-auto rounded-xl border border-slate-200 bg-white p-1 shadow-xl">{matches.map((p,i)=><button id={`${id}-${i}`} key={p.id} type="button" role="option" aria-selected={i===active} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(p.id)} className={`block w-full rounded-lg p-3 text-left ${i===active?'bg-blue-50':'hover:bg-slate-50'}`}><div className="flex justify-between gap-3"><span className="text-xs font-semibold">{p.code}</span><span className="text-xs font-medium text-blue-600">{formatMoney(price(p.id),currency)}</span></div><p className="mt-1 text-xs text-slate-600">{p.name}</p><p className="mt-2 text-[10px] text-slate-400">{p.categoryCode?`${p.categoryCode} · `:''}{p.unit}{p.stock!=null?` · On hand ${p.stock}`:''}</p></button>)}{!matches.length&&<p className="p-4 text-xs text-slate-400">No catalogue products match.</p>}</div>,document.body)}</div>;
}
