import {DocumentContent} from '@/modules/projects/components/document-actions';
import Link from 'next/link';
import {requireSession} from '@/core/auth/session';
import {assertCapability,can} from '@/core/permissions/check';
import {db} from '@/core/db/client';
import {documentScope} from '@/core/permissions/work-access';
import {workData} from '@/modules/projects/services/queries';
import {Field,Hidden,input,TaskCreator} from '@/modules/projects/components/forms';
import {ActionForm} from '@/components/ui/action-form';
import {Button} from '@/components/ui/button';
import {restoreDocument,editDocument} from '../../actions';
export default async function Page({params}:{params:Promise<{documentId:string}>}){
 const session=await requireSession();assertCapability(session,'projects.read');const {documentId}=await params,doc=await db.projectDocument.findFirstOrThrow({where:{AND:[documentScope(session),{id:documentId}]}}),data=await workData(session),revisions=await db.projectDocumentRevision.findMany({where:{organisationId:session.organisationId,documentId},orderBy:{version:'desc'}}),manage=can(session,'projects.manage');
 return <div className="mx-auto max-w-4xl space-y-6"><Link href={doc.projectId?`/projects/${doc.projectId}?tab=${doc.kind==='NOTE'?'Notes':'Docs'}`:`/projects/work/${doc.kind==='NOTE'?'notes':'docs'}`} className="text-xs text-[var(--color-ink-muted)]">← {doc.kind==='NOTE'?'Notes':'Documents'}</Link><header><p className="text-xs text-[var(--color-ink-faint)]">{doc.visibility} · Version {doc.version}</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">{doc.title}</h1></header><DocumentContent id={doc.id} body={doc.body} version={doc.version} editable={manage}/>{manage&&<><details className="rounded-2xl border border-[var(--color-border)] bg-white p-6"><summary className="cursor-pointer text-sm font-semibold">Edit document</summary><ActionForm action={editDocument.bind(null,doc.id)} className="mt-5 space-y-4"><Hidden name="version" value={doc.version}/><Field label="Title"><input required name="title" defaultValue={doc.title} className={input}/></Field><Field label="Content"><textarea name="body" defaultValue={doc.body} rows={16} className={input}/></Field><Button type="submit" variant="primary">Save new version</Button></ActionForm></details><TaskCreator projects={data.projects} projectId={doc.projectId??undefined} members={data.members} me={session.userId}/></>}<details className="rounded-2xl border border-[var(--color-border)] bg-white p-6"><summary className="cursor-pointer text-sm font-semibold">Version history ({revisions.length})</summary><div className="mt-5 space-y-5">{revisions.map(r=><details key={r.id}><summary className="cursor-pointer text-xs">Version {r.version} · {r.createdAt.toLocaleString('en-GB',{timeZone:'Europe/London'})}</summary><p className="mt-3 whitespace-pre-wrap text-sm text-[var(--color-ink-muted)]">{r.body}</p>{manage&&r.version!==doc.version&&<ActionForm action={restoreDocument.bind(null,doc.id)} className="mt-3"><Hidden name="version" value={doc.version}/><Hidden name="restoreVersion" value={r.version}/><Button type="submit">Restore as new version</Button></ActionForm>}</details>)}</div></details></div>;
}
