import Link from "next/link";
import { requireSession } from "@/core/auth/session";
import { assertCapability } from "@/core/permissions/check";
import { getFinanceCollections, recordFinanceCollection } from "@/modules/finance/services/collections";
import { money } from "@/modules/finance/domain/money";
import { ActionForm } from "@/modules/finance/components/action-form";
import { FinanceWorkspace, FinanceEntities, FinancePagination, financeField as field, financeSection as section } from "@/modules/finance/components/workspace";

export default async function Collections({ searchParams }: { searchParams: Promise<{ entity?: string; q?: string; view?: string; page?: string }> }) {
  const session = await requireSession();
  assertCapability(session, "finance.receivables.read");
  const filter = await searchParams, page = Number(filter.page || 0), data = await getFinanceCollections({ entityId: filter.entity, query: filter.q, view: filter.view || "OVERDUE", page }), entity = data.entity;
  const query = new URLSearchParams({ entity: entity?.id ?? "", q: filter.q ?? "", view: filter.view || "OVERDUE" });
  return <FinanceWorkspace title="Collections" description="Work the outstanding invoices: record contact, payment promises, disputes and follow-up dates. Activities retain their author and become part of the invoice timeline.">
    <FinanceEntities entities={data.entities} selected={entity?.id} path="/finance/collections"/>
    {entity && <><form className="grid items-end gap-3 sm:grid-cols-3"><input type="hidden" name="entity" value={entity.id}/><label className="text-xs">Work queue<select className={field} name="view" defaultValue={filter.view || "OVERDUE"}><option value="OVERDUE">Overdue</option><option value="ALL">All open receivables</option><option value="PROMISES">Payment promises</option><option value="DISPUTED">Disputes recorded</option></select></label><label className="text-xs">Customer / invoice<input className={field} name="q" defaultValue={filter.q}/></label><button className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-medium text-white">Apply</button></form>
      <section className={section}><h2 className="text-lg font-semibold">Customer follow-up</h2>{!data.rows.length && <p className="text-sm text-slate-500">No invoices match this queue.</p>}{data.rows.map(doc => <details key={doc.id} className="border-b border-slate-200 py-4"><summary className="cursor-pointer"><div className="inline-grid w-[95%] gap-2 text-sm sm:grid-cols-[2fr_1fr_1fr]"><span><strong>{doc.party?.name ?? "Customer"}</strong><span className="ml-3 text-slate-500">{doc.reference}</span></span><span className="text-slate-500">{doc.age} · Due {doc.dueAt?.toISOString().slice(0, 10) ?? "not set"}</span><strong className="sm:text-right">{money(doc.gross - doc.settled, doc.currency)}</strong></div></summary>
        <div className="mt-5 grid gap-6 lg:grid-cols-2"><div className="space-y-4"><Link className="text-sm text-blue-700" href={`/finance/documents/${doc.id}`}>Open invoice, evidence &amp; financial timeline →</Link>{doc.activities.map(activity => <article key={activity.id} className="border-l border-slate-200 pl-4"><p className="text-xs font-medium">{activity.kind.replaceAll("_", " ")} · {activity.createdAt.toISOString().slice(0, 10)}{activity.followUpAt ? ` · Follow up ${activity.followUpAt.toISOString().slice(0, 10)}` : ""}</p><p className="mt-1 whitespace-pre-wrap text-sm text-slate-600">{activity.notes}</p>{activity.promisedAmount !== null && <p className="mt-1 text-xs text-slate-500">Promised {money(activity.promisedAmount, doc.currency)}</p>}</article>)}{!doc.activities.length && <p className="text-sm text-slate-500">No collection activity recorded.</p>}</div>
          {session.capabilities.has("finance.receivables.manage") && <ActionForm action={recordFinanceCollection} label="Record collection activity"><input type="hidden" name="documentId" value={doc.id}/><label className="text-xs">Activity<select className={field} name="kind"><option value="CALL">Phone call</option><option value="EMAIL">Email recorded</option><option value="LETTER">Letter recorded</option><option value="PROMISE">Promise to pay</option><option value="DISPUTE">Dispute</option><option value="FOLLOW_UP">Follow-up</option><option value="RESOLVED">Resolution recorded</option></select></label><label className="block text-xs">Notes<textarea className={field} name="notes" required minLength={5} rows={3}/></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs">Promise amount ({doc.currency}, if applicable)<input className={field} name="promisedAmount"/></label><label className="text-xs">Promised / follow-up date<input className={field} name="followUpAt" type="date"/></label></div><p className="text-xs text-slate-500">This records what happened. Email and letter activities do not send messages. A dispute note does not automatically change the Sales credit policy or authorise a credit.</p></ActionForm>}
        </div>
      </details>)}<FinancePagination page={page} count={data.count} href={`/finance/collections?${query}`}/></section>
    </>}
  </FinanceWorkspace>;
}
