import {SourceGoals} from "@/modules/kpis/components/source-goals";
import Link from "next/link";
import { requireSession } from "@/core/auth/session";
import { assertCapability } from "@/core/permissions/check";
import { getFinanceLedger, getFinanceSubledgerReconciliation } from "@/modules/finance/services/reporting";
import { journalForm } from "@/modules/finance/services/commands";
import { money } from "@/modules/finance/domain/money";
import { ActionForm } from "@/modules/finance/components/action-form";
import { FinanceWorkspace, FinanceEntities, FinancePagination, financeField as field, financeSection as section } from "@/modules/finance/components/workspace";

export default async function GeneralLedger({ searchParams }: { searchParams: Promise<{ entity?: string; account?: string; start?: string; end?: string; q?: string; page?: string }> }) {
  const session = await requireSession();
  assertCapability(session, "finance.ledger.read");
  const filter = await searchParams, page = Number(filter.page || 0), data = await getFinanceLedger({ entityId: filter.entity, accountId: filter.account, start: filter.start, end: filter.end, query: filter.q, page }), entity = data.entity;
  const reconciliation = entity ? await getFinanceSubledgerReconciliation(entity.id) : null;
  const query = new URLSearchParams({ entity: entity?.id ?? "", account: filter.account ?? "", start: data.start.toISOString().slice(0, 10), end: data.end.toISOString().slice(0, 10), q: filter.q ?? "" });
  return <FinanceWorkspace title="General ledger" description="Posted balances, journals and the source transactions behind them. Draft journals appear only in the approval workspace and do not change these balances.">
    <SourceGoals session={session} prefixes={["finance."]}/>
    <FinanceEntities entities={data.entities} selected={entity?.id} path="/finance/ledger"/>
    {!entity ? <p className="text-sm">Set up the first books in Finance overview.</p> : <>
      <form className="grid items-end gap-3 sm:grid-cols-5"><input type="hidden" name="entity" value={entity.id}/><label className="text-xs">From<input name="start" type="date" className={field} defaultValue={data.start.toISOString().slice(0, 10)}/></label><label className="text-xs">Through<input name="end" type="date" className={field} defaultValue={data.end.toISOString().slice(0, 10)}/></label><label className="text-xs">Account<select name="account" className={field} defaultValue={filter.account}><option value="">All accounts</option>{data.accounts.map(account => <option key={account.id} value={account.id}>{account.code} · {account.name}</option>)}</select></label><label className="text-xs">Journal reference / description<input name="q" className={field} defaultValue={filter.q}/></label><button className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-medium text-white">Apply filters</button></form>
      <section className={section}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">Trial balance · {data.end.toISOString().slice(0, 10)}</h2><p className={`text-sm ${data.debit === data.credit ? "text-slate-600" : "text-rose-700"}`}>Debit {money(data.debit, entity.currency)} · Credit {money(data.credit, entity.currency)} · Difference {money(data.debit - data.credit, entity.currency)}</p></div>
        <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs text-slate-500"><th className="py-3">Account</th><th>Type</th><th className="text-right">Debit</th><th className="text-right">Credit</th></tr></thead><tbody>{data.accounts.map(account => { const balance = data.balances.find(row => row.accountId === account.id), net = (balance?._sum.debit ?? 0n) - (balance?._sum.credit ?? 0n); if (!net && !filter.account) return null; const drill = new URLSearchParams(query); drill.set("account", account.id); return <tr className="border-b border-slate-100" key={account.id}><td className="py-3"><Link className="text-blue-700" href={`/finance/ledger?${drill}`}>{account.code} · {account.name}</Link></td><td className="text-xs text-slate-500">{account.type}</td><td className="text-right tabular-nums">{net > 0n ? money(net, entity.currency) : "—"}</td><td className="text-right tabular-nums">{net < 0n ? money(-net, entity.currency) : "—"}</td></tr>; })}</tbody></table></div>
      </section>
      <section className={section}><h2 className="text-lg font-semibold">Account transactions</h2><p className="text-sm text-slate-500">{filter.account ? `Opening ${money(data.opening, entity.currency)} · Period movement ${money(data.movement, entity.currency)}` : "All authorised posted entries in the selected date range."}</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs text-slate-500"><th className="py-3">Date</th><th>Journal</th><th>Account / explanation</th><th>Dimensions</th><th className="text-right">Debit</th><th className="text-right">Credit</th></tr></thead><tbody>{data.entries.map(line => <tr key={line.id} className="border-b border-slate-100"><td className="whitespace-nowrap py-3 pr-3 text-xs">{line.journal.accountingDate.toISOString().slice(0, 10)}</td><td className="pr-3"><Link className="text-blue-700" href={`/finance/journals/${line.journal.id}`}>{line.journal.reference}</Link><p className="text-xs text-slate-500">{line.journal.sourceType}</p></td><td className="py-3 pr-3"><p>{line.account.code} · {line.account.name}</p><p className="text-xs text-slate-500">{line.description}</p></td><td className="text-xs text-slate-500">{[line.department, line.costCentre, line.site, line.projectId].filter(Boolean).join(" · ") || "—"}</td><td className="text-right tabular-nums">{line.debit ? money(line.debit, entity.currency) : "—"}</td><td className="text-right tabular-nums">{line.credit ? money(line.credit, entity.currency) : "—"}</td></tr>)}</tbody></table></div><FinancePagination page={page} count={data.count} href={`/finance/ledger?${query}`}/></section>
      {!!reconciliation?.rows.length && <section className={section}><h2 className="text-lg font-semibold">Subledger reconciliation</h2><p className="text-xs leading-5 text-slate-500">{reconciliation.basis}</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs text-slate-500"><th className="py-3">Subledger</th><th className="text-right">Source balance</th><th className="text-right">GL control</th><th className="text-right">Difference</th></tr></thead><tbody>{reconciliation.rows.map(row => <tr key={row.side} className="border-b border-slate-100"><td className="py-3"><Link className="text-blue-700" href={`/finance/${row.side === "AR" ? "receivables" : "payables"}?entity=${entity.id}`}>{row.side === "AR" ? "Receivables" : "Payables"}</Link></td><td className="text-right">{money(row.subledger, entity.currency)}</td><td className="text-right">{money(row.ledgerBalance, entity.currency)}</td><td className={`text-right ${row.difference ? "font-medium text-rose-700" : "text-slate-600"}`}>{money(row.difference, entity.currency)}</td></tr>)}</tbody></table></div></section>}
      {session.capabilities.has("finance.journal.create") && <details className={section}><summary className="cursor-pointer text-base font-semibold">Create a manual journal</summary><ActionForm action={journalForm} label="Create draft and request approval"><input type="hidden" name="entityId" value={entity.id}/><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs">Posting date<input name="date" type="date" className={field} required defaultValue={new Date().toISOString().slice(0, 10)}/></label><label className="text-xs">Explanation<input name="description" className={field} required minLength={5}/></label></div>{[0, 1, 2, 3].map(index => <fieldset className="grid gap-2 sm:grid-cols-4" key={index}><legend className="mb-2 text-xs font-medium">Line {index + 1}</legend><label className="text-xs">Account<select name="accountId" className={field}><option value="">Choose account</option>{data.accounts.filter(account => account.active && account.postingAllowed).map(account => <option key={account.id} value={account.id}>{account.code} · {account.name}</option>)}</select></label><label className="text-xs">Debit ({entity.currency})<input name="debit" className={field}/></label><label className="text-xs">Credit ({entity.currency})<input name="credit" className={field}/></label><label className="text-xs">Department<input name="department" className={field}/></label><label className="text-xs">Cost centre<input name="costCentre" className={field}/></label><label className="text-xs">Site ID / code<input name="site" className={field}/></label><label className="text-xs">Authorised project ID<input name="projectId" className={field}/></label></fieldset>)}<p className="text-xs text-slate-500">Leave unused lines empty. Requires a JOURNAL approval route. Another assigned approver reviews and posts from Accounting.</p></ActionForm></details>}
      <div className="flex flex-wrap gap-5 text-sm"><Link className="text-blue-700" href={`/finance/accounting?entity=${entity.id}`}>Journal approvals &amp; period close</Link>{session.capabilities.has("finance.configure") && <Link className="text-blue-700" href={`/finance/settings?entity=${entity.id}`}>Chart, dimensions &amp; posting profiles</Link>}</div>
    </>}
  </FinanceWorkspace>;
}
