import {CreateDialog} from "@/components/ui/create-dialog";
import Link from "next/link";
import {ArrowUpRight,Layers3} from "lucide-react";
import {requireSession} from "@/core/auth/session";
import {assertCapability,can} from "@/core/permissions/check";
import {CORE_CAPABILITIES} from "@/core/permissions/capabilities";
import {db} from "@/core/db/client";
import {ActionForm} from "@/components/ui/action-form";
import {Button} from "@/components/ui/button";
import {createPriceList} from "./actions";
const input="mt-2 w-full rounded-xl border border-[var(--color-border)] bg-white p-3 text-sm";
export default async function PricingPage(){
 const session=await requireSession();assertCapability(session,CORE_CAPABILITIES.pricingRead);
 const lists=await db.priceList.findMany({where:{organisationId:session.organisationId},include:{_count:{select:{entries:true,customerDefaults:true}}},orderBy:{name:'asc'}});
 return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-2xl font-semibold tracking-tight">Your pricing workspace</h2><p className="mt-2 text-sm text-[var(--color-ink-muted)]">Product and category pricing, discounts and currency-specific agreements.</p></div><Link href="/settings/imports" className="rounded-xl border border-[var(--color-border)] bg-white px-4 py-3 text-sm">CSV imports & templates</Link></div>{can(session,CORE_CAPABILITIES.pricingManage)&&<CreateDialog title="Create a pricelist" label="New pricelist"><ActionForm action={createPriceList} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs">List name<input name="name" required className={input}/></label><label className="text-xs">Selling currency<input name="currency" required defaultValue="GBP" maxLength={3} className={input}/></label><label className="text-xs">Base price currency<input name="baseCurrency" required defaultValue="GBP" maxLength={3} className={input}/></label><label className="text-xs">Exchange rate to selling currency<input name="exchangeRate" required type="number" min="0.000001" step="any" defaultValue="1" className={input}/></label><p className="text-xs text-[var(--color-ink-muted)] sm:col-span-2 lg:col-span-4">Percentage and monetary adjustments use standard product prices, converted using this explicit rate. Fixed prices are entered directly in the selling currency.</p><Button type="submit" variant="primary" className="justify-self-start">Create pricelist</Button></ActionForm></CreateDialog>}<div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{lists.map(l=><Link href={`/pricing/${l.id}`} key={l.id} className="group rounded-2xl border border-[var(--color-border)] bg-white p-6 transition hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-lg"><div className="mb-6 flex justify-between"><span className="rounded-xl bg-blue-50 p-3 text-blue-600"><Layers3 size={20}/></span><ArrowUpRight size={18} className="text-slate-400 group-hover:text-blue-600"/></div><h3 className="text-lg font-semibold">{l.name}</h3><p className="mt-2 text-sm text-slate-500">{l.currency} · {l._count.entries} rules</p><div className="mt-5 border-t border-slate-100 pt-4 text-xs text-slate-500">{l._count.customerDefaults} assigned customers · 1 {l.baseCurrency} = {l.exchangeRate} {l.currency}</div></Link>)}</div>{!lists.length&&<p className="rounded-2xl bg-white p-8 text-center text-slate-500">Create a retail, wholesale or customer-specific pricelist.</p>}</div>;
}
