"use client";
import {useState} from "react";
import {ActionForm} from "@/components/ui/action-form";
import {Button} from "@/components/ui/button";
import {saveRule} from "./actions";
import type {PriceRule} from "@/core/pricing/rules";
import {ProductSearch} from "./product-search";
const input="mt-2 block w-full rounded-xl border border-[var(--color-border)] bg-white p-3 text-sm";
export function RuleEditor({listId,currency,products,categories,rule}:{listId:string;currency:string;products:{id:string;name:string;code:string}[];categories:string[];rule?:PriceRule}) {
 const [scope,setScope]=useState(rule?.scope??'PRODUCT'),[method,setMethod]=useState(rule?.method??'FIXED');
 return <ActionForm action={saveRule.bind(null,listId)} className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><input type="hidden" name="ruleId" value={rule?.id??''}/><label className="text-xs">Applies to<select name="scope" value={scope} onChange={e=>setScope(e.target.value)} className={input}><option value="PRODUCT">A product</option><option value="CATEGORY">A category / catalogue code</option><option value="ALL">All products</option></select></label>{scope==='PRODUCT'&&<ProductSearch products={products} defaultId={rule?.productId??''} />}{scope==='CATEGORY'&&<label className="text-xs">Category code<select name="categoryCode" required defaultValue={rule?.categoryCode??''} className={input}><option value="">Choose category</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label>}<label className="text-xs">Calculation<select name="method" value={method} onChange={e=>setMethod(e.target.value)} className={input}><option value="FIXED">Fixed unit price ({currency})</option><option value="PERCENT">Percentage discount / markup</option><option value="AMOUNT">Monetary adjustment ({currency})</option></select></label><label className="text-xs">{method==='PERCENT'?'Discount % (negative = markup)':method==='AMOUNT'?`Adjustment ${currency} (+ adds, − discounts)`:`Unit price ${currency}`}<input key={method} required name="value" type="number" step="0.01" min={method==='FIXED'?0:method==='PERCENT'?-1000:undefined} max={method==='PERCENT'?100:undefined} defaultValue={rule?(method==='FIXED'?rule.unitPriceAmount/100:method==='PERCENT'?rule.percentage:rule.adjustmentAmount/100):undefined} className={input}/></label><label className="text-xs">Minimum line quantity<input required name="quantity" type="number" min={1} max={1000000} step={1} defaultValue={rule?.minimumQuantity??1} className={input}/></label><label className="text-xs">Priority within the same quantity<input required name="priority" type="number" min={0} max={1000} defaultValue={rule?.priority??0} className={input}/></label><label className="text-xs">Valid from<input name="validFrom" type="date" defaultValue={rule?.validFrom?.slice(0,10)} className={input}/></label><label className="text-xs">Valid until<input name="validTo" type="date" defaultValue={rule?.validTo?.slice(0,10)} className={input}/></label><p className="text-xs text-slate-500 sm:col-span-2 lg:col-span-3">Product rules win over category rules, then all-product rules. The highest applicable quantity break wins. Rules do not stack.</p><Button type="submit" variant="primary" className="justify-self-start">{rule?'Save changes':'Add pricing rule'}</Button></ActionForm>;
}
