import Link from "next/link";
import {Users,Settings,MessageCircle,ArrowUpRight,ShieldCheck} from "lucide-react";
import {requireSession} from "@/core/auth/session";
import {getNavigableModules} from "@/core/modules/runtime";
import {getAttentionItems} from "@/core/attention/aggregate";
import {can} from "@/core/permissions/check";
import {CORE_CAPABILITIES,CUSTOMER_CAPABILITIES} from "@/core/permissions/capabilities";
import {accentColorForModule} from "@/core/shared/module-colors";
export default async function HomePage(){
 const session=await requireSession();const [modules,attention]=await Promise.all([getNavigableModules(session),getAttentionItems(session)]);
 const apps=[...(can(session,CUSTOMER_CAPABILITIES.read)?[{id:'customers',name:'Customers',description:'Accounts & relationships',rootPath:'/customers',icon:Users}]:[]),...modules,...(can(session,CORE_CAPABILITIES.chatRead)?[{id:'chat',name:'Team chat',description:'Stay connected',rootPath:'/chat',icon:MessageCircle}]:[]),...(can(session,CORE_CAPABILITIES.usersManage)?[{id:'settings',name:'Company admin',description:'People & permissions',rootPath:'/settings',icon:Settings}]:[]),...(can(session,'atlas.companies.manage')?[{id:'platform',name:'Atlas console',description:'Company accounts',rootPath:'/atlas',icon:ShieldCheck}]:[])];
 return <div className="mx-auto max-w-6xl py-4 sm:py-10"><div className="mb-9 flex flex-wrap items-end justify-between gap-5"><div><p className="mb-3 text-[11px] font-semibold uppercase tracking-[.18em] text-blue-600">{session.organisationName}</p><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Your business, beautifully connected.</h1><p className="mt-3 text-sm text-slate-500">Welcome back, {session.userName.split(' ')[0]}. Where would you like to work?</p></div>{can(session,CORE_CAPABILITIES.modulesManage)&&<Link href="/apps" className="rounded-full border border-slate-200 bg-white px-5 py-2.5 text-sm font-medium text-slate-600 hover:border-blue-300">Manage apps →</Link>}</div><section aria-label="Business apps" className="rounded-[28px] border border-white bg-white/75 p-4 shadow-[0_8px_40px_#26377508] sm:p-8"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{apps.map(app=>{const Icon=app.icon,color=`var(--color-accent-${accentColorForModule(app.id)})`;return <Link key={app.id} href={app.rootPath} className="group flex min-h-40 flex-col items-center rounded-2xl p-4 text-center transition duration-200 hover:-translate-y-1 hover:bg-white hover:shadow-lg"><div className="flex size-[68px] items-center justify-center rounded-[21px] text-white shadow-[0_8px_18px_#223c6b18] ring-1 ring-white/20 transition group-hover:scale-105" style={{background:`linear-gradient(145deg,color-mix(in srgb,${color},white 18%),${color})`}}><Icon size={29} strokeWidth={1.6}/></div><h2 className="mt-4 text-sm font-semibold text-slate-800">{app.name}</h2><p className="mt-1 line-clamp-2 text-[11px] leading-relaxed text-slate-400">{app.description}</p></Link>;})}</div></section><section className="mt-8 rounded-2xl border border-slate-200/70 bg-white p-6"><div className="flex justify-between"><h2 className="text-sm font-semibold">Your attention, in one place</h2><span className="rounded-full bg-blue-50 px-3 py-1 text-[11px] text-blue-600">{attention.length} items</span></div><div className="mt-4 divide-y divide-slate-100">{attention.map(item=><Link key={item.id} href={item.href} className="flex items-center gap-3 py-3 text-sm text-slate-600 hover:text-blue-600"><span className={`size-2 rounded-full ${item.severity==='critical'?'bg-rose-500':item.severity==='warning'?'bg-amber-500':'bg-blue-500'}`}/><span className="flex-1">{item.label}</span><ArrowUpRight size={15}/></Link>)}{!attention.length&&<p className="py-4 text-sm text-slate-400">You’re all caught up.</p>}</div></section></div>;
}
