import { requireSession } from "@/core/auth/session";
import { assertCapability } from "@/core/permissions/check";
import { db } from "@/core/db/client";
import { saveKnowledge } from "@/core/service-work/knowledge";
import { ActionForm } from "@/components/ui/action-form";
import { Field, TextArea, Select } from "@/components/ui/service-fields";
import { Card } from "@/components/ui/card";
export async function Knowledge({ q = "", moduleId = "service" }: { q?: string; moduleId?: string }) {
  const session = await requireSession(); assertCapability(session, moduleId === "service" ? "service.case.read" : "tickets.ticket.read");
  const memberships = await db.serviceQueueMember.findMany({ where: { organisationId: session.organisationId, userId: session.userId }, select: { queueId: true } });
  const rows = await db.serviceKnowledge.findMany({ where: { organisationId: session.organisationId, AND:[{OR:[{status:"PUBLISHED"},{status:"DRAFT",ownerUserId:session.userId}]}], OR: [{ queueId: null }, { queueId: { in: memberships.map(member => member.queueId) } }], ...(q ? { AND: [{OR:[{status:"PUBLISHED"},{status:"DRAFT",ownerUserId:session.userId}]},{ OR: [{ title: { contains: q, mode: "insensitive" } }, { content: { contains: q, mode: "insensitive" } }, { keywords: { has: q } }] }] } : {}) }, orderBy: { reviewedAt: "desc" }, take: 100 });
  return <div className="space-y-6"><h2 className="text-3xl font-semibold">Knowledge & response library</h2><p className="text-sm text-slate-500">Reviewed answers and reusable response text. Case content is never published automatically.</p><form className="flex items-end gap-3"><Field title="Search articles" name="q" defaultValue={q}/><button className="atlas-secondary-button">Search</button></form><div className="grid gap-4 lg:grid-cols-2">{rows.map(row => <Card className="p-5" key={row.id}><p className="text-xs text-teal-700">{row.category} · Version {row.version} · {row.status.toLowerCase()}</p><h3 className="mt-2 text-lg font-semibold">{row.title}</h3><p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed text-slate-600">{row.content}</p>{(session.capabilities.has("service.queue.manage")||session.capabilities.has("tickets.queue.manage"))&&<details className="mt-4"><summary className="cursor-pointer text-xs text-teal-700">Revise as a new version</summary><ActionForm action={saveKnowledge} className="mt-4 space-y-3" label="Save new version"><input type="hidden" name="previousId" value={row.id}/><input type="hidden" name="queueId" value={row.queueId??""}/><Field title="Title" name="title" defaultValue={row.title} required/><Field title="Category" name="category" defaultValue={row.category}/><Field title="Keywords" name="keywords" defaultValue={row.keywords.join(", ")}/><TextArea title="Content" name="content" defaultValue={row.content} required/><Select title="Status" name="status" options={["DRAFT","PUBLISHED"]} defaultValue={row.status}/></ActionForm></details>}</Card>)}</div>{!rows.length && <p className="rounded-xl border border-slate-200 p-8 text-sm text-slate-500">No published articles match this search.</p>}{(session.capabilities.has("service.queue.manage") || session.capabilities.has("tickets.queue.manage")) && <details className="max-w-3xl rounded-xl border border-slate-200 p-5"><summary className="cursor-pointer font-medium">Write an article / reusable response</summary><ActionForm action={saveKnowledge} className="mt-4 space-y-3" label="Save article"><Field title="Title" name="title" required/><Field title="Category" name="category"/><Field title="Keywords · comma separated" name="keywords"/><TextArea title="Reviewed article or response text" name="content" required/><Select title="Status" name="status" options={["DRAFT", "PUBLISHED"]}/></ActionForm></details>}</div>;
}
