"use client";
import { useState } from "react";
import { ActionForm } from "@/components/ui/action-form";
import { Field, Select, TextArea, inputClass } from "@/components/ui/service-fields";
import { createWork } from "@/core/service-work/actions";
import { suggestedPriority, type serviceSchema } from "@/core/service-work/config";
import type { z } from "zod";
type Service = z.infer<typeof serviceSchema>;
export function RequestForm({ queues, kind = "TICKET", parentCaseId, parentId, initialQueueId, initialServiceId }: { initialQueueId?:string; initialServiceId?:string; queues: { id: string; name: string; services: Service[] }[]; kind?: string; parentCaseId?: string; parentId?: string }) {
  const [queueId, setQueue] = useState(initialQueueId ?? queues[0]?.id ?? ""), [serviceId, setService] = useState(initialServiceId ?? ""), [answers, setAnswers] = useState<Record<string, string | boolean>>({});
  const [priority,setPriority]=useState("NORMAL");
  const [impact, setImpact] = useState("INDIVIDUAL"), [urgency, setUrgency] = useState("NORMAL");
  const queue = queues.find(value => value.id === queueId), service = queue?.services.find(value => value.id === serviceId);
  return <ActionForm action={createWork} label={kind === "QUERY" ? "Create linked query" : "Create ticket"}>
    <input type="hidden" name="kind" value={kind}/><input type="hidden" name="parentCaseId" value={parentCaseId ?? ""}/><input type="hidden" name="parentId" value={parentId ?? ""}/><input type="hidden" name="answers" value={JSON.stringify(answers)}/>
    <div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-medium text-slate-600">Receiving team<select className={inputClass} name="queueId" value={queueId} onChange={event => { setQueue(event.target.value); setService(""); setAnswers({}); }} required><option value="">Choose team</option>{queues.map(value => <option key={value.id} value={value.id}>{value.name}</option>)}</select></label><label className="text-xs font-medium text-slate-600">Service / request<select className={inputClass} name="serviceId" value={serviceId} onChange={event => { setService(event.target.value); setAnswers({}); }}><option value="">General request</option>{queue?.services.map(value => <option value={value.id} key={value.id}>{value.name}</option>)}</select></label></div>
    <Field title={kind === "QUERY" ? "What do you need from this team?" : "Subject"} name="subject" required maxLength={250}/><TextArea title="Details and requested action" name="description" required/>
    {service && <div className="space-y-3 rounded-xl bg-slate-50 p-5"><h3 className="text-sm font-semibold">{service.name}</h3>{service.fields.map(field => <label className="block text-xs font-medium" key={field.key}>{field.label}{field.required ? " *" : ""}{field.type === "select" ? <select className={inputClass} required={field.required} value={String(answers[field.key] ?? "")} onChange={event => setAnswers({ ...answers, [field.key]: event.target.value })}><option value="">Choose</option>{field.options.map(value => <option key={value}>{value}</option>)}</select> : field.type === "textarea" ? <textarea className={inputClass} required={field.required} onChange={event => setAnswers({ ...answers, [field.key]: event.target.value })}/> : <input className={field.type === "checkbox" ? "ml-3" : inputClass} type={field.type} required={field.required} onChange={event => setAnswers({ ...answers, [field.key]: field.type === "checkbox" ? event.target.checked : event.target.value })}/>}</label>)}{service.approval && <p className="text-xs text-amber-800">This request needs approval before resolution.</p>}{service.requiredEvidence && <p className="text-xs text-slate-500">Attach the required evidence after creating this ticket.</p>}</div>}
    <details className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer text-sm font-medium">Impact, urgency and classification</summary><div className="mt-4 grid gap-3 sm:grid-cols-2"><Select title="Ticket type" name="type" defaultValue="SERVICE_REQUEST" options={["INCIDENT", "SERVICE_REQUEST", "TASK", "PROBLEM", "CHANGE", "ACCESS_REQUEST"]}/><Select title="Priority" name="priority" options={["LOW", "NORMAL", "HIGH", "URGENT"]} value={priority} onChange={event=>setPriority(event.target.value)}/><Select title="Impact" name="impact" options={["INDIVIDUAL", "TEAM", "DEPARTMENT", "BUSINESS"]} value={impact} onChange={event => {setImpact(event.target.value);setPriority(suggestedPriority(event.target.value,urgency));}}/><Select title="Urgency" name="urgency" options={["LOW", "NORMAL", "HIGH", "IMMEDIATE"]} value={urgency} onChange={event => {setUrgency(event.target.value);setPriority(suggestedPriority(impact,event.target.value));}}/></div><p className="mt-2 text-xs text-slate-500">Suggested priority: {suggestedPriority(impact, urgency).toLowerCase()}.</p><Field title="Priority override reason, if applicable" name="priorityReason"/><Field title="Affected service or asset reference" name="asset"/></details>
    <details className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer text-sm font-medium">Problem / controlled change</summary><div className="mt-4 space-y-3"><TextArea title="Problem statement / known symptoms" name="problem"/><TextArea title="Workaround" name="workaround"/><TextArea title="Root cause" name="rootCause"/><TextArea title="Risk and impact" name="risk"/><TextArea title="Implementation plan" name="implementationPlan"/><TextArea title="Rollback plan" name="rollbackPlan"/><TextArea title="Testing plan" name="testingPlan"/><Field title="Planned date" name="schedule" type="date"/></div></details>
  </ActionForm>;
}
