import { Button } from "@/components/ui/button";
import Link from "next/link";
import { requireSession } from "@/core/auth/session";
import { assertCapability } from "@/core/permissions/check";
import { workList, deskQueues } from "@/core/service-work/queries";
import { slaState } from "@/core/service-work/sla";
import { Card } from "@/components/ui/card";
import { inputClass } from "@/components/ui/service-fields";

const label = (value: string) => value.replaceAll("_", " ").toLowerCase();
export async function WorkList({ filters, kind = "TICKET" }: { filters: { q?: string; mine?: string; queueId?: string; status?: string; type?: string; breach?: string }; kind?: string }) {
  const session = await requireSession();
  assertCapability(session, kind === "TICKET" ? "tickets.ticket.read" : "service.ticket.read");
  const [rows, queues] = await Promise.all([workList(session, { ...filters, kind, mine: filters.mine === "1", breach: filters.breach === "1" }), deskQueues(session)]);
  const open = rows.filter(row => !["RESOLVED", "CLOSED", "CANCELLED"].includes(row.status));
  return <div className="space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-teal-700">{kind === "QUERY" ? "Cross-team collaboration" : "Internal service desk"}</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">{kind === "QUERY" ? "Queries" : filters.mine ? "My tickets" : "Tickets"}</h2><p className="mt-2 text-sm text-slate-500">{kind === "QUERY" ? "Clear requests, accountable teams and a direct path back to the customer." : "Every request has a home. Keep your teams moving."}</p></div>{kind === "TICKET" && session.capabilities.has("tickets.ticket.create") && <Link className="inline-flex items-center rounded-full bg-[var(--color-atlas-blue)] px-5 py-2.5 text-sm font-semibold text-white hover:bg-[var(--color-atlas-blue-hover)] focus-visible:outline-2 focus-visible:outline-offset-2" href="/tickets/create">New ticket</Link>}</div>
    <div className="grid gap-3 sm:grid-cols-4">{[{ title: "Open in this view", value: open.length }, { title: "Unassigned", value: open.filter(row => !row.ownerUserId).length }, { title: "SLA breached", value: open.filter(row => slaState(row.resolutionDueAt, row.pausedAt, row.resolvedAt) === "BREACHED").length }, { title: "Waiting", value: open.filter(row => row.status.startsWith("PENDING")).length }].map(metric => <Card className="p-5" key={metric.title}><p className="text-xs text-slate-500">{metric.title}</p><p className="mt-2 text-3xl font-semibold tabular-nums">{metric.value}</p></Card>)}</div>
    <form className="flex flex-wrap items-end gap-3"><label className="min-w-60 flex-1 text-xs">Find work<input name="q" className={inputClass} placeholder="Reference or subject" defaultValue={filters.q}/></label><label className="text-xs">Queue<select name="queueId" defaultValue={filters.queueId} className={inputClass}><option value="">All available queues</option>{queues.map(queue => <option key={queue.id} value={queue.id}>{queue.name}</option>)}</select></label><label className="text-xs">Status<select name="status" className={inputClass} defaultValue={filters.status}><option value="">All statuses</option>{["NEW", "ASSIGNED", "IN_PROGRESS", "PENDING_REQUESTER", "PENDING_INTERNAL", "ANSWERED", "RESOLVED", "CLOSED", "CANCELLED"].map(status => <option key={status} value={status}>{label(status)}</option>)}</select></label>{filters.mine && <input type="hidden" name="mine" value="1"/>}<Button variant="secondary">Filter</Button></form>
    <Card className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs text-slate-500"><tr>{["Work", "Queue", "Priority", "Status", "Resolution SLA"].map(name => <th className="px-5 py-3 font-medium" key={name}>{name}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map(row => { const state = slaState(row.resolutionDueAt, row.pausedAt, row.resolvedAt); return <tr key={row.id} className="hover:bg-slate-50"><td className="px-5 py-4"><Link href={`/${row.kind === "QUERY" ? "service/queries" : "tickets"}/${row.id}`} className="font-medium text-slate-900"><span className="block text-xs text-teal-700">{row.number}{row.mergedIntoId ? " · merged" : ""}</span><span className="mt-1 block">{row.subject}</span></Link></td><td className="px-5 py-4 text-slate-500">{row.queue.name}</td><td className="px-5 py-4 capitalize">{label(row.priority)}</td><td className="px-5 py-4 capitalize">{label(row.status)}</td><td className="px-5 py-4"><span className={`text-xs font-medium ${state === "BREACHED" ? "text-red-700" : state === "AT_RISK" ? "text-amber-700" : "text-slate-500"}`}>{label(state)}</span><p className="mt-1 text-xs text-slate-400">{row.resolutionDueAt?.toLocaleString("en-GB", { timeZone: "Europe/London" })}</p></td></tr>; })}</tbody></table>{!rows.length && <div className="p-12 text-center"><h3 className="font-semibold">A clear queue</h3><p className="mt-2 text-sm text-slate-500">No work matches these filters.</p></div>}</Card><p className="text-xs text-slate-400">Showing the latest {rows.length} records, up to 100. Measures describe this filtered view.</p>
  </div>;
}
