import {db} from '@/core/db/client';
import type {Session} from '@/core/auth/session';
import {ActionForm} from '@/components/ui/action-form';
import {Button} from '@/components/ui/button';
import {resolveComment,addComment,linkWork} from '@/app/(app)/projects/actions';
import {resolveWorkLink} from '../services/links';
import {Field,Hidden,Select,input,type Person} from './forms';
import Link from 'next/link';
/** Caller must resolve source access before rendering. Targets are checked separately. */
export async function Discussion({session,projectId,taskId,members,manage}:{session:Session;projectId?:string|null;taskId?:string;members:Person[];manage:boolean}){
 const scope={organisationId:session.organisationId,projectId:projectId??null,taskId:taskId??null},[comments,links]=await Promise.all([db.projectComment.findMany({where:scope,orderBy:{createdAt:'asc'}}),db.projectWorkLink.findMany({where:scope})]),cards=await Promise.all(links.map(async l=>({id:l.id,card:await resolveWorkLink(session,l)}))),names=new Map(members.map(m=>[m.userId,m.user.name]));
 return <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-[var(--color-border)] bg-white p-6"><h2 className="text-lg font-semibold">Discussion</h2><div className="mt-5 space-y-5">{comments.map(c=><article key={c.id}><p className="text-xs text-[var(--color-ink-faint)]">{names.get(c.authorUserId)??'Former member'} · {c.createdAt.toLocaleString('en-GB',{timeZone:'Europe/London'})}</p><p className="mt-2 whitespace-pre-wrap text-sm">{c.body}</p><p className="mt-2 text-xs text-[var(--color-ink-faint)]">{c.resolved?'Resolved':'Open'}</p>{(manage||c.authorUserId===session.userId)&&<ActionForm action={resolveComment.bind(null,c.id)} className="mt-2"><Hidden name="resolved" value={c.resolved?'false':'true'}/><Button type="submit" variant="ghost">{c.resolved?'Reopen':'Resolve'}</Button></ActionForm>}</article>)}</div><ActionForm action={addComment} className="mt-6 space-y-3"><Hidden name="projectId" value={projectId}/><Hidden name="taskId" value={taskId}/><Field label="Add a comment"><textarea required name="body" rows={3} className={input}/></Field><details><summary className="cursor-pointer text-xs text-[var(--color-ink-muted)]">Mention people</summary><div className="mt-3 flex flex-wrap gap-3">{members.map(m=><label key={m.userId} className="flex gap-2 text-xs"><input type="checkbox" name="mention" value={m.userId}/>{m.user.name}</label>)}</div></details><Button type="submit">Post comment</Button></ActionForm></section><section className="rounded-2xl border border-[var(--color-border)] bg-white p-6"><h2 className="text-lg font-semibold">Linked work</h2><div className="mt-5 space-y-3">{cards.map(({id,card})=>card?<Link key={id} href={card.href} className="block rounded-xl border border-[var(--color-border)] p-4"><p className="text-sm font-medium">{card.title}</p><p className="mt-1 text-xs text-[var(--color-ink-muted)]">{card.detail.replaceAll('_',' ')}</p></Link>:<div key={id} className="rounded-xl border border-[var(--color-border)] p-4 text-sm text-[var(--color-ink-muted)]">Restricted Atlas record</div>)}</div>{manage&&<details className="mt-5"><summary className="cursor-pointer text-xs">Link an Atlas record</summary><ActionForm action={linkWork} className="mt-4 space-y-3"><Hidden name="projectId" value={projectId}/><Hidden name="taskId" value={taskId}/><Field label="Type"><Select name="targetEntity" values={['ProjectTask','ProjectDocument','Party','Product','SalesOrder','Quote']}/></Field><Field label="Record ID"><input required name="targetId" className={input}/></Field><Button type="submit">Link record</Button></ActionForm></details>}</section></div>;
}
