import {ActionForm} from '@/components/ui/action-form';
import {Button} from '@/components/ui/button';
import {CreateDialog} from '@/components/ui/create-dialog';
import {createTask,createProject} from '@/app/(app)/projects/actions';
import {PRIORITIES,PROJECT_TYPES} from '../domain/work';
export const input='mt-1.5 w-full rounded-lg border border-[var(--color-border)] bg-white px-3 py-2 text-sm';
export function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs font-medium text-[var(--color-ink-muted)]">{label}{children}</label>;}
export function Hidden({name,value}:{name:string;value:string|number|null|undefined}){return <input type="hidden" name={name} value={value??''}/>;}
export function Select({name,values,value}:{name:string;values:readonly string[];value?:string}){return <select key={`${name}:${value??''}`} name={name} defaultValue={value} className={input}>{values.map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select>;}
export type Person={userId:string;user:{name:string}};
export function PeopleSelect({members,name='assigneeUserId',value}:{members:Person[];name?:string;value?:string}){return <select key={`${name}:${value??''}`} name={name} defaultValue={value} className={input}>{members.map(m=><option key={m.userId} value={m.userId}>{m.user.name}</option>)}</select>;}
export function TaskCreator({projects,members,projectId,parentTaskId,me}:{projects:Array<{id:string;name:string}>;members:Person[];projectId?:string;parentTaskId?:string;me:string}){return <CreateDialog title={parentTaskId?'New subtask':'Capture a task'} label={parentTaskId?'Add subtask':'New task'}><ActionForm action={createTask} className="mt-5 space-y-4"><Field label="What needs doing?"><input autoFocus required name="title" maxLength={300} className={input} placeholder="A clear next action"/></Field><Hidden name="parentTaskId" value={parentTaskId}/>{projectId?<Hidden name="projectId" value={projectId}/>:<Field label="Project"><select name="projectId" className={input}><option value="">Personal task · private</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>}<details><summary className="cursor-pointer text-xs text-[var(--color-ink-muted)]">Assignment, dates and details</summary><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Accountable owner"><PeopleSelect members={members} value={me}/></Field><Field label="Due date"><input type="date" name="dueAt" className={input}/></Field><Field label="Start date"><input type="date" name="startAt" className={input}/></Field><Field label="Priority"><Select name="priority" values={PRIORITIES} value="NORMAL"/></Field><Field label="Effort (minutes)"><input name="estimatedMinutes" type="number" min="0" defaultValue="0" className={input}/></Field><Field label="Description"><textarea name="description" className={input}/></Field></div></details><Button type="submit" variant="primary">Create task</Button></ActionForm></CreateDialog>;}
export function ProjectCreator({members,me,customers,teams=[]}:{members:Person[];me:string;customers:Array<{id:string;name:string}>;teams?:Array<{id:string;name:string}>}){return <CreateDialog title="New project" label="New project"><ActionForm action={createProject} className="mt-5 space-y-4"><Field label="Project name"><input required name="name" maxLength={200} className={input}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Owner"><PeopleSelect members={members} name="ownerUserId" value={me}/></Field><Field label="Target date"><input type="date" name="targetAt" className={input}/></Field></div><details><summary className="cursor-pointer text-xs text-[var(--color-ink-muted)]">Visibility and context</summary><div className="mt-4 space-y-4"><Field label="Visibility"><Select name="visibility" values={['PRIVATE','INVITE_ONLY','TEAM','COMPANY']}/></Field><Field label="Team"><select name="teamId" className={input}><option value="">No team</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><Field label="Type"><Select name="projectType" values={PROJECT_TYPES} value="TEAM"/></Field><Field label="Customer / supplier (optional)"><select name="partyId" className={input}><option value="">No business account</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Description"><textarea name="notes" className={input}/></Field></div></details><Button type="submit" variant="primary">Create project</Button></ActionForm></CreateDialog>;}
