'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ActionForm} from '@/components/ui/action-form';
import {Button} from '@/components/ui/button';
import {rescheduleTask} from '@/app/(app)/projects/actions';
import {DAY,dayNumber,isoDay,duration,finishVariance,ganttWindow,ganttSummary,type GanttTask,type GanttMilestone,type GanttBaseline} from '../domain/gantt';
import {scheduleForecast,dependencyConflicts,done} from '../domain/work';
const field='rounded-lg border border-[var(--color-border)] bg-white px-3 py-2 text-sm';
const date=(value:string|null)=>value?new Date(value).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'2-digit',timeZone:'UTC'}):'Not set';
export function Gantt({tasks,milestones=[],baselines=[],targetAt=null,today}:{tasks:GanttTask[];milestones?:GanttMilestone[];baselines?:GanttBaseline[];targetAt?:string|null;today:string}){
 const [zoom,setZoom]=useState('Weeks'),[anchor,setAnchor]=useState<number|null>(null),[selected,setSelected]=useState<string|null>(null),[baselineId,setBaseline]=useState(baselines[0]?.id??''),[query,setQuery]=useState(''),[openOnly,setOpenOnly]=useState(false),[criticalOnly,setCriticalOnly]=useState(false);
 const work=tasks.map(t=>({...t,weight:1,startAt:t.startAt?new Date(t.startAt):null,dueAt:t.dueAt?new Date(t.dueAt):null})),ids=new Set(tasks.map(t=>t.id)),edges=tasks.flatMap(t=>t.dependencies).filter(e=>ids.has(e.predecessorId)&&ids.has(e.successorId)),forecast=scheduleForecast(work,edges,targetAt?new Date(targetAt):null),conflicts=dependencyConflicts(work,edges),critical=new Set(forecast.critical),summary=ganttSummary(tasks,dayNumber(today));
 const rows=tasks.filter(t=>(!openOnly||!done(t.status))&&(!criticalOnly||critical.has(t.id))&&`${t.title} ${t.owner} ${t.project}`.toLowerCase().includes(query.toLowerCase())),view=ganttWindow(rows,milestones,anchor,zoom,dayNumber(today)),width=view.count*view.pixels,rowHeight=62,baseline=baselines.find(b=>b.id===baselineId),base=new Map(baseline?.tasks.map(t=>[t.id,t])??[]),task=tasks.find(t=>t.id===selected),index=new Map(rows.map((t,i)=>[t.id,i]));
 const x=(value:string)=> (dayNumber(value)-view.start)*view.pixels;
 const ticks=Array.from({length:view.count},(_,i)=>{const d=new Date((view.start+i)*DAY);return {i,d,label:d.toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'UTC'})};}).filter(t=>zoom==='Days'||(zoom==='Weeks'?t.i%7===0:t.d.getUTCDate()===1));
 const bar=(start:string|null,end:string|null)=>{if(!start&&!end)return null;const left=x(start??end!),right=x(end??start!)+view.pixels;if(right<=0||left>=width)return null;return {left:Math.max(0,left),width:Math.max(3,Math.min(width,right)-Math.max(0,left))};};
 return <section aria-label="Project Gantt" className="min-w-0 space-y-4">
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Open tasks',summary.open],['Overdue',summary.overdue],['Need dates',summary.unscheduled],['Open task estimates',`${summary.hours.toFixed(1)}h`]].map(([label,value])=><div key={label} className="rounded-xl border border-[var(--color-border)] bg-white p-4"><p className="text-xs text-[var(--color-ink-muted)]">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>)}</div>
  <div className="rounded-xl border border-[var(--color-border)] bg-white p-4 text-sm"><strong>Schedule outlook</strong><p className="mt-2">Forecast {date(forecast.forecast?.toISOString()??null)}{targetAt?` · Target ${date(targetAt)}`:''} · {forecast.critical.length} critical tasks · {conflicts.length} dependency conflicts</p><p className="mt-2 text-xs text-[var(--color-ink-muted)]">Calendar days. Forecast uses dated, unfinished tasks; {forecast.missingDates} need dates. Critical tasks have no spare days against {targetAt?'the project target':'the forecast finish'}. Saving a date moves only that task.</p></div>
  <div className="flex flex-wrap items-end gap-3"><label className="grid gap-1 text-xs">Find task or owner<input aria-label="Find task or owner" className={field} value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="grid gap-1 text-xs">Zoom<select aria-label="Gantt zoom" className={field} value={zoom} onChange={e=>setZoom(e.target.value)}>{['Days','Weeks','Months'].map(z=><option key={z}>{z}</option>)}</select></label>{baselines.length>0&&<label className="grid min-w-0 gap-1 text-xs">Compare baseline<select aria-label="Compare baseline" className={`${field} max-w-64`} value={baselineId} onChange={e=>setBaseline(e.target.value)}><option value="">No comparison</option>{baselines.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>}<Button onClick={()=>setAnchor(view.start-view.count)}>Earlier</Button><Button onClick={()=>setAnchor(dayNumber(today)-3)}>Today</Button><Button onClick={()=>{setAnchor(null);setZoom('Months');}}>Whole plan</Button><Button onClick={()=>setAnchor(view.start+view.count)}>Later</Button></div>
  <div className="flex flex-wrap gap-5 text-xs"><label className="flex items-center gap-2"><input type="checkbox" checked={openOnly} onChange={e=>setOpenOnly(e.target.checked)}/>Open work only</label><label className="flex items-center gap-2"><input type="checkbox" checked={criticalOnly} onChange={e=>setCriticalOnly(e.target.checked)}/>Critical tasks only</label><span>Blue: planned · Red: critical · Grey: completed · Thin grey: baseline · ◆ milestone</span></div>
  <p className="text-xs text-[var(--color-ink-muted)]">{date(isoDay(view.start))} – {date(isoDay(view.end))} · {rows.length} tasks. Select a task to see its detail and edit dates.{view.last>view.end||view.first<view.start?' Some dates are outside this window; use Earlier / Later.':''}</p>
  <div className="max-h-[650px] overflow-auto rounded-xl border border-[var(--color-border)] bg-white" tabIndex={0} aria-label="Scrollable Gantt chart">
   <div style={{width:width+220,minWidth:'100%'}}>
    <div className="sticky top-0 z-30 flex h-12 border-b border-[var(--color-border)] bg-slate-50"><div className="sticky left-0 z-40 w-[220px] shrink-0 border-r border-[var(--color-border)] bg-slate-50 p-4 text-xs font-semibold">Task · Owner · Duration</div><div className="relative" style={{width}}>{ticks.map(t=><span key={t.i} className="absolute top-4 whitespace-nowrap border-l border-slate-300 pl-1 text-[10px]" style={{left:t.i*view.pixels}}>{t.label}</span>)}</div></div>
    <div className="relative">
     {rows.map(t=>{const planned=bar(t.startAt,t.dueAt),snapshot=base.get(t.id),shadow=snapshot?bar(snapshot.startAt,snapshot.dueAt):null,variance=finishVariance(t,snapshot),days=duration(t);return <div key={t.id} className="flex border-b border-[var(--color-border)]" style={{height:rowHeight}}>
      <button type="button" onClick={()=>setSelected(t.id)} className={`sticky left-0 z-20 w-[220px] shrink-0 border-r border-[var(--color-border)] px-3 py-2 text-left hover:bg-blue-50 ${selected===t.id?'bg-blue-50':'bg-white'}`}><span className="block truncate text-xs font-medium">{t.parentTaskId?'↳ ':''}{t.title}</span><span className="mt-1 block truncate text-[10px] text-[var(--color-ink-muted)]">{t.owner} · {days===null?'Dates incomplete':`${days}d`} · {t.status.replaceAll('_',' ')}</span></button>
      <div className="relative" style={{width,backgroundImage:`repeating-linear-gradient(to right,transparent 0,transparent ${view.pixels*7-1}px,#e2e8f0 ${view.pixels*7-1}px,#e2e8f0 ${view.pixels*7}px)`}}>{shadow&&<div title={`Baseline: ${date(snapshot!.startAt)} – ${date(snapshot!.dueAt)}`} className="absolute top-11 h-1.5 rounded bg-slate-400" style={shadow}/ >}{planned?<button type="button" aria-label={`Schedule ${t.title}`} title={`${date(t.startAt)} – ${date(t.dueAt)}${variance!==null?` · ${variance>0?'+':''}${variance}d against baseline`:''}`} onClick={()=>setSelected(t.id)} className={`absolute top-3 h-6 overflow-hidden rounded px-2 text-left text-[10px] text-white ${done(t.status)?'bg-slate-500':critical.has(t.id)?'bg-red-600':'bg-blue-600'} ${days===null?'border-2 border-dashed border-white':''}`} style={planned}>{view.pixels>=16?t.title:''}</button>:<span className="absolute left-3 top-5 text-[10px] text-slate-500">{!t.startAt&&!t.dueAt?'Unscheduled':'Outside window'}</span>}</div>
     </div>;})}
     {dayNumber(today)>=view.start&&dayNumber(today)<=view.end&&<div aria-label="Today marker" className="pointer-events-none absolute top-0 bottom-0 z-10 border-l-2 border-emerald-500" style={{left:220+x(today)}}><span className="bg-emerald-600 px-1 text-[9px] text-white">Today</span></div>}
     <svg aria-label="Task dependency connectors" className="pointer-events-none absolute left-[220px] top-0" style={{width,height:rows.length*rowHeight,overflow:'hidden'}}><defs><marker id="gantt-arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="#64748b"/></marker></defs>{edges.map((e,i)=>{const a=rows.find(t=>t.id===e.predecessorId),b=rows.find(t=>t.id===e.successorId);if(!a||!b)return null;const source=e.kind.startsWith('START')?a.startAt:a.dueAt,target=e.kind.endsWith('START')?b.startAt:b.dueAt;if(!source||!target)return null;const sx=x(source)+(e.kind.startsWith('FINISH')?view.pixels:0),tx=x(target)+(e.kind.endsWith('FINISH')?view.pixels:0),sy=index.get(a.id)!*rowHeight+25,ty=index.get(b.id)!*rowHeight+25;if(Math.max(sx,tx)<0||Math.min(sx,tx)>width)return null;return <path key={i} d={`M${sx},${sy} H${sx+8} V${ty} H${tx}`} fill="none" stroke="#64748b" strokeWidth="1.5" markerEnd="url(#gantt-arrow)"><title>{`${a.title} → ${b.title} · ${e.kind.replaceAll('_',' ')} · ${e.lagDays}d lag`}</title></path>;})}</svg>
    </div>
    {milestones.map(m=><div key={m.id} className="flex h-10 border-t border-[var(--color-border)]"><div className="sticky left-0 z-20 w-[220px] shrink-0 truncate bg-slate-50 p-3 text-xs">◆ {m.name}{m.complete?' · Complete':''}</div><div className="relative" style={{width}}>{x(m.targetAt)>=0&&x(m.targetAt)<width&&<span title={`${m.name} · ${date(m.targetAt)}`} className="absolute top-2 text-purple-700" style={{left:x(m.targetAt)}}>◆</span>}</div></div>)}

   </div>
  </div>
  {!rows.length&&<p className="rounded-xl border border-dashed border-slate-300 p-6 text-sm">No tasks match this view. Clear filters or add a task.</p>}
  {task&&<section aria-label="Selected task details" className="rounded-xl border border-blue-200 bg-white p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{task.title}</h3><p className="mt-1 text-xs text-[var(--color-ink-muted)]">{task.project} · {task.owner} · {task.priority} · {(task.estimatedMinutes/60).toFixed(1)}h estimate</p></div><Button onClick={()=>setSelected(null)}>Close details</Button></div><p className="mt-3 text-sm">{date(task.startAt)} → {date(task.dueAt)} · {duration(task)??'Unknown'} calendar days{forecast.slack[task.id]!==undefined?` · ${forecast.slack[task.id]}d slack`:''}</p>{base.has(task.id)&&<p className="mt-2 text-xs">Baseline finish {date(base.get(task.id)!.dueAt)} · {finishVariance(task,base.get(task.id))??'Unknown'}d finish variance</p>}<Link className="mt-3 inline-block text-sm text-blue-700" href={`/projects/tasks/${task.id}`}>Open full task →</Link>{task.dependencies.filter(e=>ids.has(e.predecessorId)).map((e,i)=><p key={i} className="mt-2 text-xs">Depends on {tasks.find(t=>t.id===e.predecessorId)?.title} · {e.kind.replaceAll('_',' ').toLowerCase()} · {e.lagDays}d lag</p>)}{task.editable&&<ActionForm key={`${task.id}:${task.version}`} action={rescheduleTask.bind(null,task.id)} className="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="version" value={task.version}/><label className="grid gap-1 text-xs">Task start<input required aria-label="Task start" name="startAt" type="date" defaultValue={task.startAt?.slice(0,10)} className={field}/></label><label className="grid gap-1 text-xs">Task finish<input required aria-label="Task finish" name="dueAt" type="date" defaultValue={task.dueAt?.slice(0,10)} className={field}/></label><Button type="submit" variant="primary">Save task dates</Button></ActionForm>}</section>}
  {conflicts.length>0&&<details className="rounded-xl border border-amber-200 bg-amber-50 p-4"><summary className="cursor-pointer text-sm font-medium">Review {conflicts.length} dependency conflicts</summary>{conflicts.map((c,i)=><p key={i} className="mt-3 text-xs">{c.predecessor.title} → {c.successor.title}: successor needs {c.days} more days. Review the task dates and dependency type.</p>)}</details>}
  {baseline&&<details className="rounded-xl border border-[var(--color-border)] bg-white p-4"><summary className="cursor-pointer text-sm font-medium">Baseline comparison · {baseline.name}</summary><p className="mt-2 text-xs text-[var(--color-ink-muted)]">Saved {date(baseline.createdAt)}. Positive finish variance means later than the saved plan.</p><div className="mt-3 overflow-auto"><table className="w-full text-left text-xs"><thead><tr><th className="p-2">Task</th><th className="p-2">Baseline finish</th><th className="p-2">Current finish</th><th className="p-2">Variance</th></tr></thead><tbody>{rows.map(t=>{const b=base.get(t.id),v=finishVariance(t,b);return <tr key={t.id} className="border-t border-slate-100"><td className="p-2">{t.title}</td><td className="p-2">{b?date(b.dueAt):'Added since baseline'}</td><td className="p-2">{date(t.dueAt)}</td><td className={`p-2 ${v!==null&&v>0?'text-red-700':''}`}>{v===null?'—':`${v>0?'+':''}${v}d`}</td></tr>;})}</tbody></table></div></details>}
 </section>;
}
