import {Gantt} from './gantt';
import type {GanttMilestone,GanttBaseline} from '../domain/gantt';
import Link from 'next/link';
import {ActionForm} from '@/components/ui/action-form';
import {Button} from '@/components/ui/button';
import {changeTaskStatus,planToday} from '@/app/(app)/projects/actions';
import {TASK_STATUSES,done} from '../domain/work';
import {Hidden,Select,type Person} from './forms';
import type {workData} from '../services/queries';
type Tasks=Awaited<ReturnType<typeof workData>>['tasks'];
export function dateLabel(date:Date|null){return date?date.toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'Europe/London'}):'No date';}
export function TaskViews({tasks,members,layout='list',manage=false,group='status',milestones=[],baselines=[],targetAt=null}:{tasks:Tasks;members:Person[];layout?:string;manage?:boolean;group?:string;milestones?:GanttMilestone[];baselines?:GanttBaseline[];targetAt?:string|null}){
 const names=new Map(members.map(m=>[m.userId,m.user.name]));
 const card=(t:Tasks[number])=><article key={t.id} className="rounded-xl border border-[var(--color-border)] bg-white p-4"><Link href={`/projects/tasks/${t.id}`} className="font-medium text-sm hover:text-[var(--color-atlas-blue)]">{t.title}</Link><p className="mt-1 text-xs text-[var(--color-ink-faint)]">{t.reference??t.id.slice(-8)} · {t.project?.name??'Personal'}</p><div className="mt-4 flex items-center justify-between text-xs text-[var(--color-ink-muted)]"><span>{names.get(t.assigneeUserId)??'Former member'}</span><span className={t.dueAt&&t.dueAt<new Date()&&!done(t.status)?'text-[var(--color-status-danger)]':''}>{dateLabel(t.dueAt)}</span></div>{t.status==='WAITING'&&<p className="mt-2 text-xs">{t.waitingReason??'Waiting on a handoff'}</p>}</article>;
 if(!tasks.length&&layout!=='timeline')return <div className="rounded-2xl border border-dashed border-[var(--color-border)] px-6 py-16 text-center"><p className="text-sm font-medium">A clear space for your next action.</p><p className="mt-2 text-xs text-[var(--color-ink-muted)]">Capture a task or adjust your filters.</p></div>;
 if(layout==='board'){const key=(t:Tasks[number])=>group==='assignee'?names.get(t.assigneeUserId)??'Former member':group==='priority'?t.priority:group==='project'?t.project?.name??'Personal':t.status,groups=group==='status'?TASK_STATUSES.filter(s=>tasks.some(t=>t.status===s)):[...new Set(tasks.map(key))];return <div className="flex gap-4 overflow-x-auto pb-4">{groups.map(s=><section key={s} className="min-w-64 flex-1"><h3 className="mb-3 flex justify-between text-xs font-semibold uppercase tracking-wide text-[var(--color-ink-muted)]">{s.replaceAll('_',' ')}<span>{tasks.filter(t=>key(t)===s).length}</span></h3><div className="space-y-3">{tasks.filter(t=>key(t)===s).map(card)}</div></section>)}</div>;}
 if(layout==='calendar'){const days=[...new Set(tasks.map(t=>t.dueAt?.toISOString().slice(0,10)??'Unscheduled'))].sort();return <div className="grid gap-4 md:grid-cols-3">{days.map(day=><section key={day}><h3 className="mb-3 text-sm font-semibold">{day==='Unscheduled'?day:dateLabel(new Date(day))}</h3><div className="space-y-3">{tasks.filter(t=>(t.dueAt?.toISOString().slice(0,10)??'Unscheduled')===day).map(card)}</div></section>)}</div>;}
 if(layout==='timeline')return <Gantt today={new Date().toISOString().slice(0,10)} targetAt={targetAt} milestones={milestones} baselines={baselines} tasks={tasks.map(t=>({id:t.id,title:t.title,status:t.status,startAt:t.startAt?.toISOString()??null,dueAt:t.dueAt?.toISOString()??null,owner:names.get(t.assigneeUserId)??'Former member',project:t.project?.name??'Personal',priority:t.priority,estimatedMinutes:t.estimatedMinutes,parentTaskId:t.parentTaskId,version:t.version,editable:manage,dependencies:t.predecessors.filter(e=>tasks.some(v=>v.id===e.predecessorId)).map(e=>({predecessorId:e.predecessorId,successorId:e.successorId,kind:e.kind,lagDays:e.lagDays}))}))}/>;
 return <div className="overflow-x-auto rounded-2xl border border-[var(--color-border)] bg-white"><table className="w-full text-left text-sm"><thead className="border-b border-[var(--color-border)] text-xs text-[var(--color-ink-muted)]"><tr>{['Task','Owner','Status','Due','Effort',''].map((h,i)=><th key={i} className="px-5 py-4 font-medium">{h}</th>)}</tr></thead><tbody>{tasks.map(t=><tr key={t.id} className="border-b border-[var(--color-border)] last:border-0"><td className="px-5 py-4"><Link href={`/projects/tasks/${t.id}`} className="font-medium hover:text-[var(--color-atlas-blue)]">{t.parentTaskId?'↳ ':''}{t.title}</Link><p className="mt-1 text-xs text-[var(--color-ink-faint)]">{t.project?.name??'Personal'} · {t.priority.replaceAll('_',' ')}</p></td><td className="px-5 py-4 text-xs">{names.get(t.assigneeUserId)??'Former member'}</td><td className="px-5 py-3">{manage?<ActionForm action={changeTaskStatus.bind(null,t.id)} className="flex items-center gap-2"><Hidden name="version" value={t.version}/><Select name="status" values={TASK_STATUSES} value={t.status}/><Button type="submit" variant="ghost">Save</Button></ActionForm>:t.status.replaceAll('_',' ')}</td><td className={`px-5 py-4 text-xs ${t.dueAt&&t.dueAt<new Date()&&!done(t.status)?'text-[var(--color-status-danger)]':''}`}>{dateLabel(t.dueAt)}</td><td className="px-5 py-4 text-xs">{t.estimatedMinutes?(t.estimatedMinutes/60).toFixed(1)+'h':'—'}</td><td className="px-5 py-4"><ActionForm action={planToday.bind(null,t.id)}><Hidden name="day" value={new Date().toLocaleDateString('en-CA',{timeZone:'Europe/London'})}/><Button type="submit" variant="ghost">Focus today</Button></ActionForm></td></tr>)}</tbody></table></div>;
}
