import Link from 'next/link';
import {requireSession} from '@/core/auth/session';
import {assertCapability,can} from '@/core/permissions/check';
import {db} from '@/core/db/client';
import {taskScope} from '@/core/permissions/work-access';
import {workData} from '../services/queries';
import {TaskViews,dateLabel} from './tasks';
import {TaskCreator,Field,Hidden,Select,input} from './forms';
import {ActionForm} from '@/components/ui/action-form';
import {Button} from '@/components/ui/button';
import {getProjectWorkload,createDocument,createPortfolio,updateInbox,saveView} from '@/app/(app)/projects/actions';
import {done,TASK_STATUSES,dependencyConflicts} from '../domain/work';
import {notFound} from 'next/navigation';
export type Params=Record<string,string|undefined>;
const titles:Record<string,string>={'my-work':'My Work','my-day':'My Day',tasks:'All work',waiting:'Waiting on',inbox:'Inbox',notes:'Notes',docs:'Documents',portfolios:'Portfolios & goals',calendar:'Calendar',timeline:'Timeline',workload:'Workload',timesheets:'My time',reports:'Reports',archive:'Archive'};
export async function WorkSpace({section,filters={}}:{section:string;filters?:Params}){
 const session=await requireSession();assertCapability(session,'projects.read');if(!titles[section])notFound();const data=await workData(session),manage=can(session,'projects.manage'),layout=filters.layout??(section==='calendar'?'calendar':section==='timeline'?'timeline':'list');
 let tasks=data.tasks;
 if(['my-work','my-day','waiting'].includes(section))tasks=tasks.filter(t=>t.assigneeUserId===session.userId||t.contributorUserIds.includes(session.userId));
 if(section==='my-day'){const day=new Date().toLocaleDateString('en-CA',{timeZone:'Europe/London'}),plans=await db.projectPersonalPlan.findMany({where:{organisationId:session.organisationId,userId:session.userId,day:new Date(day),task:taskScope(session)}}),ids=new Set(plans.map(p=>p.taskId));tasks=tasks.filter(t=>ids.has(t.id)||t.dueAt&&t.dueAt.toISOString().slice(0,10)<=day);}
 if(section==='waiting')tasks=tasks.filter(t=>['BLOCKED','WAITING'].includes(t.status));
 if(filters.status)tasks=tasks.filter(t=>t.status===filters.status);else if(['my-work','my-day'].includes(section))tasks=tasks.filter(t=>!done(t.status));
 if(filters.owner)tasks=tasks.filter(t=>t.assigneeUserId===filters.owner);if(filters.projectId)tasks=tasks.filter(t=>t.projectId===filters.projectId);if(filters.query)tasks=tasks.filter(t=>(t.title+' '+t.description+' '+(t.reference??'')).toLowerCase().includes(filters.query!.toLowerCase()));
 const header=<header className="flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs uppercase tracking-widest text-[var(--color-ink-faint)]">Projects</p><h1 className="text-3xl font-semibold tracking-tight">{titles[section]}</h1><p className="mt-2 text-sm text-[var(--color-ink-muted)]">{section==='my-day'?'Your personal plan. Project deadlines stay separate.':section==='waiting'?'Clear handoffs and the next follow-up.':'One connected workspace for the work ahead.'}</p></div>{manage&&<TaskCreator projects={data.projects.filter(p=>!p.archivedAt)} members={data.members} me={session.userId}/>}</header>;
 let body:React.ReactNode;
 if(['tasks','my-work','my-day','waiting','calendar','timeline'].includes(section)){const edges=tasks.flatMap(t=>t.predecessors),conflicts=dependencyConflicts(tasks,edges);body=<><form className="flex flex-wrap items-end gap-3"><Field label="Search"><input name="query" defaultValue={filters.query} className={input} placeholder="Task title or reference"/></Field><Field label="Status"><select name="status" defaultValue={filters.status} className={input}><option value="">All statuses</option>{TASK_STATUSES.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Owner"><select name="owner" defaultValue={filters.owner} className={input}><option value="">Everyone</option>{data.members.map(m=><option key={m.userId} value={m.userId}>{m.user.name}</option>)}</select></Field><Field label="View"><Select name="layout" values={['list','board','calendar','timeline']} value={layout}/></Field><Field label="Group board by"><Select name="group" values={['status','assignee','priority','project']} value={filters.group??'status'}/></Field><Button type="submit">Apply</Button></form><div className="flex flex-wrap gap-3">{data.views.map(v=>{const d=v.definition as Record<string,string>;return <Link key={v.id} href={`?${new URLSearchParams(d).toString()}`} className="rounded-lg border border-[var(--color-border)] px-3 py-2 text-xs">{v.name}</Link>;})}<details className="text-xs"><summary className="cursor-pointer px-3 py-2">Save this view</summary><ActionForm action={saveView} className="mt-3 flex items-end gap-3"><Field label="View name"><input required name="name" className={input}/></Field>{Object.entries({layout,group:filters.group??'status',status:filters.status,owner:filters.owner,query:filters.query,projectId:filters.projectId}).map(([name,value])=><Hidden key={name} name={name} value={value}/>)}<Button type="submit">Save</Button></ActionForm></details></div>{conflicts.length>0&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm">{conflicts.map(c=><p key={c.successor.id}>{c.predecessor.title} delays {c.successor.title} by {c.days} days.</p>)}</div>}<TaskViews tasks={tasks} members={data.members} layout={layout} group={filters.group??'status'}/></>;}
 else if(section==='inbox')body=<div className="space-y-3">{data.inbox.map(i=><article key={i.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-[var(--color-border)] bg-white p-5"><Link href={i.taskId?`/projects/tasks/${i.taskId}`:i.projectId?`/projects/${i.projectId}`:'/projects'} className="text-sm font-medium">{i.label}<span className="ml-3 text-xs font-normal text-[var(--color-ink-faint)]">{i.kind}</span></Link><ActionForm action={updateInbox.bind(null,i.id)} className="flex items-end gap-2"><Select name="mode" values={['DISMISS','SNOOZE']}/><input aria-label="Snooze until" type="datetime-local" name="snoozedUntil" className={input}/><Button type="submit">Apply</Button></ActionForm></article>)}{!data.inbox.length&&<p className="py-16 text-center text-sm text-[var(--color-ink-muted)]">You’re all caught up.</p>}</div>;
 else if(['notes','docs'].includes(section))body=<><div className="grid gap-4 md:grid-cols-2">{data.documents.filter(d=>d.kind===(section==='notes'?'NOTE':'DOC')).map(d=><Link href={`/projects/documents/${d.id}`} key={d.id} className="rounded-2xl border border-[var(--color-border)] bg-white p-6"><p className="text-xs text-[var(--color-ink-faint)]">{d.visibility} · v{d.version} · {dateLabel(d.updatedAt)}</p><h2 className="mt-3 text-lg font-semibold">{d.title}</h2><p className="mt-3 line-clamp-3 whitespace-pre-wrap text-sm text-[var(--color-ink-muted)]">{d.body}</p></Link>)}</div>{manage&&<details className="rounded-2xl border border-[var(--color-border)] bg-white p-5"><summary className="cursor-pointer text-sm font-medium">Write {section==='notes'?'a note':'a document'}</summary><ActionForm action={createDocument} className="mt-5 space-y-4"><Hidden name="kind" value={section==='notes'?'NOTE':'DOC'}/><Field label="Title"><input required name="title" className={input}/></Field><Field label="Project"><select name="projectId" className={input}><option value="">Personal · private</option>{data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Visibility"><Select name="visibility" values={['PRIVATE','PROJECT']}/></Field><Field label="Content"><textarea name="body" rows={10} className={input}/></Field><Button type="submit" variant="primary">Save</Button></ActionForm></details>}</>;
 else if(section==='portfolios')body=<><div className="grid gap-4 md:grid-cols-2">{data.portfolios.map(p=><article key={p.id} className="rounded-2xl border border-[var(--color-border)] bg-white p-6"><p className="text-xs text-[var(--color-ink-faint)]">{p.kind}</p><h2 className="mt-2 text-lg font-semibold">{p.name}</h2><p className="mt-3 text-sm text-[var(--color-ink-muted)]">{p.description}</p><div className="mt-5 space-y-3">{p.projects.map(l=>{const project=data.projects.find(x=>x.id===l.projectId);return project?<Link key={l.id} href={`/projects/${project.id}`} className="flex justify-between text-sm"><span>{project.name}</span><span className="text-xs">{project.health.replaceAll('_',' ')}</span></Link>:null;})}</div></article>)}</div>{manage&&<ActionForm action={createPortfolio} className="grid gap-4 rounded-2xl border border-[var(--color-border)] bg-white p-5"><Field label="Name"><input required name="name" className={input}/></Field><Field label="Type"><Select name="kind" values={['PORTFOLIO','PROGRAMME','GOAL']}/></Field><Field label="Purpose"><textarea name="description" className={input}/></Field><fieldset><legend className="text-xs">Supporting projects</legend><div className="mt-3 flex flex-wrap gap-4">{data.projects.map(p=><label key={p.id} className="flex gap-2 text-sm"><input type="checkbox" name="projectId" value={p.id}/>{p.name}</label>)}</div></fieldset><Button type="submit" className="justify-self-start">Create group</Button></ActionForm>}</>;
 else if(section==='workload'){if(!manage)body=<p className="text-sm text-[var(--color-ink-muted)]">Project management permission is required for team workload. Your work is available in My Work.</p>;else {const from=filters.from??new Date().toISOString().slice(0,10),rows=await getProjectWorkload(from);body=<><form className="flex items-end gap-3"><Field label="Week starting"><input type="date" name="from" defaultValue={from} className={input}/></Field><Button type="submit">Show week</Button></form><p className="text-sm text-[var(--color-ink-muted)]">Estimates are distributed over working days. Confidential work is included only as Private work. Contracted capacity excludes leave and calendar exceptions.</p><div className="overflow-x-auto rounded-2xl border border-[var(--color-border)] bg-white"><table className="w-full text-left text-sm"><thead><tr><th className="p-4">Person</th>{Array.from({length:7},(_,i)=><th key={i} className="p-4 text-xs">{dateLabel(new Date(new Date(from).getTime()+i*86400000))}</th>)}<th className="p-4 text-xs">Contract / week</th></tr></thead><tbody>{rows.map(r=><tr key={r.userId} className="border-t border-[var(--color-border)]"><td className="p-4"><p className="font-medium">{r.name}</p><p className="mt-1 text-xs text-[var(--color-ink-faint)]">{r.unestimated} unestimated · {(r.unscheduledMinutes/60).toFixed(1)}h unscheduled</p></td>{r.dailyMinutes.map((mins,i)=><td key={i} className="p-4 text-xs">{(mins/60).toFixed(1)}h{r.privateMinutes[i]>0&&<p className="mt-1 text-[var(--color-ink-faint)]">{(r.privateMinutes[i]/60).toFixed(1)}h Private work</p>}</td>)}<td className="p-4 text-xs">{r.contractedWeeklyHours===null?'Unavailable':`${r.contractedWeeklyHours}h`}</td></tr>)}</tbody></table></div></>;}}
 else if(section==='timesheets'){const entries=await db.projectTimeEntry.findMany({where:{organisationId:session.organisationId,userId:session.userId,task:taskScope(session)},include:{task:{select:{title:true}}},orderBy:{workedAt:'desc'}});body=<><p className="text-sm text-[var(--color-ink-muted)]">{(entries.reduce((n,e)=>n+e.minutes,0)/60).toFixed(1)} hours logged. Open a task to record time.</p><div className="rounded-xl border border-[var(--color-border)] bg-white">{entries.map(e=><Link key={e.id} href={`/projects/tasks/${e.taskId}`} className="flex justify-between border-b border-[var(--color-border)] p-4 text-sm"><span>{e.task.title}<span className="ml-3 text-xs text-[var(--color-ink-faint)]">{dateLabel(e.workedAt)}</span></span><span>{(e.minutes/60).toFixed(1)}h</span></Link>)}</div></>;}
 else if(section==='reports')body=<div className="rounded-2xl border border-[var(--color-border)] bg-white p-8"><h2 className="text-xl font-semibold">Projects in Analytics Studio</h2><p className="mt-3 text-sm text-[var(--color-ink-muted)]">Build dashboards from permission-filtered Projects, task status, health, overdue work and effort metrics.</p><Link href="/analytics" className="mt-6 inline-block text-sm text-[var(--color-atlas-blue)]">Open Analytics Studio →</Link></div>;
 else {const archived=data.projects.filter(p=>p.archivedAt);body=<div className="space-y-3">{archived.map(p=><Link key={p.id} href={`/projects/${p.id}`} className="block rounded-xl border border-[var(--color-border)] bg-white p-5">{p.name}<span className="ml-4 text-xs text-[var(--color-ink-muted)]">{dateLabel(p.archivedAt)}</span></Link>)}{!archived.length&&<p className="py-16 text-center text-sm text-[var(--color-ink-muted)]">No archived projects.</p>}</div>;}
 
 return <div className="space-y-6">{header}{body}</div>;
}
