import {beforeEach,describe,expect,it,vi} from 'vitest';
const mock=vi.hoisted(()=>({session:{userId:'user',organisationId:'org-a',capabilities:new Set(['customers.commercial.manage'])},db:{party:{findFirstOrThrow:vi.fn()},priceList:{findFirstOrThrow:vi.fn()},product:{findFirstOrThrow:vi.fn()},customerProduct:{findUnique:vi.fn()},commercialAgreement:{findMany:vi.fn()},priceListEntry:{findMany:vi.fn()},customerCommercialSettings:{upsert:vi.fn()},auditEntry:{create:vi.fn()},$transaction:vi.fn()}}));
vi.mock('@/core/auth/session',()=>({requireSession:async()=>mock.session}));vi.mock('@/core/db/client',()=>({db:mock.db}));vi.mock('next/cache',()=>({revalidatePath:vi.fn()}));
import {saveOrderingPreferences} from '@/core/customers/commercial-actions';
import {resolvePrice} from '@/core/pricing/resolve-price';
beforeEach(()=>{vi.resetAllMocks();mock.db.$transaction.mockImplementation(async fn=>fn(mock.db));mock.db.party.findFirstOrThrow.mockResolvedValue({commercialSettings:{priceList:'default-list'}});mock.db.product.findFirstOrThrow.mockResolvedValue({id:'product-a',categoryCode:null,basePriceAmount:500,baseCurrency:'GBP'});mock.db.customerProduct.findUnique.mockResolvedValue(null);mock.db.commercialAgreement.findMany.mockResolvedValue([]);mock.db.priceList.findFirstOrThrow.mockResolvedValue({id:'default-list',name:'Trade',currency:'GBP',baseCurrency:'GBP',exchangeRate:1});mock.db.priceListEntry.findMany.mockResolvedValue([{id:'rule',scope:'PRODUCT',productId:'product-a',categoryCode:null,method:'FIXED',minimumQuantity:1,unitPriceAmount:300,percentage:0,adjustmentAmount:0,priority:0,active:true,validFrom:null,validTo:null}]);});
describe('linked customer pricing',()=>{
 it('refuses foreign-company pricelist assignment before any write',async()=>{mock.db.priceList.findFirstOrThrow.mockRejectedValue(new Error('not found'));const f=new FormData();f.set('partyId','party-a');f.set('priceList','foreign-list');await expect(saveOrderingPreferences(f)).rejects.toThrow('not found');expect(mock.db.priceList.findFirstOrThrow).toHaveBeenCalledWith({where:{id:'foreign-list',organisationId:'org-a'}});expect(mock.db.$transaction).not.toHaveBeenCalled();});
 it('saves preferences and audit in one transaction',async()=>{const f=new FormData();f.set('partyId','party-a');f.set('priceList','default-list');f.set('customerPoRequired','on');await saveOrderingPreferences(f);expect(mock.db.customerCommercialSettings.upsert).toHaveBeenCalledWith(expect.objectContaining({where:{partyId:'party-a'},update:expect.objectContaining({priceList:'default-list',customerPoRequired:true})}));expect(mock.db.auditEntry.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({organisationId:'org-a'})}));});
 it('resolves the customer default list with quantity and date constraints',async()=>{const asOf=new Date('2026-10-03T12:00:00Z');expect(await resolvePrice({organisationId:'org-a',partyId:'party-a',productId:'product-a',quantity:10,asOf})).toMatchObject({unitPriceAmount:300,discountPercent:0,currency:'GBP',source:'Trade price list · Fixed price · GBP'});expect(mock.db.priceListEntry.findMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({priceListId:'default-list',minimumQuantity:{lte:10},AND:expect.arrayContaining([{OR:[{validFrom:null},{validFrom:{lte:asOf}}]},{OR:[{validTo:null},{validTo:{gte:asOf}}]}])})}));});
 it('returns the set price and its discount in the price list currency',async()=>{mock.db.priceList.findFirstOrThrow.mockResolvedValue({id:'default-list',name:'Export',currency:'EUR',baseCurrency:'GBP',exchangeRate:1.2});mock.db.priceListEntry.findMany.mockResolvedValue([{id:'rule',scope:'PRODUCT',productId:'product-a',categoryCode:null,method:'FIXED',minimumQuantity:1,unitPriceAmount:1000,percentage:15,adjustmentAmount:0,priority:0,active:true,validFrom:null,validTo:null}]);expect(await resolvePrice({organisationId:'org-a',partyId:'party-a',productId:'product-a',quantity:1})).toMatchObject({unitPriceAmount:1000,discountPercent:15,currency:'EUR',source:'Export price list · Set price · 15% discount'});});
 it('lets an explicit standard-price selection bypass the default list',async()=>{expect(await resolvePrice({organisationId:'org-a',partyId:'party-a',productId:'product-a',quantity:1,priceListId:null})).toMatchObject({unitPriceAmount:500,source:'Standard price'});expect(mock.db.priceList.findFirstOrThrow).not.toHaveBeenCalled();});
  it('gives customer contract prices precedence when no agreement price applies',async()=>{mock.db.customerProduct.findUnique.mockResolvedValue({contractedPriceAmount:200,contractedPriceCurrency:'GBP'});expect(await resolvePrice({organisationId:'org-a',partyId:'party-a',productId:'product-a',quantity:1})).toMatchObject({unitPriceAmount:200,source:'Customer contract price'});expect(mock.db.priceListEntry.findMany).not.toHaveBeenCalled();});
  it('uses the latest active agreement special price ahead of a saved customer price',async()=>{mock.db.customerProduct.findUnique.mockResolvedValue({contractedPriceAmount:200,contractedPriceCurrency:'GBP'});mock.db.commercialAgreement.findMany.mockResolvedValue([{id:'newer',name:'2026 supply',status:'ACTIVE',startsOn:new Date('2026-06-01'),endsOn:null,priceListId:'contract-list',priceList:{currency:'EUR'},prices:[{id:'line',unitPriceAmount:150,minimumQuantity:1}]},{id:'older',name:'Old supply',status:'ACTIVE',startsOn:new Date('2025-01-01'),endsOn:null,priceListId:null,priceList:null,prices:[{id:'old-line',unitPriceAmount:10,minimumQuantity:1}]}]);expect(await resolvePrice({organisationId:'org-a',partyId:'party-a',productId:'product-a',quantity:1,asOf:new Date('2026-10-03')})).toMatchObject({unitPriceAmount:150,currency:'EUR',source:'2026 supply · special price'});expect(mock.db.priceListEntry.findMany).not.toHaveBeenCalled();});
  it('prices from the agreement list when the agreement has no special price',async()=>{mock.db.commercialAgreement.findMany.mockResolvedValue([{id:'agr',name:'Trade contract',status:'ACTIVE',startsOn:new Date('2026-01-01'),endsOn:null,priceListId:'default-list',priceList:{currency:'GBP'},prices:[]}]);expect(await resolvePrice({organisationId:'org-a',partyId:'party-a',productId:'product-a',quantity:1,asOf:new Date('2026-10-03')})).toMatchObject({unitPriceAmount:300,source:'Trade price list · Fixed price · GBP · Trade contract'});});
});
