import {describe,it,expect} from 'vitest';
import {date,version,link,trainingDates,assuranceState,assertApplicationMove} from '@/modules/people/domain/platform';
function form(values:Record<string,string>){const f=new FormData();Object.entries(values).forEach(([k,v])=>f.set(k,v));return f;}
describe('HR platform validation',()=>{
 it('rejects impossible and malformed calendar dates',()=>{for(const d of ['2026-02-30','2026-1-01','today'])expect(()=>date(form({dueOn:d}),'dueOn')).toThrow('valid');expect(date(form({dueOn:'2028-02-29'}),'dueOn')?.toISOString()).toBe('2028-02-29T00:00:00.000Z');});
 it('requires a genuine nonnegative version',()=>{for(const n of ['','-1','0.5','Infinity'])expect(()=>version(form({version:n}))).toThrow();expect(version(form({version:'0'}))).toBe(0);});
 it('rejects executable and credential-bearing evidence URLs',()=>{for(const url of ['javascript:alert(1)','data:text/html,x','https://secret:token@host/path','broken'])expect(()=>link(form({evidenceUrl:url}))).toThrow();expect(link(form({evidenceUrl:'https://approved.example/file'}))).toBe('https://approved.example/file');});
 it('completion requires actual evidence dates and renewal cannot predate completion',()=>{const d=new Date('2026-10-08'),past=new Date('2026-10-01');expect(()=>trainingDates('COMPLETED',null,null,d)).toThrow('completion');expect(()=>trainingDates('PLANNED',past,null,d)).toThrow('Only completed');expect(()=>trainingDates('COMPLETED',new Date('2026-10-09'),null,d)).toThrow('future');expect(()=>trainingDates('COMPLETED',d,past,d)).toThrow('before');expect(()=>trainingDates('COMPLETED',past,d,d)).not.toThrow();});
 it('expiry is inclusive and UTC based; archive never counts as overdue',()=>{const today=new Date('2026-10-08T20:00Z');expect(assuranceState({status:'COMPLETED',expiresOn:new Date('2026-10-07')},today)).toBe('Expired');expect(assuranceState({status:'COMPLETED',expiresOn:new Date('2026-10-08')},today)).toBe('Expires soon');expect(assuranceState({status:'PLANNED',expiresOn:null,dueOn:new Date('2026-10-07')},today)).toBe('Overdue');expect(assuranceState({status:'ARCHIVED',expiresOn:new Date('2020-01-01')},today)).toBe('Archived');});
 it('requires an offer before hire and preserves closed recruitment history',()=>{expect(()=>assertApplicationMove('APPLIED','HIRED')).toThrow('offer');expect(()=>assertApplicationMove('OFFER','HIRED')).not.toThrow();for(const stage of ['HIRED','REJECTED','WITHDRAWN'])expect(()=>assertApplicationMove(stage,'APPLIED')).toThrow('closed');expect(()=>assertApplicationMove('APPLIED','UNKNOWN')).toThrow();});
});
