import {describe,it,expect} from 'vitest';
import {moneyMinor,marketingPlanSchema,activitySchema,budgetLineSchema,journeyMapSchema,journeyStageSchema,journeyTouchSchema} from '../src/modules/marketing/domain/planning';
describe('Marketing planning',()=>{
 it('converts decimal budgets exactly without silent rounding',()=>{expect(moneyMinor('1234.56')).toBe(123456);expect(moneyMinor('0.01')).toBe(1);expect(moneyMinor('12.5')).toBe(1250);for(const invalid of ['-1','1.001','NaN','1e3','99999999'])expect(()=>moneyMinor(invalid)).toThrow();});
 it('requires a measurable strategy and validates target bounds',()=>{const plan={objective:'Grow commercial accounts',targetMarket:'UK manufacturers',proposition:'Reliable fulfilment',successMeasure:'Review qualified leads monthly',salesTargetMinor:1000000,leadTarget:20,currency:'GBP'};expect(marketingPlanSchema.parse(plan)).toEqual(plan);expect(marketingPlanSchema.safeParse({...plan,successMeasure:''}).success).toBe(false);expect(marketingPlanSchema.safeParse({...plan,leadTarget:-1}).success).toBe(false);});
 it('keeps forecasts separate from planned allocations and rejects unknown fields',()=>{const line={channel:'Events',category:'Venue',supplier:'',plannedMinor:10000,forecastMinor:12500,currency:'GBP',notes:''};const parsed=budgetLineSchema.parse(line);expect(parsed.forecastMinor).toBe(12500);expect(parsed.place).toBe('Unassigned');expect(parsed.approval).toBe('DRAFT');expect(budgetLineSchema.parse({...line,place:'UK paid search'}).place).toBe('UK paid search');expect(budgetLineSchema.safeParse({...line,actualMinor:10000}).success).toBe(false);});
 it('requires a valid delivery date, owner and supported progress state',()=>{const activity={channel:'Content',deliverable:'Publish product guide',owner:'Marketing',dueAt:'2026-11-01T00:00:00.000Z',status:'PLANNED'};expect(activitySchema.safeParse(activity).success).toBe(true);expect(activitySchema.safeParse({...activity,dueAt:'bad'}).success).toBe(false);expect(activitySchema.safeParse({...activity,status:'SENT'}).success).toBe(false);});
 it('keeps a journey stage and its touchpoint on the same map',()=>{const map=journeyMapSchema.parse({who:'Existing accounts'});expect(map.who).toBe('Existing accounts');const stage=journeyStageSchema.parse({journeyId:'map',order:2,customerIntent:'They compare suppliers.'});const touch=journeyTouchSchema.parse({journeyId:'map',stageId:'stage',channel:'Events',moment:'Stand at the autumn show',owner:'Marketing'});expect(stage.order).toBe(2);expect(touch.stageId).toBe('stage');expect(journeyTouchSchema.safeParse({...touch,channel:'Carrier pigeon'}).success).toBe(false);});
});
