import {describe,it,expect,vi,beforeEach} from 'vitest';
const m=vi.hoisted(()=>({session:{organisationId:'tenant-a',userId:'actor',capabilities:new Set<string>()},tx:{marketingProfile:{findFirstOrThrow:vi.fn(),update:vi.fn()},marketingEvent:{findFirst:vi.fn(),create:vi.fn()},marketingCampaign:{findFirstOrThrow:vi.fn()},marketingTouch:{create:vi.fn()},marketingLead:{upsert:vi.fn()},domainOutbox:{create:vi.fn()},marketingJourney:{findMany:vi.fn()},marketingSuppression:{create:vi.fn()},auditEntry:{create:vi.fn()}},state:vi.fn()}));
vi.mock('@/core/auth/session',()=>({requireSession:async()=>m.session}));
vi.mock('@/core/db/client',()=>({db:{$transaction:async(fn:(tx:unknown)=>unknown)=>fn(m.tx),moduleState:{findMany:m.state}}}));
vi.mock('next/cache',()=>({revalidatePath:vi.fn()}));
import {ingestEvent,createCampaign} from '@/modules/marketing/services/commands';
function event(){const f=new FormData();Object.entries({profileId:'p',type:'CONTENT_DOWNLOADED',source:'FORM',idempotencyKey:'event-a',occurredAt:'2026-09-01',properties:'{}'}).forEach(([k,v])=>f.set(k,v));return f;}
beforeEach(()=>{vi.clearAllMocks();m.session.capabilities=new Set(['marketing.event.ingest']);m.state.mockResolvedValue([{moduleId:'marketing',enabled:true,entitled:true}]);m.tx.marketingProfile.findFirstOrThrow.mockResolvedValue({id:'p',score:68,lifecycle:'SUBSCRIBER'});m.tx.marketingEvent.findFirst.mockResolvedValue(null);m.tx.marketingEvent.create.mockImplementation(async({data})=>({...data,id:'e'}));m.tx.marketingJourney.findMany.mockResolvedValue([]);});
describe('Marketing persistence entry boundaries',()=>{
 it('deduplicates events without incrementing scores or creating another MQL',async()=>{m.tx.marketingEvent.findFirst.mockResolvedValue({profileId:'p',type:'CONTENT_DOWNLOADED'});await ingestEvent(event());expect(m.tx.marketingEvent.create).not.toHaveBeenCalled();expect(m.tx.marketingProfile.update).not.toHaveBeenCalled();expect(m.tx.marketingLead.upsert).not.toHaveBeenCalled();});
 it('rejects conflicting event idempotency keys',async()=>{m.tx.marketingEvent.findFirst.mockResolvedValue({profileId:'foreign',type:'CONTENT_DOWNLOADED'});await expect(ingestEvent(event())).rejects.toThrow('different event');});
 it('records an explained threshold crossing and durable MQL once',async()=>{await ingestEvent(event());expect(m.tx.marketingProfile.findFirstOrThrow).toHaveBeenCalledWith({where:{id:'p',organisationId:'tenant-a'}});expect(m.tx.marketingProfile.update).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({score:78,lifecycle:'MQL'})}));expect(m.tx.marketingLead.upsert).toHaveBeenCalledWith(expect.objectContaining({create:expect.objectContaining({organisationId:'tenant-a',explanation:expect.objectContaining({previous:68,score:78,delta:10})})}));expect(m.tx.domainOutbox.create).toHaveBeenCalledOnce();});
 it('rejects unauthorized ingestion before reading identity',async()=>{m.session.capabilities.clear();await expect(ingestEvent(event())).rejects.toThrow();expect(m.tx.marketingProfile.findFirstOrThrow).not.toHaveBeenCalled();});
 it('rejects disabled Marketing even with a capability',async()=>{m.state.mockResolvedValue([]);await expect(ingestEvent(event())).rejects.toThrow('disabled');expect(m.tx.marketingProfile.findFirstOrThrow).not.toHaveBeenCalled();});
 it('campaign creation does not inherit read permission as create permission',async()=>{m.session.capabilities=new Set(['marketing.campaign.read']);await expect(createCampaign(new FormData())).rejects.toThrow();});
});
