import { expect, it } from 'vitest';
import { parseCampaignDetails, readCampaignDetails, mergeCampaignDetails, safeResourceUrl } from '@/modules/marketing/domain/campaign-details';
function form(){const f=new FormData();f.set('detail:customerProblem',' Slow delivery ');f.append('customLabel','Agency contact');f.append('customValue','Marketing team');f.append('resourceLabel','Artwork');f.append('resourceUrl','https://example.com/artwork');return f;}
it('round trips extended brief, custom information and resource links without dropping unrelated metadata',()=>{const details=parseCampaignDetails(form());const merged=mergeCampaignDetails({legacy:{source:'preserved'},workspace:{futureSetting:true}},details);expect(merged).toMatchObject({legacy:{source:'preserved'},workspace:{futureSetting:true}});expect(readCampaignDetails(merged)).toEqual(details);expect(details.fields.customerProblem).toBe('Slow delivery');});
it('does not treat absent or old brief metadata as completed new information',()=>{expect(readCampaignDetails(null).custom).toEqual([]);expect(readCampaignDetails({legacy:true}).resources).toEqual([]);});
it('rejects oversized notes instead of silently cutting information',()=>{const f=form();f.set('detail:notes','x'.repeat(5001));expect(()=>parseCampaignDetails(f)).toThrow('too long');});
it('requires unique named custom fields with paired values',()=>{const f=form();f.append('customLabel','agency CONTACT');f.append('customValue','Duplicate');expect(()=>parseCampaignDetails(f)).toThrow('different name');f.delete('customLabel');expect(()=>parseCampaignDetails(f)).toThrow('matching');});
it('limits custom information and resource counts',()=>{const f=form();for(let n=0;n<20;n++){f.append('customLabel',`Field ${n}`);f.append('customValue','value');}expect(()=>parseCampaignDetails(f)).toThrow('20');});
it.each(['javascript:alert(1)','data:text/html,test','file:///secret','https://user:password@example.com','broken'])('rejects unsafe resource link %s',url=>{const f=form();f.set('resourceUrl',url);expect(safeResourceUrl(url)).toBe(false);expect(()=>parseCampaignDetails(f)).toThrow('valid http');expect(readCampaignDetails({workspace:{resources:[{label:'Unsafe',url}]}}).resources).toEqual([]);});
it('supports clearing all optional information explicitly',()=>{expect(parseCampaignDetails(new FormData())).toMatchObject({custom:[],resources:[],fields:{notes:''}});});
