import {describe,it,expect} from 'vitest';
import {eligibility,evaluateRule,parseRule,allocateExperiment,attributionWeights,validateJourney,campaignTransition,type EligibilityInput} from '@/modules/marketing/domain/policy';
const base:EligibilityInput={channel:'EMAIL',purpose:'PROMOTIONS',brand:'DEFAULT',country:'GB',legalEntity:'Company',classification:'PROMOTIONAL',email:'contact@example.test',mobile:null,active:true,suppressions:[],permissions:[{channel:'EMAIL',purpose:'PROMOTIONS',brand:'DEFAULT',country:'GB',legalEntity:'Company',state:'SUBSCRIBED',occurredAt:new Date('2026-01-01')}],sentIn7Days:0,severeComplaint:false};
describe('Marketing permission and execution safety',()=>{
 it('separates matching from eligibility for an unsubscribed audience member',()=>{expect(evaluateRule(parseRule({field:'country',operator:'eq',value:'GB'}),{country:'GB',lifecycle:'SUBSCRIBER',score:0,source:'FORM',brand:'DEFAULT',events:[]}).matched).toBe(true);expect(eligibility({...base,permissions:[{...base.permissions[0],state:'UNSUBSCRIBED'}]})).toEqual({eligible:false,reasons:['Promotion subscription unavailable']});});
 it('global objection blocks every channel including an older consent grant',()=>{for(const channel of ['EMAIL','SMS'])expect(eligibility({...base,channel,suppressions:[{channel:'ALL',reason:'OBJECTED'}]}).eligible).toBe(false);});
 it('uses the latest exact permission dimensions and fails closed for another purpose',()=>{expect(eligibility({...base,permissions:[...base.permissions,{...base.permissions[0],state:'UNSUBSCRIBED',occurredAt:new Date('2026-02-01')}]}).eligible).toBe(false);expect(eligibility({...base,purpose:'NEWSLETTER'}).eligible).toBe(false);});
 it('frequency policy blocks a fourth message',()=>{expect(eligibility({...base,sentIn7Days:3}).reasons).toContain('Frequency cap: 3 messages in 7 days');});
 it('severe complaint excludes promotion but permits valid transactional eligibility',()=>{expect(eligibility({...base,severeComplaint:true}).eligible).toBe(false);expect(eligibility({...base,severeComplaint:true,classification:'TRANSACTIONAL',permissions:[]}).eligible).toBe(true);});
 it('hard bounce remains blocked for transactional messages',()=>{expect(eligibility({...base,classification:'TRANSACTIONAL',suppressions:[{channel:'EMAIL',reason:'HARD_BOUNCE'}]}).eligible).toBe(false);});
 it('supports nested logic and event time windows',()=>{const rules=parseRule({all:[{any:[{field:'country',operator:'eq',value:'GB'},{field:'country',operator:'eq',value:'IE'}]},{not:{field:'event',operator:'exists',value:'PURCHASE_COMPLETED',days:180}}]});const p={country:'GB',lifecycle:'MQL',score:76,source:'FORM',brand:'DEFAULT',events:[]};expect(evaluateRule(rules,p).matched).toBe(true);expect(evaluateRule(rules,{...p,events:[{type:'PURCHASE_COMPLETED',occurredAt:new Date()}]}).matched).toBe(false);});
 it('rejects unknown fields, empty groups and excessive rule depth',()=>{expect(()=>parseRule({field:'salary',operator:'gte',value:0})).toThrow();expect(()=>parseRule({all:[]})).toThrow();let r:unknown={field:'score',operator:'gte',value:0};for(let n=0;n<8;n++)r={not:r};expect(()=>parseRule(r)).toThrow();});
 it('allocates 10,000 unique people to exactly one frozen group',()=>{const ids=Array.from({length:10000},(_,i)=>String(i));const assignments=allocateExperiment([...ids,ids[0]],45,45,10);expect(assignments).toHaveLength(10000);for(const [group,count]of [['CONTROL',4500],['VARIANT',4500],['HOLDOUT',1000]])expect(assignments.filter(a=>a.group===group)).toHaveLength(Number(count));expect(allocateExperiment(ids.reverse(),45,45,10)).toEqual(assignments);expect(()=>allocateExperiment(ids,45,45,15)).toThrow();});
 it('preserves touches across attribution models and excludes future/out-of-window facts',()=>{const touches=[{campaignId:'ad',occurredAt:new Date('2026-09-01')},{campaignId:'webinar',occurredAt:new Date('2026-09-02')},{campaignId:'email',occurredAt:new Date('2026-09-03')},{campaignId:'future',occurredAt:new Date('2026-10-05')}];const copy=JSON.stringify(touches),at=new Date('2026-10-03');expect(attributionWeights(touches,'FIRST',at)[0].campaignId).toBe('ad');expect(attributionWeights(touches,'LAST',at)[0].campaignId).toBe('email');expect(attributionWeights(touches,'LINEAR',at).reduce((n,w)=>n+w.weight,0)).toBe(1);expect(JSON.stringify(touches)).toBe(copy);});
 it('validates forward journey branches and explicit termination',()=>{expect(()=>validateJourney([{kind:'BRANCH',event:'EMAIL_CLICKED',yes:0,no:1},{kind:'END'}])).toThrow();expect(()=>validateJourney([{kind:'WAIT',hours:3}])).toThrow();expect(validateJourney([{kind:'WAIT',hours:72},{kind:'END'}])).toHaveLength(2);});
 it('rejects retrospective campaign state edits',()=>{expect(()=>campaignTransition('COMPLETED','LIVE')).toThrow();expect(()=>campaignTransition('APPROVAL','SCHEDULED')).not.toThrow();});
});
