import { beforeEach, expect, it, vi } from 'vitest';
const m=vi.hoisted(()=>({session:{organisationId:'company',userId:'user',capabilities:new Set(['marketing.campaign.create','marketing.campaign.manage'])},campaign:{findFirst:vi.fn(),count:vi.fn(),create:vi.fn(),updateMany:vi.fn()},lines:{createMany:vi.fn()},activities:{createMany:vi.fn()},audit:{create:vi.fn()},enabled:vi.fn(),member:vi.fn(),transaction:vi.fn()}));
vi.mock('@/core/auth/session',()=>({requireSession:async()=>m.session}));
vi.mock('@/core/db/client',()=>({db:{marketingCampaign:m.campaign,moduleState:{findFirst:m.enabled},membership:{findFirst:m.member},$transaction:m.transaction}}));
vi.mock('next/navigation',()=>({redirect:(url:string)=>{throw new Error(`REDIRECT:${url}`);}}));vi.mock('next/cache',()=>({revalidatePath:vi.fn()}));
import { createCampaignAction, saveCampaignBriefAction } from '@/modules/marketing/services/campaign-actions';
function form(){const f=new FormData();Object.entries({name:'Campaign',campaignId:'campaign',version:'3',budget:'120.50',briefWorkspace:'1','detail:notes':'Team notes'}).forEach(([key,value])=>f.set(key,value));return f;}
beforeEach(()=>{vi.clearAllMocks();m.session.capabilities=new Set(['marketing.campaign.create','marketing.campaign.manage']);m.enabled.mockResolvedValue({id:'enabled'});m.campaign.findFirst.mockResolvedValue({id:'campaign',brief:{legacy:'preserved'}});m.campaign.count.mockResolvedValue(1);m.campaign.create.mockResolvedValue({id:'new',ownerUserId:'user'});m.campaign.updateMany.mockResolvedValue({count:1});m.transaction.mockImplementation(async fn=>fn({marketingCampaign:m.campaign,marketingBudgetLine:m.lines,marketingActivity:m.activities,auditEntry:m.audit}));});
it('updates only the signed tenant and expected version; preserves metadata and brand when absent',async()=>{await saveCampaignBriefAction(form());const query=m.campaign.updateMany.mock.calls[0][0];expect(query.where).toEqual({id:'campaign',organisationId:'company',version:3});expect(query.data.brief).toMatchObject({legacy:'preserved',workspace:{fields:{notes:'Team notes'}}});expect(query.data).not.toHaveProperty('brand');expect(query.data.budgetMinor).toBe(12050);expect(m.audit.create).toHaveBeenCalledOnce();});
it('rejects a stale save without recording successful audit',async()=>{m.campaign.updateMany.mockResolvedValue({count:0});await expect(saveCampaignBriefAction(form())).rejects.toThrow('changed');expect(m.audit.create).not.toHaveBeenCalled();});
it('rejects missing version and foreign campaign access',async()=>{const f=form();f.delete('version');await expect(saveCampaignBriefAction(f)).rejects.toThrow('Refresh');m.campaign.findFirst.mockResolvedValue(null);await expect(saveCampaignBriefAction(form())).rejects.toThrow('no longer');expect(m.campaign.updateMany).not.toHaveBeenCalled();});
it.each(['1.001','NaN','1e3','-1'])('rejects invalid money before persistence: %s',value=>{const f=form();f.set('budget',value);return expect(createCampaignAction(f)).rejects.toThrow();});
it('validates budget splits before creating any record',async()=>{const f=form();f.set('channels','Email');f.set('split:Email','121');await expect(createCampaignAction(f)).rejects.toThrow('exceed');expect(m.transaction).not.toHaveBeenCalled();expect(m.campaign.create).not.toHaveBeenCalled();});
it('creates campaign, channel budget, launch plan and audit in one transaction',async()=>{m.campaign.findFirst.mockResolvedValue(null);const f=form();f.set('channels','Email');f.set('split:Email','120.50');f.set('seedPlan','on');await expect(createCampaignAction(f)).rejects.toThrow('REDIRECT:/marketing/campaigns/new');expect(m.transaction).toHaveBeenCalledOnce();expect(m.lines.createMany).toHaveBeenCalled();expect(m.activities.createMany).toHaveBeenCalled();expect(m.audit.create).toHaveBeenCalled();});
it('propagates child failure without a success redirect or audit',async()=>{m.campaign.findFirst.mockResolvedValue(null);m.lines.createMany.mockRejectedValueOnce(new Error('Budget unavailable'));const f=form();f.set('channels','Email');f.set('split:Email','10');await expect(createCampaignAction(f)).rejects.toThrow('Budget unavailable');expect(m.audit.create).not.toHaveBeenCalled();});
it('rejects impossible dates and inactive owners',async()=>{const f=form();f.set('startAt','2026-02-30');await expect(createCampaignAction(f)).rejects.toThrow('valid date');f.delete('startAt');f.set('ownerUserId','inactive');m.member.mockResolvedValue(null);await expect(createCampaignAction(f)).rejects.toThrow('owner');expect(m.member).toHaveBeenCalledWith(expect.objectContaining({where:{organisationId:'company',userId:'inactive',active:true}}));});
it('requires manage permission and an enabled company module',async()=>{m.session.capabilities.clear();await expect(saveCampaignBriefAction(form())).rejects.toThrow('FORBIDDEN');m.session.capabilities.add('marketing.campaign.manage');m.enabled.mockResolvedValue(null);await expect(saveCampaignBriefAction(form())).rejects.toThrow('not enabled');expect(m.campaign.updateMany).not.toHaveBeenCalled();});
