import {beforeEach,describe,it,expect,vi} from "vitest";
import type {Session} from "@/core/auth/session";
const mock=vi.hoisted(()=>({employees:vi.fn(),organisation:vi.fn(),settings:vi.fn()}));
vi.mock("@/core/db/client",()=>({db:{employee:{findMany:mock.employees},organisation:{findUniqueOrThrow:mock.organisation},payrollSettings:{findUnique:mock.settings}}}));
import {preparePayroll,payrollPeriod} from "@/modules/payroll/services/preparation";
const session={organisationId:"company",capabilities:new Set(["payroll.run.read"])} as Session;
const employee=()=>({id:"employee",organisationId:"company",firstName:"Alex",lastName:"Example",employeeNumber:"QA01",department:"Contact centre",status:"ACTIVE",payBasis:"SALARIED",hourlyRateMinorUnits:null,postgraduateLoan:false,annualSalaryMinorUnits:5280000,currency:"GBP",taxCode:"1257L M1",niCategory:"A",studentLoanPlan:null,pensionOptOut:true,payFrequency:"MONTHLY",contractedWeeklyHours:37.5,workingDays:[1,2,3,4,5],startDate:new Date("2026-04-06"),endDate:null,taxYearToDates:[{openingReviewed:true,openingGrossMinorUnits:0,openingTaxMinorUnits:0}],timesheets:[] as {id:string;status:string;entries:{id:string;workedOn:Date;minutes:number}[]}[],absences:[] as {id:string;type:string;startDate:Date;endDate:Date}[],payrollAdjustments:[] as {id:string;version:number;statutoryReviewed:boolean;statutoryPayMinorUnits:number;salaryReductionMinorUnits:number;additionalPayMinorUnits:number}[],payslips:[]});
beforeEach(()=>{vi.resetAllMocks();mock.employees.mockResolvedValue([employee()]);mock.organisation.mockResolvedValue({hrStandardWeeklyHours:37.5,hrOvertimeMultiplier:1.5});mock.settings.mockResolvedValue({currentTaxYear:"2026-27",employeePensionPercent:5,employerPensionPercent:3});});
describe("payroll preparation boundaries",()=>{
  it("rejects HR-only access before reading pay data",async()=>{await expect(preparePayroll({...session,capabilities:new Set(["people.employee.read"])},"2026-10-01","2026-10-31")).rejects.toThrow("FORBIDDEN");expect(mock.employees).not.toHaveBeenCalled();});
  it("scopes employees to the company and selected frequency",async()=>{await preparePayroll(session,"2026-10-01","2026-10-31");expect(mock.employees.mock.calls[0][0].where).toMatchObject({organisationId:"company",payFrequency:"MONTHLY"});});
  it("uses approved actual time and blocks entered unapproved hours",async()=>{const e=employee();e.timesheets=[{id:"approved",status:"APPROVED",entries:[{id:"day",workedOn:new Date("2026-10-12"),minutes:600}]},{id:"submitted",status:"SUBMITTED",entries:[{id:"other",workedOn:new Date("2026-10-19"),minutes:420}]}];mock.employees.mockResolvedValue([e]);const data=await preparePayroll(session,"2026-10-01","2026-10-31");expect(data.approvedHours).toBe(10);expect(data.awaitingApproval).toBe(1);expect(data.rows[0].issues).toContain("Review every entered timesheet before calculating pay.");expect(data.rows[0].result).toBeNull();});
  it("requires an explicit opening-history review even for zero balances",async()=>{const e=employee();e.taxYearToDates=[];mock.employees.mockResolvedValue([e]);expect((await preparePayroll(session,"2026-10-01","2026-10-31")).rows[0].issues.join(" ")).toMatch(/opening pay/);});
  it("changes the input binding when approved time or reviewed balances change",async()=>{const original=await preparePayroll(session,"2026-10-01","2026-10-31");const e=employee();e.taxYearToDates[0].openingTaxMinorUnits=10000;mock.employees.mockResolvedValue([e]);expect((await preparePayroll(session,"2026-10-01","2026-10-31")).inputDigest).not.toBe(original.inputDigest);e.timesheets=[{id:"approved",status:"APPROVED",entries:[{id:"day",workedOn:new Date("2026-10-12"),minutes:600}]}];expect((await preparePayroll(session,"2026-10-01","2026-10-31")).inputDigest).not.toBe(original.inputDigest);});
  it("counts unpaid absence only on contracted working days",async()=>{const e=employee();e.absences=[{id:"unpaid",type:"UNPAID",startDate:new Date("2026-10-10"),endDate:new Date("2026-10-11")}];mock.employees.mockResolvedValue([e]);const data=await preparePayroll(session,"2026-10-01","2026-10-31");expect(data.rows[0].unpaidDays).toBe(0);expect(data.rows[0].result?.unpaidLeaveDeductionMinorUnits).toBe(0);});
  it("prorates a starter’s salary against employed working days",async()=>{const e=employee();e.startDate=new Date("2026-10-15");mock.employees.mockResolvedValue([e]);expect((await preparePayroll(session,"2026-10-01","2026-10-31")).rows[0].result?.grossMinorUnits).toBe(240000);});
  it("requires review before applying statutory or hourly holiday pay",async()=>{const e=employee();e.absences=[{id:"sick",type:"SICKNESS",startDate:new Date("2026-10-12"),endDate:new Date("2026-10-12")}];mock.employees.mockResolvedValue([e]);expect((await preparePayroll(session,"2026-10-01","2026-10-31")).issues).toBe(1);e.payrollAdjustments=[{id:"review",version:0,statutoryReviewed:true,statutoryPayMinorUnits:2465,salaryReductionMinorUnits:20000,additionalPayMinorUnits:0}];const reviewed=await preparePayroll(session,"2026-10-01","2026-10-31");expect(reviewed.issues).toBe(0);expect(reviewed.rows[0].result?.grossMinorUnits).toBe(420000);expect(reviewed.rows[0].result?.statutoryPayMinorUnits).toBe(2465);});
  it("rejects invalid lengths and unsupported tax years",()=>{expect(()=>payrollPeriod("2026-10-01","2026-10-02","MONTHLY")).toThrow("28–31");expect(()=>payrollPeriod("2025-10-01","2025-10-31","MONTHLY")).toThrow("2026–27");expect(()=>payrollPeriod("2026-10-01","2026-10-07","WEEKLY")).not.toThrow();});
});
