import { beforeEach,describe,it,expect,vi } from 'vitest';
import { planWindow,planningDate,plannedQuantity } from '@/modules/planning/domain/plans';
import { exportCsv } from '@/core/shared/csv-export';
function windowForm(){const form=new FormData();form.set('startsOn','2027-01-01');form.set('endsOn','2027-12-31');form.set('bucket','MONTH');return form;}
describe('planning windows and export safety',()=>{
 it('supports a full-year monthly plan and a one-week daily plan',()=>{expect(planWindow(windowForm()).bucket).toBe('MONTH');const week=windowForm();week.set('endsOn','2027-01-07');week.set('bucket','DAY');expect(planWindow(week).endsOn.toISOString()).toBe('2027-01-07T00:00:00.000Z');});
 it('rejects impossible dates, reversed windows and unsupported buckets',()=>{expect(()=>planningDate('2027-02-29')).toThrow('calendar');const form=windowForm();form.set('endsOn','2026-01-01');expect(()=>planWindow(form)).toThrow('window');form.set('endsOn','2027-12-31');form.set('bucket','FORTNIGHT');expect(()=>planWindow(form)).toThrow('interval');});
 it('preserves decimal quantities without floating point arithmetic',()=>{expect(plannedQuantity('00012.340000')).toBe('12.34');expect(plannedQuantity('0.000001')).toBe('0.000001');expect(()=>plannedQuantity('1.0000001')).toThrow('six');expect(()=>plannedQuantity('-1')).toThrow('positive');expect(()=>plannedQuantity('0')).toThrow('positive');});
 it('protects formula-like text, quotes and newlines while retaining numeric deltas',()=>{const csv=exportCsv([['SKU','Note','Delta'],['=WEBSERVICE("x")','two\nlines',-10]]);expect(csv).toContain("'=");expect(csv).toContain('"two\nlines"');expect(csv).toContain(',-10');expect(csv.startsWith('\uFEFF')).toBe(true);});
});
const state=vi.hoisted(()=>({session:{userId:'u',organisationId:'org-a',capabilities:new Set<string>()},enabled:vi.fn(),db:{productionPlan:{findFirstOrThrow:vi.fn(),findUnique:vi.fn(),create:vi.fn(),updateMany:vi.fn()},productionPlanLine:{findUnique:vi.fn(),create:vi.fn()},product:{findFirstOrThrow:vi.fn()},workTeam:{findFirstOrThrow:vi.fn()},membership:{findFirstOrThrow:vi.fn()},workTeamMember:{findUnique:vi.fn()},auditEntry:{create:vi.fn()},$transaction:vi.fn()}}));
vi.mock('@/core/auth/session',()=>({requireSession:async()=>state.session}));
vi.mock('@/core/modules/access',()=>({assertModuleEnabled:state.enabled}));
vi.mock('@/core/db/client',()=>({db:state.db}));vi.mock('next/cache',()=>({revalidatePath:vi.fn()}));
import { createProductionPlan,addProductionPlanLine } from '@/modules/planning/services/plans';
function lineForm(){const form=windowForm();for(const [key,value]of Object.entries({planId:'plan',productId:'product',quantity:'12.34',version:'1',teamId:'team',assignedMembershipId:'member',requestKey:'line-key',notes:'Build target'}))form.set(key,value);return form;}
beforeEach(()=>{vi.clearAllMocks();state.session.capabilities=new Set(['planning.plan.manage']);state.enabled.mockResolvedValue(undefined);state.db.$transaction.mockImplementation(async fn=>fn(state.db));state.db.productionPlanLine.findUnique.mockResolvedValue(null);state.db.productionPlan.findUnique.mockResolvedValue(null);state.db.productionPlan.findFirstOrThrow.mockResolvedValue({id:'plan',startsOn:new Date('2027-01-01'),endsOn:new Date('2027-12-31')});state.db.productionPlan.updateMany.mockResolvedValue({count:1});state.db.product.findFirstOrThrow.mockResolvedValue({id:'product',unitOfMeasure:'kg'});state.db.workTeamMember.findUnique.mockResolvedValue({teamId:'team',membershipId:'member'});state.db.productionPlanLine.create.mockResolvedValue({id:'line'});state.db.productionPlan.create.mockResolvedValue({id:'plan'});});
describe('plan and team assignment boundaries',()=>{
 it('rejects missing write capability and disabled app',async()=>{state.session.capabilities.clear();await expect(addProductionPlanLine(lineForm())).rejects.toThrow('FORBIDDEN');expect(state.db.$transaction).not.toHaveBeenCalled();state.session.capabilities.add('planning.plan.manage');state.enabled.mockRejectedValue(new Error('disabled'));await expect(addProductionPlanLine(lineForm())).rejects.toThrow('disabled');});
 it('saves an annual plan with provenance and audit',async()=>{const form=windowForm();form.set('name','2027 target');form.set('requestKey','plan-key');await createProductionPlan(form);expect(state.db.productionPlan.create.mock.calls[0][0].data).toMatchObject({organisationId:'org-a',createdByUserId:'u',name:'2027 target',bucket:'MONTH'});expect(state.db.auditEntry.create).toHaveBeenCalledTimes(1);});
 it('rejects a line outside the saved plan window',async()=>{const form=lineForm();form.set('endsOn','2028-01-01');await expect(addProductionPlanLine(form)).rejects.toThrow('inside');expect(state.db.productionPlanLine.create).not.toHaveBeenCalled();});
 it('validates active tenant membership and selected team before saving',async()=>{await addProductionPlanLine(lineForm());expect(state.db.membership.findFirstOrThrow).toHaveBeenCalledWith({where:{id:'member',organisationId:'org-a',active:true}});expect(state.db.workTeam.findFirstOrThrow).toHaveBeenCalledWith({where:{id:'team',organisationId:'org-a'}});expect(state.db.productionPlanLine.create.mock.calls[0][0].data).toMatchObject({organisationId:'org-a',quantity:'12.34',unitOfMeasure:'kg',teamId:'team',assignedMembershipId:'member'});});
 it('rejects a person outside the selected team and a stale plan version',async()=>{state.db.workTeamMember.findUnique.mockResolvedValue(null);await expect(addProductionPlanLine(lineForm())).rejects.toThrow('belong');expect(state.db.productionPlanLine.create).not.toHaveBeenCalled();state.db.workTeamMember.findUnique.mockResolvedValue({});state.db.productionPlan.updateMany.mockResolvedValue({count:0});await expect(addProductionPlanLine(lineForm())).rejects.toThrow('Another planner');expect(state.db.productionPlanLine.create).not.toHaveBeenCalled();});
 it('replaying a saved work line does not create duplicate work',async()=>{state.db.productionPlanLine.findUnique.mockResolvedValue({planId:'plan',productId:'product',quantity:{toString:()=> '12.34'},startsOn:new Date('2027-01-01'),endsOn:new Date('2027-12-31'),teamId:'team',assignedMembershipId:'member',notes:'Build target'});await addProductionPlanLine(lineForm());expect(state.db.productionPlanLine.create).not.toHaveBeenCalled();});
});
