import {beforeEach,describe,it,expect,vi} from 'vitest';
const mock=vi.hoisted(()=>({lookup:vi.fn()}));
vi.mock('next/headers',()=>({cookies:async()=>({get:()=>({value:'signed-token'})})}));
vi.mock('jsonwebtoken',()=>({default:{verify:()=>({userId:'user',organisationId:'org'})}}));
vi.mock('@/core/db/client',()=>({db:{membership:{findUnique:mock.lookup}}}));
import {getSession} from '@/core/auth/session';
const membership=(grant:boolean,status='ACTIVE',active=true)=>({id:'m',userId:'user',organisationId:'org',active,user:{name:'Owner',email:'owner@example.com',platformAdmin:grant?{userId:'user'}:null},organisation:{name:'Company',status},roles:[{role:{capabilities:['core.users.manage','atlas.companies.manage']}}]});
beforeEach(()=>vi.clearAllMocks());
describe('platform access boundary',()=>{
 it('ignores platform permissions injected through a company role',async()=>{mock.lookup.mockResolvedValue(membership(false));expect((await getSession())?.capabilities.has('atlas.companies.manage')).toBe(false);});
 it('requires an independent platform grant',async()=>{mock.lookup.mockResolvedValue(membership(true));expect((await getSession())?.capabilities.has('atlas.companies.manage')).toBe(true);});
 it('applies company restrictions to administrator grants on each request',async()=>{const row=membership(true);Object.assign(row.organisation,{restrictedAccessAreas:['customers','pricing','audit']});row.roles[0].role.capabilities.push('customers.read','customers.addresses.manage','core.pricing.read','core.audit.read','sales.order.read');mock.lookup.mockResolvedValue(row);const session=await getSession();expect(session?.capabilities.has('customers.read')).toBe(false);expect(session?.capabilities.has('customers.addresses.manage')).toBe(false);expect(session?.capabilities.has('core.pricing.read')).toBe(false);expect(session?.capabilities.has('core.audit.read')).toBe(false);expect(session?.capabilities.has('sales.order.read')).toBe(true);expect(session?.capabilities.has('core.users.manage')).toBe(true);expect(session?.capabilities.has('atlas.companies.manage')).toBe(true);Object.assign(row.organisation,{restrictedAccessAreas:[]});expect((await getSession())?.capabilities.has('customers.read')).toBe(true);});
 it('honours individual denials and revokes old session versions',async()=>{const row=membership(false);row.roles[0].role.capabilities.push('customers.read');Object.assign(row,{grantedCapabilities:['sales.order.read'],deniedCapabilities:['customers.read']});mock.lookup.mockResolvedValue(row);expect((await getSession())?.capabilities.has('customers.read')).toBe(false);expect((await getSession())?.capabilities.has('sales.order.read')).toBe(true);Object.assign(row,{sessionVersion:1});expect(await getSession()).toBeNull();Object.assign(row,{sessionVersion:0});Object.assign(row.user,{authVersion:1});expect(await getSession()).toBeNull();});
 it('blocks suspended companies and paused memberships on the next request',async()=>{mock.lookup.mockResolvedValue(membership(false,'SUSPENDED'));expect(await getSession()).toBeNull();mock.lookup.mockResolvedValue(membership(false,'ACTIVE',false));expect(await getSession()).toBeNull();});
});
