import { beforeEach,expect,it,vi } from 'vitest';
const m=vi.hoisted(()=>({session:{organisationId:'company',userId:'user',capabilities:new Set(['quality.check.execute'])},point:vi.fn(),product:vi.fn(),warehouse:vi.fn(),location:vi.fn(),inspection:vi.fn(),measurement:vi.fn(),hold:vi.fn(),ncr:vi.fn(),audit:vi.fn(),seq:vi.fn(),transaction:vi.fn()}));
vi.mock('@/core/auth/session',()=>({requireSession:async()=>m.session}));vi.mock('@/core/modules/access',()=>({assertModuleEnabled:vi.fn()}));vi.mock('@/core/db/client',()=>({db:{$transaction:m.transaction}}));vi.mock('@/modules/stock/services/provider',()=>({stockProvider:{executeMovement:vi.fn()}}));vi.mock('next/cache',()=>({revalidatePath:vi.fn()}));vi.mock('next/navigation',()=>({redirect:(url:string)=>{throw new Error(`REDIRECT:${url}`);}}));
import { executeInspection } from '@/modules/quality/services/commands';
const point={id:'point',active:true,productId:'product',specificationId:'spec',trigger:'RECEIPT',specification:{organisationId:'company',productId:'product',status:'EFFECTIVE',characteristics:[{id:'size',name:'Diameter',method:'MEASUREMENT',lowerLimit:0,upperLimit:10},{id:'finish',name:'Finish',method:'VISUAL',lowerLimit:null,upperLimit:null}]}};
function form(extra:Record<string,string>={},ids=['size','finish']){const f=new FormData();Object.entries({controlPointId:'point',quantityInspected:'2','value:size':'5','pass:finish':'1',...extra}).forEach(([k,v])=>f.set(k,v));ids.forEach(id=>f.append('characteristicId',id));return f;}
beforeEach(()=>{vi.clearAllMocks();m.session.capabilities=new Set(['quality.check.execute']);m.point.mockResolvedValue(point);m.product.mockResolvedValue({id:'product'});m.warehouse.mockResolvedValue({id:'warehouse'});m.location.mockResolvedValue({id:'location'});m.inspection.mockResolvedValue({id:'inspection'});m.hold.mockResolvedValue({id:'hold'});m.ncr.mockResolvedValue({id:'ncr'});m.seq.mockResolvedValue({value:1});m.transaction.mockImplementation(async fn=>fn({qualityControlPoint:{findFirst:m.point},product:{findFirst:m.product},warehouse:{findFirst:m.warehouse},stockLocation:{findFirst:m.location},qualitySequence:{upsert:m.seq},qualityInspection:{create:m.inspection},qualityMeasurement:{create:m.measurement},qualityHold:{create:m.hold},nonConformance:{create:m.ncr},auditEntry:{create:m.audit}}));});
it.each([[],['size'],['size','size'],['size','foreign']].map(ids=>({ids})))('rejects omitted, duplicated and foreign characteristic sets $ids',async ({ids})=>{await expect(executeInspection(form({},ids))).resolves.toMatchObject({error:expect.stringContaining('exactly once')});expect(m.inspection).not.toHaveBeenCalled();expect(m.audit).not.toHaveBeenCalled();});
it.each(['','NaN','Infinity'])('rejects missing/nonfinite measurement %s',async value=>{await expect(executeInspection(form({'value:size':value}))).resolves.toMatchObject({error:expect.stringContaining('finite measurement')});expect(m.inspection).not.toHaveBeenCalled();});
it('maps each answer by characteristic instead of positional arrays',async()=>{await expect(executeInspection(form({'pass:finish':'0'}))).rejects.toThrow('REDIRECT:/quality/ncr/ncr');expect(m.measurement.mock.calls.map(call=>call[0].data)).toEqual([expect.objectContaining({characteristicId:'size',valueNumber:5,pass:true}),expect.objectContaining({characteristicId:'finish',valueNumber:null,pass:false})]);expect(m.hold).toHaveBeenCalledOnce();expect(m.ncr.mock.calls[0][0].data).toMatchObject({source:'INCOMING',holdId:'hold'});expect(m.audit).toHaveBeenCalledOnce();});
it('records manual failure and opens hold/NCR instead of silently passing',async()=>{m.point.mockResolvedValue({...point,specificationId:null,specification:null});await expect(executeInspection(form({pass:'0'},[]))).rejects.toThrow('REDIRECT:/quality/ncr/ncr');expect(m.inspection.mock.calls[0][0].data.result).toBe('FAIL');expect(m.measurement.mock.calls[0][0].data).toMatchObject({characteristicId:null,pass:false});expect(m.hold).toHaveBeenCalledOnce();});
it('does not accept a missing manual answer or draft specification',async()=>{m.point.mockResolvedValueOnce({...point,specificationId:null,specification:null});await expect(executeInspection(form({},[]))).resolves.toMatchObject({error:expect.stringContaining('Explicitly')});m.point.mockResolvedValueOnce({...point,specification:{...point.specification,status:'DRAFT'}});await expect(executeInspection(form())).resolves.toMatchObject({error:expect.stringContaining('effective')});});
it('rejects foreign warehouse/product/specification and invalid quantity',async()=>{m.warehouse.mockResolvedValueOnce(null);await expect(executeInspection(form({warehouseId:'foreign'}))).resolves.toMatchObject({error:expect.stringContaining('company')});m.product.mockResolvedValueOnce(null);await expect(executeInspection(form())).rejects.toThrow('unavailable');m.point.mockResolvedValueOnce({...point,specification:{...point.specification,organisationId:'foreign'}});await expect(executeInspection(form())).rejects.toThrow('unavailable');await expect(executeInspection(form({quantityInspected:'1.5'}))).resolves.toMatchObject({error:expect.stringContaining('whole quantity')});expect(m.inspection).not.toHaveBeenCalled();});
