import { beforeEach,expect,it,vi } from 'vitest';
const m=vi.hoisted(()=>({session:{organisationId:'company',userId:'user',capabilities:new Set(['quality.ncr.manage','quality.ncr.close','quality.ncr.report'])},ncr:{findFirst:vi.fn(),updateMany:vi.fn(),create:vi.fn()},actions:{create:vi.fn(),updateMany:vi.fn()},member:vi.fn(),product:vi.fn(),sequence:vi.fn(),audit:{create:vi.fn()},enabled:vi.fn(),transaction:vi.fn()}));
vi.mock('@/core/auth/session',()=>({requireSession:async()=>m.session}));vi.mock('@/core/modules/access',()=>({assertModuleEnabled:m.enabled}));vi.mock('@/core/db/client',()=>({db:{$transaction:m.transaction}}));vi.mock('next/cache',()=>({revalidatePath:vi.fn()}));vi.mock('next/navigation',()=>({redirect:(url:string)=>{throw new Error(`REDIRECT:${url}`);}}));
import { reportNcr,updateNcrInvestigation,addNcrAction,updateNcrAction,closeNcr,reopenNcr } from '@/modules/quality/services/ncr-actions';
const row={id:'ncr',number:'NCR-1',version:3,status:'INVESTIGATING',severity:'MAJOR',disposition:'REWORK',rootCauseConfirmed:true,workspace:{legacy:'preserve'},actions:[{id:'action',status:'OPEN',effectivenessCriterion:'No repeat'}]};
function form(extra:Record<string,string>={}){const f=new FormData();Object.entries({ncrId:'ncr',version:'3',title:'Issue',defect:'Requirement failed',source:'FINAL',severity:'MAJOR',disposition:'REWORK',rootCause:'Setup failed',rootCauseConfirmed:'1',causeEvidence:'Setup logs reviewed',...extra}).forEach(([k,v])=>f.set(k,v));return f;}
beforeEach(()=>{vi.clearAllMocks();m.session.capabilities=new Set(['quality.ncr.manage','quality.ncr.close','quality.ncr.report']);m.ncr.findFirst.mockResolvedValue(row);m.ncr.updateMany.mockResolvedValue({count:1});m.ncr.create.mockResolvedValue({id:'new',number:'NCR-2'});m.member.mockResolvedValue({id:'member'});m.product.mockResolvedValue({id:'product'});m.sequence.mockResolvedValue({value:2});m.transaction.mockImplementation(async fn=>fn({nonConformance:m.ncr,nonConformanceAction:m.actions,membership:{findFirst:m.member},product:{findFirst:m.product},qualitySequence:{upsert:m.sequence},auditEntry:m.audit}));});
it('locks parent to signed tenant and submitted version, preserving metadata and atomic audit',async()=>{await expect(updateNcrInvestigation(form())).resolves.toEqual({saved:true});expect(m.ncr.updateMany.mock.calls[0][0].where).toEqual({id:'ncr',organisationId:'company',version:3});expect(m.ncr.updateMany.mock.calls[1][0].data.workspace).toMatchObject({legacy:'preserve',causeEvidence:'Setup logs reviewed'});expect(m.audit.create).toHaveBeenCalledOnce();});
it('returns a safe stale conflict without writes/audit',async()=>{await expect(updateNcrInvestigation(form({version:'2'}))).resolves.toMatchObject({error:expect.stringContaining('changed')});expect(m.ncr.updateMany).not.toHaveBeenCalled();expect(m.audit.create).not.toHaveBeenCalled();});
it('handles a race after read by rejecting zero-row lock',async()=>{m.ncr.updateMany.mockResolvedValue({count:0});await expect(addNcrAction(form())).resolves.toMatchObject({error:expect.stringContaining('changed')});expect(m.actions.create).not.toHaveBeenCalled();expect(m.audit.create).not.toHaveBeenCalled();});
it('does not close unfinished corrective work',async()=>{await expect(closeNcr(form({closureEvidence:'Reviewed the outcomes'}))).resolves.toMatchObject({error:expect.stringContaining('Verify every')});expect(m.audit.create).not.toHaveBeenCalled();});
it('closes only after verified actions and closure evidence, without touching holds',async()=>{m.ncr.findFirst.mockResolvedValue({...row,actions:[{status:'VERIFIED'}]});await expect(closeNcr(form({closureEvidence:'Reviewed 20 subsequent batches'}))).resolves.toEqual({saved:true});expect(m.ncr.updateMany.mock.calls[1][0].data).toMatchObject({status:'CLOSED',workspace:{legacy:'preserve',closureEvidence:'Reviewed 20 subsequent batches'}});expect(m.audit.create).toHaveBeenCalledOnce();});
it('locks closed records and allows reasoned reopening',async()=>{m.ncr.findFirst.mockResolvedValue({...row,status:'CLOSED'});await expect(updateNcrInvestigation(form())).resolves.toMatchObject({error:expect.stringContaining('closed')});await expect(reopenNcr(form({reason:'Repeat failure found during follow-up'}))).resolves.toEqual({saved:true});expect(m.ncr.updateMany.mock.calls.at(-1)?.[0].data).toMatchObject({status:'INVESTIGATING',closedAt:null,workspace:{reopenReason:'Repeat failure found during follow-up'}});});
it('checks active same-company owners and product identifiers',async()=>{m.member.mockResolvedValue(null);await expect(reportNcr(form({ownerUserId:'foreign'}))).resolves.toMatchObject({error:expect.stringContaining('active owner')});m.member.mockResolvedValue({id:'owner'});m.product.mockResolvedValue(null);await expect(reportNcr(form({productId:'foreign'}))).resolves.toMatchObject({error:expect.stringContaining('product from this company')});expect(m.ncr.create).not.toHaveBeenCalled();});
it('creates issue and audit together',async()=>{await expect(reportNcr(form({ownerUserId:'user',dueAt:'2026-10-10'}))).rejects.toThrow('REDIRECT:/quality/ncr/new');expect(m.ncr.create.mock.calls[0][0].data).toMatchObject({organisationId:'company',ownerUserId:'user',workspace:{causeEvidence:'Setup logs reviewed'}});expect(m.audit.create).toHaveBeenCalledOnce();});
it('refuses foreign NCR and child identifiers',async()=>{m.ncr.findFirst.mockResolvedValueOnce(null);await expect(updateNcrInvestigation(form())).rejects.toThrow('unavailable');await expect(updateNcrAction(form({actionId:'foreign',status:'DONE'}))).rejects.toThrow('unavailable');expect(m.actions.updateMany).not.toHaveBeenCalled();});
it('enforces capabilities and module availability before persistence',async()=>{m.session.capabilities.clear();await expect(updateNcrInvestigation(form())).rejects.toThrow('FORBIDDEN');m.session.capabilities.add('quality.ncr.manage');m.enabled.mockRejectedValueOnce(new Error('disabled'));await expect(updateNcrInvestigation(form())).rejects.toThrow('disabled');expect(m.transaction).not.toHaveBeenCalled();});
