import {describe,it,expect} from 'vitest';
import {PDFDocument} from 'pdf-lib';
import {buildQuotePdf,type QuotePdfData} from '@/modules/sales/services/quote-pdf';
export const sampleQuote:QuotePdfData={reference:'Q-TEST-001',organisationName:'Northbridge Group',customerName:'Example Customer Ltd',customerCode:'C001',status:'DRAFT',createdAt:new Date('2026-10-03'),expiryDate:new Date('2026-11-03'),customerPoReference:'PO-1234',paymentTerms:'30 days',currency:'GBP',invoiceAddress:{line1:'12 High Street',city:'London',postcode:'SW1A 1AA',country:'United Kingdom'},deliveryAddress:{line1:'Warehouse One',city:'Manchester',postcode:'M1 1AA',country:'United Kingdom'},netAmount:18000,taxAmount:3600,totalAmount:21600,lines:[{description:'Premium industrial acoustic panel with a long description that wraps cleanly inside its product column.',code:'PANEL-01',quantity:10,unitAmount:2000,discountPercent:10,netAmount:18000,taxAmount:3600}]};
describe('quotation PDF',()=>{
 it('produces a valid A4 document using saved totals',async()=>{const bytes=await buildQuotePdf(sampleQuote);expect(Buffer.from(bytes).subarray(0,4).toString()).toBe('%PDF');const pdf=await PDFDocument.load(bytes);expect(pdf.getPageCount()).toBe(1);expect(pdf.getTitle()).toBe('Quotation Q-TEST-001');expect(pdf.getPage(0).getWidth()).toBeCloseTo(595.28,1);});
 it('labels order acknowledgements distinctly with saved delivery dates',async()=>{const pdf=await PDFDocument.load(await buildQuotePdf({...sampleQuote,documentType:'Order acknowledgement',requestedDeliveryDate:new Date('2026-11-01'),promisedDeliveryDate:new Date('2026-11-02')}));expect(pdf.getTitle()).toBe('Order acknowledgement Q-TEST-001');expect(pdf.getPageCount()).toBe(1);});
 it('paginates long quotations without dropping lines',async()=>{const bytes=await buildQuotePdf({...sampleQuote,lines:Array.from({length:60},(_,i)=>({...sampleQuote.lines[0],description:`Line ${i+1} ${sampleQuote.lines[0].description}`}))});const pdf=await PDFDocument.load(bytes);expect(pdf.getPageCount()).toBeGreaterThan(2);});
});
