import { beforeEach, expect, it, vi } from 'vitest';
const m=vi.hoisted(()=>({session:{organisationId:'company',userId:'user',capabilities:new Set(['safety.risk.create'])},record:{findFirst:vi.fn(),create:vi.fn(),updateMany:vi.fn()},audit:{create:vi.fn()},enabled:vi.fn(),transaction:vi.fn(),reference:vi.fn()}));
vi.mock('@/core/auth/session',()=>({requireSession:async()=>m.session}));
vi.mock('@/core/db/client',()=>({db:{moduleState:{findFirst:m.enabled},$transaction:m.transaction}}));
vi.mock('@/modules/safety/services/numbers',()=>({nextSafetyReference:m.reference}));
vi.mock('next/navigation',()=>({redirect:(url:string)=>{throw new Error(`REDIRECT:${url}`);}}));vi.mock('next/cache',()=>({revalidatePath:vi.fn()}));
import { saveWorkplaceRecord } from '@/modules/safety/services/commands';
const version=new Date('2026-10-08T10:00:00Z');
function form(values:Record<string,string>={}){const f=new FormData();for(const [k,v]of Object.entries({kind:'DSE_ASSESSMENT',title:'Review',recordId:'record',version:version.toISOString(),...values}))f.set(k,v);return f;}
beforeEach(()=>{vi.clearAllMocks();m.session.capabilities=new Set(['safety.risk.create']);m.enabled.mockResolvedValue({id:'enabled'});m.record.findFirst.mockResolvedValue({id:'record',kind:'DSE_ASSESSMENT',updatedAt:version,payload:{legacy:'keep'},status:'OPEN'});m.record.updateMany.mockResolvedValue({count:1});m.record.create.mockResolvedValue({id:'new'});m.reference.mockResolvedValue('WSR-001');m.transaction.mockImplementation(async fn=>fn({safetyRecord:m.record,auditEntry:m.audit}));});
it('scopes updates to signed tenant and expected timestamp; preserves legacy fields; audits atomically without private text',async()=>{await expect(saveWorkplaceRecord(form({finding1:'Private finding'}))).rejects.toThrow('REDIRECT:/safety/records/record');const query=m.record.updateMany.mock.calls[0][0];expect(query.where).toEqual({id:'record',organisationId:'company',updatedAt:version});expect(query.data.payload).toMatchObject({legacy:'keep',finding1:'Private finding'});expect(JSON.stringify(m.audit.create.mock.calls)).not.toContain('Private finding');expect(m.audit.create).toHaveBeenCalledOnce();});
it.each(['stale',''])('rejects stale/missing version %s without writing',async value=>{await expect(saveWorkplaceRecord(form({version:value}))).resolves.toMatchObject({error:expect.stringContaining('changed')});expect(m.record.updateMany).not.toHaveBeenCalled();expect(m.audit.create).not.toHaveBeenCalled();});
it('protects against a concurrent write between read and update',async()=>{m.record.updateMany.mockResolvedValue({count:0});await expect(saveWorkplaceRecord(form())).resolves.toMatchObject({error:expect.stringContaining('changed')});expect(m.audit.create).not.toHaveBeenCalled();});
it('refuses foreign and sensitive existing records',async()=>{m.record.findFirst.mockResolvedValueOnce(null);await expect(saveWorkplaceRecord(form())).rejects.toThrow('unavailable');m.record.findFirst.mockResolvedValueOnce({id:'record',kind:'PEEP',sensitive:true});await expect(saveWorkplaceRecord(form())).rejects.toThrow('FORBIDDEN');expect(m.record.updateMany).not.toHaveBeenCalled();});
it('requires explicit sensitive access and rejects hidden type changes',async()=>{await expect(saveWorkplaceRecord(form({kind:'PEEP'}))).rejects.toThrow('FORBIDDEN');await expect(saveWorkplaceRecord(form({kind:'FIRE_DRILL'}))).resolves.toMatchObject({error:expect.stringContaining('type unchanged')});});
it('rejects capability and module bypasses',async()=>{m.session.capabilities.clear();await expect(saveWorkplaceRecord(form())).rejects.toThrow('FORBIDDEN');m.session.capabilities.add('safety.risk.create');m.enabled.mockResolvedValue(null);await expect(saveWorkplaceRecord(form())).rejects.toThrow('not enabled');expect(m.record.updateMany).not.toHaveBeenCalled();});
it('returns safe expected validation errors before transaction',async()=>{await expect(saveWorkplaceRecord(form({status:'COMPLETE'}))).resolves.toMatchObject({error:expect.stringContaining('completed or checked')});expect(m.transaction).not.toHaveBeenCalled();});
it('creates a central record and audit in one transaction',async()=>{await expect(saveWorkplaceRecord(form({recordId:'',location:'Warehouse',dueAt:'2026-10-09'}))).rejects.toThrow('REDIRECT:/safety/records/new');expect(m.record.create.mock.calls[0][0].data).toMatchObject({organisationId:'company',ownerUserId:'user',sensitive:false,payload:{location:'Warehouse'}});expect(m.audit.create).toHaveBeenCalledOnce();});

it('uses one distinct shared reference series across different workplace record types',async()=>{await expect(saveWorkplaceRecord(form({recordId:'',kind:'FIRE_DRILL'}))).rejects.toThrow('REDIRECT:');await expect(saveWorkplaceRecord(form({recordId:'',kind:'FIRST_AID_KIT'}))).rejects.toThrow('REDIRECT:');for(const call of m.reference.mock.calls)expect(call.slice(1)).toEqual(['company','workplace_record','WSR']);expect(m.reference).toHaveBeenCalledTimes(2);});
