import 'dotenv/config';
import {describe,it,expect,beforeAll,afterAll,vi} from 'vitest';
const state=vi.hoisted(()=>({userId:'',organisationId:'',membershipId:'',capabilities:new Set(['sales.quote.create','sales.quote.approve','sales.order.create','sales.order.edit_draft','sales.order.confirm','sales.order.price_override','sales.order.amend','sales.order.cancel','customers.commercial.manage','customers.addresses.manage'])}));
vi.mock('@/core/auth/session',()=>({requireSession:async()=>state}));
vi.mock('next/cache',()=>({revalidatePath:vi.fn()}));
vi.mock('next/navigation',()=>({redirect:(url:string)=>{throw new Error('REDIRECT:'+url);}}));
import {createSalesAddress} from '@/modules/sales/services/address-actions';
import {saveCustomerTradingLink} from '@/core/customers/trading-actions';
import {persistWorkingDraft,resumeWorkingDraft} from '@/modules/sales/services/working-drafts';
import {db} from '@/core/db/client';
import {saveDocument} from '@/modules/sales/services/documents';
import {createOrderFromQuote} from '@/modules/sales/services/commands';
import {scheduleOrderDelivery} from '@/app/(app)/sales/orders/actions';
import {confirmOrder,cancelOrder} from '@/modules/sales/services/orders';
import {assertRecordCreationAllowed} from '@/core/policies/record-creation';
describe.runIf(process.env.ATLAS_DB_TESTS==='1')('isolated Sales database journey',()=>{
 let partyId='',productId='',billingId='',deliveryId='',quoteId='',orderId='';
 beforeAll(async()=>{const suffix=crypto.randomUUID();const org=await db.organisation.create({data:{name:'Disposable Sales workflow test',slug:'sales-test-'+suffix}});state.organisationId=org.id;const user=await db.user.create({data:{name:'Sales Test',email:`sales-${suffix}@example.test`,passwordHash:'not-a-login-password'}});state.userId=user.id;const member=await db.membership.create({data:{organisationId:org.id,userId:user.id}});state.membershipId=member.id;await db.moduleState.create({data:{organisationId:org.id,moduleId:'sales',enabled:true,entitled:true}});const party=await db.party.create({data:{organisationId:org.id,kind:'COMPANY',name:'Sales test customer',customerCode:'TEST01',commercialSettings:{create:{customerPoRequired:true,orderReferenceRequired:true}},addresses:{create:[{type:'BILLING',line1:'1 Test Street',country:'GB',isDefaultBilling:true},{type:'DELIVERY',line1:'2 Test Street',country:'GB',isDefaultDelivery:true}]}},include:{addresses:true}});partyId=party.id;billingId=party.addresses.find(a=>a.type==='BILLING')!.id;deliveryId=party.addresses.find(a=>a.type==='DELIVERY')!.id;const product=await db.product.create({data:{organisationId:org.id,code:'TEST-SKU',name:'Test product',basePriceAmount:10000,baseCurrency:'GBP',kind:'PRODUCT',unitOfMeasure:'each',taxCategory:'STANDARD'}});productId=product.id;});
 afterAll(async()=>{if(state.organisationId)await db.organisation.delete({where:{id:state.organisationId}});if(state.userId)await db.user.delete({where:{id:state.userId}});await db.$disconnect();});
 const form=()=>{const f=new FormData();for(const [key,value]of Object.entries({mode:'quote',partyId,invoiceAddressId:billingId,deliveryAddressId:deliveryId,customerPoReference:'PO-TEST',externalReference:'JOB-TEST',tags:'Priority, Repeat',notes:'Commercial terms'}))f.set(key,value);f.set('lines',JSON.stringify([{type:'SECTION',description:'Supply',productId:'',quantity:1,discount:0},{type:'PRODUCT',productId,description:'Included',quantity:3,discount:12.5},{type:'PRODUCT',productId,description:'Optional',quantity:1,discount:0,optional:true}]));return f;};
 it('saves real product lines, notes, tags, optional exclusions and decimal discounts atomically',async()=>{await expect(saveDocument({error:''},form())).rejects.toThrow('REDIRECT:');const q=await db.quote.findFirstOrThrow({where:{organisationId:state.organisationId},include:{lines:true}});quoteId=q.id;expect(q).toMatchObject({netAmount:26250,taxAmount:5250,totalAmount:31500,customerNotes:'Commercial terms',tags:['priority','repeat']});expect(q.lines).toHaveLength(3);});
 it('rejects a stale edit without deleting the saved lines',async()=>{const f=form();f.set('documentId',quoteId);f.set('version','2000-01-01T00:00:00.000Z');expect((await saveDocument({error:''},f)).error).toContain('another window');expect(await db.quoteLine.count({where:{quoteId}})).toBe(3);});
 it('accepts a quotation into one draft order with saved prices and no optional products',async()=>{await expect(createOrderFromQuote(quoteId)).rejects.toThrow('REDIRECT:');const o=await db.salesOrder.findFirstOrThrow({where:{organisationId:state.organisationId},include:{lines:true}});orderId=o.id;expect(o).toMatchObject({netAmount:26250,taxAmount:5250,grossAmount:31500,externalReference:'JOB-TEST'});expect(o.lines).toHaveLength(2);expect(o.lines.find(l=>l.productId)?.discountPercent).toBe(12.5);});
 it('confirms the commercial sale with address, PO, reference, credit and tax checks',async()=>{expect(await confirmOrder(orderId)).toMatchObject({confirmed:true});const o=await db.salesOrder.findUniqueOrThrow({where:{id:orderId}});expect(o.commercialStatus).toBe('CONFIRMED');expect(await db.salesOrderRevision.count({where:{orderId}})).toBe(1);expect(await db.domainOutbox.count({where:{organisationId:state.organisationId}})).toBe(1);expect(await db.auditEntry.count({where:{organisationId:state.organisationId,entityId:orderId}})).toBeGreaterThan(0);});
 it('preserves confirmed delivery revisions and rejects stale schedules',async()=>{const o=await db.salesOrder.findUniqueOrThrow({where:{id:orderId}});const f=new FormData();f.set('confirmed','yes');f.set('version',o.updatedAt.toISOString());f.set('reason','Customer agreed delivery');f.set('requestedDeliveryDate','2026-11-01');f.set('promisedDeliveryDate','2026-11-02');await scheduleOrderDelivery(orderId,f);expect(await db.salesOrderRevision.count({where:{orderId}})).toBe(2);await expect(scheduleOrderDelivery(orderId,f)).rejects.toThrow('changed');expect(await db.salesOrderRevision.count({where:{orderId}})).toBe(2);});
 it('cancels atomically while retaining the agreed commercial value in history',async()=>{await cancelOrder(orderId,'Test cancellation');const o=await db.salesOrder.findUniqueOrThrow({where:{id:orderId}});expect(o).toMatchObject({commercialStatus:'CANCELLED',grossAmount:0});const revisions=await db.salesOrderRevision.findMany({where:{orderId},orderBy:{revision:'asc'}});expect(revisions).toHaveLength(3);expect(revisions[0].snapshot).toMatchObject({grossAmount:31500,commercialStatus:'CONFIRMED'});expect(revisions[2].snapshot).toMatchObject({grossAmount:0,commercialStatus:'CANCELLED'});});
 it('uses negotiated pricing through a trading account and carries distinct notes into the order',async()=>{
  const beneficiary=await db.party.create({data:{organisationId:state.organisationId,kind:'COMPANY',name:'Pricing beneficiary',customerCode:'BENEFICIARY'}});
  const link=new FormData();link.set('tradingAccountId',partyId);await saveCustomerTradingLink(beneficiary.id,link);
  await db.customerProduct.create({data:{partyId:beneficiary.id,productId,contractedPriceAmount:5000,contractedPriceCurrency:'GBP'}});
  const f=form();f.set('pricingPartyId',beneficiary.id);f.set('deliveryInstructions','Use the side gate');f.set('financeInstructions','Bill merchant using PO');f.set('lines',JSON.stringify([{type:'PRODUCT',productId,description:'Agreed product',quantity:2,discount:0}]));await expect(saveDocument({error:''},f)).rejects.toThrow('REDIRECT:');
  const q=await db.quote.findFirstOrThrow({where:{organisationId:state.organisationId,pricingPartyId:beneficiary.id}});expect(q).toMatchObject({partyId,netAmount:10000,deliveryInstructions:'Use the side gate',financeInstructions:'Bill merchant using PO'});
  await expect(createOrderFromQuote(q.id)).rejects.toThrow('REDIRECT:');const o=await db.salesOrder.findUniqueOrThrow({where:{quoteId:q.id}});expect(o).toMatchObject({partyId,pricingPartyId:beneficiary.id,netAmount:10000,deliveryInstructions:'Use the side gate',financeInstructions:'Bill merchant using PO'});
  await db.customerTradingLink.updateMany({where:{accountId:beneficiary.id},data:{active:false}});await expect(confirmOrder(o.id)).rejects.toThrow('no longer linked');
 });
 it('rejects an unrelated pricing account and a foreign company trading link',async()=>{
  const unlinked=await db.party.create({data:{organisationId:state.organisationId,kind:'COMPANY',name:'Unlinked',customerCode:'UNLINKED'}});const f=form();f.set('pricingPartyId',unlinked.id);expect((await saveDocument({error:''},f)).error).toContain('Link this pricing account');
  const foreign=await db.organisation.create({data:{name:'Foreign test',slug:'foreign-'+crypto.randomUUID()}});try{const p=await db.party.create({data:{organisationId:foreign.id,kind:'COMPANY',name:'Foreign',customerCode:'FOREIGN'}}),link=new FormData();link.set('tradingAccountId',p.id);await expect(saveCustomerTradingLink(partyId,link)).rejects.toThrow('Both accounts');}finally{await db.organisation.delete({where:{id:foreign.id}});}
 });
 it('recovers notes and protects autosaves from late writes and other users',async()=>{
  const id=crypto.randomUUID(),payload={mode:'order',partyId,notes:'New notes',financeInstructions:'Finance only',deliveryInstructions:'Site instructions',lines:JSON.stringify([{type:'PRODUCT',productId,quantity:1,discount:0}])};await persistWorkingDraft(state as never,id,payload,200);await persistWorkingDraft(state as never,id,{...payload,notes:'Stale notes'},100);expect(await resumeWorkingDraft(state as never,id)).toMatchObject({notes:'New notes',financeInstructions:'Finance only',deliveryInstructions:'Site instructions'});
  await expect(resumeWorkingDraft({...state,userId:'other-user'} as never,id)).rejects.toThrow();await expect(persistWorkingDraft({...state,userId:'other-user'} as never,id,payload,300)).rejects.toThrow();
  await db.salesWorkingDraft.update({where:{id},data:{archived:true}});await persistWorkingDraft(state as never,id,{...payload,notes:'After save'},400);expect((await db.salesWorkingDraft.findUniqueOrThrow({where:{id}})).archived).toBe(true);
 });
 it('creates a delivery address from Sales as a canonical customer address with an audit entry',async()=>{const f=new FormData();for(const [key,value] of Object.entries({partyId,type:'DELIVERY',label:'Job site',line1:'3 Test Lane',line2:'',city:'Bristol',region:'',postcode:'BS1 1AA',country:'GB'}))f.set(key,value);const address=await createSalesAddress('order',f);expect(address).toMatchObject({partyId,type:'DELIVERY',country:'GB',defaultDelivery:false});expect(await db.address.findUniqueOrThrow({where:{id:address.id}})).toMatchObject({line1:'3 Test Lane'});expect(await db.auditEntry.count({where:{organisationId:state.organisationId,entityId:address.id}})).toBe(1);f.set('line1','');await expect(createSalesAddress('order',f)).rejects.toThrow();});
 it('enforces company creation controls without disabling existing catalogue use',async()=>{await db.organisation.update({where:{id:state.organisationId},data:{allowProductCreation:false,allowCustomerCreation:false}});await expect(assertRecordCreationAllowed(state.organisationId,'products')).rejects.toThrow('disabled');await expect(assertRecordCreationAllowed(state.organisationId,'customers')).rejects.toThrow('disabled');expect(await db.product.count({where:{organisationId:state.organisationId,id:productId}})).toBe(1);});
});
