import {describe,it,expect} from 'vitest';
import ExcelJS from 'exceljs';
import {orderWhere,quoteWhere} from '@/modules/sales/services/list-filters';
import {selectedColumns} from '@/modules/sales/services/view-definition';
import {exportCsv,exportWorkbook} from '@/modules/sales/services/export-file';
describe('Sales views and exports',()=>{
 it('combines multi-select groups with tenant scope and nested advanced OR rules',()=>{const where=orderWhere('org-a',{owner:'u1,u2',customer:'c1,c2',tag:'Priority,repeat',tagMode:'all',status:'DRAFT,CONFIRMED',rules:JSON.stringify([{field:'po',operator:'contains',value:'ABC'},{field:'productCode',operator:'eq',value:'SKU01'}]),match:'any'});expect(where).toMatchObject({organisationId:'org-a',ownerUserId:{in:['u1','u2']},partyId:{in:['c1','c2']},tags:{hasEvery:['priority','repeat']},commercialStatus:{in:['DRAFT','CONFIRMED']},AND:[{OR:[{customerPoReference:{contains:'ABC'}},{lines:{some:{product:{code:{equals:'SKU01'}}}}}]}]});});
 it('requires a currency for monetary comparisons and converts amounts to minor units',()=>{const rules=JSON.stringify([{field:'total',operator:'gte',value:'123.45'}]);expect(()=>orderWhere('a',{rules})).toThrow('currency');expect(orderWhere('a',{rules,currency:'GBP'})).toMatchObject({currency:{in:['GBP']},AND:[{AND:[{grossAmount:{gte:12345}}]}]});});
 it('rejects unsupported fields/operators and preserves inclusive dates',()=>{expect(()=>orderWhere('a',{rules:JSON.stringify([{field:'passwordHash',operator:'eq',value:'x'}])})).toThrow();expect(()=>quoteWhere('a',{rules:JSON.stringify([{field:'requested',operator:'eq',value:'2026-10-01'}])})).toThrow('document type');expect(orderWhere('a',{dateField:'promised',from:'2026-10-01',to:'2026-10-03'})).toMatchObject({promisedDeliveryDate:{gte:new Date('2026-10-01'),lte:new Date('2026-10-03T23:59:59.999Z')}});});
 it('keeps the clickable number and excludes unknown/sensitive columns',()=>{expect(selectedColumns('total,passwordHash,total,currency')).toEqual(['number','total','currency']);});
 it('quotes multiline CSV values and prevents spreadsheet formula execution',()=>{const csv=exportCsv([{key:'name',label:'Customer'}],[{name:'=HYPERLINK("x")'},{name:'Company, Limited\nSite 2'}]);expect(csv).toContain('"\'=HYPERLINK(""x"")"');expect(csv).toContain('"Company, Limited\nSite 2"');});
 it('exports Excel amounts as numbers, freezes headings and preserves dangerous text as literal strings',async()=>{const bytes=await exportWorkbook([{key:'name',label:'Customer'},{key:'total',label:'Total',type:'money'}],[{name:'=SUM(1,2)',total:123.45}],'Sales orders'),book=new ExcelJS.Workbook();await book.xlsx.load(new Uint8Array(bytes).buffer);const sheet=book.getWorksheet(1)!;expect(sheet.getCell('A2').value).toBe('=SUM(1,2)');expect(sheet.getCell('B2').value).toBe(123.45);expect(sheet.getCell('B2').numFmt).toBe('#,##0.00');expect(sheet.views[0]).toMatchObject({state:'frozen',ySplit:1});});
});
