import {beforeEach,describe,it,expect,vi} from 'vitest';
const s=vi.hoisted(()=>({session:{userId:'user',organisationId:'org',capabilities:new Set(['sales.quote.create','sales.order.create'])},quote:{findFirstOrThrow:vi.fn(),updateMany:vi.fn()},order:{findFirst:vi.fn(),create:vi.fn()},audit:{create:vi.fn()},transaction:vi.fn()}));
vi.mock('@/core/auth/session',()=>({requireSession:async()=>s.session}));vi.mock('@/core/modules/access',()=>({assertModuleEnabled:vi.fn()}));vi.mock('@/core/db/client',()=>({db:{quote:s.quote,salesOrder:s.order,auditEntry:s.audit,$transaction:s.transaction}}));vi.mock('next/cache',()=>({revalidatePath:vi.fn()}));vi.mock('next/navigation',()=>({redirect:(url:string)=>{throw new Error('REDIRECT:'+url);}}));vi.mock('@/core/events/bus',()=>({emit:vi.fn(),DOMAIN_EVENTS:{}}));
import {createOrderFromQuote,sendQuote} from '@/modules/sales/services/commands';
const quote=()=>({id:'q',organisationId:'org',partyId:'customer',status:'SENT',updatedAt:new Date(),expiryDate:null,totalCurrency:'GBP',tags:['priority'],party:{commercialSettings:null},lines:[{id:'included',lineNumber:1,type:'PRODUCT',productId:'sku',description:'Product',quantity:2,unitAmount:10000,discountPercent:12.5,taxAmount:3500,optional:false},{id:'optional',lineNumber:2,type:'PRODUCT',productId:'extra',description:'Extra',quantity:1,unitAmount:9000,discountPercent:0,taxAmount:1800,optional:true}]});
beforeEach(()=>{vi.clearAllMocks();s.quote.findFirstOrThrow.mockResolvedValue(quote());s.quote.updateMany.mockResolvedValue({count:1});s.order.findFirst.mockResolvedValue(null);s.order.create.mockResolvedValue({id:'order',reference:'SO-TEST'});s.transaction.mockImplementation(async f=>f({quote:s.quote,salesOrder:s.order,auditEntry:s.audit}));});
describe('atomic quote to order lifecycle',()=>{
 it('excludes optional products, preserves decimal discounts and audits conversion',async()=>{await expect(createOrderFromQuote('q')).rejects.toThrow('REDIRECT:/sales/orders/order');expect(s.order.create.mock.calls[0][0].data).toMatchObject({netAmount:17500,taxAmount:3500,grossAmount:21000,tags:['priority'],lines:{create:[{productId:'sku',discountPercent:12.5}]}});expect(s.order.create.mock.calls[0][0].data.lines.create).toHaveLength(1);expect(s.audit.create).toHaveBeenCalledTimes(1);});
 it('does not create an order after a concurrent quotation edit',async()=>{s.quote.updateMany.mockResolvedValue({count:0});await expect(createOrderFromQuote('q')).rejects.toThrow('changed');expect(s.order.create).not.toHaveBeenCalled();});
 it('refuses an expired quotation before any transition or order write',async()=>{s.quote.findFirstOrThrow.mockResolvedValue({...quote(),expiryDate:new Date('2020-01-01')});await expect(createOrderFromQuote('q')).rejects.toThrow('expired');expect(s.quote.updateMany).not.toHaveBeenCalled();expect(s.order.create).not.toHaveBeenCalled();});
 it('returns the existing linked order on repeated conversion',async()=>{s.order.findFirst.mockResolvedValue({id:'existing'});await expect(createOrderFromQuote('q')).rejects.toThrow('REDIRECT:/sales/orders/existing');expect(s.transaction).not.toHaveBeenCalled();});
 it('rejects marking accepted or sent quotations as sent again',async()=>{await expect(sendQuote('q')).rejects.toThrow('draft');expect(s.quote.updateMany).not.toHaveBeenCalled();});
});
