"use client";
import {useEffect,useRef,useState,useTransition} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {ChevronLeft,ChevronRight,Plus,X,Check,Clock3,CalendarDays,Users,Send,Trash2} from "lucide-react";
import {Button} from "@/components/ui/button";
import {createBulkShifts,editScheduledShift,setScheduledShift,publishWeekShifts,completeShiftTask,saveHoursBudget} from "@/app/(app)/scheduling/actions";
import type {getSchedule} from "@/app/(app)/scheduling/actions";
import {londonDate,londonTime} from "@/modules/scheduling/domain/time";
import {addDays} from "@/modules/people/domain/working-time";
type Data=Awaited<ReturnType<typeof getSchedule>>;
type Editor={staff:string[];days:string[];shift?:Data["shifts"][number]};
const input="mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm focus:outline-2 focus:outline-blue-500";
const dateKey=(date:Date)=>date.toISOString().slice(0,10);
const label=(date:Date,options:Intl.DateTimeFormatOptions)=>date.toLocaleDateString("en-GB",{timeZone:"UTC",...options});
export function RotaPlanner({data,query}:{data:Data;query:{q?:string;department?:string;view?:string}}){
 const router=useRouter(),dialog=useRef<HTMLDialogElement>(null);
 const [editor,setEditor]=useState<Editor|null>(null),[start,setStart]=useState("09:00"),[end,setEnd]=useState("17:00"),[breakMinutes,setBreakMinutes]=useState(30);
 const [pending,transition]=useTransition(),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [staffSearch,setStaffSearch]=useState("");
 const {manage,employees,shifts,absences,weekStart}=data;
 const days=Array.from({length:7},(_,i)=>addDays(weekStart,i));
 const hours=(shift:Data["shifts"][number])=>(shift.endsAt.getTime()-shift.startsAt.getTime())/3600000-shift.breakMinutes/60;
 const draftCount=shifts.filter(s=>s.status==="SCHEDULED").length;
 const totalHours=shifts.reduce((sum,s)=>sum+hours(s),0);
 const href=(week:Date,own=query.view==="mine")=>{const params=new URLSearchParams({week:dateKey(week)});if(query.q)params.set("q",query.q);if(query.department)params.set("department",query.department);if(own)params.set("view","mine");return `/scheduling?${params}`;};
 useEffect(()=>{if(editor&&!dialog.current?.open)dialog.current?.showModal();if(!editor&&dialog.current?.open)dialog.current.close();},[editor]);
 function open(next:Editor){setError("");setStaffSearch("");setStart(next.shift?londonTime(next.shift.startsAt):"09:00");setEnd(next.shift?londonTime(next.shift.endsAt):"17:00");setBreakMinutes(next.shift?.breakMinutes??30);setEditor(next);}
 function toggle(kind:"staff"|"days",value:string){setEditor(current=>current?{...current,[kind]:current[kind].includes(value)?current[kind].filter(v=>v!==value):[...current[kind],value]}:current);}
 function run(action:()=>Promise<void>,success:string,close=false){setError("");setNotice("");transition(async()=>{try{await action();if(close)setEditor(null);setNotice(success);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Could not save. Try again.");}});}
 function save(form:FormData){if(!editor)return;const current=editor;if(!current.shift){if(!current.staff.length||!current.days.length){setError("Choose at least one person and one day.");return;}for(const id of current.staff)form.append("employeeId",id);for(const day of current.days)form.append("dates",day);form.set("weekStart",dateKey(weekStart));}else form.set("day",current.days[0]);run(()=>current.shift?editScheduledShift(current.shift.id,form):createBulkShifts(form),current.shift?"Shift updated.":`${current.staff.length*current.days.length} shift${current.staff.length*current.days.length===1?"":"s"} saved.`,true);}
 const selectedName=editor?.shift?employees.find(e=>e.id===editor.shift?.employeeId):null;
 const staffOptions=employees.filter(e=>`${e.firstName} ${e.lastName} ${e.department??""}`.toLowerCase().includes(staffSearch.toLowerCase()));
 return <div className="space-y-5">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-semibold tracking-tight">{manage?"Plan your team’s week":"Your week at a glance"}</h2><p className="mt-1 text-sm text-slate-500">{manage?"Click a day to add a shift. Click a shift to change it.":"Published shifts, your tasks and time off, all in one place."}</p></div><div className="flex flex-wrap gap-2">{manage&&<><Button disabled={pending||!draftCount} onClick={()=>{const form=new FormData();form.set("weekStart",dateKey(weekStart));for(const e of employees)form.append("employeeId",e.id);run(()=>publishWeekShifts(form),"This week’s draft shifts are now published.");}}><Send size={15}/>{pending?"Saving…":`Publish ${draftCount||""} drafts`}</Button><Button variant="primary" disabled={!employees.length||pending} onClick={()=>open({staff:[],days:[dateKey(days[0])]})}><Plus size={16}/>Add shifts</Button></>}</div></div>
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[{icon:Users,title:"Staff in view",value:employees.length},{icon:Clock3,title:"Planned paid hours",value:`${totalHours.toFixed(1)}h`},{icon:CalendarDays,title:"Published shifts",value:shifts.length-draftCount},{icon:Send,title:"Ready to publish",value:draftCount}].map(({icon:Icon,title,value})=><div key={title} className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white px-4 py-3"><span className="rounded-xl bg-slate-50 p-2 text-slate-400"><Icon size={17}/></span><div><p className="text-xl font-semibold">{value}</p><p className="text-xs text-slate-500">{title}</p></div></div>)}</div>
  {manage&&data.budget&&<section aria-label="Weekly hours budget" className={`rounded-2xl border p-4 ${data.budget.minutes!==null&&data.budget.plannedMinutes>data.budget.minutes?"border-amber-200 bg-amber-50":"border-slate-200 bg-white"}`}>
   <div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="text-sm font-semibold">Weekly hours budget</h3><p className="mt-1 text-xs text-slate-500">{data.budget.department||"Your whole managed team"} · {data.budget.staffCount} staff · includes all staff in this scope, regardless of search</p></div><form action={form=>run(()=>saveHoursBudget(form),"Weekly hours budget saved.")} className="flex items-end gap-2"><input type="hidden" name="weekStart" value={dateKey(weekStart)}/><input type="hidden" name="department" value={data.budget.department}/><label className="text-xs text-slate-500">Budget hours<input name="hours" type="number" step="0.25" min="0" max="1000000" required defaultValue={data.budget.minutes===null?"":data.budget.minutes/60} key={`${dateKey(weekStart)}-${data.budget.department}-${data.budget.minutes}`} placeholder={(data.budget.contractMinutes/60).toFixed(1)} className={`${input} max-w-36`}/></label><Button type="submit" disabled={pending}>Save budget</Button></form></div>
   <div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5">{[{label:"Hours budget",value:data.budget.minutes===null?"Not set":`${(data.budget.minutes/60).toFixed(1)}h`},{label:"Planned hours",value:`${(data.budget.plannedMinutes/60).toFixed(1)}h`},{label:data.budget.minutes!==null&&data.budget.plannedMinutes>data.budget.minutes?"Over budget":"Hours remaining",value:data.budget.minutes===null?"—":`${(Math.abs(data.budget.minutes-data.budget.plannedMinutes)/60).toFixed(1)}h`},{label:"Approved actual hours",value:`${(data.budget.approvedMinutes/60).toFixed(1)}h`},{label:"Contracted hours",value:`${(data.budget.contractMinutes/60).toFixed(1)}h`}].map(item=><div key={item.label}><p className="text-lg font-semibold">{item.value}</p><p className="mt-1 text-xs text-slate-500">{item.label}</p></div>)}</div>
   {data.budget.minutes!==null&&<div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${data.budget.plannedMinutes>data.budget.minutes?"bg-amber-500":"bg-blue-500"}`} style={{width:`${data.budget.minutes?Math.min(100,data.budget.plannedMinutes/data.budget.minutes*100):data.budget.plannedMinutes?100:0}%`}}/></div>}
   <p className="mt-3 text-[11px] text-slate-500">Your saved planning budget for this week and scope. Over-budget plans are flagged; publishing remains available. Actual hours include approved timesheets only.</p>
  </section>}
  <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white p-3"><div className="flex items-center gap-2"><Link aria-label="Previous week" href={href(addDays(weekStart,-7))} className="rounded-lg border p-2 hover:bg-slate-50"><ChevronLeft size={17}/></Link><span className="min-w-36 text-center text-sm font-semibold">{label(weekStart,{day:"numeric",month:"short"})} – {label(days[6],{day:"numeric",month:"short",year:"numeric"})}</span><Link aria-label="Next week" href={href(addDays(weekStart,7))} className="rounded-lg border p-2 hover:bg-slate-50"><ChevronRight size={17}/></Link><Link href={href(new Date())} className="rounded-lg px-2 py-2 text-xs text-blue-600">This week</Link></div><div className="flex items-center gap-2">{manage&&<Link href={href(weekStart,true)} className="rounded-lg px-3 py-2 text-xs text-slate-600 hover:bg-slate-50">My shifts</Link>}{!manage&&query.view==="mine"&&<Link href={href(weekStart,false)} className="rounded-lg px-3 py-2 text-xs text-blue-600">Team rota</Link>}<Link href={`/people/timesheets?week=${dateKey(weekStart)}`} className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-medium">Actual hours</Link><Link href="/people/me" className="rounded-lg px-3 py-2 text-xs text-slate-600">Time off</Link></div></div>
  {manage&&<form className="flex flex-wrap items-end gap-2"><input type="hidden" name="week" value={dateKey(weekStart)}/><label className="min-w-48 flex-1 text-xs text-slate-500">Find staff<input name="q" defaultValue={query.q??""} placeholder="Name or role" className={input}/></label><label className="text-xs text-slate-500">Department<select name="department" defaultValue={query.department??""} className={input}><option value="">All departments</option>{data.departments.map(d=><option key={d}>{d}</option>)}</select></label><Button type="submit">Apply</Button>{(query.q||query.department)&&<Link href={href(weekStart).split("&q=")[0].split("&department=")[0]} className="p-2 text-xs text-blue-600">Clear</Link>}</form>}
  {notice&&<p role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}{error&&!editor&&<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
  <section aria-label="Weekly staff rota" className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1120px] table-fixed border-collapse text-sm"><thead><tr className="border-b border-slate-200 bg-slate-50/80"><th className="sticky left-0 z-20 w-56 bg-slate-50 p-4 text-left text-xs font-medium text-slate-500">Your team</th>{days.map(d=><th key={dateKey(d)} className={`p-3 text-left ${dateKey(d)===dateKey(new Date())?"bg-blue-50 text-blue-700":"text-slate-500"}`}><p className="text-xs font-medium">{label(d,{weekday:"short"})}</p><p className="mt-0.5 text-lg font-semibold">{label(d,{day:"numeric"})}</p></th>)}</tr></thead><tbody>{employees.map(e=>{const employeeHours=shifts.filter(s=>s.employeeId===e.id).reduce((sum,s)=>sum+hours(s),0),contracted=e.contractedWeeklyHours??data.standardHours;return <tr key={e.id} className="border-b border-slate-100 align-top last:border-0"><th className="sticky left-0 z-10 bg-white px-4 py-4 text-left"><div className="flex items-center gap-2"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-slate-100 text-xs font-medium text-slate-500">{e.firstName[0]}{e.lastName[0]}</span><div><p className="text-sm font-medium">{e.firstName} {e.lastName}</p><p className="mt-0.5 truncate text-[11px] font-normal text-slate-400">{e.department??e.jobTitle}</p></div></div><div className="mt-3 flex items-center justify-between text-[11px] font-normal"><span className={employeeHours>contracted?"text-amber-700":"text-slate-500"}>{employeeHours.toFixed(1)} / {contracted}h</span><span className="text-slate-400">{employeeHours>contracted?"Over target":"Planned"}</span></div><div className="mt-1 h-1 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${employeeHours>contracted?"bg-amber-400":"bg-blue-400"}`} style={{width:`${Math.min(100,employeeHours/contracted*100)}%`}}/></div></th>{days.map(d=>{const day=dateKey(d),unavailable=absences.some(a=>a.employeeId===e.id&&dateKey(a.startDate)<=day&&dateKey(a.endDate)>=day),daily=shifts.filter(s=>s.employeeId===e.id&&londonDate(s.startsAt)===day);return <td key={day} className={`border-l border-slate-100 p-2 ${dateKey(d)===dateKey(new Date())?"bg-blue-50/20":""}`}>
    {unavailable&&<div className="mb-2 rounded-xl bg-amber-50 px-2.5 py-3 text-xs font-medium text-amber-700">Time off</div>}{daily.map(s=><div key={s.id} className="mb-2"><button type="button" disabled={pending} onClick={()=>open({staff:[e.id],days:[day],shift:s})} className={`w-full rounded-xl border px-2.5 py-3 text-left transition hover:shadow-sm ${s.status==="SCHEDULED"?"border-dashed border-slate-300 bg-slate-50":"border-blue-100 bg-blue-50 text-blue-950"}`}><p className="text-xs font-semibold">{londonTime(s.startsAt)} – {londonTime(s.endsAt)}{londonDate(s.endsAt)!==day?" +1":""}</p>{s.role&&<p className="mt-1 truncate text-[11px] text-slate-500">{s.role}</p>}<div className="mt-2 flex flex-wrap items-center gap-1 text-[10px] text-slate-500"><span>{hours(s).toFixed(1)}h</span><span>·</span><span>{s.status==="SCHEDULED"?"Draft":"Published"}</span>{s.tasks.length>0&&<span className="ml-auto rounded bg-white px-1.5 py-0.5">{s.tasks.filter(t=>t.completedAt).length}/{s.tasks.length} tasks</span>}</div></button></div>)}{manage&&!unavailable&&<button type="button" aria-label={`Add shift for ${e.firstName} ${e.lastName} on ${label(d,{weekday:"long",day:"numeric",month:"long"})}`} disabled={pending} onClick={()=>open({staff:[e.id],days:[day]})} className={`flex w-full items-center justify-center rounded-xl border border-dashed border-transparent py-2 text-slate-300 hover:border-blue-200 hover:bg-blue-50 hover:text-blue-500 ${daily.length?"":"min-h-20"}`}><Plus size={16}/></button>}{!manage&&!daily.length&&!unavailable&&<span className="block py-6 text-center text-xs text-slate-300">Day off</span>}
   </td>})}</tr>})}</tbody></table></div>{!employees.length&&<div className="px-6 py-12 text-center"><Users className="mx-auto mb-3 text-slate-300" size={28}/><p className="font-medium">No staff to show</p><p className="mt-1 text-sm text-slate-500">{query.q||query.department?"Try another search or department.":"Your employee record or team assignment needs to be linked to your Atlas account."}</p></div>}<div className="flex flex-wrap justify-between gap-2 border-t border-slate-100 px-4 py-3 text-[11px] text-slate-400"><span>Drafts stay with managers. Publishing shares shifts with staff.</span><span>London time · {data.total>100?`100 of ${data.total} staff — filter by department`:employees.length+" staff"}</span></div></section>
  <dialog ref={dialog} aria-label={editor?.shift?"Shift details":"Add shifts"} onCancel={event=>{event.preventDefault();if(!pending)setEditor(null);}} onClick={event=>{if(event.target===event.currentTarget&&!pending)setEditor(null);}} className="m-auto max-h-[90vh] w-[min(680px,calc(100vw-32px))] overflow-y-auto rounded-3xl border-0 bg-white p-0 shadow-2xl backdrop:bg-slate-900/30">
   {editor&&<div><header className="sticky top-0 z-10 flex items-start justify-between border-b border-slate-100 bg-white px-6 py-5"><div><h3 className="text-lg font-semibold">{editor.shift?(manage?"Edit shift":"Your shift"):"Add shifts"}</h3><p className="mt-1 text-xs text-slate-500">{editor.shift?`${selectedName?.firstName} ${selectedName?.lastName} · ${label(dateOnlyClient(editor.days[0]),{weekday:"long",day:"numeric",month:"short"})}`:"Choose people and days, then set their hours."}</p></div><button type="button" autoFocus aria-label="Close shift editor" disabled={pending} onClick={()=>setEditor(null)} className="rounded-full p-2 text-slate-400 hover:bg-slate-100"><X size={20}/></button></header>
   {manage?<form action={save} className="space-y-5 p-6"><fieldset disabled={pending} className="space-y-5">
    {!editor.shift&&<><fieldset><legend className="text-sm font-medium">People <span className="ml-1 text-xs font-normal text-slate-400">{editor.staff.length} selected</span></legend><input aria-label="Find people to schedule" placeholder="Find a person" value={staffSearch} onChange={event=>setStaffSearch(event.target.value)} className={input}/><div className="mt-2 max-h-44 overflow-y-auto rounded-xl border border-slate-200"><label className="flex cursor-pointer items-center gap-3 border-b border-slate-100 bg-slate-50 px-3 py-2 text-xs"><input type="checkbox" checked={staffOptions.length>0&&staffOptions.every(e=>editor.staff.includes(e.id))} onChange={event=>setEditor({...editor,staff:event.target.checked?[...new Set([...editor.staff,...staffOptions.map(e=>e.id)])]:editor.staff.filter(id=>!staffOptions.some(e=>e.id===id))})}/>Select everyone shown</label>{staffOptions.map(e=><label key={e.id} className="flex cursor-pointer items-center gap-3 px-3 py-2.5 text-sm hover:bg-slate-50"><input type="checkbox" checked={editor.staff.includes(e.id)} onChange={()=>toggle("staff",e.id)}/><span>{e.firstName} {e.lastName}</span><span className="ml-auto text-xs text-slate-400">{e.department}</span></label>)}</div></fieldset><fieldset><legend className="text-sm font-medium">Days</legend><div className="mt-2 grid grid-cols-7 gap-1.5">{days.map(d=><button type="button" key={dateKey(d)} onClick={()=>toggle("days",dateKey(d))} aria-pressed={editor.days.includes(dateKey(d))} className={`rounded-xl border py-2 text-center ${editor.days.includes(dateKey(d))?"border-blue-500 bg-blue-50 text-blue-700":"border-slate-200 text-slate-500"}`}><span className="block text-[11px]">{label(d,{weekday:"short"})}</span><span className="mt-1 block text-sm font-semibold">{label(d,{day:"numeric"})}</span></button>)}</div></fieldset></>}
    {editor.shift&&<label className="block text-xs text-slate-500">Shift date<input type="date" required value={editor.days[0]} onChange={event=>setEditor({...editor,days:[event.target.value]})} className={input}/></label>}
    <div><p className="text-sm font-medium">Hours</p><div className="mt-2 flex flex-wrap gap-1.5">{[{name:"Day",start:"09:00",end:"17:00"},{name:"Early",start:"07:00",end:"15:00"},{name:"Late",start:"14:00",end:"22:00"},{name:"Night",start:"22:00",end:"06:00"}].map(preset=><button key={preset.name} type="button" onClick={()=>{setStart(preset.start);setEnd(preset.end);}} className="rounded-lg bg-slate-100 px-3 py-1.5 text-xs text-slate-600 hover:bg-blue-50 hover:text-blue-700">{preset.name}</button>)}</div><div className="mt-3 grid grid-cols-3 gap-3"><label className="text-xs text-slate-500">Start<input type="time" name="startTime" required value={start} onChange={event=>setStart(event.target.value)} className={input}/></label><label className="text-xs text-slate-500">Finish<input type="time" name="endTime" required value={end} onChange={event=>setEnd(event.target.value)} className={input}/></label><label className="text-xs text-slate-500">Break (minutes)<input type="number" name="breakMinutes" min="0" max="1439" required value={breakMinutes} onChange={event=>setBreakMinutes(Number(event.target.value))} className={input}/></label></div>{end<=start&&<p className="mt-2 text-xs text-blue-600">Finishes the following day.</p>}</div>
    <details open={Boolean(editor.shift?.role||editor.shift?.location||editor.shift?.notes)} className="rounded-xl border border-slate-200 p-3"><summary className="cursor-pointer text-sm font-medium">Role, location &amp; instructions</summary><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-500">Role<input name="role" maxLength={100} defaultValue={editor.shift?.role??""} className={input}/></label><label className="text-xs text-slate-500">Location<input name="location" maxLength={100} defaultValue={editor.shift?.location??""} className={input}/></label><label className="text-xs text-slate-500 sm:col-span-2">Instructions<textarea name="instructions" rows={3} maxLength={3000} defaultValue={editor.shift?.notes??""} className={input}/></label>{!editor.shift&&<label className="text-xs text-slate-500 sm:col-span-2">Tasks · one per line<textarea name="tasks" rows={3} maxLength={6000} placeholder="Open reception&#10;Complete handover" className={input}/></label>}</div></details>
    {editor.shift?.tasks.length? <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-medium">Shift tasks</p>{editor.shift.tasks.map(task=><p key={task.id} className="mt-1.5 text-xs text-slate-500">{task.completedAt?"✓ ":"○ "}{task.title}</p>)}</div>:null}
    <label className="flex items-center gap-3 rounded-xl bg-blue-50 px-3 py-3 text-sm"><input type="checkbox" name="publish" defaultChecked={editor.shift?.status==="CONFIRMED"} disabled={editor.shift?.status==="CONFIRMED"}/>{editor.shift?.status==="CONFIRMED"?"Published — changes will appear for staff":"Publish to staff now"}</label>
    {error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-4"><div>{editor.shift&&<Button type="button" variant="ghost" disabled={pending} onClick={()=>{const form=new FormData();form.set("status","CANCELLED");run(()=>setScheduledShift(editor.shift!.id,form),"Shift cancelled.",true);}} className="text-red-600"><Trash2 size={15}/>Cancel shift</Button>}</div><Button variant="primary" type="submit" disabled={pending||(!editor.shift&&(!editor.staff.length||!editor.days.length))}>{pending?"Saving…":editor.shift?"Save shift":`Save ${editor.staff.length*editor.days.length||""} shift${editor.staff.length*editor.days.length===1?"":"s"}`}</Button></div>
   </fieldset></form>:<div className="space-y-5 p-6"><div className="rounded-2xl bg-blue-50 p-5"><p className="text-2xl font-semibold">{start} – {end}</p><p className="mt-2 text-sm text-slate-500">{editor.shift?.breakMinutes} minute break{editor.shift?.location?` · ${editor.shift.location}`:""}</p></div>{editor.shift?.notes&&<p className="whitespace-pre-wrap text-sm text-slate-600">{editor.shift.notes}</p>}{editor.shift?.tasks.map(task=><div key={task.id} className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 p-3"><p className={`text-sm ${task.completedAt?"text-slate-400 line-through":""}`}>{task.title}</p>{task.completedAt?<Check size={16} className="text-emerald-500"/>:<Button disabled={pending} onClick={()=>run(()=>completeShiftTask(task.id),"Task completed.",true)}><Check size={14}/>Done</Button>}</div>)}</div>}
   </div>}
  </dialog>
 </div>;
}
function dateOnlyClient(day:string){return new Date(day+"T00:00:00Z");}
