"use client";
import { PeopleWorkspaceHeader, WorkspaceStats } from "@/components/ui/people-workspace";
import { useEffect, useRef, useState, useTransition } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ChevronLeft, ChevronRight, Plus, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { fillTeamMonth, publishMonth, removeBusyRule, replanCover, saveBusyRule, saveDemand, saveShift, saveWorkType, setScheduledShift } from "@/app/(app)/scheduling/actions";
import type { getTeamPlan } from "@/app/(app)/scheduling/actions";
import { londonDate, londonTime } from "@/modules/scheduling/domain/time";
import { WORK_CATEGORIES, WORK_CATEGORY_LABEL, contractedMonthMinutes, dayCoverage, planCover, type WorkCategory } from "@/modules/scheduling/domain/planner";

type Data = Awaited<ReturnType<typeof getTeamPlan>>;
type Shift = Data["shifts"][number];
const field = "mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm";
const tone: Record<string, string> = { OFFICE: "border-blue-200 bg-blue-50 text-blue-950", PRODUCTION: "border-amber-200 bg-amber-50 text-amber-950", CONTACT: "border-emerald-200 bg-emerald-50 text-emerald-950", FIELD: "border-teal-200 bg-teal-50 text-teal-950", TRAINING: "border-violet-200 bg-violet-50 text-violet-950", ON_CALL: "border-slate-300 bg-slate-100 text-slate-800", OTHER: "border-slate-200 bg-white text-slate-700" };
const dayText = (day: string) => new Date(`${day}T00:00:00Z`).toLocaleDateString("en-GB", { timeZone: "UTC", weekday: "short", day: "numeric" });
const shiftDay = (shift: Shift) => londonDate(shift.startsAt);
const shiftMinutes = (shift: Shift) => Math.max(0, Math.round((shift.endsAt.getTime() - shift.startsAt.getTime()) / 60000) - shift.breakMinutes);
const hours = (minutes: number) => `${(minutes / 60).toFixed(1)}h`;

export function TeamPlanner({ data, query }: { data: Data; query: { month?: string; team?: string; q?: string; department?: string; view?: string } }) {
  const router = useRouter();
  const dialog = useRef<HTMLDialogElement>(null);
  const [pending, start] = useTransition();
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const [editor, setEditor] = useState<{ employeeId: string; day: string; shift?: Shift } | null>(null);
  const [pattern, setPattern] = useState(data.workTypes[0]?.id ?? "");
  const [selected, setSelected] = useState(data.employees.map((employee) => employee.id));
  const [demandMode, setDemandMode] = useState<"traffic" | "hours">("traffic");
  useEffect(() => { if (editor && !dialog.current?.open) dialog.current?.showModal(); if (!editor && dialog.current?.open) dialog.current?.close(); }, [editor]);

  const href = (month: string, own = query.view === "mine") => {
    const params = new URLSearchParams({ month });
    if (query.team) params.set("team", query.team);
    if (query.q) params.set("q", query.q);
    if (query.department) params.set("department", query.department);
    if (own) params.set("view", "mine");
    return `/scheduling?${params}`;
  };
  const moveMonth = (delta: number) => {
    const [year, month] = data.month.split("-").map(Number);
    return new Date(Date.UTC(year, month - 1 + delta, 1)).toISOString().slice(0, 7);
  };
  const covers = (employeeId: string, day: string, status: string) => data.absences.some((absence) => absence.employeeId === employeeId && absence.status === status && absence.startDate.toISOString().slice(0, 10) <= day && absence.endDate.toISOString().slice(0, 10) >= day);
  const demands = data.demands.map((row) => ({ day: row.demandDate.toISOString().slice(0, 10), teamId: row.teamId, department: row.department, workTypeId: row.workTypeId, requiredMinutes: row.requiredMinutes, forecastVolume: row.forecastVolume, minutesPerUnit: row.minutesPerUnit, shrinkagePercent: row.shrinkagePercent }));
  const planned = data.shifts.map((shift) => ({ employeeId: shift.employeeId, day: shiftDay(shift), minutes: shiftMinutes(shift) }));
  const coverage = data.days.map((day) => dayCoverage(day, demands, planned, new Set(data.employees.filter((employee) => covers(employee.id, day, "APPROVED")).map((employee) => employee.id)), { teamId: query.team, department: query.department }));
  const moves = data.manage ? planCover(
    data.shifts.filter((shift) => covers(shift.employeeId, shiftDay(shift), "APPROVED")).map((shift) => ({ shiftId: shift.id, day: shiftDay(shift), minutes: shiftMinutes(shift), teamId: shift.teamId, department: data.employees.find((employee) => employee.id === shift.employeeId)?.department ?? null })),
    data.employees.map((employee) => ({ id: employee.id, teamIds: employee.teamIds, department: employee.department, remainingMinutes: contractedMonthMinutes(employee.contractedWeeklyHours ?? data.standardHours, employee.workingDays, data.days), absentDays: data.days.filter((day) => covers(employee.id, day, "APPROVED")), busyDays: [...data.shifts.filter((shift) => shift.employeeId === employee.id).map(shiftDay)] })),
  ) : [];
  const groups = groupPeople(data, query.team);
  const chosen = data.workTypes.find((item) => item.id === pattern) ?? data.workTypes[0];
  const monthLabel = new Date(`${data.month}-01T00:00:00Z`).toLocaleDateString("en-GB", { month: "long", year: "numeric", timeZone: "UTC" });
  const draftCount = data.shifts.filter((shift) => shift.status === "SCHEDULED").length;

  function run(action: () => Promise<unknown>, success: string) {
    setError(""); setNotice("");
    start(async () => {
      try { const result = await action(); setEditor(null); const placed = result && typeof result === "object" && "saved" in result ? result as { saved: unknown; leave?: number; overlap?: number } : null; setNotice(typeof result === "number" ? success.replace("{n}", String(result)) : placed ? `Placed ${placed.saved} shifts${placed.leave ? `, skipped ${placed.leave} days of leave` : ""}${placed.overlap ? `, ${placed.overlap} already planned` : ""}.` : success); router.refresh(); }
      catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save. Try again."); }
    });
  }

  return <div className="space-y-5">
    <PeopleWorkspaceHeader eyebrow="Workforce scheduling" title={data.manage ? "People planner" : "Your month"} description={data.manage ? "Build a flexible rota across departments, teams and work patterns. Match hours to demand, resolve cover and publish a clear plan to each person." : "Your published shifts, work pattern and upcoming time off."} actions={<>{data.manage&&<Link href={`/scheduling/workforce${query.department?`?department=${encodeURIComponent(query.department)}`:""}`} className="rounded-xl border border-blue-200 bg-white px-4 py-2 text-sm font-semibold text-blue-700">Coverage & open shifts →</Link>}<Link href="/scheduling/workforce" className="rounded-xl border border-blue-200 bg-white px-4 py-2 text-sm font-semibold text-blue-700">Availability</Link></>}/>
    <WorkspaceStats items={[{label:"People in view",value:data.total,detail:`${data.employees.length} shown in the rota`},{label:"Planned paid hours",value:hours(data.shifts.reduce((n,s)=>n+shiftMinutes(s),0))},{label:"Draft shifts",value:draftCount,detail:"Publish when the team plan is ready."},{label:"Days short of demand",value:coverage.filter(c=>(c.short??0)>0).length,tone:"warning"}]}/>
    {data.manage&&<div className="flex flex-wrap justify-end gap-2"><Button disabled={pending || !draftCount} onClick={() => { const form = new FormData(); form.set("month", data.month); for (const id of selected) form.append("employeeId", id); run(() => publishMonth(form), "This month is published on their profiles."); }}>Publish {draftCount || ""} drafts</Button><Button variant="primary" disabled={pending || !chosen || !selected.length} onClick={() => { const form = new FormData(); form.set("month", data.month); form.set("workTypeId", chosen.id); if (query.team) form.set("teamId", query.team); for (const id of selected) form.append("employeeId", id); run(() => fillTeamMonth(form), ""); }}>Fill draft month with {chosen?.name ?? "a pattern"}</Button></div>}
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white p-3">
      <div className="flex items-center gap-2">
        <Link aria-label="Previous month" href={href(moveMonth(-1))} className="rounded-lg border p-2 hover:bg-slate-50"><ChevronLeft size={17} /></Link>
        <span className="min-w-36 text-center text-sm font-semibold">{monthLabel}</span>
        <Link aria-label="Next month" href={href(moveMonth(1))} className="rounded-lg border p-2 hover:bg-slate-50"><ChevronRight size={17} /></Link>
        <Link href={href(new Date().toISOString().slice(0, 7))} className="rounded-lg px-2 py-2 text-xs text-blue-600">This month</Link>
      </div>
      <div className="flex gap-2 text-xs">{data.manage && <Link href={href(data.month, true)} className="rounded-lg px-3 py-2 text-slate-600 hover:bg-slate-50">My month</Link>}<Link href="/people/me" className="rounded-lg px-3 py-2 text-slate-600">Time off</Link><Link href="/profile" className="rounded-lg px-3 py-2 text-slate-600">Profiles</Link></div>
    </div>
    {data.manage && <form className="flex flex-wrap items-end gap-2"><input type="hidden" name="month" value={data.month} /><label className="min-w-40 flex-1 text-xs text-slate-500">Find a person<input name="q" defaultValue={query.q ?? ""} className={field} /></label><label className="text-xs text-slate-500">Team<select name="team" defaultValue={query.team ?? ""} className={field}><option value="">All teams</option>{data.teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label className="text-xs text-slate-500">Department<select name="department" defaultValue={query.department ?? ""} className={field}><option value="">All departments</option>{data.departments.map((department) => <option key={department}>{department}</option>)}</select></label><Button type="submit">Show</Button></form>}
    {notice && <p role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}
    {error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    {!!moves.length && <section className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><h3 className="text-sm font-semibold">Cover needed</h3><p className="mt-1 text-xs text-amber-900">Approved sickness or holiday overlaps a planned shift. The suggestion uses a teammate who is in, has no other shift that day, and has the most contracted time left.</p><ul className="mt-3 space-y-1 text-sm">{moves.map((move) => { const shift = data.shifts.find((item) => item.id === move.shiftId); const from = data.employees.find((employee) => employee.id === shift?.employeeId); const to = data.employees.find((employee) => employee.id === move.employeeId); return <li key={move.shiftId}>{from?.firstName} {from?.lastName} · {shift ? dayText(shiftDay(shift)) : ""} {shift?.workType?.name ?? "shift"} → {to?.firstName} {to?.lastName}</li>; })}</ul><Button className="mt-3" variant="primary" disabled={pending} onClick={() => run(() => replanCover(moves), "{n} shifts moved onto the people who can cover.")}>Replan {moves.length} gaps</Button></section>}
    <section aria-label="Month coverage" className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full border-collapse text-xs"><thead><tr>{data.days.map((day) => <th key={day} className="min-w-12 px-1 py-2 text-center font-medium text-slate-500">{dayText(day)}</th>)}</tr></thead><tbody><tr>{coverage.map((row, index) => <td key={data.days[index]} className={`px-1 py-2 text-center ${row.short ? "bg-amber-50 text-amber-900" : "text-slate-600"}`}><div>{row.required == null ? "—" : hours(row.required)}</div><div className="text-[10px] text-slate-400">{row.planned ? hours(row.planned) : ""}</div>{row.volume > 0 && <div className="text-[10px]">{row.volume}</div>}</td>)}</tr></tbody></table></div><p className="border-t border-slate-100 px-4 py-2 text-[11px] text-slate-500">Top number is man-hours required from traffic or a direct target. The number under it is hours still covered after sickness and holiday. Amber means the day is short. A third number is forecast volume.</p></section>
    {!!data.traffic.length && <p className="text-xs text-slate-500">Live context this month: {data.traffic.reduce((sum, row) => sum + row.salesOrders, 0)} sales orders with a requested delivery date{data.traffic.some((row) => row.productionUnits) ? `, and ${data.traffic.reduce((sum, row) => sum + row.productionUnits, 0).toFixed(0)} forecast production units` : ""}. Use that as traffic, or type the department’s own volume.</p>}
    {!!data.rules.length && <ul className="flex flex-wrap gap-2">{data.rules.map((rule) => <li key={rule.id} className="flex items-center gap-2 rounded-full bg-slate-100 px-3 py-1 text-xs">{rule.name}: {rule.blockHolidays ? "holiday closed" : `max ${rule.maxOffPerDay} off`} · {rule.startsOn.toISOString().slice(0, 10)} to {rule.endsOn.toISOString().slice(0, 10)}{data.manage && <button type="button" className="text-slate-400" aria-label={`Remove ${rule.name}`} disabled={pending} onClick={() => run(() => removeBusyRule(rule.id), "Busy period removed.")}>×</button>}</li>)}</ul>}
    {data.manage && <div className="grid gap-3 lg:grid-cols-3">
      <details className="rounded-2xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer text-sm font-semibold">Work patterns</summary><ul className="mt-3 space-y-1 text-xs text-slate-600">{data.workTypes.map((item) => <li key={item.id} className="flex items-center justify-between gap-2"><button type="button" className={pattern === item.id ? "font-semibold text-blue-700" : ""} onClick={() => setPattern(item.id)}>{item.name}</button><span>{WORK_CATEGORY_LABEL[item.category]} · {item.startTime}–{item.endTime}</span></li>)}</ul><PatternForm teams={data.teams} pending={pending} onSave={(form) => run(() => saveWorkType(form), "Work pattern saved.")} /></details>
      <details className="rounded-2xl border border-slate-200 bg-white p-4" open><summary className="cursor-pointer text-sm font-semibold">Traffic and man-hours</summary><p className="mt-2 text-xs text-slate-500">A contact centre can enter calls and minutes each. Production or office can enter the man-hours the day needs. Shrinkage adds the extra hours for breaks, absence and training.</p><form action={(form) => run(() => saveDemand(form), "Demand saved for {n} days.")} className="mt-3 space-y-2"><input type="hidden" name="month" value={data.month} /><div className="flex gap-3 text-xs"><label><input type="radio" name="mode" value="traffic" checked={demandMode === "traffic"} onChange={() => setDemandMode("traffic")} /> Traffic</label><label><input type="radio" name="mode" value="hours" checked={demandMode === "hours"} onChange={() => setDemandMode("hours")} /> Man-hours</label></div>{demandMode === "traffic" ? <div className="grid grid-cols-2 gap-2"><label className="text-xs">Volume<input name="forecastVolume" type="number" min="0" required className={field} /></label><label className="text-xs">Each takes (min)<input name="minutesPerUnit" type="number" min="1" max="1440" required className={field} /></label><label className="text-xs">Unit<input name="volumeUnit" defaultValue="calls" className={field} /></label><label className="text-xs">Shrinkage %<input name="shrinkagePercent" type="number" min="0" max="80" defaultValue={chosen?.category === "CONTACT" ? 30 : 0} className={field} /></label></div> : <label className="text-xs">Man-hours<input name="hours" type="number" min="0" step="0.25" required className={field} /></label>}<label className="text-xs">Label<input name="label" placeholder="Inbound calls" className={field} /></label><label className="text-xs">Team<select name="teamId" defaultValue={query.team ?? ""} className={field}><option value="">Any team</option>{data.teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label className="text-xs">Department<select name="department" defaultValue={query.department ?? ""} className={field}><option value="">Any department</option>{data.departments.map((department) => <option key={department}>{department}</option>)}</select></label><label className="text-xs">Work pattern<select name="workTypeId" defaultValue="" className={field}><option value="">Any pattern</option>{data.workTypes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-xs">Day, if not the whole month<input type="date" name="day" defaultValue={data.days.find((day) => day >= new Date().toISOString().slice(0, 10)) ?? data.days[0]} className={field} /></label><label className="flex items-center gap-2 text-xs"><input type="checkbox" name="span" value="month" defaultChecked /> Every weekday this month</label><Button type="submit" disabled={pending}>Save demand</Button></form></details>
      <details className="rounded-2xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer text-sm font-semibold">Busy months</summary><p className="mt-2 text-xs text-slate-500">Peak months can cap how many people are off, or close holiday requests. Sickness is still recorded and then replanned.</p><form action={(form) => run(() => saveBusyRule(form), "Busy period saved. New holiday requests follow it.")} className="mt-3 space-y-2"><label className="text-xs">Name<input name="name" required placeholder="Christmas peak" className={field} /></label><div className="grid grid-cols-2 gap-2"><label className="text-xs">From<input type="date" name="startsOn" required defaultValue={`${data.month}-01`} className={field} /></label><label className="text-xs">To<input type="date" name="endsOn" required className={field} /></label></div><label className="text-xs">Max people off per day<input name="maxOffPerDay" type="number" min="0" className={field} /></label><label className="flex items-center gap-2 text-xs"><input type="checkbox" name="blockHolidays" /> Close holiday requests</label><label className="text-xs">Team<select name="teamId" defaultValue={query.team ?? ""} className={field}><option value="">Whole company</option>{data.teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label className="text-xs">Department<select name="department" defaultValue="" className={field}><option value="">Any department</option>{data.departments.map((department) => <option key={department}>{department}</option>)}</select></label><Button type="submit" disabled={pending}>Save busy period</Button></form></details>
    </div>}
    <section aria-label="Team month plan" className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full border-collapse text-xs"><thead><tr><th className="sticky left-0 z-10 bg-slate-50 p-3 text-left">Team</th>{data.days.map((day) => <th key={day} className="min-w-11 px-1 py-2 font-medium text-slate-500">{day.slice(8)}</th>)}</tr></thead><tbody>{groups.map((group) => group.people.map((employee, index) => {
      const plannedMinutes = data.shifts.filter((shift) => shift.employeeId === employee.id).reduce((sum, shift) => sum + shiftMinutes(shift), 0);
      const contracted = contractedMonthMinutes(employee.contractedWeeklyHours ?? data.standardHours, employee.workingDays, data.days);
      return <tr key={`${group.id}-${employee.id}`} className="border-t border-slate-100 align-top"><th className="sticky left-0 z-10 bg-white p-3 text-left font-medium"><span className="block text-[10px] font-normal text-slate-400">{index === 0 ? group.name : ""}</span>{employee.firstName} {employee.lastName}<span className={`mt-1 block font-normal ${plannedMinutes > contracted ? "text-amber-700" : "text-slate-400"}`}>{hours(plannedMinutes)} / {hours(contracted)}</span>{data.manage && <label className="mt-1 flex items-center gap-1 font-normal text-slate-400"><input type="checkbox" checked={selected.includes(employee.id)} onChange={() => setSelected((current) => current.includes(employee.id) ? current.filter((id) => id !== employee.id) : [...current, employee.id])} />Include</label>}</th>{data.days.map((day) => {
        const daily = data.shifts.filter((shift) => shift.employeeId === employee.id && shiftDay(shift) === day);
        const off = covers(employee.id, day, "APPROVED");
        const asked = covers(employee.id, day, "PENDING");
        return <td key={day} className="border-l border-slate-50 p-1">{off && <div className="mb-1 rounded bg-amber-100 px-1 py-1 text-center text-[10px] text-amber-800">{data.absences.find((absence) => absence.employeeId === employee.id && absence.status === "APPROVED" && absence.startDate.toISOString().slice(0, 10) <= day && absence.endDate.toISOString().slice(0, 10) >= day)?.type === "SICKNESS" ? "Sick" : "Off"}</div>}{asked && !off && <div className="mb-1 rounded bg-slate-100 px-1 py-1 text-center text-[10px] text-slate-500">Asked</div>}{daily.map((shift) => <button key={shift.id} type="button" disabled={pending} onClick={() => data.manage && setEditor({ employeeId: employee.id, day, shift })} className={`mb-1 block w-full rounded border px-1 py-1 text-left text-[10px] ${tone[shift.workType?.category ?? "OTHER"] ?? tone.OTHER} ${shift.status === "SCHEDULED" ? "border-dashed" : ""}`}>{shift.workType?.name ?? londonTime(shift.startsAt)}<span className="block text-[9px] opacity-70">{hours(shiftMinutes(shift))}</span></button>)}{data.manage && !daily.length && !off && <button type="button" aria-label={`Plan ${employee.firstName} ${employee.lastName} on ${day}`} className="flex h-7 w-full items-center justify-center text-slate-300 hover:text-blue-500" onClick={() => setEditor({ employeeId: employee.id, day })}><Plus size={12} /></button>}</td>;
      })}</tr>;
    }))}</tbody></table></div>{!data.employees.length && <p className="px-6 py-10 text-center text-sm text-slate-500">No one is in this team view. Link people to a team, or clear the filter.</p>}<p className="border-t border-slate-100 px-4 py-2 text-[11px] text-slate-400">{data.total > data.employees.length ? `Showing ${data.employees.length} of ${data.total}. Filter by team.` : `${data.employees.length} people`} · Drafts stay with the planner until you publish them onto profiles.</p></section>
    {data.manage && !!chosen && <p className="text-xs text-slate-500">Fill uses {chosen.name} ({chosen.startTime}–{chosen.endTime}, {WORK_CATEGORY_LABEL[chosen.category]}) on its working days, for the ticked people, and publishes it so it shows on their profiles. Days they are already off are skipped.</p>}
    <dialog ref={dialog} aria-label="Shift" className="m-auto w-[min(480px,calc(100vw-32px))] rounded-3xl border-0 p-0 shadow-2xl backdrop:bg-slate-900/30" onCancel={(event) => { event.preventDefault(); if (!pending) setEditor(null); }}>
      {editor && <form action={(form) => run(() => saveShift(form), "Shift saved.")} className="space-y-4 p-6"><header className="flex items-start justify-between"><div><h3 className="text-lg font-semibold">{editor.shift ? "Edit this day" : "Plan this day"}</h3><p className="mt-1 text-xs text-slate-500">{data.employees.find((employee) => employee.id === editor.employeeId)?.firstName} · {dayText(editor.day)}</p></div><button type="button" aria-label="Close" onClick={() => setEditor(null)}><X size={18} /></button></header><input type="hidden" name="day" value={editor.day} />{editor.shift && <input type="hidden" name="id" value={editor.shift.id} />}{!editor.shift && <input type="hidden" name="employeeId" value={editor.employeeId} />}<label className="block text-xs">Work pattern<select name="workTypeId" defaultValue={editor.shift?.workTypeId ?? chosen?.id ?? ""} className={field} onChange={(event) => { const next = data.workTypes.find((item) => item.id === event.target.value); const start = event.target.form?.elements.namedItem("startTime"); const end = event.target.form?.elements.namedItem("endTime"); if (next && start instanceof HTMLInputElement && end instanceof HTMLInputElement) { start.value = next.startTime; end.value = next.endTime; } }}><option value="">Custom hours</option>{data.workTypes.map((item) => <option key={item.id} value={item.id}>{item.name} · {WORK_CATEGORY_LABEL[item.category]}</option>)}</select></label><label className="block text-xs">Team<select name="teamId" defaultValue={editor.shift?.teamId ?? query.team ?? ""} className={field}><option value="">No team</option>{data.teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label><div className="grid grid-cols-2 gap-2"><label className="text-xs">Start<input type="time" name="startTime" required defaultValue={editor.shift ? londonTime(editor.shift.startsAt) : chosen?.startTime ?? "09:00"} className={field} /></label><label className="text-xs">Finish<input type="time" name="endTime" required defaultValue={editor.shift ? londonTime(editor.shift.endsAt) : chosen?.endTime ?? "17:30"} className={field} /></label></div><label className="block text-xs">Unpaid break (minutes)<input type="number" name="breakMinutes" min="0" required defaultValue={editor.shift?.breakMinutes ?? chosen?.breakMinutes ?? 30} className={field} /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="publish" defaultChecked={editor.shift?.status !== "SCHEDULED"} /> Show on their profile</label>{error && <p className="text-sm text-red-700">{error}</p>}<div className="flex justify-between">{editor.shift && <Button type="button" disabled={pending} onClick={() => { const form = new FormData(); form.set("status", "CANCELLED"); run(() => setScheduledShift(editor.shift!.id, form), "Shift removed."); }}>Remove</Button>}<Button type="submit" variant="primary" disabled={pending}>Save</Button></div></form>}
    </dialog>
  </div>;
}

function PatternForm({ teams, pending, onSave }: { teams: Data["teams"]; pending: boolean; onSave: (form: FormData) => void }) {
  return <form action={onSave} className="mt-3 space-y-2 border-t border-slate-100 pt-3"><label className="text-xs">New pattern<input name="name" required placeholder="Weekend contact" className={field} /></label><label className="text-xs">Type of work<select name="category" className={field}>{WORK_CATEGORIES.map((category) => <option key={category} value={category}>{WORK_CATEGORY_LABEL[category as WorkCategory]}</option>)}</select></label><div className="grid grid-cols-3 gap-2"><label className="text-xs">Start<input type="time" name="startTime" required defaultValue="09:00" className={field} /></label><label className="text-xs">Finish<input type="time" name="endTime" required defaultValue="17:00" className={field} /></label><label className="text-xs">Break<input type="number" name="breakMinutes" min="0" defaultValue={30} className={field} /></label></div><fieldset className="flex flex-wrap gap-2 text-[11px]">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((label, index) => <label key={label}><input type="checkbox" name="weekdays" value={index} defaultChecked={index > 0 && index < 6} /> {label}</label>)}</fieldset><label className="text-xs">Limit to a team<select name="teamId" className={field}><option value="">Any team</option>{teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label><div className="flex gap-2"><Button type="submit" disabled={pending}>Add pattern</Button></div></form>;
}

function groupPeople(data: Data, teamId?: string) {
  if (teamId) {
    const team = data.teams.find((item) => item.id === teamId);
    return [{ id: teamId, name: team?.name ?? "Team", people: data.employees.filter((employee) => employee.teamIds.includes(teamId)) }];
  }
  const used = new Set<string>();
  const groups = data.teams.map((team) => {
    const people = data.employees.filter((employee) => employee.teamIds[0] === team.id && !used.has(employee.id));
    people.forEach((employee) => used.add(employee.id));
    return { id: team.id, name: team.name, people };
  }).filter((group) => group.people.length);
  const rest = data.employees.filter((employee) => !used.has(employee.id));
  const departments = [...new Set(rest.map((employee) => employee.department || "No team"))];
  for (const department of departments) groups.push({ id: department, name: department, people: rest.filter((employee) => (employee.department || "No team") === department) });
  return groups.length ? groups : [{ id: "all", name: "Team", people: data.employees }];
}
