import Link from "next/link";
import { requireSession } from "@/core/auth/session";
import { assertCapability, can } from "@/core/permissions/check";
import { assertModuleEnabled } from "@/core/modules/access";
import { db } from "@/core/db/client";
import { ActionForm } from "@/components/ui/action-form";
import { Button } from "@/components/ui/button";
import { blockGroups, EXPORT_REQUIRED } from "@/modules/sales/domain/invoice-templates";
import { retireInvoiceTemplate, saveInvoiceTemplate } from "@/modules/sales/services/invoice-template-actions";

const input = "mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm";

export default async function InvoiceTemplatesPage() {
  const session = await requireSession();
  assertCapability(session, "sales.order.read");
  await assertModuleEnabled(session, "sales");
  const manage = can(session, "sales.quote.create");
  const templates = await db.invoiceDocumentTemplate.findMany({ where: { organisationId: session.organisationId, active: true }, include: { assignments: { select: { id: true } } }, orderBy: { name: "asc" } });
  return <div className="mx-auto max-w-5xl space-y-6">
    <div><Link href="/sales/orders" className="text-xs text-slate-500">Sales</Link><h2 className="mt-2 text-2xl font-semibold tracking-tight">Template menu</h2><p className="mt-2 max-w-2xl text-sm text-slate-500">These templates say what goes on a customer’s invoice. Attach one to the customer account, including the address. An export template also asks for the weight, volume and customs details, and the sale raises a proforma. The proforma is not a tax invoice.</p></div>
    {manage && <div className="flex flex-wrap gap-3">{(["DOMESTIC", "EXPORT"] as const).map((kind) => <ActionForm key={kind} action={saveInvoiceTemplate}><input type="hidden" name="preset" value="yes" /><input type="hidden" name="kind" value={kind} /><Button type="submit">{kind === "EXPORT" ? "Add export proforma" : "Add domestic invoice"}</Button></ActionForm>)}</div>}
    <div className="grid gap-4">{templates.map((template) => <article key={template.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-blue-600">{template.kind === "EXPORT" ? "Export proforma" : "Domestic invoice"}</p><h3 className="mt-1 text-lg font-semibold">{template.name}</h3><p className="mt-2 text-xs text-slate-500">On {template.assignments.length} customer {template.assignments.length === 1 ? "account" : "accounts"}{template.exporterEori ? ` · Exporter EORI ${template.exporterEori}` : ""}</p></div>{manage && <ActionForm action={retireInvoiceTemplate}><input type="hidden" name="id" value={template.id} /><Button type="submit" variant="ghost">Retire</Button></ActionForm>}</div><ul className="mt-4 flex flex-wrap gap-2">{template.blocks.map((block) => <li key={block} className="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-600">{blockGroups().flatMap((group) => group.blocks).find((item) => item.key === block)?.label ?? block}</li>)}</ul>{template.footer && <p className="mt-4 text-sm text-slate-500">{template.footer}</p>}{manage && <ActionForm action={saveInvoiceTemplate} className="mt-4 grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-2"><input type="hidden" name="id" value={template.id} /><input type="hidden" name="kind" value={template.kind} />{template.blocks.map((block) => <input key={block} type="hidden" name="blocks" value={block} />)}<label className="text-xs text-slate-500">Name<input name="name" required defaultValue={template.name} className={input} /></label>{template.kind === "EXPORT" && <label className="text-xs text-slate-500">Exporter EORI<input name="exporterEori" defaultValue={template.exporterEori ?? ""} className={input} /></label>}<label className="text-xs text-slate-500 sm:col-span-2">Note on the document<textarea name="footer" defaultValue={template.footer ?? ""} className={`${input} min-h-16`} /></label><Button type="submit">Save template</Button></ActionForm>}</article>)}{!templates.length && <p className="rounded-2xl border border-dashed border-slate-200 p-6 text-sm text-slate-500">No invoice templates yet. Add a domestic invoice, or an export proforma for weight, volume, commodity codes and Incoterms.</p>}</div>
    {manage && <ActionForm action={saveInvoiceTemplate} className="space-y-5 rounded-2xl border border-slate-200 bg-white p-6"><h3 className="font-semibold">New template</h3><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs text-slate-500">Name<input name="name" required maxLength={80} className={input} /></label><label className="text-xs text-slate-500">Use<select name="kind" className={input} defaultValue="DOMESTIC"><option value="DOMESTIC">Domestic invoice</option><option value="EXPORT">Export proforma</option></select></label><label className="text-xs text-slate-500">Exporter EORI<input name="exporterEori" placeholder="Used when this template is an export" className={input} /></label><label className="text-xs text-slate-500 sm:col-span-2">Note printed on the document<textarea name="footer" maxLength={500} className={`${input} min-h-20`} /></label></div><div className="grid gap-6 sm:grid-cols-3">{blockGroups().map((group) => <fieldset key={group.group}><legend className="text-sm font-medium">{group.group}</legend><div className="mt-3 space-y-2">{group.blocks.map((block) => <label key={block.key} className="flex items-start gap-2 text-sm text-slate-600"><input type="checkbox" name="blocks" value={block.key} defaultChecked={group.group !== "Export"} />{block.label}{EXPORT_REQUIRED.includes(block.key) ? <span className="text-[10px] text-slate-400">Required on export</span> : null}</label>)}</div></fieldset>)}</div><Button type="submit" variant="primary">Save template</Button></ActionForm>}
  </div>;
}
