import Link from 'next/link';
import {ActionForm} from '@/components/ui/action-form';
import {generateSopForecast,updateSopWorkflow,approveSopVersion,publishSopVersion,type getSopWorkspace} from '../services/workspace';
import {cycleGuidance,reviewStages,REVIEW_GUIDES,monthlyBrief} from '../domain/guidance';
import {MonthlyBrief} from './monthly-brief';
type Workspace=Awaited<ReturnType<typeof getSopWorkspace>>;
const quiet='inline-flex rounded-full border border-[var(--color-border)] bg-white px-4 py-2 text-sm font-medium';
const primary='inline-flex rounded-full bg-[var(--color-atlas-blue)] px-4 py-2 text-sm font-semibold text-white';
const panel='rounded-2xl border border-[var(--color-border)] bg-white p-5';
export function SopGuideHome({data}:{data:Workspace}){
 const {cycle,version}=data,can=(c:string)=>data.capabilities.includes(c),payload=version?.payload,base=cycle?`/sop?cycle=${cycle.id}${version?`&version=${version.id}`:''}`:'/sop?';
 const state=cycle?cycleGuidance(version,cycle.inputRevision,cycle.workflow,payload?.rows.length??0,!!data.inaccessibleVersions):null;
 return <section aria-label="S&OP next steps" className="space-y-6">
  <div className={`${panel} border-blue-200 bg-blue-50/40`}><p className="text-xs font-semibold uppercase tracking-wide text-blue-700">Start here</p><h2 className="mt-2 text-2xl font-semibold">{state?.title??'One agreed plan for what to sell and how to deliver it'}</h2><p className="mt-3 max-w-3xl text-sm leading-relaxed text-[var(--color-ink-muted)]">{state?.detail??'Sales & Operations Planning brings Sales, Operations and Finance together. Agree expected demand, check what you can supply, decide how to close the gaps, then release the approved plan.'}</p><div className="mt-4 flex flex-wrap gap-3">{state?<Link className={primary} href={`${base}&view=${state.view}`}>{state.view==='setup'?'Open setup':state.view==='reviews'?'Open review checklist':state.view==='scenarios'?'Compare scenarios':'Open Orders & Service'} →</Link>:can('sop.manage')?<a className={primary} href="#new-cycle">Create your first cycle →</a>:<p className="text-sm">Ask your planning lead to create a cycle and share it with you.</p>}<Link className={quiet} href={cycle?`${base}&view=help`:'/sop?view=help'}>How to use S&OP</Link></div></div>
  <ol aria-label="S&OP working process" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
   ['1','Prepare','Choose months, products and sales inputs.','setup'],['2','Review','Agree demand, supply cover and financial impact.','reviews'],['3','Decide','Compare options and give each action an owner.','decisions'],['4','Approve & release','Commit to one version, then send demand to Manufacturing.','reviews'],
  ].map(([n,title,detail,view])=><li key={n} className={panel}><p className="text-xs font-semibold text-blue-700">{n}</p><h3 className="mt-2 font-semibold">{title}</h3><p className="mt-2 text-xs leading-relaxed text-[var(--color-ink-muted)]">{detail}</p>{cycle&&<Link className="mt-3 inline-block text-xs text-blue-700" href={`${base}&view=${view}`}>Open {title.toLowerCase()} →</Link>}</li>)}</ol>
  {cycle&&<div className="grid gap-4 md:grid-cols-3"><div className={panel}><h3 className="text-sm font-semibold">Connected inputs</h3><p className="mt-2 text-2xl font-semibold">{cycle.sourcePlanIds.length} plans</p><p className="mt-2 text-xs text-[var(--color-ink-muted)]">Confirmed Sales orders and accessible source apps are read when generating. Connect plans for additional assumptions.</p><Link href={`${base}&view=setup`} className="mt-3 inline-block text-xs text-blue-700">Check inputs →</Link></div><div className={panel}><h3 className="text-sm font-semibold">Review progress</h3><p className="mt-2 text-2xl font-semibold">{state?.key==='published'?'Released':`${state?.approved??0} / 7`}</p><p className="mt-2 text-xs text-[var(--color-ink-muted)]">{state?.key==='published'?'This historical version has been released. Current review records may belong to a newer forecast.':'Reviews apply to the exact selected working forecast. Opening a page does not approve it.'}</p></div><div className={panel}><h3 className="text-sm font-semibold">Follow-up actions</h3><p className="mt-2 text-2xl font-semibold">{Array.isArray(cycle.actions)?cycle.actions.filter(a=>a&&typeof a==='object'&&'status' in a&&a.status!=='completed').length:0} open</p><Link href={`${base}&view=decisions`} className="mt-3 inline-block text-xs text-blue-700">Open decisions & actions →</Link></div></div>}
  {payload&&<MonthlyBrief months={monthlyBrief(payload.rows,payload.targets??[],payload.settings.targetPlanId,payload.currency)} currency={payload.currency} base={base}/>}
 </section>;
}
export function SopGenerate({data}:{data:Workspace}){
 const {cycle}=data;if(!cycle)return null;
 const required=[['sop.manage','Planning management'],['plan.read','Plan inputs'],['sales.order.read','Sales orders'],['customers.read','Customers'],['core.products.read','Products']];
 const signal=(cycle.settings as {signal?:string}|null)?.signal;if(['shipments','deliveries'].includes(signal??''))required.push(['logistics.shipment.read','Logistics delivery evidence']);
 const missing=required.filter(([cap])=>!data.capabilities.includes(cap));
 if(missing.length)return <p className="text-sm text-[var(--color-ink-muted)]">To generate a forecast, your planning lead needs access to {missing.map(([,label])=>label).join(', ')}.</p>;
 return <ActionForm action={generateSopForecast} className="space-y-3"><input type="hidden" name="cycleId" value={cycle.id}/><input type="hidden" name="revision" value={cycle.revision}/><p className="text-sm text-[var(--color-ink-muted)]">Reads current inputs and creates a saved working forecast. Existing versions remain intact; the seven reviews start again for the new version.</p><button className={primary}>Generate working forecast</button></ActionForm>;
}
export function SopReviews({data}:{data:Workspace}){
 const {cycle,version}=data;if(!cycle)return null;const state=cycleGuidance(version,cycle.inputRevision,cycle.workflow,version?.payload.rows.length??0),stages=reviewStages(cycle.workflow),base=`/sop?cycle=${cycle.id}${version?`&version=${version.id}`:''}`,can=(c:string)=>data.capabilities.includes(c);
 return <section aria-label="Planning review checklist" className="space-y-5"><div><h2 className="text-2xl font-semibold">Review the plan together</h2><p className="mt-2 max-w-3xl text-sm text-[var(--color-ink-muted)]">Inspect the evidence with each department, agree the outcome and record its review. Approval is a separate decision. All seven reviews must refer to this exact working forecast.</p><p role="status" className="mt-3 text-sm font-medium">{state.title} · {state.approved} of 7 recorded</p></div>
  {REVIEW_GUIDES.map((guide,index)=>{const stage=stages[index],current=stage?.title===guide.title&&stage.versionId===version?.id,recorded=current&&stage.status==='approved',editable=can('sop.approve')&&version?.kind==='consensus'&&version.status!=='published'&&version.sourceRevision===cycle.inputRevision&&current;return <article key={guide.title} id={`review-${index}`} className={panel}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-[var(--color-ink-muted)]">Review {index+1} · {recorded?'Recorded for this version':current?'Awaiting review':'No review linked to this version'}</p><h3 className="mt-1 text-lg font-semibold">{guide.title}</h3><p className="mt-2 text-sm font-medium">{guide.question}</p></div><Link href={`${base}&view=${guide.view}`} className={quiet}>Open evidence →</Link></div><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-[var(--color-ink-muted)]">{guide.checks.map(check=><li key={check}>{check}</li>)}</ul><p className="mt-4 text-xs">Owner: {stage?.owner||'Not assigned'} · Due: {stage?.dueOn||'Not set'}</p>{editable&&<ActionForm action={updateSopWorkflow} className="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="cycleId" value={cycle.id}/><input type="hidden" name="revision" value={cycle.revision}/><input type="hidden" name="versionId" value={version.id}/><input type="hidden" name="kind" value="stage"/><input type="hidden" name="index" value={index}/><input type="hidden" name="status" value={recorded?'open':'approved'}/><label className="grid gap-1 text-xs">Review owner<input name="owner" aria-label={`${guide.title} owner`} defaultValue={stage.owner} maxLength={160} className="rounded-lg border border-slate-200 px-3 py-2 text-sm"/></label><label className="grid gap-1 text-xs">Due date<input name="dueOn" aria-label={`${guide.title} due date`} type="date" defaultValue={stage.dueOn} className="rounded-lg border border-slate-200 px-3 py-2 text-sm"/></label><button className={quiet}>{recorded?'Reopen review':'Record review complete'}</button></ActionForm>}</article>;})}
  <section className={panel}><h3 className="text-lg font-semibold">Approve & release</h3><p className="mt-2 text-sm text-[var(--color-ink-muted)]">{state.detail}</p>{state.ready&&version?.status==='draft'&&can('sop.approve')&&<ActionForm action={approveSopVersion} className="mt-4"><input type="hidden" name="cycleId" value={cycle.id}/><input type="hidden" name="versionId" value={version.id}/><button className={primary}>Approve agreed forecast</button></ActionForm>}{state.ready&&version?.status==='approved'&&can('sop.publish')&&can('manufacturing.plan.manage')&&<ActionForm action={publishSopVersion} className="mt-4 space-y-3"><input type="hidden" name="cycleId" value={cycle.id}/><input type="hidden" name="versionId" value={version.id}/><p className="text-sm">Replaces monthly Manufacturing demand for these products. MRP counts confirmed orders once. This does not create or release production orders.</p><button className={primary}>Release approved demand to Manufacturing</button></ActionForm>}{state.ready&&version?.status==='approved'&&(!can('sop.publish')||!can('manufacturing.plan.manage'))&&<p className="mt-3 text-sm">Ask an authorised Manufacturing planner to release this approved demand.</p>}{version?.status==='published'&&<p className="mt-3 text-sm text-green-800">This demand has already been released. Its saved history is retained.</p>}</section>
 </section>;
}
export function SopHelp(){return <section aria-label="S&OP how-to guide" className="max-w-4xl space-y-5"><h2 className="text-2xl font-semibold">How to use S&OP</h2><p className="text-sm leading-relaxed text-[var(--color-ink-muted)]">Use S&OP for your regular business planning meeting: what will customers buy, can we deliver it, and what decisions do we need to make? Start with a monthly cycle, usually looking 12–18 months ahead.</p><ol className="list-decimal space-y-4 pl-5 text-sm">{['Create a cycle: name the planning round and choose its first month, horizon and currency.','Open Setup: choose product codes and connect your sales plans. Existing Sales orders are read automatically when you generate; Plan is where you add reasoned future assumptions.','Generate a working forecast: this saves a snapshot for everyone to review. A new snapshot starts new reviews.','Inspect Demand, Supply and Finance: investigate exceptions and compare useful what-if scenarios. Record decisions and owned actions.','Open Reviews & release: follow each checklist, record the seven reviews, then ask an authorised approver to approve the agreed version.','Release approved demand to Manufacturing when ready. Monitor Orders & Service and Accuracy & History, then refresh for the next planning round.'].map(step=><li key={step}>{step}</li>)}</ol><div className={panel}><h3 className="font-semibold">A simple example</h3><p className="mt-3 text-sm leading-relaxed">You expect to sell 100 units, including 60 already ordered. With orders consuming the forecast, total demand stays 100. If stock and dated supply cover only 80, you have a 20-unit gap to resolve. Keep the 100-unit demand visible while deciding whether to add supply, change dates or manage customer commitments.</p><p className="mt-3 text-xs text-[var(--color-ink-muted)]">Illustration only. These numbers are not saved into your company.</p></div><dl className="grid gap-4 sm:grid-cols-2">{[['Cycle','One planning round, with a start month and a forward-looking horizon.'],['Working forecast / consensus','The version the departments are trying to agree. It is not approved just because it exists.'],['Scenario','A what-if option. Promote the chosen option to a new working forecast and review it.'],['Stock cover at risk','Demand not covered by stock, receipts and planned production. It is not a full machine, material or labour capacity check.'],['Revenue target','A target from one connected Plan. Finance spending budgets are different.'],['Snapshot','Saved inputs and calculations at a point in time. Check its date; it does not refresh itself.']].map(([term,definition])=><div key={term} className={panel}><dt className="font-semibold">{term}</dt><dd className="mt-2 text-sm text-[var(--color-ink-muted)]">{definition}</dd></div>)}</dl></section>;}
export function SopViewIntro({view,base}:{view:string;base:string}){
 const guide=REVIEW_GUIDES.find(g=>g.view===view);if(!guide)return null;
 const terms=view==='demand'?[['Baseline','Expected demand from history before project inputs and confirmed-order consumption.'],['Confirmed orders','Whole-period orders, including fulfilled quantities. Remaining firm demand is shown separately.'],['Weighted project','Project demand adjusted for probability. Attributed orders consume it once.'],['Consensus','The whole-period demand you are reviewing, kept separate from supply constraints.']]:view==='supply'?[['Remaining demand','Demand still to fulfil, after recorded fulfilment or closed orders.'],['Constrained','Remaining demand covered by dated stock and supply after safety stock.'],['Demand at risk','Uncovered demand to discuss with Operations. Missing supply evidence is unavailable, not zero.']]:[['Revenue','Confirmed order values plus selling-price assumptions for uncommitted quantities.'],['Assumed cost / margin','Calculated only when an explicit cost assumption exists. These are not posted Finance actuals.']];
 return <section className="space-y-3 rounded-xl border border-blue-100 bg-blue-50/30 p-5"><h2 className="text-xl font-semibold">{guide.question}</h2><p className="text-sm text-[var(--color-ink-muted)]">{guide.checks[0]}</p><Link className="inline-block text-sm text-blue-700" href={`${base}&view=reviews`}>Open checklist and record the review →</Link><details><summary className="cursor-pointer text-sm font-medium">What these numbers mean</summary><dl className="mt-3 grid gap-3 sm:grid-cols-2">{terms.map(([term,meaning])=><div key={term}><dt className="text-sm font-semibold">{term}</dt><dd className="mt-1 text-xs text-[var(--color-ink-muted)]">{meaning}</dd></div>)}</dl></details></section>;
}
