'use client';
import {useState} from 'react';
import Link from 'next/link';
import type {monthlyBrief} from '../domain/guidance';
export function MonthlyBrief({months,currency,base}:{months:ReturnType<typeof monthlyBrief>;currency:string;base:string}){
 const [selected,setSelected]=useState(months[0]?.period??''),month=months.find(m=>m.period===selected)??months[0];
 const money=(n:number|null)=>n===null?'Not available':new Intl.NumberFormat('en-GB',{style:'currency',currency,maximumFractionDigits:0}).format(n/100),number=(n:number|null)=>n===null?'Supply evidence unavailable':n.toLocaleString('en-GB',{maximumFractionDigits:1});
 if(!month)return <p className="rounded-xl border border-dashed border-slate-300 p-5 text-sm">No product demand in this version. Check product scope and inputs in Setup.</p>;
 return <section aria-label="Monthly decision brief" className="space-y-4 rounded-2xl border border-[var(--color-border)] bg-white p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-semibold">Monthly planning picture</h2><p className="mt-2 text-xs text-[var(--color-ink-muted)]">Saved forecast, not live actuals. Select a month to focus the meeting.</p></div><label className="grid gap-1 text-xs">Planning month<select aria-label="Planning month" value={month.period} onChange={e=>setSelected(e.target.value)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm">{months.map(m=><option key={m.period}>{m.period}</option>)}</select></label></div><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[['Forecast revenue',money(month.revenue)],['Revenue target',money(month.target)],['Gap to target',money(month.gap)],['Assumed gross margin',money(month.margin)]].map(([label,value])=><div key={label}><p className="text-xs text-[var(--color-ink-muted)]">{label}</p><p className="mt-2 break-words text-xl font-semibold">{value}</p></div>)}</div><div className="grid gap-3 sm:grid-cols-2">{month.units.map(u=><div key={u.unit} className="rounded-xl bg-slate-50 p-4 text-sm"><h3 className="font-semibold">{u.unit}</h3><p className="mt-2">Expected demand: {number(u.demand)}</p><p className="mt-1">Still to fulfil: {number(u.remaining)}</p><p className={`mt-1 ${u.risk!==null&&u.risk>0?'text-amber-800':''}`}>Uncovered demand: {number(u.risk)}</p></div>)}</div><p className="text-xs text-[var(--color-ink-muted)]">{month.shortfalls} product-month shortfalls with known supply evidence. Unlike units are kept separate. Margin uses explicit cost assumptions.</p><div className="flex flex-wrap gap-4 text-sm">{[['demand','Review demand'],['supply','Review supply gaps'],['finance','Review finances'],['decisions','Record a decision']].map(([view,label])=><Link key={view} href={`${base}&view=${view}`} className="text-blue-700">{label} →</Link>)}</div></section>;
}
