import {SopGuideHome,SopHelp,SopReviews,SopViewIntro} from './guidance';
import {SopSetup} from './setup';
import Link from 'next/link';
import { SopService } from './service';
import { SopInsights } from './insights';
import { SopOverview,SopFinancialReview } from './overview';
import { ActionForm } from '@/components/ui/action-form';
import { getSopWorkspace,createSopCycle,updateSopWorkflow,createSopScenario,promoteSopScenario,overrideSopDemand,getSopComparison,getSopAccuracy } from '../services/workspace';
import type { DemandRow } from '../domain/engine';
const field='mt-1 w-full rounded-xl border border-black/10 bg-white px-3 py-2 text-sm';
const primary='rounded-full bg-[var(--color-atlas-blue)] px-4 py-2 text-sm font-semibold text-white';
const quiet='rounded-full border border-black/10 px-4 py-2 text-sm font-medium';
const num=(v:number|null|undefined)=>v==null?'Unavailable':v.toLocaleString('en-GB',{maximumFractionDigits:1});
const money=(v:number|null|undefined,currency:string)=>v==null?'Unavailable':new Intl.NumberFormat('en-GB',{style:'currency',currency,maximumFractionDigits:0}).format(v/100);
const date=(v:Date)=>v.toISOString().slice(0,10);
type WorkItem={id:string;title:string;detail:string;owner:string;dueOn:string;status:string};
export async function SopWorkspace({query}:{query:Record<string,string|undefined>}){
 const data=await getSopWorkspace(query.cycle,query.version,!['service','help'].includes(query.view??'')),{cycle,version}=data,view=['overview','demand','supply','finance','products','customers','projects','scenarios','cycle','history','service','setup','reviews','decisions','help'].includes(query.view??'')?query.view!:'overview',can=(c:string)=>data.capabilities.includes(c),payload=version?.payload;
 const base=cycle?`/sop?cycle=${cycle.id}`:'/sop';
 const rows=(payload?.rows??[]).filter(r=>!query.q||`${r.code} ${r.name}`.toLowerCase().includes(query.q.toLowerCase()));

 return <div className="space-y-7"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-wider text-[var(--color-ink-muted)]">Sales & Operations Planning</p><h1 className="mt-2 text-4xl font-semibold">{cycle?.name??'Sales & Operations Planning'}</h1><p className="mt-2 text-sm text-[var(--color-ink-muted)]">{cycle?`${date(cycle.startsOn)} — ${date(cycle.endsOn)} · ${cycle.currency} · ${cycle.companyVisible?'Shared with the company':'Private cycle'}`:'Agree what to sell, check how to deliver it, and make one plan together.'}</p></div><div className="flex flex-wrap gap-2"><Link href="/plan/plans" className={quiet}>Department plans ↗</Link><Link href="/sop?view=help" className={quiet}>How to use S&OP</Link>{can('sop.manage')?<a href="#new-cycle" className={primary}>New cycle</a>:null}</div></header>
 {data.cycles.length?<div className="flex flex-wrap items-end gap-5"><form className="flex min-w-0 flex-wrap items-end gap-3"><input type="hidden" name="view" value={view}/><label className="text-sm">Cycle<select aria-label="Planning cycle" name="cycle" className={`${field} max-w-64`} defaultValue={cycle?.id}>{data.cycles.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className={quiet}>Open cycle</button></form>{cycle&&data.versions.length?<form className="flex min-w-0 flex-wrap items-end gap-3"><input type="hidden" name="cycle" value={cycle.id}/><input type="hidden" name="view" value={view}/><label className="text-sm">Version<select aria-label="Forecast version" name="version" className={`${field} max-w-64`} defaultValue={version?.id}>{data.versions.map(v=><option key={v.id} value={v.id}>{v.name} · {v.status}</option>)}</select></label><button className={quiet}>Open version</button></form>:null}</div>:null}
 {cycle?<><div className="flex flex-wrap items-center justify-between gap-3 border-y border-black/10 py-4"><div className="text-sm">{version?<><strong>{version.name}</strong> · {version.status} · snapshot {date(version.createdAt)}{version.publishedAt?' · Published to MRP':''}</>:view==='service'?'Current service evidence':data.inaccessibleVersions?'Forecast versions need additional source access. Your authorised Orders & Service view remains available.':'No working forecast yet. Start with Setup, then generate your first forecast.'}</div>{can('sop.manage')&&view!=='setup'?<Link href={`${base}&view=setup`} className={quiet}>Refresh or change inputs →</Link>:null}</div>
 {view==='overview'?<><SopGuideHome data={data}/>{payload?<details className="rounded-2xl border border-black/10 p-5"><summary className="cursor-pointer font-semibold">Whole-horizon charts & financial detail</summary><div className="mt-5"><SopOverview payload={payload} base={`${base}&version=${version!.id}`} status={version!.status}/></div></details>:null}</>:null}
 {view==='setup'?<SopSetup data={data}/>:null}
 {view==='reviews'?<SopReviews data={data}/>:null}
 {view==='help'?<SopHelp/>:null}
 {['demand','supply','finance'].includes(view)&&payload?<><SopViewIntro view={view} base={`${base}&version=${version!.id}`}/><form className="flex max-w-lg items-end gap-2"><input type="hidden" name="cycle" value={cycle.id}/><input type="hidden" name="version" value={version?.id}/><input type="hidden" name="view" value={view}/><label className="grow text-sm">Product<input name="q" className={field} defaultValue={query.q} placeholder="Search SKU or product"/></label><button className={quiet}>Filter</button></form><DemandTable rows={rows.slice(0,500)} view={view} currency={cycle.currency} payload={payload}/>{rows.length>500?<p className="text-sm">Showing 500 rows. Filter by product to narrow the view.</p>:null}{view==='demand'&&version?.kind==='consensus'&&can('sop.manage')?<details className="rounded-2xl border border-black/10 p-5"><summary className="cursor-pointer font-semibold">Propose a demand override</summary><p className="mt-3 text-sm text-[var(--color-ink-muted)]">Revise whole-period consensus with a reason. Confirmed orders remain the minimum. A new immutable draft starts fresh reviews.</p><ActionForm action={overrideSopDemand} className="mt-4 grid max-w-4xl gap-4 md:grid-cols-3"><input type="hidden" name="cycleId" value={cycle.id}/><input type="hidden" name="versionId" value={version.id}/><input type="hidden" name="revision" value={cycle.revision}/><label className="text-sm">Product<select name="productId" className={field}>{[...new Map(rows.map(r=>[r.productId,r])).values()].map(r=><option key={r.productId} value={r.productId}>{r.code} · {r.name}</option>)}</select></label><label className="text-sm">Month<select name="period" className={field}>{[...new Set(rows.map(r=>r.period))].map(period=><option key={period}>{period}</option>)}</select></label><label className="text-sm">Revised demand<input name="quantity" type="number" min="0" step=".0001" required className={field}/></label><label className="text-sm md:col-span-3">Reason<textarea name="reason" required className={field}/></label><button className={quiet}>Create revised consensus</button></ActionForm></details>:null}{view==='finance'?<><SopFinancialReview payload={payload} base={`${base}&version=${version!.id}`}/><section><h2 className="text-xl font-semibold">Finance budget references</h2><p className="mt-1 text-sm text-[var(--color-ink-muted)]">These are Finance spending authorisations. They are not a revenue budget and are not subtracted from sales forecasts.</p>{payload.budgets.filter(b=>b.currency===cycle.currency).map(b=><p key={b.id} className="mt-3 text-sm">{b.name} · {money(b.amountMinor,b.currency)} · {b.startsOn} — {b.endsOn}</p>)}</section></>:null}</>:null}
 {['demand','supply','finance','products','customers','projects','scenarios','history'].includes(view)&&!payload?<SopGuideHome data={data}/>:null}
 {view==='service'?<SopService cycleId={cycle.id} query={query}/>:null}
 {['products','customers','projects'].includes(view)&&payload?<><form className="flex max-w-lg items-end gap-2"><input type="hidden" name="cycle" value={cycle.id}/><input type="hidden" name="version" value={version?.id}/><input type="hidden" name="view" value={view}/><label className="grow text-sm">Search<input name="q" className={field} defaultValue={query.q}/></label><button className={quiet}>Filter</button></form><SopInsights payload={payload} view={view} base={`${base}&version=${version!.id}`} query={query.q}/></>:null}
 {view==='scenarios'&&payload?<><ScenarioComparison cycleId={cycle.id} versionId={version!.id} currency={cycle.currency}/>{can('sop.manage')?<ActionForm action={createSopScenario} className="grid max-w-4xl gap-4 md:grid-cols-3"><input type="hidden" name="cycleId" value={cycle.id}/><input type="hidden" name="versionId" value={version!.id}/><label className="text-sm">Scenario name<input required name="name" className={field} placeholder="Upside / Downside / Project win"/></label><label className="text-sm">Demand change %<input type="number" min="-100" max="1000" step=".1" name="percent" defaultValue="0" className={field}/></label><label className="text-sm">Price change %<input type="number" min="-100" max="1000" step=".1" name="pricePercent" defaultValue="0" className={field}/></label><label className="text-sm">Production change %<input type="number" min="-100" max="1000" step=".1" name="productionPercent" defaultValue="0" className={field}/></label><label className="text-sm">Receipt delay (months)<input type="number" min="0" max="12" name="receiptDelayMonths" defaultValue="0" className={field}/></label><label className="text-sm">Unit cost change %<input type="number" min="-100" max="1000" step=".1" name="unitCostPercent" defaultValue="0" className={field}/></label><label className="text-sm md:col-span-3">Reason / assumptions<input required name="reason" className={field}/></label><button className={primary}>Create scenario from this version</button></ActionForm>:null}{version?.kind==='scenario'&&can('sop.manage')?<ActionForm action={promoteSopScenario} className="max-w-3xl space-y-3 rounded-2xl border border-black/10 p-5"><input type="hidden" name="cycleId" value={cycle.id}/><input type="hidden" name="versionId" value={version.id}/><input type="hidden" name="revision" value={cycle.revision}/><h3 className="font-semibold">Propose this scenario as consensus</h3><p className="text-sm text-[var(--color-ink-muted)]">Creates a new draft and starts fresh reviews. This scenario and the prior approved forecast are preserved.</p><label className="block text-sm">Decision reason<textarea name="reason" required className={field}/></label><button className={quiet}>Create proposed consensus</button></ActionForm>:null}</>:null}
 {['cycle','decisions'].includes(view)?<>{view==='cycle'?<><SopSetup data={data}/><SopReviews data={data}/></>:null}{view==='decisions'?<div><h2 className="text-2xl font-semibold">Decisions & follow-up</h2><p className="mt-2 text-sm text-[var(--color-ink-muted)]">Record the supply or financial gap, the option you chose and why. Give each follow-up an owner and due date. Keep unresolved decisions visible for the planning meeting.</p><Link className="mt-3 inline-block text-sm text-blue-700" href={`${base}&view=scenarios`}>Compare what-if scenarios →</Link></div>:null}{[['risks','Risks'],['actions','Actions'],['decisions','Decisions']].map(([kind,label])=><section key={kind}><h2 className="text-xl font-semibold">{label}</h2><ul className="mt-3 space-y-2">{(cycle[kind as 'risks'|'actions'|'decisions'] as unknown as WorkItem[]).map(i=><li className="border-l-2 border-black/10 pl-4 text-sm" key={i.id}><strong>{i.title}</strong> · {i.owner}{i.dueOn?` · ${i.dueOn}`:''}<p className="text-[var(--color-ink-muted)]">{i.detail}</p><p className="mt-1 text-xs">{i.status}</p>{kind==='actions'&&i.status!=='completed'&&can('sop.manage')?<ActionForm action={updateSopWorkflow} className="mt-2"><input type="hidden" name="cycleId" value={cycle.id}/><input type="hidden" name="revision" value={cycle.revision}/><input type="hidden" name="kind" value="complete-action"/><input type="hidden" name="actionId" value={i.id}/><button className={quiet}>Mark completed</button></ActionForm>:null}</li>)}</ul>{can('sop.manage')?<ActionForm action={updateSopWorkflow} className="mt-4 grid gap-3 md:grid-cols-4"><input type="hidden" name="cycleId" value={cycle.id}/><input type="hidden" name="revision" value={cycle.revision}/><input type="hidden" name="kind" value={kind}/><input name="title" required aria-label={`${label} title`} placeholder="Title" className={field}/><input name="detail" required aria-label={`${label} impact`} placeholder="Reason, alternatives and impact" className={field}/><input name="owner" aria-label={`${label} owner`} placeholder="Owner" className={field}/><input type="date" name="dueOn" aria-label={`${label} due date`} className={field}/><button className={quiet}>Add {label.toLowerCase().replace(/s$/,'')}</button></ActionForm>:null}</section>)}<div className="flex flex-wrap gap-3">{can('sop.share')?<ActionForm action={updateSopWorkflow}><input type="hidden" name="cycleId" value={cycle.id}/><input type="hidden" name="revision" value={cycle.revision}/><input type="hidden" name="kind" value="share"/><button className={quiet}>{cycle.companyVisible?'Make cycle private':'Share cycle with authorised company users'}</button></ActionForm>:null}</div></>:null}
 {view==='history'?<section><h2 className="text-xl font-semibold">Version history & model validation</h2><LagAccuracy cycleId={cycle.id}/><p className="mt-2 text-sm text-[var(--color-ink-muted)]">Previous snapshots are preserved. Model scores below use rolling historical holdouts; forecast-lag results use closed requested-demand periods above.</p><ul className="mt-4 divide-y divide-black/5">{data.versions.map(v=><li key={v.id} className="py-3"><Link href={`${base}&view=history&version=${v.id}`} className="font-medium text-[var(--color-atlas-blue)]">{v.name}</Link> · {v.kind} · {v.status} · {date(v.createdAt)}</li>)}</ul>{payload?.models.map(m=><details key={m.productId} className="border-t border-black/10 py-4"><summary className="cursor-pointer text-sm font-medium">{payload.rows.find(r=>r.productId===m.productId)?.code??m.productId} · {m.method} · {m.classification}</summary><p className="mt-3 text-sm">{m.explanation}</p><div className="mt-3 text-sm">{m.historyPeriods.map((p,index)=><p key={p}>{p} · observed {num(m.history[index])}</p>)}{m.validation.map(v=><p key={v.method}>{v.method} · MAE {num(v.mae)} · WAPE {num(v.wape)}% · bias {num(v.bias)}%</p>)}</div></details>)}</section>:null}
 {payload?<details className="border-t border-black/10 pt-4"><summary className="cursor-pointer text-sm text-[var(--color-ink-muted)]">Data basis & limitations</summary><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-[var(--color-ink-muted)]">{payload.warnings.map(w=><li key={w}>{w}</li>)}</ul></details>:null}
 </>:view==='help'?<SopHelp/>:<SopGuideHome data={data}/>}
 {can('sop.manage')?<details id="new-cycle" className="border-t border-black/10 pt-5" open={!cycle}><summary className="cursor-pointer text-xl font-semibold">Create a planning cycle</summary><p className="mt-3 max-w-3xl text-sm text-[var(--color-ink-muted)]">A cycle is one planning round. Give it a recognisable name, choose the first month and how far ahead to look. It starts private; you can share it after setup.</p><ActionForm action={createSopCycle} className="mt-4 grid max-w-4xl gap-4 md:grid-cols-4"><label className="text-sm">Cycle name<input aria-label="Cycle name" required name="name" className={field} placeholder="October S&OP"/></label><label className="text-sm">First planning month<input aria-label="First planning month" required type="month" name="start" className={field} defaultValue={new Date().toISOString().slice(0,7)}/></label><label className="text-sm">Look ahead<select aria-label="Planning horizon" name="horizon" defaultValue="18" className={field}>{[12,18,24,36].map(n=><option value={n} key={n}>{n} months</option>)}</select></label><label className="text-sm">Currency<select aria-label="Planning currency" name="currency" className={field}>{['GBP','EUR','USD'].map(c=><option key={c}>{c}</option>)}</select></label><button className={primary}>Create private cycle</button></ActionForm></details>:null}
 </div>;
}
function DemandTable({rows,view,currency,payload}:{rows:DemandRow[];view:string;currency:string;payload:import('../services/workspace').SopPayload}){
 const columns=view==='supply'?['Opening stock','Receipts','Production','Safety stock','Remaining demand','Constrained','Demand at risk','Closing stock']:view==='finance'?['Consensus units','Selling price','Revenue','Assumed cost','Margin']:['Baseline','Confirmed orders','Fulfilled / closed','Remaining firm','Project raw','Weighted project','Converted project','Project remaining','Adjustment','Consumed forecast','Consensus'];
 return <div className="overflow-x-auto rounded-2xl border border-black/10"><table className="w-full whitespace-nowrap text-sm"><thead className="bg-black/[.025] text-right"><tr><th className="sticky left-0 bg-white p-3 text-left">Product / month</th>{columns.map(c=><th key={c} className="p-3 font-medium">{c}</th>)}<th className="p-3">Why?</th></tr></thead><tbody>{rows.map(r=>{const values=view==='supply'?[r.opening,r.receipts,r.production,r.safetyStock,r.remainingDemand,r.constrained,r.atRisk,r.closing]:view==='finance'?[r.consensus,r.priceMinor,r.revenueMinor,r.costMinor,r.marginMinor]:[r.baseline,r.confirmedOrders,r.fulfilled,r.openOrders,r.projectRaw,r.projectWeighted,r.projectConsumed,r.projectRemaining,r.adjustment,r.consumed,r.consensus];return <tr className="border-t border-black/5 text-right" key={r.productId+r.period}><th className="sticky left-0 bg-white p-3 text-left font-medium"><Link href={`/products/${r.productId}`} className="text-[var(--color-atlas-blue)]">{r.code} ↗</Link><p className="text-xs font-normal text-[var(--color-ink-muted)]">{r.period} · {r.unit}</p></th>{values.map((v,i)=><td className="p-3 tabular-nums" key={i}>{view==='finance'&&i>0?money(v,currency):num(v)}</td>)}<td className="max-w-sm p-3 text-left"><details><summary className="cursor-pointer text-[var(--color-atlas-blue)]">Explain</summary><p className="mt-2 whitespace-normal text-xs">{r.why}</p>{payload.inputs.filter(i=>r.inputIds.includes(i.id)).map(i=><div key={i.id} className="mt-2 whitespace-normal text-xs"><Link href={`/plan/plans/${i.planId}?tab=inputs`} className="text-[var(--color-atlas-blue)]">{i.label} · source plan ↗</Link><p>{i.note}</p></div>)}{view==='supply'?(payload.supplySources??[]).filter(s=>s.productId===r.productId&&s.on.startsWith(r.period)).map((s,index)=><Link key={s.href+index} className="mt-2 block whitespace-normal text-xs text-[var(--color-atlas-blue)]" href={s.href}>{s.type} · {s.on} · {num(s.quantity)} {r.unit} ↗</Link>):null}{r.orderIds.map(id=><Link key={id} className="mt-1 block text-xs text-[var(--color-atlas-blue)]" href={`/sales/orders/${id}`}>Sales order ↗</Link>)}</details></td></tr>;})}{!rows.length?<tr><td colSpan={columns.length+2} className="p-8 text-center text-[var(--color-ink-muted)]">No demand in this selection. Add product inputs to a connected plan or load sales history.</td></tr>:null}</tbody></table></div>;
}
async function ScenarioComparison({cycleId,versionId,currency}:{cycleId:string;versionId:string;currency:string}){const rows=await getSopComparison(cycleId,versionId);return <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-left"><tr>{['Version','Revenue','Margin','Demand at risk value'].map(c=><th className="p-3 font-medium" key={c}>{c}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-black/5"><td className="p-3"><Link href={`/sop?cycle=${cycleId}&version=${r.id}&view=demand`} className="text-[var(--color-atlas-blue)]">{r.name}</Link> · {r.kind}<details className="mt-2 text-xs"><summary className="cursor-pointer">Revenue movement from selected version</summary><p className="mt-2">Opening {money(r.bridge.opening,currency)}<br/>Volume {money(r.bridge.volume,currency)}<br/>Price {money(r.bridge.price,currency)}<br/>Volume × price {money(r.bridge.interaction,currency)}<br/>Confirmed order value {money(r.bridge.committed,currency)}<br/>Rounding {money(r.bridge.rounding,currency)}<br/>Closing {money(r.bridge.closing,currency)}</p></details></td><td className="p-3">{money(r.revenue,currency)}</td><td className="p-3">{money(r.margin,currency)}</td><td className="p-3">{money(r.atRiskValueMinor,currency)}</td></tr>)}</tbody></table></div>;}
async function LagAccuracy({cycleId}:{cycleId:string}){const rows=await getSopAccuracy(cycleId);return <div className="my-5"><h3 className="font-medium">Forecast lag accuracy · requested demand</h3>{rows.length?<table className="mt-3 w-full text-sm"><thead className="text-left"><tr>{['Lag / unit','Product periods','MAE','WAPE','Bias','Value add vs baseline'].map(c=><th className="p-2 font-medium" key={c}>{c}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.lag+r.unit} className="border-t border-black/5"><td className="p-2">{r.lag} months · {r.unit}</td><td className="p-2">{r.count}</td><td className="p-2">{num(r.consensus.mae)}</td><td className="p-2">{num(r.consensus.wape)}%</td><td className="p-2">{num(r.consensus.bias)}%</td><td className="p-2">{num(r.fva)} percentage points</td></tr>)}</tbody></table>:<p className="mt-2 text-sm text-[var(--color-ink-muted)]">No closed requested-demand periods with a forecast made at least one month ahead yet. Keep publishing versions; accuracy appears as those periods close.</p>}</div>;}
