import Link from "next/link";
import { BookOpen, ArrowUpRight } from "lucide-react";
import { SUPPLY_GUIDES } from "@/modules/manufacturing/domain/guides";
export default async function SupplyHelp({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const query = await searchParams;
  const q = typeof query.q === "string" ? query.q.trim().toLowerCase().slice(0, 150) : "";
  const guides = SUPPLY_GUIDES.filter((guide) => `${guide.title} ${guide.summary} ${guide.role} ${guide.steps.map((step) => step.instruction).join(" ")}`.toLowerCase().includes(q));
  return <div className="space-y-6"><header className="rounded-[24px] border border-blue-100 bg-gradient-to-br from-blue-50 to-white p-6"><BookOpen className="text-blue-600" size={28} /><h2 className="mt-3 text-3xl font-semibold tracking-tight">How-to library</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500">Practical working instructions for planning, making, buying and reporting. Each guide includes a picture of the flow, the steps to follow, checks and common exceptions.</p></header><form className="flex gap-2"><label className="min-w-0 flex-1"><span className="sr-only">Search working instructions</span><input name="q" defaultValue={q} placeholder="Search products, stock, MRP, purchasing, receiving, spend…" className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm" /></label><button className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white">Search</button></form><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{guides.map((guide) => <Link key={guide.id} href={`/manufacturing/help/${guide.id}`} className="group rounded-[22px] border border-slate-200 bg-white p-5 hover:border-blue-200"><p className="text-xs font-semibold uppercase tracking-wider text-blue-600">{guide.role}</p><h3 className="mt-3 text-base font-semibold tracking-tight">{guide.title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{guide.summary}</p><p className="mt-4 flex items-center gap-2 text-xs font-semibold text-blue-600">Read working instructions<ArrowUpRight size={14} /></p></Link>)}</div>{!guides.length && <p className="rounded-2xl bg-white p-6 text-sm text-slate-500">No guide matches. Try another task or product term.</p>}</div>;
}
