"use client";
import Link from "next/link";
import { useState, useTransition } from "react";
import { cleanupConfirmation } from "@/core/admin/cleanup-input";
import { deleteSelectedTestCompanies, retryCompanyFileCleanup, type CleanupResult } from "./actions";
export type CleanupCompany = { id: string; name: string; updatedAt: string; status: string; current: boolean; users: number; customers: number; products: number; employees: number; files: number };
const input = "mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm";
export function CompanyCleanupForm({ companies, initialCompany }: { companies: CleanupCompany[]; initialCompany?: string }) {
  const [selected, setSelected] = useState<string[]>(companies.filter(company => company.id === initialCompany && !company.current).map(company => company.id));
  const [query, setQuery] = useState(""), [reviewing, setReviewing] = useState(false), [error, setError] = useState("");
  const [result, setResult] = useState<Exclude<CleanupResult, { error: string }> | null>(null);
  const [pending, start] = useTransition();
  const chosen = companies.filter(company => selected.includes(company.id));
  const shown = companies.filter(company => company.name.toLowerCase().includes(query.trim().toLowerCase()));
  if (result) return <section role="status" className={`space-y-4 rounded-2xl border p-6 ${result.filesPending ? "border-amber-200 bg-amber-50" : "border-emerald-200 bg-emerald-50"}`}><h3 className="text-lg font-semibold">{result.deleted} test {result.deleted === 1 ? "company deleted" : "companies deleted"}</h3><p className="text-sm">{result.filesPending ? `${result.filesPending} uploaded files still need removal. Use Retry file cleanup in the history below.` : "Company records, test-only accounts and uploaded files have been removed. Shared users and Atlas staff are preserved."}</p><Link href="/atlas" className="inline-block rounded-xl bg-slate-900 px-4 py-3 text-sm text-white">Back to companies</Link></section>;
  if (!reviewing) return <section className="space-y-5 rounded-2xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-semibold">Choose test companies</h3><p className="mt-2 text-sm text-slate-500">Select the companies you want to remove in one sweep.</p></div><span className="text-sm font-medium">{chosen.length} selected</span></div><label className="block text-xs">Find test companies<input value={query} onChange={event => setQuery(event.target.value)} className={input} placeholder="Search by company name…" /></label><div className="flex flex-wrap gap-3"><button type="button" className="rounded-lg border border-slate-200 px-3 py-2 text-xs" onClick={() => setSelected([...new Set([...selected, ...shown.filter(company => !company.current).map(company => company.id)])])}>Select all shown ({shown.filter(company => !company.current).length})</button><button type="button" className="rounded-lg border border-slate-200 px-3 py-2 text-xs" onClick={() => setSelected([])}>Clear selection</button></div><div className="max-h-[28rem] divide-y divide-slate-100 overflow-auto rounded-xl border border-slate-200">{shown.map(company => <label key={company.id} className="flex items-start gap-3 p-4"><input type="checkbox" checked={selected.includes(company.id)} disabled={company.current} className="mt-1" onChange={event => setSelected(event.target.checked ? [...selected, company.id] : selected.filter(id => id !== company.id))} /><span><span className="block text-sm font-medium">{company.name}</span><span className="mt-1 block text-xs text-slate-500">{company.status.toLowerCase()} · {company.users} users · {company.customers} customers · {company.products} products · {company.employees} employees · {company.files} uploaded files{company.current ? " · Current workspace: switch out first" : ""}</span></span></label>)}{!shown.length && <p className="p-5 text-sm text-slate-500">No test companies match.</p>}</div><button type="button" disabled={!chosen.length} onClick={() => { setReviewing(true); setError(""); }} className="rounded-xl bg-slate-900 px-5 py-3 text-sm text-white disabled:opacity-40">Review cleanup ({chosen.length})</button></section>;
  const confirmation = cleanupConfirmation(chosen.length);
  return <form method="post" className="space-y-5 rounded-2xl border border-rose-200 bg-white p-6" onSubmit={event => {
    event.preventDefault(); if (pending) return;
    const form = new FormData(event.currentTarget);
    form.set("selectedCompanies", JSON.stringify(chosen.map(({ id, name, updatedAt }) => ({ id, name, updatedAt }))));
    setError("");
    start(async () => {
      try { const response = await deleteSelectedTestCompanies(form); if ("error" in response) setError(response.error); else setResult(response); }
      catch { setError("The connection was interrupted. Refresh this page and check cleanup history before retrying."); }
    });
  }}><fieldset disabled={pending} className="space-y-5"><div><h3 className="text-lg font-semibold">Review permanent deletion</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">These {chosen.length} test companies and their records across every app will be deleted, including posted test finance records, documents, uploads, history, setup codes and company access. Accounts used elsewhere and Atlas staff remain. Existing server backups are retained.</p></div><ul className="max-h-60 space-y-2 overflow-auto rounded-xl bg-rose-50 p-4 text-sm">{chosen.map(company => <li key={company.id} className="font-medium">{company.name}</li>)}</ul><p className="text-sm text-rose-800">This cannot be undone in Atlas. Database records are deleted together. If file storage is unavailable, any remaining uploads are recorded for retry.</p><label className="block text-xs">Type {confirmation} to confirm<input name="confirmation" required autoComplete="off" className={input} /></label><label className="block text-xs">Your administrator password<input name="currentPassword" type="password" required autoComplete="current-password" className={input} /></label><label className="flex items-start gap-2 text-xs text-slate-700"><input name="acknowledge" type="checkbox" required className="mt-0.5" />I have reviewed this list and understand these companies and their data will be permanently deleted.</label><div className="flex flex-wrap gap-3"><button type="button" onClick={() => setReviewing(false)} className="rounded-xl border border-slate-200 px-4 py-3 text-sm">Back to selection</button><button type="submit" className="rounded-xl bg-rose-700 px-5 py-3 text-sm font-medium text-white disabled:opacity-50">{pending ? "Deleting…" : `Permanently delete ${chosen.length} ${chosen.length === 1 ? "company" : "companies"}`}</button></div></fieldset>{error && <p role="alert" className="text-sm text-rose-700">{error}</p>}</form>;
}
export function RetryFileCleanup({ runId }: { runId: string }) {
  const [pending, start] = useTransition(), [message, setMessage] = useState("");
  return <div><button type="button" disabled={pending} className="mt-3 rounded-lg border border-amber-300 px-3 py-2 text-xs disabled:opacity-50" onClick={() => start(async () => { try { const result = await retryCompanyFileCleanup(retryForm(runId)); setMessage("error" in result ? result.error : result.filesPending ? `${result.filesPending} files remain. Retry when storage is available.` : "All uploaded files removed."); } catch { setMessage("Could not reach Atlas. Retry when the connection returns."); } })}>{pending ? "Removing files…" : "Retry file cleanup"}</button>{message && <p role="status" className="mt-2 text-xs">{message}</p>}</div>;
}
function retryForm(runId: string): FormData { const form = new FormData(); form.set("runId", runId); return form; }
