import Link from 'next/link';
import type { Session } from '@/core/auth/session';
import { PLAN_TYPES,metricsFor,templateFor } from '../domain/catalogue';
import { createPlan } from '../services/commands';
import { enabledModules,planList } from '../services/queries';
import { field,primary,quiet } from './format';
import { ActionForm } from '@/components/ui/action-form';
export async function CreatePlan({session,query}:{session:Session;query:Record<string,string|undefined>}){
 const type=PLAN_TYPES.some(([key])=>key===query.type)?query.type!:'sales',template=templateFor(type),sensitive=session.capabilities.has('plan.sensitive.read');
 const [enabled,plans]=await Promise.all([enabledModules(session.organisationId),planList(session)]),metrics=metricsFor(enabled,sensitive),selected=new Set(template.metricKeys);
 const year=new Date().getFullYear(),start=`${year}-01-01`,end=`${year}-12-31`;
 return <div className="space-y-6"><header><Link href="/plan/plans" className="text-sm text-[var(--color-ink-muted)]">← All plans</Link><h1 className="mt-4 text-3xl font-semibold">Create a plan</h1><p className="mt-2 text-[var(--color-ink-muted)]">Choose a starting point. Add your projects, products, people and assumptions once the plan is created.</p></header><nav aria-label="Plan type" className="flex flex-wrap gap-2">{PLAN_TYPES.map(([key,label])=><Link key={key} href={`?type=${key}`} className={key===type?primary:quiet}>{label}</Link>)}</nav><ActionForm action={createPlan} className="max-w-4xl space-y-6" key={type}><input type="hidden" name="type" value={type}/><input type="hidden" name="mode" value="custom"/><input type="hidden" name="measuresChosen" value="true"/><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Name<input name="name" required placeholder={`${year} ${PLAN_TYPES.find(([key])=>key===type)?.[1]} plan`} className={field}/></label><label className="text-sm">Team<input name="team" className={field} placeholder="Optional"/></label><label className="text-sm">From<input type="date" name="start" required className={field} defaultValue={start}/></label><label className="text-sm">To<input type="date" name="end" required className={field} defaultValue={end}/></label><label className="text-sm sm:col-span-2">Purpose<textarea name="purpose" className={field} defaultValue={template.purpose} rows={2}/></label></div><details className="rounded-2xl border border-black/10 p-5"><summary className="cursor-pointer font-medium">Measures · change the starting selection</summary><fieldset className="mt-4 grid gap-3 sm:grid-cols-2">{metrics.map(m=><label key={m.key} className="flex gap-3 text-sm"><input type="checkbox" name="metric" value={m.key} defaultChecked={selected.has(m.key)}/><span><span className="font-medium">{m.name}</span><span className="block text-xs text-[var(--color-ink-muted)]">{m.definition}</span></span></label>)}</fieldset></details>{plans.length?<label className="block text-sm">Parent plan<select name="parent" className={field}><option value="">Independent plan</option>{plans.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>:null}{sensitive?<label className="flex items-center gap-2 text-sm"><input type="checkbox" name="sensitive" defaultChecked={template.sensitive===true}/>Contains sensitive figures</label>:null}<label className="flex items-center gap-2 text-sm"><input type="checkbox" name="starterWork"/>Add the suggested goals and work phases</label><p className="text-sm text-[var(--color-ink-muted)]">Private until you share it. You can add or change measures and inputs later.</p><button className={primary}>Create plan</button></ActionForm></div>;
}
