import { getPlanBuilder,savePlanInput,setPlanInputIncluded,applyPlanInputs } from '../services/builder';
import { ActionForm } from '@/components/ui/action-form';
import { field,primary,quiet,showMeasure } from './format';
import { metricByKey } from '../domain/catalogue';
import Link from 'next/link';
export async function InputBuilder({planId,search,editId}:{planId:string;search?:string;editId?:string}){
 const data=await getPlanBuilder(planId,search);const editing=data.inputs.find(i=>i.id===editId);
 return <div className="space-y-6">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><h3 className="text-2xl font-semibold">Build the plan</h3><p className="mt-2 max-w-3xl text-sm text-[var(--color-ink-muted)]">Pick a Sales project, opportunity, quotation or HR person, then enter what this plan expects. Add products, recruitment, costs or other assumptions directly. Phase a total across months or add each month separately.</p></div>{data.canEdit?<a href="#add-input" className={primary}>Add to plan</a>:null}</div>
  <form method="get" className="flex max-w-xl items-end gap-2"><input type="hidden" name="tab" value="inputs"/><label className="grow text-sm">Find a source<input name="q" defaultValue={search} placeholder="Project, quotation, product or person" className={field}/></label><button className={quiet}>Search</button></form>
  {data.warnings.map(w=><p key={w} className="text-sm text-amber-700">{w}</p>)}{data.hiddenInputs?<p className="text-sm text-amber-700">{data.hiddenInputs} inputs require source access you do not have. They cannot be applied to your forecast.</p>:null}
  <div className="overflow-x-auto rounded-2xl border border-black/10"><table className="w-full text-sm"><thead className="bg-black/[.025] text-left"><tr>{['Input / source','Measure / product','Month','Raw value','Probability','Weighted','Status',''].map(t=><th key={t} className="px-4 py-3 font-medium">{t}</th>)}</tr></thead><tbody>{data.inputs.map(i=>{const metric=metricByKey(i.metricKey);return <tr key={i.id} className="border-t border-black/5"><td className="px-4 py-3"><div className="font-medium">{i.label}</div>{i.source?<Link href={i.source.href} className="text-xs text-[var(--color-atlas-blue)]">{i.source.label} ↗</Link>:<span className="text-xs text-[var(--color-ink-muted)]">Planning assumption</span>}<p className="mt-1 text-xs text-[var(--color-ink-muted)]">{i.note}</p></td><td className="px-4 py-3">{metric?.name}<p className="text-xs text-[var(--color-ink-muted)]">{data.products.find(p=>p.id===i.productId)?.code}</p></td><td className="px-4 py-3">{i.periodKey}</td><td className="px-4 py-3 tabular-nums">{showMeasure(i.value,metric?.unit??'count')}</td><td className="px-4 py-3">{i.probability}%</td><td className="px-4 py-3 tabular-nums">{showMeasure(i.value*i.probability/100,metric?.unit??'count')}</td><td className="px-4 py-3">{i.source?.active===false?'Source lost / inactive':i.included?'Included':'Excluded'}</td><td className="px-4 py-3">{data.canEdit?<div className="flex gap-3"><Link href={`?tab=inputs&edit=${i.id}#add-input`} className="text-[var(--color-atlas-blue)]">Edit</Link><ActionForm action={setPlanInputIncluded}><input type="hidden" name="planId" value={planId}/><input type="hidden" name="inputId" value={i.id}/><input type="hidden" name="revision" value={data.revision}/><button className="text-[var(--color-ink-muted)]">{i.included?'Exclude':'Include'}</button></ActionForm></div>:null}</td></tr>;})}{!data.inputs.length?<tr><td colSpan={8} className="p-8 text-center text-[var(--color-ink-muted)]">This plan has no inputs yet. Start with a project, a product forecast, a hire or an expected cost below.</td></tr>:null}</tbody></table></div>
  {data.canEdit?<><section id="add-input" className="rounded-2xl border border-black/10 p-6"><h3 className="text-xl font-semibold">{editing?'Edit input':'Add to plan'}</h3><ActionForm action={savePlanInput} className="mt-4 grid gap-4 md:grid-cols-3" key={editing?.id??'new'}><input type="hidden" name="planId" value={planId}/><input type="hidden" name="revision" value={data.revision}/><input type="hidden" name="inputId" value={editing?.id??''}/>
   <label className="text-sm md:col-span-2">Source<select name="source" className={field} defaultValue={editing?.source?`${editing.source.module}|${editing.source.type}|${editing.source.id}`:''}><option value="">Direct planning assumption</option>{[...new Map([...data.sources,...(editing?.source?[editing.source]:[])].map(s=>[`${s.module}|${s.type}|${s.id}`,s])).values()].map(s=><option key={`${s.module}|${s.type}|${s.id}`} value={`${s.module}|${s.type}|${s.id}`}>{s.type} · {s.label}{s.probability!=null?` · ${s.probability}%`:''}</option>)}</select></label>
   <label className="text-sm">Name<input name="label" required className={field} defaultValue={editing?.label} placeholder="Project phase / new hire / sales uplift"/></label>
   <label className="text-sm">Measure<select name="metricKey" className={field} defaultValue={editing?.metricKey??'sales_volume'}>{data.metrics.map(m=><option value={m.key} key={m.key}>{m.owner} · {m.name}</option>)}</select></label>
   <label className="text-sm">Product<select name="productId" className={field} defaultValue={editing?.productId??''}><option value="">No product (people / costs / values)</option>{data.products.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name} ({p.unit})</option>)}</select></label>
   <label className="text-sm">Total value / quantity<input name="value" required className={field} defaultValue={editing?editing.value/(metricByKey(editing.metricKey)?.unit==='money'?100:1):''} placeholder="50000 or £120k"/></label>
   <label className="text-sm">First month<select name="period" className={field} defaultValue={editing?.periodKey??data.periods[0]}>{data.periods.map(p=><option key={p}>{p}</option>)}</select></label>
   <label className="text-sm">Last month (equal phasing)<select name="endPeriod" className={field} defaultValue="" disabled={!!editing}><option value="">Single month</option>{data.periods.map(p=><option key={p}>{p}</option>)}</select></label>
   <label className="text-sm">Probability %<input type="number" min="0" max="100" step=".01" name="probability" className={field} defaultValue={editing?.probabilityOverride?editing.probability:''} placeholder="Source probability, or 100%"/></label>
   <label className="text-sm">Selling price per unit<input name="unitPrice" className={field} defaultValue={editing?.unitPriceMinor!=null?editing.unitPriceMinor/100:''} placeholder="Optional — derives revenue from units"/></label>
   <label className="text-sm md:col-span-2">Reason / assumption<input required name="note" className={field} defaultValue={editing?.note} placeholder="What supports this number?"/></label>
   <input type="hidden" name="included" value={editing&&!editing.included?'off':'on'}/><div className="md:col-span-3"><button className={primary}>{editing?'Save input':'Add input'}</button>{editing?<Link href="?tab=inputs#add-input" className="ml-3 text-sm">Cancel edit</Link>:null}</div>
  </ActionForm></section>
  {data.inputs.length?<section className="flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-black/[.025] p-5"><p className="max-w-2xl text-sm">Replace affected forecast totals with the included, probability-weighted inputs. Product quantities with a selling price also derive revenue. Approved targets and previous versions remain unchanged. S&OP reconciles these inputs with confirmed orders.</p><ActionForm action={applyPlanInputs}><input type="hidden" name="planId" value={planId}/><input type="hidden" name="revision" value={data.revision}/><button className={primary} disabled={data.hiddenInputs>0}>Build forecast from inputs</button></ActionForm></section>:null}</>:null}
 </div>;
}
