import Link from 'next/link';
import type { Session } from '@/core/auth/session';
import { planRecord,cellValue } from '../services/queries';
import { audienceLabel,canEditPlan } from '../domain/access';
import { metricByKey,METRICS,planTypeLabel } from '../domain/catalogue';
import { periodKeys } from '../domain/engine';
import { InputBuilder } from './input-builder';
import { AdvancedPlanWorkspace } from './workspace';
import { PlanStory } from './story';
import { liveActuals } from '../services/actuals';
import { enabledModules } from '../services/queries';
import { savePlanGrid, removePlanMeasure } from '../services/builder';
import { addMeasure } from '../services/commands';
import { ActionForm } from '@/components/ui/action-form';
import { field,primary,quiet,showMeasure } from './format';
const tabs=[['overview','Overview'],['inputs','Build plan'],['forecast','Targets & forecast'],['work','Work & sharing'],['review','Review & scenarios']] as const;
export async function PlanWorkspace({session,planId,tab='overview',scenarioId,metricKey,query,editId}:{session:Session;planId:string;tab?:string;scenarioId?:string;metricKey?:string;query?:string;editId?:string}){
 const plan=await planRecord(session,planId),base=`/plan/plans/${plan.id}`;
 const canEdit=session.capabilities.has('plan.edit')&&canEditPlan(plan,session.userId)&&!plan.locked;
 const periods=periodKeys(plan.periodStart.toISOString().slice(0,10),plan.periodEnd.toISOString().slice(0,10));
 const working=plan.versions.find(v=>v.kind==='forecast'),baseline=plan.versions.find(v=>v.kind==='baseline'&&v.status==='approved');
 const metric=metricByKey(metricKey??plan.measures[0]?.metricKey??'revenue');
 const actuals=tab==='overview'||tab==='work'?await liveActuals(session,plan.measures.map(m=>m.metricKey),plan.periodStart,plan.periodEnd,await enabledModules(session.organisationId)):{};
 const targetTotal=plan.cells.filter(c=>c.versionId===(baseline??working)?.id&&c.kind==='plan'&&c.metricKey==='revenue'&&!c.dimensionKey).reduce((s,c)=>s+Number(c.value),0);
 return <div className="space-y-7"><header className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/plan/plans" className="text-sm text-[var(--color-ink-muted)]">← All plans</Link><p className="mt-4 text-xs uppercase tracking-wider text-[var(--color-ink-muted)]">{planTypeLabel(plan.planType)} · {plan.periodLabel} · {plan.status}</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">{plan.name}</h1><p className="mt-2 max-w-3xl text-[var(--color-ink-muted)]">{plan.purpose}</p><p className="mt-2 text-xs text-[var(--color-ink-muted)]">{plan.ownerName} · {audienceLabel(plan.audience,plan.shares.length)}{plan.locked?' · Locked':''}</p></div><div className="flex gap-2">{canEdit?<Link href={`${base}?tab=inputs#add-input`} className={primary}>Add to plan</Link>:null}<Link href={`${base}/present`} className={quiet}>Present</Link></div></header>
 <nav aria-label="Plan workspace" className="flex flex-wrap gap-2 border-b border-black/10 pb-4">{tabs.map(([key,label])=><Link key={key} href={`${base}?tab=${key}`} aria-current={tab===key?'page':undefined} className={tab===key?primary:quiet}>{label}</Link>)}</nav>
 {tab==='inputs'?<InputBuilder planId={plan.id} search={query} editId={editId}/>:null}
 {tab==='overview'?<><div className="grid gap-4 md:grid-cols-3">{[['Build the plan','Choose projects, products, people and assumptions.','inputs'],['Set the numbers','Edit monthly targets and the current forecast together.','forecast'],['Turn it into work','Owners, actions, timeline and sharing.','work']].map(([title,detail,key])=><Link href={`${base}?tab=${key}`} key={key} className="rounded-2xl border border-black/10 p-5"><h2 className="text-lg font-semibold">{title} →</h2><p className="mt-2 text-sm text-[var(--color-ink-muted)]">{detail}</p></Link>)}</div><section><h2 className="text-xl font-semibold">Plan, forecast and actual</h2><div className="mt-4 overflow-x-auto rounded-2xl border border-black/10"><table className="w-full text-sm"><thead className="text-left"><tr>{['Measure','Target','Forecast','Actual','Gap to target'].map(t=><th key={t} className="p-4 font-medium">{t}</th>)}</tr></thead><tbody>{plan.measures.map(m=>{const measure=metricByKey(m.metricKey);if(!measure)return null;const total=(id:string|undefined,kind:string)=>{const values=plan.cells.filter(c=>c.versionId===id&&c.metricKey===m.metricKey&&c.kind===kind&&!c.dimensionKey).map(c=>Number(c.value));return !values.length?null:measure.aggregation==='sum'?values.reduce((s,v)=>s+v,0):measure.aggregation==='average'?values.reduce((s,v)=>s+v,0)/values.length:values.at(-1)!;};const target=total((baseline??working)?.id,'plan'),forecast=total(working?.id,'forecast');return <tr key={m.metricKey} className="border-t border-black/5"><td className="p-4"><Link className="font-medium text-[var(--color-atlas-blue)]" href={`${base}?tab=forecast&metric=${m.metricKey}`}>{measure.name}</Link><p className="text-xs text-[var(--color-ink-muted)]">{measure.aggregation==='none'?'Latest entered period':measure.aggregation==='average'?'Period average':'Period total'}</p></td>{[target,forecast,actuals[m.metricKey]?.value,target!=null&&forecast!=null?forecast-target:null].map((v,i)=><td key={i} className="p-4 tabular-nums">{showMeasure(v,measure.unit,plan.currency)}</td>)}</tr>;})}</tbody></table></div></section><p className="text-sm text-[var(--color-ink-muted)]">Sales product inputs can be connected to an S&OP cycle for forecast consumption and supply review. <Link href="/sop" className="text-[var(--color-atlas-blue)]">Open S&OP ↗</Link></p></>:null}
 {tab==='forecast'&&metric&&working?<><div className="flex flex-wrap gap-2">{plan.measures.map(m=><Link href={`${base}?tab=forecast&metric=${m.metricKey}`} className={m.metricKey===metric.key?primary:quiet} key={m.metricKey}>{metricByKey(m.metricKey)?.name}</Link>)}</div><section><h2 className="text-2xl font-semibold">{metric.name}</h2><p className="mt-2 text-sm text-[var(--color-ink-muted)]">{metric.definition} {metric.unit==='money'?`Enter amounts in ${plan.currency}.`:''}{baseline?' Approved targets are preserved; propose revisions in Review & scenarios.':''}</p><ActionForm action={savePlanGrid} className="mt-5 space-y-4"><input type="hidden" name="planId" value={plan.id}/><input type="hidden" name="metricKey" value={metric.key}/><input type="hidden" name="revision" value={plan.revision}/><div className="overflow-x-auto rounded-2xl border border-black/10"><table className="w-full text-sm"><thead><tr><th className="sticky left-0 bg-white p-4 text-left">{metric.name}</th>{periods.map(p=><th className="p-3 font-medium" key={p}>{p}</th>)}</tr></thead><tbody>{['plan','forecast'].map(kind=><tr key={kind} className="border-t border-black/5"><th className="sticky left-0 bg-white p-4 text-left font-medium">{kind==='plan'?'Target':'Forecast'}</th>{periods.map(period=>{const v=cellValue(plan.cells,kind==='plan'?(baseline??working).id:working.id,metric.key,period,'',kind);return <td key={period} className="min-w-32 p-2"><input aria-label={`${kind} ${period}`} name={`${kind}:${period}`} defaultValue={v==null?'':v/(metric.unit==='money'?100:1)} className={field} disabled={!canEdit||plan.lockedPeriods.includes(period)||kind==='plan'&&!!baseline}/></td>;})}</tr>)}</tbody></table></div>{canEdit?<button className={primary}>Save {metric.name.toLowerCase()}</button>:null}</ActionForm></section></>:null}
 {tab==='forecast'&&canEdit?<ActionForm action={addMeasure} className="flex max-w-xl items-end gap-3"><input type="hidden" name="planId" value={plan.id}/><label className="grow text-sm">Add a measure<select className={field} name="metric">{METRICS.filter(m=>!plan.measures.some(p=>p.metricKey===m.key)&&(!m.sensitive||plan.sensitive&&session.capabilities.has('plan.sensitive.read'))).map(m=><option key={m.key} value={m.key}>{m.owner} · {m.name}</option>)}</select></label><button className={quiet}>Add measure</button></ActionForm>:null}
 {tab==='forecast'&&canEdit&&metric?<ActionForm action={removePlanMeasure}><input type="hidden" name="planId" value={plan.id}/><input type="hidden" name="revision" value={plan.revision}/><input type="hidden" name="metricKey" value={metric.key}/><button className="text-sm text-[var(--color-ink-muted)]">Hide this measure (history is kept)</button></ActionForm>:null}
 {tab==='work'?<PlanStory session={session} plan={plan} revenuePlan={targetTotal} actuals={actuals}/>:null}
 {tab==='review'?<AdvancedPlanWorkspace session={session} planId={planId} lens="executive" scenarioId={scenarioId} metricKey={metricKey}/>:null}
 </div>;
}
