import Link from "next/link";
import { requireSession } from "@/core/auth/session";
import { assertCapability } from "@/core/permissions/check";
import { QUALITY_CAPABILITIES as C } from "@/core/permissions/capabilities";
import { ncrDetail, similarNcr, qualityWorkspaceOptions } from "@/modules/quality/services/queries";
import { updateNcrAction, closeNcr, reopenNcr } from "@/modules/quality/services/ncr-actions";
import { ActionEditor } from "@/modules/quality/components/action-editor";
import { QualityForm } from "@/modules/quality/components/action-form";
import { IssueForm, qualityInput as input } from "@/modules/quality/components/issue-form";
import { canClose, label } from "@/modules/quality/domain/workflow";
import { QUALITY_FIELDS } from "@/modules/quality/domain/workspace";
export default async function NcrDetail({params}:{params:Promise<{ncrId:string}>}){
 const session=await requireSession();assertCapability(session,C.ncrRead);const ncr=await ncrDetail((await params).ncrId);const [options,similar]=await Promise.all([qualityWorkspaceOptions(),similarNcr(session,ncr.productId,ncr.defect)]);
 const manage=session.capabilities.has(C.ncrManage),open=ncr.status!=="CLOSED",gate=canClose(ncr);const ws=ncr.workspace&&typeof ncr.workspace==="object"&&!Array.isArray(ncr.workspace)?ncr.workspace as Record<string,unknown>:{};
 const hidden=<><input type="hidden" name="ncrId" value={ncr.id}/><input type="hidden" name="version" value={ncr.version}/></>;
 const owner=(id:string|null)=>options.members.find(p=>p.id===id)?.name??(id?"Previous company member":"Unassigned");
 return <div className="space-y-7"><Link href="/quality/ncr" className="text-sm text-[var(--color-atlas-blue)]">← Quality issues</Link><header className="space-y-2"><p className="text-sm text-slate-500">{ncr.number} · {label(ncr.source)} · {label(ncr.severity)}</p><h1 className="break-words text-3xl font-semibold tracking-tight">{ncr.title}</h1><p className="text-sm">{label(ncr.status)} · Owner: {owner(ncr.ownerUserId)}{ncr.dueAt?` · Target ${ncr.dueAt.toLocaleDateString("en-GB",{timeZone:"UTC"})}`:""}</p></header>
 {ncr.inspectionId&&session.capabilities.has(C.checkExecute)&&<Link href={`/quality/checks/${ncr.inspectionId}`} className="block text-sm underline">Open linked inspection results</Link>}
 <nav aria-label="Issue workflow" className="flex flex-wrap gap-2 text-xs">{["Record issue","Contain","Investigate","Take action","Verify effectiveness","Close"].map(step=><span key={step} className="rounded-full border bg-white px-3 py-2">{step}</span>)}</nav>
 <section className="grid gap-4 rounded-3xl border bg-white p-5 md:grid-cols-2"><div><p className="text-xs text-slate-500">Product / affected quantity</p><p className="text-sm">{ncr.product?.name??"Not product-specific"} · {ncr.quantityAffected??"Not recorded"}</p></div><div><p className="text-xs text-slate-500">Quality hold</p><p className="text-sm">{ncr.hold?`${ncr.hold.number} · ${label(ncr.hold.status)}`:"No linked hold"}</p>{ncr.hold&&session.capabilities.has(C.holdRead)&&<Link href="/quality/holds" className="text-xs underline">Review quality holds</Link>}</div>{[["Defect",ncr.defect],["Containment",ncr.containment],["Root cause",ncr.rootCause],["Disposition",`${label(ncr.disposition)} · ${ncr.dispositionNote??"No reason recorded"}`]].map(([title,value])=><div key={title} className="min-w-0"><p className="text-xs text-slate-500">{title}</p><p className="whitespace-pre-wrap break-words text-sm">{value||"Not recorded"}</p></div>)}</section>
 <details className="rounded-3xl border bg-white p-5"><summary className="cursor-pointer font-semibold">Context, investigation and evidence</summary><dl className="mt-4 grid gap-4 md:grid-cols-2">{QUALITY_FIELDS.filter(([key])=>ws[key]).map(([key,title])=><div key={key} className="min-w-0"><dt className="text-xs text-slate-500">{title}</dt><dd className="whitespace-pre-wrap break-words text-sm">{String(ws[key])}</dd></div>)}</dl></details>
 {similar.some(item=>item.id!==ncr.id)&&<aside className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm"><p className="font-medium">Possible repeat issues — same product and overlapping defect wording</p>{similar.filter(item=>item.id!==ncr.id).map(item=><Link key={item.id} href={`/quality/ncr/${item.id}`} className="mt-2 block underline">{item.number} · {item.title}</Link>)}</aside>}
 {manage&&open&&<details className="rounded-3xl border bg-white p-5"><summary className="cursor-pointer text-lg font-semibold">Edit issue and investigation</summary><div className="mt-5"><IssueForm record={{...ncr,dueAt:ncr.dueAt?.toISOString().slice(0,10)??"",workspace:ws}} options={options}/></div></details>}
 <section className="space-y-4 rounded-3xl border bg-white p-5"><h2 className="text-xl font-semibold">Corrective actions and effectiveness</h2><p className="text-sm text-slate-500">Record the work, then check whether it prevented the problem. Ineffective actions remain unresolved.</p>
 {!ncr.actions.length&&<p className="text-sm text-slate-500">No actions recorded yet.</p>}
 {ncr.actions.map(action=><article key={action.id} className="min-w-0 space-y-2 rounded-2xl border p-4"><h3 className="break-words font-medium">{action.description}</h3><p className="text-xs text-slate-500">{label(action.status)} · {owner(action.ownerUserId)}{action.dueDate?` · Due ${action.dueDate.toLocaleDateString("en-GB",{timeZone:"UTC"})}`:" · No due date"}</p><p className="text-sm">Effectiveness criterion: {action.effectivenessCriterion??"Not recorded"}</p><p className="text-xs text-slate-500">Review: {action.effectivenessReviewDate?.toLocaleDateString("en-GB",{timeZone:"UTC"})??"Not scheduled"}</p>{action.effectivenessResult&&<p className="whitespace-pre-wrap break-words text-sm">Review evidence: {action.effectivenessResult}</p>}
 {manage&&open&&action.status!=="VERIFIED"&&<QualityForm key={ncr.version} action={updateNcrAction} className="space-y-3">{hidden}<input type="hidden" name="actionId" value={action.id}/><label className="block text-sm">Next step<select aria-label={`Next step for ${action.description}`} name="status" className={input}>{(action.status==="OPEN"?["DONE"]:action.status==="INEFFECTIVE"?["OPEN"]:["VERIFIED","INEFFECTIVE","OPEN"]).map(value=><option key={value} value={value}>{label(value)}</option>)}</select></label><label className="block text-sm">Review evidence<textarea aria-label={`Review evidence for ${action.description}`} name="effectivenessResult" maxLength={2000} defaultValue={action.effectivenessResult??""} className={input}/></label><button type="submit" className="rounded-xl border px-4 py-2 text-sm">Update action</button></QualityForm>}{manage&&open&&action.status!=="VERIFIED"&&<details className="border-t pt-3"><summary className="cursor-pointer text-sm font-medium">Edit action details and dates</summary><ActionEditor ncrId={ncr.id} version={ncr.version} action={action} members={options.members}/></details>}</article>)}
 {manage&&open&&<details className="border-t pt-4"><summary className="cursor-pointer font-semibold">Add corrective action</summary><ActionEditor ncrId={ncr.id} version={ncr.version} members={options.members}/></details>}
 </section>
 {open&&session.capabilities.has(C.ncrClose)&&<section className="rounded-3xl border bg-white p-5"><h2 className="text-lg font-semibold">Closure review</h2>{!gate.ok&&<p className="my-3 text-sm text-amber-700">{gate.reason}</p>}<QualityForm key={ncr.version} action={closeNcr} className="mt-3 space-y-3">{hidden}<label className="block text-sm">Closure evidence<textarea aria-label="Closure evidence" name="closureEvidence" required minLength={10} className={input}/></label><button type="submit" disabled={!gate.ok} className="atlas-primary-button disabled:opacity-50">Close quality issue</button></QualityForm><p className="mt-2 text-xs text-slate-500">Closing this issue does not release a quality hold.</p></section>}
 {!open&&<section className="rounded-3xl border bg-white p-5"><p className="text-sm">Closed {ncr.closedAt?.toLocaleString("en-GB")} · {String(ws.closureEvidence??"Legacy closure — no evidence note recorded")}</p>{manage&&<details className="mt-4"><summary className="cursor-pointer font-medium">Reopen with a reason</summary><QualityForm key={ncr.version} action={reopenNcr} className="mt-3 space-y-3">{hidden}<label className="block text-sm">Reopen reason<textarea aria-label="Reopen reason" name="reason" required minLength={10} className={input}/></label><button type="submit" className="rounded-xl border px-4 py-2 text-sm">Reopen issue</button></QualityForm></details>}</section>}
 </div>;
}
