import Link from "next/link";
import { requireSession } from "@/core/auth/session";
import { assertCapability } from "@/core/permissions/check";
import { requireFinance } from "@/modules/finance/services/access";
import { FinanceWorkspace, financeSection as section } from "@/modules/finance/components/workspace";

const topics = [
  { title: "Finance overview", href: "/finance", capability: "finance.overview.read", text: "Choose the legal entity before reviewing its position. Receivables and payables show posted open invoices; purchase commitments are separate. Cash comes from posted bank-account entries. Draft documents do not change ledger balances." },
  { title: "Chart of accounts and posting profiles", href: "/finance/settings", capability: "finance.configure", text: "Create posting accounts and non-posting groups in Settings. A profile such as AR, AP, GRNI or REVENUE selects an account without hard-coded account numbers. Configure separate FX_GAIN, FX_LOSS and ROUNDING profiles for foreign-currency accounting. Accounts with transactions keep their type, profile and currency; deactivate them for future use instead of deleting history." },
  { title: "Financial dimensions", href: "/finance/settings", capability: "finance.configure", text: "Accounts can require, allow or prohibit Department, Cost centre, Site and Project. Configured department/cost-centre codes must be active and belong to the same books. Sites and projects refer to existing Atlas records. Project access is checked separately. Rule changes apply to subsequent postings and do not rewrite previous dimensions." },
  { title: "Journals and corrections", href: "/finance/ledger", capability: "finance.ledger.read", text: "A journal must balance exactly in transaction and base currencies. Manual journals require an assigned independent approver. The accounts and dimensions are checked again when posting. Posted entries are immutable; correct a manual entry with a linked reversal in an open period. Invoice corrections use separately approved source credit/debit notes. Recurring journals, accrual schedules and automatic prepayment release are not available yet." },
  { title: "Receivables and customer invoices", href: "/finance/receivables", capability: "finance.receivables.read", text: "Sales and delivered shipments can provide a sourced draft invoice. Finance submits it for approval and posts it separately. An invoice normally debits receivables and credits revenue and tax. The document, Sales order, source lines and journal remain linked. Posting dates and tax dates can differ from the document date. Customer statements and prepayment/refund workflows are still to be completed." },
  { title: "Credit control and collections", href: "/finance/collections", capability: "finance.receivables.read", text: "Use Collections to find overdue invoices and record calls, promises, disputes and follow-ups. Outstanding amounts remain in each invoice currency. A recorded email/letter does not send a message. Customer Service credit requests retain the case and invoice provenance; an independent Finance approval precedes posting. Configurable credit-exposure holds, dunning and automatic promise outcomes are not implemented in this release." },
  { title: "Supplier bills and invoice matching", href: "/finance/payables", capability: "finance.payables.read", text: "Use an existing shared Party as the supplier identity. Supplier onboarding and bank changes need independent verification. A PO bill compares cumulative invoiced quantities with ordered and accepted quantities. A bill for 100 units when only 80 were accepted is blocked. Price tolerance is configured per legal entity in basis points (200 = 2%); accepted-receipt and ordered-quantity limits still block. Allowed price differences post separately to Purchase price variance so GRNI clears at the receipt cost. OCR capture and supplier/item-specific tolerance overrides are not yet available. Authorised non-PO bills still follow approval and account validation." },
  { title: "Purchasing, receipts and GRNI", href: "/finance/purchases", capability: "finance.purchase.read", text: "An approved request creates a linked purchase order. Accepted goods receipts create valuation and GRNI accounting; physical products also update the selected Inventory warehouse with separate Inventory permission. Damaged units do not become available stock. Supplier invoice posting clears GRNI to payables. Quantity ownership remains with Inventory; lot, serial, bin and alternative valuation workflows require further work." },
  { title: "Payment runs", href: "/finance/banking", capability: "finance.payment.create", text: "A run proposes outstanding supplier invoices against an independently verified bank-account version. Pending bank verification, risk holds and duplicate active runs block preparation. Another assigned approver authorises the proposal. No bank execution connector is installed, so approving a run does not send money or mark invoices paid. Actual statement settlement remains separate." },
  { title: "Bank reconciliation", href: "/finance/reconcile", capability: "finance.bank.read", text: "Import tab-separated statement rows with stable external IDs, dates, references and signed amounts. Exact retries are unchanged; conflicting IDs are rejected. Review exact-amount and two-invoice suggestions, or choose partial/multiple allocations. The allocated bank amounts must equal the statement exactly. Imported evidence never invents an expense. Live feeds, bank rules, refunds, transfers and suspense workflows are not yet available." },
  { title: "Multi-currency", href: "/finance/reconcile", capability: "finance.bank.read", text: "Invoice postings retain their transaction currency, historical exchange rate and exact base amounts. When settling a foreign invoice from a base-currency bank, enter the invoice amount and its bank-currency equivalent. Atlas clears the retained carrying value and posts a realised FX gain or loss, including final-penny handling for partial payments. Historical invoice values stay unchanged. Foreign-bank accounts, period-end FX revaluation and group translation remain unfinished." },
  { title: "Expenses", href: "/finance/spend", capability: "finance.expense.create", text: "Expenses reference an approved Atlas HR claim. Finance validates that the total and currency equal the approved claim, records the reviewed tax split, and follows financial approval and posting. Receipts use central PDF/image storage. Approval does not itself reimburse an employee. Corporate cards, mileage/policy rules and an expense reimbursement payment interface require further work." },
  { title: "Fixed assets", href: "/finance/assets", capability: "finance.asset.read", text: "Register acquisition cost, residual value, useful life and location. The current engine posts straight-line monthly depreciation once per asset/month and caps it at the remaining depreciable amount. Registering an asset does not create acquisition accounting; reconcile it to a source bill or opening journal. Multiple books, disposal, impairment and automatic scheduler integration are not yet implemented." },
  { title: "Budgeting and cash forecast", href: "/finance/planning", capability: "finance.planning.read", text: "Budgets distinguish posted spend and remaining purchase commitments. A blocking budget is checked again at approval. The current cash outlook uses posted AR/AP due dates and retained invoice rates, and lists the sources it excludes. Saved scenarios are assumptions, not calculated forecasts. Versioned budgets, monthly phasing and the full 13-week operational cash model remain open." },
  { title: "Inventory accounting and manufacturing costing", href: "/finance/purchases", capability: "finance.purchase.read", text: "Finance consumes accepted purchasing receipts and records inventory/expense or capital cost against GRNI. Manufacturing, MRP and Inventory keep their operational records and existing connections. Full WIP, labour/overhead absorption, completion valuation, production variance, FIFO/weighted-average cost and landed-cost posting are not implemented here. Do not treat a product catalogue price or a physical movement alone as verified financial cost." },
  { title: "S&OP and projects", href: "/finance/planning", capability: "finance.planning.read", text: "Existing Plan/S&OP providers and Manufacturing links are preserved. Finance’s existing provider supplies governed posted actuals to shared business planning; it does not create a second operational forecast. Project references on postings use existing authorised Atlas projects. Translating an approved S&OP plan into a complete forecast P&L, balance sheet and cash flow remains unfinished." },
  { title: "Tax / VAT", href: "/finance/tax", capability: "finance.tax.read", text: "Source lines retain their configured tax treatment and amount. Input/output tax posts to configured accounts and links back to the document. Tax dates are retained separately for new postings. The existing tax ledger is not an HMRC submission or a filed VAT return. Tax-return locking/versioning, localisation rules, CIS, withholding and Making Tax Digital need tested connectors and further implementation." },
  { title: "Intercompany and consolidation", href: "/finance/reporting", capability: "finance.report.read", text: "Each configured legal entity has separate books, periods and a base currency. This does not yet provide intercompany pairing, due-to/due-from reconciliation, translation, eliminations or consolidated financial statements. Sites are not automatically separate legal entities. These group-finance workflows remain explicit delivery gaps." },
  { title: "Period close", href: "/finance/control", capability: "finance.control.read", text: "Complete close tasks with evidence and resolve draft journals before closing. On-hold periods allow only their configured source types; a closed period blocks ordinary posting. Reopening a held/closed period requires an assigned independent PERIOD_REOPEN approval. Locked periods stay final. Fiscal dates cannot overlap; adding a fiscal-start setting never changes existing period boundaries. Year-end retained-earnings closing is still to be implemented." },
  { title: "Reports, reconciliation and audit", href: "/finance/ledger", capability: "finance.ledger.read", text: "Trial balance is calculated from posted entries through the selected date. Drill into an account, then a journal, then its original document and Sales order. AR/AP reconciliation compares source carrying values and settlements with GL control accounts; differences stay visible. Report queries aggregate server-side and paginate transaction details. Advanced cash-flow statements, management packs, report builders and Inventory/Asset-to-GL reconciliation remain open." },
  { title: "Approvals and evidence", href: "/finance/control", capability: "finance.control.read", text: "Finance uses the shared Atlas approval policies, stages and dated delegations. Requesters cannot approve their own work. Posting checks the document’s exact approved version. Supported PDF, PNG and JPEG evidence stays on the central server. Existing Customer Service, S&OP and Manufacturing workflows are retained; Finance configuration does not grant additional source-module permissions." },
];

export default async function FinanceHelp() {
  const session = await requireSession();
  assertCapability(session, "finance.overview.read");
  await requireFinance(session, "finance.overview.read");
  return <FinanceWorkspace title="Finance help" description="How to use the connected accounting workflows available in Atlas, and where further implementation is still required.">
    <p className="max-w-3xl text-sm leading-6 text-slate-600">Business event → source document → approval → accounting distribution → balanced journal → ledger → report. Each stage keeps the originating record and its own access controls.</p>
    <div>{topics.filter(topic => session.capabilities.has(topic.capability)).map(topic => <details key={topic.title} className={`${section} pb-5`}><summary className="cursor-pointer font-semibold">{topic.title}</summary><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-600">{topic.text}</p><Link href={topic.href} className="mt-3 inline-block text-sm text-blue-700">Open workspace →</Link></details>)}</div>
  </FinanceWorkspace>;
}
