import Link from 'next/link';
import {notFound} from 'next/navigation';
import {requireSession} from '@/core/auth/session';
import {can} from '@/core/permissions/check';
import {HR_CAPABILITIES as HR} from '@/core/permissions/capabilities';
import {db} from '@/core/db/client';
import {hrPageRestriction,hrAccess} from '@/modules/people/services/platform-queries';
import {HRRestricted,HRHeading,panelClass} from '@/modules/people/components/platform-ui';
import {ApplicationForm} from '@/modules/people/components/recruitment-form';
export default async function Application({params}:{params:Promise<{applicationId:string}>}){const session=await requireSession();const restriction=await hrPageRestriction(session,true);if(restriction)return <HRRestricted disabled={restriction==='disabled'}/>;await hrAccess(session,true);const {applicationId}=await params;const record=await db.hrApplication.findFirst({where:{id:applicationId,organisationId:session.organisationId},include:{vacancy:true}});if(!record)notFound();const hire=can(session,HR.onboardingManage),employees=hire?await db.employee.findMany({where:{organisationId:session.organisationId,status:'ONBOARDING',email:{equals:record.email,mode:'insensitive'}},select:{id:true,firstName:true,lastName:true,email:true}}):[];return <div className="mx-auto w-full min-w-0 max-w-3xl space-y-6 break-words"><HRHeading title={record.name} description={`${record.vacancy.title} · ${record.stage}`}/><Link href="/people/recruitment" className="text-sm text-[var(--color-atlas-blue)]">← Recruitment</Link><section className={panelClass}>{['HIRED','REJECTED','WITHDRAWN'].includes(record.stage)?<><h3 className="font-semibold">Recruitment history</h3><p className="mt-3 text-sm">{record.email}{record.phone?` · ${record.phone}`:''}</p><p className="mt-3 whitespace-pre-wrap text-sm">{record.notes??'No decision notes recorded.'}</p>{record.employeeId&&<Link href={`/people/${record.employeeId}`} className="mt-3 inline-block text-sm text-[var(--color-atlas-blue)]">Open onboarding employee →</Link>}</>:<><h3 className="font-semibold">Application details</h3><ApplicationForm vacancies={[record.vacancy]} record={record} employees={employees} hire={hire}/>{record.stage==='OFFER'&&hire&&<Link href="/people/directory" className="mt-4 inline-block text-sm text-[var(--color-atlas-blue)]">Add accepted applicant as an employee →</Link>}</>}</section></div>;}
