"use client";
import {useState} from 'react';
import {ActionForm} from '@/components/ui/action-form';
import {presetCapabilities,effectiveRoleCapabilities,type AccessGroup,type AccessLevel} from '@/core/permissions/access-levels';
type Role={id:string;name:string;capabilities:string[]};
export function AccessEditor({groups,capabilities,action,roleId,membershipId,organisationId,roles=[],roleIds=[],granted=[],denied=[],disabled=false}:{groups:AccessGroup[];capabilities:string[];action:(form:FormData)=>Promise<void>;roleId?:string;membershipId?:string;organisationId?:string;roles?:Role[];roleIds?:string[];granted?:string[];denied?:string[];disabled?:boolean}){
 const [selected,setSelected]=useState(new Set(capabilities)),[assigned,setAssigned]=useState(new Set(roleIds)),[search,setSearch]=useState('');
 const changeRole=(id:string,checked:boolean)=>{const next=new Set(assigned);if(checked)next.add(id);else next.delete(id);setAssigned(next);setSelected(effectiveRoleCapabilities(roles.filter(r=>next.has(r.id)),granted,denied));};
 const preset=(group:AccessGroup,level:AccessLevel)=>{setSelected(previous=>{const next=new Set(previous);group.capabilities.forEach(c=>next.delete(c));presetCapabilities(group,level).forEach(c=>next.add(c));return next;});};
 const toggle=(cap:string,checked:boolean)=>setSelected(previous=>{const next=new Set(previous);if(checked)next.add(cap);else next.delete(cap);return next;});
 return <ActionForm action={action} className="space-y-6">{organisationId&&<input type="hidden" name="organisationId" value={organisationId}/>}<input type="hidden" name={roleId?'roleId':'membershipId'} value={roleId??membershipId}/>{[...selected].map(cap=><input key={cap} type="hidden" name="capability" value={cap}/>)}{[...assigned].map(id=><input key={id} type="hidden" name="roleId" value={id}/>)}<fieldset disabled={disabled} className="space-y-6">
 {!!roles.length&&<div><h3 className="text-sm font-semibold">Assigned roles</h3><p className="mt-1 text-xs text-slate-500">Combine roles, then fine-tune this user’s access below. Company restrictions still apply.</p><div className="mt-4 flex flex-wrap gap-2">{roles.map(role=><label key={role.id} className={`flex cursor-pointer items-center gap-2 rounded-xl border px-3 py-2 text-xs ${assigned.has(role.id)?'border-blue-200 bg-blue-50 text-blue-700':'border-slate-200 text-slate-600'}`}><input type="checkbox" checked={assigned.has(role.id)} onChange={e=>changeRole(role.id,e.target.checked)} className="accent-blue-600"/>{role.name}</label>)}</div></div>}
 <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-sm font-semibold">Access by workspace</h3><p className="mt-1 text-xs text-slate-500">Read views records. Write adds and edits. Admin includes approvals and sensitive controls. Expand to customise.</p></div><input aria-label="Find permissions" placeholder="Find a workspace or permission…" value={search} onChange={e=>setSearch(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-xs sm:w-64"/></div>
 <div className="space-y-3">{groups.filter(group=>(group.name+' '+group.capabilities.join(' ')).toLowerCase().includes(search.toLowerCase())).map(group=>{const selectedCaps=group.capabilities.filter(cap=>selected.has(cap));const level=(['none','read','write','admin'] as AccessLevel[]).find(level=>{const expected=presetCapabilities(group,level);return expected.length===selectedCaps.length&&expected.every(c=>selected.has(c));});return <div key={group.id} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h4 className="text-sm font-medium">{group.name}</h4><p className="mt-1 text-[11px] text-slate-400">{selectedCaps.length} of {group.capabilities.length} permissions · {level??'Custom'}</p></div><div className="flex rounded-xl bg-slate-100 p-1" role="group" aria-label={`${group.name} access level`}>{(['none','read','write','admin'] as AccessLevel[]).map(value=><button type="button" key={value} aria-pressed={level===value} onClick={()=>preset(group,value)} className={`rounded-lg px-3 py-2 text-xs capitalize transition ${level===value?'bg-white font-semibold text-blue-600 shadow-sm':'text-slate-500 hover:text-blue-600'}`}>{value}</button>)}</div></div><details className="mt-3 border-t border-slate-100 pt-3"><summary className="cursor-pointer text-xs text-blue-600">Fine-tune permissions</summary><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{group.capabilities.map(cap=><label key={cap} className="flex items-start gap-2 text-xs text-slate-600"><input type="checkbox" checked={selected.has(cap)} onChange={e=>toggle(cap,e.target.checked)} className="mt-0.5 accent-blue-600"/><span>{cap.split('.').slice(1).join(' · ').replaceAll('_',' ')}</span></label>)}</div></details></div>;})}</div>
 <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-blue-50 p-4"><p className="text-xs text-blue-700">{selected.size} permissions selected. Changes apply on the next request.</p><button type="submit" className="rounded-xl bg-blue-600 px-5 py-2.5 text-xs font-semibold text-white">Save access</button></div></fieldset>{disabled&&<p className="text-xs text-slate-500">Ask another administrator to change your own access.</p>}</ActionForm>;
}
