import Link from "next/link";
import {requireSession} from "@/core/auth/session";
import {can} from "@/core/permissions/check";
import {assertModuleEnabled} from "@/core/modules/access";
import {isModuleEnabled} from "@/core/modules/runtime";
import {getModule} from "@/core/modules/registry";
import {PeopleWorkspaceHeader,WorkspaceStats,workspacePanel} from "@/components/ui/people-workspace";

export default async function HRPayPage() {
  const session=await requireSession();await assertModuleEnabled(session,"people");const read=can(session,"payroll.run.read"),enabled=await isModuleEnabled(session,"payroll"),now=new Date(),start=`${now.toISOString().slice(0,7)}-01`,end=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,0)).toISOString().slice(0,10),provider=getModule("payroll")?.payrollReadinessProvider;
  const readiness=read&&enabled&&provider?await provider(session,start,end):null;
  const links=[{title:"Employee pay setup",description:"Hourly/salaried pay, tax, NI, pension, bank details and opening pay history.",href:"/payroll/employees",show:can(session,"payroll.employee.manage")&&enabled},{title:"Employee pay & contracts",description:"Employment, salary, contracted hours and permissioned payroll setup.",href:"/people/directory",show:can(session,"people.employee.read")},{title:"Approved actual time",description:"Review submitted time before it feeds overtime calculations.",href:"/people/timesheets",show:can(session,"people.team.manage")||can(session,"people.employee.manage")},{title:"Absence & leave",description:"Approved leave, sickness and statutory-pay review inputs.",href:"/people/absence",show:can(session,"people.absence.read")},{title:"Prepare UK payroll",description:"Check readiness, review statutory pay and generate draft payslips.",href:"/payroll/prepare",show:read&&enabled},{title:"Payroll runs",description:"Review payslips, finalise once and record payment status.",href:"/payroll",show:read&&enabled},{title:"My payslips",description:"Your pay records alongside your employee profile.",href:"/profile",show:true}];
  return <div className="space-y-6"><PeopleWorkspaceHeader eyebrow="HR platform" title="Pay & time" description="Employee records, approved time and reviewed pay inputs connect to UK payroll. Each step keeps its own approval and access rules." actions={<Link href="/people/workspace" className="rounded-xl border border-blue-200 bg-white px-4 py-2 text-sm font-semibold text-blue-700">HR home →</Link>}/>{readiness&&<WorkspaceStats items={[{label:"Monthly employees",value:readiness.employees},{label:"Approved actual hours",value:readiness.approvedHours.toFixed(1)},{label:"Time awaiting approval",value:readiness.awaitingApproval,tone:readiness.awaitingApproval?"warning":undefined},{label:"Pay setup issues",value:readiness.issues,tone:readiness.issues?"warning":undefined}]}/>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{links.filter(l=>l.show).map(link=><Link key={link.title} href={link.href} className={`${workspacePanel} transition hover:border-blue-300`}><h2 className="font-semibold">{link.title} →</h2><p className="mt-3 text-sm leading-6 text-slate-500">{link.description}</p></Link>)}</div>{!enabled&&<p className={`${workspacePanel} text-sm text-slate-500`}>Payroll is not enabled for this company. Employee records and time remain in HR; your company administrator can enable Payroll when needed.</p>}<section className={workspacePanel}><h2 className="font-semibold">A clear payroll sequence</h2><ol className="mt-4 grid gap-4 text-sm sm:grid-cols-4">{["Confirm employee and contract setup","Approve actual time and review absence","Generate and review draft payslips","Finalise once, then record payment"].map((step,i)=><li key={step} className="rounded-xl bg-blue-50 p-4"><span className="mb-2 block text-lg font-bold text-blue-700">{i+1}</span>{step}</li>)}</ol><p className="mt-4 text-xs leading-5 text-slate-500">Drafts hold a snapshot of their inputs. Source changes require a reviewed refresh. Year-to-date totals change at finalisation; marking a run paid records its status.</p></section></div>;
}
