import { CreateDialog } from "@/components/ui/create-dialog";
import { requireSession } from "@/core/auth/session";
import { assertCapability,can } from "@/core/permissions/check";
import { db } from "@/core/db/client";
import { ActionForm } from "@/components/ui/action-form";
import { Button } from "@/components/ui/button";
import { createTask,changeTaskStatus } from "../actions";
const input='mt-2 block w-full border border-[var(--color-border)] bg-white p-3 text-sm';
export default async function TasksPage() {
 const session=await requireSession();
 assertCapability(session,'projects.read');
 const [tasks,projects,members,meetings]=await Promise.all([db.projectTask.findMany({where:{organisationId:session.organisationId},include:{project:true,meeting:true},orderBy:{createdAt:'desc'}}),db.project.findMany({where:{organisationId:session.organisationId}}),db.membership.findMany({where:{organisationId:session.organisationId},include:{user:{select:{name:true}}}}),db.meeting.findMany({where:{organisationId:session.organisationId},orderBy:{startsAt:'desc'},take:100})]);
 const names=new Map(members.map(m=>[m.userId,m.user.name])),manage=can(session,'projects.manage');
 return <div className="space-y-6"><div><h2 className="text-3xl font-semibold tracking-tight">Team work, in one view.</h2><p className="mt-2 text-sm text-[var(--color-ink-muted)]">Clear owners, due dates and meeting actions.</p></div>{manage&&<CreateDialog title="Assign a task" label="Assign task"><ActionForm action={createTask} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><label className="text-xs">Task<input required name="title" className={input}/></label><label className="text-xs">Owner<select required name="assigneeUserId" className={input}>{members.map(m=><option key={m.id} value={m.userId}>{m.user.name}</option>)}</select></label><label className="text-xs">Due date<input type="date" name="dueAt" className={input}/></label><label className="text-xs">Project<select name="projectId" className={input}><option value="">Standalone task</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="text-xs">Meeting action<select name="meetingId" className={input}><option value="">No linked meeting</option>{meetings.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><Button type="submit" variant="primary" className="self-end">Assign task</Button></ActionForm></CreateDialog>}<div className="overflow-x-auto rounded-2xl border border-[var(--color-border)] bg-white"><table className="w-full text-sm"><thead className="bg-[var(--color-surface-sunken)] text-left"><tr>{['Task','Owner','Status','Due','Project / meeting'].map(h=><th key={h} className="p-4 font-medium">{h}</th>)}</tr></thead><tbody>{tasks.map(t=><tr key={t.id} className="border-t border-[var(--color-border)]"><td className="border-l-4 border-l-[var(--color-atlas-blue)] p-4 font-medium">{t.title}</td><td className="p-4"><span className="rounded-full bg-[var(--color-atlas-blue-soft)] px-3 py-1 text-xs">{names.get(t.assigneeUserId)??'Former member'}</span></td><td className="p-3">{manage?<ActionForm action={changeTaskStatus.bind(null,t.id)} className="flex items-center gap-2"><select name="status" defaultValue={t.status} className={`rounded-lg p-2 text-xs ${t.status==='DONE'?'bg-[var(--color-status-success-soft)] text-[var(--color-status-success)]':t.status==='BLOCKED'?'bg-[var(--color-status-warning-soft)] text-[var(--color-status-warning)]':'bg-[var(--color-atlas-blue-soft)] text-[var(--color-atlas-blue)]'}`}>{['TODO','IN_PROGRESS','BLOCKED','DONE'].map(s=><option key={s}>{s}</option>)}</select><Button type="submit" variant="ghost">Save</Button></ActionForm>:t.status}</td><td className="p-4">{t.dueAt?.toLocaleDateString('en-GB')??'—'}</td><td className="p-4 text-xs text-[var(--color-ink-muted)]">{[t.project?.name,t.meeting?.title].filter(Boolean).join(' · ')||'—'}</td></tr>)}</tbody></table>{!tasks.length&&<p className="p-8 text-center text-sm text-[var(--color-ink-muted)]">Assign the first task to your team.</p>}</div></div>;
}
