import Link from "next/link";
import { getTeamEmployee, addPrivateNote, updateWorkingPattern } from "@/app/(app)/people/self-service";
import { requireSession } from "@/core/auth/session";
import { can } from "@/core/permissions/check";
import { HR_CAPABILITIES as HR } from "@/core/permissions/capabilities";
import { ActionForm } from "@/components/ui/action-form";
import { Button } from "@/components/ui/button";
import { PersonGoals } from "@/modules/kpis/components/person-goals";
export async function TeamMemberWorkspace({employeeId,backPath="/people/my-team"}:{employeeId:string;backPath?:string}) {
  const employee=await getTeamEmployee(employeeId);
  const session=await requireSession();
  const hr=can(session,HR.employeeManage);
  return <div className="space-y-6"><div><Link href={backPath} className="mb-3 inline-block text-sm text-blue-600">← Back to team</Link><h2 className="text-2xl font-semibold">{employee.firstName} {employee.lastName}</h2><p className="mt-2 text-sm text-slate-500">{employee.jobTitle} · {employee.department}</p></div><PersonGoals employeeId={employee.id} personLabel={`${employee.firstName} ${employee.lastName}`} /><section className="rounded-2xl border bg-white p-6"><h3 className="font-semibold">Confidential manager &amp; HR notes</h3><p className="mt-2 text-xs text-slate-500">Staff cannot see these notes. Manager + HR notes are visible to the current direct manager and authorised HR. HR-only notes stay with HR. Notes are append-only.</p><ActionForm action={addPrivateNote.bind(null,employeeId)} className="mt-4 space-y-4"><label className="block text-sm">Note<textarea name="body" required maxLength={10000} rows={5} className="mt-2 w-full rounded-lg border p-3" /></label><label className="block text-sm">Visibility<select name="audience" className="mt-2 block rounded-lg border bg-white p-3"><option value="MANAGER_HR">Manager + HR</option>{hr && <option value="HR_ONLY">HR only</option>}</select></label><Button type="submit" variant="primary">Add private note</Button></ActionForm><ol className="mt-6 space-y-4">{employee.privateNotes.map(n=><li key={n.id} className="rounded-xl bg-slate-50 p-4"><p className="whitespace-pre-wrap text-sm">{n.body}</p><p className="mt-2 text-xs text-slate-500">{n.audience==="HR_ONLY"?"HR only":"Manager + HR"} · {n.createdAt.toLocaleString("en-GB")}{n.authorUserId===session.userId?" · Added by you":""}</p></li>)}</ol></section>{hr && <section className="rounded-2xl border bg-white p-6"><h3 className="font-semibold">Contracted working days</h3><p className="mt-2 text-xs text-slate-500">Used for holiday calculations. Existing booked days remain unchanged.</p><ActionForm action={updateWorkingPattern.bind(null,employeeId)} className="mt-4 flex flex-wrap gap-4">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map((label,i)=><label key={label} className="text-sm"><input type="checkbox" name="workingDays" value={i} defaultChecked={employee.workingDays.includes(i)} className="mr-2" />{label}</label>)}<Button type="submit">Save working days</Button></ActionForm></section>}</div>;
}
