import { ActionForm } from "@/components/ui/action-form";
import { Button } from "@/components/ui/button";
import { StatusPill } from "@/components/ui/status-pill";
import { getTimesheetContext, saveTimesheet, reviewTimesheet } from "@/app/(app)/people/timesheets/actions";
import { addDays } from "@/modules/people/domain/working-time";
export async function TimesheetsWorkspace({ query, basePath="/people/timesheets" }: { query: { week?: string; employeeId?: string }; basePath?: string }) {
  const { employees, selected, sheet, pending, weekStart } = await getTimesheetContext(query.week ?? new Date().toISOString().slice(0,10),query.employeeId);
  const locked = sheet && ["SUBMITTED", "APPROVED"].includes(sheet.status);
  return <div className="space-y-6"><div><h2 className="text-2xl font-semibold">Timesheets</h2><p className="mt-2 text-sm text-slate-500">Record actual work, save a draft, then submit for approval. Managers can enter hours for their team.</p></div>
    <form action={basePath} className="flex flex-wrap items-end gap-3"><label className="text-sm">Week containing<input type="date" name="week" defaultValue={weekStart.toISOString().slice(0,10)} className="mt-2 block rounded-lg border p-3" /></label><label className="text-sm">Employee<select name="employeeId" defaultValue={selected?.id} className="mt-2 block rounded-lg border bg-white p-3">{employees.map(e => <option key={e.id} value={e.id}>{e.firstName} {e.lastName}</option>)}</select></label><Button type="submit">Open week</Button></form>
    {!selected ? <p className="rounded-xl border p-6">Ask HR to link your login to an employee record.</p> : <section className="rounded-2xl border bg-white p-6"><div className="flex justify-between"><h3 className="font-semibold">{selected.firstName} {selected.lastName} · week of {weekStart.toLocaleDateString("en-GB", {timeZone:"UTC"})}</h3><StatusPill label={sheet?.status ?? "DRAFT"} tone={sheet?.status === "APPROVED" ? "success" : "neutral"} /></div>{sheet?.reviewNote && <p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm">Reviewer: {sheet.reviewNote}</p>}<ActionForm action={saveTimesheet} className="mt-5 space-y-4"><input type="hidden" name="employeeId" value={selected.id} /><input type="hidden" name="weekStart" value={weekStart.toISOString().slice(0,10)} /><fieldset disabled={Boolean(locked)} className="space-y-3">{Array.from({length:7},(_,i) => { const date=addDays(weekStart,i); const entry=sheet?.entries.find(e => e.workedOn.toISOString().slice(0,10)===date.toISOString().slice(0,10));return <div key={i} className="grid items-center gap-3 border-b pb-3 sm:grid-cols-[130px_120px_1fr]"><p className="text-sm">{date.toLocaleDateString("en-GB",{weekday:"short",day:"numeric",month:"short",timeZone:"UTC"})}</p><label className="text-xs">Hours<input name={`hours_${i}`} type="number" min="0" max="24" step="0.25" defaultValue={entry ? entry.minutes/60 : ""} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-xs">Work / task details<input name={`description_${i}`} maxLength={1000} defaultValue={entry?.description ?? ""} className="mt-1 w-full rounded-lg border p-2" /></label></div>})}{!locked && <div className="flex gap-3"><Button type="submit" name="intent" value="draft">Save draft</Button><Button type="submit" name="intent" value="submit" variant="primary">Submit hours</Button></div>}</fieldset><p className="text-sm text-slate-500">Recorded: {((sheet?.entries.reduce((s,e)=>s+e.minutes,0) ?? 0)/60).toFixed(2)} hours. Approved hours are not automatically posted to payroll.</p></ActionForm></section>}
    {pending.length > 0 && <section className="space-y-4 rounded-2xl border bg-white p-6"><h3 className="font-semibold">Hours awaiting your approval</h3>{pending.map(s => <div key={s.id} className="space-y-3 border-t pt-4"><p className="text-sm font-medium">{s.employee.firstName} {s.employee.lastName} · {s.weekStart.toLocaleDateString("en-GB",{timeZone:"UTC"})} · {(s.entries.reduce((sum,e)=>sum+e.minutes,0)/60).toFixed(2)} hours</p><details><summary className="cursor-pointer text-xs text-blue-600">Inspect daily hours</summary><ul className="mt-2 space-y-1 text-sm">{s.entries.map(e => <li key={e.id}>{e.workedOn.toLocaleDateString("en-GB",{timeZone:"UTC"})}: {e.minutes/60}h · {e.description ?? "No work description"}</li>)}</ul></details><ActionForm action={reviewTimesheet.bind(null,s.id)} className="flex flex-wrap gap-2"><input name="reviewNote" maxLength={2000} placeholder="Reviewer note (required when returning)" className="min-w-64 flex-1 rounded-lg border p-2 text-sm" /><Button type="submit" name="decision" value="APPROVED" variant="primary">Approve</Button><Button type="submit" name="decision" value="REJECTED">Return for correction</Button></ActionForm></div>)}</section>}
  </div>;
}
