"use client";
import { useState } from "react";
import { ActionForm } from "@/components/ui/action-form";
import { Field, TextArea, inputClass, RecordVersion } from "@/components/ui/service-fields";
import { askFinanceForCredit } from "../services/commands";
export function CreditRequestForm({ caseId, version, invoices, affectedQuantity }: { caseId: string; version: number; invoices: { id: string; reference: string; currency: string; lines: { id: string; description: string; quantity: string; net: string; tax: string }[] }[]; affectedQuantity?: number | null }) {
  const [invoiceId, setInvoice] = useState(invoices[0]?.id ?? ""), [lineId, setLine] = useState(""), [mode, setMode] = useState("QUANTITY"), [key] = useState(() => crypto.randomUUID());
  const invoice = invoices.find(value => value.id === invoiceId), line = invoice?.lines.find(value => value.id === lineId);
  if (!invoices.length) return <p className="text-sm text-slate-500">No posted invoice with outstanding value is available. Finance reviews paid-invoice refunds and goodwill separately.</p>;
  return <ActionForm action={askFinanceForCredit} label="Request Finance credit"><RecordVersion id={caseId} version={version}/><input name="requestKey" type="hidden" value={key}/><label className="block text-xs">Original invoice<select className={inputClass} name="invoiceId" value={invoiceId} onChange={event => { setInvoice(event.target.value); setLine(""); }}>{invoices.map(invoice => <option key={invoice.id} value={invoice.id}>{invoice.reference} · {invoice.currency}</option>)}</select></label><label className="block text-xs">Affected invoice line<select name="lineId" className={inputClass} value={lineId} onChange={event => setLine(event.target.value)} required><option value="">Choose original line</option>{invoice?.lines.map(line => <option key={line.id} value={line.id}>{line.description} · quantity {line.quantity}</option>)}</select></label>{line && <p className="text-xs text-slate-500">Original net {invoice?.currency} {(Number(line.net) / 100).toFixed(2)} · tax {(Number(line.tax) / 100).toFixed(2)}. Previous and pending credits are checked when you submit.</p>}<label className="block text-xs">Credit basis<select className={inputClass} value={mode} onChange={event => setMode(event.target.value)}><option value="QUANTITY">Affected quantity · original net price and tax</option><option value="VALUE">Fixed net value</option></select></label>{mode === "QUANTITY" ? <Field name="creditQuantity" title="Quantity to credit" type="number" min="1" step="1" max={line ? Number(line.quantity) : undefined} defaultValue={affectedQuantity ?? undefined} required/> : <Field name="amount" title={`Net amount · ${invoice?.currency ?? ""}`} inputMode="decimal" required/>}<TextArea name="reason" title="Reason and evidence summary" required/><p className="text-xs text-slate-500">Creates a CR request and linked draft credit. Independent Finance approval and manual posting are required.</p></ActionForm>;
}
