// Server-only synthetic acceptance; credentials and records never exported to Mac.
import fs from 'node:fs';import pg from 'pg';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const endpoint=process.argv[2]??'http://127.0.0.1:3104';if(!/^http:\/\/127\.0\.0\.1:\d+$/.test(endpoint))throw Error('Private loopback only.');
const env=Object.fromEntries(fs.readFileSync('/etc/atlas-test/migration.env','utf8').trim().split('\n').map(l=>{const i=l.indexOf('=');return[l.slice(0,i),l.slice(i+1)];}));const c=new pg.Client({connectionString:env.DATABASE_URL});await c.connect();
const identities=[],stamp=crypto.randomUUID(),base='src/modules/service/services/commands:';
const form=entries=>({__atlas:'form',entries:Object.entries(entries).map(([k,v])=>[k,String(v)])});
async function action(cookie,key,args){const r=await fetch(endpoint+'/api/desktop/action',{method:'POST',headers:{'Content-Type':'application/json','X-Atlas-Client':'desktop',...(cookie?{Cookie:cookie}:{})},body:JSON.stringify({action:key,args})});return{status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
async function ok(cookie,key,args){const r=await action(cookie,key,args);assert.equal(r.status,200,key+': '+JSON.stringify(r.body));return r.body;}
async function blocked(cookie,key,args){const r=await action(cookie,key,args);assert(r.status>=400,key+' unexpectedly allowed');return r;}
async function query(cookie,model,args,method='findMany'){const r=await fetch(endpoint+'/api/desktop/query',{method:'POST',headers:{'Content-Type':'application/json','X-Atlas-Client':'desktop',Cookie:cookie},body:JSON.stringify({model,method,args})});return{status:r.status,body:await r.json()};}
async function signup(suffix){const email=`service-${stamp}-${suffix}@example.invalid`,password=crypto.randomUUID()+crypto.randomUUID();identities.push(email);const r=await action(null,'src/app/(auth)/signup/actions:signup',[{error:''},form({name:'Synthetic '+suffix,company:'Synthetic Service '+stamp+' '+suffix,email,password})]);assert.equal(r.body.redirect,'/home',JSON.stringify(r.body));assert(r.cookie);const row=(await c.query('SELECT u.id AS userid,m.id AS membership,m."organisationId" AS org FROM users u JOIN memberships m ON m."userId"=u.id WHERE u.email=$1',[email])).rows[0];return{...row,email,password,cookie:r.cookie};}
async function move(user,org,caps){await c.query('DELETE FROM roles_on_memberships WHERE "membershipId"=$1',[user.membership]);await c.query('DELETE FROM memberships WHERE id=$1',[user.membership]);await c.query('DELETE FROM roles WHERE "organisationId"=$1',[user.org]);await c.query('DELETE FROM organisations WHERE id=$1',[user.org]);user.org=org;user.membership=crypto.randomUUID();await c.query('INSERT INTO memberships (id,"organisationId","userId",active,"grantedCapabilities","deniedCapabilities") VALUES ($1,$2,$3,true,$4,$5)',[user.membership,org,user.userid,caps,[]]);const r=await action(null,'src/core/auth/actions:loginAction',[form({email:user.email,password:user.password})]);assert(r.cookie);user.cookie=r.cookie;}
async function record(id){return(await c.query('SELECT * FROM service_cases WHERE id=$1',[id])).rows[0];}
try{
 const agent=await signup('agent'),department=await signup('department'),foreign=await signup('foreign'),standard=await signup('standard');
 await move(department,agent.org,['service.ticket.read','service.ticket.update']);await move(standard,agent.org,['service.case.read','service.ticket.read']);
 const party=crypto.randomUUID();await c.query('INSERT INTO parties (id,"organisationId",kind,name,"customerCode",tags,"updatedAt") VALUES ($1,$2,$3,$4,$5,$6,now())',[party,agent.org,'COMPANY','Synthetic Customer','TEST-SERVICE',[]]);
 const created=await ok(agent.cookie,base+'createCase',[form({partyId:party,subject:'Synthetic invoice complaint',type:'COMPLAINT',priority:'HIGH',severity:'SEV2'})]);const caseId=created.redirect.split('/').at(-1);let parent=await record(caseId);assert.equal(parent.ownerUserId,agent.userid);assert.equal(parent.priority,'HIGH');assert.equal(parent.severity,'SEV2');
 await ok(agent.cookie,base+'createQueue',[form({name:'Synthetic Finance',department:'Finance',prefix:'FIN'})]);const queue=(await c.query('SELECT id FROM service_queues WHERE "organisationId"=$1',[agent.org])).rows[0].id;await ok(agent.cookie,base+'addQueueMember',[form({queueId:queue,userId:department.userid})]);
 for(const subject of ['Investigate invoice','Confirm agreed price']){parent=await record(caseId);await ok(agent.cookie,base+'createDepartmentTicket',[form({caseId,version:parent.version,queueId:queue,subject,description:'Synthetic departmental investigation.',dueAt:'2026-10-04T11:00'})]);}
 parent=await record(caseId);assert.equal(parent.ownerUserId,agent.userid);assert.equal(parent.status,'WAITING_INTERNAL');
 const work=(await ok(department.cookie,base+'getDepartmentWork',[])).value;assert.equal(work.length,2);assert(work.every(t=>t.caseNumber===parent.number&&!('case'in t)&&!('party'in t)));
 const direct=await query(department.cookie,'serviceCase',{});assert.equal(direct.status,403);await blocked(department.cookie,base+'addCaseEntry',[form({caseId,version:parent.version,kind:'INTERNAL_NOTE',body:'Must not write'})]);
 await blocked(foreign.cookie,base+'updateCase',[form({caseId,version:parent.version,type:'QUERY',priority:'LOW',severity:'SEV4'})]);const other=await query(foreign.cookie,'serviceCase',{where:{id:caseId}});assert.equal(other.status,200);assert.equal(other.body.value.length,0);
 const first=work[0];await ok(department.cookie,base+'updateDepartmentTicket',[form({ticketId:first.id,version:first.version,status:'COMPLETE',takeOwnership:'yes',outcome:'Synthetic correction validated.',customerSafeSummary:'The discrepancy has been corrected.'})]);parent=await record(caseId);assert.equal(parent.status,'WAITING_INTERNAL');assert.equal(parent.ownerUserId,agent.userid);
 await blocked(agent.cookie,base+'transitionCase',[form({caseId,version:parent.version,status:'RESOLVED',resolutionCode:'INVOICE_CORRECTED',resolutionSummary:'Synthetic corrected invoice.'})]);
 const second=work[1];await ok(department.cookie,base+'updateDepartmentTicket',[form({ticketId:second.id,version:second.version,status:'COMPLETE',takeOwnership:'yes',outcome:'Synthetic contract price confirmed.'})]);
 parent=await record(caseId);await ok(agent.cookie,base+'addCaseEntry',[form({caseId,version:parent.version,kind:'EXTERNAL_LOG',body:'Synthetic customer update already made by telephone.'})]);parent=await record(caseId);await ok(agent.cookie,base+'transitionCase',[form({caseId,version:parent.version,status:'RESOLVED',resolutionCode:'INVOICE_CORRECTED',resolutionSummary:'Synthetic corrected invoice.'})]);
 parent=await record(caseId);await ok(agent.cookie,base+'addCaseEntry',[form({caseId,version:parent.version,kind:'CUSTOMER_CONTACT',body:'Synthetic follow-up: issue remains.'})]);parent=await record(caseId);assert.equal(parent.status,'OPEN');assert.equal(parent.reopenCount,1);
 await blocked(agent.cookie,base+'updateCase',[form({caseId,version:1,type:'QUERY',priority:'LOW',severity:'SEV4'})]);
 const restricted=await ok(agent.cookie,base+'createCase',[form({partyId:party,subject:'Synthetic restricted case',security:'RESTRICTED'})]);const restrictedId=restricted.redirect.split('/').at(-1);const restrictedQuery=await query(standard.cookie,'serviceCase',{where:{id:restrictedId}});assert.equal(restrictedQuery.status,200);assert.equal(restrictedQuery.body.value.length,0);
 assert.equal((await query(agent.cookie,'serviceEntry',{},'deleteMany')).status,403);await blocked(null,base+'getDepartmentWork',[]);assert.equal((await fetch(endpoint+'/service')).status,404);assert.equal((await fetch(endpoint+'/service/cases')).status,404);
 assert.equal((await c.query('SELECT count(*)::int AS n FROM domain_outbox WHERE "organisationId"=$1 AND "eventName" LIKE $2',[agent.org,'service.%'])).rows[0].n>0,true);
 console.log('PASS: central case/two-ticket lifecycle, owner retained, incomplete dependency blocks resolution, response-ready history, customer-update log, resolution/reopening, stale-version rejection, department/tenant/restricted isolation, append-only query protection, durable outbox and server UI absent.');
}finally{
 const orgs=(await c.query('SELECT DISTINCT m."organisationId" AS id FROM users u JOIN memberships m ON m."userId"=u.id WHERE u.email=ANY($1)',[identities])).rows.map(r=>r.id);
 for(const org of orgs){for(const table of ['service_entries','service_links','service_tickets','service_cases','service_queue_members','service_queues','service_sequences'])await c.query(`DELETE FROM ${table} WHERE "organisationId"=$1`,[org]);await c.query('DELETE FROM roles_on_memberships WHERE "membershipId" IN (SELECT id FROM memberships WHERE "organisationId"=$1)',[org]);await c.query('DELETE FROM roles WHERE "organisationId"=$1',[org]);await c.query('DELETE FROM organisations WHERE id=$1',[org]);}
 await c.query('DELETE FROM users WHERE email=ANY($1)',[identities]);await c.end();console.log('Synthetic Service fixtures removed on server.');
}
