// Server operator only. Back up and verify restore before reviewed additive schema changes.
import fs from 'node:fs';import pg from 'pg';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
const env=Object.fromEntries(fs.readFileSync('/etc/atlas-test/migration.env','utf8').split('\n').filter(Boolean).map(l=>{const i=l.indexOf('=');return[l.slice(0,i),l.slice(i+1)];}));
const url=new URL(env.DATABASE_URL),connection={PGHOST:url.hostname,PGPORT:url.port||'5432',PGUSER:decodeURIComponent(url.username),PGPASSWORD:decodeURIComponent(url.password)},db=new pg.Client({connectionString:env.DATABASE_URL});await db.connect();const stamp=new Date().toISOString().replace(/[:.]/g,'-'),backup=`/opt/atlas-test/backups/finance-${stamp}`,restore=`atlas_finance_restore_${Date.now()}`;
try{await db.query("SELECT pg_advisory_lock(hashtext('atlas-release-finance'))");fs.mkdirSync(backup,{recursive:true,mode:0o700});execFileSync('pg_dump',['-Fc','-f',`${backup}/central.dump`,decodeURIComponent(url.pathname.slice(1))],{env:{...process.env,...connection},stdio:'pipe'});fs.writeFileSync(`${backup}/previous-release.txt`,fs.realpathSync('/opt/atlas-test/current'));await db.query(`CREATE DATABASE "${restore}"`);try{execFileSync('pg_restore',['--exit-on-error','--no-owner','-d',restore,`${backup}/central.dump`],{env:{...process.env,...connection},stdio:'pipe'});}finally{await db.query(`DROP DATABASE "${restore}" WITH (FORCE)`);}console.log('Central backup saved and restore verified on server.');
 const existing=(await db.query("SELECT to_regclass('public.finance_entities') AS present")).rows[0].present;if(existing)throw new Error('Finance schema already exists; reconcile recorded migration before attempting release.');const sql=fs.readFileSync(new URL('../prisma/migrations/20261003400000_finance_controls/migration.sql',import.meta.url),'utf8');fs.writeFileSync(`${backup}/finance-migration.sql`,sql);await db.query('BEGIN');await db.query(sql);await db.query('ALTER TABLE projects_work_links ADD COLUMN IF NOT EXISTS "targetVersion" INTEGER, ADD COLUMN IF NOT EXISTS "anchorStart" INTEGER, ADD COLUMN IF NOT EXISTS "anchorEnd" INTEGER');
 // Record only this reviewed migration. Never apply all unrelated pending migrations.
 await db.query('INSERT INTO _prisma_migrations(id,checksum,finished_at,migration_name,logs,started_at,applied_steps_count) VALUES($1,$2,now(),$3,NULL,now(),1)',[crypto.randomUUID(),crypto.createHash('sha256').update(sql).digest('hex'),'20261003400000_finance_controls']);await db.query('GRANT SELECT,INSERT,UPDATE,DELETE ON finance_entities,finance_accounts,finance_periods,finance_journals,finance_journal_lines,finance_suppliers,finance_bank_versions,finance_documents,finance_document_lines,finance_settlements,finance_banks,finance_bank_transactions,finance_budgets,finance_assets,finance_contracts,finance_scenarios,finance_close_tasks,finance_timeline,approval_policies,approval_instances,approval_steps,approval_delegations,finance_payment_runs,finance_payment_items,finance_attachments TO atlas_runtime');await db.query('COMMIT');console.log('Reviewed Finance schema applied; additive Project compatibility fields present. No existing business rows changed.');console.log(`Backup: ${backup}`);
}catch(e){try{await db.query('ROLLBACK');}catch{}throw e;}finally{await db.query("SELECT pg_advisory_unlock(hashtext('atlas-release-finance'))");await db.end();}
