"use client";
import { useState } from "react";
import Link from "next/link";
import { Building2, Network, MapPin, ChevronDown, ChevronRight } from "lucide-react";
type Customer={id:string;name:string;customerCode:string;parentPartyId:string|null;hierarchyRole:string;customerGroup:string|null;status:string};
export function CustomerMap({customers}:{customers:Customer[]}) {
 const [query,setQuery]=useState(''),[group,setGroup]=useState(''),[collapsed,setCollapsed]=useState<Set<string>>(new Set());
 const groups=[...new Set(customers.flatMap(c=>c.customerGroup?[c.customerGroup]:[]))].sort();
 const children=(id:string)=>customers.filter(c=>c.parentPartyId===id);
 function matches(c:Customer,seen=new Set<string>()):boolean {if(seen.has(c.id))return false;seen.add(c.id);return ((!group||c.customerGroup===group)&&(!query||`${c.name} ${c.customerCode}`.toLowerCase().includes(query.toLowerCase())))||children(c.id).some(child=>matches(child,new Set(seen)));}
 function toggle(id:string){setCollapsed(prev=>{const next=new Set(prev);if(next.has(id))next.delete(id);else next.add(id);return next;});}
 function node(c:Customer,seen=new Set<string>()):React.ReactNode {
  if(seen.has(c.id))return null;seen.add(c.id);
  const branches=children(c.id).filter(child=>matches(child)),folded=collapsed.has(c.id),Icon=c.hierarchyRole==='GROUP'?Network:c.hierarchyRole==='BRANCH'?MapPin:Building2;
  const color=c.hierarchyRole==='GROUP'?'violet':c.hierarchyRole==='BRANCH'?'teal':'blue';
  return <div key={c.id} className="flex shrink-0 flex-col items-center"><div className="relative w-60 rounded-2xl border bg-white p-5 shadow-[0_8px_25px_#31447c0a] transition-all hover:-translate-y-1 hover:shadow-lg" style={{borderColor:`var(--color-accent-${color}-soft)`}}><div className="mb-4 flex items-center justify-between"><span className="flex size-10 items-center justify-center rounded-xl" style={{background:`var(--color-accent-${color}-soft)`,color:`var(--color-accent-${color})`}}><Icon size={20}/></span><span className="rounded-full px-2.5 py-1 text-[10px] font-semibold tracking-wide" style={{background:`var(--color-accent-${color}-soft)`,color:`var(--color-accent-${color})`}}>{c.hierarchyRole}</span></div><Link href={`/customers/${c.id}`} className="block text-sm font-semibold leading-relaxed">{c.name}</Link><p className="mt-2 text-[11px] text-[var(--color-ink-faint)]">{c.customerCode} · {c.status.replaceAll('_',' ')}</p>{c.customerGroup&&<p className="mt-2 text-xs text-[var(--color-ink-muted)]">{c.customerGroup}</p>}{branches.length>0&&<button onClick={()=>toggle(c.id)} aria-expanded={!folded} className="mt-4 flex w-full items-center justify-between rounded-lg bg-[var(--color-surface-sunken)] px-3 py-2 text-xs">{branches.length} connected accounts {folded?<ChevronRight size={14}/>:<ChevronDown size={14}/>}</button>}</div>{branches.length>0&&!folded&&<><div className="h-8 w-px bg-[#c8d3ec]"/><div className="flex items-start gap-5">{branches.map(child=><div key={child.id} className="relative flex flex-col items-center before:absolute before:inset-x-[-10px] before:top-0 before:h-px before:bg-[#c8d3ec]"><div className="h-8 w-px bg-[#c8d3ec]"/>{node(child,new Set(seen))}</div>)}</div></>}</div>;
 }
 const roots=customers.filter(c=>!c.parentPartyId||!customers.some(p=>p.id===c.parentPartyId)).filter(c=>matches(c));
 return <div className="space-y-5"><div className="flex flex-wrap gap-3 rounded-2xl border border-[var(--color-border)] bg-white p-4"><input aria-label="Search customer map" placeholder="Find an account or branch…" value={query} onChange={e=>setQuery(e.target.value)} className="min-w-48 flex-1 border border-[var(--color-border)] px-4 py-2.5 text-sm"/><select aria-label="Customer type" value={group} onChange={e=>setGroup(e.target.value)} className="border border-[var(--color-border)] bg-white px-4 py-2.5 text-sm"><option value="">All customer types</option>{groups.map(g=><option key={g}>{g}</option>)}</select><button onClick={()=>setCollapsed(new Set())} className="rounded-xl bg-[var(--color-surface-sunken)] px-4 py-2 text-xs">Expand all</button><button onClick={()=>setCollapsed(new Set(customers.map(c=>c.id)))} className="rounded-xl bg-[var(--color-surface-sunken)] px-4 py-2 text-xs">Collapse all</button></div><div className="overflow-auto rounded-3xl border border-[#dce5f6] bg-[#f2f5fc] p-8" style={{backgroundImage:'radial-gradient(#c5d1eb 1px, transparent 1px)',backgroundSize:'20px 20px'}}><div className="flex min-w-max items-start justify-center gap-12 pb-5">{roots.map(c=>node(c))}</div>{!roots.length&&<p className="py-12 text-center text-sm text-[var(--color-ink-muted)]">No matching accounts.</p>}</div><p className="text-xs text-[var(--color-ink-muted)]">Tap an account to open its record. Change its level, type and parent from Account hierarchy. Scroll the canvas to explore wider groups.</p></div>;
}
