import {requireSession} from '@/core/auth/session';
import {assertCapability,can} from '@/core/permissions/check';
import {assertModuleEnabled} from '@/core/modules/access';
import {db} from '@/core/db/client';
import {members} from '@/core/shared/operational-forms';
import {CreateDialog} from '@/components/ui/create-dialog';
import {JobForm} from '@/modules/fieldservice/components/form';
import {Heading,Panel,Empty,Stats,Row,quiet} from '@/components/operations/ui';
export default async function Page({searchParams}:{searchParams:Promise<{mine?:string;customerId?:string}>}){const s=await requireSession();assertCapability(s,'fieldservice.job.read');await assertModuleEnabled(s,'fieldservice');assertCapability(s,'customers.read');const q=await searchParams,[jobs,customers,people]=await Promise.all([db.fieldServiceJob.findMany({where:{organisationId:s.organisationId,party:{identityScrubbed:false},...(q.customerId?{partyId:q.customerId}:{}),...(q.mine==='1'?{engineerUserId:s.userId}:{})},include:{party:{select:{name:true,customerCode:true}}},orderBy:{scheduledStart:'desc'},take:201}),db.party.findMany({where:{organisationId:s.organisationId,archived:false,identityScrubbed:false},select:{id:true,name:true,customerCode:true},orderBy:{name:'asc'},take:500}),members(s)]),open=jobs.filter(j=>!['COMPLETED','CANCELLED'].includes(j.status));return <div className="space-y-6"><Heading eyebrow="Field Service" title="Every visit, ready to deliver." description="Schedule engineers, prepare the job sheet, record what happened on site and close the job with a clear outcome.">{can(s,'fieldservice.job.manage')?<CreateDialog title="Schedule service visit" label="Schedule visit"><JobForm customers={customers.map(c=>({id:c.id,name:c.customerCode+' · '+c.name}))} people={people}/></CreateDialog>:null}</Heading><Stats items={[{label:'Scheduled / open',value:open.length},{label:'On site',value:jobs.filter(j=>j.status==='ON_SITE').length},{label:'Waiting',value:jobs.filter(j=>j.status==='WAITING').length},{label:'Unassigned visits',value:open.filter(j=>!j.engineerUserId).length}]}/><form method="get" className="flex flex-wrap items-center gap-3">{q.customerId?<input type="hidden" name="customerId" value={q.customerId}/>:null}<label className="flex items-center gap-2 text-sm"><input type="checkbox" name="mine" value="1" defaultChecked={q.mine==='1'}/>Only my visits</label><button className={quiet}>Apply view</button></form><Panel title="Engineer schedule"><div className="space-y-3">{jobs.slice(0,200).map(j=><Row key={j.id} href={'/fieldservice/'+j.id} title={j.title} meta={`${j.party.name} · ${j.scheduledStart.toLocaleString('en-GB',{timeZone:j.timezone})} · ${people.find(p=>p.userId===j.engineerUserId)?.user.name??'Unassigned'}`} status={j.status}/>)}{!jobs.length?<Empty>No service visits in this view. Schedule a customer visit, assign an engineer and add the site details and preparation instructions.</Empty>:null}</div>{jobs.length>200?<p className="mt-4 text-xs text-slate-500">Showing the most recent 200 visits.</p>:null}</Panel></div>;}
