import Link from 'next/link';
import {requireSession} from '@/core/auth/session';
import {assertCapability} from '@/core/permissions/check';
import {db} from '@/core/db/client';
import {CreateDialog} from '@/components/ui/create-dialog';
import {ActionForm} from '@/components/ui/action-form';
import {Button} from '@/components/ui/button';
import {createCompanyAccount} from './actions';
export default async function AtlasConsole({searchParams}:{searchParams:Promise<{q?:string}>}){
 const session=await requireSession();assertCapability(session,'atlas.companies.manage');const {q=''}=await searchParams;
 const organisations=await db.organisation.findMany({where:q?{name:{contains:q,mode:'insensitive'}}:{},include:{_count:{select:{memberships:true,moduleStates:true}}},orderBy:{createdAt:'desc'},take:100});
 return <div className="mx-auto max-w-6xl space-y-6"><div className="rounded-3xl bg-[#12213c] p-8 text-white"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-blue-300">ATLAS OWNER CONSOLE</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Your company accounts</h1><p className="mt-3 text-sm text-slate-300">Manage access, trials and app entitlements across Atlas. Company business records stay inside their workspaces.</p></div><div className="flex flex-wrap justify-between gap-4"><form className="flex gap-3"><input aria-label="Search companies" name="q" defaultValue={q} placeholder="Find a company…" className="border border-slate-200 bg-white px-4 py-3 text-sm"/><Button type="submit">Search</Button></form><CreateDialog title="Create a company account" label="New company"><ActionForm action={createCompanyAccount} className="grid gap-4 sm:grid-cols-2">{[['name','Company name','text'],['ownerName','Administrator name','text'],['email','Administrator email','email'],['password','Initial password','password']].map(([name,label,type])=><label key={name} className="text-sm">{label}<input required name={name} type={type} minLength={type==='password'?12:undefined} autoComplete={type==='password'?'new-password':'off'} className="mt-2 w-full border border-slate-200 p-3"/></label>)}<p className="text-xs text-slate-500 sm:col-span-2">Creates an isolated workspace with all implemented apps for a 14-day trial. Subscription dates are managed here; automated billing is not connected.</p><Button type="submit" variant="primary">Create company account</Button></ActionForm></CreateDialog></div><div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{['Company','Account','Subscription','Users','Created',''].map(h=><th key={h} className="p-4 font-medium">{h}</th>)}</tr></thead><tbody>{organisations.map(o=><tr key={o.id} className="border-t border-slate-100"><td className="p-4 font-semibold"><Link href={`/atlas/${o.id}`} className="text-blue-600">{o.name}</Link><p className="mt-1 text-xs font-normal text-slate-400">{o.planName}</p></td><td className="p-4"><span className={`rounded-full px-3 py-1 text-[10px] ${o.status==='ACTIVE'?'bg-emerald-50 text-emerald-700':'bg-rose-50 text-rose-600'}`}>{o.status}</span></td><td className="p-4 text-xs">{o.subscriptionStatus}{o.trialEndsAt&&<p className="mt-1 text-slate-400">Trial ends {o.trialEndsAt.toLocaleDateString('en-GB')}</p>}</td><td className="p-4">{o._count.memberships}</td><td className="p-4 text-xs text-slate-500">{o.createdAt.toLocaleDateString('en-GB')}</td><td className="p-4"><Link href={`/atlas/${o.id}`} className="text-blue-600">Manage →</Link></td></tr>)}</tbody></table></div><p className="text-xs text-slate-400">Showing up to 100 matching accounts. Atlas owner grants cannot be assigned through company roles.</p></div>;
}
