import { NCR_SOURCES, NCR_SEVERITIES, NCR_DISPOSITIONS, ACTION_STATUSES } from "./workflow";
export class QualityInputError extends Error {}
export const QUALITY_FIELDS = [
 ["location","Site / work area"],["department","Department / process"],["lot","Lot / batch / serial reference"],["externalReference","Customer, supplier or document reference"],
 ["requirement","Expected requirement / standard"],["impact","Impact and extent of the problem"],["evidence","Evidence / document references"],["investigationMethod","Investigation method"],
 ["why1","Why 1 — what caused the problem?"],["why2","Why 2"],["why3","Why 3"],["why4","Why 4"],["why5","Why 5"],
 ["causeEvidence","Evidence supporting the root cause"],["prevention","Wider prevention / lessons learned"],["closureEvidence","Closure review and evidence"],
] as const;
export function qualityText(form:FormData,key:string,max=4000){const raw=form.get(key);if(raw!==null&&typeof raw!=="string")throw new QualityInputError("Use text for form fields.");const value=String(raw??"").trim();if(value.length>max)throw new QualityInputError(`${key} is too long (maximum ${max} characters).`);return value;}
export function requiredText(form:FormData,key:string,max=4000){const value=qualityText(form,key,max);if(!value)throw new QualityInputError(`${key} is required.`);return value;}
export function qualityDate(form:FormData,key:string){const raw=qualityText(form,key,10);if(!raw)return null;const date=new Date(`${raw}T00:00:00.000Z`);if(!/^\d{4}-\d{2}-\d{2}$/.test(raw)||Number.isNaN(date.getTime())||date.toISOString().slice(0,10)!==raw)throw new QualityInputError("Enter a valid calendar date.");return date;}
export function choice<T extends string>(form:FormData,key:string,options:readonly T[]):T{const value=qualityText(form,key,40);if(!options.includes(value as T))throw new QualityInputError(`Choose an available ${key}.`);return value as T;}
export function ncrInput(form:FormData){const raw=qualityText(form,"quantityAffected",16);const quantityAffected=raw?Number(raw):null;if(quantityAffected!==null&&(!Number.isSafeInteger(quantityAffected)||quantityAffected<0||quantityAffected>2147483647))throw new QualityInputError("Quantity affected must be a non-negative whole number.");return {title:requiredText(form,"title",250),defect:requiredText(form,"defect",2000),source:choice(form,"source",NCR_SOURCES),severity:choice(form,"severity",NCR_SEVERITIES),productId:qualityText(form,"productId",100)||null,ownerUserId:qualityText(form,"ownerUserId",100)||null,dueAt:qualityDate(form,"dueAt"),quantityAffected,containment:qualityText(form,"containment")||null,rootCause:qualityText(form,"rootCause")||null,rootCauseConfirmed:form.get("rootCauseConfirmed")==="1",disposition:choice(form,"disposition",NCR_DISPOSITIONS),dispositionNote:qualityText(form,"dispositionNote",2000)||null,workspace:Object.fromEntries(QUALITY_FIELDS.map(([key])=>[key,qualityText(form,key)]))};}
export function actionInput(form:FormData){return {description:requiredText(form,"description",2000),ownerUserId:requiredText(form,"ownerUserId",100),dueDate:qualityDate(form,"dueDate"),effectivenessCriterion:requiredText(form,"effectivenessCriterion",2000),effectivenessReviewDate:qualityDate(form,"effectivenessReviewDate")};}
export function actionTransition(from:string,to:string,result:string,criterion:string|null){if(!ACTION_STATUSES.includes(to as typeof ACTION_STATUSES[number]))throw new QualityInputError("Choose an available action status.");const allowed:Record<string,string[]>={OPEN:["DONE"],DONE:["OPEN","VERIFIED","INEFFECTIVE"],VERIFIED:[],INEFFECTIVE:["OPEN"]};if(!allowed[from]?.includes(to))throw new QualityInputError("Record completion before verification. Reopen an ineffective action before doing the work again.");if(["VERIFIED","INEFFECTIVE"].includes(to)&&(!criterion||result.trim().length<10))throw new QualityInputError("Record the effectiveness criterion and review evidence before verifying the outcome.");}
