import { requireSession } from "@/core/auth/session";
import { assertCapability } from "@/core/permissions/check";
import { db } from "@/core/db/client";
import { ATLAS_STAFF_ROLES } from "@/core/admin/access";
import { CreateDialog } from "@/components/ui/create-dialog";
import { PortalActionForm as ActionForm } from "@/app/(app)/atlas/portal-action-form";
import { CredentialForm } from "../credential-form";
import { createAtlasStaff, updateAtlasStaff, issueAtlasStaffRecovery, saveAtlasStaffProfile } from "../admin-actions";
const input = "mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm";
export default async function AtlasTeam({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const session = await requireSession();
  assertCapability(session, "atlas.staff.manage");
  const query = ((await searchParams).q ?? "").trim().slice(0, 100);
  const people = await db.platformAdministrator.findMany({ where: query ? { user: { OR: [{ name: { contains: query, mode: "insensitive" } }, { email: { contains: query, mode: "insensitive" } }] } } : {}, include: { user: { select: { name: true, email: true } } }, orderBy: [{ active: "desc" }, { user: { name: "asc" } }] });
  const roleOptions = Object.entries(ATLAS_STAFF_ROLES).map(([key, role]) => <option key={key} value={key}>{role.name}</option>);
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-semibold tracking-tight">Atlas team</h2><p className="mt-2 max-w-2xl text-sm text-slate-500">Atlas Owners, Administrators and Employees currently have full platform access and full permissions in the company they open. Customers cannot grant this access.</p></div><CreateDialog title="Add Atlas staff" label="Add Atlas employee"><CredentialForm action={createAtlasStaff} label="Create staff access"><label className="block text-xs">Full name<input name="name" required maxLength={100} className={input} /></label><label className="block text-xs">Email<input name="email" required type="email" maxLength={254} className={input} /></label><label className="block text-xs">Atlas role<select name="staffRole" defaultValue="EMPLOYEE" className={input}>{roleOptions}</select></label><label className="flex items-start gap-2 text-xs text-slate-600"><input type="checkbox" name="existingAccount" className="mt-0.5" />If this email already exists, grant that existing person full Atlas staff access. They keep their password.</label><label className="block text-xs">Your administrator password<input name="currentPassword" type="password" required autoComplete="current-password" className={input} /></label><p className="text-xs text-slate-500">New staff receive a single-use setup code. Their internal workspace has no customer ERP roles. Opening a company is explicit and audited.</p></CredentialForm></CreateDialog></div>
    <div className="grid gap-3 sm:grid-cols-3">{Object.entries(ATLAS_STAFF_ROLES).map(([key, role]) => <div key={key} className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-sm font-semibold">{role.name}</h3><p className="mt-2 text-xs leading-relaxed text-slate-500">{role.description}</p></div>)}</div>
    <form className="flex gap-3"><input name="q" aria-label="Search Atlas staff" defaultValue={query} placeholder="Find an Atlas employee…" className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-white p-3 text-sm" /><button className="rounded-xl bg-slate-900 px-5 text-sm text-white">Search</button></form>
    <div className="space-y-3">{people.map(person => <details key={person.userId} className="rounded-2xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer text-sm"><span className="font-semibold">{person.user.name}</span>{person.userId === session.userId && <span className="ml-2 text-xs text-slate-400">You</span>}<span className="ml-3 text-xs text-slate-500">{person.role} · {person.active ? "Active" : "Staff access suspended"}</span><p className="mt-2 break-all text-xs text-slate-500">{person.user.email}</p></summary>{person.userId === session.userId ? <p className="mt-5 text-xs text-slate-500">Another Atlas administrator must change your own staff access. Change your password in My work.</p> : <div className="mt-6 grid items-start gap-6 border-t border-slate-100 pt-6 lg:grid-cols-3"><ActionForm action={updateAtlasStaff} label="Save staff access"><input name="userId" type="hidden" value={person.userId} /><label className="block text-xs">Atlas role<select name="staffRole" defaultValue={person.role} className={input}>{roleOptions}</select></label><label className="block text-xs">Staff status<select name="status" defaultValue={person.active ? "ACTIVE" : "SUSPENDED"} className={input}><option value="ACTIVE">Active</option><option value="SUSPENDED">Suspend staff access</option></select></label><label className="block text-xs">Your administrator password<input name="currentPassword" type="password" required autoComplete="current-password" className={input} /></label><p className="text-xs text-slate-500">Changes revoke all of their current sessions. The last active Owner is protected.</p></ActionForm><ActionForm action={saveAtlasStaffProfile} label="Save staff profile"><input name="userId" type="hidden" value={person.userId} /><label className="block text-xs">Full name<input name="name" required maxLength={100} defaultValue={person.user.name} className={input} /></label><label className="block text-xs">Email<input name="email" type="email" required maxLength={254} defaultValue={person.user.email} className={input} /></label><label className="block text-xs">Your administrator password<input name="currentPassword" type="password" required autoComplete="current-password" className={input} /></label></ActionForm>{person.active && <CredentialForm action={issueAtlasStaffRecovery} label="Issue staff recovery code"><input name="userId" type="hidden" value={person.userId} /><h3 className="text-sm font-semibold">Password recovery</h3><p className="text-xs text-slate-500">This resets the staff identity across all workspaces. The person chooses a new password with a single-use code.</p><label className="block text-xs">Your administrator password<input name="currentPassword" type="password" required autoComplete="current-password" className={input} /></label></CredentialForm>}</div>}</details>)}{!people.length && <p className="p-6 text-sm text-slate-500">No staff match this search.</p>}</div>
  </div>;
}
