import { db } from "@/core/db/client";
import { timeSeries } from "@/core/analytics/buckets";
import type { AnalyticsProvider } from "@/core/analytics/types";
import { assertCapability } from "@/core/permissions/check";

export const marketingAnalytics: AnalyticsProvider = [
  { id: "marketing.campaign.count", name: "Marketing campaigns", subject: "Marketing", definition: "Campaigns created in the selected period, grouped by current status. Counts initiatives, not deliveries or revenue.", grain: "One campaign", capability: "marketing.campaign.read", href: "/marketing/campaigns", snapshot: false, query: async (session, since) => { assertCapability(session, "marketing.campaign.read"); const rows = await db.marketingCampaign.groupBy({ by: ["status"], where: { organisationId: session.organisationId, ...(since ? { createdAt: { gte: since } } : {}) }, _count: { _all: true } }); return rows.map((row) => ({ label: row.status.replaceAll("_", " "), value: row._count._all })); } },
  { id: "marketing.lead.count", name: "Marketing qualified leads", subject: "Marketing", definition: "Recorded qualified leads, grouped by current sales feedback status. Not accepted pipeline or revenue.", grain: "One qualified contact", capability: "marketing.lead.read", href: "/marketing/leads", snapshot: false, query: async (session, since) => { assertCapability(session, "marketing.lead.read"); const rows = await db.marketingLead.groupBy({ by: ["status"], where: { organisationId: session.organisationId, ...(since ? { createdAt: { gte: since } } : {}) }, _count: { _all: true } }); return rows.map((row) => ({ label: row.status.replaceAll("_", " "), value: row._count._all })); } },
  { id: "marketing.campaign.trend", name: "Campaigns over time", subject: "Marketing", definition: "Campaigns created in the selected period, by week or by month on longer ranges. Latest 8,000 campaigns. Counts initiatives, not revenue.", grain: "One campaign", capability: "marketing.campaign.read", href: "/marketing/campaigns", snapshot: false, shape: "trend", query: async (session, since) => { assertCapability(session, "marketing.campaign.read"); const rows = await db.marketingCampaign.findMany({ where: { organisationId: session.organisationId, ...(since ? { createdAt: { gte: since } } : {}) }, select: { createdAt: true }, orderBy: { createdAt: "desc" }, take: 8000 }); return timeSeries(rows.map((row) => row.createdAt), since); } },
];
