import type {Session} from '@/core/auth/session';
import {MODEL_FIELDS} from './model-metadata';
export type ModelName=keyof typeof MODEL_FIELDS;
type Scope=Record<string,unknown>;
const capabilities:Record<ModelName,string[]>={
 Organisation:['core.profile.self'],User:['core.profile.self'],Membership:['core.profile.self'],Role:['core.roles.manage','core.users.manage'],RoleOnMembership:['core.roles.manage','core.users.manage'],ModuleState:['core.profile.self'],
 Party:['customers.read'],CustomerTradingLink:['customers.commercial.read','sales.order.read','sales.quote.read'],Contact:['customers.read'],CommunicationDestination:['customers.read'],Address:['customers.read'],CustomerCommercialSettings:['customers.commercial.read','sales.order.read','sales.quote.read'],PaymentTerm:['customers.read','sales.order.read','sales.quote.read'],CustomerCreditProfile:['customers.credit.read','sales.order.read','sales.quote.read'],TaxRegistration:['customers.tax.read'],BankAccount:['customers.bank.read'],DirectDebitMandate:['customers.bank.read'],Document:['customers.documents.read'],Note:['customers.read'],AuditEntry:['core.audit.read'],Activity:['customers.read'],
 Product:['core.products.read','sales.order.read','sales.quote.read'],CustomerProduct:['customers.commercial.read','sales.order.read','sales.quote.read'],PriceList:['core.pricing.read','sales.order.read','sales.quote.read'],PriceListEntry:['core.pricing.read','sales.order.read','sales.quote.read'],SalesTeam:['sales.opportunity.read'],SalesTeamMember:['sales.opportunity.read'],Pipeline:['sales.opportunity.read'],PipelineStage:['sales.opportunity.read'],LossReason:['sales.opportunity.read'],OpportunityStakeholder:['sales.opportunity.read'],OpportunityMilestone:['sales.opportunity.read'],OpportunityChangeEvent:['sales.opportunity.read'],Opportunity:['sales.opportunity.read'],Prospect:['sales.prospect.read'],SalesActivity:['sales.activity.manage','sales.opportunity.read','sales.prospect.read'],Quote:['sales.quote.read'],QuoteLine:['sales.quote.read'],SalesOrder:['sales.order.read'],SalesOrderLine:['sales.order.read'],OrderHold:['sales.order.read'],OrderChangeEvent:['sales.order.read'],OrderApproval:['sales.order.read'],Project:['projects.read'],ChatMessage:['core.chat.read'],Dashboard:['sales.opportunity.read','sales.report.read'],Warehouse:['stock.read'],InventoryBalance:['stock.read'],InventoryMovement:['stock.read'],Kpi:['kpis.read'],KpiUpdate:['kpis.read'],ProjectTask:['projects.read'],Meeting:['projects.read'],PlatformAdministrator:['atlas.companies.manage'],SalesQuotationTemplate:['sales.quote.read'],SalesOrderRevision:['sales.order.read'],DomainOutbox:['core.outbox.read'],SalesSavedView:['sales.order.read','sales.quote.read'],SalesWorkingDraft:['sales.order.create','sales.quote.create'],
 Employee:['people.employee.read'],EmployeeTask:['people.onboarding.manage','people.offboarding.manage'],Appraisal:['people.appraisal.read'],OneToOne:['people.one_to_one.read'],AbsenceRecord:['people.absence.read'],RotaShift:['people.rota.read'],PayrollRun:['people.payroll.read'],Payslip:['people.payroll.read']};
export const PARENT_SCOPE:Partial<Record<ModelName,string>>={Contact:'party',CommunicationDestination:'party',Address:'party',CustomerCommercialSettings:'party',CustomerCreditProfile:'party',TaxRegistration:'party',BankAccount:'party',DirectDebitMandate:'party',Note:'party',CustomerProduct:'party',PriceListEntry:'priceList',SalesTeamMember:'team',PipelineStage:'pipeline',OpportunityStakeholder:'opportunity',OpportunityMilestone:'opportunity',OpportunityChangeEvent:'opportunity',QuoteLine:'quote',SalesOrderLine:'order',OrderHold:'order',OrderChangeEvent:'order',OrderApproval:'order',SalesOrderRevision:'order',KpiUpdate:'kpi',RoleOnMembership:'membership'};
export function canReadModel(session:Session,model:ModelName){return capabilities[model]?.some(c=>session.capabilities.has(c))??false;}
export function modelScope(session:Session,model:ModelName):Scope{
 const organisationId=session.organisationId;
 if(model==='Organisation')return session.capabilities.has('atlas.companies.manage')?{}:{id:organisationId};
 if(model==='User')return {memberships:{some:{organisationId}}};
 if(model==='PlatformAdministrator')return {userId:session.userId};
 const parent=PARENT_SCOPE[model];const scope:Scope=parent?{[parent]:{organisationId}}:{organisationId};
 if(model==='SalesSavedView'||model==='SalesWorkingDraft'){scope.ownerUserId=session.userId;scope.mode={in:['order','quote'].filter(mode=>session.capabilities.has(`sales.${mode}.${model==='SalesWorkingDraft'?'create':'read'}`))};}
 if(model==='Note'&&!session.capabilities.has('customers.restricted_notes.read'))scope.restricted=false;
 return scope;
}
export function deniedScalar(session:Session,model:ModelName,field:string){if(model==='User'&&field==='passwordHash')return true;if(model==='CustomerCreditProfile'&&!session.capabilities.has('customers.credit.read')&&!['id','partyId','paymentTermId'].includes(field))return true;if(model==='BankAccount'&&['accountNumber','iban','sortCode'].includes(field))return true;return false;}
export function resolveModel(delegate:string):ModelName{const model=(Object.keys(MODEL_FIELDS) as ModelName[]).find(name=>name[0].toLowerCase()+name.slice(1)===delegate);if(!model)throw new Error('FORBIDDEN: unsupported data model.');return model;}
