import {goalWhere,planWhere as goalPlanWhere} from '@/modules/kpis/services/access';
import {planWhere} from '@/modules/plan/domain/access';
import {policyAudiences} from '@/core/permissions/hr-access';
import {echoMentionScope,echoNoteScope} from '@/core/audit/scope';
import {serviceCaseScope,serviceTicketScope} from '@/core/permissions/service-access';
import {projectScope,taskScope,documentScope,workAuditScope,meetingScope} from '@/core/permissions/work-access';
import type {Session} from '@/core/auth/session';
import {MODEL_FIELDS} from './model-metadata';
export type ModelName=keyof typeof MODEL_FIELDS;
type Scope=Record<string,unknown>;
const capabilities:Partial<Record<ModelName,string[]>>={
 BusinessPlan:['plan.read'],PlanVersion:['plan.read'],PlanMeasure:['plan.read'],PlanCell:['plan.read'],PlanAssumption:['plan.read'],PlanDriver:['plan.read'],PlanBlock:['plan.read'],PlanGoal:['plan.read'],PlanInitiative:['plan.read'],PlanAction:['plan.read'],PlanRisk:['plan.read'],PlanDependency:['plan.read'],PlanDecision:['plan.read'],PlanComment:['plan.read'],PlanReview:['plan.read'],PlanUpdate:['plan.read'],PlanLens:['plan.read'],PlanModelLink:['plan.read'],PlanSourceLink:['plan.read'],PlanShare:['plan.read'],PlanNote:['plan.read'],
 MarketingProfile:['marketing.profile.read'], MarketingPermission:['marketing.consent.view'], MarketingSuppression:['marketing.consent.view'], MarketingEvent:['marketing.profile.read'], MarketingAudience:['marketing.audience.read'], MarketingAudienceMember:['marketing.audience.read'], MarketingCampaign:['marketing.campaign.read'], MarketingContent:['marketing.content.read'], MarketingMessage:['marketing.email.read'], MarketingSendJob:['marketing.email.read'], MarketingDelivery:['marketing.email.read'], MarketingJourney:['marketing.journey.read'], MarketingJourneyVersion:['marketing.journey.read'], MarketingJourneyEnrolment:['marketing.journey.read'], MarketingLead:['marketing.lead.read'], MarketingProgram:['marketing.program.read'], MarketingTouch:['marketing.report.read'], MarketingExperiment:['marketing.experiment.manage'], MarketingExperimentAssignment:['marketing.experiment.manage'],
 ServiceCase:["service.case.read"],ServiceEntry:["service.case.read"],ServiceTicket:["service.ticket.read"],ServiceQueue:["service.ticket.read"],ServiceQueueMember:["service.ticket.read"],ServiceLink:["service.case.read"],
 QualitySpecification:["quality.spec.read"],QualityCharacteristic:["quality.spec.read"],QualityControlPoint:["quality.control_point.read"],QualityInspection:["quality.check.execute","quality.today.read"],QualityMeasurement:["quality.check.execute","quality.today.read"],QualityHold:["quality.hold.read"],NonConformance:["quality.ncr.read"],NonConformanceAction:["quality.ncr.read"],QualitySequence:["quality.spec.manage","quality.control_point.manage"],
 ProjectTemplate:['projects.read'],ProjectAutomationRule:['projects.read'],ProjectAutomationExecution:['projects.read'],ProjectTimer:['projects.read'],ProjectPreference:['projects.read'],ProjectFile:['projects.read'],ProjectProperty:['projects.read'],ProjectPropertyValue:['projects.read'],
 ProjectMember:['projects.read'],ProjectMilestone:['projects.read'],ProjectChecklistItem:['projects.read'],ProjectDependency:['projects.read'],ProjectDocument:['projects.read'],ProjectDocumentRevision:['projects.read'],ProjectDecision:['projects.read'],ProjectUpdate:['projects.read'],ProjectRisk:['projects.read'],ProjectApproval:['projects.read'],ProjectRequest:['projects.read'],ProjectComment:['projects.read'],ProjectTimeEntry:['projects.read'],ProjectPersonalPlan:['projects.read'],ProjectInboxItem:['projects.read'],ProjectSavedView:['projects.read'],ProjectPortfolio:['projects.read'],ProjectPortfolioLink:['projects.read'],ProjectBaseline:['projects.read'],ProjectBudgetLine:['projects.read'],ProjectWorkLink:['projects.read'],
 WorkTeam:['planning.demand.read','projects.read','core.users.manage','people.team.manage'],WorkTeamMember:['planning.demand.read','projects.read','core.users.manage','people.team.manage'],ProductionPlan:['planning.demand.read'],ProductionPlanLine:['planning.demand.read'],
 Organisation:['core.profile.self'],User:['core.profile.self'],Membership:['core.profile.self'],Role:['core.roles.manage','core.users.manage'],RoleOnMembership:['core.roles.manage','core.users.manage'],ModuleState:['core.profile.self'],
 Party:['customers.read'],CustomerTradingLink:['customers.commercial.read','sales.order.read','sales.quote.read'],Contact:['customers.read'],CommunicationDestination:['customers.read'],Address:['customers.read'],CustomerCommercialSettings:['customers.commercial.read','sales.order.read','sales.quote.read'],PaymentTerm:['customers.read','sales.order.read','sales.quote.read'],CustomerCreditProfile:['customers.credit.read','sales.order.read','sales.quote.read'],TaxRegistration:['customers.tax.read'],BankAccount:['customers.bank.read'],DirectDebitMandate:['customers.bank.read'],Document:['customers.documents.read'],Note:['customers.read'],AuditEntry:['core.audit.read'],EchoNote:['echo.read'],EchoMention:['echo.read'],Activity:['customers.read'],
 Product:['stock.read','core.products.read','sales.order.read','sales.quote.read'],ProductDefinition:['core.products.read'],ProductBomLine:['core.products.read'],ProductOperation:['core.products.read'],ProductCategory:['core.products.read','stock.read'],ProductLink:['core.products.read','stock.read'],CustomerProduct:['customers.commercial.read','sales.order.read','sales.quote.read'],PriceList:['core.pricing.read','sales.order.read','sales.quote.read'],PriceListEntry:['core.pricing.read','sales.order.read','sales.quote.read'],CommercialAgreement:['core.pricing.read','customers.commercial.read','sales.order.read','sales.quote.read'],AgreementPrice:['core.pricing.read','customers.commercial.read','sales.order.read','sales.quote.read'],SalesTeam:['sales.opportunity.read'],SalesTeamMember:['sales.opportunity.read'],Pipeline:['sales.opportunity.read'],PipelineStage:['sales.opportunity.read'],LossReason:['sales.opportunity.read'],OpportunityStakeholder:['sales.opportunity.read'],OpportunityMilestone:['sales.opportunity.read'],OpportunityChangeEvent:['sales.opportunity.read'],Opportunity:['sales.opportunity.read'],Prospect:['sales.prospect.read'],CrmIndustry:['sales.prospect.read','sales.opportunity.read'],SalesActivity:['sales.activity.manage','sales.opportunity.read','sales.prospect.read'],Quote:['sales.quote.read'],QuoteLine:['sales.quote.read'],SalesAgreement:['sales.order.read','sales.quote.read'],SalesAgreementLine:['sales.order.read','sales.quote.read'],SalesOrder:['sales.order.read'],SalesOrderLine:['sales.order.read'],OrderHold:['sales.order.read'],OrderChangeEvent:['sales.order.read'],OrderApproval:['sales.order.read'],Project:['projects.read'],ChatConversation:['core.chat.read'],ChatParticipant:['core.chat.read'],ChatMessage:['core.chat.read'],ChatLink:['core.chat.read'],Dashboard:['sales.opportunity.read','sales.report.read','analytics.dashboard.read'],Site:['stock.read'],Warehouse:['stock.read'],InventoryBalance:['stock.read'],InventoryMovement:['stock.read'],InternalMove:['stock.read'],Kpi:['kpis.read','people.conduct.read','people.conduct.manage','core.profile.self'],KpiUpdate:['kpis.read','people.conduct.read','people.conduct.manage','core.profile.self'],PerformancePlan:['people.conduct.read','people.conduct.manage','kpis.read','core.profile.self'],PerformanceReview:['people.conduct.read','people.conduct.manage','kpis.read','core.profile.self'],ProjectTask:['projects.read'],Meeting:['projects.read'],PlatformAdministrator:['atlas.companies.manage'],SalesQuotationTemplate:['sales.quote.read'],InvoiceDocumentTemplate:['sales.order.read','sales.quote.read'],CustomerInvoiceTemplate:['customers.commercial.read','sales.order.read','sales.quote.read'],SalesProforma:['sales.order.read'],SalesOrderRevision:['sales.order.read'],DomainOutbox:['core.outbox.read'],SalesSavedView:['sales.order.read','sales.quote.read'],SalesWorkingDraft:['sales.order.create','sales.quote.create'],
 HrVacancy:['people.employee.manage'],HrApplication:['people.employee.manage'],EmployeeTraining:['people.employee.read','core.profile.self'],
 EmployeeHistoryEvent:['people.employee.read'],EmployeeDocument:['people.employee.read'],Employee:['people.employee.read'],EmployeeTask:['people.onboarding.manage','people.offboarding.manage'],Appraisal:['people.appraisal.read','core.profile.self'],AppraisalTemplate:['people.appraisal.read'],OneToOne:['people.one_to_one.read','core.profile.self'],OneToOneTemplate:['people.one_to_one.read'],AbsenceRecord:['people.absence.read','people.holiday.self','people.team.manage','core.profile.self'],RotaShift:['people.rota.read','scheduling.read'],SchedulingWorkType:['scheduling.read','scheduling.manage'],SchedulingDemand:['scheduling.manage'],SchedulingCalendarRule:['scheduling.manage','scheduling.read'],PayrollRun:['payroll.run.read'],Payslip:['payroll.run.read','payroll.payslip.self','core.profile.self'],PayrollSettings:['payroll.settings.manage','payroll.run.read'],EmployeeTaxYearToDate:['payroll.run.read'],StatutoryPayRecord:['payroll.run.read'],PayrollDocument:['payroll.run.read','payroll.payslip.self','core.profile.self'],ExpenseClaim:['people.expense.read','core.profile.self'],HrPolicy:['people.policy.read','people.policy.manage','people.employee.manage'],
 StockLocation:['stock.read'],StockLot:['stock.read'],StockSerial:['stock.read'],StockPosition:['stock.read'],StockReservation:['stock.read'],StockDiscrepancy:['stock.manage'],
 ManufacturingWorkCentre:['manufacturing.order.read'],ManufacturingResource:['manufacturing.order.read'],ManufacturingOrder:['manufacturing.order.read'],ManufacturingWorkOrder:['manufacturing.order.read'],ManufacturingShift:['manufacturing.schedule.read'],ManufacturingDemandForecast:['manufacturing.plan.read'],ManufacturingPlanningRun:['manufacturing.plan.read'],ManufacturingSupplySuggestion:['manufacturing.plan.read'],
 SafetyProfile:['safety.today.read'],SafetyCounter:['safety.today.read'],SafetyPlace:['safety.today.read','safety.risk.read'],SafetyMatrix:['safety.risk.read'],SafetyRisk:['safety.risk.read'],SafetyAssessment:['safety.risk.read'],SafetyControl:['safety.risk.read'],SafetyAction:['safety.action.read','safety.today.read'],SafetyIncident:['safety.incident.read','safety.sensitive_incident.read'],SafetyInvestigation:['safety.incident.read','safety.incident.investigate'],SafetyCause:['safety.incident.investigate'],SafetyRiddorDecision:['safety.riddor.review'],SafetyReviewRequest:['safety.risk.read'],SafetyInspectionTemplate:['safety.inspection.execute'],SafetyInspection:['safety.inspection.execute'],SafetyAudit:['safety.audit.execute'],SafetyFinding:['safety.audit.execute'],SafetyPermit:['safety.permit.request','safety.permit.authorise'],SafetyIsolation:['safety.isolation.apply','safety.permit.request'],SafetyIsolationLock:['safety.isolation.apply','safety.permit.request'],SafetyHold:['safety.hold.manage','safety.today.read','safety.equipment.read'],SafetyStatutoryCheck:['safety.equipment.read','safety.statutory.manage','safety.today.read'],SafetySubstance:['safety.coshh.read'],SafetySds:['safety.coshh.read'],SafetyCoshhAssessment:['safety.coshh.read'],SafetyCompetence:['safety.competence.read','safety.today.read'],SafetyDocument:['safety.document.read'],SafetyAcknowledgement:['safety.document.read'],SafetyObligation:['safety.report.read','safety.today.read'],SafetyChange:['safety.change.manage'],SafetyLink:['safety.risk.read','safety.incident.read'],SafetyRecord:['safety.risk.read','safety.today.read','safety.health_surveillance.read'],
 PlannerTeam:['teams.read'],PlannerTeamMember:['teams.read'],PlannerTask:['teams.read'],PlannerCover:['teams.read'],PlannerHandover:['teams.read'],PlannerPlace:['teams.read'],PlannerMoment:['teams.read'],
 LogisticsPolicy:['logistics.fulfilment.read','logistics.policy.manage','core.modules.manage'],LogisticsCounter:['logistics.fulfilment.read'],FulfilmentRequirement:['logistics.fulfilment.read'],FulfilmentLine:['logistics.fulfilment.read'],LogisticsWave:['logistics.pick.read'],WarehouseTask:['logistics.pick.read'],WarehouseTaskLine:['logistics.pick.read'],LogisticsPackage:['logistics.shipment.read'],PackageContent:['logistics.shipment.read'],Shipment:['logistics.shipment.read'],ShipmentSource:['logistics.shipment.read'],TrackingEvent:['logistics.shipment.read'],LogisticsLoad:['logistics.shipment.read'],LoadStop:['logistics.shipment.read'],ExpectedReceipt:['logistics.receipt.execute'],ReceiptLine:['logistics.receipt.execute'],ReturnAuthorisation:['logistics.return.read'],ReturnLine:['logistics.return.read'],LogisticsOperation:['logistics.fulfilment.read'],CarrierRule:['logistics.dispatch.manage'],LogisticsSavedView:['logistics.fulfilment.read'],LogisticsNote:['logistics.fulfilment.read'],HandlingUnitType:['logistics.fulfilment.read']};
export const PARENT_SCOPE:Partial<Record<ModelName,string>>={WorkTeamMember:'team',Contact:'party',CommunicationDestination:'party',Address:'party',CustomerCommercialSettings:'party',CustomerCreditProfile:'party',TaxRegistration:'party',BankAccount:'party',DirectDebitMandate:'party',Note:'party',CustomerProduct:'party',PriceListEntry:'priceList',AgreementPrice:'agreement',SalesTeamMember:'team',PipelineStage:'pipeline',OpportunityStakeholder:'opportunity',OpportunityMilestone:'opportunity',OpportunityChangeEvent:'opportunity',QuoteLine:'quote',SalesAgreementLine:'agreement',SalesOrderLine:'order',OrderHold:'order',OrderChangeEvent:'order',OrderApproval:'order',SalesOrderRevision:'order',KpiUpdate:'kpi',RoleOnMembership:'membership',QualityCharacteristic:'specification',QualityMeasurement:'inspection',NonConformanceAction:'ncr'};
export function canReadModel(session:Session,model:ModelName){return capabilities[model]?.some(c=>session.capabilities.has(c))??false;}
function allowed(session:Session,...names:string[]){return names.some(name=>session.capabilities.has(name));}
function ownEmployee(session:Session){return {organisationId:session.organisationId,userId:session.userId};}
export function modelScope(session:Session,model:ModelName):Scope{
 const organisationId=session.organisationId;
 if(model==='BusinessPlan'||(model.startsWith('Plan')&&!model.startsWith('Planner'))){
  const planScope=planWhere(session);
  const versionScope=session.capabilities.has('plan.scenario.share')||session.capabilities.has('plan.approve')?{organisationId}:{organisationId,OR:[{kind:{not:'scenario'}},{shared:true},{ownerUserId:session.userId}]};
  if(model==='BusinessPlan')return planScope;
  if(model==='PlanVersion')return {...versionScope,plan:planScope};
  if(model==='PlanLens')return {organisationId,plan:planScope,OR:[{ownerUserId:null},{ownerUserId:session.userId}]};
  if(model==='PlanCell'||model==='PlanAssumption'||model==='PlanDriver')return {organisationId,plan:planScope,version:versionScope};
  return {organisationId,plan:planScope};
 }
 if(model.startsWith("Marketing"))return {organisationId,organisation:{moduleStates:{some:{moduleId:"marketing",enabled:true,entitled:true}}}};
 if(["LogisticsPolicy","LogisticsCounter","FulfilmentRequirement","FulfilmentLine","LogisticsWave","WarehouseTask","WarehouseTaskLine","LogisticsPackage","PackageContent","Shipment","ShipmentSource","TrackingEvent","LogisticsLoad","LoadStop","ExpectedReceipt","ReceiptLine","ReturnAuthorisation","ReturnLine","LogisticsOperation","CarrierRule","LogisticsSavedView","LogisticsNote","HandlingUnitType"].includes(model))return {organisationId,organisation:{moduleStates:{some:{moduleId:"logistics",enabled:true,entitled:true}}},...(model==="LogisticsSavedView"?{OR:[{scope:"COMPANY"},{ownerUserId:session.userId}]}:{})};
 if(model==='ServiceCase')return serviceCaseScope(session) as Scope;
 if(model==='ServiceTicket')return serviceTicketScope(session) as Scope;
 if(model==='ServiceEntry'||model==='ServiceLink')return {organisationId,case:serviceCaseScope(session)};
 if(model==='ServiceQueue')return {organisationId,organisation:{moduleStates:{some:{moduleId:'service',enabled:true,entitled:true}}},...(!session.capabilities.has('service.case.read')?{members:{some:{organisationId,userId:session.userId}}}:{})};
 if(model==='ServiceQueueMember')return {organisationId,organisation:{moduleStates:{some:{moduleId:'service',enabled:true,entitled:true}}},...(!session.capabilities.has('service.case.read')?{userId:session.userId}:{})};
 if(model==='AuditEntry')return workAuditScope(session) as Scope;
 if(model==='EchoNote')return echoNoteScope(session) as Scope;
 if(model==='EchoMention')return echoMentionScope(session) as Scope;
 if(model==='ProjectTemplate'||model==='ProjectPortfolio')return {organisationId,ownerUserId:session.userId};
 if(model==='ProjectTimer'||model==='ProjectPreference')return {organisationId,userId:session.userId,...(model==='ProjectTimer'?{task:taskScope(session)}:{project:projectScope(session)})};
 if(['ProjectAutomationRule','ProjectFile','ProjectProperty'].includes(model))return {organisationId,project:projectScope(session)};
 if(model==='ProjectAutomationExecution')return {organisationId,rule:{organisationId,project:projectScope(session)}};
 if(model==='ProjectPropertyValue')return {organisationId,task:taskScope(session),property:{organisationId,project:projectScope(session)}};
 if(model==='ChatConversation')return {organisationId,kind:{in:['DIRECT','GROUP']},participants:{some:{organisationId,userId:session.userId}}};
 if(model==='ChatParticipant')return {organisationId,conversation:{organisationId,kind:{in:['DIRECT','GROUP']},participants:{some:{organisationId,userId:session.userId}}}};
 if(model==='ChatLink')return {organisationId,message:{organisationId,conversation:{organisationId,kind:{in:['DIRECT','GROUP']},participants:{some:{organisationId,userId:session.userId}}}}};
 if(model==='ChatMessage')return {organisationId,conversation:{organisationId,kind:{in:['DIRECT','GROUP']},participants:{some:{organisationId,userId:session.userId}}}};
 if(model==='Project')return projectScope(session) as Scope;
 if(model==='Meeting'){const visible=meetingScope(session);return session.capabilities.has('projects.manage')?visible:{AND:[visible,{OR:[{organiserUserId:session.userId},{attendeeUserIds:{has:session.userId}}]}]}};
 if(model==='ProjectTask')return taskScope(session) as Scope;
 if(model==='ProjectDocument')return documentScope(session) as Scope;
 if(model==='ProjectDocumentRevision')return {organisationId,document:documentScope(session)};
 if(['ProjectMember','ProjectMilestone','ProjectDecision','ProjectUpdate','ProjectRisk','ProjectApproval','ProjectRequest','ProjectBaseline','ProjectBudgetLine','ProjectPortfolioLink'].includes(model))return {organisationId,project:projectScope(session)};
 if(model==='ProjectDependency')return {organisationId,predecessor:taskScope(session),successor:taskScope(session)};
 if(model==='ProjectChecklistItem'||model==='ProjectTimeEntry')return {organisationId,task:taskScope(session)};
 if(model==='ProjectPersonalPlan')return {organisationId,userId:session.userId,task:taskScope(session)};
 if(model==='ProjectSavedView')return {organisationId,userId:session.userId};
 if(['ProjectComment','ProjectWorkLink','ProjectInboxItem'].includes(model))return {organisationId,...(model==='ProjectInboxItem'?{userId:session.userId}:{}),AND:[{OR:[{projectId:null},{project:projectScope(session)}]},{OR:[{taskId:null},{task:taskScope(session)}]}]};
 if(model==='HrVacancy'||model==='HrApplication')return {organisationId,organisation:{moduleStates:{some:{moduleId:'people',enabled:true,entitled:true}}}};
 if(model==='EmployeeTraining')return {organisationId,employee:session.capabilities.has('people.employee.read')?{organisationId}:ownEmployee(session),organisation:{moduleStates:{some:{moduleId:'people',enabled:true,entitled:true}}}};
 if(model==='HrPolicy')return {organisationId,audience:{in:[...policyAudiences(session)]},...(session.capabilities.has('people.policy.manage')?{}:{status:'PUBLISHED'})};
 if(model==='Kpi')return goalWhere(session);
 if(model==='PerformancePlan')return goalPlanWhere(session);
 if(model==='KpiUpdate')return {kpi:{AND:[goalWhere(session),{OR:[{visibility:'PRIVATE'},{metricId:''}]}]}};
 if(model==='PerformanceReview')return {plan:goalPlanWhere(session)};
 if(model==='AbsenceRecord')return allowed(session,'people.absence.read','people.absence.manage','people.employee.manage')?{organisationId}:session.capabilities.has('people.team.manage')?{organisationId,employee:{organisationId,OR:[{userId:session.userId},{manager:{organisationId,userId:session.userId}}]}}:{organisationId,employee:ownEmployee(session)};
 if(model==='Payslip'||model==='PayrollDocument')return allowed(session,'payroll.run.read','payroll.run.manage')?{organisationId}:{organisationId,employee:ownEmployee(session)};
 if(model==='EmployeeTaxYearToDate'||model==='StatutoryPayRecord')return allowed(session,'payroll.run.read','payroll.run.manage')?{organisationId}:{organisationId,employee:ownEmployee(session)};
 if(model==='ExpenseClaim')return allowed(session,'people.expense.read','people.expense.approve','people.employee.manage')?{organisationId}:{organisationId,employee:ownEmployee(session)};
 if(model==='Appraisal')return allowed(session,'people.appraisal.read','people.appraisal.manage','people.employee.manage')?{organisationId}:{organisationId,OR:[{reviewerUserId:session.userId},{employee:ownEmployee(session)}]};
 if(model==='OneToOne')return allowed(session,'people.one_to_one.read','people.one_to_one.manage','people.employee.manage')?{organisationId}:{organisationId,OR:[{managerUserId:session.userId},{employee:ownEmployee(session)}]};
 if(model==='RotaShift')return allowed(session,'people.rota.read','people.rota.manage','scheduling.manage','people.team.manage')?{organisationId}:{organisationId,employee:ownEmployee(session)};
 if(model==='Organisation')return session.capabilities.has('atlas.companies.manage')?{}:{id:organisationId};
 if(model==='User')return {memberships:{some:{organisationId}}};
 if(model==='PlatformAdministrator')return {userId:session.userId};
 const parent=PARENT_SCOPE[model];const scope:Scope=parent?{[parent]:{organisationId}}:{organisationId};
 if(model==='Dashboard')scope.userId=session.userId;
 if(model==='SalesSavedView'||model==='SalesWorkingDraft'){scope.ownerUserId=session.userId;scope.mode={in:['order','quote'].filter(mode=>session.capabilities.has(`sales.${mode}.${model==='SalesWorkingDraft'?'create':'read'}`))};}
 if(model==='Note'&&!session.capabilities.has('customers.restricted_notes.read'))scope.restricted=false;
 if(model==='SafetyIncident'&&!session.capabilities.has('safety.sensitive_incident.read'))scope.confidential=false;
 if(model==='SafetyInvestigation'&&!session.capabilities.has('safety.sensitive_incident.read'))scope.incident={organisationId,confidential:false};
 if(model==='SafetyCause'&&!session.capabilities.has('safety.sensitive_incident.read'))scope.investigation={organisationId,incident:{organisationId,confidential:false}};
 if(model==='SafetyRiddorDecision'&&!session.capabilities.has('safety.sensitive_incident.read'))scope.incident={organisationId,confidential:false};
 if(model==='SafetyRecord'&&!session.capabilities.has('safety.health_surveillance.read')&&!session.capabilities.has('safety.sensitive_incident.read'))scope.OR=[{sensitive:false},{ownerUserId:session.userId}];
 return scope;
}
export function deniedScalar(session:Session,model:ModelName,field:string){if(model==='Shipment'&&['estimatedCostMinor','actualCostMinor','customerChargeMinor'].includes(field))return !session.capabilities.has('logistics.cost.read');if(model==='ProjectFile'&&field==='content')return true;if(model==='HrPolicy'&&field==='content')return true;if(model==='Employee'&&field==='notes')return !session.capabilities.has('people.employee.manage');if(model==='Employee'&&['hourlyRateMinorUnits','payFrequency','niCategory','studentLoanPlan','pensionOptOut','postgraduateLoan','annualSalaryMinorUnits','taxCode','niNumber','bankAccountName','bankSortCode','bankAccountNumber'].includes(field))return !session.capabilities.has('payroll.run.read')&&!session.capabilities.has('payroll.run.manage')&&!session.capabilities.has('payroll.employee.manage');if(model==='AbsenceRecord'&&(field==='notes'||field==='reason'))return !allowed(session,'people.absence.read','people.absence.manage','people.employee.manage');if(model==='User'&&field==='passwordHash')return true;if(model==='CustomerCreditProfile'&&!session.capabilities.has('customers.credit.read')&&!['id','partyId','paymentTermId'].includes(field))return true;if(model==='BankAccount'&&['accountNumber','iban','sortCode'].includes(field))return true;return false;}
export function resolveModel(delegate:string):ModelName{const model=(Object.keys(MODEL_FIELDS) as ModelName[]).find(name=>name[0].toLowerCase()+name.slice(1)===delegate);if(!model)throw new Error('FORBIDDEN: unsupported data model.');return model;}
