import { db } from "@/core/db/client";
import { timeSeries } from "@/core/analytics/buckets";
import type { AnalyticsProvider } from "@/core/analytics/types";
import { assertCapability } from "@/core/permissions/check";
const opportunity = "sales.opportunity.read";
const prospect = "sales.prospect.read";
export const crmAnalytics: AnalyticsProvider = [
{id:"crm.opportunities",name:"Opportunities",subject:"CRM",definition:"Current opportunities by outcome. Counts opportunities. Values are on the separate pipeline-value measure so currencies stay apart.",grain:"One opportunity",capability:opportunity,href:"/crm/pipeline",snapshot:true,query:async(session)=>{assertCapability(session,opportunity);const rows=await db.opportunity.groupBy({by:["status"],where:{organisationId:session.organisationId},_count:{_all:true}});return rows.map(r=>({label:String(r.status).replaceAll("_"," "),value:r._count._all}));}},
{id:"crm.pipeline.stages",name:"Open pipeline by stage",subject:"CRM",definition:"Open opportunities by pipeline stage. Counts opportunities, not value.",grain:"One opportunity",capability:opportunity,href:"/crm/pipeline",snapshot:true,query:async(session)=>{assertCapability(session,opportunity);const [rows,stages]=await Promise.all([db.opportunity.groupBy({by:["stageId"],where:{organisationId:session.organisationId,status:"OPEN"},_count:{_all:true}}),db.pipelineStage.findMany({where:{pipeline:{organisationId:session.organisationId}},select:{id:true,name:true}})]);return rows.map(row=>({label:stages.find(stage=>stage.id===row.stageId)?.name??"Stage",value:row._count._all}));}},
{id:"crm.pipeline.value",name:"Open pipeline value",subject:"CRM",definition:"Open opportunity value by currency, in minor units. Currencies are never added together.",grain:"One currency",capability:opportunity,href:"/crm/pipeline",snapshot:true,unit:"money",query:async(session)=>{assertCapability(session,opportunity);const rows=await db.opportunity.groupBy({by:["valueCurrency"],where:{organisationId:session.organisationId,status:"OPEN"},_sum:{valueAmount:true}});return rows.map(row=>({label:row.valueCurrency,value:row._sum.valueAmount??0}));}},
{id:"crm.winrate",name:"Win rate",subject:"CRM",definition:"Won opportunities as a percentage of won and lost opportunities closed in the selected period.",grain:"Closed opportunities",capability:opportunity,href:"/crm/forecast",snapshot:false,unit:"percent",query:async(session,since)=>{assertCapability(session,opportunity);const rows=await db.opportunity.findMany({where:{organisationId:session.organisationId,status:{in:["WON","LOST"]},...(since?{actualCloseDate:{gte:since}}:{})},select:{status:true},take:8000});const won=rows.filter(row=>row.status==="WON").length;return [{label:"Win rate",value:rows.length?Math.round(won/rows.length*100):0}];}},
{id:"crm.prospects",name:"New prospects",subject:"CRM",definition:"Prospects created in the selected period, by lifecycle status.",grain:"One prospect",capability:prospect,href:"/crm/prospect",snapshot:false,query:async(session,since)=>{assertCapability(session,prospect);const rows=await db.prospect.groupBy({by:["lifecycleStage"],where:{organisationId:session.organisationId,createdAt:since?{gte:since}:undefined},_count:{_all:true}});return rows.map(r=>({label:String(r.lifecycleStage).replaceAll("_"," "),value:r._count._all}));}},
{id:"crm.prospects.trend",name:"Prospects over time",subject:"CRM",definition:"Prospects created in the selected period, by week or by month on longer ranges. Latest 8,000 prospects.",grain:"One prospect",capability:prospect,href:"/crm/prospect",snapshot:false,shape:"trend",query:async(session,since)=>{assertCapability(session,prospect);const rows=await db.prospect.findMany({where:{organisationId:session.organisationId,...(since?{createdAt:{gte:since}}:{})},select:{createdAt:true},orderBy:{createdAt:"desc"},take:8000});return timeSeries(rows.map(row=>row.createdAt),since);}},
];
