import type { DemandRow } from './engine';
export const REVIEW_GUIDES=[
 {title:'Data refresh',view:'setup',question:'Are we using the right inputs?',checks:['Check the planning months, currency and product scope.','Connect the plans that contain your sales assumptions.','Generate a new working forecast after changing inputs.']},
 {title:'Product review',view:'products',question:'Are the right products included?',checks:['Check new, active and retiring products in the forecast.','Investigate missing product history and unusual demand.','Record any launch or lifecycle assumptions.']},
 {title:'Demand review',view:'demand',question:'What do we expect customers to buy?',checks:['Compare historical baseline, confirmed orders and weighted project demand.','Investigate unusual product-month quantities and record justified overrides.','Agree demand before reducing it to match available supply.']},
 {title:'Supply review',view:'supply',question:'Can we cover that demand?',checks:['Review stock, receipts, production and the safety-stock reserve.','Find uncovered demand and agree an owner for each important gap.','Check material, machine and labour feasibility with Operations separately.']},
 {title:'Financial review',view:'finance',question:'Does the plan meet our financial target?',checks:['Compare forecast revenue with the selected revenue target.','Check selling-price and cost assumptions; unavailable margin is not zero.','Record the financial trade-offs of proposed changes.']},
 {title:'Pre-S&OP',view:'decisions',question:'Which trade-offs need a decision?',checks:['Compare useful scenarios against this working forecast.','Record the chosen option, reason, owner and due date.','Escalate unresolved supply and financial gaps.']},
 {title:'Executive review',view:'decisions',question:'Which plan will the business commit to?',checks:['Confirm the chosen forecast and outstanding commitments.','Agree who will deliver each action and monitor the results.','Approve this exact version, then release its demand to Manufacturing.']},
] as const;
export type ReviewStage={title:string;status:string;owner:string;dueOn:string;versionId?:string};
export function reviewStages(value:unknown):ReviewStage[]{return Array.isArray(value)?value.flatMap(s=>s&&typeof s==='object'&&typeof s.title==='string'?[{title:s.title,status:typeof s.status==='string'?s.status:'open',owner:typeof s.owner==='string'?s.owner:'',dueOn:typeof s.dueOn==='string'?s.dueOn:'',versionId:typeof s.versionId==='string'?s.versionId:undefined}]:[]):[];}
export type GuidedVersion={id:string;kind:string;status:string;sourceRevision:number};
export function cycleGuidance(version:GuidedVersion|null,inputRevision:number,workflow:unknown,rowCount:number,inaccessible=false){
 const stages=reviewStages(workflow),matching=stages.length===REVIEW_GUIDES.length&&stages.every((s,i)=>s.title===REVIEW_GUIDES[i].title&&s.versionId===version?.id),approved=matching?stages.filter(s=>s.status==='approved').length:0;
 if(!version)return {key:inaccessible?'access':'setup',title:inaccessible?'Ask for access to the forecast sources':'Set up your first working forecast',detail:inaccessible?'Your profile cannot read the saved forecast. Orders & Service and the how-to guide remain available.':'Choose the products and connect your sales plans, then generate a working forecast.',view:inaccessible?'service':'setup',approved,ready:false};
 if(version.kind==='scenario')return {key:'scenario',title:'Compare this what-if scenario',detail:'A scenario is a test option. Propose it as a new working forecast before asking for approval.',view:'scenarios',approved:0,ready:false};
 if(version.status==='published')return {key:'published',title:'Your approved demand has been released',detail:'Manufacturing can use this version. Monitor delivery performance and record follow-up actions; refresh when you are ready for a new review.',view:'service',approved,ready:false};
 if(version.sourceRevision!==inputRevision)return {key:'stale',title:'Refresh the forecast after your setup changes',detail:'These results use earlier cycle settings. Generate a new working forecast and review that version.',view:'setup',approved:0,ready:false};
 if(!rowCount)return {key:'empty',title:'Add products before you review this forecast',detail:'This version contains no product demand. Check the product scope, currency and accessible sources in Setup.',view:'setup',approved,ready:false};
 if(!matching)return {key:'other',title:'Open the version linked to the current reviews',detail:'These review records belong to a different working forecast. Select the current version or generate a new one.',view:'reviews',approved,ready:false};
 if(approved<REVIEW_GUIDES.length){const next=stages.findIndex(s=>s.status!=='approved');return {key:'review',title:`Next: ${REVIEW_GUIDES[next].question}`,detail:`${approved} of ${REVIEW_GUIDES.length} reviews recorded for this exact version. Open the review checklist, inspect the evidence, then record your review.`,view:'reviews',approved,ready:false};}
 return {key:version.status==='approved'?'publish':'approve',title:version.status==='approved'?'Release approved demand to Manufacturing':'Approve the agreed working forecast',detail:version.status==='approved'?'Release this approved version when the business is ready to use its monthly demand.':'All seven reviews are recorded. An authorised approver can now commit to this version. Source changes are rechecked when approving and releasing.',view:'reviews',approved,ready:true};
}
/** Never combine unlike units or turn absent supply/cost evidence into a zero. */
export function monthlyBrief(rows:DemandRow[],targets:{periodKey:string;value:number;planId:string;metricKey:string;currency:string}[],targetPlanId:string|null|undefined,currency:string){
 return [...new Set(rows.map(r=>r.period))].sort().map(period=>{
  const selected=rows.filter(r=>r.period===period),unitGroups=[...new Set(selected.map(r=>r.unit))].map(unit=>{const items=selected.filter(r=>r.unit===unit);return {unit,demand:items.reduce((n,r)=>n+r.consensus,0),remaining:items.reduce((n,r)=>n+r.remainingDemand,0),risk:items.every(r=>r.atRisk!==null)?items.reduce((n,r)=>n+r.atRisk!,0):null};});
  const target=targets.find(t=>t.planId===targetPlanId&&t.metricKey==='revenue'&&t.currency===currency&&t.periodKey===period)?.value??null,revenue=selected.reduce((n,r)=>n+r.revenueMinor,0),margin=selected.every(r=>r.marginMinor!==null)?selected.reduce((n,r)=>n+r.marginMinor!,0):null;
  return {period,units:unitGroups,revenue,target,gap:target===null?null:revenue-target,margin,shortfalls:selected.filter(r=>(r.atRisk??0)>0).length};
 });
}
