import Link from 'next/link';
import {redirect} from 'next/navigation';
import {requireSession} from '@/core/auth/session';
import {can} from '@/core/permissions/check';
import {HR_CAPABILITIES as HR} from '@/core/permissions/capabilities';
import {db} from '@/core/db/client';
import {hrPageRestriction,hrAccess,personSelect} from '@/modules/people/services/platform-queries';
import {platformSummary} from '@/modules/people/services/platform-summary';
import {HRRestricted,panelClass} from '@/modules/people/components/platform-ui';
import {ActionForm} from '@/components/ui/action-form';
import {Button} from '@/components/ui/button';
import {completeEmployeeTask} from '../actions';
export default async function HRHome(){const session=await requireSession();if(!can(session,HR.employeeRead))redirect('/people/me');const restriction=await hrPageRestriction(session);if(restriction)return <HRRestricted disabled={restriction==='disabled'}/>;await hrAccess(session);const summary=await platformSummary(session),organisationId=session.organisationId,phases:('ONBOARDING'|'OFFBOARDING')[]=[];if(can(session,HR.onboardingManage))phases.push('ONBOARDING');if(can(session,HR.offboardingManage))phases.push('OFFBOARDING');const [tasks,appraisals,meetings,away]=await Promise.all([
 phases.length?db.employeeTask.findMany({where:{organisationId,phase:{in:phases},completedAt:null,employee:{organisationId,status:{not:'LEFT'}}},include:{employee:{select:personSelect}},orderBy:[{dueDate:'asc'},{createdAt:'asc'}],take:12}):[],
 can(session,HR.appraisalRead)?db.appraisal.findMany({where:{organisationId,status:'SCHEDULED',scheduledAt:{lte:summary.fortnight},employee:{status:{not:'LEFT'}}},include:{employee:{select:personSelect}},orderBy:{scheduledAt:'asc'},take:6}):[],
 can(session,HR.oneToOneRead)?db.oneToOne.findMany({where:{organisationId,status:'SCHEDULED',scheduledAt:{lte:summary.fortnight},employee:{status:{not:'LEFT'}}},include:{employee:{select:personSelect}},orderBy:{scheduledAt:'asc'},take:6}):[],
 can(session,HR.absenceRead)?db.absenceRecord.findMany({where:{organisationId,status:'APPROVED',startDate:{lte:new Date()},endDate:{gte:summary.today},employee:{status:{not:'LEFT'}}},select:{id:true,employeeId:true,endDate:true,employee:{select:personSelect}},orderBy:{endDate:'asc'},take:8}):[]]);
 const employed=summary.departments.reduce((n,d)=>n+d._count,0),count=(status:string)=>summary.statuses.find(s=>s.status===status)?._count??0;
 const alerts=[{label:'Overdue training',value:summary.trainingOverdue,href:'/people/training?view=overdue'},{label:'Training renewals',value:summary.trainingRenewals,href:'/people/training?view=renewal'},{label:'Document renewals',value:summary.documentRenewals,href:'/people/documents?view=renewal'},...(summary.leave!==null?[{label:'Leave decisions',value:summary.leave,href:'/people/holidays'}]:[]),...(summary.expenses!==null?[{label:'Expense decisions',value:summary.expenses,href:'/people/expenses'}]:[])];
 const journeys=[{title:'Employee directory',description:'Find a person, update their record and follow their history.',href:'/people/directory',show:true},{title:'Recruitment',description:'Vacancies, applicants, interviews and accepted offers.',href:'/people/recruitment',show:can(session,HR.employeeManage)},{title:'Joining & leaving',description:'Owned checklists and the next step for each employee.',href:can(session,HR.onboardingManage)?'/people/onboarding':'/people/offboarding',show:phases.length>0},{title:'Training & qualifications',description:'Required learning, actual completion and renewal dates.',href:'/people/training',show:true},{title:'Employee documents',description:'Contracts and evidence with dates and retained history.',href:'/people/documents',show:true},{title:'Performance & development',description:'Appraisals and recurring review conversations.',href:'/people/appraisals',show:can(session,HR.appraisalRead)},{title:'Policies',description:'Published guidance and company policy documents.',href:'/people/policies',show:can(session,HR.policyRead)||can(session,HR.policyManage)},{title:'Workforce reports',description:'Current workforce, departments and outstanding people work.',href:'/people/reports',show:true}];
 return <div className="min-w-0 space-y-6"><header className={`${panelClass} flex flex-wrap items-start justify-between gap-4`}><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-wide text-[var(--color-atlas-blue)]">People operations</p><h2 className="mt-2 text-3xl font-semibold">HR home</h2><p className="mt-2 text-sm text-slate-500">Look after your people, keep their records together and see what needs attention today.</p></div><Link href="/people/me" className="rounded-lg border border-slate-200 px-4 py-2 text-sm">My HR →</Link></header>
 <div className="grid gap-3 sm:grid-cols-3"><Link href="/people/reports" className={panelClass}><p className="text-xs text-slate-500">Currently employed</p><p className="mt-2 text-3xl font-semibold">{employed}</p><p className="mt-1 text-xs text-slate-500">Active, on leave or offboarding; already started.</p></Link><Link href="/people/directory?status=ONBOARDING" className={panelClass}><p className="text-xs text-slate-500">Joining / onboarding</p><p className="mt-2 text-3xl font-semibold">{count('ONBOARDING')}</p></Link><Link href="/people/directory?status=OFFBOARDING" className={panelClass}><p className="text-xs text-slate-500">Leaving / offboarding</p><p className="mt-2 text-3xl font-semibold">{count('OFFBOARDING')}</p></Link></div>
 <section><h3 className="mb-3 text-lg font-semibold">Needs attention</h3><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{alerts.map(a=><Link key={a.label} href={a.href} className={panelClass}><p className="text-xs text-slate-500">{a.label}</p><p className={`mt-2 text-2xl font-semibold ${a.value?'text-amber-700':''}`}>{a.value}</p></Link>)}</div><p className="mt-2 text-xs text-slate-500">Renewals include expired records and dates within 30 days for current employees.</p></section>
 <div className="grid min-w-0 gap-5 xl:grid-cols-2"><section className={panelClass}><h3 className="font-semibold">Joining & leaving work</h3><p className="mt-1 text-xs text-slate-500">Next 12 outstanding checklist tasks within your permissions.</p>{tasks.map(t=><div key={t.id} className="mt-3 flex flex-wrap items-start justify-between gap-3 border-t border-slate-100 pt-3"><div className="min-w-0"><Link className="text-sm font-medium text-[var(--color-atlas-blue)]" href={`/people/${t.employeeId}`}>{t.employee.firstName} {t.employee.lastName}</Link><p className="mt-1 break-words text-sm">{t.title}</p><p className="mt-1 text-xs text-slate-500">{t.phase} · {t.dueDate?.toLocaleDateString('en-GB')??'Needs a deadline'}</p></div><ActionForm action={completeEmployeeTask.bind(null,t.id)}><Button type="submit">Complete</Button></ActionForm></div>)}{!tasks.length&&<p className="mt-4 text-sm text-slate-500">No outstanding checklists within your access.</p>}</section>
 <section className={panelClass}><h3 className="font-semibold">Reviews due</h3><p className="mt-1 text-xs text-slate-500">Next fortnight, including overdue. {(summary.appraisals??0)+(summary.meetings??0)} scheduled in total.</p>{[...appraisals.map(a=>({...a,label:'Appraisal',href:`/people/appraisals?employeeId=${a.employeeId}`})),...meetings.map(a=>({...a,label:'One-to-one',href:`/people/one-to-ones?employeeId=${a.employeeId}`}))].sort((a,b)=>a.scheduledAt.getTime()-b.scheduledAt.getTime()).map(r=><Link key={r.id} href={r.href} className="mt-3 flex flex-wrap justify-between gap-2 border-t border-slate-100 pt-3 text-sm"><span>{r.employee.firstName} {r.employee.lastName}<span className="block text-xs text-slate-500">{r.label}</span></span><span>{r.scheduledAt.toLocaleDateString('en-GB')}</span></Link>)}{!appraisals.length&&!meetings.length&&<p className="mt-4 text-sm text-slate-500">No reviews due within your access.</p>}</section></div>
 <section><h3 className="mb-3 text-lg font-semibold">Your HR workspace</h3><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{journeys.filter(j=>j.show).map(j=><Link className={panelClass} key={j.title} href={j.href}><h4 className="font-semibold">{j.title} →</h4><p className="mt-2 text-sm text-slate-500">{j.description}</p></Link>)}</div></section>
 {can(session,HR.absenceRead)&&<section className={panelClass}><h3 className="font-semibold">Away today</h3><p className="mt-1 text-xs text-slate-500">Approved absences; personal reasons stay on the permissioned absence record.</p>{away.map(a=><Link key={a.id} href={`/people/${a.employeeId}`} className="mt-3 flex flex-wrap justify-between gap-2 text-sm"><span>{a.employee.firstName} {a.employee.lastName}</span><span>Until {a.endDate.toLocaleDateString('en-GB')}</span></Link>)}{!away.length&&<p className="mt-3 text-sm text-slate-500">No current approved absences.</p>}</section>}
 </div>;
}
