import { db } from '@/core/db/client';
import type { BusinessPlanningProvider } from '@/core/planning/business';
export const salesBusinessPlanning:BusinessPlanningProvider=async(session,request)=>{
 if(request.purpose==='picker'){
  if(!session.capabilities.has('sales.quote.read'))return {requiredCapabilities:[]};
  const quotes=await db.quote.findMany({where:{organisationId:session.organisationId,...(request.sourceIds?{id:{in:request.sourceIds}}:{}),...(request.search?{reference:{contains:request.search,mode:'insensitive'}}:{})},select:{id:true,reference:true,netAmount:true,totalCurrency:true},orderBy:{createdAt:'desc'},take:501});
  return {sources:quotes.slice(0,500).map(q=>({module:'sales',type:'quote',id:q.id,label:q.reference,href:`/sales/quotes/${q.id}`,capability:'sales.quote.read',valueMinor:q.netAmount,currency:q.totalCurrency})),requiredCapabilities:['sales.quote.read']};
 }
 if(!session.capabilities.has('sales.order.read')||!session.capabilities.has('customers.read'))return {requiredCapabilities:[],warnings:['Sales order history is unavailable without Sales order and Customer read access.']};
 const lines=await db.salesOrderLine.findMany({where:{type:'PRODUCT',productId:request.productIds?{in:request.productIds}:{not:null},order:{organisationId:session.organisationId,commercialStatus:{in:['CONFIRMED','CLOSED','ON_HOLD']},orderType:{notIn:['BLANKET','INTERNAL']},orderDate:{lte:new Date(`${request.endsOn}T23:59:59.999Z`)},OR:[{orderDate:{gte:new Date(request.historyStartsOn)}},{requestedDeliveryDate:{gte:new Date(request.historyStartsOn)}},{promisedDeliveryDate:{gte:new Date(request.historyStartsOn)}},{commercialStatus:{not:'CLOSED'}}]}},select:{id:true,productId:true,orderedQuantity:true,cancelledQuantity:true,netAmount:true,requestedDeliveryDate:true,promisedDeliveryDate:true,order:{select:{id:true,reference:true,partyId:true,salesProjectId:true,opportunityId:true,currency:true,commercialStatus:true,orderDate:true,requestedDeliveryDate:true,promisedDeliveryDate:true,party:{select:{name:true}}}}},orderBy:{id:'asc'},take:5001});
 if(lines.length>5000)throw Error('This history contains more than 5,000 order lines. Narrow the history window before generating a forecast.');
 const shipped=await db.fulfilmentLine.groupBy({by:['salesOrderLineId'],where:{organisationId:session.organisationId,salesOrderLineId:{in:lines.map(l=>l.id)}},_sum:{shippedQuantity:true}});
 const shippedByLine=new Map(shipped.map(s=>[s.salesOrderLineId,Number(s._sum.shippedQuantity??0)]));
 const missingDates=lines.filter(l=>!l.requestedDeliveryDate&&!l.order.requestedDeliveryDate).length;
 return {warnings:missingDates?[`${missingDates} sales order lines have no requested delivery date; they cannot enter requested-demand history or a monthly demand bucket until Sales records that date.`]:[],orders:lines.map(l=>({id:l.order.id,lineId:l.id,reference:l.order.reference,partyId:l.order.partyId,customer:l.order.party.name,productId:l.productId!,projectId:l.order.salesProjectId,opportunityId:l.order.opportunityId,quantity:Math.max(0,l.orderedQuantity-l.cancelledQuantity),valueMinor:l.orderedQuantity?Math.round(l.netAmount*Math.max(0,l.orderedQuantity-l.cancelledQuantity)/l.orderedQuantity):0,currency:l.order.currency,closed:l.order.commercialStatus==='CLOSED',onHold:l.order.commercialStatus==='ON_HOLD',dispatchedQuantity:shippedByLine.get(l.id)??0,bookedOn:l.order.orderDate.toISOString().slice(0,10),requestedOn:(l.requestedDeliveryDate??l.order.requestedDeliveryDate)?.toISOString().slice(0,10)??null,promisedOn:(l.promisedDeliveryDate??l.order.promisedDeliveryDate)?.toISOString().slice(0,10)??null})),requiredCapabilities:['sales.order.read','customers.read']};
};
