import { db } from "@/core/db/client";
import type { Session } from "@/core/auth/session";
import { can } from "@/core/permissions/check";
import type { DocumentData } from "../components/document-types";
export async function getDocumentData(session:Session):Promise<DocumentData> {
 const organisationId=session.organisationId;
 const [customers,addresses,products,lists,contracts,terms,opportunities,projects,balances,policy,tradingLinks]=await Promise.all([
 db.party.findMany({where:{organisationId},include:{commercialSettings:true,creditProfile:true},orderBy:{name:'asc'}}),db.address.findMany({where:{active:true,party:{organisationId}},include:{party:{select:{name:true}}}}),db.product.findMany({where:{organisationId,active:true},orderBy:{name:'asc'}}),db.priceList.findMany({where:{organisationId},include:{entries:true},orderBy:{name:'asc'}}),db.customerProduct.findMany({where:{party:{organisationId},product:{organisationId},contractedPriceAmount:{not:null}}}),db.paymentTerm.findMany({where:{organisationId}}),can(session,'sales.opportunity.read')?db.opportunity.findMany({where:{organisationId},select:{id:true,name:true,partyId:true}}):[],can(session,'projects.read')?db.project.findMany({where:{organisationId},select:{id:true,name:true,partyId:true}}):[],can(session,'stock.read')?db.inventoryBalance.groupBy({by:['productId'],where:{organisationId},_sum:{quantity:true}}):[],db.organisation.findUniqueOrThrow({where:{id:organisationId},select:{allowCustomerCreation:true,allowProductCreation:true}}),db.customerTradingLink.findMany({where:{organisationId,active:true,account:{organisationId},tradingAccount:{organisationId}},select:{accountId:true,tradingAccountId:true}})]);
 return {allowProductCreation:policy.allowProductCreation&&can(session,'core.products.manage'),allowCustomerCreation:policy.allowCustomerCreation&&can(session,'customers.create'),canOverrideQuotePrice:can(session,'sales.quote.approve'),canOverrideOrderPrice:can(session,'sales.order.price_override'),canOverridePrice:can(session,'sales.quote.approve')||can(session,'sales.order.price_override'),tradingLinks,customers:customers.map(c=>({id:c.id,name:c.name,code:c.customerCode,parentId:c.parentPartyId,currency:c.preferredCurrency,defaultListId:c.commercialSettings?.priceList??null,defaultTermId:c.creditProfile?.paymentTermId??null,poRequired:c.commercialSettings?.customerPoRequired??false,referenceRequired:c.commercialSettings?.orderReferenceRequired??false,...(can(session,'customers.credit.read')?{creditHold:c.creditProfile?.onHold??false}:{})})),addresses:addresses.map(a=>({id:a.id,partyId:a.partyId,type:a.type,label:`${a.party.name} · ${a.label??a.line1} · ${a.postcode??''}`,country:a.country,defaultBilling:a.isDefaultBilling,defaultDelivery:a.isDefaultDelivery})),products:products.map(p=>({id:p.id,name:p.name,code:p.code,categoryCode:p.categoryCode,unit:p.unitOfMeasure,price:p.basePriceAmount,currency:p.baseCurrency,taxCategory:p.taxCategory,stock:can(session,'stock.read')?balances.find(b=>b.productId===p.id)?._sum.quantity??0:null})),lists:lists.map(l=>({id:l.id,name:l.name,currency:l.currency,baseCurrency:l.baseCurrency,exchangeRate:l.exchangeRate,entries:l.entries.map(e=>({...e,validFrom:e.validFrom?.toISOString()??null,validTo:e.validTo?.toISOString()??null}))})),contracts:contracts.map(c=>({partyId:c.partyId,productId:c.productId,price:c.contractedPriceAmount!,currency:c.contractedPriceCurrency??'GBP'})),terms:terms.map(t=>({id:t.id,name:t.name})),opportunities,projects};
}
