import type {Prisma} from '@/generated/prisma/client';
import {parseRules,RULE_FIELDS,selections,type SalesRule} from './view-definition';
export type SalesFilters={customerScope?:string;beneficiary?:string;q?:string;owner?:string;customer?:string;tag?:string;tagMode?:string;status?:string;currency?:string;page?:string;view?:string;from?:string;to?:string;group?:string;dateField?:string;rules?:string;match?:string;columns?:string;sort?:string;direction?:string};
function text(value:string,operator:string){if(operator==='eq')return {equals:value,mode:'insensitive'};if(operator==='contains')return {contains:value,mode:'insensitive'};if(operator==='not_contains')return {not:{contains:value,mode:'insensitive'}};if(operator==='empty')return {equals:''};throw new Error('Choose a text filter operator.');}
function condition(rule:SalesRule,mode:'order'|'quote',currency?:string):Record<string,unknown>{
 const kind=RULE_FIELDS.find(([key])=>key===rule.field)?.[2],value=rule.value.trim();if(!value&&rule.operator!=='empty')throw new Error('Enter a value for each advanced filter.');
 if((mode==='order'&&rule.field==='expiry')||(mode==='quote'&&['requested','promised'].includes(rule.field)))throw new Error('This filter does not apply to this document type.');
 const scalar:Record<string,string>={reference:'reference',po:'customerPoReference',external:'externalReference',notes:'customerNotes',created:'createdAt',updated:'updatedAt',requested:'requestedDeliveryDate',promised:'promisedDeliveryDate',expiry:'expiryDate',net:'netAmount',tax:'taxAmount',total:mode==='order'?'grossAmount':'totalAmount'};
 if(kind==='date'){if(rule.operator==='empty')return {[scalar[rule.field]]:null};if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||isNaN(new Date(value).getTime()))throw new Error('Choose a valid date.');const start=new Date(value),end=new Date(value+'T23:59:59.999Z');if(!['eq','gte','lte','gt','lt'].includes(rule.operator))throw new Error('Choose a date comparison.');return {[scalar[rule.field]]:rule.operator==='eq'?{gte:start,lte:end}:{[rule.operator]:['lte','gt'].includes(rule.operator)?end:start}};}
 if(kind==='money'||kind==='number'){if(rule.operator==='empty')throw new Error('Choose a numeric comparison.');if(kind==='money'&&selections(currency).length!==1)throw new Error('Choose one currency when filtering monetary amounts.');const n=Number(value)*(kind==='money'?100:1);if(!Number.isFinite(n)||n<0||n>2147483647||!['eq','gte','lte','gt','lt'].includes(rule.operator))throw new Error('Enter a valid numeric comparison.');const filter={[rule.operator==='eq'?'equals':rule.operator]:kind==='money'?Math.round(n):n};return kind==='money'?{[scalar[rule.field]]:filter}:{lines:{some:{[rule.field==='discount'?'discountPercent':mode==='order'?'orderedQuantity':'quantity']:filter}}};}
 const filter=text(value,rule.operator);
 const nullable=(key:string)=>rule.operator==='empty'?{OR:[{[key]:null},{[key]:''}]}:{[key]:filter};
 if(rule.field==='customerType')return {party:nullable('customerGroup')};
 if(rule.field==='pricingCustomer')return {pricingParty:{name:filter}};
 if(rule.field==='customerName'||rule.field==='customerCode')return {party:{[rule.field==='customerName'?'name':'customerCode']:filter}};
 if(rule.field==='customerEmail')return {party:{contacts:{some:nullable('email')}}};
 if(['productCode','category'].includes(rule.field))return {lines:{some:{product:rule.field==='category'?nullable('categoryCode'):{code:filter}}}};
 if(rule.field==='description')return {lines:{some:{[mode==='order'?'descriptionSnapshot':'description']:filter}}};
 if(['postcode','country'].includes(rule.field)){const path=[rule.field];if(rule.operator==='empty')throw new Error('Use an address text comparison.');if(rule.operator==='eq')return {deliveryAddressSnapshot:{path,equals:value}};const match={deliveryAddressSnapshot:{path,string_contains:value}};return rule.operator==='not_contains'?{NOT:match}:match;}
 return ['po','external','notes'].includes(rule.field)?nullable(scalar[rule.field]):{[scalar[rule.field]]:filter};
}
function base(organisationId:string,p:SalesFilters,mode:'order'|'quote'){
 const q=(p.q??'').trim().slice(0,150),owners=selections(p.owner),customers=selections(p.customer,10000),tags=selections(p.tag).map(v=>v.toLowerCase()),statuses=selections(p.status).filter(s=>(mode==='order'?['DRAFT','PENDING_APPROVAL','CONFIRMED','ON_HOLD','CANCELLED','CLOSED']:['DRAFT','SENT','ACCEPTED','DECLINED']).includes(s)),currencies=selections(p.currency),rules=parseRules(p.rules);
 const AND:Record<string,unknown>[]=[];if(q)AND.push({OR:[{reference:{contains:q,mode:'insensitive'}},{customerPoReference:{contains:q,mode:'insensitive'}},{externalReference:{contains:q,mode:'insensitive'}},{customerNotes:{contains:q,mode:'insensitive'}},{party:{name:{contains:q,mode:'insensitive'}}},{party:{customerCode:{contains:q,mode:'insensitive'}}},{pricingParty:{name:{contains:q,mode:'insensitive'}}},{lines:{some:{[mode==='order'?'descriptionSnapshot':'description']:{contains:q,mode:'insensitive'}}}},{lines:{some:{product:{OR:[{code:{contains:q,mode:'insensitive'}},{categoryCode:{contains:q,mode:'insensitive'}}]}}}},{deliveryAddressSnapshot:{path:['postcode'],string_contains:q}}]});
 if(p.beneficiary){const ids=selections(p.beneficiary);AND.push({OR:[{pricingPartyId:{in:ids}},{pricingPartyId:null,partyId:{in:ids}}]});}
 if(rules.length)AND.push({[p.match==='any'?'OR':'AND']:rules.map(r=>condition(r,mode,p.currency))});
 const dateKeys=mode==='order'?{created:'orderDate',updated:'updatedAt',requested:'requestedDeliveryDate',promised:'promisedDeliveryDate'}:{created:'createdAt',updated:'updatedAt',expiry:'expiryDate'},dateKey=dateKeys[p.dateField as keyof typeof dateKeys]??dateKeys.created;
 return {organisationId,...(owners.length?{ownerUserId:owners.length===1?owners[0]:{in:owners}}:{}),...(customers.length?{partyId:customers.length===1?customers[0]:{in:customers}}:{}),...(tags.length?{tags:tags.length===1?{has:tags[0]}:p.tagMode==='all'?{hasEvery:tags}:{hasSome:tags}}:{}),...(statuses.length?{[mode==='order'?'commercialStatus':'status']:{in:statuses}}:{}),...(currencies.length?{[mode==='order'?'currency':'totalCurrency']:{in:currencies}}:{}),...(AND.length?{AND}:{}),...(dateRange(p)?{[dateKey]:dateRange(p)}:{})};
}
export function orderWhere(organisationId:string,p:SalesFilters):Prisma.SalesOrderWhereInput{return base(organisationId,p,'order') as Prisma.SalesOrderWhereInput;}
export function quoteWhere(organisationId:string,p:SalesFilters):Prisma.QuoteWhereInput{return base(organisationId,p,'quote') as Prisma.QuoteWhereInput;}
function dateRange(p:SalesFilters){const range:{gte?:Date;lte?:Date}={};if(p.from&&/^\d{4}-\d{2}-\d{2}$/.test(p.from)){const d=new Date(p.from);if(!isNaN(d.getTime()))range.gte=d;}if(p.to&&/^\d{4}-\d{2}-\d{2}$/.test(p.to)){const d=new Date(p.to+'T23:59:59.999Z');if(!isNaN(d.getTime()))range.lte=d;}return Object.keys(range).length?range:undefined;}
