import {PDFDocument,StandardFonts,rgb,PageSizes} from 'pdf-lib';
import {formatMoney} from '@/core/shared/money';
export type QuotePdfData={documentType?:'Quotation'|'Order acknowledgement';requestedDeliveryDate?:Date|null;promisedDeliveryDate?:Date|null;notes?:string|null;reference:string;organisationName:string;customerName:string;customerCode:string;status:string;createdAt:Date;expiryDate:Date|null;customerPoReference:string|null;paymentTerms:string|null;currency:string;invoiceAddress:unknown;deliveryAddress:unknown;netAmount:number;taxAmount:number;totalAmount:number;lines:{type?:string;optional?:boolean;description:string;code:string|null;quantity:number;unitAmount:number;discountPercent:number;netAmount:number;taxAmount:number}[]};
export async function buildQuotePdf(quote:QuotePdfData){
 const documentType=quote.documentType??'Quotation';
 const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);
 pdf.setTitle(`${documentType} ${quote.reference}`);pdf.setAuthor(quote.organisationName);pdf.setSubject(`Saved ${documentType.toLowerCase()}`);
 const ink=rgb(.09,.14,.23),muted=rgb(.40,.45,.53),blue=rgb(.14,.34,.83),line=rgb(.88,.91,.95);
 const safe=(value:string)=>[...value].map(c=>{try{font.encodeText(c);return c;}catch{return '?';}}).join('');
 const wrap=(value:string,width:number,size:number)=>{const lines:string[]=[];let current='';for(const word of safe(value).split(/\s+/)){if(font.widthOfTextAtSize(`${current} ${word}`.trim(),size)>width&&current){lines.push(current);current='';}if(font.widthOfTextAtSize(word,size)>width){for(const character of word){if(font.widthOfTextAtSize(current+character,size)>width){lines.push(current);current='';}current+=character;}}else current+=(current?' ':'')+word;}if(current)lines.push(current);return lines.length?lines:[''];};
 let page=pdf.addPage(PageSizes.A4),y=780;
 const text=(value:string,x:number,at:number,size=10,strong=false,color=ink)=>page.drawText(safe(value),{x,y:at,size,font:strong?bold:font,color});
 const right=(value:string,x:number,at:number,size=10,strong=false)=>text(value,x-(strong?bold:font).widthOfTextAtSize(safe(value),size),at,size,strong);
 const header=()=>{page.drawRectangle({x:0,y:816,width:595.28,height:26,color:blue});text(quote.organisationName,42,780,18,true);text(documentType.toUpperCase(),42,745,9,true,blue);text(quote.reference,42,718,24,true);text(`${quote.status} · ${quote.currency}`,42,699,9,false,muted);right(`Issued ${quote.createdAt.toLocaleDateString('en-GB')}`,553,745,9);if(quote.expiryDate)right(`Valid until ${quote.expiryDate.toLocaleDateString('en-GB')}`,553,727,9);if(quote.customerPoReference)right(`PO ${quote.customerPoReference}`,553,709,9);};
 const tableHeader=()=>{page.drawRectangle({x:42,y:y-9,width:511,height:28,color:rgb(.95,.97,.99)});text('PRODUCT / DESCRIPTION',52,y,8,true,muted);right('QTY',352,y,8,true);right('UNIT PRICE',423,y,8,true);right('DISC %',473,y,8,true);right('NET',543,y,8,true);y-=36;};
 const address=(label:string,value:unknown,x:number,start:number)=>{text(label,x,start,8,true,blue);const a=value&&typeof value==='object'?value as Record<string,unknown>:{};const content=[a.label,a.line1,a.line2,a.city,a.region,a.postcode,a.country].filter(v=>typeof v==='string'&&v).join(', ');let at=start-18;for(const row of wrap(content||'Not specified',235,9)){text(row,x,at,9);at-=13;}return at;};
 header();y=657;text(quote.customerName,42,y,13,true);text(quote.customerCode,42,y-18,9,false,muted);
 y=Math.min(address('INVOICE ADDRESS',quote.invoiceAddress,42,610),address('DELIVERY ADDRESS',quote.deliveryAddress,313,610))-25;
 tableHeader();
 for(const item of quote.lines){if(['SECTION','NOTE'].includes(item.type??'')){const heading=wrap(item.description,480,10);if(y-heading.length*14<100){page=pdf.addPage(PageSizes.A4);header();y=660;tableHeader();}for(const row of heading){text(row,52,y,10,item.type==='SECTION');y-=14;}y-=12;continue;}const lines=wrap((item.optional?'OPTIONAL: ':'')+item.description,260,9),height=Math.max(35,lines.length*13+18+(item.code?12:0));if(y-height<100){page=pdf.addPage(PageSizes.A4);header();y=660;tableHeader();}let at=y;for(const row of lines){text(row,52,at,9);at-=13;}if(item.code)text(item.code,52,at-3,8,false,muted);right(String(item.quantity),352,y,9);right(formatMoney(item.unitAmount,quote.currency),423,y,9);right(item.discountPercent.toFixed(1),473,y,9);right(formatMoney(item.netAmount,quote.currency),543,y,9,true);page.drawLine({start:{x:42,y:y-height+10},end:{x:553,y:y-height+10},thickness:.5,color:line});y-=height;}
 if(y<190){page=pdf.addPage(PageSizes.A4);header();y=660;}
 if(quote.requestedDeliveryDate||quote.promisedDeliveryDate){if(y<220){page=pdf.addPage(PageSizes.A4);header();y=660;}text(`Requested delivery: ${quote.requestedDeliveryDate?.toLocaleDateString('en-GB')??'To be agreed'} · Promised: ${quote.promisedDeliveryDate?.toLocaleDateString('en-GB')??'To be agreed'}`,42,y,9);y-=28;}
 y-=18;text('Payment terms',42,y,9,true);for(const row of wrap(quote.paymentTerms??'To be agreed',240,9)){text(row,42,y-17,9,false,muted);y-=13;}
 const totalsTop=y+13;text('Untaxed amount',350,totalsTop,10,false,muted);right(formatMoney(quote.netAmount,quote.currency),543,totalsTop,10);text('Tax',350,totalsTop-23,10,false,muted);right(formatMoney(quote.taxAmount,quote.currency),543,totalsTop-23,10);page.drawLine({start:{x:350,y:totalsTop-36},end:{x:543,y:totalsTop-36},thickness:1,color:line});text('Total',350,totalsTop-59,13,true);right(formatMoney(quote.totalAmount,quote.currency),543,totalsTop-59,15,true);
 if(quote.notes){y-=100;for(const row of wrap(quote.notes,500,9)){if(y<80){page=pdf.addPage(PageSizes.A4);header();y=660;}text(row,42,y,9,false,muted);y-=13;}}
 const pages=pdf.getPages();for(let i=0;i<pages.length;i++){page=pages[i];page.drawLine({start:{x:42,y:49},end:{x:553,y:49},thickness:.5,color:line});text(`${quote.organisationName} · ${quote.reference}`,42,33,8,false,muted);right(`${i+1} / ${pages.length}`,553,33,8);}
 return pdf.save();
}
