import {z} from 'zod';
export const SALES_COLUMNS=[['number','Number'],['customer','Invoice account'],['pricingCustomer','Pricing account'],['customerType','Customer type'],['status','Status'],['owner','Salesperson'],['po','PO / tags'],['delivery','Delivery / validity'],['total','Total'],['external','Customer reference'],['currency','Currency'],['net','Net amount'],['tax','Tax'],['created','Created date'],['updated','Last updated'],['promised','Promised delivery'],['postcode','Delivery postcode'],['lines','Line count']] as const;
export const DEFAULT_COLUMNS=['number','customer','status','owner','po','delivery','total'];
export const RULE_FIELDS=[['reference','Document number','text'],['po','Customer PO','text'],['external','Customer reference','text'],['customerName','Customer name','text'],['customerCode','Customer code','text'],['customerEmail','Contact email','text'],['customerType','Customer type','text'],['pricingCustomer','Pricing account name','text'],['productCode','Product SKU','text'],['category','Product category code','text'],['description','Line description','text'],['notes','Customer notes','text'],['postcode','Delivery postcode','text'],['country','Delivery country','text'],['net','Net amount','money'],['tax','Tax amount','money'],['total','Total amount','money'],['quantity','Line quantity','number'],['discount','Line discount %','number'],['created','Created date','date'],['updated','Updated date','date'],['requested','Requested delivery','date'],['promised','Promised delivery','date'],['expiry','Quote validity','date']] as const;
const ruleFields=RULE_FIELDS.map(f=>f[0]);
export const ruleSchema=z.object({field:z.string().refine(f=>ruleFields.includes(f as typeof ruleFields[number])),operator:z.enum(['contains','eq','not_contains','empty','gte','lte','gt','lt']),value:z.string().max(200).default('')});
export type SalesRule=z.infer<typeof ruleSchema>;
export function parseRules(raw?:string):SalesRule[]{if(!raw)return [];if(raw.length>12000)throw new Error('Too many filter rules.');return z.array(ruleSchema).max(20).parse(JSON.parse(raw));}
export function selectedColumns(raw?:string){if(!raw)return DEFAULT_COLUMNS;return ['number',...raw.split(',').filter(c=>c!=='number'&&SALES_COLUMNS.some(([key])=>key===c))].filter((c,i,a)=>a.indexOf(c)===i);}
export function selections(raw?:string,limit=100){return [...new Set((raw??'').split(',').map(v=>v.trim()).filter(Boolean))].slice(0,limit);}
export function fieldsForMode(mode:'order'|'quote'){return RULE_FIELDS.filter(([key])=>mode==='order'?key!=='expiry':!['requested','promised'].includes(key));}
