import Link from "next/link";
import { Studio } from "@/modules/analytics/components/studio";
import type { AnalyticsResult } from "@/core/analytics/types";
const metrics:AnalyticsResult[]=[
 {id:"sales.orders",name:"Orders received",subject:"Sales",definition:"Orders in the selected period. Choose status, order type, product, category, customer or time. Product and category count lines. This is not recognised revenue.",grain:"One sales order, or one product line",snapshot:false,href:"/sales/orders",breakdowns:[{id:"status",label:"Status"},{id:"type",label:"Order type"},{id:"product",label:"Product"},{id:"category",label:"Category"},{id:"customer",label:"Customer"},{id:"time",label:"Over time",shape:"trend"}],points:[{label:"Confirmed",value:842},{label:"Draft",value:126},{label:"Closed",value:318},{label:"Cancelled",value:24}],previewSlices:{type:{points:[{label:"Standard",value:980},{label:"Return",value:42}]},product:{points:[{label:"Atlas chair",value:210},{label:"Harbour desk",value:140},{label:"Lane lamp",value:88}]},category:{points:[{label:"Seating",value:260},{label:"Desks",value:140},{label:"Lighting",value:88}]},customer:{points:[{label:"Northwind",value:40},{label:"Harbour Co",value:28}]},time:{shape:"trend",points:[{label:"1 Sep",value:42},{label:"8 Sep",value:55},{label:"15 Sep",value:48},{label:"22 Sep",value:63}]}}},
 {id:"people.headcount",name:"Active employees",subject:"HR",definition:"Illustrative active employee count by department.",grain:"One employee",snapshot:true,href:"/people",points:[{label:"Operations",value:84},{label:"Sales & commercial",value:32},{label:"Finance",value:18},{label:"People & culture",value:12}]},
 {id:"stock.positions",name:"Stock positions",subject:"Inventory",definition:"Illustrative count of product/warehouse balances, not stock quantity or valuation.",grain:"One product per warehouse",snapshot:true,href:"/stock",points:[{label:"Main warehouse",value:624},{label:"Distribution centre",value:418},{label:"Production store",value:286},{label:"Returns & inspection",value:72}]},
 {id:"crm.opportunities",name:"Opportunities",subject:"CRM",definition:"Illustrative opportunity counts by outcome.",grain:"One opportunity",snapshot:true,href:"/crm/pipeline",points:[{label:"Open",value:96},{label:"Won",value:48},{label:"Lost",value:22}]},
 {id:"customers.lifecycle",name:"Customer accounts",subject:"Customers",definition:"Illustrative account counts by lifecycle status.",grain:"One shared Party",snapshot:true,href:"/customers",points:[{label:"Active",value:482},{label:"Prospect",value:128},{label:"Archived",value:34}]},
 {id:"projects.status",name:"Project portfolio",subject:"Projects",definition:"Illustrative project counts by workflow status.",grain:"One project",snapshot:true,href:"/projects",points:[{label:"Active",value:24},{label:"Planned",value:12},{label:"Completed",value:86}]},
 {id:"products.catalogue",name:"Active catalogue",subject:"Products",definition:"Illustrative shared catalogue count by kind.",grain:"One product or service",snapshot:true,href:"/products",points:[{label:"Product",value:824},{label:"Service",value:62}]},
 {id:"pricing.lists",name:"Pricelists",subject:"Pricing",definition:"Illustrative number of pricelists per currency, not monetary amounts.",grain:"One pricelist",snapshot:true,href:"/pricing",points:[{label:"GBP",value:12},{label:"EUR",value:6},{label:"USD",value:4}]},
 {id:"kpis.scorecards",name:"Team scorecards",subject:"Goals & KPIs",definition:"Illustrative KPI definition count by team.",grain:"One KPI definition",snapshot:true,href:"/kpis",points:[{label:"Operations",value:18},{label:"Sales",value:14},{label:"Customer service",value:9}]},
 {id:"planning.plans",name:"Production plans",subject:"Planning",definition:"Illustrative count of planner intentions by bucket. Not executable production orders.",grain:"One plan",snapshot:false,href:"/planning/plans",points:[{label:"Weekly",value:18},{label:"Daily",value:24}]},
 {id:"sales.orders.trend",name:"Orders over time",subject:"Sales",definition:"Illustrative weekly order counts. Not recognised revenue.",grain:"One sales order",snapshot:false,shape:"trend",href:"/sales/orders",points:[{label:"1 Sep",value:42},{label:"8 Sep",value:55},{label:"15 Sep",value:48},{label:"22 Sep",value:63},{label:"29 Sep",value:58}]},
 {id:"crm.pipeline.value",name:"Open pipeline value",subject:"CRM",definition:"Illustrative open pipeline by currency. Currencies are not combined.",grain:"One currency",snapshot:true,unit:"money",href:"/crm/pipeline",points:[{label:"GBP",value:18650000},{label:"EUR",value:4200000}]},
 {id:"crm.winrate",name:"Win rate",subject:"CRM",definition:"Illustrative won share of closed opportunities.",grain:"Closed opportunities",snapshot:false,unit:"percent",href:"/crm/forecast",points:[{label:"Win rate",value:46}]},
 {id:"crm.pipeline.stages",name:"Open pipeline by stage",subject:"CRM",definition:"Illustrative open opportunities by stage.",grain:"One opportunity",snapshot:true,href:"/crm/pipeline",points:[{label:"Qualification",value:28},{label:"Proposal",value:19},{label:"Negotiation",value:11}]},
 {id:"crm.prospects.trend",name:"Prospects over time",subject:"CRM",definition:"Illustrative new prospects by week.",grain:"One prospect",snapshot:false,shape:"trend",href:"/crm/prospect",points:[{label:"1 Sep",value:12},{label:"8 Sep",value:18},{label:"15 Sep",value:9},{label:"22 Sep",value:21}]},
 {id:"service.case.status",name:"Case status",subject:"Customer Service",definition:"Illustrative current cases by status.",grain:"One customer case",snapshot:true,href:"/service/cases",points:[{label:"New",value:14},{label:"Working",value:22},{label:"Waiting",value:8}]},
 {id:"service.case.count",name:"Cases opened",subject:"Customer Service",definition:"Illustrative cases by type.",grain:"One customer case",snapshot:false,href:"/service/cases",points:[{label:"Query",value:30},{label:"Complaint",value:6}]},
 {id:"logistics.shipments",name:"Shipments",subject:"Logistics",definition:"Illustrative shipments by status.",grain:"One shipment",snapshot:true,href:"/logistics/dispatch",points:[{label:"Planning",value:8},{label:"Dispatched",value:24},{label:"Delivered",value:40}]},
 {id:"logistics.fulfilment",name:"Fulfilment",subject:"Logistics",definition:"Illustrative fulfilment requirements by status.",grain:"One fulfilment requirement",snapshot:true,href:"/logistics/fulfil",points:[{label:"Open",value:16},{label:"Released",value:11},{label:"Done",value:30}]},
 {id:"logistics.shipments.trend",name:"Shipments over time",subject:"Logistics",definition:"Illustrative shipments by week.",grain:"One shipment",snapshot:false,shape:"trend",href:"/logistics/dispatch",points:[{label:"1 Sep",value:10},{label:"8 Sep",value:14},{label:"15 Sep",value:12},{label:"22 Sep",value:18}]},
 {id:"stock.movements.trend",name:"Movements over time",subject:"Inventory",definition:"Illustrative movement counts by week.",grain:"One inventory movement",snapshot:false,shape:"trend",href:"/stock/movements",points:[{label:"1 Sep",value:80},{label:"8 Sep",value:64},{label:"15 Sep",value:90},{label:"22 Sep",value:72}]},
 {id:"people.employment",name:"Employee lifecycle",subject:"HR",definition:"Illustrative employees by status.",grain:"One employee",snapshot:true,href:"/people",points:[{label:"Active",value:146},{label:"Leaving",value:4}]},
 {id:"people.absence.status",name:"Time off requests",subject:"HR",definition:"Illustrative requests by decision. No medical detail.",grain:"One absence request",snapshot:true,href:"/people/absence",points:[{label:"Pending",value:6},{label:"Approved",value:22}]},
 {id:"scheduling.shifts",name:"Shifts",subject:"Scheduling",definition:"Illustrative shifts by status.",grain:"One rota shift",snapshot:false,href:"/scheduling",points:[{label:"Scheduled",value:84},{label:"Confirmed",value:60}]},
 {id:"scheduling.timesheets",name:"Timesheets",subject:"Scheduling",definition:"Illustrative timesheets by status.",grain:"One timesheet",snapshot:false,href:"/people/timesheets",points:[{label:"Draft",value:12},{label:"Submitted",value:18},{label:"Approved",value:40}]},
 {id:"people.appraisals",name:"Appraisal reviews",subject:"HR",definition:"Illustrative appraisals by status. Review content is excluded.",grain:"One appraisal",snapshot:false,href:"/people/appraisals",points:[{label:"Scheduled",value:8},{label:"Complete",value:14}]},
 {id:"people.oneToOnes",name:"One-to-one meetings",subject:"HR",definition:"Illustrative meetings by status.",grain:"One meeting",snapshot:false,href:"/people/one-to-ones",points:[{label:"Scheduled",value:11},{label:"Complete",value:20}]},
 {id:"customers.territories",name:"Customer territories",subject:"Customers",definition:"Illustrative accounts by territory.",grain:"One shared Party",snapshot:true,href:"/customers",points:[{label:"North",value:120},{label:"South",value:98},{label:"Export",value:40}]}
];
export default async function Preview({searchParams}:{searchParams:Promise<{period?:string;new?:string;template?:string;edit?:string;menu?:string}>}){const params=await searchParams;const period=["30","90","365","all"].includes(params.period??"")?params.period!:"90";const scale=period==="30"?0.35:period==="365"?3.6:period==="all"?5:1;const scalePoints=(points:AnalyticsResult["points"])=>points.map(p=>({...p,value:Math.round(p.value*scale)}));const scoped=metrics.map(m=>m.snapshot?m:{...m,points:scalePoints(m.points),previewSlices:m.previewSlices&&Object.fromEntries(Object.entries(m.previewSlices).map(([key,slice])=>[key,{...slice,points:scalePoints(slice.points)}]))});return <main className="min-h-screen bg-[#f5f7fb] px-4 py-6 sm:px-8"><div className="mx-auto max-w-[1320px]"><nav className="mb-6 flex items-center justify-between border-b border-slate-200 pb-5"><Link href="/home" className="text-lg font-semibold tracking-tight text-slate-800">Atlas<span className="ml-3 text-xs font-normal text-slate-400">Your business, connected.</span></Link><Link href="/analytics" className="text-xs font-medium text-blue-600">Open live Dashboards ↗</Link></nav><Studio key={`${period}:${params.template??""}:${params.new??""}:${params.menu??""}`} metrics={scoped} dashboards={[]} period={period} canManage company="Example company" sample createNew={params.new==="1"} templateId={params.template} startEditing={params.new==="1"||params.edit==="1"} openMenuMetric={params.menu}/></div></main>;}
