export class HRInputError extends Error {}
export const APPLICATION_STAGES = ['APPLIED','SCREENING','INTERVIEW','OFFER','HIRED','REJECTED','WITHDRAWN'] as const;
export const TRAINING_STATUSES = ['PLANNED','IN_PROGRESS','COMPLETED','CANCELLED'] as const;
export function text(form:FormData,key:string,max=200,required=false){const value=String(form.get(key)??'').trim();if(value.length>max||required&&!value)throw new HRInputError(`Enter ${key.replace(/([A-Z])/g,' $1').toLowerCase()}${value.length>max?` within ${max} characters`:''}.`);return value;}
export function date(form:FormData,key:string){const value=text(form,key,10);if(!value)return null;const d=new Date(value+'T00:00:00.000Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==value)throw new HRInputError(`Enter a valid ${key.replace(/([A-Z])/g,' $1').toLowerCase()}.`);return d;}
export function version(form:FormData){const value=text(form,'version',15,true);if(!/^\d+$/.test(value)||!Number.isSafeInteger(Number(value)))throw new HRInputError('Refresh this record before saving.');return Number(value);}
export function link(form:FormData,key='evidenceUrl'){const value=text(form,key,2000);if(!value)return null;let url:URL;try{url=new URL(value);}catch{throw new HRInputError('Use a valid HTTP or HTTPS evidence link.');}if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw new HRInputError('Use a HTTP or HTTPS link without embedded credentials.');return value;}
export function assertApplicationMove(from:string,to:string){if(!(APPLICATION_STAGES as readonly string[]).includes(to))throw new HRInputError('Choose an application stage.');if(['HIRED','REJECTED','WITHDRAWN'].includes(from)&&from!==to)throw new HRInputError('This application is closed; retain it as recruitment history.');if(to==='HIRED'&&from!=='OFFER')throw new HRInputError('Record an offer before handing over to onboarding.');}
export function trainingDates(status:string,completedOn:Date|null,expiresOn:Date|null,now=new Date()) {if(status==='COMPLETED'&&!completedOn)throw new HRInputError('Enter the actual completion date.');if(status!=='COMPLETED'&&(completedOn||expiresOn))throw new HRInputError('Only completed training can have completion or expiry dates.');if(completedOn&&completedOn.toISOString().slice(0,10)>now.toISOString().slice(0,10))throw new HRInputError('Completion cannot be in the future.');if(expiresOn&&completedOn&&expiresOn<completedOn)throw new HRInputError('Expiry cannot be before completion.');}
export function assuranceState(record:{status:string;expiresOn:Date|null;dueOn?:Date|null},now=new Date()){const today=new Date(now.toISOString().slice(0,10)+'T00:00:00Z'),soon=new Date(today.getTime()+30*86400000);if(['CANCELLED','ARCHIVED'].includes(record.status))return 'Archived';if(record.expiresOn&&record.expiresOn<today)return 'Expired';if(record.expiresOn&&record.expiresOn<=soon)return 'Expires soon';if(record.status!=='COMPLETED'&&record.dueOn&&record.dueOn<today)return 'Overdue';return record.status==='COMPLETED'?'Completed':record.status==='ACTIVE'?'Current':record.status==='IN_PROGRESS'?'In progress':'Planned';}
