import Link from 'next/link';
import { requireSession } from '@/core/auth/session';
import { assertCapability, can } from '@/core/permissions/check';
import { db } from '@/core/db/client';
import { CreateDialog } from '@/components/ui/create-dialog';
import { StatusPill } from '@/components/ui/status-pill';
import { ContractComposer } from '@/components/contracts/composer';
import { canAccessContractSource } from '@/core/contracts/access';
import { parseBlocks } from '@/core/templates/domain';
import { ownerRestriction } from '@/modules/crm/services/visibility';
const labels:Record<string,string>={DRAFT:'Draft',SENT:'Sent',VIEWED:'Opened',RETURNED:'Returned · review needed',SIGNED:'Completed',DECLINED:'Declined',REVOKED:'Link revoked'};
export default async function Page({searchParams}:{searchParams:Promise<{q?:string;status?:string;customer?:string}>}){
 const s=await requireSession();assertCapability(s,'core.contract.manage');const f=await searchParams,q=typeof f.q==='string'?f.q.trim().slice(0,200):'',status=['DRAFT','SIGNED','RETURNED','DECLINED','REVOKED','waiting'].includes(f.status??'')?f.status??'':'';
 const [candidates,parties,templates,deals,accounts]=await Promise.all([
 db.contractDocument.findMany({where:{organisationId:s.organisationId,status:{not:'SUPERSEDED'},...(f.customer?{partyId:f.customer}:{}),...(q?{OR:[{title:{contains:q,mode:'insensitive'}},{reference:{contains:q,mode:'insensitive'}},{signerName:{contains:q,mode:'insensitive'}},{signerEmail:{contains:q,mode:'insensitive'}}]}:{})},select:{id:true,reference:true,title:true,status:true,kind:true,partyId:true,opportunityId:true,sourceModule:true,sourceType:true,sourceId:true,signerName:true,signerEmail:true,createdAt:true,signedAt:true},orderBy:{createdAt:'desc'},take:200}),
 db.party.findMany({where:{organisationId:s.organisationId,identityScrubbed:false,archived:false},select:{id:true,name:true},orderBy:{name:'asc'},take:2000}),
 db.documentTemplate.findMany({where:{organisationId:s.organisationId,status:'PUBLISHED',targetModules:{has:'crm'}},select:{id:true,name:true,titleTemplate:true,blocks:true},orderBy:{name:'asc'}}),
 can(s,'sales.opportunity.read')?db.opportunity.findMany({where:{organisationId:s.organisationId,ownerUserId:ownerRestriction(s)},select:{id:true,name:true,partyId:true},orderBy:{updatedAt:'desc'},take:200}):[],
 can(s,'core.email.send')?db.emailAccount.findMany({where:{organisationId:s.organisationId,active:true,OR:[{scope:'COMPANY'},{scope:'PERSONAL',ownerUserId:s.userId}]},select:{id:true,label:true},orderBy:{isDefault:'desc'}}):[]]);
 const allowed=await Promise.all(candidates.map(r=>canAccessContractSource(s,r))),all=candidates.filter((_,i)=>allowed[i]),rows=all.filter(r=>!status||(status==='waiting'?['SENT','VIEWED'].includes(r.status):r.status===status)),names=new Map(parties.map(p=>[p.id,p.name]));
 return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-semibold">Contracts & approvals</h2><p className="mt-1 max-w-2xl text-sm text-slate-500">Build a contract, attach it to a deal and share a branded customer link. Track online signatures and review returned PDFs here.</p></div><div className="flex items-center gap-3"><Link href="/templates" className="text-sm text-blue-700">Template library</Link><CreateDialog label="New contract" title="Build a contract"><ContractComposer parties={parties} templates={templates.map(t=>({...t,blocks:parseBlocks(t.blocks)}))} deals={deals} accounts={accounts}/></CreateDialog></div></div>
 <div className="grid gap-3 sm:grid-cols-4">{([['waiting','Waiting on customer'],['RETURNED','Returns to review'],['SIGNED','Completed'],['DRAFT','Drafts']] as const).map(([key,label])=><Link key={key} href={`/crm/contracts?status=${key}`} className={`rounded-2xl border bg-white p-5 ${key===status?'border-blue-500':'border-slate-200'}`}><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-3xl font-semibold">{all.filter(r=>key==='waiting'?['SENT','VIEWED'].includes(r.status):r.status===key).length}</p></Link>)}</div>
 <form className="flex flex-wrap items-end gap-3 rounded-2xl border border-slate-200 bg-white p-4"><label className="flex-1 text-xs text-slate-500">Search<input name="q" defaultValue={q} placeholder="Title, reference or signer" className="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2 text-sm"/></label><label className="text-xs text-slate-500">Status<select name="status" defaultValue={status} className="mt-1 block rounded-xl border border-slate-200 px-3 py-2 text-sm"><option value="">Everything</option><option value="waiting">Waiting on customer</option>{Object.entries(labels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label className="text-xs text-slate-500">Customer<select name="customer" defaultValue={f.customer??''} className="mt-1 block max-w-60 rounded-xl border border-slate-200 px-3 py-2 text-sm"><option value="">All customers</option>{parties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="rounded-xl bg-blue-600 px-4 py-2 text-sm text-white">Apply</button><Link href="/crm/contracts" className="text-sm text-slate-500">Reset</Link></form>
 <div className="divide-y divide-slate-100 overflow-hidden rounded-2xl border border-slate-200 bg-white">{rows.map(r=><Link key={r.id} href={`/crm/contracts/${r.id}`} className="flex flex-wrap items-center justify-between gap-4 px-5 py-5 hover:bg-slate-50"><div><p className="text-xs text-slate-400">{r.reference} · {r.kind==='QUOTE'?'Quotation approval':r.sourceModule?`${r.sourceModule.toUpperCase()} document`:'Contract'}</p><h3 className="mt-1 font-semibold">{r.title}</h3><p className="mt-1 text-xs text-slate-500">{names.get(r.partyId??'')??'Customer document'}{r.signerName?` · ${r.signerName}`:''}{r.opportunityId?' · Deal linked':''}</p></div><StatusPill label={labels[r.status]??r.status} tone={r.status==='SIGNED'?'success':r.status==='RETURNED'?'warning':r.status==='DECLINED'?'danger':'neutral'}/></Link>)}{!rows.length&&<p className="p-10 text-center text-sm text-slate-500">{q||status?'No documents match these filters.':'Create your first contract here or from a Deal.'}</p>}</div><p className="text-xs text-slate-400">Showing up to 200 recent documents within your record access.</p></div>;
}
