'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
export function ActionForm({action,children,label='Save'}:{action:(form:FormData)=>Promise<unknown>;children?:React.ReactNode;label?:string}){
 const [pending,start]=useTransition(),[result,setResult]=useState<unknown>(),[error,setError]=useState('');const router=useRouter();
 return <form className="space-y-3" method="post" onSubmit={event=>{event.preventDefault();if(pending)return;const form=new FormData(event.currentTarget,(event.nativeEvent as SubmitEvent).submitter);start(async()=>{setError('');setResult(undefined);try{const value=await action(form);if(value&&typeof value==='object'&&'error' in value&&typeof value.error==='string'){setError(value.error);return;}setResult(value??{saved:true});router.refresh();}catch(e){setError(e instanceof Error?e.message:'Unable to save. Please retry.');}});}}><fieldset disabled={pending} className="contents">{children}<Button type="submit" variant="primary" disabled={pending}>{pending?'Saving…':label}</Button></fieldset>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{result!==undefined&&<div role="status" className="rounded-lg bg-slate-50 p-3 text-sm">{typeof result==='object'&&result!==null&&'matched' in result?<AudienceResult value={result}/>:typeof result==='object'&&result!==null&&'processed' in result?`${result.processed} journey steps processed.`:typeof result==='object'&&result!==null&&'message' in result?String(result.message):'Saved.'}</div>}</form>;
}

function AudienceResult({value}:{value:object}){const v=value as {matched:number;eligible:number;excluded:number;reasons:Record<string,number>};return <><div className="grid grid-cols-3 gap-3">{[["Matched",v.matched],["Eligible",v.eligible],["Excluded",v.excluded]].map(([label,count])=><div key={label}><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-lg font-semibold">{count}</p></div>)}</div>{Object.entries(v.reasons).map(([reason,count])=><p className="mt-2 text-xs" key={reason}>{reason}: {count}</p>)}</>;}
