'use client';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { EVENT_TYPES } from '../domain/policy';
const style='rounded-lg border border-slate-200 bg-white px-2 py-2 text-sm';
export function AudienceBuilder(){
 const [join,setJoin]=useState('all');const [rows,setRows]=useState([{field:'country',operator:'eq',value:'GB'}]);
 return <fieldset className="space-y-3"><legend className="mb-2 text-sm font-medium">People who match</legend><select aria-label="Match rule groups" className={style} value={join} onChange={e=>setJoin(e.target.value)}><option value="all">All conditions (AND)</option><option value="any">Any condition (OR)</option></select>{rows.map((r,i)=><div key={i} className="grid grid-cols-2 gap-2"><select aria-label={`Condition ${i+1} field`} className={style} value={r.field} onChange={e=>setRows(rows.map((x,j)=>j===i?{...x,field:e.target.value}:x))}>{['country','lifecycle','score','source','brand','event'].map(f=><option key={f}>{f}</option>)}</select><select aria-label={`Condition ${i+1} comparison`} className={style} value={r.operator} onChange={e=>setRows(rows.map((x,j)=>j===i?{...x,operator:e.target.value}:x))}>{[['eq','is'],['neq','is not'],['gte','at least'],['lte','at most'],['contains','contains'],['exists','did event'],['absent','did not do event']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input aria-label={`Condition ${i+1} value`} className={`${style} col-span-2`} value={r.value} onChange={e=>setRows(rows.map((x,j)=>j===i?{...x,value:e.target.value}:x))}/>{rows.length>1&&<Button type="button" variant="ghost" onClick={()=>setRows(rows.filter((_,j)=>i!==j))}>Remove</Button>}</div>)}<Button type="button" onClick={()=>setRows([...rows,{field:'score',operator:'gte',value:'0'}])}>Add condition</Button><input type="hidden" name="rules" value={JSON.stringify({[join]:rows.map(r=>({...r,value:r.field==='score'?Number(r.value):r.value}))})}/></fieldset>;
}
export function JourneyBuilder(){const [nodes,setNodes]=useState<Array<{kind:string;hours?:number;event?:string}>>([{kind:'WAIT',hours:72},{kind:'END'}]);return <fieldset className="space-y-3"><legend className="text-sm font-medium">Customer path</legend>{nodes.map((n,i)=><div key={i} className="rounded-lg border border-slate-200 p-3"><p className="mb-2 text-xs text-slate-500">Step {i+1}</p><select aria-label={`Step ${i+1} kind`} className={style} value={n.kind} onChange={e=>setNodes(nodes.map((x,j)=>i===j?e.target.value==='WAIT'?{kind:'WAIT',hours:24}:e.target.value==='GOAL'?{kind:'GOAL',event:'PURCHASE_COMPLETED'}:{kind:'END'}:x))}><option value="WAIT">Wait</option><option value="GOAL">Check goal</option><option value="END">End journey</option></select>{n.kind==='WAIT'&&<label className="ml-2 text-sm">Hours <input aria-label={`Step ${i+1} wait hours`} className={`${style} w-20`} type="number" min={1} max={8760} value={n.hours} onChange={e=>setNodes(nodes.map((x,j)=>i===j?{...x,hours:Number(e.target.value)}:x))}/></label>}{n.kind==='GOAL'&&<select aria-label={`Step ${i+1} goal event`} className={`${style} mt-2 w-full`} value={n.event} onChange={e=>setNodes(nodes.map((x,j)=>i===j?{...x,event:e.target.value}:x))}>{EVENT_TYPES.map(t=><option key={t}>{t}</option>)}</select>}</div>)}<Button type="button" onClick={()=>setNodes([...nodes.slice(0,-1),{kind:'WAIT',hours:24},{kind:'END'}])}>Add wait step</Button><input name="nodes" type="hidden" value={JSON.stringify(nodes)}/></fieldset>;}
