'use client';
import { useState } from 'react';
import { CAMPAIGN_DETAIL_GROUPS, type CampaignDetails } from '../domain/campaign-details';
const field='mt-1 block w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm';
export function CampaignDetailsFields({details}:{details:CampaignDetails}) {
  const [custom,setCustom]=useState(details.custom.map((row,index)=>({...row,key:index})));
  const [resources,setResources]=useState(details.resources.map((row,index)=>({...row,key:index})));
  const [next,setNext]=useState(Math.max(custom.length,resources.length));
  return <div className="min-w-0 space-y-5">
    <input type="hidden" name="briefWorkspace" value="1"/>
    <p className="text-sm text-slate-600">Fill in what matters for this campaign. These details can be changed later.</p>
    {CAMPAIGN_DETAIL_GROUPS.map(group=><details key={group.title} className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer text-sm font-semibold">{group.title}</summary><div className="mt-4 grid gap-4 sm:grid-cols-2">{group.fields.map(([name,label,hint])=><label key={name} className="block text-sm font-medium">{label}<textarea name={`detail:${name}`} defaultValue={details.fields[name]??''} maxLength={5000} rows={3} placeholder={hint} className={field}/></label>)}</div></details>)}
    <section className="space-y-3 rounded-xl border border-slate-200 p-4"><h3 className="text-sm font-semibold">Custom information</h3><p className="text-xs text-slate-500">Add your own fields, such as event location, agency contact or offer terms.</p>{custom.map((row,index)=><div key={row.key} className="grid min-w-0 gap-2 sm:grid-cols-[minmax(0,1fr)_minmax(0,2fr)_auto]"><label className="text-sm">Field name {index+1}<input name="customLabel" maxLength={100} defaultValue={row.label} className={field}/></label><label className="text-sm">Field value {index+1}<textarea name="customValue" maxLength={5000} defaultValue={row.value} rows={2} className={field}/></label><button type="button" aria-label={`Remove custom field ${index+1}`} onClick={()=>setCustom(custom.filter(item=>item.key!==row.key))} className="self-end py-2 text-sm text-red-700">Remove</button></div>)}<button type="button" disabled={custom.length>=20} onClick={()=>{setCustom([...custom,{key:next,label:'',value:''}]);setNext(next+1);}} className="text-sm font-medium text-blue-700 disabled:text-slate-400">Add custom field</button></section>
    <section className="space-y-3 rounded-xl border border-slate-200 p-4"><h3 className="text-sm font-semibold">Resources and links</h3><p className="text-xs text-slate-500">Link to creative files, landing pages, research or supplier documents. Files stay in their original location.</p>{resources.map((row,index)=><div key={row.key} className="grid min-w-0 gap-2 sm:grid-cols-[minmax(0,1fr)_minmax(0,2fr)_auto]"><label className="text-sm">Resource name {index+1}<input name="resourceLabel" maxLength={150} defaultValue={row.label} className={field}/></label><label className="text-sm">Resource URL {index+1}<input name="resourceUrl" type="url" maxLength={2000} defaultValue={row.url} placeholder="https://" className={field}/></label><button type="button" aria-label={`Remove resource ${index+1}`} onClick={()=>setResources(resources.filter(item=>item.key!==row.key))} className="self-end py-2 text-sm text-red-700">Remove</button></div>)}<button type="button" disabled={resources.length>=20} onClick={()=>{setResources([...resources,{key:next,label:'',url:''}]);setNext(next+1);}} className="text-sm font-medium text-blue-700 disabled:text-slate-400">Add resource link</button></section>
  </div>;
}
