import { db } from "@/core/db/client";
import { timeSeries } from "@/core/analytics/buckets";
import type { AnalyticsProvider } from "@/core/analytics/types";
import { assertCapability } from "@/core/permissions/check";

export const logisticsAnalytics: AnalyticsProvider = [
  { id: "logistics.shipments", name: "Shipments", subject: "Logistics", definition: "Current shipments by status. Counts shipments, not freight cost or order value.", grain: "One shipment", capability: "logistics.shipment.read", href: "/logistics/dispatch", snapshot: true, query: async (session) => { assertCapability(session, "logistics.shipment.read"); const rows = await db.shipment.groupBy({ by: ["status"], where: { organisationId: session.organisationId }, _count: { _all: true } }); return rows.map((row) => ({ label: row.status.replaceAll("_", " "), value: row._count._all })); } },
  { id: "logistics.fulfilment", name: "Fulfilment", subject: "Logistics", definition: "Current fulfilment requirements by status. Counts requirements, not quantities or value.", grain: "One fulfilment requirement", capability: "logistics.fulfilment.read", href: "/logistics/fulfil", snapshot: true, query: async (session) => { assertCapability(session, "logistics.fulfilment.read"); const rows = await db.fulfilmentRequirement.groupBy({ by: ["status"], where: { organisationId: session.organisationId }, _count: { _all: true } }); return rows.map((row) => ({ label: row.status.replaceAll("_", " "), value: row._count._all })); } },
  { id: "logistics.shipments.trend", name: "Shipments over time", subject: "Logistics", definition: "Shipments created in the selected period, by week or by month on longer ranges. Uses the latest 8,000 records in that window. Counts shipments, not cost.", grain: "One shipment", capability: "logistics.shipment.read", href: "/logistics/dispatch", snapshot: false, shape: "trend", query: async (session, since) => { assertCapability(session, "logistics.shipment.read"); const rows = await db.shipment.findMany({ where: { organisationId: session.organisationId, ...(since ? { createdAt: { gte: since } } : {}) }, select: { createdAt: true }, orderBy: { createdAt: "desc" }, take: 8000 }); return timeSeries(rows.map((row) => row.createdAt), since); } },
];
