import { db } from '@/core/db/client';
import { recordDataset } from '@/core/reports/records';
import { text, date } from '@/core/reports/columns';
export const reports=[
recordDataset({id:'logistics.shipments',name:'Shipments',source:'Logistics',description:'Dispatch and delivery tracking; protected shipping costs are excluded.',anyOf:['logistics.shipment.read'],dateField:'createdAt',columns:[text('reference','Shipment'),text('customer','Customer','party.name'),text('status','Status'),text('carrierCode','Carrier'),text('trackingNumber','Tracking number'),date('plannedDispatchAt','Planned dispatch'),date('dispatchedAt','Dispatched'),date('expectedDeliveryAt','Expected delivery'),date('deliveredAt','Delivered'),date('createdAt','Created')]},
(s,w,take,skip)=>db.shipment.findMany({where:{AND:[{organisationId:s.organisationId},w]},select:{reference:true,party:{select:{name:true}},status:true,carrierCode:true,trackingNumber:true,plannedDispatchAt:true,dispatchedAt:true,expectedDeliveryAt:true,deliveredAt:true,createdAt:true},orderBy:[{createdAt:'desc'},{id:'asc'}],take,skip}),
(s,w)=>db.shipment.count({where:{AND:[{organisationId:s.organisationId},w]}}),r=>({reference:r.reference,customer:r.party.name,status:r.status,carrierCode:r.carrierCode,trackingNumber:r.trackingNumber,plannedDispatchAt:r.plannedDispatchAt,dispatchedAt:r.dispatchedAt,expectedDeliveryAt:r.expectedDeliveryAt,deliveredAt:r.deliveredAt,createdAt:r.createdAt})),
recordDataset({id:'logistics.fulfilment',name:'Fulfilment requirements',source:'Logistics',description:'Customer fulfilment requirements and promised dates.',anyOf:['logistics.fulfilment.read'],dateField:'createdAt',columns:[text('reference','Requirement'),text('customer','Customer','party.name'),text('status','Status'),text('fulfilmentMode','Mode'),date('requestedOn','Requested'),date('promisedOn','Promised'),date('createdAt','Created')]},
(s,w,take,skip)=>db.fulfilmentRequirement.findMany({where:{AND:[{organisationId:s.organisationId},w]},select:{reference:true,party:{select:{name:true}},status:true,fulfilmentMode:true,requestedOn:true,promisedOn:true,createdAt:true},orderBy:[{createdAt:'desc'},{id:'asc'}],take,skip}),
(s,w)=>db.fulfilmentRequirement.count({where:{AND:[{organisationId:s.organisationId},w]}}),r=>({reference:r.reference,customer:r.party.name,status:r.status,fulfilmentMode:r.fulfilmentMode,requestedOn:r.requestedOn,promisedOn:r.promisedOn,createdAt:r.createdAt}))];
