"use server";
import {requireSession} from '@/core/auth/session';
import {assertCapability} from '@/core/permissions/check';
import {assertModuleEnabled} from '@/core/modules/access';
import {db} from '@/core/db/client';
import {required,text,choice,integer,number,day,member,audit,changed} from '@/core/shared/operational-forms';
import {EQUIPMENT_STATES,WORK_TYPES,maintenanceTransition} from '../domain/rules';
import {revalidatePath} from 'next/cache';
import {redirect} from 'next/navigation';
export async function saveEquipment(f:FormData){
 const s=await requireSession();
 assertCapability(s,'maintenance.work.manage');
 await assertModuleEnabled(s,'maintenance');const id=text(f,'id'),data={code:required(f,'code',60).toUpperCase(),name:required(f,'name'),serialNumber:text(f,'serialNumber'),location:text(f,'location'),manufacturer:text(f,'manufacturer'),model:text(f,'model'),criticality:choice(text(f,'criticality')||'NORMAL',['LOW','NORMAL','HIGH','CRITICAL']),status:choice(text(f,'status')||'OPERATIONAL',EQUIPMENT_STATES),nextServiceAt:day(f,'nextServiceAt'),serviceIntervalDays:text(f,'serviceIntervalDays')?integer(f,'serviceIntervalDays',1,3650):null,notes:text(f,'notes',12000)};let saved=id;await db.$transaction(async tx=>{if(id)changed((await tx.maintenanceEquipment.updateMany({where:{id,organisationId:s.organisationId,version:integer(f,'version',1)},data:{...data,version:{increment:1}}})).count);else saved=(await tx.maintenanceEquipment.create({data:{...data,organisationId:s.organisationId}})).id;await audit(tx,s,'maintenance.equipment.saved','MaintenanceEquipment',saved,{code:data.code,status:data.status});});revalidatePath('/maintenance','layout');redirect('/maintenance/equipment/'+saved);
}
export async function createMaintenanceWork(f:FormData){
 const s=await requireSession();
 assertCapability(s,'maintenance.work.manage');
 await assertModuleEnabled(s,'maintenance');const equipmentId=text(f,'equipmentId')||null,vehicleId=text(f,'vehicleId')||null;if(Boolean(equipmentId)===Boolean(vehicleId))throw Error('Choose one equipment item or vehicle.');if(equipmentId&&!await db.maintenanceEquipment.findFirst({where:{id:equipmentId,organisationId:s.organisationId,status:{not:'RETIRED'}}}))throw Error('Equipment unavailable.');if(vehicleId){assertCapability(s,'fleet.vehicle.read');await assertModuleEnabled(s,'fleet');if(!await db.fleetVehicle.findFirst({where:{id:vehicleId,organisationId:s.organisationId,status:{not:'RETIRED'}}}))throw Error('Vehicle unavailable.');}const kind=choice(required(f,'kind'),WORK_TYPES),assigneeUserId=await member(s,text(f,'assigneeUserId'));let id='';await db.$transaction(async tx=>{const w=await tx.maintenanceWorkOrder.create({data:{organisationId:s.organisationId,equipmentId,vehicleId,title:required(f,'title'),kind,priority:choice(text(f,'priority')||'NORMAL',['LOW','NORMAL','HIGH','URGENT']),reportedByUserId:s.userId,assigneeUserId,dueAt:day(f,'dueAt'),findings:text(f,'findings',12000),downtimeStartedAt:f.get('downtime')==='on'?new Date():null}});id=w.id;await audit(tx,s,'maintenance.work.created','MaintenanceWorkOrder',id,{kind,equipmentId,vehicleId});});revalidatePath('/maintenance','layout');revalidatePath('/fleet','layout');redirect('/maintenance/work/'+id);
}
export async function updateMaintenanceWork(f:FormData){
 const s=await requireSession();
 assertCapability(s,'maintenance.work.manage');
 await assertModuleEnabled(s,'maintenance');const w=await db.maintenanceWorkOrder.findFirst({where:{id:required(f,'id'),organisationId:s.organisationId}});if(!w)throw Error('Work order unavailable.');if(w.vehicleId){assertCapability(s,'fleet.vehicle.read');await assertModuleEnabled(s,'fleet');}const status=required(f,'status');maintenanceTransition(w.status,status);const resolution=text(f,'resolution',12000);if(status==='COMPLETED'&&!resolution)throw Error('Record the completed repair or service.');const nextServiceAt=day(f,'nextServiceAt');if(nextServiceAt&&w.vehicleId)assertCapability(s,'fleet.vehicle.manage');await db.$transaction(async tx=>{changed((await tx.maintenanceWorkOrder.updateMany({where:{id:w.id,organisationId:s.organisationId,version:integer(f,'version',1),status:w.status},data:{status,findings:text(f,'findings',12000),resolution,actualMinutes:integer(f,'actualMinutes',0,525600),startedAt:w.startedAt??(status==='IN_PROGRESS'?new Date():null),completedAt:status==='COMPLETED'?new Date():null,downtimeEndedAt:['COMPLETED','CANCELLED'].includes(status)&&w.downtimeStartedAt?new Date():null,version:{increment:1}}})).count);if(status==='COMPLETED'&&nextServiceAt&&w.equipmentId)await tx.maintenanceEquipment.updateMany({where:{id:w.equipmentId,organisationId:s.organisationId},data:{nextServiceAt,version:{increment:1}}});if(status==='COMPLETED'&&nextServiceAt&&w.vehicleId)await tx.fleetVehicle.updateMany({where:{id:w.vehicleId,organisationId:s.organisationId},data:{serviceDueAt:nextServiceAt,version:{increment:1}}});await audit(tx,s,'maintenance.work.'+status.toLowerCase(),'MaintenanceWorkOrder',w.id);});revalidatePath('/maintenance','layout');revalidatePath('/fleet','layout');
}
export async function recordMaintenancePart(f:FormData){
 const s=await requireSession();
 assertCapability(s,'maintenance.work.manage');
 await assertModuleEnabled(s,'maintenance');assertCapability(s,'core.products.read');await assertModuleEnabled(s,'products');const id=required(f,'id'),productId=required(f,'productId');const w=await db.maintenanceWorkOrder.findFirst({where:{id,organisationId:s.organisationId}});if(!w)throw Error('Work order unavailable.');if(w.vehicleId){assertCapability(s,'fleet.vehicle.read');await assertModuleEnabled(s,'fleet');}if(!await db.product.findFirst({where:{id:productId,organisationId:s.organisationId,active:true}}))throw Error('Product unavailable.');await db.$transaction(async tx=>{changed((await tx.maintenanceWorkOrder.updateMany({where:{id,organisationId:s.organisationId,version:integer(f,'version',1),status:{in:['OPEN','IN_PROGRESS','WAITING_PARTS']}},data:{version:{increment:1}}})).count);const p=await tx.maintenancePart.create({data:{organisationId:s.organisationId,workOrderId:id,productId,quantity:number(f,'quantity',0.0001,1000000),note:required(f,'note',1000)}});await audit(tx,s,'maintenance.part.recorded','MaintenancePart',p.id,{workOrderId:id,productId});});revalidatePath('/maintenance','layout');
}
