"use server";
import {requireSession} from '@/core/auth/session';
import {assertCapability} from '@/core/permissions/check';
import {assertModuleEnabled} from '@/core/modules/access';
import {db} from '@/core/db/client';
import {required,integer,audit,changed,safeJoinUrl} from '@/core/shared/operational-forms';
import {graph,calendarPath} from './microsoft';
import {meetingAccess} from './queries';
import {revalidatePath} from 'next/cache';
export async function disconnectMicrosoftCalendar(){
 const s=await requireSession();
 assertCapability(s,'meetings.calendar.connect');
 await assertModuleEnabled(s,'meetings');await db.$transaction(async tx=>{await tx.microsoftCalendarConnection.deleteMany({where:{organisationId:s.organisationId,userId:s.userId}});await tx.meetingOAuthState.deleteMany({where:{organisationId:s.organisationId,userId:s.userId}});await audit(tx,s,'meetings.calendar.disconnected','User',s.userId);});revalidatePath('/meetings','layout');
}
export async function chooseMicrosoftCalendar(f:FormData){
 const s=await requireSession();
 assertCapability(s,'meetings.calendar.connect');
 await assertModuleEnabled(s,'meetings');const id=required(f,'calendarId',1000),list=await graph(s,'/me/calendars?$top=100&$select=id,name,canEdit') as {value:{id:string;name:string;canEdit:boolean}[]};const c=list.value.find(c=>c.id===id&&c.canEdit);if(!c)throw Error('Choose an editable connected calendar.');await db.$transaction(async tx=>{await tx.microsoftCalendarConnection.update({where:{organisationId_userId:{organisationId:s.organisationId,userId:s.userId}},data:{calendarId:c.id,calendarName:c.name.slice(0,200)}});await audit(tx,s,'meetings.calendar.selected','User',s.userId);});revalidatePath('/meetings','layout');
}
export async function sendMicrosoftMeeting(f:FormData){
 const s=await requireSession();
 assertCapability(s,'meetings.meeting.manage');
 assertCapability(s,'meetings.calendar.connect');await assertModuleEnabled(s,'meetings');const id=required(f,'id'),m=await meetingAccess(s,id);if(m.organiserUserId!==s.userId||m.status!=='SCHEDULED'||m.version!==integer(f,'version',1))throw Error('Refresh this scheduled meeting as its organiser before sending.');if(f.get('confirmSend')!=='on')throw Error('Confirm the invitation and attendee list before sending.');if(m.microsoftEventId&&!m.microsoftManaged)throw Error('Edit imported invitations in Outlook; Atlas retains the linked notes without replacing external attendees.');const c=await db.microsoftCalendarConnection.findUniqueOrThrow({where:{organisationId_userId:{organisationId:s.organisationId,userId:s.userId}}});if(m.microsoftOwnerUserId&&m.microsoftOwnerUserId!==s.userId)throw Error('Only the connected organiser can update this invitation.');if(m.microsoftCalendarId&&m.microsoftCalendarId!==c.calendarId)throw Error('Select the original Outlook calendar before updating this meeting.');const members=await db.membership.findMany({where:{organisationId:s.organisationId,active:true,userId:{in:m.attendeeUserIds}},select:{user:{select:{email:true,name:true}}}});if(members.length!==m.attendeeUserIds.length)throw Error('An attendee has left the company. Update the meeting before sending.');const body={subject:m.title,start:{dateTime:m.startsAt.toISOString(),timeZone:'UTC'},end:{dateTime:(m.endsAt??new Date(+m.startsAt+3600000)).toISOString(),timeZone:'UTC'},body:{contentType:'text',content:(m.agenda??'')+'\n\nAtlas notes and actions: https://atlassystem.online/meetings/'+m.id},location:{displayName:m.location??''},attendees:members.map(x=>({emailAddress:{address:x.user.email,name:x.user.name},type:'required'})),...(!m.microsoftEventId?{transactionId:m.id,isOnlineMeeting:f.get('teams')==='on',...(f.get('teams')==='on'?{onlineMeetingProvider:'teamsForBusiness'}:{})}:{})};const path=calendarPath(c.calendarId)+(m.microsoftEventId?'/'+encodeURIComponent(m.microsoftEventId):'');let remote=await graph(s,path,{method:m.microsoftEventId?'PATCH':'POST',body:JSON.stringify(body)}) as {id?:string;onlineMeeting?:{joinUrl?:string}}|null;if(!remote&&m.microsoftEventId)remote=await graph(s,path);if(!remote?.id)throw Error('Microsoft returned no event identity. Check Outlook before retrying.');const eventId=remote.id,joinUrl=remote.onlineMeeting?.joinUrl?safeJoinUrl(remote.onlineMeeting.joinUrl):m.joinUrl;await db.$transaction(async tx=>{changed((await tx.meeting.updateMany({where:{id,organisationId:s.organisationId,version:m.version,organiserUserId:s.userId,status:'SCHEDULED'},data:{microsoftManaged:true,microsoftEventId:eventId,microsoftOwnerUserId:s.userId,microsoftCalendarId:c.calendarId,joinUrl,version:{increment:1}}})).count);await audit(tx,s,'meetings.calendar.invitation_sent','Meeting',id,{eventId});});revalidatePath('/meetings','layout');
}
export async function importMicrosoftMeetings(){
 const s=await requireSession();
 assertCapability(s,'meetings.meeting.manage');
 assertCapability(s,'meetings.calendar.connect');await assertModuleEnabled(s,'meetings');const c=await db.microsoftCalendarConnection.findUniqueOrThrow({where:{organisationId_userId:{organisationId:s.organisationId,userId:s.userId}}}),start=new Date(Date.now()-30*86400000).toISOString(),end=new Date(Date.now()+90*86400000).toISOString(),prefix=c.calendarId==='primary'?'/me/calendarView':'/me/calendars/'+encodeURIComponent(c.calendarId)+'/calendarView';const result=await graph(s,prefix+'?'+new URLSearchParams({startDateTime:start,endDateTime:end,'$top':'100','$select':'id,subject,start,end,location,onlineMeeting,isCancelled'})) as {value:{id:string;subject:string;start:{dateTime:string};end:{dateTime:string};location?:{displayName?:string};onlineMeeting?:{joinUrl?:string};isCancelled?:boolean}[];'@odata.nextLink'?:string};if(result['@odata.nextLink'])throw Error('This calendar has over 100 events in the import window. Choose a smaller dedicated calendar; no partial import was applied.');await db.$transaction(async tx=>{for(const event of result.value){const startsAt=new Date(event.start.dateTime.endsWith('Z')?event.start.dateTime:event.start.dateTime+'Z'),endsAt=new Date(event.end.dateTime.endsWith('Z')?event.end.dateTime:event.end.dateTime+'Z');if(!Number.isFinite(+startsAt)||!Number.isFinite(+endsAt)||+endsAt<=+startsAt)throw Error('Microsoft returned an invalid meeting time.');const existing=await tx.meeting.findFirst({where:{organisationId:s.organisationId,microsoftOwnerUserId:s.userId,microsoftCalendarId:c.calendarId,microsoftEventId:event.id}});const data={title:(event.subject||'Outlook meeting').slice(0,200),startsAt,endsAt,location:event.location?.displayName?.slice(0,300)??null,joinUrl:event.onlineMeeting?.joinUrl?safeJoinUrl(event.onlineMeeting.joinUrl):null,status:event.isCancelled?'CANCELLED':'SCHEDULED'};if(existing){if(existing.status==='COMPLETED')continue;changed((await tx.meeting.updateMany({where:{id:existing.id,organisationId:s.organisationId,version:existing.version},data:{...data,version:{increment:1}}})).count);}else if(!event.isCancelled)await tx.meeting.create({data:{...data,organisationId:s.organisationId,organiserUserId:s.userId,attendeeUserIds:[],visibility:'PRIVATE',microsoftOwnerUserId:s.userId,microsoftCalendarId:c.calendarId,microsoftEventId:event.id}});}await tx.microsoftCalendarConnection.update({where:{id:c.id},data:{lastSyncAt:new Date()}});await audit(tx,s,'meetings.calendar.imported','User',s.userId,{events:result.value.length});},{timeout:30000});revalidatePath('/meetings','layout');
}
