import {db} from '@/core/db/client';
import type {Session} from '@/core/auth/session';
import {encryptSecret,decryptSecret} from '@/core/security/secrets';
export function microsoftReady(){return Boolean(process.env.ATLAS_MICROSOFT_CLIENT_ID&&process.env.ATLAS_MICROSOFT_CLIENT_SECRET);}
export const callbackUrl='https://atlassystem.online/meetings/microsoft/callback';
export function tokenUrl(){const tenant=process.env.ATLAS_MICROSOFT_TENANT_ID||'organizations';if(!/^[a-zA-Z0-9.-]+$/.test(tenant))throw Error('Microsoft tenant configuration is invalid.');return `https://login.microsoftonline.com/${tenant}/oauth2/v2.0/token`;}
export async function tokenRequest(body:URLSearchParams){if(!microsoftReady())throw Error('Microsoft calendar connection is not configured by your Atlas administrator.');body.set('client_id',process.env.ATLAS_MICROSOFT_CLIENT_ID!);body.set('client_secret',process.env.ATLAS_MICROSOFT_CLIENT_SECRET!);const r=await fetch(tokenUrl(),{method:'POST',body,signal:AbortSignal.timeout(15000),cache:'no-store'});if(!r.ok)throw Error('Microsoft connection expired or could not be authorised. Reconnect your calendar.');const t=await r.json() as {access_token?:string;refresh_token?:string;expires_in?:number};if(!t.access_token||!t.refresh_token||!t.expires_in)throw Error('Microsoft did not return a reusable calendar connection.');return t as {access_token:string;refresh_token:string;expires_in:number};}
export async function graph(s:Session,path:string,init:RequestInit={}){let c=await db.microsoftCalendarConnection.findUnique({where:{organisationId_userId:{organisationId:s.organisationId,userId:s.userId}}});if(!c)throw Error('Connect your Outlook calendar first.');if(+c.expiresAt<Date.now()+60000){const t=await tokenRequest(new URLSearchParams({grant_type:'refresh_token',refresh_token:decryptSecret(c.refreshToken)}));c=await db.microsoftCalendarConnection.update({where:{id:c.id},data:{accessToken:encryptSecret(t.access_token),refreshToken:encryptSecret(t.refresh_token),expiresAt:new Date(Date.now()+t.expires_in*1000)}});}if(!path.startsWith('/me/')||path.includes('..'))throw Error('Unsupported Microsoft calendar request.');const response=await fetch('https://graph.microsoft.com/v1.0'+path,{...init,headers:{Authorization:'Bearer '+decryptSecret(c.accessToken),'Content-Type':'application/json',Prefer:'outlook.timezone="UTC"',...init.headers},cache:'no-store',signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error(response.status===403?'Microsoft denied access to this calendar. Check the calendar permissions.':'Microsoft calendar could not be reached. Nothing is marked as sent; refresh or reconnect before retrying.');return response.status===204?null:await response.json();}
export function calendarPath(calendarId:string){return calendarId==='primary'?'/me/events':'/me/calendars/'+encodeURIComponent(calendarId)+'/events';}
export function outlookDraft(m:{title:string;startsAt:Date;endsAt:Date|null;location:string|null;id:string}){return 'https://outlook.office.com/calendar/0/deeplink/compose?'+new URLSearchParams({subject:m.title,startdt:m.startsAt.toISOString(),enddt:(m.endsAt??new Date(+m.startsAt+3600000)).toISOString(),location:m.location??'',body:'Agenda, notes and actions: https://atlassystem.online/meetings/'+m.id}).toString();}
