import Link from 'next/link';
import {notFound} from 'next/navigation';
import {UserRound,ShieldCheck,Link2,LockKeyhole} from 'lucide-react';
import {requireSession} from '@/core/auth/session';
import {assertCapability,can} from '@/core/permissions/check';
import {db} from '@/core/db/client';
import {memberAccessRevision} from '@/core/permissions/access-revision';
import {effectiveRoleCapabilities} from '@/core/permissions/access-levels';
import {applyCompanyAccessRestrictions,COMPANY_ACCESS_AREAS,hasCompanyAreaAccess} from '@/core/permissions/company-access';
import {AccessEditor} from '@/components/admin/access-editor';
import {RecoveryForm} from '@/components/admin/recovery-form';
import {ActionForm} from '@/components/ui/action-form';
import {setUserStatus,revokeUserSessions,saveUserAccess,linkEmployeeProfile} from '../../user-actions';
import {accessGroups} from '../../access-groups';
export default async function UserAdministration({params}:{params:Promise<{membershipId:string}>}){
 const session=await requireSession();assertCapability(session,'core.users.manage');const {membershipId}=await params;
 const member=await db.membership.findFirst({where:{id:membershipId,organisationId:session.organisationId},include:{user:{select:{id:true,name:true,email:true,createdAt:true}},roles:{include:{role:true}}}});if(!member)notFound();
 const self=member.id===session.membershipId,manageHR=can(session,'people.employee.manage'),viewHR=can(session,'people.employee.read');
 const [roles,company,employees]=await Promise.all([db.role.findMany({where:{organisationId:session.organisationId},orderBy:{name:'asc'}}),db.organisation.findUniqueOrThrow({where:{id:session.organisationId},select:{restrictedAccessAreas:true}}),manageHR||viewHR?db.employee.findMany({where:{organisationId:session.organisationId,...(!manageHR?{userId:member.userId}:{})},select:{id:true,userId:true,firstName:true,lastName:true,jobTitle:true,department:true,employeeNumber:true},orderBy:{lastName:'asc'}}):[]]);
 const linked=employees.find(e=>e.userId===member.userId),caps=effectiveRoleCapabilities(member.roles.map(r=>r.role),member.grantedCapabilities,member.deniedCapabilities),effective=applyCompanyAccessRestrictions(caps,company.restrictedAccessAreas);
 return <div className="space-y-6"><Link href="/settings?tab=users" className="inline-flex rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs text-slate-500">← All users</Link><section className="flex flex-wrap items-center gap-5 rounded-2xl border border-slate-200 bg-white p-6"><span className="flex size-16 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><UserRound size={28}/></span><div className="flex-1"><h2 className="text-2xl font-semibold tracking-tight">{member.user.name}{self&&<span className="ml-2 text-sm text-slate-400">You</span>}</h2><p className="mt-1 break-all text-sm text-slate-500">{member.user.email}</p><p className="mt-3 text-xs text-slate-400">Joined {member.createdAt.toLocaleDateString('en-GB')} · {member.lastLoginAt?'Last sign-in '+member.lastLoginAt.toLocaleString('en-GB'):'Not signed in yet'}</p></div><span className={`rounded-full px-4 py-2 text-xs font-medium ${member.active?'bg-emerald-50 text-emerald-600':'bg-amber-50 text-amber-600'}`}>{member.active?'Active':'Suspended'}</span></section>
 <div className="grid gap-5 lg:grid-cols-3"><div className="space-y-5 lg:col-span-2"><section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="mb-6 flex items-center gap-3"><ShieldCheck size={20} className="text-blue-500"/><h3 className="font-semibold">Roles & individual access</h3></div>{can(session,'core.roles.manage')?<AccessEditor key={memberAccessRevision(member,roles)} membershipId={member.id} accessRevision={memberAccessRevision(member,roles)} capabilities={[...caps]} groups={accessGroups()} roles={roles} roleIds={member.roles.map(r=>r.roleId)} granted={member.grantedCapabilities} denied={member.deniedCapabilities} action={saveUserAccess} disabled={self}/>:<p className="text-sm text-slate-500">Role administration permission is needed to edit access. Assigned roles: {member.roles.map(r=>r.role.name).join(', ')||'None'}.</p>}</section></div>
 <aside className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-sm font-semibold">Effective workspace access</h3><p className="mt-2 text-xs leading-relaxed text-slate-400">Company restrictions override assigned roles and individual grants.</p><div className="mt-4 divide-y divide-slate-100">{COMPANY_ACCESS_AREAS.map(area=><div key={area.id} className="flex justify-between gap-3 py-3 text-xs"><span>{area.label}</span><span className="text-slate-400">{company.restrictedAccessAreas.includes(area.id)?'Off for company':hasCompanyAreaAccess(effective, area)?'Can view':'No view access'}</span></div>)}</div><p className="mt-2 text-xs text-slate-400">{effective.size} effective permissions {member.active?'':'· sign-in suspended'}</p></section>
 <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><Link2 size={18} className="text-blue-500"/><h3 className="text-sm font-semibold">Employee profile</h3></div>{linked?<div className="mt-4"><p className="text-sm">{linked.firstName} {linked.lastName}</p><p className="mt-1 text-xs text-slate-400">{linked.jobTitle} · {linked.department??'No department'}</p>{viewHR&&<Link href={`/people/${linked.id}`} className="mt-3 inline-block text-xs text-blue-600">Open employee record →</Link>}</div>:<p className="mt-3 text-xs text-slate-400">{manageHR||viewHR?'No linked employee record.':'Employee details require HR permission.'}</p>}{manageHR&&<ActionForm action={linkEmployeeProfile} className="mt-5 space-y-3"><input type="hidden" name="membershipId" value={member.id}/><label className="block text-xs">Link existing employee<select name="employeeId" defaultValue={linked?.id??''} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-xs"><option value="">No employee link</option>{employees.filter(e=>!e.userId||e.userId===member.userId).map(e=><option key={e.id} value={e.id}>{e.employeeNumber} · {e.firstName} {e.lastName}</option>)}</select></label><button className="rounded-lg bg-blue-50 px-4 py-2 text-xs text-blue-600">Save employee link</button></ActionForm>}</section>
 <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><LockKeyhole size={18} className="text-blue-500"/><h3 className="text-sm font-semibold">Account security</h3></div>{self?<Link href="/profile" className="mt-4 inline-block text-xs text-blue-600">Manage your password & sessions →</Link>:<div className="mt-4 space-y-5"><ActionForm action={setUserStatus} className="space-y-2"><input type="hidden" name="membershipId" value={member.id}/><input type="hidden" name="status" value={member.active?'SUSPENDED':'ACTIVE'}/><p className="text-xs leading-relaxed text-slate-500">{member.active?'Suspending immediately blocks access on every device. Records are preserved.':'Restore sign-in access with their existing permissions.'}</p><button className={`rounded-xl px-4 py-2.5 text-xs font-medium ${member.active?'bg-amber-50 text-amber-700':'bg-blue-50 text-blue-600'}`}>{member.active?'Suspend access':'Restore access'}</button></ActionForm><ActionForm action={revokeUserSessions} className="space-y-2"><input type="hidden" name="membershipId" value={member.id}/><p className="text-xs text-slate-500">Require this user to sign in again on their devices.</p><button className="rounded-xl border border-slate-200 px-4 py-2.5 text-xs">Revoke company sessions</button></ActionForm>{member.active&&<details className="border-t border-slate-100 pt-4"><summary className="cursor-pointer text-xs font-semibold text-blue-600">Reset password</summary><div className="mt-4"><RecoveryForm membershipId={member.id}/></div></details>}</div>}</section></aside></div></div>;
}
