import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireSession } from '@/core/auth/session';
import { assertCapability } from '@/core/permissions/check';
import { db } from '@/core/db/client';
import { caseRecord, serviceQueues, serviceMembers } from '@/modules/service/services/queries';
import { updateCase, assignCase, transitionCase, addCaseEntry, createDepartmentTicket, linkCaseRecord, getCaseOwners, creditChoices, askFinanceForCredit } from '@/modules/service/services/commands';
import { SERVICE_CREDIT_REASONS } from '@/modules/service/domain/credit';
import { money } from '@/modules/finance/domain/money';
import { ActionForm } from '@/modules/service/components/action-form';
import { Field, Select, TextArea, RecordVersion, inputClass } from '@/modules/service/components/fields';
import { CASE_TYPES, CASE_STATUSES, PRIORITIES, SEVERITIES, RESOLUTION_CODES, label, nextAction, isComplaint } from '@/modules/service/domain/workflow';
import { readManagerPolicy, serviceNeedsManagerSignOff } from '@/core/permissions/manager-level';
import { readCompanyProfile } from '@/core/setup/company-profile';
import { formatMoney } from '@/core/shared/money';
import { Card } from '@/components/ui/card';
import { StatusPill } from '@/components/ui/status-pill';
export default async function Case({params}:{params:Promise<{caseId:string}>}) {
 const session=await requireSession();assertCapability(session,'service.case.read');const {caseId}=await params;const c=await caseRecord(session,caseId);if(!c)notFound();
 const [queues,members,party]=await Promise.all([serviceQueues(session),serviceMembers(session),session.capabilities.has('customers.read')?db.party.findFirst({where:{id:c.partyId,organisationId:session.organisationId},select:{id:true,name:true,customerCode:true}}):null]);
 const owners=session.capabilities.has('service.case.assign')?await getCaseOwners():[];
 const names=new Map(members.map(m=>[m.userId,m.user.name])),can=(s:string)=>session.capabilities.has(s);
 const lastUpdate=c.entries.filter(e=>e.kind==='EXTERNAL_LOG').at(-1)?.createdAt??null;
 const orders=can('sales.order.read')?await db.salesOrder.findMany({where:{organisationId:session.organisationId,partyId:c.partyId},select:{id:true,reference:true,commercialStatus:true,grossAmount:true,currency:true},orderBy:{createdAt:'desc'},take:30}):[];
 const company=await db.organisation.findUniqueOrThrow({where:{id:session.organisationId},select:{managerPolicy:true,companyProfile:true}});
 const companyCurrency=readCompanyProfile(company.companyProfile).defaultCurrency;
 const linkedIds=c.links.filter(link=>link.entityType==='SalesOrder').map(link=>link.entityId);
 const linkedValues=linkedIds.length?await db.salesOrder.findMany({where:{organisationId:session.organisationId,id:{in:linkedIds}},select:{grossAmount:true,currency:true}}):[];
 const managerSignOff=serviceNeedsManagerSignOff(readManagerPolicy(company.managerPolicy),{complaint:isComplaint(c.type),foreign:linkedValues.some(order=>order.currency!==companyCurrency),linkedGross:linkedValues.filter(order=>order.currency===companyCurrency).reduce((sum,order)=>sum+order.grossAmount,0)});
 const canSignOff=can('service.case.approve');
 const products=can('core.products.read')?await db.product.findMany({where:{organisationId:session.organisationId},select:{id:true,name:true},take:100,orderBy:{name:'asc'}}):[];
 const orderMap=new Map(orders.map(o=>[o.id,o]));
 const credit=await creditChoices(c.id);
 return <div className="space-y-5"><Link href="/service/cases" className="text-xs text-blue-700">← Cases</Link><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-medium text-slate-500">{c.number} · {label(c.type)} · {label(c.security)}</p><h2 className="mt-1 text-2xl font-semibold">{c.subject}</h2><p className="mt-2 text-sm text-slate-500">Owner: {names.get(c.ownerUserId)??'Company member'} · {label(c.priority)} priority · {c.severity} · {label(c.channel)}</p></div><StatusPill label={label(c.status)} tone={c.status==='CLOSED'?'success':'neutral'}/></div>
 <div className="rounded-lg border border-teal-200 bg-teal-50 px-4 py-3"><p className="text-xs font-semibold text-teal-800">Next action</p><p className="mt-1 text-sm">{nextAction(c,c.tickets,lastUpdate)}</p></div>
 {managerSignOff&&<div className={`rounded-lg border px-4 py-3 text-sm ${canSignOff?'border-amber-200 bg-amber-50':'border-slate-200 bg-white'}`}><p className="font-medium">{isComplaint(c.type)?'A customer service manager signs off this complaint.':'A customer service manager signs off this high-value query.'}</p>{linkedValues.length>0&&<p className="mt-1 text-slate-600">Linked orders {linkedValues.map(order=>formatMoney(order.grossAmount,order.currency)).join(', ')}.</p>}{!canSignOff&&<p className="mt-1 text-slate-500">You can keep working the case. Resolving or closing it waits for a manager.</p>}</div>}
 <div className="grid gap-5 lg:grid-cols-[minmax(0,1.6fr)_minmax(0,1fr)]"><div className="space-y-5"><Card className="p-5"><h3 className="font-semibold">Customer conversation & timeline</h3><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{c.description||'No initial description recorded.'}</p><div className="mt-4 divide-y divide-slate-200">{c.entries.map(e=><article key={e.id} className="py-4"><div className="flex flex-wrap justify-between gap-2 text-xs"><strong>{e.kind==='INTERNAL_NOTE'?'Internal note — employees only':e.kind==='CUSTOMER_CONTACT'?'Customer contact recorded':e.kind==='EXTERNAL_LOG'?'Customer update logged externally':label(e.kind)}</strong><span className="text-slate-500">{e.createdAt.toLocaleString('en-GB',{timeZone:'Europe/London'})}</span></div><p className="mt-1 text-xs text-slate-500">{names.get(e.authorUserId)??'Company member'} · {e.visibility==='INTERNAL'?'Internal — never customer visible':'Customer-facing communication log'}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm">{e.body}</p></article>)}</div></Card>
 {can('service.case.note')||can('service.case.communication')?<Card className="p-5"><h3 className="mb-3 font-semibold">Record communication</h3><ActionForm action={addCaseEntry} label="Add to timeline"><RecordVersion id={c.id} version={c.version}/><Select title="Communication type" name="kind" options={[...(can('service.case.note')?['INTERNAL_NOTE']:[]),...(can('service.case.communication')?['CUSTOMER_CONTACT','EXTERNAL_LOG']:[])]}/><TextArea title="Note / conversation summary" name="body" required/><p className="text-xs text-slate-500">External log records a customer update you have already made by phone or another channel. Atlas does not send an email from this form.</p></ActionForm></Card>:null}
 <Card className="p-5"><div className="flex justify-between"><h3 className="font-semibold">Departmental dependencies</h3><Link className="text-xs text-blue-700" href="/service/tickets">Department queues →</Link></div><p className="mt-2 text-xs text-slate-500">Internal deadlines are agreed due dates. Business-hours OLA policies are a later phase.</p><div className="mt-3 space-y-3">{c.tickets.map(t=><div key={t.id} className="rounded-lg border border-slate-200 p-3"><div className="flex justify-between text-sm"><strong>{t.number} · {t.queue.name}</strong><span>{label(t.status)}</span></div><p className="mt-1 text-sm">{t.subject}</p><p className={`mt-2 text-xs ${t.dueAt<new Date()&&!['COMPLETE','CANCELLED'].includes(t.status)?'text-red-700':'text-slate-500'}`}>Due {t.dueAt.toLocaleString('en-GB',{timeZone:'Europe/London'})} · {t.ownerUserId?names.get(t.ownerUserId)??'Company member':'Unassigned'}</p>{t.outcome&&<p className="mt-2 whitespace-pre-wrap text-sm">Internal outcome: {t.outcome}</p>}{t.customerSafeSummary&&<p className="mt-2 whitespace-pre-wrap text-sm text-teal-800">Customer-safe summary: {t.customerSafeSummary}</p>}</div>)}{c.tickets.length===0&&<p className="text-sm text-slate-500">No department tickets yet.</p>}</div>
 {can('service.ticket.create')&&<details className="mt-4"><summary className="cursor-pointer text-sm font-medium">Create department ticket</summary><ActionForm action={createDepartmentTicket} className="mt-3" label="Create internal ticket"><RecordVersion id={c.id} version={c.version}/><label className="block text-xs">Queue<select className={inputClass} name="queueId" required><option value="">Choose department</option>{queues.filter(q=>q.active).map(q=><option key={q.id} value={q.id}>{q.name}</option>)}</select></label><Field title="Required work" name="subject" required maxLength={250}/><TextArea title="Investigation brief" name="description" required maxLength={10000}/><Field title="Department response due (UTC)" name="dueAt" type="datetime-local" required/><p className="text-xs text-slate-500">The department may pick up the ticket. The case stays owned by {names.get(c.ownerUserId)??'Customer Service'}.</p></ActionForm></details>}</Card>
 </div><aside className="space-y-4"><Card className="p-5"><h3 className="font-semibold">Customer context</h3>{party?<Link href={`/customers/${party.id}`} className="mt-2 block text-sm text-blue-700">{party.customerCode} · {party.name}</Link>:<p className="mt-2 text-sm">Customer details require Customer Master access.</p>}<p className="mt-3 text-xs text-slate-500">Opened {c.createdAt.toLocaleString('en-GB',{timeZone:'Europe/London'})} · Reopened {c.reopenCount} times</p>{c.customerUpdateDueAt&&<p className="mt-3 text-sm">Promised update: {c.customerUpdateDueAt.toLocaleString('en-GB',{timeZone:'Europe/London'})}</p>}</Card>
 {(can('service.case.update')||credit.sent)&&<Card className="p-5"><h3 className="font-semibold">Credit against this customer</h3><p className="mt-2 text-xs text-slate-500">A complaint, damage, shortage or pricing query can ask Finance to raise a credit on the customer’s invoice. The balance does not change until Finance posts it.</p>{credit.sent&&<p className="mt-3 text-sm">{can('finance.overview.read')?<Link className="text-blue-700" href={`/finance/documents/${credit.sent.id}`}>{credit.sent.reference}</Link>:<span>{credit.sent.reference}</span>} is {credit.sent.status.replaceAll('_',' ').toLowerCase()} with Finance.</p>}{can('service.case.update')&&!credit.sent&&credit.invoices.length>0&&<ActionForm action={askFinanceForCredit} className="mt-3" label="Send to Finance"><RecordVersion id={c.id} version={c.version}/><label className="block text-xs">Why<select className={inputClass} name="reason" required>{SERVICE_CREDIT_REASONS.map(reason=><option key={reason}>{reason}</option>)}</select></label><label className="block text-xs">Invoice<select className={inputClass} name="invoiceId" required>{credit.invoices.map(invoice=><option key={invoice.id} value={invoice.id}>{invoice.reference} · {money(invoice.outstanding,invoice.currency)} still owed</option>)}</select></label><Field title="Credit amount" name="amount" required inputMode="decimal" placeholder="0.00"/><TextArea title="What happened" name="note" maxLength={2000}/></ActionForm>}{can('service.case.update')&&!credit.sent&&!credit.invoices.length&&<p className="mt-3 text-sm text-slate-500">This customer has no posted invoice with a balance. Finance can raise the credit once an invoice is posted.</p>}</Card>}
 <Card className="p-5"><h3 className="font-semibold">ERP context</h3><div className="mt-3 space-y-2">{c.links.map(l=>{const order=orderMap.get(l.entityId);return <p key={l.id} className="text-sm">{l.entityType==='SalesOrder'&&can('sales.order.read')?<Link className="text-blue-700" href={`/sales/orders/${l.entityId}`}>{order?.reference??'Linked order'}{order?` · ${label(order.commercialStatus)}`:''}</Link>:l.entityType==='Product'&&can('core.products.read')?`Product · ${products.find(p=>p.id===l.entityId)?.name??'Linked product'}`:l.entityType==='FinanceDocument'?can('finance.overview.read')?<Link className="text-blue-700" href={`/finance/documents/${l.entityId}`}>Credit with Finance</Link>:'Credit sent to Finance':'ERP record linked — source access required'}</p>;})}{!c.links.length&&<p className="text-sm text-slate-500">No ERP links yet.</p>}</div>{can('service.case.update')&&(orders.length>0||products.length>0)&&<details className="mt-3"><summary className="cursor-pointer text-sm">Link existing record</summary>{orders.length>0&&<ActionForm action={linkCaseRecord} label="Link order" className="mt-3"><RecordVersion id={c.id} version={c.version}/><input type="hidden" name="entityType" value="SalesOrder"/><label className="block text-xs">Order<select className={inputClass} name="entityId">{orders.map(o=><option key={o.id} value={o.id}>{o.reference}</option>)}</select></label></ActionForm>}{products.length>0&&<ActionForm action={linkCaseRecord} label="Link product" className="mt-3"><RecordVersion id={c.id} version={c.version}/><input type="hidden" name="entityType" value="Product"/><label className="block text-xs">Product<select className={inputClass} name="entityId">{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></ActionForm>}</details>}</Card>
 {can('service.case.assign')&&<Card className="p-5"><h3 className="mb-3 font-semibold">Case ownership</h3><ActionForm action={assignCase}><RecordVersion id={c.id} version={c.version}/><label className="block text-xs">Customer Service owner<select className={inputClass} name="ownerUserId" defaultValue={c.ownerUserId}>{owners.map(m=><option key={m.userId} value={m.userId}>{m.name}</option>)}</select></label></ActionForm></Card>}
 {can('service.case.update')&&<><Card className="p-5"><h3 className="mb-3 font-semibold">Classification & promises</h3><ActionForm action={updateCase}><RecordVersion id={c.id} version={c.version}/><Select title="Type" name="type" options={CASE_TYPES} defaultValue={c.type}/><Field title="Category" name="category" defaultValue={c.category} maxLength={250}/><Select title="Priority" name="priority" options={PRIORITIES} defaultValue={c.priority}/><Select title="Severity" name="severity" options={SEVERITIES} defaultValue={c.severity}/><TextArea title="Root cause (after investigation)" name="rootCause" defaultValue={c.rootCause??''} maxLength={2000}/><Field title="Promised customer update (UTC)" name="customerUpdateDueAt" type="datetime-local" defaultValue={c.customerUpdateDueAt?.toISOString().slice(0,16)??''}/></ActionForm></Card><Card className="p-5"><h3 className="mb-3 font-semibold">Workflow & resolution</h3><ActionForm action={transitionCase} label="Change status"><RecordVersion id={c.id} version={c.version}/><Select title="Next status" name="status" options={CASE_STATUSES.filter(s=>(s!=='RESOLVED'||can('service.case.resolve'))&&(s!=='CLOSED'||can('service.case.close'))&&(!(managerSignOff&&!canSignOff)||!['RESOLVED','CLOSED'].includes(s)))} defaultValue={c.status}/><Select title="Resolution code" name="resolutionCode" options={RESOLUTION_CODES} defaultValue={c.resolutionCode??'INFORMATION_PROVIDED'}/><TextArea title="Resolution summary" name="resolutionSummary" defaultValue={c.resolutionSummary??''} maxLength={10000}/><TextArea title="Reason / customer acceptance" name="reason" maxLength={2000}/></ActionForm></Card></>}
 </aside></div></div>;
}
