import { ExportMenu } from '@/components/ui/export-menu';
import { requireSession } from '@/core/auth/session';
import { assertCapability,can } from '@/core/permissions/check';
import Link from 'next/link';
import { DataTable } from '@/components/ui/table';
import { getPlanOptions,getAssignedPlanningWork } from '@/modules/planning/services/plans';
import { createWorkTeam } from '@/core/teams/actions';
import { CreateDialog } from '@/components/ui/create-dialog';
import { ActionForm } from '@/components/ui/action-form';
import { Button } from '@/components/ui/button';
export default async function TeamsPage({searchParams}:{searchParams:Promise<{team?:string}>}) {
 const session=await requireSession();assertCapability(session,'planning.demand.read');const options=await getPlanOptions();const filters=await searchParams;const team=typeof filters.team==='string'?filters.team:'';const work=await getAssignedPlanningWork(team);
 return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-semibold tracking-tight">Teams & work</h2><p className="mt-1 text-sm text-slate-500">Build production teams from existing workspace people, then assign product-plan work.</p></div>{can(session,'planning.team.manage')&&<CreateDialog title="Create a production team" label="New team"><ActionForm action={createWorkTeam} className="space-y-4"><label className="block text-xs font-medium">Team name<input name="name" required maxLength={100} className="mt-2 block w-full rounded-xl border border-slate-200 p-3 text-sm"/></label><label className="block text-xs font-medium">Team code<input name="code" required maxLength={30} className="mt-2 block w-full rounded-xl border border-slate-200 p-3 text-sm"/></label><fieldset className="space-y-2"><legend className="mb-2 text-xs font-medium">Members</legend>{options.memberships.map(m=><label key={m.id} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3 text-sm"><input type="checkbox" name="membershipId" value={m.id}/>{m.name}</label>)}</fieldset><Button type="submit" variant="primary">Create team</Button></ActionForm></CreateDialog>}</div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{options.teams.map(team=><section key={team.id} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs text-slate-400">{team.code}</p><h3 className="mt-1 text-lg font-semibold">{team.name}</h3><p className="mt-4 text-xs text-slate-500">{team.members.length} members</p><Link href={`/planning/teams?team=${team.id}`} className="mt-3 inline-block text-xs font-medium text-blue-600">View team work →</Link><ul className="mt-2 space-y-2 text-sm">{team.members.map(member=><li key={member.membershipId}>{options.memberships.find(m=>m.id===member.membershipId)?.name??'Inactive member'}</li>)}</ul></section>)}</div>{!options.teams.length&&<div className="rounded-2xl border border-dashed border-slate-200 p-12 text-center text-sm text-slate-500">Create a team, then choose it on a product plan’s work line.</div>}<section className="space-y-3"><div className="flex flex-wrap justify-between gap-3"><h3 className="text-sm font-semibold">Assigned product-plan work</h3><div className="flex gap-4 text-xs"><Link href="/planning/teams" className="text-slate-500">All teams</Link><ExportMenu href={`/api/planning/export?type=teams&team=${team}`}/></div></div><DataTable rows={work} getHref={line=>`/planning/plans/${line.planId}`} emptyLabel="No planned work in this view. Assign a team and responsible person on a product plan." columns={[{header:'Product',render:l=>`${l.code} · ${l.name}`},{header:'Plan',render:l=>l.planName},{header:'Target',align:'right',render:l=>`${l.quantity} ${l.unitOfMeasure}`},{header:'Work ends',render:l=>l.endsOn},{header:'Team',render:l=>l.teamName},{header:'Responsible',render:l=>l.assignedName}]}/></section></div>;
}
