import {workAuditScope} from '@/core/permissions/work-access';
import { requireSession } from "@/core/auth/session";
import { assertCapability } from "@/core/permissions/check";
import { db } from "@/core/db/client";
export default async function AuditPage({searchParams}:{searchParams:Promise<{entity?:string;page?:string}>}) {
 const session=await requireSession();
 assertCapability(session,"core.audit.read");
 const params=await searchParams, page=Math.max(1,Math.min(Number(params.page)||1,1000)), entity=(params.entity??'').slice(0,100);
 const entries=await db.auditEntry.findMany({where:{AND:[workAuditScope(session),...(entity?[{entityType:entity}]:[])]},orderBy:{createdAt:'desc'},take:50,skip:(page-1)*50});
 const users=await db.user.findMany({where:{id:{in:entries.flatMap(e=>e.actorUserId?[e.actorUserId]:[])},memberships:{some:{organisationId:session.organisationId}}},select:{id:true,name:true}});
 const names=new Map(users.map(u=>[u.id,u.name]));
 return <div className="mx-auto max-w-5xl space-y-6"><h1 className="text-3xl font-semibold tracking-tight">Audit trail</h1><p className="text-sm text-[var(--color-ink-muted)]">Who changed what, and when. Read-only history for this company.</p><form className="flex gap-3"><label className="flex-1 text-xs">Record type<input name="entity" placeholder="Party, Quote, Role…" defaultValue={entity} className="mt-2 block w-full border border-[var(--color-border)] bg-white p-3 text-sm"/></label><button className="self-end rounded-xl border border-[var(--color-border)] bg-white px-5 py-3 text-sm">Filter</button></form><div className="divide-y divide-[var(--color-border)] rounded-2xl border border-[var(--color-border)] bg-white">{entries.map(e=><details key={e.id}><summary className="flex cursor-pointer flex-wrap items-center gap-4 p-4 text-sm"><time className="text-xs text-[var(--color-ink-faint)]">{e.createdAt.toLocaleString('en-GB',{timeZone:'Europe/London'})}</time><span className="flex-1 font-medium">{e.action.replaceAll('.',' · ')}</span><span className="text-xs">{e.actorUserId?names.get(e.actorUserId)??'Former member':'System'}</span><span className="text-xs text-[var(--color-ink-muted)]">{e.entityType}</span></summary><div className="grid gap-4 border-t border-[var(--color-border)] p-4 sm:grid-cols-2"><div><h2 className="mb-2 text-xs font-semibold">Before</h2><pre className="max-h-60 overflow-auto rounded-lg bg-[var(--color-surface-sunken)] p-3 text-xs">{JSON.stringify(e.before,null,2)??'—'}</pre></div><div><h2 className="mb-2 text-xs font-semibold">After</h2><pre className="max-h-60 overflow-auto rounded-lg bg-[var(--color-surface-sunken)] p-3 text-xs">{JSON.stringify(e.after,null,2)??'—'}</pre></div></div></details>)}{!entries.length&&<p className="p-8 text-center text-sm text-[var(--color-ink-muted)]">No changes recorded for this filter.</p>}</div><div className="flex justify-between text-sm">{page>1?<a href={`?entity=${encodeURIComponent(entity)}&page=${page-1}`}>← Previous</a>:<span/>}{entries.length===50&&<a href={`?entity=${encodeURIComponent(entity)}&page=${page+1}`}>Next →</a>}</div></div>;
}
