"use server";
import {z} from 'zod';
import {salesFinanceSource,stockReceipt} from '@/core/finance/connections';
import {approvedExpenseSource} from '@/core/finance/expense-source';
import {createHash} from 'node:crypto';
import {db} from '@/core/db/client';
import {requireSession,type Session} from '@/core/auth/session';
import {assertCapability} from '@/core/permissions/check';
import {revalidatePath} from 'next/cache';
import {Prisma} from '@/generated/prisma/client';
import {createApproval,decideApproval} from '@/core/approvals/service';
import {stagesSchema,conditionsSchema,matchesConditions} from '@/core/approvals/policy';
import {readCompanyProfile} from '@/core/setup/company-profile';
import {MANAGER_SIGNOFF_POLICY,financeNeedsManagerSignOff,isManagerLevelSnapshot,rangesOverlap,readManagerPolicy} from '@/core/permissions/manager-level';
import {effectiveRoleCapabilities} from '@/core/permissions/access-levels';
import {applyCompanyAccessRestrictions} from '@/core/permissions/company-access';
import {projectScope} from '@/core/permissions/work-access';
import {requireFinance,documentCapability,documentScope} from './access';
import {budgetUsage,incrementalBudgetSpend} from './budgets';
import {postLedger,controls,type PostingLine} from './ledger';
import {digits,minor,lineAmounts,decimalUnits,roundRatio,assertBalanced,convert} from '../domain/money';
import {DOCUMENT_KINDS,TAX_CODES,checkActorSeparation,normaliseInvoiceNumber,matchLine} from '../domain/controls';
const text=(f:FormData,k:string)=>String(f.get(k)??'').trim();
const dateEnd=(s:string)=>date(/^\d{4}-\d{2}-\d{2}$/.test(s)?`${s}T23:59:59.999Z`:s);
const date=(s:string)=>{const d=new Date(s);if(!s||Number.isNaN(d.getTime()))throw new Error('Enter a valid date.');return d;};
function nested<T extends {organisationId:string}>(value:T){const {organisationId,...rest}=value;if(!organisationId)throw new Error('Nested record requires tenant context.');return rest;}
const refresh=()=>revalidatePath('/finance','layout');
async function transaction<T>(fn:(tx:Prisma.TransactionClient)=>Promise<T>){return db.$transaction(fn,{isolationLevel:'Serializable',timeout:20000});}
const lineSchema=z.object({description:z.string().min(1).max(500),quantity:z.string(),unitPrice:z.string(),taxCode:z.enum(TAX_CODES),taxRateBps:z.number().int().min(0).max(10000),productId:z.string().optional(),accountId:z.string().optional(),sourceLineId:z.string().optional()});
const documentSchema=z.object({draftId:z.string().optional(),expenseClaimId:z.string().optional(),entityId:z.string().min(1),kind:z.enum(DOCUMENT_KINDS),title:z.string().min(1).max(250),currency:z.string().length(3),exchangeRate:z.string().default('1'),documentDate:z.string(),dueAt:z.string().optional(),partyId:z.string().optional(),projectId:z.string().optional(),sourceId:z.string().optional(),externalReference:z.string().max(100).optional(),department:z.string().max(100).optional(),costCentre:z.string().max(100).optional(),site:z.string().max(100).optional(),category:z.string().max(100).optional(),reason:z.string().max(4000).optional(),capex:z.boolean().default(false),recurring:z.boolean().default(false),lines:z.array(lineSchema).min(1).max(200)});
export async function setupFinance(form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.configure');
 await requireFinance(session,'finance.configure');
 const name=z.string().min(1).max(150).parse(text(form,'name')),code=z.string().regex(/^[A-Z0-9-]{1,20}$/).parse(text(form,'code')),currency=text(form,'currency')||'GBP';digits(currency);
 const startAt=date(text(form,'startAt')),endAt=dateEnd(text(form,'endAt'));if(startAt>=endAt)throw new Error('Period end must follow start.');
 const result=await transaction(async tx=>{const entity=await tx.financeEntity.create({data:{organisationId:session.organisationId,name,code,currency}});
 const chart=[['1000','Bank','ASSET','BANK'],['1100','Trade receivables','ASSET','AR'],['1200','Inventory','ASSET','INVENTORY'],['1300','Fixed assets','ASSET','ASSET'],['1390','Accumulated depreciation','ASSET','DEPRECIATION_ACCUMULATED'],['2000','Trade payables','LIABILITY','AP'],['2100','VAT output','LIABILITY','VAT_OUTPUT'],['2110','VAT input','ASSET','VAT_INPUT'],['2200','Goods received not invoiced','LIABILITY','GRNI'],['3000','Opening equity','EQUITY','EQUITY'],['4000','Revenue','REVENUE','REVENUE'],['5000','Operating expenses','EXPENSE','EXPENSE'],['5100','Depreciation','EXPENSE','DEPRECIATION'],['5200','Purchase price variance','EXPENSE','PURCHASE_VARIANCE']];
 await tx.financeAccount.createMany({data:chart.map(([accountCode,accountName,type,control])=>({organisationId:session.organisationId,entityId:entity.id,code:accountCode,name:accountName,type,control}))});
 const period=await tx.financePeriod.create({data:{organisationId:session.organisationId,entityId:entity.id,name:`${startAt.toISOString().slice(0,10)} – ${endAt.toISOString().slice(0,10)}`,startAt,endAt}});
 await tx.financeCloseTask.createMany({data:['Bank reconciliation','Accounts receivable','Accounts payable','Stock valuation','Accruals','Fixed assets','Payroll','Intercompany','VAT','Management accounts'].map(name=>({organisationId:session.organisationId,entityId:entity.id,periodId:period.id,name}))});
 await tx.auditEntry.create({data:{organisationId:session.organisationId,actorUserId:session.userId,action:'finance.entity.created',entityType:'FinanceEntity',entityId:entity.id,after:{name,code,currency}}});return entity;});refresh();return {id:result.id};
}
export async function createFinanceDocument(input:unknown){
 const session=await requireSession();
 assertCapability(session,documentCapability(String((input as {kind?:unknown})?.kind),true));
 const parsed=documentSchema.parse(input);const expense=parsed.kind==='EXPENSE'?await approvedExpenseSource(session,z.string().min(1).parse(parsed.expenseClaimId)):null;await requireFinance(session,documentCapability(parsed.kind,true));if(parsed.kind==='RECEIPT')throw new Error('Record receipts against an approved PO.');
 const result=await transaction(async tx=>{const organisationId=session.organisationId;const entity=await tx.financeEntity.findFirstOrThrow({where:{id:parsed.entityId,organisationId}});digits(parsed.currency);if(decimalUnits(parsed.exchangeRate,12)<=0n)throw new Error('Enter a positive exchange rate.');if(parsed.currency===entity.currency&&decimalUnits(parsed.exchangeRate,12)!==1000000000000n)throw new Error('Same-currency exchange rate must be 1.');
 if(parsed.partyId){assertCapability(session,'customers.read');await tx.party.findFirstOrThrow({where:{id:parsed.partyId,organisationId}});}if(['AP_INVOICE','AP_CREDIT','AR_INVOICE','AR_CREDIT','PO'].includes(parsed.kind)&&!parsed.partyId)throw new Error('Choose a shared customer or supplier.');
 if(parsed.projectId){assertCapability(session,'projects.read');await tx.project.findFirstOrThrow({where:{AND:[projectScope(session),{id:parsed.projectId}]}});}
 let source=null;if(parsed.sourceId){source=await tx.financeDocument.findFirstOrThrow({where:{AND:[documentScope(session),{id:parsed.sourceId,entityId:entity.id,currency:parsed.currency}]},include:{lines:true}});if(source.projectId!==parsed.projectId&&source.projectId)throw new Error('Retain the source project allocation.');if(source.partyId!==parsed.partyId)throw new Error('Source customer/supplier differs.');if(parsed.kind==='AP_INVOICE'&&!(source.kind==='PO'&&['APPROVED','PART_RECEIVED','RECEIVED'].includes(source.status)))throw new Error('Supplier bills must reference an approved purchase order.');if((parsed.kind.endsWith('_CREDIT')||parsed.kind.endsWith('_DEBIT'))&&source.kind!==parsed.kind.replace(/_(CREDIT|DEBIT)$/,'_INVOICE'))throw new Error('Credit must reference the original invoice.');}if((parsed.kind.endsWith('_CREDIT')||parsed.kind.endsWith('_DEBIT'))&&!source)throw new Error('Credit requires an original posted invoice.');
 const lines=[];for(const [i,l]of parsed.lines.entries()){if(source&&parsed.kind==='AP_INVOICE'){const sourceLine=source.lines.find(s=>s.id===l.sourceLineId);if(!sourceLine)throw new Error('Choose a PO source line for every bill line.');l.productId=sourceLine.productId??undefined;}if(l.productId){assertCapability(session,'core.products.read');await tx.product.findFirstOrThrow({where:{id:l.productId,organisationId,active:true}});}if(l.accountId)await tx.financeAccount.findFirstOrThrow({where:{id:l.accountId,organisationId,entityId:entity.id,active:true}});if(!['STANDARD','REDUCED'].includes(l.taxCode)&&l.taxRateBps!==0)throw new Error('Zero/exempt/outside-scope lines cannot carry a VAT rate.');if(['STANDARD','REDUCED'].includes(l.taxCode)&&l.taxRateBps===0)throw new Error('Taxable lines require an explicit VAT rate.');const unitPrice=minor(l.unitPrice,parsed.currency),amounts=lineAmounts(l.quantity,unitPrice,l.taxRateBps);lines.push({organisationId,number:i+1,description:l.description,quantity:l.quantity,unitPrice,net:amounts.net,tax:amounts.tax,taxCode:l.taxCode,taxRateBps:l.taxRateBps,productId:l.productId||null,accountId:l.accountId||null,sourceLineId:l.sourceLineId||null});}
 const draft=parsed.draftId?await tx.financeDocument.findFirstOrThrow({where:{AND:[documentScope(session),{id:parsed.draftId,creatorUserId:session.userId,kind:parsed.kind,status:{in:['DRAFT','NEEDS_INFORMATION','REJECTED']}}]},include:{lines:true}}):null;const net=lines.reduce((s,l)=>s+l.net,0n),tax=lines.reduce((s,l)=>s+l.tax,0n);if(net+tax===0n)throw new Error('Document must have a positive total.');
 if(expense&&(expense.currency!==parsed.currency||BigInt(expense.amountMinorUnits)!==net+tax))throw new Error('Finance expense amount/currency must match the approved HR claim.');const duplicateKey=expense?`expense:${expense.id}`:parsed.kind==='AP_INVOICE'?`${entity.id}:${parsed.partyId}:${normaliseInvoiceNumber(parsed.externalReference??'')}`:null;if(parsed.kind==='AP_INVOICE'&&!normaliseInvoiceNumber(parsed.externalReference??''))throw new Error('Enter the supplier invoice number.');
 const prefixes:Record<string,string>={REQUEST:'PR',PO:'PO',AP_INVOICE:'BILL',AR_INVOICE:'INV',AP_CREDIT:'SCN',AR_CREDIT:'CN',AP_DEBIT:'SDN',AR_DEBIT:'DN',EXPENSE:'EXP'};
 const documentData={organisationId,expenseClaimId:expense?.id??null,entityId:entity.id,kind:parsed.kind,reference:`${prefixes[parsed.kind]}-${crypto.randomUUID().slice(0,10).toUpperCase()}`,externalReference:parsed.externalReference||null,duplicateKey,title:parsed.title,creatorUserId:session.userId,partyId:parsed.partyId||null,projectId:parsed.projectId||null,sourceId:parsed.sourceId||null,currency:parsed.currency,exchangeRate:parsed.exchangeRate,documentDate:date(parsed.documentDate),dueAt:parsed.dueAt?date(parsed.dueAt):null,net,tax,gross:net+tax,department:parsed.department,category:parsed.category,site:parsed.site,costCentre:parsed.costCentre,reason:parsed.reason,capex:parsed.capex,recurring:parsed.recurring,lines:{create:lines.map(nested)}};if(draft?.salesOrderId)throw new Error('Sales invoice values are retained from the confirmed revision. Void the unposted invoice and review Sales before regenerating.');if(draft)await tx.financeDocumentLine.deleteMany({where:{organisationId,documentId:draft.id}});const document=draft?await tx.financeDocument.update({where:{id:draft.id},data:{...documentData,reference:draft.reference,status:'DRAFT',version:{increment:1},approverUserId:null}}):await tx.financeDocument.create({data:documentData});if(draft)await tx.auditEntry.create({data:{organisationId,actorUserId:session.userId,action:'finance.draft.revised',entityType:'FinanceDocument',entityId:draft.id,before:{version:draft.version,title:draft.title,gross:draft.gross.toString(),lines:draft.lines.map(l=>({number:l.number,description:l.description,quantity:l.quantity.toString(),unitPrice:l.unitPrice.toString(),tax:l.tax.toString()}))},after:{version:document.version,gross:document.gross.toString()}}});
 await tx.financeTimeline.create({data:{organisationId,documentId:document.id,actorUserId:session.userId,action:'CREATED',detail:'Draft created; no financial posting.'}});await tx.auditEntry.create({data:{organisationId,actorUserId:session.userId,action:'finance.document.created',entityType:'FinanceDocument',entityId:document.id,after:{kind:parsed.kind,reference:document.reference}}});return document;});refresh();return {id:result.id};
}
async function financeManagerIds(tx:Prisma.TransactionClient,organisationId:string,restricted:string[]){
 const rows=await tx.membership.findMany({where:{organisationId,active:true},select:{userId:true,grantedCapabilities:true,deniedCapabilities:true,roles:{select:{role:{select:{capabilities:true}}}}}});
 return rows.filter(row=>applyCompanyAccessRestrictions(effectiveRoleCapabilities(row.roles.map(role=>role.role),row.grantedCapabilities,row.deniedCapabilities),restricted).has('finance.approval.decide')).map(row=>row.userId);
}
async function approvalForDocument(tx:Prisma.TransactionClient,session:Session,doc:{id:string;kind:string;version:number;gross:bigint;currency:string;entityId:string;department:string|null;category:string|null;site:string|null;projectId:string|null;partyId:string|null;capex:boolean;recurring:boolean},budgetStatus:string){
 const org=await tx.organisation.findUniqueOrThrow({where:{id:session.organisationId},select:{managerPolicy:true,companyProfile:true,restrictedAccessAreas:true}});
 const policy=readManagerPolicy(org.managerPolicy),companyCurrency=readCompanyProfile(org.companyProfile).defaultCurrency;
 const context={budgetStatus,employee:session.userId,legalEntity:doc.entityId,currency:doc.currency,entityId:doc.entityId,department:doc.department,category:doc.category,site:doc.site,projectId:doc.projectId,partyId:doc.partyId,capex:doc.capex,recurring:doc.recurring};
 const base={subjectType:doc.kind,subjectId:doc.id,subjectVersion:doc.version,amount:doc.gross,currency:doc.currency};
 if(!financeNeedsManagerSignOff(policy,{gross:doc.gross,currency:doc.currency,companyCurrency}))return createApproval(tx,session,{...base,context});
 const managers=(await financeManagerIds(tx,session.organisationId,org.restrictedAccessAreas)).filter(id=>id!==session.userId);
 if(!managers.length)throw new Error('Give someone Finance approval before a high-value document can be submitted.');
 const routes=await tx.approvalPolicy.findMany({where:{organisationId:session.organisationId,subjectType:doc.kind,currency:doc.currency,active:true}});
 const matching=routes.filter(route=>doc.gross>=route.minAmount&&(route.maxAmount===null||doc.gross<=route.maxAmount)&&matchesConditions(route.conditions,context));
 if(matching.length>1)throw new Error('Approval policies overlap; resolve the control conflict.');
 if(matching.length===1){
  const approvers=stagesSchema.parse(matching[0].stages).flat();
  if(!approvers.some(id=>managers.includes(id)))throw new Error('Add a finance manager to the approval route for amounts at or above the manager limit.');
  return createApproval(tx,session,{...base,context});
 }
 const minAmount=doc.currency===companyCurrency?BigInt(policy.financeLimitMinor):0n;
 const current=routes.find(route=>route.name===MANAGER_SIGNOFF_POLICY);
 const others=routes.filter(route=>route.id!==current?.id);
 if(others.some(route=>rangesOverlap(minAmount,null,route.minAmount,route.maxAmount)))throw new Error('No finance manager route covers this amount. Adjust the approval routes or the manager limit so they do not overlap.');
 const stages=[managers];
 if(current)await tx.approvalPolicy.update({where:{id:current.id},data:{minAmount,maxAmount:null,stages,active:true,version:{increment:1}}});
 else await tx.approvalPolicy.create({data:{organisationId:session.organisationId,name:MANAGER_SIGNOFF_POLICY,subjectType:doc.kind,minAmount,maxAmount:null,currency:doc.currency,conditions:{},stages,active:true}});
 return createApproval(tx,session,{...base,context:{...context,managerLevel:true}});
}
export async function submitFinanceDocument(id:string){
 const session=await requireSession();
 assertCapability(session,'finance.overview.read');
 await requireFinance(session,'finance.overview.read');
 await transaction(async tx=>{const doc=await tx.financeDocument.findFirstOrThrow({where:{AND:[documentScope(session),{id,status:'DRAFT'}]}});assertCapability(session,documentCapability(doc.kind,true));const positions=await budgetUsage(tx,session.organisationId,doc.entityId,doc.department,doc.documentDate),entity=await tx.financeEntity.findFirstOrThrow({where:{id:doc.entityId,organisationId:session.organisationId}}),request=await incrementalBudgetSpend(tx,doc,entity.currency);const over=request>0n?positions.filter(b=>request>b.available):[];if(over.some(b=>b.policy==='BLOCK'))throw new Error('Request exceeds available budget and policy blocks additional spend.');const budgetStatus=over.length?'OVER':'WITHIN';const approval=await approvalForDocument(tx,session,doc,budgetStatus);await tx.financeDocument.update({where:{id:doc.id},data:{status:'AWAITING_APPROVAL'}});await tx.financeTimeline.create({data:{organisationId:session.organisationId,documentId:id,actorUserId:session.userId,action:'SUBMITTED',detail:`Approval ${approval.id} requested.`}});});refresh();
}
export async function saveApprovalPolicy(form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.configure');
 await requireFinance(session,'finance.configure');
 const currency=text(form,'currency')||'GBP',subjectType=z.enum([...DOCUMENT_KINDS,'JOURNAL','BANK_CHANGE','PAYMENT_RUN','PERIOD_REOPEN']).parse(text(form,'subjectType')),stages=stagesSchema.parse(JSON.parse(text(form,'stages'))),conditions=conditionsSchema.parse(JSON.parse(text(form,'conditions')||'{}'));
 const minAmount=minor(text(form,'minimum')||'0',currency),maxAmount=text(form,'maximum')?minor(text(form,'maximum'),currency):null;if(minAmount<0n||(maxAmount!==null&&maxAmount<minAmount))throw new Error('Invalid approval range.');
 await transaction(async tx=>{const ids=[...new Set(stages.flat())];if(await tx.membership.count({where:{organisationId:session.organisationId,userId:{in:ids},active:true}})!==ids.length)throw new Error('Choose active company approvers.');await tx.approvalPolicy.create({data:{organisationId:session.organisationId,name:z.string().min(1).max(100).parse(text(form,'name')),subjectType,minAmount,maxAmount,currency,stages,conditions}});await tx.auditEntry.create({data:{organisationId:session.organisationId,actorUserId:session.userId,action:'approval.policy.created',entityType:'ApprovalPolicy',entityId:'new',after:{subjectType,minAmount:minAmount.toString(),maxAmount:maxAmount?.toString()??null,stages,conditions}}});});refresh();
}
export async function decideFinanceApproval(id:string,form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.approval.decide');
 await requireFinance(session,'finance.approval.decide');const decision=z.enum(['APPROVED','REJECTED','INFORMATION']).parse(text(form,'decision')),reason=z.string().min(1).max(2000).parse(text(form,'reason'));
 await transaction(async tx=>{const instance=await tx.approvalInstance.findFirstOrThrow({where:{id,organisationId:session.organisationId}});const doc=await tx.financeDocument.findFirstOrThrow({where:{AND:[documentScope(session),{id:instance.subjectId,kind:instance.subjectType,version:instance.subjectVersion,status:'AWAITING_APPROVAL'}]}});checkActorSeparation(doc.creatorUserId,session.userId);if(decision==='APPROVED'){const positions=await budgetUsage(tx,session.organisationId,doc.entityId,doc.department,doc.documentDate),entity=await tx.financeEntity.findFirstOrThrow({where:{id:doc.entityId,organisationId:session.organisationId}}),requested=await incrementalBudgetSpend(tx,doc,entity.currency);if(requested>0n&&positions.some(b=>b.policy==='BLOCK'&&requested>b.available))throw new Error('Available budget changed; this approval would exceed a blocking budget.');}if(isManagerLevelSnapshot(instance.snapshot))await tx.approvalStep.updateMany({where:{organisationId:session.organisationId,instanceId:instance.id,stage:instance.currentStage,status:'PENDING',approverUserId:{not:session.userId}},data:{status:'SKIPPED',reason:'Another finance manager signed off.',actedAt:new Date()}});const result=await decideApproval(tx,session,id,decision,reason);if(result.status!=='PENDING')await tx.financeDocument.update({where:{id:doc.id},data:{status:result.status==='INFORMATION'?'NEEDS_INFORMATION':result.status,approverUserId:result.status==='APPROVED'?session.userId:null}});await tx.financeTimeline.create({data:{organisationId:session.organisationId,documentId:doc.id,actorUserId:session.userId,action:decision,detail:reason}});});refresh();
}
export async function createPurchaseOrder(requestId:string){
 const session=await requireSession();
 assertCapability(session,'finance.purchase.manage');
 await requireFinance(session,'finance.purchase.manage');
 const result=await transaction(async tx=>{const organisationId=session.organisationId,request=await tx.financeDocument.findFirstOrThrow({where:{AND:[documentScope(session),{id:requestId,kind:'REQUEST',status:'APPROVED'}]},include:{lines:true,children:true}});if(request.children.some(c=>c.kind==='PO'))throw new Error('This request already has a purchase order.');if(!request.partyId)throw new Error('Add a supplier before approval and PO conversion.');await tx.financeSupplier.findFirstOrThrow({where:{organisationId,partyId:request.partyId,status:'ACTIVE'}});
 const doc=await tx.financeDocument.create({data:{organisationId,entityId:request.entityId,kind:'PO',reference:`PO-${crypto.randomUUID().slice(0,10).toUpperCase()}`,title:request.title,status:'DRAFT',creatorUserId:request.creatorUserId,approverUserId:request.approverUserId,partyId:request.partyId,projectId:request.projectId,sourceId:request.id,currency:request.currency,exchangeRate:request.exchangeRate,documentDate:new Date(),dueAt:request.dueAt,net:request.net,tax:request.tax,gross:request.gross,department:request.department,category:request.category,costCentre:request.costCentre,site:request.site,capex:request.capex,recurring:request.recurring,reason:request.reason,lines:{create:request.lines.map(l=>({number:l.number,productId:l.productId,description:l.description,quantity:l.quantity,unitPrice:l.unitPrice,net:l.net,tax:l.tax,taxCode:l.taxCode,taxRateBps:l.taxRateBps,accountId:l.accountId,sourceLineId:l.id}))}}});await tx.financeDocument.update({where:{id:doc.id},data:{status:'APPROVED'}});await tx.financeTimeline.create({data:{organisationId,documentId:doc.id,actorUserId:session.userId,action:'GENERATED',detail:`Approved request ${request.reference}; approval and amount retained.`}});return doc;});refresh();return {id:result.id};
}
export async function raiseServiceCredit(id:string){
 const session=await requireSession();
 assertCapability(session,'finance.receivables.manage');
 assertCapability(session,'finance.journal.post');
 await requireFinance(session,'finance.receivables.manage');
 await transaction(async tx=>{const doc=await tx.financeDocument.findFirstOrThrow({where:{AND:[documentScope(session),{id,kind:'AR_CREDIT',category:'SERVICE_CREDIT',status:'DRAFT'}]}});await tx.financeDocument.update({where:{id:doc.id},data:{status:'APPROVED',approverUserId:session.userId}});await tx.financeTimeline.create({data:{organisationId:session.organisationId,documentId:doc.id,actorUserId:session.userId,action:'RAISED',detail:'Finance accepted the Customer Service request and is raising the credit against the customer.'}});await tx.auditEntry.create({data:{organisationId:session.organisationId,actorUserId:session.userId,action:'finance.service_credit.raised',entityType:'FinanceDocument',entityId:doc.id,after:{gross:doc.gross.toString()}}});});
 await postFinanceDocument(id);
}
export async function postFinanceDocument(id:string){
 const session=await requireSession();
 assertCapability(session,'finance.journal.post');
 await requireFinance(session,'finance.journal.post');
 await transaction(async tx=>{const organisationId=session.organisationId,doc=await tx.financeDocument.findFirstOrThrow({where:{AND:[documentScope(session),{id,status:'APPROVED'}]},include:{lines:true,source:{include:{lines:true,children:{include:{lines:true}}}}}});assertCapability(session,documentCapability(doc.kind,true));if(!['AP_INVOICE','AR_INVOICE','AP_CREDIT','AR_CREDIT','AP_DEBIT','AR_DEBIT','EXPENSE'].includes(doc.kind))throw new Error('This document does not create an invoice/expense posting.');if(!doc.approverUserId)throw new Error('Independent approval evidence is missing.');
 const account=await controls(tx,organisationId,doc.entityId),ar=doc.kind.startsWith('AR_'),credit=doc.kind.endsWith('_CREDIT'),lines:PostingLine[]=[];
 if(!ar&&doc.partyId)await tx.financeSupplier.findFirstOrThrow({where:{organisationId,partyId:doc.partyId,status:'ACTIVE'}});
 if(doc.kind.endsWith('_DEBIT')&&(!doc.source||doc.source.status!=='POSTED'))throw new Error('Debit notes require an original posted invoice.');if(credit){const source=doc.source;if(!source||source.status!=='POSTED'||source.currency!==doc.currency||source.gross-source.settled<doc.gross)throw new Error('Credit exceeds the original posted invoice outstanding amount.');}
 if(doc.kind==='AP_INVOICE'&&doc.source){for(const line of doc.lines){const poLine=doc.source.lines.find(l=>l.id===line.sourceLineId);if(!poLine)throw new Error('Every supplier invoice line must reference its PO line.');const receipts=doc.source.children.filter(d=>d.kind==='RECEIPT'&&d.status==='POSTED').flatMap(d=>d.lines).filter(l=>l.sourceLineId===poLine.id),other=doc.source.children.filter(d=>d.kind==='AP_INVOICE'&&d.id!==doc.id&&d.status==='POSTED').flatMap(d=>d.lines).filter(l=>l.sourceLineId===poLine.id);const q=(rows:typeof receipts)=>rows.reduce((s,l)=>s+decimalUnits(l.quantity.toString(),6)-decimalUnits(l.damagedQuantity.toString(),6),0n);const scaled=(v:bigint)=>`${v/1000000n}.${(v%1000000n).toString().padStart(6,'0')}`;const match=matchLine({ordered:poLine.quantity.toString(),accepted:scaled(q(receipts)),alreadyInvoiced:scaled(q(other)),invoiceQuantity:line.quantity.toString(),expectedPrice:poLine.unitPrice,invoicePrice:line.unitPrice,toleranceBps:0});if(!match.matched)throw new Error(match.issues.join(' '));}}
 const originalPurchase=doc.kind.startsWith('AP_')&&doc.source?.sourceId?await tx.financeDocument.findFirst({where:{id:doc.source.sourceId,organisationId,kind:'PO'},select:{id:true}}):null;for(const l of doc.lines){const expenseAccount=ar?account('REVENUE'):doc.source?.kind==='PO'?account('GRNI'):originalPurchase?account('PURCHASE_VARIANCE'):l.accountId??account('EXPENSE');lines.push({accountId:expenseAccount,description:l.description,debit:ar?0n:l.net,credit:ar?l.net:0n,partyId:doc.partyId,projectId:doc.projectId,department:doc.department,costCentre:doc.costCentre,site:doc.site,taxCode:l.taxCode});}
 if(doc.tax)lines.push({accountId:account(ar?'VAT_OUTPUT':'VAT_INPUT'),description:'VAT',debit:ar?0n:doc.tax,credit:ar?doc.tax:0n,taxCode:'VAT'});lines.push({accountId:account(ar?'AR':'AP'),description:doc.reference,debit:ar?doc.gross:0n,credit:ar?0n:doc.gross,partyId:doc.partyId});if(credit)for(const l of lines)[l.debit,l.credit]=[l.credit,l.debit];
 const journal=await postLedger(tx,session,{entityId:doc.entityId,date:doc.documentDate,description:doc.title,sourceKey:`document:${doc.id}:${doc.version}`,sourceType:doc.kind,sourceId:doc.id,currency:doc.currency,rate:doc.exchangeRate.toString(),lines,approverUserId:doc.approverUserId});await tx.financeDocument.update({where:{id:doc.id},data:{status:'POSTED',journalId:journal.id,...(credit?{settled:doc.gross}:{})}});if(credit&&doc.sourceId)await tx.financeDocument.update({where:{id:doc.sourceId},data:{settled:{increment:doc.gross}}});await tx.financeTimeline.create({data:{organisationId,documentId:doc.id,actorUserId:session.userId,action:'POSTED',detail:`Balanced journal ${journal.reference}.`}});await tx.domainOutbox.create({data:{organisationId,eventKey:`finance.invoice.posted:${doc.id}`,eventName:'finance.invoice.posted',payload:{documentId:doc.id,journalId:journal.id,kind:doc.kind}}});});refresh();
}
export async function recordGoodsReceipt(poId:string,input:unknown){
 const session=await requireSession();
 assertCapability(session,'finance.purchase.manage');
 await requireFinance(session,'finance.purchase.manage');const parsed=z.object({warehouseId:z.string().optional(),date:z.string(),lines:z.array(z.object({lineId:z.string(),quantity:z.string(),damaged:z.string()})).min(1).max(200)}).parse(input);if(new Set(parsed.lines.map(l=>l.lineId)).size!==parsed.lines.length)throw new Error('Receipt lines must be unique.');
 const result=await transaction(async tx=>{const organisationId=session.organisationId,po=await tx.financeDocument.findFirstOrThrow({where:{AND:[documentScope(session),{id:poId,kind:'PO',status:{in:['APPROVED','PART_RECEIVED']}}]},include:{lines:true,children:{where:{kind:'RECEIPT',status:'POSTED'},include:{lines:true}}}});const receiptLines:Array<{organisationId:string;number:number;sourceLineId:string;productId:string|null;description:string;quantity:string;damagedQuantity:string;unitPrice:bigint;net:bigint;tax:bigint;taxCode:string;taxRateBps:number}>=[];
 for(const [number,inputLine]of parsed.lines.entries()){const l=po.lines.find(l=>l.id===inputLine.lineId);if(!l)throw new Error('Receipt line is not on this PO.');const q=decimalUnits(inputLine.quantity,6),damaged=decimalUnits(inputLine.damaged,6);if(q<=0n||damaged<0n||damaged>q)throw new Error('Enter valid received and damaged quantities.');const received=po.children.flatMap(d=>d.lines).filter(r=>r.sourceLineId===l.id).reduce((s,r)=>s+decimalUnits(r.quantity.toString(),6),0n);if(received+q>decimalUnits(l.quantity.toString(),6))throw new Error('Receipt exceeds ordered quantity.');const net=roundRatio((q-damaged)*l.unitPrice,1000000n);receiptLines.push({organisationId,number:number+1,sourceLineId:l.id,productId:l.productId,description:l.description,quantity:inputLine.quantity,damagedQuantity:inputLine.damaged,unitPrice:l.unitPrice,net,tax:0n,taxCode:'OUTSIDE_SCOPE',taxRateBps:0});}
 const net=receiptLines.reduce((s,l)=>s+l.net,0n);const receipt=await tx.financeDocument.create({data:{organisationId,entityId:po.entityId,kind:'RECEIPT',reference:`GR-${crypto.randomUUID().slice(0,10).toUpperCase()}`,title:`Receipt for ${po.reference}`,creatorUserId:session.userId,partyId:po.partyId,projectId:po.projectId,sourceId:po.id,currency:po.currency,exchangeRate:po.exchangeRate,documentDate:date(parsed.date),net,gross:net,status:'DRAFT',lines:{create:receiptLines.map(nested)}},include:{lines:true}});for(const line of receipt.lines){if(!line.productId)continue;const product=await tx.product.findFirstOrThrow({where:{id:line.productId,organisationId}});const accepted=decimalUnits(line.quantity.toString(),6)-decimalUnits(line.damagedQuantity.toString(),6);if(product.kind==='PRODUCT'&&accepted>0n){if(!parsed.warehouseId)throw new Error('Choose the receiving warehouse for physical products.');if(accepted%1000000n!==0n)throw new Error('Inventory currently requires whole accepted units.');await stockReceipt(session,tx,{receiptId:receipt.id,receiptLineId:line.id,warehouseId:parsed.warehouseId,productId:line.productId,quantity:Number(accepted/1000000n),reference:receipt.reference});}}let journalId:string|undefined;if(net>0n){const a=await controls(tx,organisationId,po.entityId);const journal=await postLedger(tx,session,{entityId:po.entityId,date:receipt.documentDate,description:receipt.title,sourceKey:`receipt:${receipt.id}`,sourceType:'RECEIPT',sourceId:receipt.id,currency:po.currency,rate:po.exchangeRate.toString(),approverUserId:po.approverUserId??undefined,lines:[...await Promise.all(receiptLines.filter(l=>l.net>0n).map(async l=>{const product=l.productId?await tx.product.findFirstOrThrow({where:{id:l.productId,organisationId}}):null;return {accountId:a(po.capex?'ASSET':product&&product.kind!=='SERVICE'?'INVENTORY':'EXPENSE'),description:l.description,debit:l.net,credit:0n};})),{accountId:a('GRNI'),description:receipt.title,debit:0n,credit:net}]});journalId=journal.id;}await tx.financeDocument.update({where:{id:receipt.id},data:{status:'POSTED',journalId}});await tx.financeDocument.update({where:{id:po.id},data:{status:po.lines.every(l=>[...po.children.flatMap(d=>d.lines),...receiptLines].filter(r=>r.sourceLineId===l.id).reduce((sum,r)=>sum+decimalUnits(r.quantity.toString(),6),0n)>=decimalUnits(l.quantity.toString(),6))?'RECEIVED':'PART_RECEIVED'}});await tx.financeTimeline.create({data:{organisationId,documentId:receipt.id,actorUserId:session.userId,action:'RECEIVED',detail:'Receipt and accepted physical-product stock movements recorded atomically with valuation; damaged quantity excluded.'}});return receipt;});const receivedProducts=[...new Set(result.lines.flatMap(line=>line.productId?[line.productId]:[]))];if(receivedProducts.length){const {invoiceWhenBackInStock}=await import('./restock-invoice');await invoiceWhenBackInStock(session,receivedProducts);}refresh();return {id:result.id};
}
export async function onboardSupplier(form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.payables.manage');
 await requireFinance(session,'finance.payables.manage');const partyId=text(form,'partyId'),paymentDays=z.coerce.number().int().min(0).max(365).parse(text(form,'paymentDays')||'30');assertCapability(session,'customers.read');await db.party.findFirstOrThrow({where:{id:partyId,organisationId:session.organisationId}});
 await transaction(async tx=>{const supplier=await tx.financeSupplier.create({data:{organisationId:session.organisationId,partyId,creatorUserId:session.userId,paymentDays,currency:text(form,'currency')||'GBP',category:text(form,'category')}});await tx.auditEntry.create({data:{organisationId:session.organisationId,actorUserId:session.userId,action:'finance.supplier.requested',entityType:'FinanceSupplier',entityId:supplier.id}});});refresh();
}
export async function approveSupplier(id:string,form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.bank.verify');
 await requireFinance(session,'finance.bank.verify');const evidence=z.string().min(5).max(2000).parse(text(form,'evidence'));await transaction(async tx=>{const supplier=await tx.financeSupplier.findFirstOrThrow({where:{id,organisationId:session.organisationId,status:'REQUESTED'}});checkActorSeparation(supplier.creatorUserId,session.userId);await tx.financeSupplier.update({where:{id},data:{status:'ACTIVE',approvedByUserId:session.userId}});await tx.auditEntry.create({data:{organisationId:session.organisationId,actorUserId:session.userId,action:'finance.supplier.approved',entityType:'FinanceSupplier',entityId:id,after:{evidence}}});});refresh();
}
export async function requestSupplierBankChange(id:string,form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.bank.manage');
 await requireFinance(session,'finance.bank.manage');const organisationId=session.organisationId;const accountName=z.string().min(1).max(100).parse(text(form,'accountName')),accountNumber=z.string().regex(/^[A-Z0-9 -]{4,34}$/i).parse(text(form,'accountNumber')),sortCode=text(form,'sortCode'),iban=text(form,'iban'),evidence=z.string().min(5).max(2000).parse(text(form,'evidence'));
 await transaction(async tx=>{await tx.financeSupplier.findFirstOrThrow({where:{id,organisationId}});if(await tx.financeBankVersion.count({where:{organisationId,supplierId:id,status:'PENDING'}}))throw new Error('A bank change is already pending verification.');const fingerprint=createHash('sha256').update(`${sortCode.replace(/\W/g,'')}:${(iban||accountNumber).replace(/\W/g,'').toUpperCase()}`).digest('hex');await tx.financeBankVersion.create({data:{organisationId,supplierId:id,accountName,accountNumber,sortCode,iban,fingerprint,requesterUserId:session.userId,evidence}});await tx.auditEntry.create({data:{organisationId,actorUserId:session.userId,action:'finance.bank.change_requested',entityType:'FinanceSupplier',entityId:id,after:{masked:accountNumber.slice(-4),evidence}}});});refresh();
}
export async function verifySupplierBank(id:string,form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.bank.verify');
 await requireFinance(session,'finance.bank.verify');const reason=z.string().min(5).max(2000).parse(text(form,'reason'));await transaction(async tx=>{const organisationId=session.organisationId,bank=await tx.financeBankVersion.findFirstOrThrow({where:{id,organisationId,status:'PENDING'}});checkActorSeparation(bank.requesterUserId,session.userId);await tx.financeBankVersion.updateMany({where:{organisationId,supplierId:bank.supplierId,status:'VERIFIED'},data:{status:'SUPERSEDED'}});await tx.financeBankVersion.update({where:{id},data:{status:'VERIFIED',verifierUserId:session.userId,verifiedAt:new Date()}});await tx.auditEntry.create({data:{organisationId,actorUserId:session.userId,action:'finance.bank.verified',entityType:'FinanceBankVersion',entityId:id,after:{reason,masked:bank.accountNumber.slice(-4)}}});});refresh();
}
export async function createFinanceBank(form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.bank.manage');
 await requireFinance(session,'finance.bank.manage');const organisationId=session.organisationId,entityId=text(form,'entityId');await transaction(async tx=>{const entity=await tx.financeEntity.findFirstOrThrow({where:{id:entityId,organisationId}});const accountId=text(form,'accountId');const account=await tx.financeAccount.findFirstOrThrow({where:{id:accountId,organisationId,entityId,type:'ASSET'}});await tx.financeBank.create({data:{organisationId,entityId,accountId:account.id,name:z.string().min(1).max(100).parse(text(form,'name')),currency:entity.currency}});await tx.auditEntry.create({data:{organisationId,actorUserId:session.userId,action:'finance.bank.created',entityType:'FinanceBank',entityId:'new',after:{entityId}}});});refresh();
}
export async function importBankTransactions(bankId:string,input:unknown){
 const session=await requireSession();
 assertCapability(session,'finance.bank.manage');
 await requireFinance(session,'finance.bank.manage');const rows=z.array(z.object({externalId:z.string().min(1).max(100),date:z.string(),reference:z.string().min(1).max(300),amount:z.string()})).min(1).max(1000).parse(input);
 await transaction(async tx=>{const organisationId=session.organisationId,bank=await tx.financeBank.findFirstOrThrow({where:{id:bankId,organisationId}});for(const row of rows){const amount=minor(row.amount,bank.currency);if(amount===0n)throw new Error('Statement transaction cannot be zero.');await tx.financeBankTransaction.create({data:{organisationId,bankId,date:date(row.date),externalId:row.externalId,reference:row.reference,amount}});}await tx.auditEntry.create({data:{organisationId,actorUserId:session.userId,action:'finance.statement.imported',entityType:'FinanceBank',entityId:bankId,after:{count:rows.length}}});});refresh();
}
export async function allocateBankTransaction(id:string,input:unknown){
 const session=await requireSession();
 assertCapability(session,'finance.bank.manage');
 await requireFinance(session,'finance.bank.manage');const allocations=z.array(z.object({documentId:z.string(),amount:z.string()})).min(1).max(100).parse(input);if(new Set(allocations.map(a=>a.documentId)).size!==allocations.length)throw new Error('Choose each invoice once.');
 await transaction(async tx=>{const organisationId=session.organisationId,bankTx=await tx.financeBankTransaction.findFirstOrThrow({where:{id,organisationId,status:'UNRECONCILED'},include:{bank:true}}),incoming=bankTx.amount>0n;const docs=[];let total=0n;for(const a of allocations){const doc=await tx.financeDocument.findFirstOrThrow({where:{AND:[documentScope(session),{id:a.documentId,entityId:bankTx.bank.entityId,currency:bankTx.bank.currency,status:'POSTED',kind:{in:incoming?['AR_INVOICE','AR_DEBIT']:['AP_INVOICE','AP_DEBIT']}}]}});assertCapability(session,documentCapability(doc.kind,true));const amount=minor(a.amount,doc.currency);if(amount<=0n||amount>doc.gross-doc.settled)throw new Error('Allocation exceeds invoice outstanding balance.');docs.push({doc,amount});total+=amount;}
 const remaining=(incoming?bankTx.amount:-bankTx.amount)-bankTx.allocated;if(total!==remaining)throw new Error('Allocate the complete remaining bank amount.');const account=await controls(tx,organisationId,bankTx.bank.entityId);await postLedger(tx,session,{entityId:bankTx.bank.entityId,date:bankTx.date,description:bankTx.reference,sourceKey:`bank:${id}`,sourceType:'BANK',sourceId:id,currency:bankTx.bank.currency,rate:'1',lines:[{accountId:bankTx.bank.accountId,description:bankTx.reference,debit:incoming?total:0n,credit:incoming?0n:total},...docs.map(({doc,amount})=>({accountId:account(incoming?'AR':'AP'),description:doc.reference,debit:incoming?0n:amount,credit:incoming?amount:0n,partyId:doc.partyId}))]});for(const {doc,amount}of docs){await tx.financeSettlement.create({data:{organisationId,documentId:doc.id,bankTransactionId:id,amount,actorUserId:session.userId}});await tx.financeDocument.update({where:{id:doc.id},data:{settled:{increment:amount}}});await tx.financeTimeline.create({data:{organisationId,documentId:doc.id,actorUserId:session.userId,action:'SETTLED',detail:`Bank reference ${bankTx.reference}; allocated ${amount} minor units.`}});}await tx.financeBankTransaction.update({where:{id},data:{status:'RECONCILED',allocated:{increment:total}}});});refresh();
}
export async function createPaymentRun(input:unknown){
 const session=await requireSession();
 assertCapability(session,'finance.payment.create');
 await requireFinance(session,'finance.payment.create');const parsed=z.object({bankId:z.string(),documentIds:z.array(z.string()).min(1).max(500)}).parse(input);if(new Set(parsed.documentIds).size!==parsed.documentIds.length)throw new Error('Duplicate invoice in run.');
 const result=await transaction(async tx=>{const organisationId=session.organisationId,bank=await tx.financeBank.findFirstOrThrow({where:{id:parsed.bankId,organisationId}}),items=[];let total=0n;for(const documentId of parsed.documentIds){const doc=await tx.financeDocument.findFirstOrThrow({where:{AND:[documentScope(session),{id:documentId,entityId:bank.entityId,currency:bank.currency,kind:{in:['AP_INVOICE','AP_DEBIT']},status:'POSTED'}]}});if(doc.risk)throw new Error(`Invoice ${doc.reference} is held for review.`);const amount=doc.gross-doc.settled;if(amount<=0n)throw new Error('Invoice has no outstanding balance.');const supplier=await tx.financeSupplier.findFirstOrThrow({where:{organisationId,partyId:doc.partyId??'',status:'ACTIVE'},include:{bankVersions:true}});if(supplier.bankVersions.some(v=>v.status==='PENDING'))throw new Error('Supplier bank verification is pending.');const version=supplier.bankVersions.find(v=>v.status==='VERIFIED');if(!version)throw new Error('Supplier has no independently verified payment account.');const existing=await tx.financePaymentItem.count({where:{organisationId,documentId,run:{status:{in:['DRAFT','AWAITING_APPROVAL','APPROVED','RELEASED']}}}});if(existing)throw new Error(`Invoice ${doc.reference} already belongs to an active run.`);items.push({organisationId,documentId,bankVersionId:version.id,amount});total+=amount;}const run=await tx.financePaymentRun.create({data:{organisationId,entityId:bank.entityId,bankId:bank.id,reference:`PAY-${crypto.randomUUID().slice(0,10).toUpperCase()}`,creatorUserId:session.userId,total,currency:bank.currency,items:{create:items.map(nested)}}});await createApproval(tx,session,{subjectType:'PAYMENT_RUN',subjectId:run.id,subjectVersion:run.version,amount:total,currency:run.currency,context:{entityId:run.entityId}});await tx.financePaymentRun.update({where:{id:run.id},data:{status:'AWAITING_APPROVAL'}});return run;});refresh();return {id:result.id};
}
export async function approvePaymentRun(id:string,form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.payment.approve');
 await requireFinance(session,'finance.payment.approve');const reason=z.string().min(5).max(2000).parse(text(form,'reason'));await transaction(async tx=>{const organisationId=session.organisationId,run=await tx.financePaymentRun.findFirstOrThrow({where:{id,organisationId,status:'AWAITING_APPROVAL'}});checkActorSeparation(run.creatorUserId,session.userId);const instance=await tx.approvalInstance.findFirstOrThrow({where:{organisationId,subjectId:id,subjectType:'PAYMENT_RUN',subjectVersion:run.version,status:'PENDING'}});const result=await decideApproval(tx,session,instance.id,'APPROVED',reason);if(result.status==='APPROVED')await tx.financePaymentRun.update({where:{id},data:{status:'APPROVED',approverUserId:session.userId}});});refresh();
}
export async function createManualJournal(input:unknown){
 const session=await requireSession();
 assertCapability(session,'finance.journal.create');
 await requireFinance(session,'finance.journal.create');const parsed=z.object({entityId:z.string(),date:z.string(),description:z.string().min(5).max(500),lines:z.array(z.object({accountId:z.string(),description:z.string().min(1),debit:z.string(),credit:z.string()})).min(2).max(200)}).parse(input);
 const result=await transaction(async tx=>{const organisationId=session.organisationId,entity=await tx.financeEntity.findFirstOrThrow({where:{id:parsed.entityId,organisationId}}),accountingDate=date(parsed.date),period=await tx.financePeriod.findFirstOrThrow({where:{organisationId,entityId:entity.id,startAt:{lte:accountingDate},endAt:{gte:accountingDate},state:'OPEN'}});const lines=parsed.lines.map(l=>({organisationId,accountId:l.accountId,description:l.description,debit:minor(l.debit||'0',entity.currency),credit:minor(l.credit||'0',entity.currency),transactionDebit:minor(l.debit||'0',entity.currency),transactionCredit:minor(l.credit||'0',entity.currency)}));const amount=assertBalanced(lines),ids=[...new Set(lines.map(l=>l.accountId))];if(await tx.financeAccount.count({where:{organisationId,entityId:entity.id,id:{in:ids},active:true}})!==ids.length)throw new Error('Choose active accounts from this entity.');const journal=await tx.financeJournal.create({data:{organisationId,entityId:entity.id,periodId:period.id,reference:`JE-${crypto.randomUUID().slice(0,12).toUpperCase()}`,description:parsed.description,sourceKey:`manual:${crypto.randomUUID()}`,sourceType:'MANUAL',accountingDate,currency:entity.currency,creatorUserId:session.userId,lines:{create:lines.map(nested)}}});await createApproval(tx,session,{subjectType:'JOURNAL',subjectId:journal.id,subjectVersion:journal.version,amount,currency:journal.currency,context:{entityId:entity.id}});return journal;});refresh();return {id:result.id};
}
export async function approveManualJournal(id:string,form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.journal.post');
 await requireFinance(session,'finance.journal.post');const reason=z.string().min(5).max(2000).parse(text(form,'reason'));await transaction(async tx=>{const organisationId=session.organisationId,journal=await tx.financeJournal.findFirstOrThrow({where:{id,organisationId,sourceType:'MANUAL',status:'DRAFT'},include:{lines:true,period:true}});checkActorSeparation(journal.creatorUserId,session.userId);if(journal.period.state!=='OPEN')throw new Error('Accounting period is closed.');assertBalanced(journal.lines);const instance=await tx.approvalInstance.findFirstOrThrow({where:{organisationId,subjectType:'JOURNAL',subjectId:id,subjectVersion:journal.version,status:'PENDING'}}),result=await decideApproval(tx,session,instance.id,'APPROVED',reason);if(result.status==='APPROVED'){await tx.financeJournal.update({where:{id},data:{status:'POSTED',postedAt:new Date(),approverUserId:session.userId}});await tx.auditEntry.create({data:{organisationId,actorUserId:session.userId,action:'finance.manual_journal.posted',entityType:'FinanceJournal',entityId:id,after:{reason}}});}});refresh();
}
export async function reverseJournal(id:string,form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.journal.post');
 await requireFinance(session,'finance.journal.post');const reason=z.string().min(5).max(2000).parse(text(form,'reason'));await transaction(async tx=>{const original=await tx.financeJournal.findFirstOrThrow({where:{id,organisationId:session.organisationId,status:'POSTED',sourceType:'MANUAL'},include:{lines:true}});checkActorSeparation(original.creatorUserId,session.userId);await postLedger(tx,session,{entityId:original.entityId,date:date(text(form,'date')),description:`Reversal: ${reason}`,sourceKey:`reversal:${id}`,sourceType:'REVERSAL',sourceId:id,currency:original.currency,rate:'1',approverUserId:session.userId,reversalOfId:id,lines:original.lines.map(l=>({accountId:l.accountId,description:l.description,debit:l.credit,credit:l.debit}))});});refresh();
}
export async function setFinancePeriodState(id:string,form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.period.manage');
 await requireFinance(session,'finance.period.manage');const state=z.enum(['SOFT_CLOSED','CLOSED','LOCKED']).parse(text(form,'state')),reason=z.string().min(5).max(2000).parse(text(form,'reason'));await transaction(async tx=>{const organisationId=session.organisationId,period=await tx.financePeriod.findFirstOrThrow({where:{id,organisationId}});const rank:Record<string,number>={OPEN:0,SOFT_CLOSED:1,CLOSED:2,LOCKED:3};if(rank[state]<=rank[period.state])throw new Error('Reopening requires an independent approved request.');if(await tx.financeJournal.count({where:{organisationId,periodId:id,status:'DRAFT'}}))throw new Error('Resolve draft journals before closing.');if(['CLOSED','LOCKED'].includes(state)&&await tx.financeCloseTask.count({where:{organisationId,periodId:id,status:{not:'COMPLETE'}}}))throw new Error('Complete the close checklist before closing or locking.');await tx.financePeriod.update({where:{id},data:{state,version:{increment:1}}});await tx.auditEntry.create({data:{organisationId,actorUserId:session.userId,action:'finance.period.closed',entityType:'FinancePeriod',entityId:id,before:{state:period.state},after:{state,reason}}});});refresh();
}
export async function saveFinanceBudget(form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.planning.manage');
 await requireFinance(session,'finance.planning.manage');const organisationId=session.organisationId,entityId=text(form,'entityId'),entity=await db.financeEntity.findFirstOrThrow({where:{id:entityId,organisationId}}),amount=minor(text(form,'amount'),entity.currency),startAt=date(text(form,'startAt')),endAt=dateEnd(text(form,'endAt'));if(amount<=0n||startAt>=endAt)throw new Error('Enter a positive budget and valid date range.');await transaction(async tx=>{const budget=await tx.financeBudget.create({data:{organisationId,entityId,name:z.string().min(1).max(100).parse(text(form,'name')),amount,startAt,endAt,department:text(form,'department')||null,policy:z.enum(['WARN','APPROVAL','BLOCK']).parse(text(form,'policy'))}});await tx.auditEntry.create({data:{organisationId,actorUserId:session.userId,action:'finance.budget.created',entityType:'FinanceBudget',entityId:budget.id}});});refresh();
}
export async function saveFinanceAsset(form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.asset.manage');
 await requireFinance(session,'finance.asset.manage');const organisationId=session.organisationId,entityId=text(form,'entityId'),entity=await db.financeEntity.findFirstOrThrow({where:{id:entityId,organisationId}}),cost=minor(text(form,'cost'),entity.currency),residual=minor(text(form,'residual')||'0',entity.currency),lifeMonths=z.coerce.number().int().min(1).max(1200).parse(text(form,'lifeMonths'));if(cost<=0n||residual<0n||residual>=cost)throw new Error('Residual must be below positive acquisition cost.');await transaction(async tx=>{const asset=await tx.financeAsset.create({data:{organisationId,entityId,name:z.string().min(1).max(150).parse(text(form,'name')),acquiredAt:date(text(form,'acquiredAt')),cost,residual,lifeMonths,department:text(form,'department')||null,location:text(form,'location')||null,serialNumber:text(form,'serialNumber')||null}});await tx.auditEntry.create({data:{organisationId,actorUserId:session.userId,action:'finance.asset.created',entityType:'FinanceAsset',entityId:asset.id,after:{cost:cost.toString(),residual:residual.toString(),lifeMonths}}});});refresh();
}
export async function postAssetDepreciation(id:string,form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.asset.manage');
 assertCapability(session,'finance.journal.post');await requireFinance(session,'finance.asset.manage');await transaction(async tx=>{const organisationId=session.organisationId,asset=await tx.financeAsset.findFirstOrThrow({where:{id,organisationId,status:'ACTIVE'}}),postingDate=date(text(form,'date'));if(postingDate<asset.acquiredAt)throw new Error('Depreciation cannot precede acquisition.');const month=postingDate.toISOString().slice(0,7),sourceKey=`depreciation:${id}:${month}`;if(await tx.financeJournal.count({where:{organisationId,sourceKey}}))throw new Error('Depreciation already posted for this month.');const amount=roundRatio(asset.cost-asset.residual,BigInt(asset.lifeMonths)),remaining=asset.cost-asset.residual-asset.accumulated,depreciation=amount>remaining?remaining:amount;if(depreciation<=0n)throw new Error('Asset is fully depreciated.');const a=await controls(tx,organisationId,asset.entityId),entity=await tx.financeEntity.findFirstOrThrow({where:{id:asset.entityId,organisationId}});await postLedger(tx,session,{entityId:asset.entityId,date:postingDate,description:`Depreciation: ${asset.name}`,sourceKey,sourceType:'DEPRECIATION',sourceId:id,currency:entity.currency,rate:'1',lines:[{accountId:a('DEPRECIATION'),description:asset.name,debit:depreciation,credit:0n},{accountId:a('DEPRECIATION_ACCUMULATED'),description:asset.name,debit:0n,credit:depreciation}]});await tx.financeAsset.update({where:{id},data:{accumulated:{increment:depreciation},version:{increment:1}}});});refresh();
}
export async function completeCloseTask(id:string,form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.period.manage');
 await requireFinance(session,'finance.period.manage');const evidence=z.string().min(5).max(2000).parse(text(form,'evidence'));await transaction(async tx=>{const task=await tx.financeCloseTask.findFirstOrThrow({where:{id,organisationId:session.organisationId}});await tx.financeCloseTask.update({where:{id:task.id},data:{status:'COMPLETE',evidence,ownerUserId:session.userId}});await tx.auditEntry.create({data:{organisationId:session.organisationId,actorUserId:session.userId,action:'finance.close_task.completed',entityType:'FinanceCloseTask',entityId:id,after:{evidence}}});});refresh();
}
export async function saveFinanceContract(form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.purchase.manage');
 await requireFinance(session,'finance.purchase.manage');const organisationId=session.organisationId,entityId=text(form,'entityId'),entity=await db.financeEntity.findFirstOrThrow({where:{id:entityId,organisationId}});await transaction(async tx=>{const contract=await tx.financeContract.create({data:{organisationId,entityId,name:z.string().min(1).max(150).parse(text(form,'name')),annualAmount:minor(text(form,'annualAmount'),entity.currency),renewalAt:date(text(form,'renewalAt')),noticeDays:z.coerce.number().int().min(0).max(730).parse(text(form,'noticeDays')),ownerUserId:session.userId}});await tx.auditEntry.create({data:{organisationId,actorUserId:session.userId,action:'finance.contract.created',entityType:'FinanceContract',entityId:contract.id}});});refresh();
}
export async function saveFinanceScenario(form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.planning.manage');
 await requireFinance(session,'finance.planning.manage');const organisationId=session.organisationId,entityId=text(form,'entityId');await db.financeEntity.findFirstOrThrow({where:{id:entityId,organisationId}});const assumptions=z.object({revenueChangeBps:z.number().int().min(-10000).max(100000),additionalCost:z.string(),capex:z.string()}).parse(JSON.parse(text(form,'assumptions')));await transaction(async tx=>{const scenario=await tx.financeScenario.create({data:{organisationId,entityId,name:z.string().min(1).max(100).parse(text(form,'name')),ownerUserId:session.userId,assumptions}});await tx.auditEntry.create({data:{organisationId,actorUserId:session.userId,action:'finance.scenario.created',entityType:'FinanceScenario',entityId:scenario.id}});});refresh();
}
export async function receiptForm(poId:string,form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.purchase.manage');
 const lines=[...form.entries()].filter(([key,value])=>key.startsWith('quantity:')&&String(value).trim()&&decimalUnits(String(value),6)>0n).map(([key,value])=>({lineId:key.slice(9),quantity:String(value),damaged:text(form,`damaged:${key.slice(9)}`)||'0'}));return recordGoodsReceipt(poId,{warehouseId:text(form,'warehouseId')||undefined,date:text(form,'date'),lines});
}
export async function journalForm(form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.journal.create');
 const accountIds=form.getAll('accountId').map(String),debits=form.getAll('debit').map(String),credits=form.getAll('credit').map(String);return createManualJournal({entityId:text(form,'entityId'),date:text(form,'date'),description:text(form,'description'),lines:accountIds.map((accountId,i)=>({accountId,description:text(form,'description'),debit:debits[i]||'0',credit:credits[i]||'0'}))});
}
export async function statementForm(bankId:string,form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.bank.manage');
 const raw=text(form,'transactions');const rows=raw.split(/\r?\n/).filter(Boolean).map(line=>{const parts=line.split('\t');if(parts.length!==4)throw new Error('Use four tab-separated columns: external ID, date, reference, amount.');return {externalId:parts[0],date:parts[1],reference:parts[2],amount:parts[3]};});return importBankTransactions(bankId,rows);
}
export async function allocationForm(transactionId:string,form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.bank.manage');
 return allocateBankTransaction(transactionId,[...form.entries()].filter(([key,value])=>key.startsWith('allocate:')&&String(value).trim()&&String(value)!=='0').map(([key,value])=>({documentId:key.slice(9),amount:String(value)})));
}
export async function paymentRunForm(form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.payment.create');
 return createPaymentRun({bankId:text(form,'bankId'),documentIds:form.getAll('documentId').map(String)});
}
export async function policyForm(form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.configure');
 const stages=[0,1,2].map(i=>form.getAll(`stage${i}`).map(String).filter(Boolean)).filter(s=>s.length);form.set('stages',JSON.stringify(stages));const conditions:Record<string,string|boolean>={};for(const key of ['department','category','site','entityId'])if(text(form,key))conditions[key]=text(form,key);if(form.get('capexOnly')==='on')conditions.capex=true;form.set('conditions',JSON.stringify(conditions));return saveApprovalPolicy(form);
}
export async function scenarioForm(form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.planning.manage');
 form.set('assumptions',JSON.stringify({revenueChangeBps:Number(text(form,'revenueChangeBps')||'0'),additionalCost:text(form,'additionalCost')||'0',capex:text(form,'capex')||'0'}));return saveFinanceScenario(form);
}
export async function uploadFinanceAttachment(id:string,form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.overview.read');
 await requireFinance(session,'finance.overview.read');const file=form.get('file');if(!(file instanceof File)||file.size===0||file.size>2097152)throw new Error('Choose a PDF, PNG or JPEG up to 2 MB.');const bytes=Buffer.from(await file.arrayBuffer());const mimeType=bytes.subarray(0,5).toString()==='%PDF-'?'application/pdf':bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))?'image/png':bytes[0]===255&&bytes[1]===216&&bytes[2]===255?'image/jpeg':null;if(!mimeType)throw new Error('The file signature must be PDF, PNG or JPEG.');const checksum=createHash('sha256').update(bytes).digest('hex');await transaction(async tx=>{const doc=await tx.financeDocument.findFirstOrThrow({where:{AND:[documentScope(session),{id}]}});assertCapability(session,documentCapability(doc.kind,true));await tx.financeAttachment.create({data:{organisationId:session.organisationId,documentId:id,name:file.name.replace(/[\x00-\x1f/\\]/g,'_').slice(0,200),mimeType,checksum,content:bytes,uploadedByUserId:session.userId}});await tx.financeTimeline.create({data:{organisationId:session.organisationId,documentId:id,actorUserId:session.userId,action:'EVIDENCE_ADDED',detail:`Supporting ${mimeType} stored centrally; checksum recorded.`}});});refresh();
}

export async function generateSalesInvoice(orderId:string,form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.receivables.manage');
 await requireFinance(session,'finance.receivables.manage');assertCapability(session,'sales.order.read');const entityId=text(form,'entityId'),reason=z.string().min(5).max(2000).parse(text(form,'reason')),dueAt=date(text(form,'dueAt')),accountingDate=date(text(form,'date'));if(text(form,'basis')!=='ORDER_ON_ACCOUNT')throw new Error('Choose and review order-based invoicing. Dispatch-based invoicing requires Logistics evidence.');
 const result=await transaction(async tx=>{const source=await salesFinanceSource(session,tx,orderId),organisationId=session.organisationId,entity=await tx.financeEntity.findFirstOrThrow({where:{id:entityId,organisationId}});if(entity.currency!==source.currency)throw new Error('Select books in the Sales currency; cross-currency invoicing needs a verified exchange-rate policy.');const key=`sales-order:${orderId}`,existing=await tx.financeDocument.findFirst({where:{organisationId,duplicateKey:key}});if(existing)return existing;
 if(source.lines.some(l=>!['STANDARD','ZERO_RATED','EXEMPT','OUTSIDE_SCOPE'].includes(l.taxCategory??'')))throw new Error('Sales tax treatment must be verified before invoice generation.');const lines=source.lines.map((l,i)=>({number:i+1,salesOrderLineId:l.id,productId:l.productId,description:l.description,quantity:String(l.quantity),unitPrice:l.unitPrice,net:l.net,tax:l.tax,taxCode:l.taxCategory==='ZERO_RATED'?'ZERO':l.taxCategory==='STANDARD'?'STANDARD':l.taxCategory==='EXEMPT'?'EXEMPT':'OUTSIDE_SCOPE',taxRateBps:l.taxCategory==='STANDARD'?2000:0}));if(lines.some(l=>l.tax>0n&&roundRatio(l.net*2000n,10000n)!==l.tax))throw new Error('Unsupported Sales tax mapping; review Finance tax policy first.');
 const invoice=await tx.financeDocument.create({data:{organisationId,entityId:entity.id,kind:'AR_INVOICE',reference:`INV-${crypto.randomUUID().slice(0,10).toUpperCase()}`,title:`Invoice for ${source.reference}`,creatorUserId:session.userId,partyId:source.partyId,salesOrderId:orderId,salesOrderRevision:source.revision,duplicateKey:key,currency:source.currency,documentDate:accountingDate,dueAt,net:source.net,tax:source.tax,gross:source.gross,reason:`Order on account: ${reason}`,lines:{create:lines}}});await tx.financeTimeline.create({data:{organisationId,documentId:invoice.id,actorUserId:session.userId,action:'GENERATED_FROM_SALES',detail:`${source.reference} revision ${source.revision}; order-based billing reviewed: ${reason}. No stock dispatch is implied.`}});await tx.auditEntry.create({data:{organisationId,actorUserId:session.userId,action:'finance.sales_invoice.generated',entityType:'FinanceDocument',entityId:invoice.id,after:{orderId,revision:source.revision,gross:source.gross.toString(),basis:'ORDER_ON_ACCOUNT'}}});return invoice;});refresh();revalidatePath(`/sales/orders/${orderId}`);return {id:result.id};
}
export async function generateInvoiceAdjustment(id:string,form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.overview.read');
 await requireFinance(session,'finance.overview.read');const kind=z.enum(['CREDIT','DEBIT']).parse(text(form,'kind')),reason=z.string().min(5).max(2000).parse(text(form,'reason')),requestKey=z.string().uuid().parse(text(form,'requestKey'));
 const result=await transaction(async tx=>{const organisationId=session.organisationId,source=await tx.financeDocument.findFirstOrThrow({where:{AND:[documentScope(session),{id,kind:{in:['AR_INVOICE','AP_INVOICE']},status:'POSTED'}]},include:{lines:true}}),noteKind=source.kind.replace('_INVOICE',`_${kind}`);assertCapability(session,documentCapability(noteKind,true));const existing=await tx.financeDocument.findFirst({where:{organisationId,duplicateKey:`adjustment:${requestKey}`}});if(existing){if(existing.sourceId!==id||existing.kind!==noteKind)throw new Error('Adjustment request already used for a different invoice.');return existing;}const line=source.lines.find(l=>l.id===text(form,'lineId'));if(!line||line.net<=0n)throw new Error('Choose a source line with a positive net amount.');const net=minor(text(form,'net'),source.currency);if(net<=0n)throw new Error('Enter a positive net adjustment.');const tax=roundRatio(net*line.tax,line.net);if(kind==='CREDIT'&&net+tax>source.gross-source.settled)throw new Error('Credit exceeds the outstanding invoice balance. Refund/on-account credits require the refund workflow.');
 const note=await tx.financeDocument.create({data:{organisationId,entityId:source.entityId,kind:noteKind,reference:`${kind==='CREDIT'?'CN':'DN'}-${crypto.randomUUID().slice(0,10).toUpperCase()}`,title:`${kind==='CREDIT'?'Credit':'Debit'} note for ${source.reference}`,creatorUserId:session.userId,partyId:source.partyId,projectId:source.projectId,sourceId:source.id,salesOrderId:source.salesOrderId,salesOrderRevision:source.salesOrderRevision,duplicateKey:`adjustment:${requestKey}`,currency:source.currency,exchangeRate:source.exchangeRate,documentDate:date(text(form,'date')),dueAt:source.dueAt,net,tax,gross:net+tax,department:source.department,costCentre:source.costCentre,site:source.site,reason,lines:{create:[{number:1,description:`${kind==='CREDIT'?'Credit':'Debit'} value adjustment: ${line.description}`,quantity:'1',unitPrice:net,net,tax,taxCode:line.taxCode,taxRateBps:line.taxRateBps,sourceLineId:line.id,productId:line.productId,salesOrderLineId:line.salesOrderLineId,accountId:line.accountId}]}}});await tx.financeTimeline.create({data:{organisationId,documentId:note.id,actorUserId:session.userId,action:'ADJUSTMENT_GENERATED',detail:`Original ${source.reference}, line ${line.number}: ${reason}. Financial value adjustment; no physical return/stock movement.`}});await tx.auditEntry.create({data:{organisationId,actorUserId:session.userId,action:'finance.adjustment.generated',entityType:'FinanceDocument',entityId:note.id,after:{kind:noteKind,sourceId:id,gross:(net+tax).toString(),reason}}});return note;});refresh();return {id:result.id};
}
export async function voidFinanceDraft(id:string,form:FormData){
 const session=await requireSession();
 assertCapability(session,'finance.overview.read');
 await requireFinance(session,'finance.overview.read');const reason=z.string().min(5).max(2000).parse(text(form,'reason'));await transaction(async tx=>{const doc=await tx.financeDocument.findFirstOrThrow({where:{AND:[documentScope(session),{id,status:{in:['DRAFT','AWAITING_APPROVAL','NEEDS_INFORMATION','REJECTED','APPROVED']},journalId:null}]}});assertCapability(session,documentCapability(doc.kind,true));if(['PO','RECEIPT'].includes(doc.kind))throw new Error('Purchasing cancellation requires receipt/commitment review.');await tx.approvalInstance.updateMany({where:{organisationId:session.organisationId,subjectId:id,status:'PENDING'},data:{status:'CANCELLED'}});await tx.financeDocument.update({where:{id},data:{status:'CANCELLED',duplicateKey:doc.salesOrderId?null:doc.duplicateKey,version:{increment:1}}});await tx.financeTimeline.create({data:{organisationId:session.organisationId,documentId:id,actorUserId:session.userId,action:'VOIDED',detail:reason}});await tx.auditEntry.create({data:{organisationId:session.organisationId,actorUserId:session.userId,action:'finance.draft.voided',entityType:'FinanceDocument',entityId:id,after:{reason}}});});refresh();
}
