import { db } from '@/core/db/client';
import type { Session } from '@/core/auth/session';
import { projectScope } from '@/core/permissions/work-access';
import { recordDataset, money } from '@/core/reports/records';
import { text, date, amount, boolean } from '@/core/reports/columns';
import { documentScope } from './access';
export async function reportJournalScope(session: Session) {
 const projects=session.capabilities.has('projects.read')?await db.project.findMany({where:projectScope(session),select:{id:true}}):[];
 return {organisationId:session.organisationId,documents:{every:documentScope(session)},lines:{every:{OR:[{projectId:null},{projectId:{in:projects.map(p=>p.id)}}]}}};
}
export const reports=[
recordDataset({id:'finance.documents',name:'Finance documents',source:'Finance',description:'Authorised purchases, invoices, credits and spend documents. Restricted document kinds and private projects are excluded. Amounts use document currency.',anyOf:['finance.purchase.read','finance.payables.read','finance.receivables.read','finance.spend.read','finance.request.create','finance.expense.create','finance.approval.decide','finance.overview.read'],dateField:'documentDate',columns:[text('reference','Reference'),text('kind','Document kind'),text('status','Status'),text('entity','Legal entity','entity.name'),text('party','Customer / supplier','party.name'),text('currency','Currency'),amount('net','Net'),amount('tax','Tax'),amount('gross','Total'),amount('settled','Settled'),date('documentDate','Document date'),date('accountingDate','Accounting date'),date('dueAt','Due date'),text('department','Department'),text('costCentre','Cost centre')]},
(s,w,take,skip)=>db.financeDocument.findMany({where:{AND:[documentScope(s),w]},select:{reference:true,kind:true,status:true,entity:{select:{name:true}},party:{select:{name:true}},currency:true,net:true,tax:true,gross:true,settled:true,documentDate:true,accountingDate:true,dueAt:true,department:true,costCentre:true},orderBy:[{documentDate:'desc'},{id:'asc'}],take,skip}),
(s,w)=>db.financeDocument.count({where:{AND:[documentScope(s),w]}}),r=>({...r,entity:r.entity.name,party:r.party?.name??null,net:money(r.net),tax:money(r.tax),gross:money(r.gross),settled:money(r.settled)})),
recordDataset({id:'finance.accounts',name:'Chart of accounts',source:'Finance',description:'Ledger accounts by legal entity, including posting and active flags.',anyOf:['finance.ledger.read'],columns:[text('code','Account code'),text('name','Account'),text('entity','Legal entity','entity.name'),text('currency','Base currency','entity.currency'),text('type','Type'),text('control','Control'),boolean('active','Active'),boolean('postingAllowed','Posting allowed')]},
(s,w,take,skip)=>db.financeAccount.findMany({where:{AND:[{organisationId:s.organisationId},w]},select:{code:true,name:true,entity:{select:{name:true,currency:true}},type:true,control:true,active:true,postingAllowed:true},orderBy:[{code:'asc'},{id:'asc'}],take,skip}),
(s,w)=>db.financeAccount.count({where:{AND:[{organisationId:s.organisationId},w]}}),r=>({...r,entity:r.entity.name,currency:r.entity.currency})),
recordDataset({id:'finance.ledger',name:'Ledger entries',source:'Finance',description:'Authorised journal lines. Entire journals involving restricted documents or projects are excluded. Debit and credit are in entity base currency; transaction amounts use journal currency.',anyOf:['finance.ledger.read'],dateField:'journal.accountingDate',columns:[text('reference','Journal','journal.reference'),text('status','Journal status','journal.status'),text('entity','Legal entity','journal.entity.name'),text('account','Account','account.code'),text('accountName','Account name','account.name'),date('accountingDate','Accounting date','journal.accountingDate'),text('baseCurrency','Base currency','journal.entity.currency'),amount('debit','Base debit'),amount('credit','Base credit'),text('currency','Transaction currency','journal.currency'),amount('transactionDebit','Transaction debit'),amount('transactionCredit','Transaction credit'),text('department','Department'),text('costCentre','Cost centre')]},
async(s,w,take,skip)=>db.financeJournalLine.findMany({where:{AND:[{organisationId:s.organisationId,journal:await reportJournalScope(s)},w]},select:{journal:{select:{reference:true,status:true,entity:{select:{name:true,currency:true}},accountingDate:true,currency:true}},account:{select:{code:true,name:true}},debit:true,credit:true,transactionDebit:true,transactionCredit:true,department:true,costCentre:true},orderBy:[{journal:{accountingDate:'desc'}},{id:'asc'}],take,skip}),
async(s,w)=>db.financeJournalLine.count({where:{AND:[{organisationId:s.organisationId,journal:await reportJournalScope(s)},w]}}),r=>({reference:r.journal.reference,status:r.journal.status,entity:r.journal.entity.name,account:r.account.code,accountName:r.account.name,accountingDate:r.journal.accountingDate,baseCurrency:r.journal.entity.currency,debit:money(r.debit),credit:money(r.credit),currency:r.journal.currency,transactionDebit:money(r.transactionDebit),transactionCredit:money(r.transactionCredit),department:r.department,costCentre:r.costCentre}))];
