import Link from 'next/link';
import { requireSession } from '@/core/auth/session';
import { assertCapability, can } from '@/core/permissions/check';
import { db } from '@/core/db/client';
import { staffContract } from '@/core/contracts/access';
import { sendContract, deleteContract, revokeContract, reviewContractReturn, updateDraftContract } from '@/core/contracts/actions';
import { ShareLinkButton } from '@/app/(app)/_shared/share-link-button';
import { ActionForm } from '@/components/ui/action-form';
import { Button } from '@/components/ui/button';
const when=(d:Date|null)=>d?d.toLocaleString('en-GB',{timeZone:'Europe/London',dateStyle:'medium',timeStyle:'short'}):'Not yet';
const field='mt-1 block w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm';
export default async function Page({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{email?:string}>}){
 const s=await requireSession();assertCapability(s,'core.contract.manage');const c=await staffContract(s,(await params).id),notice=(await searchParams).email==='failed';
 const [returns,accounts,party,events]=await Promise.all([db.contractReturn.findMany({where:{contractId:c.id,organisationId:s.organisationId},select:{id:true,fileName:true,fileSize:true,contentHash:true,signerName:true,submittedAt:true,status:true,reviewNote:true,reviewedAt:true},orderBy:{submittedAt:'desc'}}),can(s,'core.email.send')?db.emailAccount.findMany({where:{organisationId:s.organisationId,active:true,OR:[{scope:'COMPANY'},{scope:'PERSONAL',ownerUserId:s.userId}]},select:{id:true,label:true}}):[],c.partyId?db.party.findFirst({where:{id:c.partyId,organisationId:s.organisationId},select:{name:true}}):null,db.auditEntry.findMany({where:{organisationId:s.organisationId,entityType:'ContractDocument',entityId:c.id},select:{id:true,action:true,createdAt:true},orderBy:{createdAt:'desc'},take:100})]);
 const open=['DRAFT','SENT','VIEWED','DECLINED','REVOKED'].includes(c.status);
 return <div className="space-y-6"><Link href="/crm/contracts" className="text-xs text-blue-700">← Contracts & approvals</Link><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-slate-400">{c.reference} · {c.status==='RETURNED'?'Returned · review needed':c.status.toLowerCase()}</p><h1 className="mt-1 text-2xl font-semibold">{c.title}</h1><p className="mt-2 text-sm text-slate-500">{party?.name??'Business document'}{c.templateVersion?` · Template origin v${c.templateVersion}`:''} · {c.signingMode==='ONLINE'?'Online signature':c.signingMode==='UPLOAD'?'Signed PDF return':'Online signature or PDF return'}</p></div><div className="flex gap-3 text-sm text-blue-700">{c.opportunityId&&<Link href={`/crm/opportunities/${c.opportunityId}`}>Open deal</Link>}{c.sourceModule==='sales'&&c.sourceId&&<Link href={`/sales/${c.sourceType==='quote'?'quotes':'orders'}/${c.sourceId}`}>Open source</Link>}{c.sourceModule==='projects'&&c.sourceId&&<Link href={`/projects/${c.sourceId}`}>Open project</Link>}{c.sourceModule==='service'&&c.sourceId&&<Link href={`/service/cases/${c.sourceId}`}>Open case</Link>}</div></div>
 {notice&&<p role="alert" className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Your contract was saved, but the email could not be sent. Check the email account or copy a share link below.</p>}
 {c.status==='DRAFT'&&<details className="rounded-2xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer text-sm font-semibold text-blue-700">Edit draft before sharing</summary><ActionForm action={updateDraftContract} className="mt-4 space-y-4"><input type="hidden" name="updatedAt" value={c.updatedAt.toISOString()}/><input type="hidden" name="id" value={c.id}/><label className="block text-xs font-medium">Title<input name="title" required maxLength={300} defaultValue={c.title} className={field}/></label><label className="block text-xs font-medium">Message<textarea name="message" maxLength={2000} defaultValue={c.message} className={field}/></label><label className="block text-xs font-medium">Customer can<select name="signingMode" defaultValue={c.signingMode} className={field}><option value="BOTH">Sign online or return a signed PDF</option><option value="ONLINE">Sign online</option><option value="UPLOAD">Return a signed PDF</option></select></label><label className="block text-xs font-medium">Replace PDF (optional)<input name="file" type="file" accept="application/pdf,.pdf" className={field}/></label><label className="block text-xs font-medium">Or replace the complete terms (optional)<textarea name="body" rows={6} maxLength={50000} placeholder="Leave both replacement fields blank to keep the current document." className={field}/></label><p className="text-xs text-slate-500">Once shared, the document is frozen. Template origin is retained when draft content is revised.</p><Button type="submit" variant="primary">Save draft changes</Button></ActionForm></details>}
 <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><section className="space-y-4"><div className="flex flex-wrap gap-3 text-sm"><a href={`/api/contracts/${c.id}/file`} target="_blank" rel="noopener" className="text-blue-700">Open original PDF ↗</a>{c.status==='SIGNED'&&<a href={`/api/contracts/${c.id}/record`} className="text-emerald-700">Download completed document & record</a>}</div>{c.fileName&&<object data={`/api/contracts/${c.id}/file#view=FitH`} type="application/pdf" className="h-[70vh] min-h-[440px] w-full rounded-2xl border border-slate-200 bg-white"><p className="p-6">Use Open original PDF to review the document.</p></object>}{!c.fileName&&<article className="rounded-2xl border border-slate-200 bg-white p-7" dangerouslySetInnerHTML={{__html:c.bodyHtml}}/>}
 {!!returns.length&&<section className="space-y-3"><h2 className="font-semibold">Signed PDF returns</h2>{returns.map(r=><article key={r.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex justify-between gap-4"><div><a href={`/api/contracts/${c.id}/returns/${r.id}`} target="_blank" rel="noopener" className="font-medium text-blue-700">{r.fileName} ↗</a><p className="mt-1 text-xs text-slate-500">Submitted by {r.signerName} · {when(r.submittedAt)} · {r.status.toLowerCase()}</p></div></div><p className="mt-2 break-all font-mono text-[10px] text-slate-400">SHA-256 {r.contentHash}</p>{r.reviewNote&&<p className="mt-3 text-sm text-slate-600">Review: {r.reviewNote}</p>}{r.status==='PENDING'&&c.status==='RETURNED'&&<ActionForm action={reviewContractReturn} className="mt-4 space-y-3"><input type="hidden" name="id" value={c.id}/><input type="hidden" name="returnId" value={r.id}/><label className="block text-xs font-medium">Review note (required when rejecting)<textarea name="reviewNote" rows={2} maxLength={2000} className={field}/></label><label className="block text-xs font-medium">Decision<select name="decision" className={field}><option value="ACCEPT">Accept as completed contract</option><option value="REJECT">Ask for a corrected signed copy</option></select></label><p className="text-xs text-slate-500">Read the returned file and check the agreed terms and signatures before accepting it.</p><Button type="submit" variant="primary">Save review</Button></ActionForm>}</article>)}</section>}
 </section><aside className="space-y-4">{open&&<section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Share with the customer</h2><p className="text-xs leading-5 text-slate-500">A private Atlas review page. Anyone with the link can open it; share it only with the intended signer. A new link cancels the previous one.</p><ShareLinkButton contractId={c.id}/>{!!accounts.length&&<details><summary className="cursor-pointer text-sm text-blue-700">Send by email</summary><ActionForm action={sendContract} className="mt-3 space-y-3"><input type="hidden" name="id" value={c.id}/><label className="block text-xs font-medium">To<input name="to" type="email" required defaultValue={c.signerEmail??''} className={field}/></label><label className="block text-xs font-medium">From<select name="accountId" className={field}>{accounts.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></label><label className="block text-xs font-medium">Link expires in<select name="validDays" defaultValue="30" className={field}>{[7,14,30,60,90].map(d=><option key={d} value={d}>{d} days</option>)}</select></label><Button type="submit" variant="primary">Send invitation</Button></ActionForm></details>}{c.status==='DRAFT'?<ActionForm action={deleteContract}><input type="hidden" name="id" value={c.id}/><button className="text-xs text-red-600">Delete unsent draft</button></ActionForm>:<ActionForm action={revokeContract}><input type="hidden" name="id" value={c.id}/><button className="text-xs text-red-600">Revoke customer link</button></ActionForm>}</section>}
 <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Document record</h2><dl className="mt-4 space-y-3 text-xs">{[['Created',when(c.createdAt)],['Sent',when(c.sentAt)],['Opened',when(c.viewedAt)],['Completed',when(c.signedAt)],['Signed by',c.signerName??'Not yet'],['Sent to',c.signerEmail??'Shared by link'],['Completion method',c.completionMethod==='UPLOAD'?'Returned PDF · staff reviewed':c.completionMethod==='ONLINE'?'Electronic signature':'Not yet'],['Network address',c.signerIp??'Not recorded']].map(([k,v])=><div key={k}><dt className="text-slate-400">{k}</dt><dd className="mt-0.5 text-slate-700">{v}</dd></div>)}</dl><p className="mt-4 text-xs text-slate-400">Original document fingerprint</p><p className="mt-1 break-all font-mono text-[10px] text-slate-500">{c.contentHash}</p></section>
 <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Timeline</h2><ol className="mt-4 space-y-4">{events.map(e=><li key={e.id}><p className="text-xs font-medium capitalize">{e.action.replaceAll('.',' ').replaceAll('_',' ')}</p><p className="mt-1 text-xs text-slate-400">{when(e.createdAt)}</p></li>)}</ol></section></aside></div></div>;
}
