/** Explicit server-only browser acceptance; fixture access revoked, central audit retained. */
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import bcrypt from 'bcryptjs';
import { chromium } from '@playwright/test';
import { db } from '../src/core/db/client';
async function main(){
 assert(process.platform==='linux'&&process.env.ATLAS_QUALITY_TEST==='1'&&process.env.ATLAS_RUNTIME!=='desktop','Explicit server acceptance required');
 const base='https://atlassystem.online',suffix=randomBytes(8).toString('hex'),password=randomBytes(24).toString('base64url'),companies:string[]=[],users:string[]=[];
 const overdueDate=new Date(Date.now()-86400000).toISOString().slice(0,10);
 let checks=0;const check=(condition:unknown,label:string)=>{assert(condition,label);checks++;console.log(`PASS ${label}`);};
 const manifest=JSON.parse(await readFile('.next/server/server-reference-manifest.json','utf8'));
 const post=async(name:string,values:Record<string,string>,cookie='')=>{
  const candidates=Object.entries(manifest.node as Record<string,{exportedName?:string;workers?:Record<string,unknown>}>).filter(([,value])=>value.exportedName===name);
  const action=candidates.find(([,value])=>Object.keys(value.workers??{}).some(key=>key.includes(name==='reportNcr'?'quality/ncr/new':'quality/ncr/[')))??candidates[0];assert(action,`Action ${name}`);
  const form=new FormData();for(const [key,value]of Object.entries(values))form.set(`_1_${key}`,value);form.set('0','["$K1"]');
  const response=await fetch(base+(name==='loginAction'?'/login':'/quality/ncr/new'),{method:'POST',headers:{Origin:base,'Next-Action':action[0],Accept:'text/x-component',...(cookie?{Cookie:cookie}:{})},body:form,redirect:'manual'});
  return {response,body:await response.text()};
 };
 const login=async(email:string)=>{const result=await post('loginAction',{email,password});const cookie=result.response.headers.get('set-cookie')?.match(/atlas_session=[^;]+/)?.[0];assert(cookie,'Normal login');return cookie;};
 try{
  for(const kind of ['inside','outside']){const org=await db.organisation.create({data:{name:`Synthetic quality ${kind}`,slug:`quality-${kind}-${suffix}`,isTest:true}});companies.push(org.id);await db.moduleState.create({data:{organisationId:org.id,moduleId:'quality',enabled:true,entitled:true}});}
  const caps=['quality.today.read','quality.ncr.read','quality.ncr.report','quality.ncr.manage','quality.ncr.close','quality.check.execute','quality.hold.read','quality.report.read'];
  const makeUser=async(name:string,grants:string[],organisationId=companies[0])=>{const user=await db.user.create({data:{name:`Synthetic ${name}`,email:`quality-${name}-${suffix}@example.test`,passwordHash:await bcrypt.hash(password,10)}});users.push(user.id);await db.membership.create({data:{organisationId,userId:user.id,grantedCapabilities:grants}});return user;};
  const worker=await makeUser('manager',caps),reader=await makeUser('reader',['quality.today.read','quality.ncr.read']),foreign=await makeUser('outside',caps,companies[1]);
  const workerCookie=await login(worker.email),readerCookie=await login(reader.email),foreignCookie=await login(foreign.email);
  const product=await db.product.create({data:{organisationId:companies[0],code:'TEST-Q',name:'Synthetic quality component',basePriceAmount:0}}),outsideProduct=await db.product.create({data:{organisationId:companies[1],code:'TEST-Q',name:'Synthetic foreign component',basePriceAmount:0}});
  const spec=await db.qualitySpecification.create({data:{organisationId:companies[0],productId:product.id,code:'TEST-SPEC',title:'Synthetic acceptance',revision:'1',status:'EFFECTIVE',createdByUserId:worker.id,characteristics:{create:[{organisationId:companies[0],name:'Diameter',method:'MEASUREMENT',unit:'mm',lowerLimit:0,upperLimit:10,position:0},{organisationId:companies[0],name:'Finish',method:'VISUAL',position:1},{organisationId:companies[0],name:'Packaging',method:'PASS_FAIL',position:2}]}},include:{characteristics:{orderBy:{position:'asc'}}}});
  const point=await db.qualityControlPoint.create({data:{organisationId:companies[0],code:'TEST-RECEIPT',name:'Synthetic receiving check',productId:product.id,specificationId:spec.id,trigger:'RECEIPT',sampleSize:2}}),manual=await db.qualityControlPoint.create({data:{organisationId:companies[0],code:'TEST-MANUAL',name:'Synthetic manual check',productId:product.id,trigger:'MANUAL'}});
  const browser=await chromium.launch({args:['--no-sandbox'],...(process.env.ATLAS_CHROMIUM_PATH?{executablePath:process.env.ATLAS_CHROMIUM_PATH}:{})});
  try{
   const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addCookies([{name:'atlas_session',value:workerCookie.slice(14),url:base,httpOnly:true,secure:true}]);const page=await context.newPage();let errors=0;page.on('pageerror',()=>errors++);
   const versionWait=async(view:typeof page,version:number)=>view.waitForFunction(value=>Array.from(document.querySelectorAll<HTMLInputElement>('input[name="version"]')).some(input=>input.value===String(value)),version);
   await page.goto(base+'/quality/ncr/new',{waitUntil:'domcontentloaded'});await page.getByLabel('What failed?',{exact:true}).fill('Synthetic quality issue');await page.getByLabel('Requirement / defect',{exact:true}).fill('Diameter exceeds the specified tolerance');await page.getByLabel('Severity',{exact:true}).selectOption('MAJOR');await page.getByLabel('Source',{exact:true}).selectOption('CUSTOMER');await page.getByLabel('Product',{exact:true}).selectOption(product.id);await page.getByLabel('Issue owner',{exact:true}).selectOption(worker.id);await page.getByLabel('Target resolution date',{exact:true}).fill(overdueDate);await page.getByLabel('Immediate containment',{exact:true}).fill('Affected batch identified and separated for review');await page.getByText('Context, impact and evidence',{exact:true}).click();await page.getByLabel('Lot / batch / serial reference',{exact:true}).fill('LOT-SYNTHETIC');await page.getByLabel('Evidence / document references',{exact:true}).fill('Synthetic measurement record TEST-MEASUREMENT');await page.getByRole('button',{name:'Report quality issue',exact:true}).click();await page.waitForURL(/\/quality\/ncr\/(?!new)[^/]+$/);
   const ncr=await db.nonConformance.findFirstOrThrow({where:{organisationId:companies[0],title:'Synthetic quality issue'}}),url=page.url();check(ncr.ownerUserId===worker.id&&ncr.dueAt?.toISOString().slice(0,10)===overdueDate&&(ncr.workspace as {lot:string}).lot==='LOT-SYNTHETIC','Rich issue context, owner and target persist centrally');
   await page.goto(base+'/quality/ncr?mine=1&due=overdue&q=Synthetic',{waitUntil:'domcontentloaded'});check(await page.getByText('Synthetic quality issue',{exact:true}).count()===1,'Search, assigned-to-me and overdue issue filters work');await page.goto(url,{waitUntil:'domcontentloaded'});await page.getByText('Edit issue and investigation',{exact:true}).click();
   const second=await context.newPage();await second.goto(url,{waitUntil:'domcontentloaded'});await second.getByText('Edit issue and investigation',{exact:true}).click();await second.getByLabel('What failed?',{exact:true}).fill('Stale investigation retained');
   await page.getByLabel('Root cause',{exact:true}).fill('Incorrect setup reference used');await page.getByLabel('Evidence supporting the root cause',{exact:true}).fill('Setup record compared with approved specification');await page.getByLabel('Root cause confirmed by evidence',{exact:true}).check();await page.getByLabel('Disposition',{exact:true}).selectOption('REWORK');await page.getByLabel('Disposition reason / authorisation reference',{exact:true}).fill('Approved rework instruction TEST-RW');await page.getByRole('button',{name:'Save issue and investigation',exact:true}).click();await versionWait(page,2);
   await second.getByRole('button',{name:'Save issue and investigation',exact:true}).click();await second.getByRole('alert').filter({hasText:'changed'}).waitFor();check(await second.getByLabel('What failed?',{exact:true}).inputValue()==='Stale investigation retained'&&(await db.nonConformance.findUniqueOrThrow({where:{id:ncr.id}})).title==='Synthetic quality issue','Stale investigation cannot overwrite a newer issue and retains draft');await second.close();check(await page.getByRole('button',{name:'Close quality issue',exact:true}).isDisabled(),'Major issue cannot close without verified corrective action');
   await page.getByText('Add corrective action',{exact:true}).click();await page.getByLabel('Action description',{exact:true}).fill('Correct setup and verify next production batches');await page.getByLabel('Action owner',{exact:true}).selectOption(worker.id);await page.getByLabel('Action due date',{exact:true}).fill(overdueDate);await page.getByLabel('Effectiveness review date',{exact:true}).fill(overdueDate);await page.getByLabel('How will you know the fix worked?',{exact:true}).fill('No repeat defect in the next 20 batches');await page.getByRole('button',{name:'Save corrective action',exact:true}).click();await versionWait(page,3);
   const action=await db.nonConformanceAction.findFirstOrThrow({where:{organisationId:companies[0],ncrId:ncr.id}});check(action.ownerUserId===worker.id&&action.effectivenessCriterion?.includes('20 batches'),'Owned corrective action and effectiveness criterion save centrally');
   await page.goto(base+'/quality/actions?mine=1&due=overdue',{waitUntil:'domcontentloaded'});check(await page.getByRole('link',{name:/Correct setup and verify/}).count()===1,'Assigned overdue corrective action appears on action board');await page.goto(url,{waitUntil:'domcontentloaded'});
   const bypass=await post('updateNcrAction',{ncrId:ncr.id,version:'3',actionId:action.id,status:'VERIFIED',effectivenessResult:'Attempted premature verification'},workerCookie);check(bypass.body.includes('completion')&&(await db.nonConformance.findUniqueOrThrow({where:{id:ncr.id}})).version===3&&(await db.nonConformanceAction.findUniqueOrThrow({where:{id:action.id}})).status==='OPEN','Premature verification rejects and rolls back parent version');
   await page.getByRole('button',{name:'Update action',exact:true}).click();await versionWait(page,4);await page.getByLabel(`Next step for ${action.description}`,{exact:true}).selectOption('INEFFECTIVE');await page.getByLabel(`Review evidence for ${action.description}`,{exact:true}).fill('Repeat failure found in subsequent checked batches');await page.getByRole('button',{name:'Update action',exact:true}).click();await versionWait(page,5);check(await page.getByRole('button',{name:'Close quality issue',exact:true}).isDisabled(),'Ineffective corrective work prevents closure');
   await page.getByRole('button',{name:'Update action',exact:true}).click();await versionWait(page,6);await page.getByRole('button',{name:'Update action',exact:true}).click();await versionWait(page,7);await page.getByLabel(`Review evidence for ${action.description}`,{exact:true}).fill('Reviewed 20 subsequent batches; no repeat defect found');await page.getByRole('button',{name:'Update action',exact:true}).click();await versionWait(page,8);check((await db.nonConformanceAction.findUniqueOrThrow({where:{id:action.id}})).status==='VERIFIED','Ineffective action can reopen, complete and verify with evidence');
   await page.getByLabel('Closure evidence',{exact:true}).fill('Reviewed disposition, root cause and verified outcomes');await page.getByRole('button',{name:'Close quality issue',exact:true}).click();await page.getByText(/^Closed · Owner:/).waitFor();check((await db.nonConformance.findUniqueOrThrow({where:{id:ncr.id}})).status==='CLOSED'&&await page.getByText('Edit issue and investigation',{exact:true}).count()===0,'Evidence-based closure freezes issue editing');
   await page.getByText('Reopen with a reason',{exact:true}).click();await page.getByLabel('Reopen reason',{exact:true}).fill('New customer information requires further investigation');await page.getByRole('button',{name:'Reopen issue',exact:true}).click();await versionWait(page,10);check((await db.nonConformance.findUniqueOrThrow({where:{id:ncr.id}})).status==='INVESTIGATING','Reasoned reopening retains the closed record history');
   await page.goto(base+`/quality/checks?controlPointId=${point.id}`,{waitUntil:'domcontentloaded'});await page.getByLabel('Measurement: Diameter',{exact:true}).fill('5');await page.locator(`input[name="pass:${spec.characteristics[1].id}"][value="0"]`).check();await page.locator(`input[name="pass:${spec.characteristics[2].id}"][value="1"]`).check();await page.getByRole('button',{name:'Complete inspection',exact:true}).click();await page.waitForURL(/\/quality\/ncr\/[^/]+$/);
   const inspected=await db.qualityInspection.findFirstOrThrow({where:{organisationId:companies[0],controlPointId:point.id},include:{measurements:true,holds:true,nonConformances:true}});check(inspected.result==='FAIL'&&inspected.measurements.length===3&&inspected.measurements.find(item=>item.characteristicId===spec.characteristics[1].id)?.pass===false&&inspected.measurements.find(item=>item.characteristicId===spec.characteristics[2].id)?.pass===true&&inspected.holds[0].status==='ACTIVE'&&inspected.nonConformances[0].source==='INCOMING','Independent measurement/pass-fail answers create correct failed inspection, hold and incoming NCR');await page.goto(base+`/quality/checks/${inspected.id}`,{waitUntil:'domcontentloaded'});check((await page.locator('body').innerText()).includes('Diameter · 5 mm'),'Recorded inspection results are readable from history');
   const missing=await post('executeInspection',{controlPointId:manual.id,quantityInspected:'1'},workerCookie);check(missing.body.includes('Explicitly')&&await db.qualityInspection.count({where:{organisationId:companies[0],controlPointId:manual.id}})===0,'Empty manual inspection cannot silently pass or create partial records');
   await page.goto(base+`/quality/checks?controlPointId=${manual.id}`,{waitUntil:'domcontentloaded'});await page.getByLabel('Fail',{exact:true}).check();await page.getByRole('button',{name:'Complete inspection',exact:true}).click();await page.waitForURL(/\/quality\/ncr\/[^/]+$/);check(await db.qualityHold.count({where:{organisationId:companies[0],status:'ACTIVE'}})===2,'Manual failed check also places hold and opens issue');
   await page.goto(url,{waitUntil:'domcontentloaded'});await page.setViewportSize({width:390,height:844});check(await page.locator('main').evaluate(element=>element.scrollWidth<=element.clientWidth),'Issue workspace fits a phone viewport');check(errors===0,'Quality manager journey has no browser runtime errors');await page.screenshot({path:'/tmp/atlas-quality-workspace.png',fullPage:true});
   for(const [cookie,visible]of [[readerCookie,true],[foreignCookie,false]] as const){const other=await browser.newContext();await other.addCookies([{name:'atlas_session',value:cookie.slice(14),url:base,httpOnly:true,secure:true}]);const view=await other.newPage();await view.goto(url,{waitUntil:'domcontentloaded'});check((await view.locator('body').innerText()).includes('Synthetic quality issue')===visible&&await view.getByText('Edit issue and investigation',{exact:true}).count()===0,'Read-only and other-company issue access preserves boundaries');await other.close();}
   const denied=await post('updateNcrInvestigation',{ncrId:ncr.id,version:'10'},readerCookie),foreignDenied=await post('closeNcr',{ncrId:ncr.id,version:'10',closureEvidence:'Foreign closure attempt'},foreignCookie);check((/(?:^|\n)\w+:E\{/.test(denied.body)||denied.response.status>=400)&&(/(?:^|\n)\w+:E\{/.test(foreignDenied.body)||foreignDenied.response.status>=400),'Raw actions cannot bypass read-only or company access');
   const crossProduct=await post('reportNcr',{title:'Foreign product attempt',defect:'Not valid',source:'OTHER',severity:'MINOR',disposition:'PENDING',productId:outsideProduct.id},workerCookie);check(crossProduct.body.includes('product from this company')&&await db.nonConformance.count({where:{organisationId:companies[0],title:'Foreign product attempt'}})===0,'Cross-company product cannot be linked to an issue');
   check(await db.auditEntry.count({where:{organisationId:companies[0],entityId:ncr.id}})>=10,'Quality workflow retains central audit history');await context.close();console.log(`LIVE QUALITY ACCEPTANCE PASSED: ${checks} assertions`);
  }finally{await browser.close();}
 }finally{
  for(const id of companies)await db.organisation.update({where:{id},data:{status:'SUSPENDED'}});
  await db.membership.updateMany({where:{userId:{in:users}},data:{active:false,grantedCapabilities:[],sessionVersion:{increment:1}}});await db.user.updateMany({where:{id:{in:users}},data:{authVersion:{increment:1},passwordHash:await bcrypt.hash(randomBytes(32).toString('hex'),10)}});await db.$disconnect();console.log('Synthetic tenants suspended and credentials revoked; central history retained.');
 }
}
main().catch(error=>{console.error(error instanceof Error?error.message:'Acceptance failed');process.exitCode=1;});
