/** Central-server synthetic acceptance; all history retained and fixture access revoked. */
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import bcrypt from 'bcryptjs';
import {chromium,expect} from '@playwright/test';
import {db} from '../src/core/db/client';
import {executeReadQuery} from '../src/server/data-api/read-query';
import type {Session} from '../src/core/auth/session';
async function main(){
 assert(process.platform==='linux'&&process.env.ATLAS_HR_TEST==='1'&&process.env.ATLAS_RUNTIME!=='desktop','Explicit central-server acceptance only');
 const base='https://atlassystem.online',suffix=randomBytes(8).toString('hex'),password=randomBytes(24).toString('base64url'),companies:string[]=[],users:string[]=[];let assertions=0;
 const check=(value:unknown,label:string)=>{assert(value,label);assertions++;console.log('PASS '+label);};
 const manifest=JSON.parse(await readFile('.next/server/server-reference-manifest.json','utf8'));
 const post=async(name:string,args:unknown[],fields:Record<string,string>,cookie='')=>{const entries=Object.entries(manifest.node as Record<string,{exportedName?:string;workers?:Record<string,unknown>}>).filter(([,v])=>v.exportedName===name);const entry=entries.find(([,v])=>Object.keys(v.workers??{}).some(k=>k.includes('people/recruitment/page')))??entries[0];assert(entry,'Action '+name);const data=new FormData();for(const[k,v]of Object.entries(fields))data.set('_1_'+k,v);data.set('0',JSON.stringify([...args,'$K1']));const response=await fetch(base+(name==='loginAction'?'/login':'/people/recruitment'),{method:'POST',headers:{Origin:base,Accept:'text/x-component','Next-Action':entry[0],...(cookie?{Cookie:cookie}:{})},body:data,redirect:'manual'});return {response,body:await response.text()};};
 const login=async(email:string)=>{const r=await post('loginAction',[],{email,password});const cookie=r.response.headers.get('set-cookie')?.match(/atlas_session=[^;]+/)?.[0];assert(cookie,'Normal sign in');return cookie;};
 try{
 for(const side of ['inside','outside']){const org=await db.organisation.create({data:{name:'Synthetic HR '+side,slug:'hr-'+side+'-'+suffix,isTest:true}});companies.push(org.id);await db.moduleState.create({data:{organisationId:org.id,moduleId:'people',enabled:true,entitled:true}});}
 const org=companies[0],caps=['core.profile.self','people.employee.read','people.employee.manage','people.onboarding.manage','people.offboarding.manage','people.appraisal.read','people.appraisal.manage','people.one_to_one.read','people.one_to_one.manage','people.absence.read','people.absence.manage','people.expense.read','people.expense.approve','people.policy.read'];
 const makeUser=async(name:string,capabilities:string[],organisationId=org)=>{const user=await db.user.create({data:{name:'Synthetic '+name,email:'hr-'+name+'-'+suffix+'@example.test',passwordHash:await bcrypt.hash(password,10)}});users.push(user.id);await db.membership.create({data:{organisationId,userId:user.id,grantedCapabilities:capabilities}});return user;};
 const manager=await makeUser('manager',caps),reader=await makeUser('reader',['core.profile.self','people.employee.read']),staff=await makeUser('staff',['core.profile.self']),outside=await makeUser('outside',caps,companies[1]);const cookie=await login(manager.email),readerCookie=await login(reader.email),staffCookie=await login(staff.email),outsideCookie=await login(outside.email);
 const staffEmployee=await db.employee.create({data:{organisationId:org,userId:staff.id,employeeNumber:'HR-SELF',firstName:'Synthetic',lastName:'Learner',email:staff.email,jobTitle:'Operator',department:'Operations',startDate:new Date('2025-01-01'),status:'ACTIVE'}}),otherEmployee=await db.employee.create({data:{organisationId:org,employeeNumber:'HR-OTHER',firstName:'Private',lastName:'Colleague',email:'other-'+suffix+'@example.test',jobTitle:'Operator',startDate:new Date('2025-01-01'),status:'ACTIVE'}});
 const today=new Date().toISOString().slice(0,10),yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10),lastMonth=new Date(Date.now()-32*86400000).toISOString().slice(0,10),applicantEmail='applicant-'+suffix+'@example.test';
 const browser=await chromium.launch({args:['--no-sandbox']});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addCookies([{name:'atlas_session',value:cookie.slice(14),url:base,httpOnly:true,secure:true}]);const page=await context.newPage();let errors=0;page.on('pageerror',()=>errors++);
 await page.goto(base+'/people',{waitUntil:'domcontentloaded'});check(await page.getByRole('heading',{name:'HR home',exact:true}).count()===1,'HR opens on operational home');check((await page.locator('body').innerText()).includes('Training renewals')&&(await page.locator('body').innerText()).includes('Workforce reports'),'Home connects records, learning and reports');
 await page.goto(base+'/people/recruitment',{waitUntil:'domcontentloaded'});await page.locator('summary').filter({hasText:/^Create vacancy$/}).click();await page.getByLabel('Vacancy title',{exact:true}).fill('Synthetic operator vacancy');await page.getByLabel('Department',{exact:true}).fill('Operations');await page.getByLabel('Hiring owner',{exact:true}).selectOption(manager.id);await page.getByLabel('Role, requirements and hiring brief',{exact:true}).fill('Synthetic role with induction and qualification requirements');await page.getByRole('button',{name:'Create vacancy',exact:true}).click();await expect.poll(()=>db.hrVacancy.count({where:{organisationId:org,title:'Synthetic operator vacancy'}})).toBe(1);const vacancy=await db.hrVacancy.findFirstOrThrow({where:{organisationId:org,title:'Synthetic operator vacancy'}});check(vacancy.ownerUserId===manager.id&&vacancy.status==='OPEN','Create a real vacancy with company hiring owner');
 await page.goto(base+'/people/recruitment',{waitUntil:'domcontentloaded'});await page.locator('summary').filter({hasText:/^Add applicant$/}).click();await page.getByLabel('Vacancy',{exact:true}).selectOption(vacancy.id);await page.getByLabel('Applicant name',{exact:true}).fill('Synthetic Accepted Applicant');await page.getByLabel('Applicant email',{exact:true}).fill(applicantEmail);await page.getByLabel('Application source',{exact:true}).fill('Direct application');await page.getByLabel('Recruitment notes / decision reason',{exact:true}).fill('Initial application received');await page.getByRole('button',{name:'Add applicant',exact:true}).click();await page.waitForURL(/\/people\/recruitment\/[^/]+$/);let application=await db.hrApplication.findFirstOrThrow({where:{organisationId:org,email:applicantEmail}});check(application.stage==='APPLIED'&&application.vacancyId===vacancy.id,'Applicant links to canonical vacancy');
 const fields={vacancyId:vacancy.id,name:application.name,email:applicantEmail,stage:'INTERVIEW',version:String(application.version)};
 const noDate=await post('saveApplication',[application.id],fields,cookie);check(noDate.body.includes('interview date')&&(await db.hrApplication.findUniqueOrThrow({where:{id:application.id}})).stage==='APPLIED','Interview cannot be saved without an actual planned date');
 for(const stage of ['INTERVIEW','OFFER']){await page.goto(base+'/people/recruitment/'+application.id,{waitUntil:'domcontentloaded'});await page.getByLabel('Application stage',{exact:true}).selectOption(stage);await page.getByLabel('Interview date',{exact:true}).fill(today);await page.getByLabel('Recruitment notes / decision reason',{exact:true}).fill(stage==='INTERVIEW'?'Interview scheduled':'Offer accepted for onboarding');await page.getByRole('button',{name:'Save application',exact:true}).click();await expect.poll(async()=>(await db.hrApplication.findUniqueOrThrow({where:{id:application.id}})).stage).toBe(stage);check(true,'Applicant advances to '+stage);}
 await page.goto(base+'/people/directory',{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Add employee',exact:true}).click();await page.getByLabel('First name',{exact:true}).fill('Synthetic');await page.getByLabel('Last name',{exact:true}).fill('Accepted Applicant');await page.getByLabel('Email',{exact:true}).fill(applicantEmail);await page.getByLabel('Job title',{exact:true}).fill('Operator');await page.getByRole('dialog',{name:'Add employee',exact:true}).getByLabel('Department',{exact:true}).fill('Operations');await page.getByLabel('Start date',{exact:true}).fill(today);await page.getByRole('button',{name:'Add employee & start onboarding',exact:true}).click();await expect.poll(()=>db.employee.count({where:{organisationId:org,email:applicantEmail}})).toBe(1);const hired=await db.employee.findFirstOrThrow({where:{organisationId:org,email:applicantEmail}});check(hired.status==='ONBOARDING'&&await db.employeeTask.count({where:{organisationId:org,employeeId:hired.id,phase:'ONBOARDING'}})>0,'Existing employee creation starts real onboarding checklists');
 await page.goto(base+'/people/recruitment/'+application.id,{waitUntil:'domcontentloaded'});await page.getByLabel('Application stage',{exact:true}).selectOption('HIRED');await page.getByLabel('Onboarding employee (when recording Hired)',{exact:false}).selectOption(hired.id);await page.getByRole('button',{name:'Save application',exact:true}).click();await expect.poll(async()=>(await db.hrApplication.findUniqueOrThrow({where:{id:application.id}})).stage).toBe('HIRED');application=await db.hrApplication.findUniqueOrThrow({where:{id:application.id}});check(application.employeeId===hired.id&&await db.employee.count({where:{organisationId:org,email:applicantEmail}})===1,'Hire hands over to one canonical onboarding employee');await page.goto(base+'/people/recruitment/'+application.id,{waitUntil:'domcontentloaded'});check(await page.getByRole('link',{name:'Open onboarding employee',exact:false}).count()===1,'Closed application retains onboarding link and recruitment history');
 await page.goto(base+'/people/training',{waitUntil:'domcontentloaded'});await page.locator('summary').filter({hasText:/^Assign training or qualification$/}).click();await page.getByLabel('Employee',{exact:true}).selectOption(staffEmployee.id);await page.getByLabel('Course or qualification',{exact:true}).fill('Synthetic forklift learning');await page.getByLabel('Provider / awarding body',{exact:true}).fill('Synthetic provider');await page.getByLabel('Due date',{exact:true}).fill(yesterday);await page.getByLabel('Required for this employee',{exact:true}).check();await page.getByRole('button',{name:'Assign training',exact:true}).click();await expect.poll(()=>db.employeeTraining.count({where:{organisationId:org,title:'Synthetic forklift learning'}})).toBe(1);let training=await db.employeeTraining.findFirstOrThrow({where:{organisationId:org,title:'Synthetic forklift learning'}});check(training.employeeId===staffEmployee.id&&training.required,'Assign required learning against employee identity');
 await page.goto(base+'/people/training?view=overdue',{waitUntil:'domcontentloaded'});check((await page.locator('body').innerText()).includes('Synthetic forklift learning')&&(await page.locator('body').innerText()).includes('Overdue'),'Overdue filter finds the outstanding qualification');await page.locator('summary').filter({hasText:/^Update training record$/}).click();const recordForm=page.locator('article').filter({hasText:'Synthetic forklift learning'});await recordForm.getByLabel('Status',{exact:true}).selectOption('COMPLETED');await recordForm.getByLabel('Actual completion date',{exact:true}).fill(lastMonth);await recordForm.getByLabel('Expiry / renewal date',{exact:true}).fill(yesterday);await recordForm.getByLabel('Completion evidence and notes',{exact:true}).fill('Synthetic qualification reviewed by HR');await recordForm.getByRole('button',{name:'Save changes',exact:true}).click();await expect.poll(async()=>(await db.employeeTraining.findUniqueOrThrow({where:{id:training.id}})).status).toBe('COMPLETED');training=await db.employeeTraining.findUniqueOrThrow({where:{id:training.id}});check(training.completedOn!==null&&training.version===1,'Actual qualification completion and version saved centrally');await page.goto(base+'/people/training?view=renewal',{waitUntil:'domcontentloaded'});check((await page.locator('body').innerText()).includes('Synthetic forklift learning')&&(await page.locator('body').innerText()).includes('Expired'),'Completed expired qualification appears in renewal work');
 const trainingFields={employeeId:staffEmployee.id,title:'Synthetic stale overwrite',category:'Qualification',status:'PLANNED',version:'0'};const stale=await post('saveTraining',[training.id],trainingFields,cookie);check(stale.body.includes('another window')&&(await db.employeeTraining.findUniqueOrThrow({where:{id:training.id}})).title===training.title,'Stale training saves preserve newer evidence');
 await page.goto(base+'/people/documents',{waitUntil:'domcontentloaded'});await page.locator('summary').filter({hasText:/^Add employee document$/}).click();await page.getByLabel('Employee',{exact:true}).selectOption(staffEmployee.id);await page.getByLabel('Document title',{exact:true}).fill('Synthetic employment contract');await page.getByLabel('Issue date',{exact:true}).fill(lastMonth);await page.getByLabel('Expiry / renewal date',{exact:true}).fill(yesterday);await page.getByRole('button',{name:'Add document',exact:true}).click();await expect.poll(()=>db.employeeDocument.count({where:{organisationId:org,title:'Synthetic employment contract'}})).toBe(1);const document=await db.employeeDocument.findFirstOrThrow({where:{organisationId:org,title:'Synthetic employment contract'}});check(document.expiresOn!==null,'Employee document holds issue and expiry dates');await page.goto(base+'/people/documents?view=renewal',{waitUntil:'domcontentloaded'});check((await page.locator('body').innerText()).includes('Synthetic employment contract'),'Document expiry filter finds renewal work');await page.locator('summary').filter({hasText:/^Update document record$/}).click();const docForm=page.locator('article').filter({hasText:'Synthetic employment contract'});await docForm.getByLabel('Status',{exact:true}).selectOption('ARCHIVED');await docForm.getByRole('button',{name:'Save changes',exact:true}).click();await expect.poll(async()=>(await db.employeeDocument.findUniqueOrThrow({where:{id:document.id}})).status).toBe('ARCHIVED');await page.goto(base+'/people/documents?view=archived',{waitUntil:'domcontentloaded'});check((await page.locator('body').innerText()).includes('Synthetic employment contract'),'Archived documents remain readable history');
 await page.goto(base+'/people/reports',{waitUntil:'domcontentloaded'});check((await page.locator('body').innerText()).includes('2 employees')&&(await page.locator('body').innerText()).includes('Open vacancies'),'Reports count current workforce independently of onboarding');await page.goto(base+'/people/'+staffEmployee.id,{waitUntil:'domcontentloaded'});check(await page.getByRole('link',{name:'Training & qualifications',exact:false}).count()===1&&await page.getByRole('link',{name:'Document register & renewals',exact:false}).count()===1,'Employee record links learning and document renewals');
 await page.goto(base+'/people?status=ONBOARDING',{waitUntil:'domcontentloaded'});check(page.url().includes('/people/directory?status=ONBOARDING')&&(await page.locator('body').innerText()).includes('Accepted Applicant'),'Legacy filtered employee URLs retain their directory meaning');
 for(const path of ['/people','/people/recruitment','/people/training','/people/documents','/people/reports']){await page.setViewportSize({width:390,height:844});await page.goto(base+path,{waitUntil:'domcontentloaded'});check(await page.locator('main').evaluate(e=>e.scrollWidth<=e.clientWidth),'Phone layout fits '+path);if(path==='/people')await page.screenshot({path:'/tmp/atlas-hr-home.png',fullPage:true});}
 check(errors===0,'HR manager workflow has zero browser runtime errors');
 await db.employeeTraining.create({data:{organisationId:org,employeeId:otherEmployee.id,title:'Private colleague learning',category:'Training'}});
 const selfSession={organisationId:org,userId:staff.id,capabilities:new Set(['core.profile.self'])} as Session,readerSession={organisationId:org,userId:reader.id,capabilities:new Set(['core.profile.self','people.employee.read'])} as Session;
 const own=await executeReadQuery(selfSession,'employeeTraining','findMany',{}) as {title:string}[];check(own.length===1&&own[0].title===training.title,'Self-service data reads only the linked employee training');let applicantDenied=false;try{await executeReadQuery(readerSession,'hrApplication','findMany',{});}catch{applicantDenied=true;}check(applicantDenied,'Employee reader cannot query confidential applicants');
 for(const [otherCookie,foreign]of [[readerCookie,false],[outsideCookie,true]] as const){const result=await post('saveTraining',[training.id],{...trainingFields,version:'1'},otherCookie);check((result.response.status>=400||/\n\w+:E\{/.test(result.body)||result.body.includes('another window')||result.body.includes('company'))&&(await db.employeeTraining.findUniqueOrThrow({where:{id:training.id}})).title===training.title,foreign?'Foreign-company write denied':'Read-only write denied');}
 const staffContext=await browser.newContext();await staffContext.addCookies([{name:'atlas_session',value:staffCookie.slice(14),url:base,httpOnly:true,secure:true}]);const self=await staffContext.newPage();await self.goto(base+'/people/my-learning',{waitUntil:'domcontentloaded'});check((await self.locator('body').innerText()).includes(training.title)&&!(await self.locator('body').innerText()).includes('Private colleague learning'),'My learning displays own records without colleague training');await staffContext.close();
 const foreign=await fetch(base+'/people/recruitment/'+application.id,{headers:{Cookie:outsideCookie}});check(!(await foreign.text()).includes(applicantEmail),'Foreign company cannot read applicant details');
 const badEvidence=await post('saveTraining',[null],{...trainingFields,evidenceUrl:'javascript:alert(1)'},cookie);check(badEvidence.body.includes('HTTP')&&await db.employeeTraining.count({where:{organisationId:org,title:'Synthetic stale overwrite'}})===0,'Unsafe evidence links are rejected without writes');
 await db.moduleState.update({where:{organisationId_moduleId:{organisationId:org,moduleId:'people'}},data:{enabled:false}});const disabled=await post('saveTraining',[training.id],{...trainingFields,version:'1'},cookie);check((disabled.response.status>=400||/\n\w+:E\{/.test(disabled.body))&&(await executeReadQuery(selfSession,'employeeTraining','findMany',{}) as unknown[]).length===0,'Disabled HR rejects actions and hides source records');
 check(await db.auditEntry.count({where:{organisationId:org,action:'hr.application.hired',entityId:application.id}})===1&&await db.auditEntry.count({where:{organisationId:org,action:'hr.training.updated',entityId:training.id}})===1,'Hire and training audit retained centrally without false stale-write entries');await context.close();console.log(`LIVE HR PLATFORM PASSED: ${assertions} assertions`);
 }finally{await browser.close();}
 }finally{for(const id of companies)await db.organisation.update({where:{id},data:{status:'SUSPENDED'}});await db.membership.updateMany({where:{userId:{in:users}},data:{active:false,grantedCapabilities:[],sessionVersion:{increment:1}}});await db.user.updateMany({where:{id:{in:users}},data:{authVersion:{increment:1},passwordHash:await bcrypt.hash(randomBytes(32).toString('hex'),10)}});await db.$disconnect();console.log('Synthetic companies suspended, access and credentials revoked; central history retained.');}
}
main().catch(error=>{console.error(error instanceof Error?error.message:'Acceptance failed');process.exitCode=1;});
