/** Central-server synthetic acceptance; all history retained and fixture access revoked. */
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import bcrypt from 'bcryptjs';
import {chromium,expect} from '@playwright/test';
import {db} from '../src/core/db/client';
async function main(){
 assert(process.platform==='linux'&&process.env.ATLAS_SOP_USABILITY_TEST==='1'&&process.env.ATLAS_RUNTIME!=='desktop','Explicit central-server acceptance only');
 const base='https://atlassystem.online',suffix=randomBytes(8).toString('hex'),password=randomBytes(24).toString('base64url'),companies:string[]=[],users:string[]=[];let assertions=0;
 const check=(value:unknown,label:string)=>{assert(value,label);assertions++;console.log('PASS '+label);};
 const manifest=JSON.parse(await readFile('.next/server/server-reference-manifest.json','utf8'));
 const post=async(name:string,args:unknown[],fields:Record<string,string>,cookie='')=>{const entries=Object.entries(manifest.node as Record<string,{exportedName?:string;workers?:Record<string,unknown>}>).filter(([,v])=>v.exportedName===name);const entry=entries.find(([,v])=>Object.keys(v.workers??{}).some(k=>k.includes('sop/')))??entries[0];assert(entry,'Action '+name);const data=new FormData();for(const[k,v]of Object.entries(fields))data.set('_1_'+k,v);data.set('0',JSON.stringify([...args,'$K1']));const response=await fetch(base+(name==='loginAction'?'/login':name.includes('Plan')&&!name.includes('Sop')?'/plan':'/sop'),{method:'POST',headers:{Origin:base,Accept:'text/x-component','Next-Action':entry[0],...(cookie?{Cookie:cookie}:{})},body:data,redirect:'manual'});return {response,body:await response.text()};};
 const login=async(email:string)=>{const r=await post('loginAction',[],{email,password});const cookie=r.response.headers.get('set-cookie')?.match(/atlas_session=[^;]+/)?.[0];assert(cookie,'Normal sign in');return cookie;};
 try{
 for(const side of ['inside','outside']){const org=await db.organisation.create({data:{name:'Synthetic S&OP usability '+side,slug:'sop-use-'+side+'-'+suffix,isTest:true}});companies.push(org.id);await db.moduleState.createMany({data:['plan','sop','products','sales','crm','stock','logistics','manufacturing','planning'].map(moduleId=>({organisationId:org.id,moduleId,enabled:true,entitled:true}))});}
 const org=companies[0],caps=['core.profile.self','plan.read','plan.create','plan.edit','sop.read','sop.manage','sop.approve','sop.publish','sop.share','sales.order.read','sales.opportunity.read','customers.read','core.products.read','stock.read','logistics.shipment.read','manufacturing.order.read','manufacturing.plan.read','manufacturing.plan.manage','planning.read'];
 const makeUser=async(name:string,capabilities:string[],organisationId=org)=>{const user=await db.user.create({data:{name:'Synthetic '+name,email:'sop-use-'+name+'-'+suffix+'@example.test',passwordHash:await bcrypt.hash(password,10)}});users.push(user.id);await db.membership.create({data:{organisationId,userId:user.id,grantedCapabilities:capabilities}});return user;};
 const manager=await makeUser('manager',caps),reader=await makeUser('reader',['sop.read','plan.read']),outside=await makeUser('outside',caps,companies[1]);const cookie=await login(manager.email),readerCookie=await login(reader.email),outsideCookie=await login(outside.email);
 const first=new Date().toISOString().slice(0,7),next=new Date(first+'-01T00:00:00Z');next.setUTCMonth(next.getUTCMonth()+1);const second=next.toISOString().slice(0,7),end=new Date(first+'-01T00:00:00Z');end.setUTCFullYear(end.getUTCFullYear()+1);end.setUTCDate(0);
 const product=await db.product.create({data:{organisationId:org,code:'SOP-EASY',name:'Synthetic planning product',basePriceAmount:1000,baseCurrency:'GBP',unitOfMeasure:'each'}});
 await post('createPlan',[],{name:'Synthetic demand assumptions',type:'sales',mode:'custom',start:first+'-01',end:end.toISOString().slice(0,10),measuresChosen:'1',metric:'sales_volume'},cookie);const plan=await db.businessPlan.findFirstOrThrow({where:{organisationId:org,name:'Synthetic demand assumptions'}});
 for(const [period,value]of [[first,'100'],[second,'200']]){const current=await db.businessPlan.findUniqueOrThrow({where:{id:plan.id}});await post('savePlanInput',[],{planId:plan.id,revision:String(current.revision),metricKey:'sales_volume',value,label:'Synthetic future demand',note:'Reasoned synthetic monthly input',productId:product.id,period,unitPrice:'10'},cookie);}check(await db.planInput.count({where:{organisationId:org,planId:plan.id}})===2,'Central reasoned product demand inputs prepared');
 const browser=await chromium.launch({args:['--no-sandbox']});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addCookies([{name:'atlas_session',value:cookie.slice(14),url:base,httpOnly:true,secure:true}]);const page=await context.newPage();let errors=0;page.on('pageerror',error=>{errors++;console.log('Browser error: '+error.message);});
 await page.goto(base+'/sop',{waitUntil:'networkidle'});check(await page.getByRole('link',{name:'Create your first cycle →',exact:true}).count()===1,'New user has an explicit first action');await page.getByRole('link',{name:'Create your first cycle →',exact:true}).click();await page.getByLabel('Cycle name',{exact:true}).fill('Synthetic easy planning round');await page.getByLabel('First planning month',{exact:true}).fill(first);await page.getByLabel('Planning horizon',{exact:true}).selectOption('12');await page.getByRole('button',{name:'Create private cycle',exact:true}).click();await page.waitForURL(/view=setup/);let cycle=await db.sopCycle.findFirstOrThrow({where:{organisationId:org,name:'Synthetic easy planning round'}});check(await page.getByRole('heading',{name:'Set up the planning round',exact:true}).count()===1,'Cycle creation opens guided Setup');
 await page.getByLabel('Connect Synthetic demand assumptions',{exact:true}).check();await page.getByLabel('Product codes',{exact:true}).fill(product.code);check(await page.locator('details').filter({has:page.locator('summary').filter({hasText:/^Advanced forecast & service settings$/})}).getAttribute('open')===null,'Advanced controls start collapsed');await page.getByRole('button',{name:'Save planning setup',exact:true}).click();await expect.poll(async()=>(await db.sopCycle.findUniqueOrThrow({where:{id:cycle.id}})).revision).toBe(cycle.revision+1);cycle=await db.sopCycle.findUniqueOrThrow({where:{id:cycle.id}});await expect(page.getByText('Saved.',{exact:true})).toBeVisible();check(cycle.sourcePlanIds.includes(plan.id),'Selected plans save centrally');
 await page.getByRole('button',{name:'Generate working forecast',exact:true}).click();await page.waitForURL(url=>url.pathname==='/sop'&&url.searchParams.has('version')&&!url.searchParams.has('view'));const version=await db.sopVersion.findFirstOrThrow({where:{cycleId:cycle.id},orderBy:{createdAt:'desc'}});check(await page.getByRole('region',{name:'S&OP next steps',exact:true}).count()===1,'Generation returns to next-action home');const brief=page.getByRole('region',{name:'Monthly decision brief',exact:true});check((await brief.innerText()).includes('£1,000')&&(await brief.innerText()).includes('Not available'),'First month displays real demand revenue and honest missing targets/cost');await page.getByLabel('Planning month',{exact:true}).selectOption(second);check((await brief.innerText()).includes('£2,000'),'Monthly selector switches the meeting picture');check(await page.getByRole('button',{name:'Approve agreed forecast',exact:true}).count()===0,'New draft is not prematurely offered for approval');
 await page.goto(base+'/sop?cycle='+cycle.id+'&version='+version.id+'&view=demand',{waitUntil:'networkidle'});check(await page.getByRole('heading',{name:'What do we expect customers to buy?',exact:true}).count()===1,'Demand opens with a plain-language review question');await page.getByRole('link',{name:'Open checklist and record the review →',exact:true}).click();await expect(page.getByRole('heading',{name:'Review the plan together',exact:true})).toBeVisible();check(true,'Evidence links back to actual review checklist');
 const incomplete=await post('approveSopVersion',[],{cycleId:cycle.id,versionId:version.id},cookie);check((incomplete.response.status>=400||/(?:^|\n)\w+:E\{/.test(incomplete.body))&&(await db.sopVersion.findUniqueOrThrow({where:{id:version.id}})).status==='draft','Server refuses incomplete review approval');
 const names=['Data refresh','Product review','Demand review','Supply review','Financial review','Pre-S&OP','Executive review'];for(const [index,name]of names.entries()){const article=page.locator('article').filter({has:page.getByRole('heading',{name,exact:true})});await article.getByLabel(name+' owner',{exact:true}).fill('Synthetic planning owner');await article.getByRole('button',{name:'Record review complete',exact:true}).click();await expect.poll(async()=>{const c=await db.sopCycle.findUniqueOrThrow({where:{id:cycle.id}});return (c.workflow as unknown as {status:string}[])[index].status;}).toBe('approved');await expect(article.getByRole('button',{name:'Reopen review',exact:true})).toBeEnabled();}check(await page.getByRole('button',{name:'Approve agreed forecast',exact:true}).count()===1,'Seven exact-version reviews unlock explicit approval');await page.getByRole('button',{name:'Approve agreed forecast',exact:true}).click();await expect.poll(async()=>(await db.sopVersion.findUniqueOrThrow({where:{id:version.id}})).status).toBe('approved');check(await page.getByRole('button',{name:'Release approved demand to Manufacturing',exact:true}).count()===1,'Approval exposes a distinct release action');await page.getByRole('button',{name:'Release approved demand to Manufacturing',exact:true}).click();await expect.poll(async()=>(await db.sopVersion.findUniqueOrThrow({where:{id:version.id}})).status).toBe('published');const published=await db.manufacturingDemandForecast.findMany({where:{organisationId:org,sourceSopVersionId:version.id},orderBy:{periodStart:'asc'}});check(published.length===2&&published[0].periodStart.toISOString().startsWith(first)&&Number(published[0].quantity)===100&&published[1].periodStart.toISOString().startsWith(second)&&Number(published[1].quantity)===200,'Guided release publishes both populated months and exact canonical demand with lineage');
 await page.goto(base+'/sop?cycle='+cycle.id+'&view=decisions',{waitUntil:'networkidle'});await page.getByLabel('Actions title',{exact:true}).fill('Synthetic close supply gap');await page.getByLabel('Actions impact',{exact:true}).fill('Review dated supply and agree delivery commitments');await page.getByLabel('Actions owner',{exact:true}).fill('Operations');await page.getByRole('button',{name:'Add action',exact:true}).click();await expect.poll(async()=>{const c=await db.sopCycle.findUniqueOrThrow({where:{id:cycle.id}});return (c.actions as unknown[]).length;}).toBe(1);check(true,'Decision workspace creates an owned central follow-up');await page.getByRole('button',{name:'Mark completed',exact:true}).click();await expect.poll(async()=>{const c=await db.sopCycle.findUniqueOrThrow({where:{id:cycle.id}});return (c.actions as unknown as {status:string}[])[0].status;}).toBe('completed');check(true,'Follow-up can be completed without erasing its history');
 await page.goto(base+'/sop?cycle='+cycle.id+'&view=setup',{waitUntil:'networkidle'});await page.getByRole('button',{name:'Generate working forecast',exact:true}).click();await page.waitForURL(url=>url.searchParams.has('version')&&url.searchParams.get('version')!==version.id&&!url.searchParams.has('view'));const fresh=await db.sopVersion.findFirstOrThrow({where:{cycleId:cycle.id},orderBy:{createdAt:'desc'}});cycle=await db.sopCycle.findUniqueOrThrow({where:{id:cycle.id}});check(fresh.id!==version.id&&(cycle.workflow as unknown as {status:string;versionId:string}[]).every(s=>s.status==='open'&&s.versionId===fresh.id)&&(await db.sopVersion.findUniqueOrThrow({where:{id:version.id}})).status==='published','Refresh resets reviews for new immutable draft and preserves published history');
 await page.goto(base+'/sop?cycle='+cycle.id+'&version='+version.id+'&view=reviews',{waitUntil:'networkidle'});check(await page.getByRole('button',{name:'Record review complete',exact:true}).count()===0,'Older published version cannot reuse current review controls');
 for(const view of ['overview','setup','reviews','decisions','help']){await page.setViewportSize({width:390,height:844});await page.goto(base+'/sop?cycle='+cycle.id+'&version='+fresh.id+'&view='+view,{waitUntil:'networkidle'});check(await page.locator('main').evaluate(e=>e.scrollWidth<=e.clientWidth),'Phone view fits '+view);if(view==='overview')await page.screenshot({path:'/tmp/atlas-sop-guided.png',fullPage:true});}check(errors===0,'Guided manager journey has zero browser runtime errors');
 await db.sopCycle.update({where:{id:cycle.id},data:{companyVisible:true}});await db.businessPlan.update({where:{id:plan.id},data:{audience:'company'}});const readerContext=await browser.newContext();await readerContext.addCookies([{name:'atlas_session',value:readerCookie.slice(14),url:base,httpOnly:true,secure:true}]);const readPage=await readerContext.newPage();await readPage.goto(base+'/sop?cycle='+cycle.id+'&view=help',{waitUntil:'networkidle'});check(await readPage.getByRole('heading',{name:'A simple example',exact:true}).count()===1,'How-to remains available without forecast source permissions');await readPage.goto(base+'/sop?cycle='+cycle.id+'&view=overview',{waitUntil:'networkidle'});check((await readPage.locator('body').innerText()).includes('Ask for access to the forecast sources'),'Restricted snapshot has useful recovery guidance');await readerContext.close();const foreign=await fetch(base+'/sop?cycle='+cycle.id,{headers:{Cookie:outsideCookie}});check(!(await foreign.text()).includes('Synthetic easy planning round'),'Foreign-company planning data remains unavailable');
 await context.close();console.log(`LIVE S&OP USABILITY PASSED: ${assertions} assertions`);
 }finally{await browser.close();}
 }finally{for(const id of companies)await db.organisation.update({where:{id},data:{status:'SUSPENDED'}});await db.membership.updateMany({where:{userId:{in:users}},data:{active:false,grantedCapabilities:[],sessionVersion:{increment:1}}});await db.user.updateMany({where:{id:{in:users}},data:{authVersion:{increment:1},passwordHash:await bcrypt.hash(randomBytes(32).toString('hex'),10)}});await db.$disconnect();console.log('Synthetic companies suspended, credentials revoked; central history retained.');}
}
main().catch(error=>{console.error(error instanceof Error?error.message:'Acceptance failed');process.exitCode=1;});
