/** Central-server synthetic acceptance; all history retained and fixture access revoked. */
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import bcrypt from 'bcryptjs';
import {chromium,expect} from '@playwright/test';
import {db} from '../src/core/db/client';
async function main(){
 assert(process.platform==='linux'&&process.env.ATLAS_PROJECTS_TEST==='1'&&process.env.ATLAS_RUNTIME!=='desktop','Explicit central-server acceptance only');
 const base='https://atlassystem.online',suffix=randomBytes(8).toString('hex'),password=randomBytes(24).toString('base64url'),companies:string[]=[],users:string[]=[];let assertions=0;
 const check=(value:unknown,label:string)=>{assert(value,label);assertions++;console.log('PASS '+label);};
 const manifest=JSON.parse(await readFile('.next/server/server-reference-manifest.json','utf8'));
 const post=async(name:string,args:unknown[],fields:Record<string,string>,cookie='')=>{const entries=Object.entries(manifest.node as Record<string,{exportedName?:string;workers?:Record<string,unknown>}>).filter(([,v])=>v.exportedName===name);const entry=entries.find(([,v])=>Object.keys(v.workers??{}).some(k=>k.includes('projects/')))??entries[0];assert(entry,'Action '+name);const data=new FormData();for(const[k,v]of Object.entries(fields))data.set('_1_'+k,v);data.set('0',JSON.stringify([...args,'$K1']));const response=await fetch(base+(name==='loginAction'?'/login':'/projects'),{method:'POST',headers:{Origin:base,Accept:'text/x-component','Next-Action':entry[0],...(cookie?{Cookie:cookie}:{})},body:data,redirect:'manual'});return {response,body:await response.text()};};
 const login=async(email:string)=>{const r=await post('loginAction',[],{email,password});const cookie=r.response.headers.get('set-cookie')?.match(/atlas_session=[^;]+/)?.[0];assert(cookie,'Normal sign in');return cookie;};
 try{
 for(const side of ['inside','outside']){const org=await db.organisation.create({data:{name:'Synthetic Gantt '+side,slug:'gantt-'+side+'-'+suffix,isTest:true}});companies.push(org.id);await db.moduleState.create({data:{organisationId:org.id,moduleId:'projects',enabled:true,entitled:true}});}
 const org=companies[0],caps=['core.profile.self','projects.read','projects.manage'];
 const makeUser=async(name:string,capabilities:string[],organisationId=org)=>{const user=await db.user.create({data:{name:'Synthetic '+name,email:'gantt-'+name+'-'+suffix+'@example.test',passwordHash:await bcrypt.hash(password,10)}});users.push(user.id);await db.membership.create({data:{organisationId,userId:user.id,grantedCapabilities:capabilities}});return user;};
 const manager=await makeUser('manager',caps),reader=await makeUser('reader',['core.profile.self','projects.read']),viewer=await makeUser('viewer',caps),outside=await makeUser('outside',caps,companies[1]);
 const cookie=await login(manager.email),readerCookie=await login(reader.email),viewerCookie=await login(viewer.email),outsideCookie=await login(outside.email);
 const p=await db.project.create({data:{organisationId:org,name:'Synthetic Gantt launch',reference:'GANTT-'+suffix,visibility:'PRIVATE',ownerUserId:manager.id,startAt:new Date('2026-10-05'),targetAt:new Date('2026-10-20'),members:{create:[{organisationId:org,userId:reader.id,role:'VIEWER'},{organisationId:org,userId:viewer.id,role:'VIEWER'}]}}});
 const createTask=(title:string,startAt:string|null,dueAt:string|null)=>db.projectTask.create({data:{organisationId:org,projectId:p.id,title,description:'Preserve detailed acceptance notes',assigneeUserId:manager.id,creatorUserId:manager.id,visibility:'PROJECT',startAt:startAt?new Date(startAt):null,dueAt:dueAt?new Date(dueAt):null,estimatedMinutes:120}});
 const a=await createTask('Synthetic design','2026-10-05','2026-10-09'),b=await createTask('Synthetic build','2026-10-06','2026-10-10');await createTask('Synthetic unscheduled',null,null);
 await db.projectDependency.create({data:{organisationId:org,predecessorId:a.id,successorId:b.id,kind:'FINISH_TO_START',lagDays:1}});
 await db.projectMilestone.create({data:{organisationId:org,projectId:p.id,name:'Synthetic go live',targetAt:new Date('2026-10-20'),ownerUserId:manager.id}});
 const secret=await db.project.create({data:{organisationId:org,name:'Private hidden delivery',reference:'HIDDEN-'+suffix,visibility:'PRIVATE',ownerUserId:reader.id}});const hidden=await db.projectTask.create({data:{organisationId:org,projectId:secret.id,title:'Private hidden task',assigneeUserId:reader.id,creatorUserId:reader.id}});
 await db.projectBaseline.create({data:{organisationId:org,projectId:p.id,name:'Agreed plan',authorUserId:manager.id,snapshot:{tasks:[{id:a.id,startAt:'2026-10-05',dueAt:'2026-10-07'},{id:hidden.id,title:'Private hidden task',dueAt:'2026-10-08'}]}}});
 const browser=await chromium.launch({args:['--no-sandbox']});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addCookies([{name:'atlas_session',value:cookie.slice(14),url:base,httpOnly:true,secure:true}]);const page=await context.newPage();let errors=0;page.on('pageerror',()=>errors++);
 const path='/projects/'+p.id+'?tab=Plan';await page.goto(base+path,{waitUntil:'domcontentloaded'});await expect(page.getByRole('region',{name:'Project Gantt',exact:true})).toBeVisible();
 check(await page.getByLabel('Gantt zoom').count()===1,'Live Gantt opens with zoom and navigation');check((await page.locator('body').innerText()).includes('Synthetic go live'),'Milestone is part of the project plan');await page.locator('summary').filter({hasText:/^Baseline comparison/}).click();check((await page.locator('body').innerText()).includes('+2d'),'Baseline finish variance is readable');check(await page.getByLabel('Task dependency connectors').locator('path[marker-end]').count()===1,'Dependency connector renders');check((await page.locator('body').innerText()).includes('Review 1 dependency conflicts'),'Conflicting dates have an explanation');check(!(await page.locator('body').innerText()).includes('Private hidden task'),'Baseline does not expose hidden historical scope');
 await page.getByLabel('Gantt zoom').selectOption('Days');await page.getByRole('button',{name:'Today',exact:true}).click();check(await page.getByLabel('Today marker').count()===1,'Today marker and day zoom work');await page.getByRole('button',{name:'Whole plan',exact:true}).click();check(await page.getByLabel('Gantt zoom').inputValue()==='Months','Whole plan selects annual overview');
 await page.getByRole('button',{name:'Schedule Synthetic design',exact:true}).click();await page.getByLabel('Task start',{exact:true}).fill('2026-10-07');await page.getByLabel('Task finish',{exact:true}).fill('2026-10-12');await page.getByRole('button',{name:'Save task dates',exact:true}).click();await expect.poll(async()=>(await db.projectTask.findUniqueOrThrow({where:{id:a.id}})).version).toBe(2);
 const changed=await db.projectTask.findUniqueOrThrow({where:{id:a.id}});check(changed.startAt?.toISOString().slice(0,10)==='2026-10-07'&&changed.dueAt?.toISOString().slice(0,10)==='2026-10-12','Gantt dates save to the canonical central task');check(changed.description===a.description&&changed.assigneeUserId===a.assigneeUserId,'Date edit preserves task detail and ownership');check((await db.projectTask.findUniqueOrThrow({where:{id:b.id}})).version===1,'Successor is not silently rescheduled');
 await page.reload({waitUntil:'domcontentloaded'});await page.locator('summary').filter({hasText:/^Baseline comparison/}).click();check((await page.locator('body').innerText()).includes('+5d'),'Reloaded Gantt compares the saved dates to immutable baseline');
 await page.getByLabel('Find task or owner').fill('unscheduled');check(await page.getByRole('button',{name:/Synthetic unscheduled/}).count()===1&&await page.getByRole('button',{name:'Schedule Synthetic design',exact:true}).count()===0,'Task search includes unscheduled work');await page.getByLabel('Find task or owner').fill('');
 await page.setViewportSize({width:390,height:844});check(await page.locator('main').evaluate(e=>e.scrollWidth<=e.clientWidth),'Phone layout keeps chart scrolling inside its panel');await page.screenshot({path:'/tmp/atlas-projects-gantt.png',fullPage:true});check(errors===0,'Gantt manager journey has zero browser runtime errors');
 await post('rescheduleTask',[b.id],{startAt:'2026-10-06',dueAt:'2026-10-10',version:'1'},cookie);check((await db.projectTask.findUniqueOrThrow({where:{id:b.id}})).version===2,'Direct action protocol succeeds for an authorized current version');
 const fields={startAt:'2026-10-07',dueAt:'2026-10-13',version:'1'};await post('rescheduleTask',[a.id],fields,cookie);check((await db.projectTask.findUniqueOrThrow({where:{id:a.id}})).version===2,'Stale edit cannot overwrite newer dates');
 for(const [c,label]of [[readerCookie,'Read-only capability'],[viewerCookie,'Viewer project role'],[outsideCookie,'Foreign company']] as const){await post('rescheduleTask',[a.id],{...fields,version:'2'},c);check((await db.projectTask.findUniqueOrThrow({where:{id:a.id}})).version===2,label+' cannot change task dates');}
 for(const dates of [{startAt:'2026-10-14',dueAt:'2026-10-13'},{startAt:'2026-02-29',dueAt:'2026-10-13'}]){await post('rescheduleTask',[a.id],{...dates,version:'2'},cookie);check((await db.projectTask.findUniqueOrThrow({where:{id:a.id}})).version===2,'Invalid date range or date refused');}
 await db.project.update({where:{id:p.id},data:{archivedAt:new Date()}});await post('rescheduleTask',[a.id],{...fields,version:'2'},cookie);check((await db.projectTask.findUniqueOrThrow({where:{id:a.id}})).version===2,'Archived project cannot be rescheduled');await page.reload({waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Schedule Synthetic design',exact:true}).click();check(await page.getByRole('button',{name:'Save task dates',exact:true}).count()===0,'Archived Gantt removes date editing controls');
 await db.moduleState.update({where:{organisationId_moduleId:{organisationId:org,moduleId:'projects'}},data:{enabled:false}});await post('rescheduleTask',[a.id],{...fields,version:'2'},cookie);check((await db.projectTask.findUniqueOrThrow({where:{id:a.id}})).version===2,'Disabled module cannot reschedule tasks');
 check(await db.auditEntry.count({where:{organisationId:org,entityId:a.id,action:'TaskRescheduled'}})===1,'Exactly one successful edit is audited; rejected edits produce none');await context.close();console.log(`LIVE PROJECTS GANTT PASSED: ${assertions} assertions`);
 }finally{await browser.close();}
 }finally{for(const id of companies)await db.organisation.update({where:{id},data:{status:'SUSPENDED'}});await db.membership.updateMany({where:{userId:{in:users}},data:{active:false,grantedCapabilities:[],sessionVersion:{increment:1}}});await db.user.updateMany({where:{id:{in:users}},data:{authVersion:{increment:1},passwordHash:await bcrypt.hash(randomBytes(32).toString('hex'),10)}});await db.$disconnect();console.log('Synthetic companies suspended, credentials revoked; central history retained.');}
}
main().catch(error=>{console.error(error instanceof Error?error.message:'Acceptance failed');process.exitCode=1;});
