/** Server-only synthetic acceptance. Central records/audit retained; fixture access revoked. */
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import bcrypt from 'bcryptjs';
import {chromium} from '@playwright/test';
import {db} from '../src/core/db/client';
async function main(){
 assert(process.platform==='linux'&&process.env.ATLAS_GOALS_TEST==='1'&&process.env.ATLAS_RUNTIME!=='desktop','Explicit central-server test required');
 const base='https://atlassystem.online',suffix=randomBytes(8).toString('hex'),password=randomBytes(24).toString('base64url'),companies:string[]=[],users:string[]=[];let assertions=0;
 const check=(condition:unknown,label:string)=>{assert(condition,label);assertions++;console.log(`PASS ${label}`);};
 const manifest=JSON.parse(await readFile('.next/server/server-reference-manifest.json','utf8'));
 const post=async(name:string,args:unknown[],fields:Record<string,string>,cookie='')=>{const candidates=Object.entries(manifest.node as Record<string,{exportedName?:string;workers?:Record<string,unknown>}>).filter(([,v])=>v.exportedName===name);const action=candidates.find(([,v])=>Object.keys(v.workers??{}).some(k=>k.includes('kpis/new')))??candidates[0];assert(action,`Action ${name}`);const body=new FormData();for(const [key,value]of Object.entries(fields))body.set(`_1_${key}`,value);body.set('0',JSON.stringify([...args,'$K1']));const response=await fetch(base+(name==='loginAction'?'/login':'/kpis/new'),{method:'POST',headers:{Origin:base,'Next-Action':action[0],Accept:'text/x-component',...(cookie?{Cookie:cookie}:{})},body,redirect:'manual'});return {response,body:await response.text()};};
 const login=async(email:string)=>{const r=await post('loginAction',[],{email,password});const cookie=r.response.headers.get('set-cookie')?.match(/atlas_session=[^;]+/)?.[0];assert(cookie,'Normal sign-in');return cookie;};
 try{
  for(const side of ['inside','outside']){const org=await db.organisation.create({data:{name:`Synthetic goals ${side}`,slug:`goals-${side}-${suffix}`,isTest:true}});companies.push(org.id);for(const moduleId of ['kpis','sales','finance','csat','service','manufacturing','logistics','products','stock','analytics'])await db.moduleState.create({data:{organisationId:org.id,moduleId,enabled:true,entitled:true}});}
  const org=companies[0],caps=['core.profile.self','kpis.read','kpis.manage','sales.order.read','finance.ledger.read','csat.result.read','service.case.read','service.ticket.read','manufacturing.order.read','logistics.shipment.read','analytics.dashboard.read','analytics.dashboard.manage'];
  const makeUser=async(name:string,grants:string[],organisationId=org)=>{const user=await db.user.create({data:{name:`Synthetic ${name}`,email:`goals-${name}-${suffix}@example.test`,passwordHash:await bcrypt.hash(password,10)}});users.push(user.id);await db.membership.create({data:{organisationId,userId:user.id,grantedCapabilities:grants}});return user;};
  const manager=await makeUser('manager',caps),reader=await makeUser('reader',['core.profile.self','kpis.read']),outside=await makeUser('outside',caps,companies[1]);const cookie=await login(manager.email),readerCookie=await login(reader.email),outsideCookie=await login(outside.email);
  const party=await db.party.create({data:{organisationId:org,kind:'COMPANY',name:'Synthetic customer',customerCode:'TEST'}}),product=await db.product.create({data:{organisationId:org,code:'TEST',name:'Synthetic part',basePriceAmount:0}});
  const inside=new Date('2026-08-15T12:00Z'),last=new Date('2026-08-31T23:59:59.900Z'),after=new Date('2026-09-01T00:00Z');
  for(const [reference,confirmationDate,netAmount,commercialStatus,currency]of [['S1',inside,10000,'CONFIRMED','GBP'],['S2',last,5000,'CLOSED','GBP'],['CANCEL',inside,90000,'CANCELLED','GBP'],['AFTER',after,990000,'CONFIRMED','GBP'],['EUR',inside,7000,'CONFIRMED','EUR']] as const)await db.salesOrder.create({data:{organisationId:org,partyId:party.id,ownerUserId:manager.id,reference,orderDate:confirmationDate,confirmationDate,netAmount,commercialStatus,currency}});
  const entity=await db.financeEntity.create({data:{organisationId:org,name:'Synthetic books',code:'TEST',currency:'GBP'}}),period=await db.financePeriod.create({data:{organisationId:org,entityId:entity.id,name:'Synthetic year',startAt:new Date('2026-01-01'),endAt:new Date('2026-12-31T23:59:59.999Z')}});
  const accounts=await Promise.all([['REV','REVENUE'],['EXP','EXPENSE'],['BANK','ASSET']].map(([code,type])=>db.financeAccount.create({data:{organisationId:org,entityId:entity.id,code,name:`Synthetic ${code}`,type}})));
  const journal=async(reference:string,date:Date,rev:bigint,expense:bigint,posted=true)=>{const lines=[{accountId:accounts[0].id,description:'Synthetic revenue',debit:0n,credit:rev},{accountId:accounts[1].id,description:'Synthetic expense',debit:expense,credit:0n},{accountId:accounts[2].id,description:'Synthetic balance',debit:rev-expense,credit:0n}];const j=await db.financeJournal.create({data:{organisationId:org,entityId:entity.id,periodId:period.id,reference,description:'Synthetic goal acceptance',sourceKey:`goals:${reference}`,sourceType:'MANUAL',accountingDate:date,currency:'GBP',exchangeRate:1,creatorUserId:manager.id,lines:{create:lines.map(l=>({...l,organisationId:org,transactionDebit:l.debit,transactionCredit:l.credit}))}}});if(posted)await db.financeJournal.update({where:{id:j.id},data:{status:'POSTED',postedAt:inside}});};
  await journal('POSTED',inside,100000n,40000n);await journal('LATE',after,900000n,0n);await journal('DRAFT',inside,800000n,0n,false);
  const visible=await db.serviceCase.create({data:{organisationId:org,partyId:party.id,number:'CS-TEST',subject:'Synthetic resolved case',ownerUserId:manager.id,createdByUserId:manager.id,status:'RESOLVED',resolvedAt:inside}}),restricted=await db.serviceCase.create({data:{organisationId:org,partyId:party.id,number:'CS-PRIVATE',subject:'Synthetic restricted case',ownerUserId:manager.id,createdByUserId:manager.id,security:'RESTRICTED',status:'RESOLVED',resolvedAt:inside}});
  const survey=await db.csatSurvey.create({data:{organisationId:org,name:'Synthetic support',question:'Synthetic?',scale:5,createdBy:manager.id,context:'SUPPORT'}});
  for(const [score,respondedAt,entityId,invalidatedAt]of [[5,inside,visible.id,null],[3,last,visible.id,null],[5,inside,restricted.id,null],[5,inside,visible.id,inside],[5,after,visible.id,null]] as const)await db.csatResponse.create({data:{organisationId:org,surveyId:survey.id,token:randomBytes(24).toString('hex'),entityType:'ServiceCase',entityId,score,respondedAt,invalidatedAt}});
  for(const [orderNumber,actualFinish,requiredDate]of [['P1',inside,new Date('2026-08-15')],['P2',last,new Date('2026-08-30')],['AFTER',after,new Date('2026-09-02')]] as const)await db.manufacturingOrder.create({data:{organisationId:org,productId:product.id,orderNumber,quantity:10,status:'COMPLETE',actualFinish,requiredDate,createdByUserId:manager.id}});
  await db.shipment.create({data:{organisationId:org,partyId:party.id,reference:'SHIP-TEST',shipTo:{},status:'DISPATCHED',dispatchedAt:inside}});
  const browser=await chromium.launch({args:['--no-sandbox']});try{
   const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addCookies([{name:'atlas_session',value:cookie.slice(14),url:base,httpOnly:true,secure:true}]);const page=await context.newPage();let errors=0;page.on('pageerror',()=>errors++);
   await page.goto(base+'/kpis',{waitUntil:'domcontentloaded'});await page.getByText('Connect a business result',{exact:true}).waitFor();check(await page.getByRole('heading',{name:'Posted profit',exact:true}).count()===1&&await page.getByRole('heading',{name:'Customer service CSAT',exact:true}).count()===1,'Available source results are discoverable from scorecards');
   const create=async(metricId:string,name:string,target:string,currency='')=>{await page.goto(base+`/kpis/new?metric=${metricId}`,{waitUntil:'domcontentloaded'});check(await page.getByLabel('Live measure',{exact:true}).inputValue()===metricId,`Suggested ${metricId} preselects its actual source`);await page.getByLabel('Goal',{exact:true}).fill(name);await page.getByLabel('Target',{exact:true}).fill(target);await page.getByLabel('Starts',{exact:true}).fill('2026-08-01');await page.getByLabel('Ends',{exact:true}).fill('2026-08-31');if(currency)await page.getByLabel('Currency',{exact:true}).fill(currency);await page.getByRole('button',{name:'Set the goal',exact:true}).click();await page.waitForURL(/\/kpis\/(?!new)[^/]+$/);return db.kpi.findFirstOrThrow({where:{organisationId:org,name}});};
   const sales=await create('sales.confirmed.value','Synthetic sales intake','200','GBP');check((await page.locator('body').innerText()).includes('£150.00'),'Sales value includes last-day confirmation but excludes cancellation, other currency and next period');
   const profit=await create('finance.posted.profit','Synthetic profit','1000','GBP');check((await page.locator('body').innerText()).includes('£600.00'),'Posted profit equals revenue less expenses; draft and out-of-period journals excluded');
   const csat=await create('csat.service.satisfaction','Synthetic service CSAT','90');check((await page.locator('body').innerText()).includes('50%')&&(await page.locator('body').innerText()).includes('Based on 2 source records'),'Service CSAT is 50% from accessible valid responses, excluding restricted, invalidated and later answers');
   const production=await create('manufacturing.on_time','Synthetic production reliability','95');check((await page.locator('body').innerText()).includes('50%'),'On-time production uses actual completed orders and required dates');
   const resolved=await create('service.resolved','Synthetic case resolution','5');check((await page.locator('body').innerText()).includes('Based on 1 source records'),'Resolved-case goal preserves restricted case boundaries');
   await create('logistics.dispatched','Synthetic dispatch','5');check((await page.locator('body').innerText()).includes('Based on 1 source records'),'Dispatch target reads actual shipment records');
   const manual=await db.kpi.create({data:{organisationId:org,name:'Synthetic existing target',teamName:'Sales',ownerUserId:manager.id,unit:'count',target:10,current:7,startsAt:new Date('2026-08-01'),endsAt:new Date('2026-08-31'),visibility:'COMPANY',updates:{create:{value:7,note:'Historical manual update',actorUserId:manager.id}}}});
   await page.goto(base+`/kpis/${manual.id}`,{waitUntil:'domcontentloaded'});await page.getByText('Connect this goal to live results',{exact:true}).click();await page.getByLabel('Connect live source',{exact:true}).selectOption('sales.confirmed.value');await page.getByLabel('Connection currency',{exact:true}).fill('GBP');await page.getByLabel('Connection target',{exact:true}).fill('200');await page.getByRole('button',{name:'Connect source',exact:true}).click();await page.getByRole('heading',{name:'Live measure',exact:true}).waitFor();const connected=await db.kpi.findUniqueOrThrow({where:{id:manual.id},include:{updates:true}});check(connected.metricId==='sales.confirmed.value'&&connected.target===20000&&connected.updates.length===1&&connected.updates[0].note==='Historical manual update','Existing manual goal connects without losing identity or history');
   for(const [path,name]of [['/sales/documents','Synthetic sales intake'],['/finance/ledger','Synthetic profit'],['/csat','Synthetic service CSAT'],['/manufacturing','Synthetic production reliability'],['/service','Synthetic case resolution']] as const){await page.goto(base+path,{waitUntil:'domcontentloaded'});check(await page.getByText(name,{exact:true}).count()>=1,`Source app ${path} shows its connected goal`);}
   await db.dashboard.create({data:{organisationId:org,userId:manager.id,name:'Analytics · Synthetic goals',widgets:[JSON.stringify({kind:'atlas-board',refreshSeconds:30}),JSON.stringify({id:'profit-widget',metricId:'finance.posted.profit',title:'Synthetic posted profit',visual:'kpi',span:6})]}});
   await page.goto(base+'/analytics?period=30',{waitUntil:'domcontentloaded'});check((await page.locator('body').innerText()).includes('Synthetic profit')&&(await page.locator('body').innerText()).includes('£600.00'),'Dashboard goal uses its own dates despite a different chart period');
   await page.goto(base+`/kpis/${csat.id}`,{waitUntil:'domcontentloaded'});await page.setViewportSize({width:390,height:844});check(await page.locator('main').evaluate(e=>e.scrollWidth<=e.clientWidth),'Connected goal fits a phone viewport');await page.screenshot({path:'/tmp/atlas-connected-goals.png',fullPage:true});check(errors===0,'Manager journey has zero browser runtime errors');
   await db.kpiUpdate.create({data:{kpiId:profit.id,value:987654,note:'Synthetic captured reading',actorUserId:manager.id}});
   for(const [otherCookie,foreign]of [[readerCookie,false],[outsideCookie,true]] as const){const other=await browser.newContext();await other.addCookies([{name:'atlas_session',value:otherCookie.slice(14),url:base,httpOnly:true,secure:true}]);const view=await other.newPage();await view.goto(base+`/kpis/${profit.id}`,{waitUntil:'domcontentloaded'});const text=await view.locator('body').innerText();check(foreign?!text.includes('Synthetic profit'):text.includes('Source access is required')&&!text.includes('£600.00')&&!text.includes('9,876.54'),'Goal and captured actuals preserve source/company access');await other.close();}
   const signature=JSON.stringify([sales.metricId,sales.sliceLabel,sales.target,sales.unit]);const denied=await post('connectGoal',[sales.id],{expectedConnection:signature,metricId:'sales.confirmed.value',sliceLabel:'GBP',target:'999'},readerCookie),foreign=await post('connectGoal',[sales.id],{expectedConnection:signature,metricId:'sales.confirmed.value',sliceLabel:'GBP',target:'999'},outsideCookie);check((denied.response.status>=400||/\n\w+:E\{/.test(denied.body))&&(foreign.response.status>=400||/\n\w+:E\{/.test(foreign.body))&&(await db.kpi.findUniqueOrThrow({where:{id:sales.id}})).target===sales.target,'Direct read-only/foreign connections reject without changes');
   const stale=await post('connectGoal',[manual.id],{expectedConnection:JSON.stringify(['','',10,'count']),metricId:'finance.posted.profit',sliceLabel:'GBP',target:'999'},cookie);check(stale.body.includes('another window')&&(await db.kpi.findUniqueOrThrow({where:{id:manual.id}})).metricId==='sales.confirmed.value','Stale source changes cannot overwrite the newer connection');
   await db.moduleState.update({where:{organisationId_moduleId:{organisationId:org,moduleId:'finance'}},data:{enabled:false}});await page.goto(base+`/kpis/${profit.id}`,{waitUntil:'domcontentloaded'});check((await page.locator('body').innerText()).includes('Source access is required')&&!(await page.locator('body').innerText()).includes('£600.00'),'Disabling a source removes its reading and never falls back to stored progress');
   check(await db.auditEntry.count({where:{organisationId:org,entityId:manual.id,action:'kpi.source.connected'}})===1,'Connection audit retained centrally');await context.close();console.log(`LIVE CONNECTED GOALS PASSED: ${assertions} assertions`);
  }finally{await browser.close();}
 }finally{
  for(const id of companies)await db.organisation.update({where:{id},data:{status:'SUSPENDED'}});
  await db.membership.updateMany({where:{userId:{in:users}},data:{active:false,grantedCapabilities:[],sessionVersion:{increment:1}}});await db.user.updateMany({where:{id:{in:users}},data:{authVersion:{increment:1},passwordHash:await bcrypt.hash(randomBytes(32).toString('hex'),10)}});await db.$disconnect();console.log('Synthetic companies suspended and fixture credentials revoked; central history retained.');
 }
}
main().catch(error=>{console.error(error instanceof Error?error.message:'Acceptance failed');process.exitCode=1;});
