import Link from "next/link";
import { requireSession } from "@/core/auth/session";
import { assertCapability } from "@/core/permissions/check";
import { getFinanceJournalDetail } from "@/modules/finance/services/reporting";
import { approveManualJournal, reverseJournal } from "@/modules/finance/services/commands";
import { money } from "@/modules/finance/domain/money";
import { ActionForm } from "@/modules/finance/components/action-form";
import { FinanceWorkspace, financeField as field, financeSection as section } from "@/modules/finance/components/workspace";

export default async function Journal({ params }: { params: Promise<{ id: string }> }) {
  const session = await requireSession();
  assertCapability(session, "finance.ledger.read");
  const { id } = await params, { journal, reversal, original, audit } = await getFinanceJournalDetail(id);
  return <FinanceWorkspace title={journal.reference} description={journal.description}>
    <div className="grid gap-4 text-sm sm:grid-cols-4">{[{ title: "Legal entity", value: journal.entity.name }, { title: "Accounting date", value: journal.accountingDate.toISOString().slice(0, 10) }, { title: "Document / tax date", value: `${journal.documentDate?.toISOString().slice(0, 10) ?? "Legacy: not retained"} / ${journal.taxDate?.toISOString().slice(0, 10) ?? "Legacy: not retained"}` }, { title: "Currency / retained rate", value: `${journal.currency} → ${journal.entity.currency} · ${journal.exchangeRate?.toString() ?? "Legacy: not retained"}` }, { title: "Period", value: `${journal.period.name} · ${journal.period.state}` }, { title: "Status", value: journal.status }].map(item => <div key={item.title}><p className="text-xs text-slate-500">{item.title}</p><p className="mt-1 font-medium">{item.value}</p></div>)}</div>
    <section className={section}><h2 className="text-lg font-semibold">Why this entry exists</h2><p className="text-sm">Source: {journal.sourceType} · {journal.sourceId ?? "Manual journal"}</p><p className="text-xs text-slate-500">Posting key: {journal.sourceKey}</p><div className="flex flex-wrap gap-5 text-sm">{journal.documents.map(doc => <span key={doc.id}><Link className="text-blue-700" href={`/finance/documents/${doc.id}`}>{doc.reference} · {doc.kind}</Link>{doc.salesOrderId && session.capabilities.has("sales.order.read") && <Link className="ml-3 text-blue-700" href={`/sales/orders/${doc.salesOrderId}`}>Sales order →</Link>}</span>)}{journal.sourceType === "BANK" && session.capabilities.has("finance.bank.read") && <Link className="text-blue-700" href={`/finance/reconcile?entity=${journal.entityId}&status=RECONCILED`}>Bank transaction and settlements →</Link>}{original && <Link className="text-blue-700" href={`/finance/journals/${original.id}`}>Reverses {original.reference}</Link>}{reversal && <Link className="text-blue-700" href={`/finance/journals/${reversal.id}`}>Reversed by {reversal.reference}</Link>}</div></section>
    <section className={section}><h2 className="text-lg font-semibold">Accounting distribution</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs text-slate-500"><th className="py-3">Account / explanation</th><th>Dimensions</th><th className="text-right">Transaction debit</th><th className="text-right">Transaction credit</th><th className="text-right">Base debit</th><th className="text-right">Base credit</th></tr></thead><tbody>{journal.lines.map(line => <tr className="border-b border-slate-100" key={line.id}><td className="py-3 pr-4"><Link className="text-blue-700" href={`/finance/ledger?entity=${journal.entityId}&account=${line.accountId}`}>{line.account.code} · {line.account.name}</Link><p className="text-xs text-slate-500">{line.description}</p>{line.taxCode && <p className="text-xs text-slate-500">Tax: {line.taxCode}</p>}</td><td className="pr-4 text-xs text-slate-500">{[line.department, line.costCentre, line.site, line.projectId].filter(Boolean).join(" · ") || "—"}</td><td className="text-right tabular-nums">{money(line.transactionDebit, journal.currency)}</td><td className="text-right tabular-nums">{money(line.transactionCredit, journal.currency)}</td><td className="text-right tabular-nums">{money(line.debit, journal.entity.currency)}</td><td className="text-right tabular-nums">{money(line.credit, journal.entity.currency)}</td></tr>)}</tbody><tfoot><tr className="border-t border-slate-300 font-semibold"><td className="py-3" colSpan={4}>Base currency totals</td><td className="text-right">{money(journal.lines.reduce((sum, line) => sum + line.debit, 0n), journal.entity.currency)}</td><td className="text-right">{money(journal.lines.reduce((sum, line) => sum + line.credit, 0n), journal.entity.currency)}</td></tr></tfoot></table></div></section>
    {journal.sourceType === "MANUAL" && session.capabilities.has("finance.journal.post") && (journal.status === "DRAFT" ? <ActionForm action={approveManualJournal.bind(null, id)} label="Approve and post"><input name="reason" className={field} minLength={5} required placeholder="Independent accounting review"/></ActionForm> : !reversal && <details className={section}><summary className="cursor-pointer font-medium">Correct by posting a reversal</summary><ActionForm className="mt-4" action={reverseJournal.bind(null, id)} label="Post linked reversal"><input name="date" type="date" className={field} required/><input name="reason" className={field} minLength={5} required placeholder="Reason for correction"/><p className="text-xs text-slate-500">Retains the original and all dimensions. The reversal must fall in a permitted period.</p></ActionForm></details>)}
    <section className={section}><h2 className="text-lg font-semibold">Audit history</h2><ul className="space-y-2 text-xs text-slate-500">{audit.map((event, index) => <li key={index}>{event.createdAt.toISOString()} · {event.action} · {event.actorUserId}</li>)}</ul></section>
  </FinanceWorkspace>;
}
