import type { Session } from "@/core/auth/session";

export const CONSOLE_ROLES = ["all", "planner", "buyer", "production", "finance"] as const;
export type ConsoleRole = typeof CONSOLE_ROLES[number];
export type ConsoleDestination = { id: string; label: string; description: string; href: string; module: string; requiredModules?: string[]; capabilities: string[]; stage: "Demand" | "Materials" | "Schedule" | "Production" | "Products & plant" | "Finance & procurement"; roles: ConsoleRole[] };
export const CONSOLE_DESTINATIONS: ConsoleDestination[] = [
  { id: "demand", label: "Customer demand", description: "Confirmed orders, stock cover and dated requirements.", href: "/planning", module: "planning", requiredModules: ["stock", "sales"], capabilities: ["planning.demand.read", "stock.read", "sales.order.read"], stage: "Demand", roles: ["planner"] },
  { id: "targets", label: "Product targets", description: "Saved production targets and planning windows.", href: "/planning/plans", module: "planning", capabilities: ["planning.demand.read"], stage: "Demand", roles: ["planner"] },
  { id: "forecast", label: "Demand forecast", description: "Product forecasts consumed by confirmed demand.", href: "/manufacturing/planning/forecast", module: "manufacturing", capabilities: ["manufacturing.plan.read"], stage: "Demand", roles: ["planner"] },
  { id: "sop", label: "Sales & operations plan", description: "Review and publish the approved consensus forecast.", href: "/sop", module: "sop", capabilities: ["sop.read"], stage: "Demand", roles: ["planner", "finance"] },
  { id: "mrp", label: "Material plan / MRP", description: "Net demand, explode recipes and review material and capacity needs.", href: "/manufacturing/planning", module: "manufacturing", requiredModules: ["stock"], capabilities: ["manufacturing.plan.read", "stock.read"], stage: "Materials", roles: ["planner", "buyer"] },
  { id: "proposals", label: "Supply proposals", description: "Review make, buy and transfer proposals with their source demand.", href: "/manufacturing/planning/planned-orders", module: "manufacturing", capabilities: ["manufacturing.plan.read"], stage: "Materials", roles: ["planner", "buyer"] },
  { id: "shortages", label: "Material shortages", description: "Find missing components and the demand they put at risk.", href: "/manufacturing/planning/shortages", module: "manufacturing", capabilities: ["manufacturing.plan.read"], stage: "Materials", roles: ["planner", "buyer"] },
  { id: "inventory", label: "Inventory & availability", description: "Shared on-hand stock, holds and incoming supply.", href: "/stock", module: "stock", capabilities: ["stock.read"], stage: "Materials", roles: ["planner", "buyer", "production"] },
  { id: "stock-forecast", label: "Replenishment policies", description: "Safety stock, usage, lead times and stock forecast.", href: "/stock/forecast", module: "stock", capabilities: ["stock.read"], stage: "Materials", roles: ["planner", "buyer"] },
  { id: "schedule", label: "Production schedule", description: "Machine load, shift calendars and scheduled operations.", href: "/manufacturing/schedule", module: "manufacturing", capabilities: ["manufacturing.schedule.read"], stage: "Schedule", roles: ["planner", "production"] },
  { id: "teams", label: "Production teams", description: "Planning teams and shared work assignments.", href: "/planning/teams", module: "planning", capabilities: ["planning.demand.read"], stage: "Schedule", roles: ["planner", "production"] },
  { id: "today", label: "Production today", description: "Running, waiting, blocked work and the next completions.", href: "/manufacturing/today", module: "manufacturing", capabilities: ["manufacturing.order.read"], stage: "Production", roles: ["production", "planner"] },
  { id: "orders", label: "Production orders", description: "Release work, follow progress and complete routing steps.", href: "/manufacturing/produce", module: "manufacturing", capabilities: ["manufacturing.order.read"], stage: "Production", roles: ["production", "planner"] },
  { id: "floor", label: "Shop floor", description: "Operator work queue, start, pause, complete and scrap.", href: "/manufacturing/shop-floor", module: "manufacturing", capabilities: ["manufacturing.work_order.execute"], stage: "Production", roles: ["production"] },
  { id: "movements", label: "Stock movements", description: "Trace material issues and production receipts.", href: "/stock/movements", module: "stock", capabilities: ["stock.read"], stage: "Production", roles: ["production", "buyer"] },
  { id: "delivery", label: "Fulfilment & delivery", description: "Warehouse work, dispatch and customer delivery.", href: "/logistics", module: "logistics", capabilities: ["logistics.read"], stage: "Production", roles: ["production", "planner"] },
  { id: "products", label: "Products & recipes", description: "One catalogue with BOMs, routing steps and estimated costs.", href: "/products", module: "products", capabilities: ["core.products.read"], stage: "Products & plant", roles: ["planner", "production", "buyer"] },
  { id: "plant", label: "Work centres & machines", description: "Configure the plant and its production resources.", href: "/manufacturing/plant", module: "manufacturing", capabilities: ["manufacturing.order.read"], stage: "Products & plant", roles: ["planner", "production"] },
  { id: "engineering", label: "Engineering changes", description: "Product revisions and engineering evidence.", href: "/engineering", module: "engineering", capabilities: ["engineering.read"], stage: "Products & plant", roles: ["planner", "production"] },
  { id: "quality", label: "Quality & holds", description: "Inspections, nonconformance and controlled disposition.", href: "/quality", module: "quality", capabilities: ["quality.read"], stage: "Products & plant", roles: ["production", "buyer"] },
  { id: "maintenance", label: "Equipment maintenance", description: "Equipment, service work and breakdown records.", href: "/maintenance", module: "maintenance", capabilities: ["maintenance.read"], stage: "Products & plant", roles: ["production", "planner"] },
  { id: "purchases", label: "Purchase orders & receipts", description: "Approve purchases and receive goods into shared Inventory.", href: "/finance/purchases", module: "finance", capabilities: ["finance.overview.read", "finance.purchase.read"], stage: "Finance & procurement", roles: ["buyer", "finance"] },
  { id: "spend", label: "Supply spend report", description: "Posted supplier spend, receipts, purchase commitments and drill-through.", href: "/manufacturing/spend", module: "finance", capabilities: ["finance.overview.read", "finance.report.read"], stage: "Finance & procurement", roles: ["finance", "buyer"] },
  { id: "suppliers", label: "Suppliers & payables", description: "Supplier invoices, credits and amounts still payable.", href: "/finance/payables", module: "finance", capabilities: ["finance.overview.read", "finance.payables.read"], stage: "Finance & procurement", roles: ["buyer", "finance"] },
  { id: "budgets", label: "Budgets & cash outlook", description: "Review budgets, commitments and posted invoice due dates.", href: "/finance/planning", module: "finance", capabilities: ["finance.overview.read", "finance.planning.read"], stage: "Finance & procurement", roles: ["finance"] },
  { id: "reports", label: "Production performance", description: "Customer orders at risk and production progress.", href: "/manufacturing/reports", module: "manufacturing", capabilities: ["manufacturing.order.read"], stage: "Finance & procurement", roles: ["planner", "production", "finance"] },
];

export function consoleDestinations(session: Session, enabled: Set<string>) {
  return CONSOLE_DESTINATIONS.filter((item) => enabled.has(item.module) && (item.requiredModules ?? []).every((id) => enabled.has(id)) && item.capabilities.every((cap) => session.capabilities.has(cap)));
}
export function consoleRole(value: unknown): ConsoleRole { return CONSOLE_ROLES.includes(value as ConsoleRole) ? value as ConsoleRole : "all"; }
