export type SupplyGuide = { id: string; title: string; summary: string; role: string; image: string; alt: string; destinations: string[]; before: string; steps: Array<{ title: string; instruction: string; check: string }>; exceptions: string[] };
export const SUPPLY_GUIDES: SupplyGuide[] = [
  { id: "start", title: "Start with the manufacturing console", summary: "Find your daily work and follow the operation from demand to spend.", role: "Everyone", image: "planning-cycle", alt: "Demand flows through material planning, supply decisions, scheduling, production and stock and spend.", destinations: ["demand", "mrp", "orders", "spend"], before: "Sign in to the correct company. Your profile determines the workspaces and actions available.", steps: [
    { title: "Choose your view", instruction: "Open Manufacturing & Supply from Home. Choose Whole operation, Planner, Procurement, Production or Finance. The view focuses the directory; it does not grant new permissions.", check: "You can see the relevant workspaces and their short descriptions." },
    { title: "Set your quick access", instruction: "Open Customise shortcuts and choose up to six destinations. Bookmark this view to return to the same selection. Search the directory when you need another task.", check: "Quick access contains your selected links." },
    { title: "Review exceptions before starting work", instruction: "Check late or blocked production and outstanding Make/Buy proposals. Read the last completed material-plan date before relying on its output.", check: "You know which records need review and when the plan was generated." },
    { title: "Follow the same records", instruction: "Use the same Manufacturing & Supply navigation for Demand, Materials, Schedule, Production, Products and Inventory. Products & plant includes warehouses and locations. Finance & procurement opens the linked purchasing and reporting controls; Finance also has a console return link.", check: "The same SKU, stock record and source document follow the work." },
  ], exceptions: ["A missing workspace usually means the app is disabled or your profile lacks access. Ask the company administrator; changing the view cannot unlock it."] },
  { id: "products-stock", title: "Set up products, materials and stock", summary: "Use one catalogue for sellable goods and internal manufacturing items.", role: "Engineer / planner", image: "product-chain", alt: "Raw material and packaging feed an intermediate item, which feeds a sellable finished product; all use the same Inventory ledger.", destinations: ["products", "inventory", "stock-forecast", "warehouses", "plant"], before: "Have a unique SKU, a stock unit, the material list and the correct make/buy decision for each item.", steps: [
    { title: "Create every stocked item once", instruction: "Open Products & recipes. Create raw materials, packaging, intermediate/WIP items and finished goods with their own SKUs. Choose the Class that describes the item. Category remains the commercial grouping.", check: "Each physical item has one catalogue identity and one stock unit." },
    { title: "Set sales eligibility", instruction: "On a product, open Details and logistics. Turn off Sellable in Sales for internal materials or intermediates that customers cannot buy. Keep Active in the catalogue on so the item can still be purchased, stocked and used in recipes.", check: "The product is labelled Internal / not sellable and is excluded from new Sales product selection." },
    { title: "Define how supply is obtained", instruction: "Open Bill and routing. Choose bought-in, made here or the appropriate intermediate policy. For made items, add component Products and their quantities, yield, scrap, batch quantity and ordered operations. Choose the real work centre and machine for each step.", check: "The multi-level structure reaches actual bought materials; it contains no loop." },
    { title: "Set stock policies and opening facts", instruction: "Use Inventory and the product's planning controls for warehouses, receipts, safety stock, lead time and expected usage. Enter physical quantities through a controlled receipt or adjustment, never through a forecast target.", check: "The Stock tab and Inventory show the same warehouse quantities. Internal materials remain visible." },
  ], exceptions: ["Class, sales eligibility and make/buy policy are separate decisions. A material can be sold when permitted; a finished item can be bought.", "A WIP-class product is a stocked intermediate. It is not a valuation of unfinished production.", "Stock execution currently requires whole accepted units. Check your unit choice before using fractional materials."] },
  { id: "demand", title: "Build demand and an agreed forecast", summary: "Keep customer orders, targets and forecasts understandable.", role: "Planner", image: "planning-cycle", alt: "Customer orders and an approved forecast feed one material plan, with consumed forecast removed.", destinations: ["demand", "targets", "forecast", "sop"], before: "Products and stock units must be set up; customer orders need product lines and realistic required dates.", steps: [
    { title: "Review customer demand", instruction: "Open Customer demand. Search by SKU or order reference. Focus Stock shortages or Unit conflicts, then open a product's demand chain to inspect required dates and outstanding quantities.", check: "Draft demand is excluded; confirmed quantities still to deliver are traceable to their orders." },
    { title: "Set product targets deliberately", instruction: "Use Product targets for saved production targets and planning windows. A saved target is planning intent; it does not receive stock or authorise a production order.", check: "You can distinguish a target from an executable order." },
    { title: "Maintain the forecast", instruction: "Use Demand forecast for monthly product quantities. When using S&OP, review and approve the agreed version before publishing its total demand to Manufacturing.", check: "An approved S&OP publication retains its version; working assumptions are not published demand." },
    { title: "Check consumption and dates", instruction: "Confirmed bookings consume forecasts for the same product and month. Review source demand on the resulting supply proposals, especially overdue requirements and items whose expected monthly usage also drives planning.", check: "You are not adding the full forecast and the same customer orders twice." },
  ], exceptions: ["Resolve incompatible units before trusting net quantities.", "The demand workbench and MRP have different source-status rules: MRP also considers on-hold bookings. Review their source documents before committing supply."] },
  { id: "mrp", title: "Run and review a material plan", summary: "Turn demand and recipes into explainable supply proposals.", role: "Planner", image: "planning-cycle", alt: "MRP combines demand, recipe components and usable stock to produce Make and Buy proposals.", destinations: ["mrp", "proposals", "shortages", "products"], before: "Check demand, active recipes, current stock, holds, lead times and existing production. Running a plan requires planning management and source access.", steps: [
    { title: "Run the calculation", instruction: "Choose Run material plan on the console or Run MRP in Material plan / MRP. Wait for the result; do not assume the output has updated until the completed run is shown.", check: "A completed run has a date, product count and proposal output." },
    { title: "Review each requirement", instruction: "Open Supply proposals. Read the source demand, needed-by/start dates, materials, operations, hours and estimated recipe costs. The engine recursively explodes made components and nets usable stock and existing production.", check: "You can explain why the proposed quantity is needed." },
    { title: "Resolve exceptions", instruction: "Open Material shortages and identify the missing component. Review stock, supplier lead time and the affected demand before choosing Make, Buy or a reviewed internal move.", check: "You have an owner and a next action for the shortage." },
    { title: "Convert only after review", instruction: "Firm a Make proposal to a production order, or open Review purchase draft on a Buy proposal. Dismiss only when you intentionally choose not to supply that requirement. A newer run makes older conversions unavailable.", check: "The conversion has one real order and a retained source proposal." },
  ], exceptions: ["MRP dates and rough capacity loads are planning estimates. They are not a protected customer delivery promise.", "Current MRP nets stock across warehouses and aggregates existing production supply; it is not yet a full site-specific, dated purchase/transfer netting engine.", "Recipe estimates are not posted Finance spend or WIP cost."] },
  { id: "procurement", title: "Convert a Buy proposal to a purchase draft", summary: "Keep the product, quantity and planning reason attached to Procurement.", role: "Procurement", image: "purchase-finance", alt: "A Buy proposal creates a reviewed purchase draft, followed by approval, receipt, supplier invoice and Finance reporting.", destinations: ["proposals", "purchases", "suppliers"], before: "You need Manufacturing plan read/firm and Finance purchase management, plus access to shared Products and suppliers. Set up a Finance legal entity first.", steps: [
    { title: "Start from the proposal", instruction: "Open Supply proposals and choose Review purchase draft on a Buy row. Use the latest completed material plan.", check: "The draft opens with the original SKU, exact proposed quantity, needed date and MRP source." },
    { title: "Review supplier, price and allocation", instruction: "Choose the correct legal entity, supplier, currency, exchange rate, unit price, verified VAT treatment, due date and cost centre/site/category. Keep the source product and quantity. A zero price requires review before saving.", check: "The commercial facts are reviewed rather than guessed by MRP." },
    { title: "Save once", instruction: "Save draft. Atlas claims the proposal and creates the financial draft together. If the proposal changed, a newer plan exists or someone already converted it, review the current proposal before retrying.", check: "One purchase draft exists and its timeline retains the MRP source." },
    { title: "Obtain approval", instruction: "Open the purchase document and submit it through the existing approval controls. Saving the draft does not receive stock, post cost or pay the supplier.", check: "The purchase order is approved before receiving or supplier invoicing." },
  ], exceptions: ["Use an ordinary reviewed purchase for a changed quantity or another requirement; the proposal conversion retains its exact product and quantity.", "A Finance draft is a procurement handoff, not dated available supply in the current MRP engine. Review replenishment and rerun after authoritative stock updates."] },
  { id: "receiving", title: "Receive materials and follow the supplier invoice", summary: "Connect approved purchasing, accepted stock and financial evidence.", role: "Warehouse / Finance", image: "purchase-finance", alt: "Approved purchase order branches to accepted stock receipt and supplier invoice; Finance reports each separately.", destinations: ["purchases", "inventory", "movements", "suppliers"], before: "Use an approved purchase order. Know the delivered quantities, damaged quantities, receiving warehouse and supplier evidence.", steps: [
    { title: "Open the approved purchase", instruction: "Go to Purchase orders & receipts and open the correct document. Review its product lines and previous receipts before entering another delivery.", check: "The source order and remaining quantities match the delivery." },
    { title: "Record the delivery accurately", instruction: "Enter received and damaged quantities for the PO lines and choose the receiving warehouse for physical products. Accepted quantity is received less damaged; it must not exceed the remaining ordered quantity.", check: "Only accepted physical units enter available stock." },
    { title: "Verify both records", instruction: "After saving, inspect the linked receipt and Inventory movements. Receipt valuation/GRNI and the accepted physical-stock changes are committed together.", check: "The same product and receipt reference appear in the stock and financial records." },
    { title: "Review the supplier bill", instruction: "Create the supplier invoice against the approved PO and match its source lines. Complete Finance's validation, approval and posting before treating it as posted supplier spend.", check: "The posted bill remains linked to its purchase; the spend report includes its net amount." },
  ], exceptions: ["Receipt value, supplier invoice spend and cash payment are different measures. Do not add them together.", "Lot/serial/bin valuation and returned-material production workflows have additional delivery gaps; do not assume a quantity-only receipt completes traceability."] },
  { id: "schedule", title: "Schedule work and review a change", summary: "Use real resources, shifts, conflicts and downstream impact.", role: "Production planner", image: "schedule-production", alt: "Three operations occupy separate machine lanes with dependencies and a highlighted conflict.", destinations: ["plant", "schedule", "orders"], before: "Configure work centres, machines and shifts. Product routing steps need appropriate resources; production orders must have generated work orders.", steps: [
    { title: "Review the plant calendar", instruction: "Open Production schedule and review the shift configuration and scheduled machine/work-centre load. A weekday estimate means real shifts still need configuration.", check: "The load basis and available hours are understood." },
    { title: "Select the operation", instruction: "Choose an operation in the schedule board. Review the production order, required completion and the following operations before moving it.", check: "You know which order and dependencies the move affects." },
    { title: "Preview the move", instruction: "Choose a new start or eligible resource and preview it. Review overlaps, the suggested alternative slot, cascaded following steps and any missed required date.", check: "The impact is visible before you commit." },
    { title: "Commit deliberately", instruction: "Save only after reviewing the impact. Respect locked operations. Running or completed work cannot be moved as if it had not happened.", check: "The published operation timing and downstream dates match the approved move." },
  ], exceptions: ["The current scheduler has resource-overlap and sequence checks. Simultaneous finite material/labour/tool scheduling, alternative-route optimisation and full scenario publication remain open.", "An override does not establish a feasible customer promise."] },
  { id: "production", title: "Release and complete production", summary: "Follow the routing and keep material issues and output consistent.", role: "Supervisor / operator", image: "schedule-production", alt: "Released production flows through ordered operations to component issues, good output and shared Inventory.", destinations: ["orders", "floor", "movements", "quality"], before: "Review the recipe, quantity, receiving warehouse, material availability and applicable safety/quality controls. Use the authorised production and operator actions.", steps: [
    { title: "Review and release the order", instruction: "Open Production orders, inspect the product/routing and required date, then release using the permitted action. Release generates the order's work steps from its recipe.", check: "Work orders have an ordered sequence and the assigned plant resources." },
    { title: "Work in the shop-floor queue", instruction: "Operators use Shop floor to start, pause and complete their work. Record good/scrap quantities accurately and follow the preceding-step rules.", check: "The visible operation status reflects the work actually done." },
    { title: "Complete the final step", instruction: "Earlier steps must be complete. On final routing completion, Atlas issues recipe materials and receives good output while completing the parent in one transaction. Intermediate steps do not receive finished stock.", check: "The final production status and component/output movements agree." },
    { title: "Review follow-on work", instruction: "Check Inventory movements, Quality work and the affected customer delivery. Manufacturing completion is separate from dispatch and invoice posting.", check: "The output is visible in Inventory and the next owner can act." },
  ], exceptions: ["If completion fails, review the stated problem before retrying; a failed transaction must not leave partial stock movements.", "Repeated partial receipts, overproduction tolerances, full WIP/cost journals, co-/by-products and rework are not fully delivered."] },
  { id: "spend", title: "Report purchasing spend to Finance", summary: "Separate posted spend, commitments, receipts and current payables.", role: "Finance / procurement", image: "purchase-finance", alt: "Four separate Finance measures show posted supplier spend, uninvoiced commitments, accepted receipts and current payables.", destinations: ["spend", "purchases", "suppliers", "budgets"], before: "Finance report access is required. Purchasing and Payables source permissions determine the measures available.", steps: [
    { title: "Choose entity and period", instruction: "Open Supply spend report. Select the legal entity and reporting dates. Keep separate transaction currencies separate; no guessed exchange rate is applied.", check: "The report clearly identifies the selected entity, dates and currencies." },
    { title: "Read each measure correctly", instruction: "Posted supplier spend is invoice net less credit net plus debit adjustments. Uninvoiced commitments are approved PO net less linked posted bills through the end date. Receipts are accepted posted receipt net in the period. Current open payables include gross unsettled supplier documents and credits.", check: "You do not treat a commitment or receipt as additional posted spend." },
    { title: "Investigate the breakdown", instruction: "Choose Supplier, Category, Cost centre, Site or Month. Open a source document to follow its original purchase, receipt, invoice and timeline.", check: "Totals can be traced to the underlying authorised records." },
    { title: "Use the right financial report", instruction: "Use Finance reports and the ledger for accounting statements, and Banking for payments. The supply report includes authorised non-manufacturing supplier purchases too; review allocations before interpreting plant-only spend.", check: "Finance receives the appropriate evidence and knows the scope." },
  ], exceptions: ["Restricted source access is displayed as Restricted, not zero.", "This supplier-document report is not a full manufacturing WIP, inventory-valuation, absorbed-cost or cost-variance report.", "Current payables are not a historical period-end balance or a cash-paid measure."] },
];
