import Link from 'next/link';
import type {ReactNode} from 'react';
export const field='mt-1 block w-full min-w-0 rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm';
export const primary='inline-flex items-center justify-center rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-medium text-white';
export const quiet='inline-flex items-center justify-center rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm';
export const formGrid='grid min-w-0 gap-4 sm:grid-cols-2';
export function Heading({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children?:ReactNode}){return <header className="flex flex-wrap items-start justify-between gap-4"><div className="max-w-3xl min-w-0"><p className="text-xs font-semibold uppercase tracking-widest text-blue-600">{eyebrow}</p><h1 className="mt-2 break-words text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-3 text-sm leading-relaxed text-slate-500">{description}</p></div>{children}</header>;}
export function Panel({title,children}:{title:string;children:ReactNode}){return <section className="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="mb-4 text-lg font-semibold">{title}</h2>{children}</section>;}
export function Input({label,name,type='text',value,required=false,maxLength=200,min,step}:{label:string;name:string;type?:string;value?:string|number;required?:boolean;maxLength?:number;min?:number;step?:string}){return <label className="block min-w-0 text-sm">{label}<input aria-label={label} name={name} type={type} defaultValue={value} required={required} maxLength={maxLength} min={min} step={step} className={field}/></label>;}
export function Textarea({label,name,value,required=false}:{label:string;name:string;value?:string|null;required?:boolean}){return <label className="block text-sm sm:col-span-2">{label}<textarea aria-label={label} name={name} defaultValue={value??''} required={required} maxLength={12000} rows={4} className={field}/></label>;}
export function Select({label,name,options,value,required=false}:{label:string;name:string;options:{id:string;name:string}[];value?:string|null;required?:boolean}){return <label className="block min-w-0 text-sm">{label}<select aria-label={label} name={name} defaultValue={value??''} required={required} className={field}>{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>;}
export function Hidden({id,version}:{id:string;version?:number}){return <><input type="hidden" name="id" value={id}/>{version!=null?<input type="hidden" name="version" value={version}/>:null}</>;}
export function Empty({children}:{children:ReactNode}){return <p className="rounded-xl bg-slate-50 p-5 text-sm leading-relaxed text-slate-500">{children}</p>;}
export function Stats({items}:{items:{label:string;value:string|number}[]}){return <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{items.map(i=><div key={i.label} className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-500">{i.label}</p><p className="mt-2 text-2xl font-semibold">{i.value}</p></div>)}</div>;}
export function Row({href,title,meta,status}:{href:string;title:string;meta:string;status?:string}){return <Link href={href} className="flex min-w-0 flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-100 p-4 hover:bg-blue-50"><div className="min-w-0"><h3 className="break-words font-medium">{title}</h3><p className="mt-1 break-words text-xs text-slate-500">{meta}</p></div>{status?<span className="rounded-full bg-slate-100 px-3 py-1 text-xs">{status.replaceAll('_',' ')}</span>:null}</Link>;}
export function DateText({date,zone='Europe/London',time=false}:{date:Date|null;zone?:string;time?:boolean}){return <>{date?date.toLocaleString('en-GB',{timeZone:zone,day:'numeric',month:'short',year:'numeric',...(time?{hour:'2-digit',minute:'2-digit'}:{})}):'Not set'}</>;}
export function localInput(d:Date,zone='Europe/London'){return new Intl.DateTimeFormat('sv-SE',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(d).replace(' ','T');}
export const options=(v:readonly string[])=>v.map(id=>({id,name:id.replaceAll('_',' ').toLowerCase().replace(/^./,c=>c.toUpperCase())}));
