import { redirect } from 'next/navigation';
import { PlanningWorkspace } from '@/modules/marketing/components/planning-workspace';
import { MarketingLeads } from '@/modules/marketing/components/leads-board';
import { MarketingCalendar } from '@/modules/marketing/components/month-calendar';
import { MarketingBudgets } from '@/modules/marketing/components/budget-board';
import { MarketingJourneyMap } from '@/modules/marketing/components/journey-map';
import { AudienceBuilder,JourneyBuilder } from '@/modules/marketing/components/builders';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireSession } from '@/core/auth/session';
import { assertCapability } from '@/core/permissions/check';
import { db } from '@/core/db/client';
import { sections,requireMarketing,type MarketingSection } from '@/modules/marketing/services/queries';
import * as actions from '@/modules/marketing/services/commands';
import { ActionForm } from '@/modules/marketing/components/action-form';
import { Card } from '@/components/ui/card';
import { CHANNELS,PERMISSION_STATES,EVENT_TYPES } from '@/modules/marketing/domain/policy';
import { attributionReport } from '@/modules/marketing/services/reporting';
function human(value:string){return value.replace(/([a-z])([A-Z])/g,'$1 $2').replaceAll('_',' ').toLowerCase().replace(/^./,c=>c.toUpperCase());}
const inputClass='mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm';
function Field({name,label=name,type='text',value='',required=true}:{name:string;label?:string;type?:string;value?:string;required?:boolean}){return <label className="block text-sm font-medium text-slate-700">{human(label)}<input className={inputClass} name={name} type={type} defaultValue={value} required={required}/></label>;}
function Area({name,label=name,value='',required=true}:{name:string;label?:string;value?:string;required?:boolean}){return <label className="block text-sm font-medium text-slate-700">{human(label)}<textarea className={inputClass} name={name} defaultValue={value} required={required} rows={4}/></label>;}
function Select({name,label=name,options}:{name:string;label?:string;options:readonly string[]}){return <label className="block text-sm font-medium text-slate-700">{human(label)}<select className={inputClass} name={name}>{options.map(v=><option key={v} value={v}>{human(v)}</option>)}</select></label>;}
function Reference({name,label,rows,optional=false}:{name:string;label:string;rows:{id:string;name:string}[];optional?:boolean}){return <label className="block text-sm font-medium text-slate-700">{human(label)}<select className={inputClass} name={name} required={!optional}>{optional&&<option value="">None</option>}{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>;}
function Hidden({name,value}:{name:string;value:string|number}){return <input type="hidden" name={name} value={value}/>;}
function Dimensions(){return <><Select name="channel" options={['EMAIL','SMS']}/><Field name="purpose" label="Subscription purpose" value="PRODUCT_PROMOTIONS"/><Field name="brand" value="DEFAULT"/><Field name="country" value="GB"/><Field name="legalEntity" label="Legal entity"/></>;}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <Card className="p-5"><h2 className="mb-4 text-lg font-semibold">{title}</h2>{children}</Card>;}
function Empty(){return <p className="rounded-xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">No records yet. Create your first record to begin.</p>;}
function Money({amount,currency='GBP'}:{amount:number;currency?:string}){return <>{new Intl.NumberFormat('en-GB',{style:'currency',currency}).format(amount/100)}</>;}
export default async function Workspace({params,searchParams}:{params:Promise<{section:string}>;searchParams:Promise<{focus?:string;partyId?:string;model?:string;month?:string}>}){
 const {section:raw}=await params;const query=await searchParams;if(raw==='plans'||raw==='campaigns')redirect(query.focus?`/marketing?focus=${encodeURIComponent(query.focus)}`:'/marketing');if(!(raw in sections))notFound();const section=raw as MarketingSection,config=sections[section];const s=await requireSession();assertCapability(s,config.cap);await requireMarketing(s);const where={organisationId:s.organisationId};const can=(c:string)=>s.capabilities.has(`marketing.${c}`);
 const [campaigns,audiences,profiles]=await Promise.all([can('campaign.read')?db.marketingCampaign.findMany({where,orderBy:{updatedAt:'desc'},take:100}):[],can('audience.read')?db.marketingAudience.findMany({where,orderBy:{name:'asc'},take:100}):[],can('profile.read')?db.marketingProfile.findMany({where:{...where,...query.partyId?{partyId:query.partyId}:{}},select:{id:true,contactId:true,partyId:true,score:true,lifecycle:true,country:true,source:true,brand:true},take:100}):[]]);
 const campaignOptions=campaigns.map(c=>({id:c.id,name:`${c.code} · ${c.name}`})),audienceOptions=audiences.map(a=>({id:a.id,name:a.name})),profileOptions=profiles.map(p=>({id:p.id,name:`${p.contactId} · ${p.lifecycle} · ${p.score}`}));
 let content:React.ReactNode;
 if(section==='sales'){content=<PlanningWorkspace session={s}/>;}
 else if(section==='calendar'){content=<MarketingCalendar session={s} month={query.month}/>;}
 else if(section==='budgets'){content=<MarketingBudgets session={s}/>;}
 else if(section==='leads'){content=<MarketingLeads session={s}/>;}
 else if(section==='journey'){content=<MarketingJourneyMap session={s} focus={query.focus}/>;}
 else if(section==='audiences')content=<div className="grid gap-6 xl:grid-cols-[1fr_360px]"><div className="space-y-4">{!audiences.length&&<Empty/>}{audiences.map(a=><Panel key={a.id} title={a.name}><p className="mb-4 text-sm text-slate-500">{a.type} · {a.source} · {a.purpose}</p><pre className="mb-4 overflow-auto text-xs">{JSON.stringify(a.rules,null,2)}</pre><ActionForm action={actions.previewAudience} label="Preview matched & eligible"><Hidden name="audienceId" value={a.id}/><Dimensions/></ActionForm></Panel>)}</div>{can('audience.create')&&<Panel title="Build an audience"><ActionForm action={actions.createAudience}><Field name="name"/><Select name="type" options={['DYNAMIC','STATIC','IMPORTED']}/><AudienceBuilder/><Area name="profileIds" label="Known profile IDs for static/imported audiences" required={false}/><Field name="source" label="Acquisition source / supplier"/><Field name="purpose"/><Field name="permissionBasis" label="Permission basis"/><Field name="acquiredAt" type="date"/><Area name="evidence" label="Provenance evidence"/></ActionForm><p className="mt-3 text-xs text-slate-500">Imported audiences reference existing Atlas profiles. Import does not grant consent. Audience matching and send eligibility are separate.</p></Panel>}</div>;
 else if(section==='profiles'||section==='accounts'){
  const contacts=s.capabilities.has('customers.read')?await db.contact.findMany({where:{party:{organisationId:s.organisationId}},select:{id:true,firstName:true,surname:true},take:500}):[];
  const names=new Map(contacts.map(c=>[c.id,`${c.firstName} ${c.surname}`]));
  content=<div className="grid gap-6 xl:grid-cols-[1fr_360px]"><div className="space-y-3">{!profiles.length&&<Empty/>}{profiles.map(p=><Panel key={p.id} title={names.get(p.contactId)??p.contactId}><p className="text-sm">{p.lifecycle} · Score {p.score} · {p.country} · {p.brand}</p><p className="mt-2 text-xs text-slate-500">Profile {p.id} · Source {p.source}</p>{s.capabilities.has('customers.read')&&<Link className="mt-2 block text-sm text-blue-600" href={`/customers/${p.partyId}`}>Open shared customer record →</Link>}</Panel>)}</div>{can('profile.manage')&&s.capabilities.has('customers.read')&&<Panel title="Add Marketing to a contact"><ActionForm action={actions.createProfile}><Reference name="contactId" label="Existing Atlas contact" rows={contacts.map(c=>({id:c.id,name:`${c.firstName} ${c.surname}`}))}/><Field name="source"/><Field name="country" value="GB"/><Field name="brand" value="DEFAULT"/></ActionForm></Panel>}</div>;
 }else if(section==='consent'){
  const [permissions,suppressions]=await Promise.all([db.marketingPermission.findMany({where,orderBy:{createdAt:'desc'},take:100}),db.marketingSuppression.findMany({where,orderBy:{createdAt:'desc'},take:100})]);
  content=<div className="grid gap-6 xl:grid-cols-[1fr_360px]"><div className="space-y-4"><Panel title="Consent evidence & history">{!permissions.length&&<Empty/>}{permissions.map(p=><div key={p.id} className="border-b border-slate-100 py-4 text-sm"><p className="font-medium">{p.channel} · {p.purpose} · {p.state}</p><p>{p.brand} / {p.country} / {p.legalEntity}</p><p className="text-xs text-slate-500">Profile {p.profileId} · {p.occurredAt.toLocaleString('en-GB')} · {p.source} · {p.lawfulBasis}</p><p className="mt-2">{p.evidence}</p></div>)}</Panel><Panel title="Suppression register">{!suppressions.length&&<Empty/>}{suppressions.map(p=><p className="border-b py-3 text-sm" key={p.id}>{p.profileId} · {p.channel} · {p.reason}</p>)}</Panel></div>{can('consent.manage')&&<div className="space-y-4"><Panel title="Record permission evidence"><ActionForm action={actions.recordPermission}><Reference name="profileId" label="Profile" rows={profileOptions}/><Dimensions/><Select name="state" options={PERMISSION_STATES}/><Field name="source"/><Area name="evidence"/><Field name="textVersion" label="Consent text version"/><Field name="noticeVersion" label="Privacy notice version"/><Field name="lawfulBasis" label="Applicable basis / rule"/></ActionForm></Panel><Panel title="Add suppression"><ActionForm action={actions.suppressProfile}><Reference name="profileId" label="Profile" rows={profileOptions}/><Select name="channel" options={['ALL',...CHANNELS]}/><Field name="reason"/><Field name="source"/></ActionForm></Panel></div>}</div>;
 }else if(section==='content'){
  const rows=await db.marketingContent.findMany({where,orderBy:{createdAt:'desc'},take:100});content=<div className="grid gap-6 xl:grid-cols-[1fr_360px]"><div className="space-y-4">{!rows.length&&<Empty/>}{rows.map(c=><Panel key={c.id} title={c.name}><p className="text-xs text-slate-500">{c.kind} · {c.status} · Version {c.version} · {c.brand}</p><p className="my-4 whitespace-pre-wrap text-sm">{c.body}</p><p className="text-xs">Rights: {c.rights||'Unspecified'}</p>{can('content.approve')&&c.status==='DRAFT'&&<ActionForm action={actions.approveContent} label="Approve content"><Hidden name="id" value={c.id}/></ActionForm>}</Panel>)}</div>{can('content.create')&&<Panel title="Create reusable content"><ActionForm action={actions.createContent}><Field name="name"/><Select name="kind" options={['EMAIL_TEMPLATE','ARTICLE','GUIDE','SOCIAL_COPY','ASSET_REFERENCE','CONTENT_BRIEF']}/><Reference name="campaignId" label="Campaign" rows={campaignOptions} optional/><Field name="brand" value="DEFAULT"/><Area name="body" label="Copy / asset reference"/><Area name="rights" label="Usage rights" required={false}/><Field name="expiresAt" type="date" required={false}/></ActionForm></Panel>}</div>;
 }else if(section==='email'){
  const [messages,jobs]=await Promise.all([db.marketingMessage.findMany({where,orderBy:{createdAt:'desc'},take:100}),db.marketingSendJob.findMany({where,select:{id:true,messageId:true,status:true,scheduledAt:true},orderBy:{createdAt:'desc'},take:100})]);content=<div className="grid gap-6 xl:grid-cols-[1fr_360px]"><div className="space-y-4"><Panel title="Send control"><p className="text-sm text-amber-700">Provider not connected. Approval freezes content and recipients as LOCKED; it does not queue or send. Final eligibility must be checked again by the connected delivery worker.</p>{jobs.map(j=><div key={j.id} className="my-4 border-t pt-4"><p className="text-sm">{j.status} · {j.scheduledAt.toLocaleString('en-GB')}</p>{can('email.send')&&j.status==='LOCKED'&&<ActionForm action={actions.cancelSend} label="Cancel unsent portion"><Hidden name="id" value={j.id}/></ActionForm>}</div>)}</Panel>{messages.map(m=><Panel key={m.id} title={m.name}><p className="text-xs">{m.channel} · {m.classification} · {m.status} · Version {m.version}</p><h3 className="mt-3 font-medium">{m.subject}</h3><p className="my-3 whitespace-pre-wrap text-sm">{m.body}</p>{can('email.approve')&&m.status==='DRAFT'&&<ActionForm action={actions.lockSend} label="Approve & lock snapshot"><Hidden name="messageId" value={m.id}/><Field name="scheduledAt" label="Planned send time" type="datetime-local"/></ActionForm>}</Panel>)}</div>{can('email.create')&&<Panel title="Draft a message"><ActionForm action={actions.createMessage}><Reference name="campaignId" label="Campaign" rows={campaignOptions}/><Field name="name"/><Dimensions/><Field name="subject"/><Area name="body" label="Message copy"/></ActionForm><p className="mt-3 text-xs text-slate-500">Promotional classification. Transactional sending requires a separately verified ERP workflow.</p></Panel>}</div>;
 }else if(section==='journeys'){
  const rows=await db.marketingJourney.findMany({where,include:{versions:{where,orderBy:{number:'desc'},take:10}},orderBy:{createdAt:'desc'},take:100});content=<div className="grid gap-6 xl:grid-cols-[1fr_360px]"><div className="space-y-4"><Panel title="Journey execution"><p className="text-sm text-amber-700">Versioned wait, event branch, goal and end paths. Recorded events enrol contacts into the published version. Process due steps runs saved waits, branches and goals. Automatic scheduling and channel actions are not activated.</p>{can("journey.manage")&&<div className="mt-4"><ActionForm action={actions.processJourneySteps} label="Process due steps"/></div>}</Panel>{rows.map(j=><Panel key={j.id} title={j.name}><p className="text-xs">{j.status} · Trigger {j.trigger} · Published V{j.publishedVersion}</p><pre className="my-4 overflow-auto text-xs">{JSON.stringify(j.versions[0]?.nodes,null,2)}</pre>{can('journey.publish')&&<ActionForm action={actions.publishJourney} label="Publish latest version"><Hidden name="id" value={j.id}/></ActionForm>}{can('journey.manage')&&<details className="mt-4"><summary className="text-sm">New version</summary><ActionForm action={actions.reviseJourney}><Hidden name="id" value={j.id}/><Area name="nodes" value={JSON.stringify(j.versions[0]?.nodes)}/><Select name="exitRule" options={['PURCHASE_COMPLETED','NONE']}/></ActionForm></details>}</Panel>)}</div>{can('journey.manage')&&<Panel title="Design a journey"><ActionForm action={actions.createJourney}><Field name="name"/><Select name="trigger" options={EVENT_TYPES}/><JourneyBuilder/><Select name="exitRule" options={['PURCHASE_COMPLETED','NONE']}/></ActionForm></Panel>}</div>;
 }else if(section==='experiments'){
  const rows=await db.marketingExperiment.findMany({where,include:{assignments:{where,take:5000}},take:100});content=<div className="grid gap-6 xl:grid-cols-[1fr_360px]"><div className="space-y-4">{!rows.length&&<Empty/>}{rows.map(e=><Panel key={e.id} title={e.name}><p className="text-sm">{e.status} · {e.metric} · {e.assignments.length} participants</p><p className="mt-2 text-sm">Control {e.control}% · Variant {e.variant}% · Holdout {e.holdout}%</p><p className="mt-3 text-xs text-slate-500">Allocation is frozen. No statistical winner claimed.</p></Panel>)}</div><Panel title="Allocate an experiment"><ActionForm action={actions.createExperiment}><Field name="name"/><Reference name="audienceId" label="Audience" rows={audienceOptions}/><Field name="control" type="number" value="45"/><Field name="variant" type="number" value="45"/><Field name="holdout" type="number" value="10"/><Select name="metric" options={['CLICK','CONVERSION','REVENUE']}/></ActionForm></Panel></div>;
 }else if(['forms','social','events'].includes(section)){
  const kinds=section==='forms'?['FORM','LANDING_PAGE']:section==='social'?['SOCIAL_POST','AD_CAMPAIGN']:['EVENT','WEBINAR'];const rows=await db.marketingProgram.findMany({where:{...where,kind:{in:kinds}},orderBy:{createdAt:'desc'},take:100});content=<div className="grid gap-6 xl:grid-cols-[1fr_360px]"><div className="space-y-4"><Panel title="Production plans"><p className="text-sm text-amber-700">These are draft briefs. Public publishing, registration, tracking and provider connections are pending.</p></Panel>{rows.map(p=><Panel key={p.id} title={p.name}><p className="text-xs">{p.kind} · {p.status} · {p.startsAt?.toLocaleString('en-GB')}</p><pre className="mt-4 whitespace-pre-wrap text-xs">{JSON.stringify(p.definition,null,2)}</pre></Panel>)}</div>{can('program.manage')&&<Panel title="Create a brief"><ActionForm action={actions.createProgram}><Field name="name"/><Select name="kind" options={kinds}/><Reference name="campaignId" label="Campaign" rows={campaignOptions} optional/><Field name="startsAt" type="datetime-local" required={false}/><Area name="brief" label="Objective, content and audience"/><Field name="url" label="Existing public URL" required={false}/><Field name="provider" label="Provider (optional)" required={false}/></ActionForm></Panel>}</div>;
 }else if(section==='attribution'){
  const report=await attributionReport(s,query.model==='FIRST'?'FIRST':query.model==='LAST'?'LAST':'LINEAR');content=<div className="space-y-4"><Panel title="Commercial attribution"><div className="mb-4 flex gap-4">{['FIRST','LAST','LINEAR'].map(m=><Link key={m} href={`/marketing/attribution?model=${m}`} className="text-sm text-blue-600">{m}</Link>)}</div><p className="text-sm text-slate-500">90-day touch window. Allocated order value uses existing confirmed Sales orders; it is not invoiced revenue or profit.</p></Panel>{report.map(r=><Panel key={r.campaignId} title={campaigns.find(c=>c.id===r.campaignId)?.name??r.campaignId}><p className="text-2xl font-semibold"><Money amount={r.amount} currency={r.currency}/></p><p className="mt-2 text-sm">{r.orders} orders influenced · <Link className="text-blue-600" href="/sales/orders">Trace source orders →</Link></p></Panel>)}</div>;
 }else if(section==='analytics')content=<Panel title="Analytics Studio"><p className="mb-4 text-sm text-slate-500">Marketing campaign and qualified-lead metrics are registered in Atlas Analytics with tenant and capability checks. Orders, pipeline, revenue and margin remain owned by their source modules.</p>{s.capabilities.has('analytics.dashboard.read')&&<Link className="text-blue-600" href="/analytics">Open Analytics Studio →</Link>}</Panel>;
 else content=<div className="grid gap-6 xl:grid-cols-2"><Panel title="Delivery readiness"><p className="mb-4 text-sm">Leave providers blank until you choose your connections. Outbound delivery remains unavailable.</p><label className="block text-sm">Email/SMS provider<input disabled placeholder="Not selected" className={inputClass}/></label><label className="mt-3 block text-sm">Sender domain<input disabled placeholder="Not selected" className={inputClass}/></label><label className="mt-3 block text-sm">Social/advertising provider<input disabled placeholder="Not selected" className={inputClass}/></label><p className="mt-4 text-xs text-slate-500">Journey scheduling and AI connections are pending.</p></Panel>{can('event.ingest')&&<Panel title="Record a marketing event"><ActionForm action={actions.ingestEvent}><Reference name="profileId" label="Profile" rows={profileOptions}/><Select name="type" options={EVENT_TYPES}/><Reference name="campaignId" label="Campaign" rows={campaignOptions} optional/><Field name="source"/><Field name="idempotencyKey" label="Source event ID / idempotency key"/><Field name="occurredAt" type="datetime-local"/><Area name="properties" value="{}"/></ActionForm></Panel>}</div>;
 return <main className="mx-auto max-w-7xl space-y-6 p-6"><header><Link href="/marketing" className="text-xs font-semibold uppercase tracking-widest text-blue-600">Marketing</Link><h1 className="mt-2 text-3xl font-semibold">{config.title}</h1></header>{content}</main>;
}
