import Link from "next/link";
import { requireSession } from "@/core/auth/session";
import { assertCapability,can } from "@/core/permissions/check";
import { SALES_CAPABILITIES } from "@/core/permissions/capabilities";
import { db } from "@/core/db/client";
import { formatMoney } from "@/core/shared/money";
import { BarChart } from "@/components/ui/bar-chart";
import { ActionForm } from "@/components/ui/action-form";
import { Button } from "@/components/ui/button";
import { saveDashboard } from "./actions";
const widgets=[['pipeline','Open pipeline'],['winrate','Win rate'],['prospects','Prospects'],['stage','Pipeline by stage'],['trend','Monthly won value'],['owners','Pipeline by owner'],['next-actions','Next action coverage']] as const;
function MoneyTotals({items}:{items:{valueCurrency:string;valueAmount:number}[]}) {const totals=items.reduce<Record<string,number>>((s,i)=>{s[i.valueCurrency]=(s[i.valueCurrency]??0)+i.valueAmount;return s;},{});return <>{Object.entries(totals).map(([currency,amount])=><p key={currency} className="text-3xl font-semibold tracking-tight">{formatMoney(amount,currency)}</p>)}{!items.length&&<p className="text-3xl font-semibold">—</p>}</>;}
export default async function DashboardsPage({searchParams}:{searchParams:Promise<{dashboard?:string;owner?:string;period?:string}>}) {
 const session=await requireSession();
 assertCapability(session,SALES_CAPABILITIES.reportRead);
 const params=await searchParams;
 const period=['30','90','365','all'].includes(params.period??'')?params.period!:'90';
 const since=period==='all'?undefined:new Date(new Date().getTime()-Number(period)*86400000);
 const dashboards=await db.dashboard.findMany({where:{organisationId:session.organisationId,userId:session.userId},orderBy:{name:'asc'}});
 const selected=dashboards.find(d=>d.id===params.dashboard);
 const active=selected?.widgets??widgets.map(w=>w[0]);
 const members=await db.membership.findMany({where:{organisationId:session.organisationId},include:{user:{select:{id:true,name:true}}}});
 const owner=members.some(m=>m.userId===params.owner)?params.owner:undefined;
 const [opportunities,prospects,stages]=await Promise.all([
 db.opportunity.findMany({where:{organisationId:session.organisationId,ownerUserId:owner},select:{id:true,name:true,status:true,valueAmount:true,valueCurrency:true,stageId:true,ownerUserId:true,actualCloseDate:true,nextActionAt:true}}),
 can(session,SALES_CAPABILITIES.prospectRead)?db.prospect.count({where:{organisationId:session.organisationId,ownerUserId:owner,createdAt:since?{gte:since}:undefined}}):0,
 db.pipelineStage.findMany({where:{pipeline:{organisationId:session.organisationId}},include:{pipeline:{select:{name:true}}},orderBy:{order:'asc'}})
 ]);
 const open=opportunities.filter(o=>o.status==='OPEN'), closed=opportunities.filter(o=>o.status!=='OPEN'&&o.actualCloseDate&&(!since||o.actualCloseDate>=since)), won=closed.filter(o=>o.status==='WON');
 const currencies=[...new Set(opportunities.map(o=>o.valueCurrency))];
 const periods=Array.from({length:6},(_,i)=>{const date=new Date();date.setUTCDate(1);date.setUTCMonth(date.getUTCMonth()-5+i);return date;});
 return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-[.14em] text-[var(--color-ink-faint)]">CRM intelligence</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">{selected?.name??'Revenue overview'}</h2><p className="mt-2 text-sm text-[var(--color-ink-muted)]">Live data. Clear signals. Your view of the business.</p></div><Link href="/crm/reports" className="rounded-xl border border-[var(--color-border)] bg-white px-4 py-2 text-sm">Detailed reports →</Link></div>
 <form className="flex flex-wrap gap-3 rounded-2xl border border-[var(--color-border)] bg-white p-4"><label className="text-xs">Dashboard<select name="dashboard" defaultValue={selected?.id??''} className="ml-2 border border-[var(--color-border)] bg-white p-2 text-sm"><option value="">Revenue overview</option>{dashboards.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className="text-xs">Owner<select name="owner" defaultValue={owner??''} className="ml-2 border border-[var(--color-border)] bg-white p-2 text-sm"><option value="">Everyone</option>{members.map(m=><option key={m.id} value={m.userId}>{m.user.name}</option>)}</select></label><label className="text-xs">Period<select name="period" defaultValue={period} className="ml-2 border border-[var(--color-border)] bg-white p-2 text-sm"><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="365">Last year</option><option value="all">All time</option></select></label><Button type="submit">Apply</Button></form>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{active.includes('pipeline')&&<Tile title="Open pipeline"><MoneyTotals items={open}/><p className="mt-3 text-xs text-[var(--color-ink-muted)]">{open.length} open opportunities · current snapshot</p></Tile>}{active.includes('winrate')&&<Tile title="Win rate"><p className="text-4xl font-semibold tracking-tight">{closed.length?`${Math.round(won.length/closed.length*100)}%`:'—'}</p><p className="mt-3 text-xs text-[var(--color-ink-muted)]">{won.length} won of {closed.length} closed in selected period</p></Tile>}{active.includes('prospects')&&can(session,SALES_CAPABILITIES.prospectRead)&&<Tile title="New prospects"><p className="text-4xl font-semibold tracking-tight">{prospects}</p><p className="mt-3 text-xs text-[var(--color-ink-muted)]">Created in the selected period</p></Tile>}{active.includes('next-actions')&&<Tile title="Next action coverage"><p className="text-4xl font-semibold tracking-tight">{open.length?`${Math.round(open.filter(o=>o.nextActionAt).length/open.length*100)}%`:'—'}</p><p className="mt-3 text-xs text-[var(--color-ink-muted)]">{open.filter(o=>!o.nextActionAt).length} opportunities need a next action</p></Tile>}</div>
 <div className="grid gap-5 lg:grid-cols-2">{active.includes('stage')&&<Tile title="Pipeline by stage">{stages.map(stage=>{const count=open.filter(o=>o.stageId===stage.id).length;return <div key={stage.id} className="mt-4"><div className="mb-2 flex justify-between text-xs"><span>{stage.pipeline.name} · {stage.name}</span><span>{count}</span></div><div className="h-2 overflow-hidden rounded-full bg-[#eef0f5]"><div className="h-full rounded-full bg-[var(--color-atlas-blue)] transition-all duration-300" style={{width:`${open.length?count/open.length*100:0}%`}}/></div></div>;})}</Tile>}{active.includes('trend')&&<Tile title="Won value · last six months">{currencies.length?currencies.map(currency=><div key={currency} className="mt-4"><p className="mb-3 text-xs text-[var(--color-ink-muted)]">{currency} · {owner?'selected owner':'all owners'}</p><BarChart points={periods.map(date=>({label:date.toLocaleString('en-GB',{month:'short',timeZone:'UTC'}),value:opportunities.filter(o=>o.status==='WON'&&o.valueCurrency===currency&&o.actualCloseDate&&o.actualCloseDate.getUTCMonth()===date.getUTCMonth()&&o.actualCloseDate.getUTCFullYear()===date.getUTCFullYear()).reduce((s,o)=>s+o.valueAmount/100,0)}))}/></div>):<p className="text-sm text-[var(--color-ink-muted)]">No opportunities yet.</p>}</Tile>}{active.includes('owners')&&<Tile title="Open pipeline by owner">{members.filter(m=>!owner||m.userId===owner).map(m=><div key={m.id} className="flex items-center justify-between border-b border-[var(--color-border)] py-3 text-sm last:border-0"><span>{m.user.name}</span><span className="text-[var(--color-ink-muted)]">{open.filter(o=>o.ownerUserId===m.userId).length} opportunities</span></div>)}</Tile>}</div>
 <details className="rounded-2xl border border-[var(--color-border)] bg-white p-5"><summary className="cursor-pointer text-sm font-semibold">Customise or create a dashboard</summary><ActionForm action={saveDashboard} className="mt-5 space-y-5"><label className="block text-sm">Dashboard name<input required name="name" maxLength={80} defaultValue={selected?.name??''} placeholder="My weekly review" className="mt-2 w-full border border-[var(--color-border)] p-3"/></label><div className="grid gap-3 sm:grid-cols-2">{widgets.map(([id,label])=><label key={id} className="flex gap-2 text-sm"><input type="checkbox" name="widget" value={id} defaultChecked={active.includes(id)}/>{label}</label>)}</div><Button variant="primary" type="submit">Save dashboard</Button><p className="text-xs text-[var(--color-ink-muted)]">Saved dashboards are private to your account in this company. Reusing a name updates that dashboard.</p></ActionForm></details>
 </div>;
}
function Tile({title,children}:{title:string;children:React.ReactNode}) {return <section className="rounded-2xl border border-[var(--color-border)] bg-white p-6 shadow-[0_2px_8px_#10131a03]"><h3 className="mb-5 text-xs font-medium text-[var(--color-ink-muted)]">{title}</h3>{children}</section>;}
