import {readSalesPolicy} from "@/modules/sales/services/sales-policy";
import Link from 'next/link';
import {requireSession} from '@/core/auth/session';
import {assertCapability} from '@/core/permissions/check';
import {db} from '@/core/db/client';
import {ActionForm} from '@/components/ui/action-form';
import {Button} from '@/components/ui/button';
import {saveCreationPolicy} from './actions';
export default async function SalesSettings(){const session=await requireSession();assertCapability(session,'core.modules.manage');const policy=await db.organisation.findUniqueOrThrow({where:{id:session.organisationId},select:{allowProductCreation:true,allowCustomerCreation:true,salesPolicy:true}});const rules=readSalesPolicy(policy.salesPolicy);return <div className="space-y-6"><h2 className="text-2xl font-semibold">Sales configuration</h2><ActionForm action={saveCreationPolicy} className="space-y-6 rounded-2xl border border-slate-200 bg-white p-6"><div><h3 className="font-semibold">Control record creation</h3><p className="mt-2 text-sm text-slate-500">Use approved catalogue and customer records across the company. Existing records can still be used and edited according to user permissions.</p></div>{[['allowProductCreation','Allow new products',policy.allowProductCreation],['allowCustomerCreation','Allow new customers',policy.allowCustomerCreation]].map(([name,label,value])=><label key={String(name)} className="flex items-center justify-between rounded-xl bg-slate-50 p-4 text-sm"><span>{label}</span><input name={String(name)} type="checkbox" defaultChecked={Boolean(value)} className="size-5 accent-blue-600"/></label>)}<div className="border-t border-slate-100 pt-5"><h3 className="font-semibold">Commercial approval limits</h3><p className="mt-2 text-xs text-slate-500">Orders above a value or discount limit require approval. Other currencies require review until a currency limit is configured.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-xs">Maximum line discount %<input type="number" name="discountLimit" min={0} max={100} step="0.1" required defaultValue={rules.discountLimit} className="mt-2 w-full rounded-xl border border-slate-200 p-3"/></label>{['GBP','EUR','USD'].map(currency=><label key={currency} className="text-xs">Order authority · {currency}<input type="number" name={'limit'+currency} min={0} max={21474836} step="0.01" required defaultValue={rules.valueLimits[currency]/100} className="mt-2 w-full rounded-xl border border-slate-200 p-3"/></label>)}</div></div><Button type="submit" variant="primary">Save configuration</Button></ActionForm><div className="flex flex-wrap gap-4 text-sm text-blue-600"><Link href="/products">Product catalogue →</Link><Link href="/pricing">Pricelists →</Link><Link href="/settings">Users & permissions →</Link></div></div>;}
