import {cookies} from 'next/headers';
import {redirect} from 'next/navigation';
import {revalidatePath} from 'next/cache';
import type {Session} from '@/core/auth/session';
import type {PrismaClient} from '@/generated/prisma/client';
import {encodeWire,decodeWire} from './wire';
export function dataApiUrl(path:string){const base=process.env.ATLAS_DATA_API_URL;if(!base)throw new Error('Configure the secure Atlas data API connection.');const url=new URL(base);if(url.protocol!=='https:'&&!(url.protocol==='http:'&&['127.0.0.1','localhost'].includes(url.hostname)))throw new Error('Use HTTPS or the private loopback SSH data connection.');return new URL(path,url).toString();}
async function remoteFetch(path:string,body?:unknown){const session=(await cookies()).get('atlas_session')?.value;const response=await fetch(dataApiUrl(path),{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-Atlas-Client':'desktop',...(session?{Cookie:`atlas_session=${session}`}:{})},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});return response;}
export async function getRemoteSession():Promise<Session|null>{const response=await remoteFetch('/api/desktop/session');if(response.status===401)return null;if(!response.ok)throw new Error('Atlas data connection is unavailable.');const value=await response.json();return {...value,capabilities:new Set(value.capabilities)};}
export async function callRemoteAction(action:string,args:unknown[],shouldRevalidate=false){const response=await remoteFetch('/api/desktop/action',{action,args:await encodeWire(args)});const store=await cookies();for(const cookie of response.headers.getSetCookie()){const parts=cookie.split(';'),separator=parts[0].indexOf('='),name=parts[0].slice(0,separator),value=parts[0].slice(separator+1),maxAge=parts.find(p=>p.trim().toLowerCase().startsWith('max-age='));if(name==='atlas_session')store.set(name,value,{httpOnly:true,sameSite:'lax',secure:false,path:'/',...(maxAge?{maxAge:Number(maxAge.split('=')[1])}:{})});}
 const result=await response.json();if(!response.ok||result.error)throw new Error(result.error??'Atlas data action failed.');if(shouldRevalidate)revalidatePath('/','layout');if(result.redirect)redirect(result.redirect);return decodeWire(result.value);}
export function createDesktopReadClient():PrismaClient{return new Proxy({},{get(_target,model){if(typeof model!=='string')return undefined;if(model==='$disconnect')return async()=>{};if(model.startsWith('$'))return ()=>{throw new Error('Local database operations are disabled. Use an authorised data API action.');};return new Proxy({},{get(_model,method){return async(args:unknown={})=>{const response=await remoteFetch('/api/desktop/query',{model,method,args:await encodeWire(args)}),result=await response.json();if(!response.ok)throw new Error(result.error??'Atlas data query failed.');return decodeWire(result.value);};}});}}) as PrismaClient;}
export async function forwardDesktopRequest(path:string,body:unknown){const session=(await cookies()).get('atlas_session')?.value,url=dataApiUrl(path);return fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Atlas-Client':'desktop',Origin:new URL(url).origin,...(session?{Cookie:`atlas_session=${session}`}:{})},body:JSON.stringify(body),cache:'no-store'});}
