import {Network,Building2,UserRound} from 'lucide-react';
import Link from 'next/link';
import {requireSession} from '@/core/auth/session';
import {assertCapability} from '@/core/permissions/check';
import {effectiveRoleCapabilities} from '@/core/permissions/access-levels';
import {db} from '@/core/db/client';
import {CreateDialog} from '@/components/ui/create-dialog';
import {ActionForm} from '@/components/ui/action-form';
import {saveManagementGroup} from '../user-actions';
const input='mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm';
export default async function ManagementGroups(){const session=await requireSession();assertCapability(session,'core.users.manage');const [groups,members,departmentRows]=await Promise.all([db.workTeam.findMany({where:{organisationId:session.organisationId},include:{members:{where:{isManager:true},include:{membership:{include:{user:{select:{name:true}},roles:{include:{role:true}}}}}}},orderBy:{name:'asc'}}),db.membership.findMany({where:{organisationId:session.organisationId,active:true},include:{user:{select:{name:true}}},orderBy:{user:{name:'asc'}}}),db.employee.findMany({where:{organisationId:session.organisationId,department:{not:null}},select:{department:true},distinct:['department']})]);const departments=[...new Set([...departmentRows.flatMap(d=>d.department?[d.department]:[]),...groups.flatMap(g=>g.departments)])].sort();
 const form=(group?:typeof groups[number])=><ActionForm action={saveManagementGroup} className="space-y-5"><input type="hidden" name="groupId" value={group?.id??''}/><label className="block text-xs">Group name<input name="name" required maxLength={100} defaultValue={group?.name} placeholder="Operations leadership" className={input}/></label><label className="block text-xs">Purpose<textarea name="description" maxLength={1000} defaultValue={group?.description??''} className={input}/></label><fieldset><legend className="mb-3 text-sm font-medium">Departments covered</legend><div className="grid gap-2 sm:grid-cols-2">{departments.map(d=><label key={d} className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs"><input name="department" type="checkbox" value={d} defaultChecked={group?.departments.includes(d)} className="accent-blue-600"/>{d}</label>)}</div>{!departments.length&&<p className="text-xs text-slate-500">Add departments to employee records in HR first.</p>}</fieldset><fieldset><legend className="mb-3 text-sm font-medium">Managers</legend><div className="grid gap-2 sm:grid-cols-2">{members.map(m=><label key={m.id} className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs"><input type="checkbox" name="managerId" value={m.id} defaultChecked={group?.members.some(v=>v.membershipId===m.id)} className="accent-blue-600"/>{m.user.name}</label>)}</div></fieldset><p className="text-xs leading-relaxed text-slate-500">Managers can oversee several groups and departments. Assign Team Manager permissions separately to use My Team, approvals or scheduling. Payroll permissions remain separate.</p><button className="rounded-xl bg-blue-600 px-5 py-3 text-xs font-semibold text-white">Save management group</button></ActionForm>;
 return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-blue-600">Connected leadership</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Management groups</h2><p className="mt-2 text-sm text-slate-500">One manager, several departments. Shared oversight with clear permissions.</p></div><CreateDialog title="Create a management group" label="New group">{form()}</CreateDialog></div><div className="grid gap-5 md:grid-cols-2">{groups.map(group=><section key={group.id} className="space-y-5 rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-start gap-3"><span className="rounded-xl bg-blue-50 p-3 text-blue-600"><Network size={22}/></span><div className="flex-1"><h3 className="font-semibold">{group.name}</h3><p className="mt-1 text-xs leading-relaxed text-slate-400">{group.description??group.code}</p></div><CreateDialog title={`Edit ${group.name}`} label="Edit group" variant="secondary">{form(group)}</CreateDialog></div><div><p className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wider text-slate-400"><Building2 size={13}/> Departments</p><div className="mt-3 flex flex-wrap gap-2">{group.departments.map(d=><span key={d} className="rounded-lg bg-blue-50 px-3 py-2 text-xs text-blue-600">{d}</span>)}{!group.departments.length&&<p className="text-xs text-slate-400">No department scope assigned</p>}</div></div><div className="border-t border-slate-100 pt-4"><p className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wider text-slate-400"><UserRound size={13}/> Managers</p><div className="mt-3 space-y-2">{group.members.map(m=><div key={m.membershipId}><Link href={`/settings/users/${m.membershipId}`} className="text-xs font-medium text-blue-600">{m.membership.user.name} →</Link>{(!m.membership.active||!['people.team.manage','people.employee.manage'].some(cap=>effectiveRoleCapabilities(m.membership.roles.map(r=>r.role),m.membership.grantedCapabilities,m.membership.deniedCapabilities).has(cap)))&&<p className="mt-1 text-[10px] text-amber-600">Assign management permission to enable oversight</p>}</div>)}{!group.members.length&&<p className="text-xs text-slate-400">No managers assigned</p>}</div></div></section>)}</div>{!groups.length&&<div className="rounded-2xl border border-dashed border-slate-200 bg-white p-12 text-center"><Network size={30} className="mx-auto text-blue-400"/><h3 className="mt-4 font-semibold">Bring departments together</h3><p className="mt-2 text-sm text-slate-400">Create your first management group and assign its managers.</p></div>}</div>;
}
