import Link from 'next/link';
import {draftFeedback} from '@/modules/finance/domain/draft-feedback';
import {getModule} from '@/core/modules/registry';
import {db} from '@/core/db/client';
import {requireSession} from '@/core/auth/session';
import {assertCapability} from '@/core/permissions/check';
import {financeChoices} from '@/modules/finance/services/queries';
import {documentCapability} from '@/modules/finance/services/access';
import {DOCUMENT_KINDS} from '@/modules/finance/domain/controls';
import {DocumentEditor} from '@/modules/finance/components/document-editor';
/** A purchase order started from the Inventory forecast: product, quantity and due date are filled in. */
async function prefill(organisationId:string,query:{kind?:string;product?:string;quantity?:string;suggestion?:string},kinds:string[],entity?:{id:string;currency:string}){
 if(query.suggestion&&!kinds.includes('PO'))throw new Error('Your profile cannot create purchase drafts. Ask your buyer to review this proposal.');
 if(query.suggestion&&kinds.includes('PO')&&entity){const provider=getModule('manufacturing')?.supplyPurchaseProvider;if(!provider)throw new Error('Manufacturing purchase handoff is unavailable.');const session=await requireSession();assertCapability(session,'manufacturing.plan.firm');const proposal=await provider.read(session,query.suggestion);return {mrpSuggestionId:proposal.id,mrpSuggestionVersion:proposal.version,id:'',expenseClaimId:'',projectId:'',entityId:entity.id,kind:'PO',title:`Purchase of ${proposal.productName}`,currency:entity.currency,exchangeRate:'1',documentDate:new Date().toISOString().slice(0,10),dueAt:proposal.neededBy??'',partyId:'',externalReference:'',sourceId:'',department:'',costCentre:'',site:'',category:'',reason:`MRP Buy proposal ${proposal.id}, run ${proposal.runId}: ${proposal.quantity} ${proposal.unit} of ${proposal.productCode}. Supplier and price require review.`,capex:false,recurring:false,lines:[{productId:proposal.productId,description:`${proposal.productCode} · ${proposal.productName}`,quantity:proposal.quantity,unitPrice:'0.00',taxCode:'OUTSIDE_SCOPE' as const,taxRateBps:0,accountId:'',sourceLineId:''}]};}
 if(query.kind!=='PO'||!kinds.includes('PO')||!query.product||!entity)return undefined;
 const product=await db.product.findFirst({where:{id:query.product,organisationId,active:true},select:{id:true,name:true,code:true,leadTimeDays:true,unitOfMeasure:true}});
 if(!product)return undefined;
 const quantity=Math.max(1,Math.min(1000000,Math.floor(Number(query.quantity)||1))),today=new Date(),due=new Date(today.getTime()+(product.leadTimeDays||0)*86_400_000);
 return {id:'',expenseClaimId:'',projectId:'',entityId:entity.id,kind:'PO',title:`Purchase of ${product.name}`,currency:entity.currency,exchangeRate:'1',documentDate:today.toISOString().slice(0,10),dueAt:product.leadTimeDays?due.toISOString().slice(0,10):'',partyId:'',externalReference:'',sourceId:'',department:'',costCentre:'',site:'',category:'',reason:`Raised from the Inventory forecast: ${quantity} ${product.unitOfMeasure} of ${product.code} suggested.`,capex:false,recurring:false,lines:[{productId:product.id,description:`${product.code} · ${product.name}`,quantity:String(quantity),unitPrice:'0.00',taxCode:'OUTSIDE_SCOPE' as const,taxRateBps:0,accountId:'',sourceLineId:''}]};
}
export default async function New({searchParams}:{searchParams:Promise<{kind?:string;product?:string;quantity?:string;suggestion?:string}>}){const session=await requireSession();assertCapability(session,'finance.overview.read');const query=await searchParams;const choices=await financeChoices(),kinds=DOCUMENT_KINDS.filter(k=>k!=='RECEIPT'&&session.capabilities.has(documentCapability(k,true)));let initial:Awaited<ReturnType<typeof prefill>>=undefined,prefillError='';if(choices.entities.length&&kinds.length){try{initial=await prefill(session.organisationId,query,kinds,choices.entities[0]);}catch(error){prefillError=draftFeedback(error);}}return <div className="mx-auto max-w-5xl space-y-6"><div><p className="text-xs uppercase tracking-wider text-emerald-700">Finance</p><h1 className="mt-2 text-2xl font-semibold">Create a financial document</h1><p className="mt-2 text-sm text-slate-500">Start with a draft. Approval and posting remain separate steps.</p></div>{!choices.entities.length?<p>Configure a legal entity from Finance Overview first.</p>:!kinds.length?<p>Your profile does not have document creation permission.</p>:prefillError?<div role="alert" className="space-y-3 rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm"><p>{prefillError}</p><Link href="/manufacturing/planning/planned-orders" className="font-medium text-blue-700 underline">Review the current material plan and linked documents</Link></div>:<DocumentEditor choices={choices} allowedKinds={query.suggestion?kinds.filter(k=>k==='PO'):kinds} initial={initial}/>}</div>;}
