import {requireSession} from '@/core/auth/session';
import {assertCapability,can} from '@/core/permissions/check';
import {assertModuleEnabled} from '@/core/modules/access';
import {db} from '@/core/db/client';
import {members} from '@/core/shared/operational-forms';
import {VehicleForm} from '@/modules/fleet/components/form';
import {CreateDialog} from '@/components/ui/create-dialog';
import {Heading,Panel,Empty,Stats,Row} from '@/components/operations/ui';
export default async function Page(){const s=await requireSession();assertCapability(s,'fleet.vehicle.read');await assertModuleEnabled(s,'fleet');const [vehicles,people]=await Promise.all([db.fleetVehicle.findMany({where:{organisationId:s.organisationId},orderBy:{registration:'asc'},take:201}),members(s)]),now=+new Date(),due=(date:Date|null)=>date&&+date<now+30*86400000;return <div className="space-y-6"><Heading eyebrow="Fleet" title="A clear view of every vehicle." description="Keep drivers, inspections, fuel, repairs and renewal dates with the vehicle. Unsafe inspections put vehicles off road.">{can(s,'fleet.vehicle.manage')?<CreateDialog title="Register vehicle" label="Add vehicle"><VehicleForm people={people}/></CreateDialog>:null}</Heading><Stats items={[{label:'Active vehicles',value:vehicles.filter(v=>v.status==='ACTIVE').length},{label:'Off road',value:vehicles.filter(v=>v.status==='OFF_ROAD').length},{label:'Service due within 30 days',value:vehicles.filter(v=>v.status!=='RETIRED'&&due(v.serviceDueAt)).length},{label:'MOT / insurance due',value:vehicles.filter(v=>v.status!=='RETIRED'&&(due(v.motDueAt)||due(v.insuranceDueAt))).length}]}/><Panel title="Vehicle register"><div className="space-y-3">{vehicles.slice(0,200).map(v=><Row key={v.id} href={'/fleet/'+v.id} title={v.registration+' · '+v.name} meta={`${[v.make,v.model].filter(Boolean).join(' ')} · ${v.odometer.toLocaleString()} miles · ${people.find(p=>p.userId===v.driverUserId)?.user.name??'No driver assigned'}`} status={v.status}/>)}{!vehicles.length?<Empty>Add your first vehicle, assign a driver and enter servicing, MOT and insurance dates. Then record inspections and running history on its record.</Empty>:null}</div>{vehicles.length>200?<p className="mt-4 text-xs text-slate-500">Showing the first 200 vehicles.</p>:null}</Panel></div>;}
