"use client";
import {useRef,useId,useSyncExternalStore,useState,useEffect} from "react";
import {createPortal} from "react-dom";
import {X,Plus} from "lucide-react";
const subscribe=()=>()=>{};
export function CreateDialog({title,label,children,iconOnly=false,variant='primary',trigger,triggerClassName,onOpen}:{title:string;label:string;children:React.ReactNode;iconOnly?:boolean;variant?:'primary'|'secondary';trigger?:(open:()=>void)=>React.ReactNode;triggerClassName?:string;onOpen?:()=>void}) {
 const ref=useRef<HTMLDialogElement>(null),id=useId(),mounted=useSyncExternalStore(subscribe,()=>true,()=>false);
 const [openRequest,setOpenRequest]=useState(0);
 useEffect(()=>{if(openRequest)ref.current?.showModal();},[openRequest]);
 const open=()=>{onOpen?.();setOpenRequest(value=>value+1);};
 return <>{trigger?trigger(open):<button type="button" onClick={open} aria-label={label} className={triggerClassName??(iconOnly?'flex size-10 items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-600 hover:bg-blue-50 hover:text-blue-600':variant==='secondary'?'inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-medium text-slate-600 hover:bg-slate-50':'inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-medium text-white shadow-sm hover:bg-blue-700')}>{iconOnly?<span className="grid grid-cols-3 gap-0.5">{Array.from({length:9},(_,i)=><span key={i} className="size-1 rounded-sm bg-current"/>)}</span>:triggerClassName?label:<><Plus size={16}/>{label}</>}</button>}{mounted&&createPortal(<dialog ref={ref} aria-labelledby={id} className="atlas-dialog m-auto max-h-[88vh] w-[calc(100%-2rem)] max-w-3xl overflow-y-auto rounded-[28px] border border-white/80 bg-white p-0 text-slate-900 shadow-[0_30px_80px_-36px_rgba(15,23,42,0.55)]" onClick={event=>{if(event.target===ref.current){const bounds=ref.current.getBoundingClientRect();if(event.clientX<bounds.left||event.clientX>bounds.right||event.clientY<bounds.top||event.clientY>bounds.bottom)ref.current.close();}if((event.target as HTMLElement).closest('a'))ref.current?.close();}}><div className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-100 bg-white px-6 py-5"><h2 id={id} className="text-lg font-semibold tracking-tight">{title}</h2><button type="button" onClick={()=>ref.current?.close()} aria-label="Close dialog" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X size={18}/></button></div><div className="p-6">{children}</div></dialog>,document.body)}</>;
}
