'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ActionForm } from '@/components/ui/action-form';
import { Button } from '@/components/ui/button';
import { saveTemplate } from '@/app/(app)/templates/actions';
import { MERGE_FIELDS, TARGET_MODULES, type TemplateBlock } from '@/core/templates/types';
import { merge } from '@/core/templates/domain';
export const field='mt-1 block w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm';
const starters:Record<string,{title:string;blocks:TemplateBlock[]}>= {
 blank:{title:'Document for {{customer.name}}',blocks:[{id:'intro',type:'heading',text:'Agreement'},{id:'terms',type:'text',text:'Between {{company.name}} and {{customer.name}}.\n\nAdd your agreed terms here.'},{id:'sign',type:'signature',text:'Customer acceptance'}]},
 supply:{title:'Supply agreement · {{record.name}}',blocks:[{id:'intro',type:'heading',text:'Supply agreement'},{id:'parties',type:'text',text:'This agreement is between {{company.name}} and {{customer.name}}, dated {{date.today}}.'},{id:'scope',type:'heading',text:'Scope of supply'},{id:'details',type:'text',text:'{{custom.scope}}'},{id:'pricing',type:'heading',text:'Price and payment'},{id:'price',type:'text',text:'{{custom.payment_terms}}'},{id:'delivery',type:'heading',text:'Delivery and responsibilities'},{id:'service',type:'text',text:'{{custom.delivery_terms}}'},{id:'sign',type:'signature',text:'For {{customer.name}}'}]},
 service:{title:'Service agreement · {{record.reference}}',blocks:[{id:'intro',type:'heading',text:'Service agreement'},{id:'body',type:'text',text:'Prepared by {{company.name}} for {{customer.name}}.\nReference: {{record.reference}}\nDate: {{date.today}}'},{id:'scope',type:'text',text:'{{custom.services}}'},{id:'levels',type:'text',text:'{{custom.service_levels}}'},{id:'sign',type:'signature',text:'Customer acceptance'}]},
 project:{title:'Project brief · {{record.name}}',blocks:[{id:'h',type:'heading',text:'Project brief'},{id:'intro',type:'text',text:'{{record.name}} · {{record.reference}}\nPrepared by {{company.name}} on {{date.today}}.'},{id:'scope',type:'text',text:'{{custom.scope}}'},{id:'success',type:'text',text:'{{custom.success_criteria}}'},{id:'sign',type:'signature',text:'Project approval'}]},
};
type Initial={id?:string;version?:number;name:string;description:string;category:string;titleTemplate:string;blocks:TemplateBlock[];targetModules:string[];status:string};
export function TemplateEditor({initial}:{initial?:Initial}){
 const [blocks,setBlocks]=useState<TemplateBlock[]>(initial?.blocks??starters.blank.blocks),[title,setTitle]=useState(initial?.titleTemplate??starters.blank.title),[selected,setSelected]=useState(blocks[0]?.id),[activeField,setActiveField]=useState<string>('customer.name');
 const change=(id:string,patch:Partial<TemplateBlock>)=>setBlocks(rows=>rows.map(b=>b.id===id?{...b,...patch}:b));
 const move=(index:number,delta:number)=>{const copy=[...blocks],at=index+delta;if(at<0||at>=copy.length)return;[copy[index],copy[at]]=[copy[at],copy[index]];setBlocks(copy);};
 const sample:Record<string,string>={'company.name':'Your company','customer.name':'Example customer','customer.code':'CUS-001','customer.address':'1 Example Street, London','contact.name':'Alex Taylor','contact.email':'alex@example.com','record.name':'Example deal','record.reference':'REF-001','record.value':'£12,000.00','record.currency':'GBP','record.date':'7 October 2026','date.today':'7 October 2026'};
 const preview=(text:string)=>{try{return merge(text,sample,false);}catch(e){return e instanceof Error?e.message:'Invalid field';}};
 return <ActionForm action={saveTemplate} className="space-y-5">
  <input type="hidden" name="id" value={initial?.id??''}/><input type="hidden" name="version" value={initial?.version??1}/><input type="hidden" name="blocks" value={JSON.stringify(blocks)}/>
  <div className="flex flex-wrap items-center justify-between gap-3"><div><Link href="/templates" className="text-xs text-blue-700">← Template library</Link><h2 className="mt-2 text-2xl font-semibold">{initial?'Edit template':'Build a template'}</h2><p className="mt-1 text-sm text-slate-500">Arrange sections, insert fields and publish to the apps that use this document.</p></div><Button type="submit" variant="primary">Save template</Button></div>
  {!initial&&<div className="flex flex-wrap items-center gap-2"><span className="text-xs text-slate-500">Start with</span>{Object.keys(starters).map(k=><button key={k} type="button" onClick={()=>{setBlocks(starters[k].blocks);setTitle(starters[k].title);setSelected(starters[k].blocks[0].id);}} className="rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs capitalize">{k==='blank'?'Blank':k==='supply'?'Supply agreement':k==='service'?'Service agreement':'Project brief'}</button>)}<span className="text-xs text-slate-400">Starter wording needs your review before use.</span></div>}
  <div className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 sm:grid-cols-2 xl:grid-cols-4">
   <label className="text-xs font-medium">Template name<input name="name" required maxLength={300} defaultValue={initial?.name} className={field}/></label>
   <label className="text-xs font-medium sm:col-span-2">Document title<input name="titleTemplate" required maxLength={300} value={title} onChange={e=>setTitle(e.target.value)} className={field}/></label>
   <label className="text-xs font-medium">Status<select name="status" defaultValue={initial?.status??'DRAFT'} className={field}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published · available to use</option></select></label>
   <label className="text-xs font-medium">Category<input name="category" maxLength={60} defaultValue={initial?.category??'Contract'} className={field}/></label>
   <label className="text-xs font-medium sm:col-span-2">Description<input name="description" maxLength={2000} defaultValue={initial?.description} className={field}/></label>
   <div className="text-xs font-medium">Use in apps<div className="mt-2 flex flex-wrap gap-3">{TARGET_MODULES.map(id=><label key={id} className="flex items-center gap-1 capitalize"><input name="targetModules" type="checkbox" value={id} defaultChecked={initial?initial.targetModules.includes(id):true}/>{id==='crm'?'CRM':id}</label>)}</div></div>
  </div>
  <div className="grid items-start gap-5 lg:grid-cols-2">
   <section className="space-y-3"><div className="flex flex-wrap items-end gap-2 rounded-2xl border border-slate-200 bg-white p-4"><label className="flex-1 text-xs font-medium">Insert merge field<select value={activeField} onChange={e=>setActiveField(e.target.value)} className={field}>{MERGE_FIELDS.map(k=><option key={k}>{k}</option>)}</select></label><button type="button" onClick={()=>{const b=blocks.find(b=>b.id===selected);if(b)change(b.id,{text:b.text+`{{${activeField}}}`});}} className="rounded-xl bg-blue-50 px-3 py-2.5 text-xs font-medium text-blue-700">Insert in selected section</button><p className="w-full text-xs text-slate-500">For a value filled in per document, type {'{{custom.your_field}}'}. Table columns use | and each row uses a new line.</p></div>
   {blocks.map((b,i)=><div key={b.id} onFocus={()=>setSelected(b.id)} className={`rounded-2xl border bg-white p-4 ${selected===b.id?'border-blue-400':'border-slate-200'}`}><div className="mb-3 flex items-center gap-2"><span className="text-xs text-slate-400">{i+1}</span><select aria-label={`Section ${i+1} type`} value={b.type} onChange={e=>change(b.id,{type:e.target.value as TemplateBlock['type']})} className="flex-1 rounded-lg border border-slate-200 px-2 py-1.5 text-sm">{['heading','text','bullets','table','signature','divider','pageBreak'].map(t=><option key={t} value={t}>{t==='pageBreak'?'Page break':t}</option>)}</select><button type="button" aria-label="Move section up" disabled={i===0} onClick={()=>move(i,-1)} className="px-1 disabled:opacity-20">↑</button><button type="button" aria-label="Move section down" disabled={i===blocks.length-1} onClick={()=>move(i,1)} className="px-1 disabled:opacity-20">↓</button><button type="button" onClick={()=>setBlocks([...blocks.slice(0,i+1),{...b,id:crypto.randomUUID()},...blocks.slice(i+1)])} className="text-xs text-blue-700">Copy</button><button type="button" disabled={blocks.length===1} onClick={()=>setBlocks(blocks.filter(x=>x.id!==b.id))} className="text-xs text-red-600 disabled:opacity-20">Remove</button></div>{!['divider','pageBreak'].includes(b.type)&&<textarea aria-label={`Section ${i+1} text`} value={b.text} onChange={e=>change(b.id,{text:e.target.value})} rows={b.type==='heading'?2:5} maxLength={12000} className={`${field} resize-y font-mono text-xs`}/>}</div>)}
   <button type="button" disabled={blocks.length>=80} onClick={()=>{const id=crypto.randomUUID();setBlocks([...blocks,{id,type:'text',text:''}]);setSelected(id);}} className="w-full rounded-2xl border border-dashed border-blue-200 py-3 text-sm text-blue-700">+ Add section</button></section>
   <section className="lg:sticky lg:top-24"><p className="mb-3 text-xs text-slate-500">Live preview · sample values</p><article className="min-h-[680px] rounded-xl border border-slate-200 bg-white p-8 shadow-sm"><p className="text-xs font-semibold uppercase tracking-widest text-blue-600">Your company</p><h1 className="my-6 text-2xl font-semibold">{preview(title)}</h1>{blocks.map(b=><div key={b.id} className="mb-5">{b.type==='heading'?<h2 className="text-lg font-semibold">{preview(b.text)}</h2>:b.type==='divider'?<hr/>:b.type==='pageBreak'?<p className="border-t border-dashed pt-2 text-xs text-slate-400">Page break</p>:b.type==='signature'?<div className="space-y-5 text-sm"><p>{preview(b.text)}</p><p>Name: ____________________</p><p>Signature: _________________ &nbsp; Date: _________</p></div>:b.type==='table'?<table className="w-full text-sm"><tbody>{preview(b.text).split('\n').map((r,i)=><tr key={i}>{r.split('|').map((c,j)=><td key={j} className="border border-slate-200 p-2">{c}</td>)}</tr>)}</tbody></table>:<p className="whitespace-pre-wrap text-sm leading-7 text-slate-600">{preview(b.text)}</p>}</div>)}</article><p className="mt-3 text-xs text-slate-500">Existing documents keep the template version used when they were created.</p></section>
  </div>
 </ActionForm>;
}
